### PR TITLE
Fixes for User Profile Synchronization with Multiple OUs, and for User Property + Added SPSecurityTokenServiceConfig resource

### PR DESCRIPTION
**Pull request by NikCharlebois**
Multiple changes to fix issues with the user profile bits that have been around since the beginning

- [ ] Change details added to Unreleased section of changelog.md?
- [ ] Added/updated documentation and descriptions in .schema.mof files where appropriate?
- [ ] Examples updated for both the single server and small farm templates in the examples folder?
- [ ] New/changed code adheres to [Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md)?
- [ ] [Unit and Integration tests](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md) created/updated where possible?

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/sharepointdsc/721)

Issue #673

### CODE REVIEW

**Comment by NikCharlebois** [comment]
@ykuijs I will need you help on this one buddy. Looks like they changed the rules once again. The first error I had said that bulleted list had to have an empty line on top, and one under, which I fixed in the Changelog. Now the error says that bulleted list should start at the top.....

**Comment by ykuijs** [comment]
Linking to issue #673 

Will review this PR shortly

**Comment by ykuijs** [comment]
PR #729 also included this new resource, so my review comments in that PR are also valid for this PR

---

Review status: 0 of 11 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/721#-:-L325iF_cllsjSZo9odN:b-cyoylh)*

**Comment by ykuijs** [comment]
@NikCharlebois Since this is included in PR 729, can we close this PR??

**Comment by NikCharlebois** [comment]
Yep

**Pull request closed without merging**
