### PR TITLE
Integration test framework first cut

### PR DESCRIPTION
**Pull request by BrianFarnhill**
This is a first cut of the integration test framework I've put together (I've had this kicking around a while, just never got around to publishing). Some points here:

1. I need to write doco on the requirements and process for running them, this will go in to a wiki page that I'll publish here before we merge this PR
2. We don't cover all of our modules at this point - I've just got a few of the key ones in there as a starting point to show how it is meant to work
3. The integration tests should be able to run on both SP2013 and SP2016
4. We restructured the folders for unit and integration tests to line up with the rest of the other DSC resources. 

While I want this merged in to the main code based before the 1.2 release, I wont start enforcing that all new code requires these integration tests until we catch them up and complete that work. By having them there now though and starting on the doco we can let people start to understand it before we make it mandatory.

So really what I'm after at this point is a code review of what's there. :)

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/sharepointdsc/358)

### CODE REVIEW

**Comment by BrianFarnhill** [comment]
I'm seeing an issue where the app catalog tests are failing - I suspect it's because the app management service isn't done yet (which if that is a thing, we should make sure that is a thing in the resource rather than let it error out with the random error I'm seeing). Outside of that the other integration tests are all clean.

**Comment by ykuijs** [comment]
Hi Brian, it all looks good. One question though (Just for my understanding):
What is the goal of these tests and how are they ran? Will this run by Github against a VM with SharePoint installed??

In other words: Do you have a more conceptual overview/description/etc :-)

---

Reviewed 164 of 171 files at r1, 3 of 3 files at r2.
Review status: 92 of 95 files reviewed at latest revision, 6 unresolved discussions.

---

*[Tests/Integration/PreflightChecks/Preflight.Tests.ps1, line 71 \[r2\]](https://reviewable.io:443/reviews/powershell/sharepointdsc/358#-KLu3U2u7UH08dpQibTE:-KLu3U2u7UH08dpQibTF:1058500886) ([raw file](https://github.com/powershell/sharepointdsc/blob/81c49944e8a3975afc68c33b30fe6af9aadc15bb/Tests/Integration/PreflightChecks/Preflight.Tests.ps1#L71)):*
> ```PowerShell
>     }
> 
>     it "Has the SharePoint installed" {
> ```

"the" should not be in here

---

*[Tests/Unit/Generate-SPDscHelpFiles.ps1, line 13 \[r2\]](https://reviewable.io:443/reviews/powershell/sharepointdsc/358#-KLu4zdweVQ28VvvIlPv:-KLu4zdweVQ28VvvIlPw:-2112824077) ([raw file](https://github.com/powershell/sharepointdsc/blob/81c49944e8a3975afc68c33b30fe6af9aadc15bb/Tests/Unit/Generate-SPDscHelpFiles.ps1#L13)):*
> ```PowerShell
>     ForEach-Object {
>         $mofFileObject = $_ 
>         $result = (Get-MofSchemaObject $_.FullName) | Where-Object { $_.ClassName -eq $mofFileObject.Name.Replace(".schema.mof", "") -and $_.FriendlyName -ne $null }
> ```

Shouldn't $null be on the other side?

---

*[Tests/Unit/Generate-SPDscHelpFiles.ps1, line 14 \[r2\]](https://reviewable.io:443/reviews/powershell/sharepointdsc/358#-KLu4voSdla8FZfvM2Zm:-KLu4voSdla8FZfvM2Zn:-2112824077) ([raw file](https://github.com/powershell/sharepointdsc/blob/81c49944e8a3975afc68c33b30fe6af9aadc15bb/Tests/Unit/Generate-SPDscHelpFiles.ps1#L14)):*
> ```PowerShell
>         $mofFileObject = $_ 
>         $result = (Get-MofSchemaObject $_.FullName) | Where-Object { $_.ClassName -eq $mofFileObject.Name.Replace(".schema.mof", "") -and $_.FriendlyName -ne $null }
>         if ($result -ne $null) {
> ```

Shouldn't $null be on the other side?

---

*[Tests/Unit/Generate-SPDscWikiPages.ps1, line 13 \[r2\]](https://reviewable.io:443/reviews/powershell/sharepointdsc/358#-KLu53ikw3-i6Cvj9BO5:-KLu53ikw3-i6Cvj9BO6:-2112824077) ([raw file](https://github.com/powershell/sharepointdsc/blob/81c49944e8a3975afc68c33b30fe6af9aadc15bb/Tests/Unit/Generate-SPDscWikiPages.ps1#L13)):*
> ```PowerShell
>     ForEach-Object { 
>         $mofFileObject = $_
>         $result = (Get-MofSchemaObject $_.FullName) | Where-Object { $_.ClassName -eq $mofFileObject.Name.Replace(".schema.mof", "") -and $_.FriendlyName -ne $null }
> ```

Shouldn't $null be on the other side?

---

*[Tests/Unit/SharePointDsc/SharePointDsc.SPUserProfileSyncService.Tests.ps1, line 46 \[r2\]](https://reviewable.io:443/reviews/powershell/sharepointdsc/358#-KLu6KYEawP-I1qiQTJC:-KLu6KYEawP-I1qiQTJD:1783627771) ([raw file](https://github.com/powershell/sharepointdsc/blob/81c49944e8a3975afc68c33b30fe6af9aadc15bb/Tests/Unit/SharePointDsc/SharePointDsc.SPUserProfileSyncService.Tests.ps1#L46)):*
> ```PowerShell
>         Mock Remove-SPDSCUserToLocalAdmin { }
>         Mock New-PSSession { return $null } -ModuleName "SharePointDsc.Util"
>         Mock Start-Sleep { }
> ```

Why is the Mock for Get-SPServiceApplication removed? What does this have to do with the Integration Test addition??

---

*[Tests/Unit/SharePointDsc/SharePointDsc.SPUserProfileSyncService.Tests.ps1, line 189 \[r2\]](https://reviewable.io:443/reviews/powershell/sharepointdsc/358#-KLu6Sa5C3nv-t1n5Yo0:-KLu6Sa5C3nv-t1n5Yo1:-628736958) ([raw file](https://github.com/powershell/sharepointdsc/blob/81c49944e8a3975afc68c33b30fe6af9aadc15bb/Tests/Unit/SharePointDsc/SharePointDsc.SPUserProfileSyncService.Tests.ps1#L189)):*
> ```PowerShell
> 
>                     It "returns true from the test method" {
>                         Test-TargetResource @testParams | Should Be $true
> ```

Why are these tests removed? What does this have to do with the Integration Test addition??

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/358#-:-KLu6aKIzJ8DL7YKv-q8:566744570)*

**Comment by BrianFarnhill** [comment]
Reviewed 170 of 171 files at r1, 3 of 3 files at r2, 5 of 5 files at r3.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[Tests/Unit/SharePointDsc/SharePointDsc.SPUserProfileSyncService.Tests.ps1, line 46 \[r2\]](https://reviewable.io:443/reviews/powershell/sharepointdsc/358#-KLu6KYEawP-I1qiQTJC:-KLuLBGqdnDGbj3wUsKM:1684301794) ([raw file](https://github.com/powershell/sharepointdsc/blob/81c49944e8a3975afc68c33b30fe6af9aadc15bb/Tests/Unit/SharePointDsc/SharePointDsc.SPUserProfileSyncService.Tests.ps1#L46)):*
<details><summary><i>Previously, ykuijs (Yorick Kuijs) wrote…</i></summary>
> Why is the Mock for Get-SPServiceApplication removed? What does this have to do with the Integration Test addition??
</details>
No idea what I did here - I had some issues with some of the tests after I screwed up the move - I fixed it though, nice catch

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/358)*

**Comment by ykuijs** [comment]
Reviewed 3 of 171 files at r1, 5 of 5 files at r3.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/358)*

**Comment by BrianFarnhill** [comment]
To respond to the other question - the goal is to give everyone (us included) a consistent set of tests to run against actual SharePoint servers to validate functionality beyond the unit tests. They wont run in AppVeyor (takes too long to install SharePoint and the reboots freak it out) but we can manually run them to validate things before merging branches in to dev and before releasing. 

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/358#-:-KLuPYbPKKwTYULInZ_E:-701485034)*

**Pull request merged**
