### PR TITLE
Another bugfix rollup

### PR DESCRIPTION
**Pull request by ykuijs**
Bugfixes for issues #540, #558, #561, #580, #587, #589, #594, #596 

- [X] Change details added to Unreleased section of changelog.md?
- [X] Added/updated documentation and descriptions in .schema.mof files where appropriate?
- [X] Examples updated for both the single server and small farm templates in the examples folder?
- [X] New/changed code adheres to [Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md)?
- [X] [Unit and Integration tests](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md) created/updated where possible?

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/sharepointdsc/600)

### CODE REVIEW

**Comment by BrianFarnhill** [comment]
Done most of the review, didn't get time to do the tests though. Will get to those this afternoon but here is what I started with. 

---

Reviewed 9 of 14 files at r1, 2 of 4 files at r2.
Review status: 11 of 15 files reviewed at latest revision, 8 unresolved discussions.

---

*[CHANGELOG.md, line 13 at r2](https://reviewable.io:443/reviews/powershell/sharepointdsc/600#-KkrMCwIVS3zBe6CHYwk:-KkrMCwIVS3zBe6CHYwl:blhw2x1) ([raw file](https://github.com/powershell/sharepointdsc/blob/14e15f537890c372642daf6794c25aa0114c1d0f/CHANGELOG.md#L13)):*
> ```Markdown
> * Fixed missing brackets in error message in SPExcelServiceApp
> * Removed the requirement for the ConfigWizard in SPInstallLanguagePack
> * Fixed LP detection issue in SPInstallLanguagePack
> ```

Can we say "Language pack" instead of LP - I don't think it's a widely used acronym here so just want to be clear

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPDesignerSettings/MSFT_SPDesignerSettings.psm1, line 123 at r2](https://reviewable.io:443/reviews/powershell/sharepointdsc/600#-KkrMKKMeuPEhOcQA6Fr:-KkrMKKMeuPEhOcQA6Fs:b880tzq) ([raw file](https://github.com/powershell/sharepointdsc/blob/14e15f537890c372642daf6794c25aa0114c1d0f/Modules/SharePointDsc/DSCResources/MSFT_SPDesignerSettings/MSFT_SPDesignerSettings.psm1#L123)):*
> ```PowerShell
> 
>                     # Check if site collections exists
>                     $site = Get-SPSite $params.Url -ErrorAction SilentlyContinue
> ```

Positional parameter - should be as follows

    $site = Get-SPSite -Identity $params.Url -ErrorAction SilentlyContinue

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPDesignerSettings/MSFT_SPDesignerSettings.psm1, line 302 at r2](https://reviewable.io:443/reviews/powershell/sharepointdsc/600#-KkrMfKSWW0TSjdU0lZY:-KkrMfKTc4ynQ09Y_IXQ:b-yz9dhk) ([raw file](https://github.com/powershell/sharepointdsc/blob/14e15f537890c372642daf6794c25aa0114c1d0f/Modules/SharePointDsc/DSCResources/MSFT_SPDesignerSettings/MSFT_SPDesignerSettings.psm1#L302)):*
> ```PowerShell
> 
>                     # Check if site collection exists
>                     $site = Get-SPSite $params.Url -ErrorAction SilentlyContinue
> ```

Same again on the positional parameter

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPInstall/Readme.md, line 10 at r2](https://reviewable.io:443/reviews/powershell/sharepointdsc/600#-KkrMmWh-vTl8kHvr4vF:-KkrMmWh-vTl8kHvr4vG:bofsfwn) ([raw file](https://github.com/powershell/sharepointdsc/blob/14e15f537890c372642daf6794c25aa0114c1d0f/Modules/SharePointDsc/DSCResources/MSFT_SPInstall/Readme.md#L10)):*
> ```Markdown
> 
> NOTE: This resource only supports SharePoint Server. SharePoint Foundation
> is not supported.
> ```

Can we add a link to the wiki here that has the package example, so its a "we don't support it, but here's another way to do it" kind of story?

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPInstallLanguagePack/MSFT_SPInstallLanguagePack.psm1, line 46 at r2](https://reviewable.io:443/reviews/powershell/sharepointdsc/600#-KkrNRbz1I2hcn5JBfPM:-KkrNRbz1I2hcn5JBfPN:b-duf2tl) ([raw file](https://github.com/powershell/sharepointdsc/blob/14e15f537890c372642daf6794c25aa0114c1d0f/Modules/SharePointDsc/DSCResources/MSFT_SPInstallLanguagePack/MSFT_SPInstallLanguagePack.psm1#L46)):*
> ```PowerShell
>     }
> 
>     $products = Get-SPDscRegProductsInfo
> ```

This is just a sanity check more than anything - so we are taking the Invoke-SPDSCCommand off this one, that's becuase we don't need it though right? Looking at the Get-SPDscRegProductsInfo command we are just checking the registry. Have I got that one right?

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPOutgoingEmailSettings/MSFT_SPOutgoingEmailSettings.psm1, line 44 at r2](https://reviewable.io:443/reviews/powershell/sharepointdsc/600#-KkrNrsHNRbWaNen6Uhj:-KkrNrsIWWDlAsi5EeQS:b4uaz3l) ([raw file](https://github.com/powershell/sharepointdsc/blob/14e15f537890c372642daf6794c25aa0114c1d0f/Modules/SharePointDsc/DSCResources/MSFT_SPOutgoingEmailSettings/MSFT_SPOutgoingEmailSettings.psm1#L44)):*
> ```PowerShell
>     $installedVersion = Get-SPDSCInstalledProductVersion
>     if (($PSBoundParameters.ContainsKey("UseTLS") -eq $true) `
>         -and $installedVersion.FileMajorPart -ne 16) 
> ```

Rather than "not equals 16" can we change it to "less than 16" so that way if/when a newer version comes along it will just work?

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPOutgoingEmailSettings/MSFT_SPOutgoingEmailSettings.schema.mof, line 9 at r2](https://reviewable.io:443/reviews/powershell/sharepointdsc/600#-KkrOW0lq_mQNpnO_zex:-KkrOW0mvTm-HQA7ykMG:btz44mo) ([raw file](https://github.com/powershell/sharepointdsc/blob/14e15f537890c372642daf6794c25aa0114c1d0f/Modules/SharePointDsc/DSCResources/MSFT_SPOutgoingEmailSettings/MSFT_SPOutgoingEmailSettings.schema.mof#L9)):*
> ```
>     [Required, Description("The email address that replies should be directed to")] string ReplyToAddress;
>     [Required, Description("The character set to use on messages")] string CharacterSet;
>     [Write, Description("Use TLS when connecting to the SMTP server")] boolean UseTLS;
> ```

Can we add "(SharePoint 2016 only)" to the descriptions here so it gets included in the doco like that?

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPWebApplication/MSFT_SPWebApplication.psm1, line 249 at r2](https://reviewable.io:443/reviews/powershell/sharepointdsc/600#-KkrOkMAcRTb2khZkcYu:-KkrOkMAcRTb2khZkcYv:b2ollfm) ([raw file](https://github.com/powershell/sharepointdsc/blob/14e15f537890c372642daf6794c25aa0114c1d0f/Modules/SharePointDsc/DSCResources/MSFT_SPWebApplication/MSFT_SPWebApplication.psm1#L249)):*
> ```PowerShell
>                     try 
>                     {
>                         $null = Get-SPManagedAccount $params.ApplicationPoolAccount -ErrorAction Stop
> ```

We can pipe to Out-Null to swallow an output rather than assigning to a variable

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/600#-:-KkrPG8iz4eyaSTk-_6y:b9hju27)*

**Comment by ykuijs** [comment]
Review status: 11 of 15 files reviewed at latest revision, 8 unresolved discussions.

---

*[CHANGELOG.md, line 13 at r2](https://reviewable.io:443/reviews/powershell/sharepointdsc/600#-KkrMCwIVS3zBe6CHYwk:-KktZ-4fxoDSJtZed02-:b-896fix) ([raw file](https://github.com/powershell/sharepointdsc/blob/14e15f537890c372642daf6794c25aa0114c1d0f/CHANGELOG.md#L13)):*
<details><summary><i>Previously, BrianFarnhill (Brian Farnhill) wrote…</i></summary><blockquote>

Can we say "Language pack" instead of LP - I don't think it's a widely used acronym here so just want to be clear
</blockquote></details>

Done.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPDesignerSettings/MSFT_SPDesignerSettings.psm1, line 123 at r2](https://reviewable.io:443/reviews/powershell/sharepointdsc/600#-KkrMKKMeuPEhOcQA6Fr:-KktZA8RVCK2sRuM-IQ9:b-896fix) ([raw file](https://github.com/powershell/sharepointdsc/blob/14e15f537890c372642daf6794c25aa0114c1d0f/Modules/SharePointDsc/DSCResources/MSFT_SPDesignerSettings/MSFT_SPDesignerSettings.psm1#L123)):*
<details><summary><i>Previously, BrianFarnhill (Brian Farnhill) wrote…</i></summary><blockquote>

Positional parameter - should be as follows

    $site = Get-SPSite -Identity $params.Url -ErrorAction SilentlyContinue
</blockquote></details>

Done.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPDesignerSettings/MSFT_SPDesignerSettings.psm1, line 302 at r2](https://reviewable.io:443/reviews/powershell/sharepointdsc/600#-KkrMfKSWW0TSjdU0lZY:-KktZB93fY4dj3HozLtv:b-896fix) ([raw file](https://github.com/powershell/sharepointdsc/blob/14e15f537890c372642daf6794c25aa0114c1d0f/Modules/SharePointDsc/DSCResources/MSFT_SPDesignerSettings/MSFT_SPDesignerSettings.psm1#L302)):*
<details><summary><i>Previously, BrianFarnhill (Brian Farnhill) wrote…</i></summary><blockquote>

Same again on the positional parameter
</blockquote></details>

Done.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPInstall/Readme.md, line 10 at r2](https://reviewable.io:443/reviews/powershell/sharepointdsc/600#-KkrMmWh-vTl8kHvr4vF:-KktZgyEd1EYCMg5hMv2:b-896fix) ([raw file](https://github.com/powershell/sharepointdsc/blob/14e15f537890c372642daf6794c25aa0114c1d0f/Modules/SharePointDsc/DSCResources/MSFT_SPInstall/Readme.md#L10)):*
<details><summary><i>Previously, BrianFarnhill (Brian Farnhill) wrote…</i></summary><blockquote>

Can we add a link to the wiki here that has the package example, so its a "we don't support it, but here's another way to do it" kind of story?
</blockquote></details>

Done.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPInstallLanguagePack/MSFT_SPInstallLanguagePack.psm1, line 46 at r2](https://reviewable.io:443/reviews/powershell/sharepointdsc/600#-KkrNRbz1I2hcn5JBfPM:-KktZi_iuIQuJmj7WTvw:bgie51r) ([raw file](https://github.com/powershell/sharepointdsc/blob/14e15f537890c372642daf6794c25aa0114c1d0f/Modules/SharePointDsc/DSCResources/MSFT_SPInstallLanguagePack/MSFT_SPInstallLanguagePack.psm1#L46)):*
<details><summary><i>Previously, BrianFarnhill (Brian Farnhill) wrote…</i></summary><blockquote>

This is just a sanity check more than anything - so we are taking the Invoke-SPDSCCommand off this one, that's becuase we don't need it though right? Looking at the Get-SPDscRegProductsInfo command we are just checking the registry. Have I got that one right?
</blockquote></details>

Correct, we don't need to use other credentials to request registry keys. It only adds overhead.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPOutgoingEmailSettings/MSFT_SPOutgoingEmailSettings.psm1, line 44 at r2](https://reviewable.io:443/reviews/powershell/sharepointdsc/600#-KkrNrsHNRbWaNen6Uhj:-Kkt_1oMS-NYOYS3X5nv:b-896fix) ([raw file](https://github.com/powershell/sharepointdsc/blob/14e15f537890c372642daf6794c25aa0114c1d0f/Modules/SharePointDsc/DSCResources/MSFT_SPOutgoingEmailSettings/MSFT_SPOutgoingEmailSettings.psm1#L44)):*
<details><summary><i>Previously, BrianFarnhill (Brian Farnhill) wrote…</i></summary><blockquote>

Rather than "not equals 16" can we change it to "less than 16" so that way if/when a newer version comes along it will just work?
</blockquote></details>

Done.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPOutgoingEmailSettings/MSFT_SPOutgoingEmailSettings.schema.mof, line 9 at r2](https://reviewable.io:443/reviews/powershell/sharepointdsc/600#-KkrOW0lq_mQNpnO_zex:-Kkt_AVDFFDNUd8aocFb:b-896fix) ([raw file](https://github.com/powershell/sharepointdsc/blob/14e15f537890c372642daf6794c25aa0114c1d0f/Modules/SharePointDsc/DSCResources/MSFT_SPOutgoingEmailSettings/MSFT_SPOutgoingEmailSettings.schema.mof#L9)):*
<details><summary><i>Previously, BrianFarnhill (Brian Farnhill) wrote…</i></summary><blockquote>

Can we add "(SharePoint 2016 only)" to the descriptions here so it gets included in the doco like that?
</blockquote></details>

Done.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPWebApplication/MSFT_SPWebApplication.psm1, line 249 at r2](https://reviewable.io:443/reviews/powershell/sharepointdsc/600#-KkrOkMAcRTb2khZkcYu:-Kkt_XIA0dOxLbkDCMLg:b-896fix) ([raw file](https://github.com/powershell/sharepointdsc/blob/14e15f537890c372642daf6794c25aa0114c1d0f/Modules/SharePointDsc/DSCResources/MSFT_SPWebApplication/MSFT_SPWebApplication.psm1#L249)):*
<details><summary><i>Previously, BrianFarnhill (Brian Farnhill) wrote…</i></summary><blockquote>

We can pipe to Out-Null to swallow an output rather than assigning to a variable
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/600)*

**Comment by ykuijs** [comment]
Also included fix for issue #601

**Comment by BrianFarnhill** [comment]
:lgtm:

---

Reviewed 2 of 14 files at r1, 2 of 4 files at r2, 6 of 6 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/600#-:-KkwW3UyCkTKoErHs_VG:bnfp4nl)*

**Pull request merged**
