### PR TITLE
Fixed issue with Mount function not being able to be called

### PR DESCRIPTION
**Pull request by ykuijs**
Fixed issue with Mount function not being able to be called. Also updated the code in this module according to the code guidelines.

- [X] Change details added to Unreleased section of changelog.md?
- [X] Added/updated documentation and descriptions in .schema.mof files where appropriate?
- [X] Examples updated for both the single server and small farm templates in the examples folder?
- [X] New/changed code adheres to [Style Guidelines]?(https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md)?
- [X] [Unit and Integration tests](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md) created/updated where possible?

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/sharepointdsc/370)

### CODE REVIEW

**Comment by BrianFarnhill** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[CHANGELOG.md, line 12 \[r1\]](https://reviewable.io:443/reviews/powershell/sharepointdsc/370#-KMaKO3-6ugAQB2x5cHx:-KMaKO30A5nEu1gjBsX6:310538760) ([raw file](https://github.com/powershell/sharepointdsc/blob/6b2405f65faf9a79b34640921f9bb5fba4ed399e/CHANGELOG.md#L12)):*
> ```Markdown
>  * Added support for NetBIOS domain names resolution to SPUserProfileServiceApp
>  * Removed chocolatey from the AppVeyor build process in favour of the PowerShell Gallery build of Pester
>  * Fixed bug with function not being found, since it was called from an Invoke-SPDSCCommand but not declared. 
> ```

Can you say which resource this related to here - like "Fixed a bug in SPContentDatabase that caused it to not function correctly" or something like that.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPContentDatabase/MSFT_SPContentDatabase.psm1, line 23 \[r1\]](https://reviewable.io:443/reviews/powershell/sharepointdsc/370#-KMaMlen0QfRfXoxh3S2:-KMaMlen0QfRfXoxh3S3:686546637) ([raw file](https://github.com/powershell/sharepointdsc/blob/6b2405f65faf9a79b34640921f9bb5fba4ed399e/Modules/SharePointDsc/DSCResources/MSFT_SPContentDatabase/MSFT_SPContentDatabase.psm1#L23)):*
> ```PowerShell
>         
>         $cdb = Get-SPDatabase | Where-Object -FilterScript `
>                                 { $_.Type -eq "Content Database" -and $_.Name -eq $params.Name }
> ```

You don't need to drop the { to a new line here for styling because it's a script block parameter to FilterScript. I would be formatting this like the below:

    $cdb = Get-SPDatabase | Where-Object -FilterScript {
        $_.Type -eq "Content Database" -and $_.Name -eq $params.Name 
    }

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPContentDatabase/MSFT_SPContentDatabase.psm1, line 89 \[r1\]](https://reviewable.io:443/reviews/powershell/sharepointdsc/370#-KMaP0GyYGBg4TdMp-4R:-KMaP0GyYGBg4TdMp-4S:-1715722797) ([raw file](https://github.com/powershell/sharepointdsc/blob/6b2405f65faf9a79b34640921f9bb5fba4ed399e/Modules/SharePointDsc/DSCResources/MSFT_SPContentDatabase/MSFT_SPContentDatabase.psm1#L89)):*
> ```PowerShell
>         $params = $args[0]
> 
>         function MountContentDatabase()
> ```

Should we drop this in to a separate child module like we've done with the web app stuff? Just to clean the code up a little

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPContentDatabase/MSFT_SPContentDatabase.psm1, line 89 \[r1\]](https://reviewable.io:443/reviews/powershell/sharepointdsc/370#-KMaPC21XplgxOYNolkl:-KMaPC21XplgxOYNolkm:265000188) ([raw file](https://github.com/powershell/sharepointdsc/blob/6b2405f65faf9a79b34640921f9bb5fba4ed399e/Modules/SharePointDsc/DSCResources/MSFT_SPContentDatabase/MSFT_SPContentDatabase.psm1#L89)):*
> ```PowerShell
>         $params = $args[0]
> 
>         function MountContentDatabase()
> ```

Can we change the name of this to follow our function naming standards - so "Mount-SPDscContentDatabase"

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPContentDatabase/MSFT_SPContentDatabase.psm1, line 93 \[r1\]](https://reviewable.io:443/reviews/powershell/sharepointdsc/370#-KMaPcueJqrg0bu8AAHF:-KMaPcueJqrg0bu8AAHG:493672186) ([raw file](https://github.com/powershell/sharepointdsc/blob/6b2405f65faf9a79b34640921f9bb5fba4ed399e/Modules/SharePointDsc/DSCResources/MSFT_SPContentDatabase/MSFT_SPContentDatabase.psm1#L93)):*
> ```PowerShell
>             param
>             (
>                 $params,
> ```

Can we add proper parameter attributes to these to identify that they are mandatory and their types?

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPContentDatabase/MSFT_SPContentDatabase.psm1, line 152 \[r1\]](https://reviewable.io:443/reviews/powershell/sharepointdsc/370#-KMaTNtQuRzVnmsmBFSC:-KMaTNtQuRzVnmsmBFSD:-1610208534) ([raw file](https://github.com/powershell/sharepointdsc/blob/7057b7ce3f441906202ca26c28ae4684aa1483dc/Modules/SharePointDsc/DSCResources/MSFT_SPContentDatabase/MSFT_SPContentDatabase.psm1#L152)):*
> ```PowerShell
> 
>     if ($CurrentValues.DatabaseServer -ne $DatabaseServer) {
>         Write-Verbose -Verbose "Specified database server does not match the actual database server. This resource cannot move the database to a different SQL instance."
> ```

Can you split the string over two lines here to get this line under 100 characters long?

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPContentDatabase/MSFT_SPContentDatabase.psm1, line 161 \[r1\]](https://reviewable.io:443/reviews/powershell/sharepointdsc/370#-KMaO5YFTAmtGQxN4dJE:-KMaO5YFTAmtGQxN4dJF:761366774) ([raw file](https://github.com/powershell/sharepointdsc/blob/6b2405f65faf9a79b34640921f9bb5fba4ed399e/Modules/SharePointDsc/DSCResources/MSFT_SPContentDatabase/MSFT_SPContentDatabase.psm1#L161)):*
> ```PowerShell
>         # Use Get-SPDatabase instead of Get-SPContentDatabase because the Get-SPContentDatabase does not return disabled databases.
>         $cdb = Get-SPDatabase | Where-Object -FilterScript `
>                                     { $_.Type -eq "Content Database" -and $_.Name -eq $params.Name }
> ```

Same comment here about formatting the filter script stuff 

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPContentDatabase/MSFT_SPContentDatabase.psm1, line 166 \[r1\]](https://reviewable.io:443/reviews/powershell/sharepointdsc/370#-KMaO0HXzVcnFLoPP6gV:-KMaO0HY9fKO-5k5CWwr:761366774) ([raw file](https://github.com/powershell/sharepointdsc/blob/6b2405f65faf9a79b34640921f9bb5fba4ed399e/Modules/SharePointDsc/DSCResources/MSFT_SPContentDatabase/MSFT_SPContentDatabase.psm1#L166)):*
> ```PowerShell
>             # Check if specified web application exists and throw exception when this is not the case
>             $webapp = Get-SPWebApplication | Where-Object -FilterScript `
>                                     { $_.Url.Trim("/") -eq $params.WebAppUrl.Trim("/") }
> ```

Same comment here about formatting the filter script stuff 

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPContentDatabase/MSFT_SPContentDatabase.psm1, line 175 \[r1\]](https://reviewable.io:443/reviews/powershell/sharepointdsc/370#-KMaNaG5sBzySLubESdc:-KMaNaG5sBzySLubESdd:1789427455) ([raw file](https://github.com/powershell/sharepointdsc/blob/6b2405f65faf9a79b34640921f9bb5fba4ed399e/Modules/SharePointDsc/DSCResources/MSFT_SPContentDatabase/MSFT_SPContentDatabase.psm1#L175)):*
> ```PowerShell
>             if ($null -ne $cdb) {
>                 if ($cdb.Server -ne $params.DatabaseServer) {
>                     throw "Specified database server does not match the actual database server." + `
> ```

This will throw an error because the string gets seen as two parameters - you need to wrap it in () so it gets processed as two strings that are combined instead of something else, so like this

    throw ("first part of error " + `
           "second part of error")

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/370)*

**Comment by ykuijs** [comment]
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPContentDatabase/MSFT_SPContentDatabase.psm1, line 89 \[r1\]](https://reviewable.io:443/reviews/powershell/sharepointdsc/370#-KMaP0GyYGBg4TdMp-4R:-KMcG76zaLb4B8yO8Med:-892989021) ([raw file](https://github.com/powershell/sharepointdsc/blob/6b2405f65faf9a79b34640921f9bb5fba4ed399e/Modules/SharePointDsc/DSCResources/MSFT_SPContentDatabase/MSFT_SPContentDatabase.psm1#L89)):*
<details><summary><i>Previously, BrianFarnhill (Brian Farnhill) wrote…</i></summary>
> Should we drop this in to a separate child module like we've done with the web app stuff? Just to clean the code up a little
</details>
Agree with the comment, but where to? Do you mean move it to the utils module? I chose not to do that, since this function is only used in this module.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPContentDatabase/MSFT_SPContentDatabase.psm1, line 93 \[r1\]](https://reviewable.io:443/reviews/powershell/sharepointdsc/370#-KMaPcueJqrg0bu8AAHF:-KMcHif381uwb0OXymSw:-1142625091) ([raw file](https://github.com/powershell/sharepointdsc/blob/6b2405f65faf9a79b34640921f9bb5fba4ed399e/Modules/SharePointDsc/DSCResources/MSFT_SPContentDatabase/MSFT_SPContentDatabase.psm1#L93)):*
<details><summary><i>Previously, BrianFarnhill (Brian Farnhill) wrote…</i></summary>
> Can we add proper parameter attributes to these to identify that they are mandatory and their types?
</details>
When I add these attributes to the function in the current location, VS Code starts complaining that the Get and Test methods don't have these parameters. Any suggestions?

Might not be necessary if we decide to move the function to a different location.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/370)*

**Comment by BrianFarnhill** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPContentDatabase/MSFT_SPContentDatabase.psm1, line 89 \[r1\]](https://reviewable.io:443/reviews/powershell/sharepointdsc/370#-KMaP0GyYGBg4TdMp-4R:-KMcqXejimlMGwWcJWOp:811951258) ([raw file](https://github.com/powershell/sharepointdsc/blob/6b2405f65faf9a79b34640921f9bb5fba4ed399e/Modules/SharePointDsc/DSCResources/MSFT_SPContentDatabase/MSFT_SPContentDatabase.psm1#L89)):*
<details><summary><i>Previously, ykuijs (Yorick Kuijs) wrote…</i></summary>
> Agree with the comment, but where to? Do you mean move it to the utils module? I chose not to do that, since this function is only used in this module.
</details>
No I mean a new sub-module - so at /Modules/SPContentDatabase/SPContentDatabase.psm1 or something like that

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPContentDatabase/MSFT_SPContentDatabase.psm1, line 93 \[r1\]](https://reviewable.io:443/reviews/powershell/sharepointdsc/370#-KMaPcueJqrg0bu8AAHF:-KMcqhv_mtVc9UWEX8X9:807176039) ([raw file](https://github.com/powershell/sharepointdsc/blob/6b2405f65faf9a79b34640921f9bb5fba4ed399e/Modules/SharePointDsc/DSCResources/MSFT_SPContentDatabase/MSFT_SPContentDatabase.psm1#L93)):*
<details><summary><i>Previously, ykuijs (Yorick Kuijs) wrote…</i></summary>
> When I add these attributes to the function in the current location, VS Code starts complaining that the Get and Test methods don't have these parameters. Any suggestions?
> 
> Might not be necessary if we decide to move the function to a different location.
</details>
If we move this as above then it wont matter.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/370)*

**Comment by ykuijs** [comment]
See that tests have failed. Will fix this tomorrow.

**Comment by ykuijs** [comment]
@BrianFarnhill, any suggestion: Now that I have moved the function to its own module, isn't the Mock for Mount-SPContentDatabase in the Pester test picked up anymore. Which is why the test is failing :-(

**Comment by BrianFarnhill** [comment]
@ykuijs This is because the "InModuleScope" bit we use says to apply the mocks for the cmdlets should be done within the main module itself. So for the cmdlets that are called inside of Mount-SPContentDatabaes (like Get-SPDatabase) you need to add "-ModuleName SPContentDatabase".

This does mean that if you have Get-SPDatabase both in the main module as well as the new child module, you need two mocks for it - one for the main module (without the ModuleName bit I said above) and another for the child module (with that parameter).

Make sense mate?

**Comment by BrianFarnhill** [comment]
Reviewed 2 of 2 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[Modules/SharePointDsc/Modules/SharePointDsc.ContentDatabase/SPContentDatabase.psm1, line 6 \[r4\]](https://reviewable.io:443/reviews/powershell/sharepointdsc/370#-KMf_Hvqz7deLvCJip4C:-KMf_Hvqz7deLvCJip4D:1289028362) ([raw file](https://github.com/powershell/sharepointdsc/blob/2805f9628a045faa875843e614c43ecce2933ba8/Modules/SharePointDsc/Modules/SharePointDsc.ContentDatabase/SPContentDatabase.psm1#L6)):*
> ```PowerShell
>     (
>         [Parameter(Mandatory=$true)]
>         [System.Collections.Hashtable]
> ```

Have you tested this one? The hashtable will work in unit tests but if it gets the actual value of $PSBoundParameters it'll actually be PSBoundParametersDictionary so this will fail its type check. If you've actually run it on a box I'm good with this but just wanted to check

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/370)*

**Comment by ykuijs** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[Modules/SharePointDsc/Modules/SharePointDsc.ContentDatabase/SPContentDatabase.psm1, line 6 \[r4\]](https://reviewable.io:443/reviews/powershell/sharepointdsc/370#-KMf_Hvqz7deLvCJip4C:-KMhLt1ifmGYWEEzMgkb:1921733338) ([raw file](https://github.com/powershell/sharepointdsc/blob/2805f9628a045faa875843e614c43ecce2933ba8/Modules/SharePointDsc/Modules/SharePointDsc.ContentDatabase/SPContentDatabase.psm1#L6)):*
<details><summary><i>Previously, BrianFarnhill (Brian Farnhill) wrote…</i></summary>
> Have you tested this one? The hashtable will work in unit tests but if it gets the actual value of $PSBoundParameters it'll actually be PSBoundParametersDictionary so this will fail its type check. If you've actually run it on a box I'm good with this but just wanted to check
</details>
Yes, I have tested this and it works.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/370)*

**Comment by BrianFarnhill** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/370#-:-KMhj6WyCjYbEy3i-Ouc:1417088721)*

**Pull request merged**
