### PR TITLE
Update SPTrustedIdentityTokenIssuer to give possibility to load signing certificate from file system as well

### PR DESCRIPTION
**Pull request by Yvand**
Current version of SPTrustedIdentityTokenIssuer can only get signing certificate from the certificate store of the local machine, but in many cases you want to get the signing certificate from its .cer file.
I updated SPTrustedIdentityTokenIssuer to allow to specify either the thumbprint or the file path.

- [x] Change details added to Unreleased section of changelog.md?
- [X] Added/updated documentation and descriptions in .schema.mof files where appropriate?
- [X] Examples updated for both the single server and small farm templates in the examples folder?
- [X] New/changed code adheres to [Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md)?
- [X] [Unit and Integration tests](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md) created/updated where possible?

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/sharepointdsc/517)

### CODE REVIEW

**Comment by Yvand** [comment]
I just noticed that pull requests has many files changed, it's weird because I synced from the remote and only updated 4-5 files.
Any idea what I did wrong?

**Comment by luigilink** [comment]
@Yvand You have to rebase the dev instead of merge, that's what I did :
```
git checkout dev
[dev] git fetch upstream
[dev] git rebase upstream/dev
[dev] git checkout Feature/Fix-Branch
[Feature/Fix-Branch] git rebase dev
```

**Comment by BrianFarnhill** [comment]
@Yvand @luigilink I'm not a total git expert but the way I do it is slightly different. I'll have a remote setup for the PowerShell org repo of this and then pull from that when I need to merge things

Set up the remote

    git add remote PowerShell https://github.com/PowerShell/SharePointDsc.git

Pull from the dev branch in to my local branch

    git pull PowerShell dev

This will then usually whinge about merge conflicts, which I resolve and then commit. After that it lets me open a PR to PowerShell/dev with no conflicts, and any time I want to update a branch from whats in dev I just run that second line. Hope that helps

**Comment by Yvand** [comment]
Ok, I think I will close this PR, clean my repo and submit a new proper one!

**Pull request closed without merging**
