### PR TITLE
Fix SPServiceApplications for OS with non en-US language

### PR DESCRIPTION
**Pull request by luigilink**
Fix SPServiceApplications for OS with non en-US language
Add GetType().FullName in Get-SPServiceApplication [...] Where-Object

- [x] Change details added to Unreleased section of changelog.md?
- [x] Added/updated documentation and descriptions in .schema.mof files where appropriate?
- [x] Examples updated for both the single server and small farm templates in the examples folder?
- [x] New/changed code adheres to [Style Guidelines]?(https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md)?
- [x] [Unit and Integration tests](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md) created/updated where possible?

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/sharepointdsc/421)

### CODE REVIEW

**Comment by BrianFarnhill** [comment]
Looks like you didn't update the tests accordingly for your changes - once these are sorted out and the tests are passing we can review this in full.

---

Review status: 0 of 14 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/421#-:-KTQpE70EK3bebf4zzFN:boiv42u)*

**Comment by luigilink** [comment]
Pester Tests updated for SPWordAutomationServiceApp and SPWorkManagementServiceApp.
Needs Review.

**Comment by ykuijs** [comment]
:lgtm:

---

Reviewed 16 of 16 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/421#-:-KTp3Wq28P3L9aN4Vlkw:bnfp4nl)*

**Comment by BrianFarnhill** [comment]
@luigilink Can I get you to do a pull from dev and resolve the merge conflicts, then we can put this one in.

**Comment by ykuijs** [comment]
:lgtm:

---

Reviewed 14 of 14 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/421#-:-KTyR5BvFcihhT39xTjK:bnfp4nl)*

**Comment by BrianFarnhill** [comment]
Reviewed 2 of 14 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPAccessServiceApp/MSFT_SPAccessServiceApp.psm1, line 49 at r2](https://reviewable.io:443/reviews/powershell/sharepointdsc/421#-KU-BriOkeetm33K9pjF:-KU-BriOkeetm33K9pjG:b-ct3ypr) ([raw file](https://github.com/powershell/sharepointdsc/blob/a1fbc40ae3e7d6275e208c6c25d5150bab326eda/Modules/SharePointDsc/DSCResources/MSFT_SPAccessServiceApp/MSFT_SPAccessServiceApp.psm1#L49)):*
> ```PowerShell
>         $serviceApp = $serviceApps | Where-Object -FilterScript { 
>             $_.TypeName -eq "Access Services Web Service Application" -or `
>             $_.GetType().FullName -eq "Microsoft.Office.Access.Services.MossHost.AccessServicesWebServiceApplication"            
> ```

Just on this one - why do we bother checking the old type name one at all here? Seeing as the told TypeName check is never surfaced to the user (we just do it internally for type validation) shouldn't we be able to just replace the old check with what has been added here rather than using an OR? @ykuijs - your thoughts?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/421)*

**Comment by ykuijs** [comment]
Agree with @BrianFarnhill, only the new check is necessary. The current check is unnecessary, since if the first one is true, the second is also true. Just using the new check is cleaner.

**Comment by luigilink** [comment]
I keep the old one to reduce code change on all tests.ps1 for service application.
How can I mock a property of a method: $_.GetType().FullName, not easy I admit :(

**Comment by ykuijs** [comment]
Should be something like:

`Mock Get-SPServiceApplication {  
    $returnval = @(@{ 
        TypeName = "Access Services Web Service Application" 
    }) 
    $returnVal = $returnVal | Add-Member ScriptMethod GetType { return @{ FullName = "Microsoft.Office.Access.Services.MossHost.AccessServicesWebServiceApplication" } } -PassThru
    return $returnval
}`

**Comment by ykuijs** [comment]
For other examples: Search in the other test files for the word ScriptMethod. This has been used multiple times.

**Comment by BrianFarnhill** [comment]
Yea look at other tests that use "Add-Member" with the ScriptMethod type,  that's how you create a mock method on an object. I'll dig you up an example when I'm not on my phone if you get stuck

**Comment by luigilink** [comment]
Thanks for the tip guys 👍 
I will change all tests and resources impacted as soon as possible.

**Comment by luigilink** [comment]
Done, ready for review.

**Comment by BrianFarnhill** [comment]
:lgtm:

---

Reviewed 27 of 27 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/421#-:-KUAlYqnyN2NNnQPXDDc:bnfp4nl)*

**Pull request merged**
