### PR TITLE
Improved and fixed multiple issues with resource SPTrustedIdentityTokenIssuer

### PR DESCRIPTION
**Pull request by Yvand**
* Changed parameter ClaimsMappings in SPTrustedIdentityTokenIssuer to use an array of custom class MSFT_SPClaimTypeMapping 
* Changed SPTrustedIdentityTokenIssuer to throw an exception if certificate specified has a private key, since SharePoint doesn't accept it
* Fixed issue with SPTrustedIdentityTokenIssuer to stop if cmdlet New-SPTrustedIdentityTokenIssuer returns null
* Fixed issue with SPTrustedIdentityTokenIssuer to correctly get parameters ClaimProviderName and ProviderSignOutUri
* Fixed issue with SPTrustedIdentityTokenIssuer to effectively remove the SPTrustedAuthenticationProvider from all zones before deleting the SPTrustedIdentityTokenIssuer
* Updated code in SPTrustedIdentityTokenIssuer to respect style guidelines

- [x] Change details added to Unreleased section of changelog.md?
- [x] Added/updated documentation and descriptions in .schema.mof files where appropriate?
- [ ] Examples updated for both the single server and small farm templates in the examples folder?
- [x] New/changed code adheres to [Style Guidelines]?(https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md)?
- [x] [Unit and Integration tests](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md) created/updated where possible?

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/sharepointdsc/395)

### CODE REVIEW

**Comment by BrianFarnhill** [comment]
I've started the review of this one, but have a few questions before we get too far in to it. Details below.

---

Review status: 0 of 6 files reviewed at latest revision, 6 unresolved discussions.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPTrustedIdentityTokenIssuer/MSFT_SPTrustedIdentityTokenIssuer.psm1, line 102 \[r1\]](https://reviewable.io:443/reviews/powershell/sharepointdsc/395#-KQNKw0Xs92TL3SoPqrQ:-KQNKw0Xs92TL3SoPqrR:b-4si0x2) ([raw file](https://github.com/powershell/sharepointdsc/blob/dcbb608da5a7f5192a33e90829474b41a28b8f7e/Modules/SharePointDsc/DSCResources/MSFT_SPTrustedIdentityTokenIssuer/MSFT_SPTrustedIdentityTokenIssuer.psm1#L102)):*
> ```PowerShell
> 
>                 if ($cert.HasPrivateKey) {
>                     throw "The certificate must be installed without the private key."
> ```

Do we have a link to TechNet or some other reference that explains why it can't have a private key that we can include with this exception?

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPTrustedIdentityTokenIssuer/MSFT_SPTrustedIdentityTokenIssuer.psm1, line 106 \[r1\]](https://reviewable.io:443/reviews/powershell/sharepointdsc/395#-KQNKHmHAYaJD0OnXb4F:-KQNKHmIn7nlxlSDbWps:bolkwg2) ([raw file](https://github.com/powershell/sharepointdsc/blob/dcbb608da5a7f5192a33e90829474b41a28b8f7e/Modules/SharePointDsc/DSCResources/MSFT_SPTrustedIdentityTokenIssuer/MSFT_SPTrustedIdentityTokenIssuer.psm1#L106)):*
> ```PowerShell
>                 
>                 $claimsMappingsArray = @()
>                 $MappingsList = $params.ClaimsMappings| ConvertFrom-Json
> ```

Why are we relying on putting JSON in here instead of working with the CIM instances which are more of a DSC standard here? 

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPTrustedIdentityTokenIssuer/MSFT_SPTrustedIdentityTokenIssuer.psm1, line 111 \[r1\]](https://reviewable.io:443/reviews/powershell/sharepointdsc/395#-KQNL3JqrDb-qxWXJAdg:-KQNL3JqrDb-qxWXJAdh:bwqbkh) ([raw file](https://github.com/powershell/sharepointdsc/blob/dcbb608da5a7f5192a33e90829474b41a28b8f7e/Modules/SharePointDsc/DSCResources/MSFT_SPTrustedIdentityTokenIssuer/MSFT_SPTrustedIdentityTokenIssuer.psm1#L111)):*
> ```PowerShell
>                     $runParams.Add("IncomingClaimTypeDisplayName", $_.Name)
>                     $runParams.Add("IncomingClaimType", $_.IncomingClaimType)
>                     if ($_.LocalClaimType -eq $null) 
> ```

$null must always be on the left side of an equality check in PowerShell as per the style guidelines, can you swap this back please?

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPTrustedIdentityTokenIssuer/MSFT_SPTrustedIdentityTokenIssuer.psm1, line 137 \[r1\]](https://reviewable.io:443/reviews/powershell/sharepointdsc/395#-KQNLHVWUjcRBJsVR8Yb:-KQNLHVWUjcRBJsVR8Yc:bsmusd4) ([raw file](https://github.com/powershell/sharepointdsc/blob/dcbb608da5a7f5192a33e90829474b41a28b8f7e/Modules/SharePointDsc/DSCResources/MSFT_SPTrustedIdentityTokenIssuer/MSFT_SPTrustedIdentityTokenIssuer.psm1#L137)):*
> ```PowerShell
>                 $trust = New-SPTrustedIdentityTokenIssuer @runParams
> 
>                 if (!$trust) {
> ```

The opening brackets for if statements need to be placed on a new line (as per style guidelines)

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPTrustedIdentityTokenIssuer/MSFT_SPTrustedIdentityTokenIssuer.psm1, line 138 \[r1\]](https://reviewable.io:443/reviews/powershell/sharepointdsc/395#-KQNLOQypoiX5x9Q6xzf:-KQNLOQypoiX5x9Q6xzg:b-nrjjc3) ([raw file](https://github.com/powershell/sharepointdsc/blob/dcbb608da5a7f5192a33e90829474b41a28b8f7e/Modules/SharePointDsc/DSCResources/MSFT_SPTrustedIdentityTokenIssuer/MSFT_SPTrustedIdentityTokenIssuer.psm1#L138)):*
> ```PowerShell
> 
>                 if (!$trust) {
>                     #throw "SharePoint failed to create the SPTrustedIdentityTokenIssuer."
> ```

Why is this commented out? We should be throwing an exception if something has gone wrong

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPTrustedIdentityTokenIssuer/MSFT_SPTrustedIdentityTokenIssuer.psm1, line 164 \[r1\]](https://reviewable.io:443/reviews/powershell/sharepointdsc/395#-KQNLiydr7D5poZ8CMCD:-KQNLiydr7D5poZ8CMCE:bsmusd4) ([raw file](https://github.com/powershell/sharepointdsc/blob/dcbb608da5a7f5192a33e90829474b41a28b8f7e/Modules/SharePointDsc/DSCResources/MSFT_SPTrustedIdentityTokenIssuer/MSFT_SPTrustedIdentityTokenIssuer.psm1#L164)):*
> ```PowerShell
>                     $zone = $_
>                     $providers = Get-SPAuthenticationProvider -WebApplication $wa.Url -Zone $zone -ErrorAction SilentlyContinue
>                     if (!$providers) { 
> ```

The opening brackets for if statements need to be placed on a new line (as per style guidelines)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/395#-:-KQNM0QZUwvqWvchAYZR:bd5v4nk)*

**Comment by Yvand** [comment]
Actually I also have a question regarding style guidelines: should the bracket just after 'Where-Object' and 'ForEach-Object' also be in a new line?
According to style guidelines I should probably do so, but I didn't see this in other resources

---

Review status: 0 of 6 files reviewed at latest revision, 6 unresolved discussions.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPTrustedIdentityTokenIssuer/MSFT_SPTrustedIdentityTokenIssuer.psm1, line 102 \[r1\]](https://reviewable.io:443/reviews/powershell/sharepointdsc/395#-KQNKw0Xs92TL3SoPqrQ:-KQPbOgfDftGAdzEJolf:b-j004d) ([raw file](https://github.com/powershell/sharepointdsc/blob/dcbb608da5a7f5192a33e90829474b41a28b8f7e/Modules/SharePointDsc/DSCResources/MSFT_SPTrustedIdentityTokenIssuer/MSFT_SPTrustedIdentityTokenIssuer.psm1#L102)):*
<details><summary><i>Previously, BrianFarnhill (Brian Farnhill) wrote…</i></summary>
> Do we have a link to TechNet or some other reference that explains why it can't have a private key that we can include with this exception?
</details>
I couldn't find anything on TechNet, but here is the error recorded in SharePoint logs:
*wsmprovhost.exe (0x13D8)    0x06EC  SharePoint Foundation   PowerShell  6tf2    High    System.ArgumentException: Certificate file must contain only one valid X509 certificate without private keys.*
Note that in DSC, that will only return $null on cmdlet New-SPTrustedIdentityTokenIssuer without any clue of the actual error, so I added this test to ease troubleshooting

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPTrustedIdentityTokenIssuer/MSFT_SPTrustedIdentityTokenIssuer.psm1, line 106 \[r1\]](https://reviewable.io:443/reviews/powershell/sharepointdsc/395#-KQNKHmHAYaJD0OnXb4F:-KQPcPq5aRFNCCsb2zvr:b-ouq5sm) ([raw file](https://github.com/powershell/sharepointdsc/blob/dcbb608da5a7f5192a33e90829474b41a28b8f7e/Modules/SharePointDsc/DSCResources/MSFT_SPTrustedIdentityTokenIssuer/MSFT_SPTrustedIdentityTokenIssuer.psm1#L106)):*
<details><summary><i>Previously, BrianFarnhill (Brian Farnhill) wrote…</i></summary>
> Why are we relying on putting JSON in here instead of working with the CIM instances which are more of a DSC standard here? 
</details>
All of this is (was) very new to me and I spent a lot of time to troubleshoot/understand this.
But I think that an array of HashTables is not possible, and no other solution actually works:

## If ClaimsMappings param is an array of HashTables
Example:
```PowerShell
ClaimsMappings = @( @{Name = "Email"; IncomingClaimType = "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress"}, @{Name = "Account name"; IncomingClaimType = "http://schemas.microsoft.com/ws/2008/06/identity/claims/role"; LocalClaimType = "http://schemas.xmlsoap.org/customSPGroupClaimType"} )
```
Node MOF file is generated successfully but it creates a 1 dimensional array of key/value pairs, e.g. Name/"Email", Name/"Account name"

## If ClaimsMappings param is an array of CimInstance
Example:
```PowerShell
ClaimsMappings = @(
    (New-CimInstance -ClassName "MSFT_KeyValuePair" -ClientOnly -Property @{
        Name = "Email"; 
        IncomingClaimType = "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress"
    }),
    (New-CimInstance -ClassName "MSFT_KeyValuePair" -ClientOnly -Property @{
        Name = "Account name"; 
        IncomingClaimType = "http://schemas.microsoft.com/ws/2008/06/identity/claims/role"; 
        LocalClaimType = "http://schemas.xmlsoap.org/customSPGroupClaimType"
    })
)
```
It doesn't work at all, the generation of node MOF file fails with various errors depending on how type is declared in resource schema file.
I made a lot of research, and it's the 2nd issue discussed in https://powershell.org/forums/topic/hashtable-as-parameter-for-custom-dsc-resource/
This is this article that gave me the idea to use JSON as workaround

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPTrustedIdentityTokenIssuer/MSFT_SPTrustedIdentityTokenIssuer.psm1, line 138 \[r1\]](https://reviewable.io:443/reviews/powershell/sharepointdsc/395#-KQNLOQypoiX5x9Q6xzf:-KQPdjXtNYCWmqJnO3cJ:bmlickk) ([raw file](https://github.com/powershell/sharepointdsc/blob/dcbb608da5a7f5192a33e90829474b41a28b8f7e/Modules/SharePointDsc/DSCResources/MSFT_SPTrustedIdentityTokenIssuer/MSFT_SPTrustedIdentityTokenIssuer.psm1#L138)):*
<details><summary><i>Previously, BrianFarnhill (Brian Farnhill) wrote…</i></summary>
> Why is this commented out? We should be throwing an exception if something has gone wrong
</details>
Ok, I put this in comment to raise this discussion this with you.
I couldn't decide if I should throw an exception if creation fails without exception (New-SPTrustedIdentityTokenIssuer just returns $null), or simply return...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/395#-:-KQPeSWTcZXKvNzqn-4c:b1jm4b9)*

**Comment by BrianFarnhill** [comment]
Review status: 0 of 6 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPTrustedIdentityTokenIssuer/MSFT_SPTrustedIdentityTokenIssuer.psm1, line 102 \[r1\]](https://reviewable.io:443/reviews/powershell/sharepointdsc/395#-KQNKw0Xs92TL3SoPqrQ:-KQwiQdn23kYU5KvpnoD:b-psxfdw) ([raw file](https://github.com/powershell/sharepointdsc/blob/dcbb608da5a7f5192a33e90829474b41a28b8f7e/Modules/SharePointDsc/DSCResources/MSFT_SPTrustedIdentityTokenIssuer/MSFT_SPTrustedIdentityTokenIssuer.psm1#L102)):*
<details><summary><i>Previously, Yvand (Yvan Duhamel) wrote…</i></summary>
> I couldn't find anything on TechNet, but here is the error recorded in SharePoint logs:
> *wsmprovhost.exe (0x13D8)    0x06EC  SharePoint Foundation   PowerShell  6tf2    High    System.ArgumentException: Certificate file must contain only one valid X509 certificate without private keys.*
> Note that in DSC, that will only return $null on cmdlet New-SPTrustedIdentityTokenIssuer without any clue of the actual error, so I added this test to ease troubleshooting
</details>
OK that makes sense - can I get you to make sure we explain that in the description readme.md file just to make it clear

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPTrustedIdentityTokenIssuer/MSFT_SPTrustedIdentityTokenIssuer.psm1, line 106 \[r1\]](https://reviewable.io:443/reviews/powershell/sharepointdsc/395#-KQNKHmHAYaJD0OnXb4F:-KQwgcDi_xl6_lOGYzlJ:b-kpitn3) ([raw file](https://github.com/powershell/sharepointdsc/blob/dcbb608da5a7f5192a33e90829474b41a28b8f7e/Modules/SharePointDsc/DSCResources/MSFT_SPTrustedIdentityTokenIssuer/MSFT_SPTrustedIdentityTokenIssuer.psm1#L106)):*
<details><summary><i>Previously, Yvand (Yvan Duhamel) wrote…</i></summary>
> All of this is (was) very new to me and I spent a lot of time to troubleshoot/understand this.
> But I think that an array of HashTables is not possible, and no other solution actually works:
> 
> ## If ClaimsMappings param is an array of HashTables
> Example:
> ```PowerShell
> ClaimsMappings = @( @{Name = "Email"; IncomingClaimType = "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress"}, @{Name = "Account name"; IncomingClaimType = "http://schemas.microsoft.com/ws/2008/06/identity/claims/role"; LocalClaimType = "http://schemas.xmlsoap.org/customSPGroupClaimType"} )
> ```
> Node MOF file is generated successfully but it creates a 1 dimensional array of key/value pairs, e.g. Name/"Email", Name/"Account name"
> 
> ## If ClaimsMappings param is an array of CimInstance
> Example:
> ```PowerShell
> ClaimsMappings = @(
>     (New-CimInstance -ClassName "MSFT_KeyValuePair" -ClientOnly -Property @{
>         Name = "Email"; 
>         IncomingClaimType = "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress"
>     }),
>     (New-CimInstance -ClassName "MSFT_KeyValuePair" -ClientOnly -Property @{
>         Name = "Account name"; 
>         IncomingClaimType = "http://schemas.microsoft.com/ws/2008/06/identity/claims/role"; 
>         LocalClaimType = "http://schemas.xmlsoap.org/customSPGroupClaimType"
>     })
> )
> ```
> It doesn't work at all, the generation of node MOF file fails with various errors depending on how type is declared in resource schema file.
> I made a lot of research, and it's the 2nd issue discussed in https://powershell.org/forums/topic/hashtable-as-parameter-for-custom-dsc-resource/
> This is this article that gave me the idea to use JSON as workaround
> 
</details>
OK, so the array of key value pairs was never going to cut it then, it's meant to be used like this:

            ClaimsMappings = @(
                MSFT_KeyValuePair {
                    Key = "name"
                    Value = "value"
                }
                MSFT_KeyValuePair {
                    Key = "name1"
                    Value = "value1"
                }
                MSFT_KeyValuePair {
                    Key = "name2"
                    Value = "value2"
                }
            )

So it wasn't ever going to give the data structure you needed (also you shouldn't need to use New-CIMInstance to get your MOFs created like that). 

Now my immediate concern is that this could form a breaking change since we are changing a property type, but technically speaking it never would have worked under the old model so we aren't breaking something that worked. @ykuijs what do you think here, do we need to make this a 2.0 thing?

In terms of moving forward here, I'm super hesitant to put the JSON array in here and would rather stick to a properly document MOF object of our own here to make sure the property names are all handled correctly. We could do something similar to SPWebAppPolicy where we have a second MOF type in the schema and take an array of that in here (Check out an [Example of it in use](https://github.com/PowerShell/SharePointDsc/blob/dev/Modules/SharePointDsc/Examples/Resources/SPWebAppPolicy/1-SpecificMembers.ps1) as well as the [MOF schema](https://github.com/PowerShell/SharePointDsc/blob/dev/Modules/SharePointDsc/DSCResources/MSFT_SPWebAppPolicy/MSFT_SPWebAppPolicy.schema.mof) to see how we do that.) Again @ykuijs what do you think here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/395)*

**Comment by ykuijs** [comment]
Isn't the solution I used in SPWebAppPolicy an option in this case? Sounds like a similar issue where this sub class solution would be ideal:
            SPWebAppPolicy WebAppPolicy
            {
                WebAppUrl = "http://sharepoint.contoso.com"
                Members = @(
                    MSFT_SPWebPolicyPermissions {
                        Username           = "contoso\user1"
                        PermissionLevel    = "Full Control"
                        ActAsSystemAccount = $true
                    }
                    MSFT_SPWebPolicyPermissions {
                        Username        = "contoso\Group 1"
                        PermissionLevel = "Full Read"
                        IdentityType    = "Claims"
                    }
                )
            }

**Comment by Yvand** [comment]
Yes it's definitely a good solution that I didn't consider because my research led me to the JSON array, which I didn't find bad.
I understand you prefer a custom object so I'll update the pull request to use this.
I'll also update the code style as done in other pull request "Update to follow PowerShell team style guidelines"

@BrianFarnhill indeed current version never worked, so should I update version number of the resource?
I'll also update the readme.md to explain private key issue.

**Comment by BrianFarnhill** [comment]
@Yvand No need to increment version numbers - we'll make that call and handle it before we ship it. Overall this is looking pretty good at this point. Can I just confirm that you've been able to test this and see it working correctly with this code base before I look to merge it in? 

---

Reviewed 6 of 6 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/395#-:-KR6iE7okY8BJvEjIfss:bjqvt8p)*

**Comment by Yvand** [comment]
@BrianFarnhill Yes I tested it intensively and I can assure you this version works fine :)
But I don't understand why appveyor fails on last commit, I don't even see the full error message, do you know what's wrong?

**Comment by BrianFarnhill** [comment]
@kwirkykat Can I get you to reset the appveyor webhooks for us on this repo? I've got permissions here but not in appveyor. Looks like the webhook is returning HTTP 400's and I'm not sure why.

**Comment by kwirkykat** [comment]
@BrianFarnhill @Yvand Triggered this one to run again manually.

I updated the SharePointDsc AppVeyor webhook as well.

**Comment by BrianFarnhill** [comment]
Thanks @kwirkykat

@Yvand Just a couple of little things to get it passing the tests. What you have is a valid MOF but there are issues with our doco generators - they are bugs I'll get fixed but for the time being if you could make these last couple of minor changes that should see the tests pass and we'll merge this in.

---

Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPTrustedIdentityTokenIssuer/MSFT_SPTrustedIdentityTokenIssuer.schema.mof, line 7 at r3](https://reviewable.io:443/reviews/powershell/sharepointdsc/395#-KRaKOnylXnzGhuH-SrF:-KRaKOnylXnzGhuH-SrG:b41cibg) ([raw file](https://github.com/powershell/sharepointdsc/blob/8475bea2557a1ff515ab0c2161577228928830ce/Modules/SharePointDsc/DSCResources/MSFT_SPTrustedIdentityTokenIssuer/MSFT_SPTrustedIdentityTokenIssuer.schema.mof#L7)):*
> ```
>     [Key, Description("Display name of the incoming claim type")] String Name;
>     [Required, Description("URI of the incoming claim type")] String IncomingClaimType;
>     [Write, Description("URI of the local claim type; not required if same as IncomingClaimType")] String LocalClaimType;
> ```

Can you take the ; out of the description here?

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPTrustedIdentityTokenIssuer/MSFT_SPTrustedIdentityTokenIssuer.schema.mof, line 19 at r3](https://reviewable.io:443/reviews/powershell/sharepointdsc/395#-KRaKRU5VzS-AqCanj-7:-KRaKRU6yOKBJUgdKByz:b11jbcv) ([raw file](https://github.com/powershell/sharepointdsc/blob/8475bea2557a1ff515ab0c2161577228928830ce/Modules/SharePointDsc/DSCResources/MSFT_SPTrustedIdentityTokenIssuer/MSFT_SPTrustedIdentityTokenIssuer.schema.mof#L19)):*
> ```
>     [Required, Description("URL of the identity provider where user is redirected to for authentication")] String SignInUrl;
>     [Required, Description("Identity claim type that uniquely identifies the user")] String IdentifierClaim;
>     [Required, EmbeddedInstance("MSFT_SPClaimTypeMapping"), Description("Array of MSFT_SPClaimTypeMapping to use with cmdlet New-SPClaimTypeMapping")] String ClaimsMappings[];
> ```

Can you swap this so the EmbeddedInstance comes after the description

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPTrustedIdentityTokenIssuer/MSFT_SPTrustedIdentityTokenIssuer.schema.mof, line 24 at r3](https://reviewable.io:443/reviews/powershell/sharepointdsc/395#-KRaKUu6dgx-vWz7sfDI:-KRaKUu6dgx-vWz7sfDJ:b11jbcv) ([raw file](https://github.com/powershell/sharepointdsc/blob/8475bea2557a1ff515ab0c2161577228928830ce/Modules/SharePointDsc/DSCResources/MSFT_SPTrustedIdentityTokenIssuer/MSFT_SPTrustedIdentityTokenIssuer.schema.mof#L24)):*
> ```
>     [Write, Description("Sign-out URL")] String ProviderSignOutUri;
>     [Write, Description("Present if the SPTrustedIdentityTokenIssuer should be created, or Absent if it should be removed"), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
>     [Write, EmbeddedInstance("MSFT_Credential"), Description("POWERSHELL 4 ONLY: The account to run this resource as, use PsDscRunAsCredential if using PowerShell 5")] String InstallAccount;
> ```

Can you swap this so the EmbeddedInstance comes after the description

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/395#-:-KRaKWPHxHIt27hxctMB:b-djr6jo)*

**Comment by Yvand** [comment]
Review status: 5 of 6 files reviewed at latest revision, 3 unresolved discussions.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPTrustedIdentityTokenIssuer/MSFT_SPTrustedIdentityTokenIssuer.schema.mof, line 7 at r3](https://reviewable.io:443/reviews/powershell/sharepointdsc/395#-KRaKOnylXnzGhuH-SrF:-KRbiN0jWSkK1edyvBgN:b-896fix) ([raw file](https://github.com/powershell/sharepointdsc/blob/8475bea2557a1ff515ab0c2161577228928830ce/Modules/SharePointDsc/DSCResources/MSFT_SPTrustedIdentityTokenIssuer/MSFT_SPTrustedIdentityTokenIssuer.schema.mof#L7)):*
<details><summary><i>Previously, BrianFarnhill (Brian Farnhill) wrote…</i></summary>
> Can you take the ; out of the description here?
</details>
Done.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPTrustedIdentityTokenIssuer/MSFT_SPTrustedIdentityTokenIssuer.schema.mof, line 19 at r3](https://reviewable.io:443/reviews/powershell/sharepointdsc/395#-KRaKRU5VzS-AqCanj-7:-KRbiRLhvX5vCTSVbVI6:b-896fix) ([raw file](https://github.com/powershell/sharepointdsc/blob/8475bea2557a1ff515ab0c2161577228928830ce/Modules/SharePointDsc/DSCResources/MSFT_SPTrustedIdentityTokenIssuer/MSFT_SPTrustedIdentityTokenIssuer.schema.mof#L19)):*
<details><summary><i>Previously, BrianFarnhill (Brian Farnhill) wrote…</i></summary>
> Can you swap this so the EmbeddedInstance comes after the description
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/395)*

**Comment by BrianFarnhill** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/395#-:-KRet04DIRpmg_O4a5fV:bnfp4nl)*

**Pull request merged**
