### PR TITLE
Added the Format-OfficePatchGuid

### PR DESCRIPTION
**Pull request by NikCharlebois**
Added a new utility function to support the extraction of well formatted Office Patch GUID.

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/sharepointdsc/708)

### CODE REVIEW

**Comment by ykuijs** [comment]
For consistency: Shouldn't we remove the semi colon at the back of these lines? Powershell doesn't require them and we don't use them anywhere else in the module

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/708#-:-L22Dzbg1KRSJb6lQE9F:b-4tb7gr)*

**Comment by NikCharlebois** [comment]
Yes. Old C# habits die hard. :)

**Comment by NikCharlebois** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/708)*

**Comment by ykuijs** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/708#-:-L279ySELTE1KrKFbv0z:bnfp4nl)*

**Pull request merged**
