### PR TITLE
Sp result source

### LINKED ISSUE #918: Breaking Change - SPSearchResultSource: Make ScopeURL a Key
#### Details of the scenario you tried and the problem that is occurring
I have a client that redefines the same Result Source (named Promotions), on several Site Collection. Problem is that with the current resource, only the name is defined as a key, causing the configuration to throw errors about duplicate resource definitions. We need to make ScopeURL a key to allow for this scenario.

#### Verbose logs showing the problem
N/A

#### Suggested solution to the issue
Make ScopeURL a key, use "Global" as a value to identify a Global Result Source.

#### The operating system the target node is running
Windows Server 2012 R2

#### Version of SharePoint that is used (e.g. SharePoint 2016)
SharePoint 2013

#### Version and build of PowerShell the target node is running
PoSh 4.0

#### Version of the DSC module that was used ('dev' if using current dev branch)
2.5.0.0

### PR DESCRIPTION
**Pull request by NikCharlebois**
#### Pull Request (PR) description
BREAKING CHANGE: Allows Result Sources to be created at different scopes: SSA, SPSite or SPWeb

#### This Pull Request (PR) fixes the following issues
- Fixes #918 

#### Task list
- [x] Added an entry under the Unreleased section of the change log in the CHANGELOG.md.
      Entry should say what was changed, and how that affects users (if applicable).
- [x] Resource documentation added/updated in README.md in the resource folder.
- [x] Resource parameter descriptions added/updated in schema.mof
      and comment-based help.
- [x] Comment-based help added/updated.
- [x] Localization strings added/updated in all localization files as appropriate.
- [x] Examples appropriately added/updated.
- [x] Unit tests added/updated. See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [x] Integration tests added/updated (where possible). See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [x] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/sharepointdsc/930)

### CODE REVIEW

**Comment by ykuijs** [comment]
There are two issues in the schema:
```
[00:34:53]     Context MSFT_SPSearchResultSource
[00:34:53] Test-ParameterMetaDataIsDscResourceProperty : The ValidateSet item SPweb for property Scope in the schema was not found in the module.
[00:34:53] At C:\Users\appveyor\Documents\WindowsPowerShell\Modules\xDscResourceDesigner\xDSCResourceDesigner.psm1:1925 char:23
[00:34:53] + ...       -not (Test-ParameterMetaDataIsDscResourceProperty $GetParameter ...
[00:34:53] +                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[00:34:53]     + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
[00:34:53]     + FullyQualifiedErrorId : SchemaModuleValidateSetItemError,Test-ParameterMetaDataIsDscResourceProperty
[00:34:53]  
[00:34:53] Test-GetKeyRequiredMandatory : The function Get-TargetResource must take all Key and Required properties, and they must be mandatory. There was an issue with property Scope.
[00:34:53] At C:\Users\appveyor\Documents\WindowsPowerShell\Modules\xDscResourceDesigner\xDSCResourceDesigner.psm1:1878 char:36
[00:34:53] + ... ror = -not (Test-GetKeyRequiredMandatory $GetCommandInfo.Parameters ` ...
[00:34:53] +                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[00:34:53]     + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
[00:34:53]     + FullyQualifiedErrorId : GetMissingKeyOrRequiredError,Test-GetKeyRequiredMandatory
[00:34:53]  
[00:34:53] Test-ParameterMetaDataIsDscResourceProperty : The ValidateSet item SPweb for property Scope in the schema was not found in the module.
[00:34:53] At C:\Users\appveyor\Documents\WindowsPowerShell\Modules\xDscResourceDesigner\xDSCResourceDesigner.psm1:1974 char:23
[00:34:53] + ...       -not (Test-ParameterMetaDataIsDscResourceProperty $SetParameter ...
[00:34:53] +                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[00:34:53]     + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
[00:34:53]     + FullyQualifiedErrorId : SchemaModuleValidateSetItemError,Test-ParameterMetaDataIsDscResourceProperty
[00:34:53]  
[00:34:53] Test-SetHasExactlyAllNonReadProperties : The functions Set-TargetResource and Test-TargetResource must take all Key, Required and Write properties. There is an issue with the parameter Scope defined in the schema.
[00:34:53] At C:\Users\appveyor\Documents\WindowsPowerShell\Modules\xDscResourceDesigner\xDSCResourceDesigner.psm1:1884 char:34
[00:34:53] + ... rror = -not (Test-SetHasExactlyAllNonReadProperties $SetCommandInfo `
[00:34:53] +                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[00:34:53]     + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
[00:34:53]     + FullyQualifiedErrorId : SetAndTestMissingParameterError,Test-SetHasExactlyAllNonReadProperties
[00:34:53]  
[00:34:53]       [-] Should pass Test-xDscResource 305ms
[00:34:53]         Expected $true, but got $false.
[00:34:53]         382:                 Test-xDscResource -Name $scriptResourcePath | Should -Be $true
[00:34:53]         at <ScriptBlock>, C:\projects\sharepointdsc\Modules\SharePointDsc\DSCResource.Tests\Meta.Tests.ps1: line 382
```

and 

```
[00:40:36]       [-] Should compile MOFs for example correctly 533ms
[00:40:36]         Expected no exception to be thrown, but an exception "At C:\projects\sharepointdsc\Modules\SharePointDsc\Examples\Resources\SPSearchResultSource\1-Example.ps1:16 char:13
[00:40:36]         +             SPSearchResultSource RemoteSharePointFarm
[00:40:36]         +             ~~~~~~~~~~~~~~~~~~~~
[00:40:36]         Undefined DSC resource 'SPSearchResultSource'. Use Import-DSCResource to import the resource." was thrown from C:\projects\sharepointdsc\Modules\SharePointDsc\Examples\Resources\SPSearchResultSource\1-Example.ps1:16 char:13
[00:40:36]             +             SPSearchResultSource RemoteSharePointFarm
[00:40:36]             +             ~~~~~~~~~~~~~~~~~~~~.
[00:40:36]         751:                     } | Should -Not -Throw
[00:40:36]         at <ScriptBlock>, C:\projects\sharepointdsc\Modules\SharePointDsc\DSCResource.Tests\Meta.Tests.ps1: line 614
```

**Comment by NikCharlebois** [comment]
I somehow pushed the changes to the Schema Mof, but appveyor isn't kicking in...

**Comment by ykuijs** [comment]
Closing and reopening to start AppVeyor

**Comment by ykuijs** [comment]
The tests are throwing the following errors:
```
ImportCimAndScriptKeywordsFromModule : Cim deserializer threw an error when deserializing file 
C:\Windows\system32\WindowsPowerShell\v1.0\Modules\SharePointDsc\DSCResources\MSFT_SPSearchResultSource\MSFT_SPSearchResultSource.Schema.mof.
At C:\Windows\system32\WindowsPowerShell\v1.0\Modules\PSDesiredStateConfiguration\PSDesiredStateConfiguration.psm1:2120 char:50
+ ... dResource = ImportCimAndScriptKeywordsFromModule -Module $mod -Resour ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], PSInvalidOperationException
    + FullyQualifiedErrorId : System.Management.Automation.PSInvalidOperationException,ImportCimAndScriptKeywordsFromModule
 
ImportCimAndScriptKeywordsFromModule : Syntax error: 
 At line:5, char:191
 Buffer:
","SPWeb"}] String Scope^;
    [
```

I remember from the past that the name scope cannot be used as parameter name. I ran into the same issue with SPDesignerSettings and had to use another name to get around the issue.

**Comment by ykuijs** [comment]
And please update from the v3.0 branch, since I just merged your other PR

**Comment by ykuijs** [comment]
Are you trying to update the v3.0-development branch with all changes from dev? I am trying to do that as well, but this took longer and turned out to be more work than I expected, but am almost there ;-)

**Comment by ykuijs** [comment]
Now that you already started, please go ahead and finish this one up. We can go from there.

**Comment by ykuijs** [comment]
Since I was already done, I just submitted a PR with the merge of dev and v3.0-dev. Can you review this, so you can do a pull to this branch afterwards?

**Comment by ykuijs** [comment]
Ok, ready for a pull from v3.0-development......I guess "Good luck" is in order here ;-)

**Comment by NikCharlebois** [comment]
Knocking on wood with my fingers crossed :)

**Comment by ykuijs** [comment]
Does this PR also solve issue 920?

**Comment by ykuijs** [comment]
Please check some of the changed files, some of them still have "<<<<<<<HEAD" lines in them.

**Comment by NikCharlebois** [comment]
Please ignore this PR for the moment, I still have a few conflicts to iron out. I will let you know when it is ready for review. Thanks

**Comment by NikCharlebois** [comment]
@ykuijs all yours to review and merge, sorry I was off sick for the past few days and couldn't fix my tests.

**Comment by ykuijs** [comment]
I have caused the failing test.....just submitted a PR that should fix the issue

**Comment by ykuijs** [comment]
Merged my PR. If you update your branch, the tests should work fine.

**Pull request merged**
