### PR TITLE
Implemented breaking changes for v2.0

### PR DESCRIPTION
**Pull request by ykuijs**
Implemented breaking changes #389, #424, #572 for the v2.0 release

- [X] Change details added to Unreleased section of changelog.md?
- [X] Added/updated documentation and descriptions in .schema.mof files where appropriate?
- [X] Examples updated for both the single server and small farm templates in the examples folder?
- [X] New/changed code adheres to [Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md)?
- [X] [Unit and Integration tests](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md) created/updated where possible?

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/sharepointdsc/637)

### CODE REVIEW

**Comment by ykuijs** [comment]
@BrianFarnhill, all checks have passed. It is all yours for review!

**Comment by BrianFarnhill** [comment]
@ykuijs Sorry for the delay, I'm kicking off my review of this one now dude

**Comment by BrianFarnhill** [comment]
Dude this is a massive effort from you, and a great bunch of fixes. Only some minor tweaks and things below - the majority of it looks awesome!

---

Reviewed 17 of 19 files at r1, 5 of 5 files at r2.
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---

*[CHANGELOG.md, line 3 at r2](https://reviewable.io:443/reviews/powershell/sharepointdsc/637#-Kpw4bhkLbsRa6_vycEP:-Kpw4bhkLbsRa6_vycEQ:bf7pz3p) ([raw file](https://github.com/powershell/sharepointdsc/blob/94f0625502507511e83ac4a5bc11246ce6373401/CHANGELOG.md#L3)):*
> ```Markdown
> # Change log for SharePointDsc
> 
> ## Unreleased v2.0
> ```

Just make this "v2.0" because we'll do a release right after we get this together

---

*[CHANGELOG.md, line 5 at r2](https://reviewable.io:443/reviews/powershell/sharepointdsc/637#-Kpw4nEHNBsyn0LdH6Ct:-Kpw4nEHNBsyn0LdH6Cu:bx4opcj) ([raw file](https://github.com/powershell/sharepointdsc/blob/94f0625502507511e83ac4a5bc11246ce6373401/CHANGELOG.md#L5)):*
> the use these resources

should be "that use these resources"

---

*[CHANGELOG.md, line 12 at r2](https://reviewable.io:443/reviews/powershell/sharepointdsc/637#-Kpw4ikck6WMO1JgTsiY:-Kpw4ikck6WMO1JgTsiZ:buozkrz) ([raw file](https://github.com/powershell/sharepointdsc/blob/94f0625502507511e83ac4a5bc11246ce6373401/CHANGELOG.md#L12)):*
> ```Markdown
>   the requirement for CredSSP
> 
> ## Unreleased
> ```

No need for a second unreleased header 

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPUserProfileServiceApp/MSFT_SPUserProfileServiceApp.psm1, line 94 at r2](https://reviewable.io:443/reviews/powershell/sharepointdsc/637#-Kpw5cwrmaYSIdPghbRl:-Kpw5cwrmaYSIdPghbRm:b-eauyut) ([raw file](https://github.com/powershell/sharepointdsc/blob/94f0625502507511e83ac4a5bc11246ce6373401/Modules/SharePointDsc/DSCResources/MSFT_SPUserProfileServiceApp/MSFT_SPUserProfileServiceApp.psm1#L94)):*
> ```PowerShell
>                 {
>                     throw ("Specified PSDSCRunAsCredential isn't the Farm Account. Make sure " + `
>                            "the specified PSDSCRunAsCredential is the Farm Account and try again")
> ```

Can we inject the user name in here to make it obvious what account it should be running as?

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPUserProfileServiceApp/MSFT_SPUserProfileServiceApp.psm1, line 248 at r2](https://reviewable.io:443/reviews/powershell/sharepointdsc/637#-Kpw5oELH7evEQuybxLl:-Kpw5oELH7evEQuybxLm:bigon2a) ([raw file](https://github.com/powershell/sharepointdsc/blob/94f0625502507511e83ac4a5bc11246ce6373401/Modules/SharePointDsc/DSCResources/MSFT_SPUserProfileServiceApp/MSFT_SPUserProfileServiceApp.psm1#L248)):*
> ```PowerShell
>     if ($Ensure -eq "Present") 
>     {    
>         $farmAccount = Invoke-SPDSCCommand -Credential $InstallAccount `
> ```

Seeing as we are doing this check in multiple places, do we want to extract it to a helper function that throws the error there instead of duplicating the code in this file? 

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPUserProfileServiceApp/readme.md, line 7 at r2](https://reviewable.io:443/reviews/powershell/sharepointdsc/637#-Kpw6DoEnyEjRZFvsgwB:-Kpw6DoFv3nboteUVBE5:bzfzo9v) ([raw file](https://github.com/powershell/sharepointdsc/blob/94f0625502507511e83ac4a5bc11246ce6373401/Modules/SharePointDsc/DSCResources/MSFT_SPUserProfileServiceApp/readme.md#L7)):*
> ```Markdown
> in to it (although these are only used during the initial provisioning).
> 
> The specified InstallAccount or PSDSCRunAsCredential has to be the Farm Account
> ```

Need a full stop on the end of this line. 

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPUserProfileSyncService/MSFT_SPUserProfileSyncService.psm1, line 36 at r2](https://reviewable.io:443/reviews/powershell/sharepointdsc/637#-Kpw6JQORlk9pcpqC5Dk:-Kpw6JQORlk9pcpqC5Dl:bxva2q8) ([raw file](https://github.com/powershell/sharepointdsc/blob/94f0625502507511e83ac4a5bc11246ce6373401/Modules/SharePointDsc/DSCResources/MSFT_SPUserProfileSyncService/MSFT_SPUserProfileSyncService.psm1#L36)):*
> ```PowerShell
>     }
> 
>     $farmAccountName = Invoke-SPDSCCommand -Credential $InstallAccount `
> ```

Same comment as above about taking this logic in to a helper function/module

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPUserProfileSyncService/MSFT_SPUserProfileSyncService.psm1, line 177 at r2](https://reviewable.io:443/reviews/powershell/sharepointdsc/637#-Kpw6OmnZmE9KyP1sysr:-Kpw6OmoreB-i9-Hkpnk:bxva2q8) ([raw file](https://github.com/powershell/sharepointdsc/blob/94f0625502507511e83ac4a5bc11246ce6373401/Modules/SharePointDsc/DSCResources/MSFT_SPUserProfileSyncService/MSFT_SPUserProfileSyncService.psm1#L177)):*
> ```PowerShell
>     }
> 
>     $farmAccountName = Invoke-SPDSCCommand -Credential $InstallAccount `
> ```

Same comment as above about taking this logic in to a helper function/module

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPUserProfileSyncService/MSFT_SPUserProfileSyncService.schema.mof, line 6 at r2](https://reviewable.io:443/reviews/powershell/sharepointdsc/637#-Kpw6Z85YmcoxhjE1mwP:-Kpw6Z85YmcoxhjE1mwQ:b-x5nfdg) ([raw file](https://github.com/powershell/sharepointdsc/blob/94f0625502507511e83ac4a5bc11246ce6373401/Modules/SharePointDsc/DSCResources/MSFT_SPUserProfileSyncService/MSFT_SPUserProfileSyncService.schema.mof#L6)):*
> ```
>     [Key, Description("The name of the user profile service for this sync instance")] string UserProfileServiceAppName;
>     [Write, Description("Present to ensure the service is running, absent to ensure it is not"), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] string Ensure;
>     [Required, Description("The farm account password, which is needed to provision the service app"), EmbeddedInstance("MSFT_Credential")] String FarmAccount;
> ```

I actually think I would put this back the way it was - asking for just the password makes it feel a little more confusing since they need to give a username anyway. 

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPUserProfileSyncService/readme.md, line 7 at r2](https://reviewable.io:443/reviews/powershell/sharepointdsc/637#-Kpw782DHQCvJNONnOKg:-Kpw782DHQCvJNONnOKh:b-4ohvgv) ([raw file](https://github.com/powershell/sharepointdsc/blob/94f0625502507511e83ac4a5bc11246ce6373401/Modules/SharePointDsc/DSCResources/MSFT_SPUserProfileSyncService/readme.md#L7)):*
> ```Markdown
> "Absent") on the current server.
> 
> This resource requires that the FarmAccount is specified as the InstallAccount
> ```

This should say "InstallAccount or PsDscRunAsCredential" - it reads like they have to pass InstallAccount now when they shouldn't be doing that for PowerShell 5

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/637#-:-Kpw9xa1OuhWx5uXivsw:b-a7mu0c)*

**Comment by ykuijs** [comment]
@BrianFarnhill, just a few questions about your remarks.

---

Review status: all files reviewed at latest revision, 10 unresolved discussions.

---

*[CHANGELOG.md, line 3 at r2](https://reviewable.io:443/reviews/powershell/sharepointdsc/637#-Kpw4bhkLbsRa6_vycEP:-KrgjlWMJ1zPBVuY0xyC:b-896fix) ([raw file](https://github.com/powershell/sharepointdsc/blob/94f0625502507511e83ac4a5bc11246ce6373401/CHANGELOG.md#L3)):*
<details><summary><i>Previously, BrianFarnhill (Brian Farnhill) wrote…</i></summary><blockquote>

Just make this "v2.0" because we'll do a release right after we get this together
</blockquote></details>

Done.

---

*[CHANGELOG.md, line 5 at r2](https://reviewable.io:443/reviews/powershell/sharepointdsc/637#-Kpw4nEHNBsyn0LdH6Ct:-Krgjm6Pk_yQkkcswSP4:b-896fix) ([raw file](https://github.com/powershell/sharepointdsc/blob/94f0625502507511e83ac4a5bc11246ce6373401/CHANGELOG.md#L5)):*
<details><summary><i>Previously, BrianFarnhill (Brian Farnhill) wrote…</i></summary><blockquote>

> the use these resources

should be "that use these resources"
</blockquote></details>

Done.

---

*[CHANGELOG.md, line 12 at r2](https://reviewable.io:443/reviews/powershell/sharepointdsc/637#-Kpw4ikck6WMO1JgTsiY:-KrgjmsD7ZQL-v2o4IKO:b-896fix) ([raw file](https://github.com/powershell/sharepointdsc/blob/94f0625502507511e83ac4a5bc11246ce6373401/CHANGELOG.md#L12)):*
<details><summary><i>Previously, BrianFarnhill (Brian Farnhill) wrote…</i></summary><blockquote>

No need for a second unreleased header 
</blockquote></details>

Done.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPUserProfileServiceApp/MSFT_SPUserProfileServiceApp.psm1, line 94 at r2](https://reviewable.io:443/reviews/powershell/sharepointdsc/637#-Kpw5cwrmaYSIdPghbRl:-KrgjoITP7C3hL86susH:b-896fix) ([raw file](https://github.com/powershell/sharepointdsc/blob/94f0625502507511e83ac4a5bc11246ce6373401/Modules/SharePointDsc/DSCResources/MSFT_SPUserProfileServiceApp/MSFT_SPUserProfileServiceApp.psm1#L94)):*
<details><summary><i>Previously, BrianFarnhill (Brian Farnhill) wrote…</i></summary><blockquote>

Can we inject the user name in here to make it obvious what account it should be running as?
</blockquote></details>

Done.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPUserProfileServiceApp/MSFT_SPUserProfileServiceApp.psm1, line 248 at r2](https://reviewable.io:443/reviews/powershell/sharepointdsc/637#-Kpw5oELH7evEQuybxLl:-KrgjrfrReJpp_nLsClP:b8wbzh6) ([raw file](https://github.com/powershell/sharepointdsc/blob/94f0625502507511e83ac4a5bc11246ce6373401/Modules/SharePointDsc/DSCResources/MSFT_SPUserProfileServiceApp/MSFT_SPUserProfileServiceApp.psm1#L248)):*
<details><summary><i>Previously, BrianFarnhill (Brian Farnhill) wrote…</i></summary><blockquote>

Seeing as we are doing this check in multiple places, do we want to extract it to a helper function that throws the error there instead of duplicating the code in this file? 
</blockquote></details>

You mean a function to retrieve the farm account?

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPUserProfileServiceApp/readme.md, line 7 at r2](https://reviewable.io:443/reviews/powershell/sharepointdsc/637#-Kpw6DoEnyEjRZFvsgwB:-KrgjvrfM4X9LgVt3fqx:bny77ey) ([raw file](https://github.com/powershell/sharepointdsc/blob/94f0625502507511e83ac4a5bc11246ce6373401/Modules/SharePointDsc/DSCResources/MSFT_SPUserProfileServiceApp/readme.md#L7)):*
<details><summary><i>Previously, BrianFarnhill (Brian Farnhill) wrote…</i></summary><blockquote>

Need a full stop on the end of this line. 
</blockquote></details>

You mean a period?

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPUserProfileSyncService/MSFT_SPUserProfileSyncService.psm1, line 36 at r2](https://reviewable.io:443/reviews/powershell/sharepointdsc/637#-Kpw6JQORlk9pcpqC5Dk:-KrgjyRTwzu-IUBMGOb3:b8wbzh6) ([raw file](https://github.com/powershell/sharepointdsc/blob/94f0625502507511e83ac4a5bc11246ce6373401/Modules/SharePointDsc/DSCResources/MSFT_SPUserProfileSyncService/MSFT_SPUserProfileSyncService.psm1#L36)):*
<details><summary><i>Previously, BrianFarnhill (Brian Farnhill) wrote…</i></summary><blockquote>

Same comment as above about taking this logic in to a helper function/module
</blockquote></details>

You mean a function to retrieve the farm account?

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPUserProfileSyncService/MSFT_SPUserProfileSyncService.psm1, line 177 at r2](https://reviewable.io:443/reviews/powershell/sharepointdsc/637#-Kpw6OmnZmE9KyP1sysr:-Krgk0MUk4bXwkrJG3mH:b8wbzh6) ([raw file](https://github.com/powershell/sharepointdsc/blob/94f0625502507511e83ac4a5bc11246ce6373401/Modules/SharePointDsc/DSCResources/MSFT_SPUserProfileSyncService/MSFT_SPUserProfileSyncService.psm1#L177)):*
<details><summary><i>Previously, BrianFarnhill (Brian Farnhill) wrote…</i></summary><blockquote>

Same comment as above about taking this logic in to a helper function/module
</blockquote></details>

You mean a function to retrieve the farm account?

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPUserProfileSyncService/MSFT_SPUserProfileSyncService.schema.mof, line 6 at r2](https://reviewable.io:443/reviews/powershell/sharepointdsc/637#-Kpw6Z85YmcoxhjE1mwP:-Krgk1zB2E6Kpc3S0wTf:b-896fix) ([raw file](https://github.com/powershell/sharepointdsc/blob/94f0625502507511e83ac4a5bc11246ce6373401/Modules/SharePointDsc/DSCResources/MSFT_SPUserProfileSyncService/MSFT_SPUserProfileSyncService.schema.mof#L6)):*
<details><summary><i>Previously, BrianFarnhill (Brian Farnhill) wrote…</i></summary><blockquote>

I actually think I would put this back the way it was - asking for just the password makes it feel a little more confusing since they need to give a username anyway. 
</blockquote></details>

Done.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPUserProfileSyncService/readme.md, line 7 at r2](https://reviewable.io:443/reviews/powershell/sharepointdsc/637#-Kpw782DHQCvJNONnOKg:-Krgk2sqzXnMrkIMer_b:b-896fix) ([raw file](https://github.com/powershell/sharepointdsc/blob/94f0625502507511e83ac4a5bc11246ce6373401/Modules/SharePointDsc/DSCResources/MSFT_SPUserProfileSyncService/readme.md#L7)):*
<details><summary><i>Previously, BrianFarnhill (Brian Farnhill) wrote…</i></summary><blockquote>

This should say "InstallAccount or PsDscRunAsCredential" - it reads like they have to pass InstallAccount now when they shouldn't be doing that for PowerShell 5
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/637#-:-Krgk4AQrNFL6s57YXwI:b-4ap8ea)*

**Comment by BrianFarnhill** [comment]
@ykuijs Did you miss actually pushing the code here mate? I see your comments on reviewable but no actual changes in the code?

**Comment by BrianFarnhill** [comment]
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPUserProfileServiceApp/MSFT_SPUserProfileServiceApp.psm1, line 248 at r2](https://reviewable.io:443/reviews/powershell/sharepointdsc/637#-Kpw5oELH7evEQuybxLl:-Ks1CyMRuHV8R2YxQx4_:b-gc2gzq) ([raw file](https://github.com/powershell/sharepointdsc/blob/94f0625502507511e83ac4a5bc11246ce6373401/Modules/SharePointDsc/DSCResources/MSFT_SPUserProfileServiceApp/MSFT_SPUserProfileServiceApp.psm1#L248)):*
<details><summary><i>Previously, ykuijs (Yorick Kuijs) wrote…</i></summary><blockquote>

You mean a function to retrieve the farm account?
</blockquote></details>

Yep, that

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPUserProfileServiceApp/readme.md, line 7 at r2](https://reviewable.io:443/reviews/powershell/sharepointdsc/637#-Kpw6DoEnyEjRZFvsgwB:-Ks1Czhl_rZx8_H_rkX4:b-tr616i) ([raw file](https://github.com/powershell/sharepointdsc/blob/94f0625502507511e83ac4a5bc11246ce6373401/Modules/SharePointDsc/DSCResources/MSFT_SPUserProfileServiceApp/readme.md#L7)):*
<details><summary><i>Previously, ykuijs (Yorick Kuijs) wrote…</i></summary><blockquote>

You mean a period?
</blockquote></details>

Yea, same thing - different locale :P 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/637)*

**Comment by ykuijs** [comment]
Correct, I did that on purpose so I could incorporate your answers to my questions. Have just pushed a new commit.

---

Review status: 15 of 22 files reviewed at latest revision, 10 unresolved discussions.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPUserProfileServiceApp/MSFT_SPUserProfileServiceApp.psm1, line 248 at r2](https://reviewable.io:443/reviews/powershell/sharepointdsc/637#-Kpw5oELH7evEQuybxLl:-Ks8-JBDFVUSLfTA51XO:b-896fix) ([raw file](https://github.com/powershell/sharepointdsc/blob/94f0625502507511e83ac4a5bc11246ce6373401/Modules/SharePointDsc/DSCResources/MSFT_SPUserProfileServiceApp/MSFT_SPUserProfileServiceApp.psm1#L248)):*
<details><summary><i>Previously, BrianFarnhill (Brian Farnhill) wrote…</i></summary><blockquote>

Yep, that
</blockquote></details>

Done.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPUserProfileServiceApp/readme.md, line 7 at r2](https://reviewable.io:443/reviews/powershell/sharepointdsc/637#-Kpw6DoEnyEjRZFvsgwB:-Ks8-Kno4TJCyt4nj-C0:b-896fix) ([raw file](https://github.com/powershell/sharepointdsc/blob/94f0625502507511e83ac4a5bc11246ce6373401/Modules/SharePointDsc/DSCResources/MSFT_SPUserProfileServiceApp/readme.md#L7)):*
<details><summary><i>Previously, BrianFarnhill (Brian Farnhill) wrote…</i></summary><blockquote>

Yea, same thing - different locale :P 
</blockquote></details>

Done.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPUserProfileSyncService/MSFT_SPUserProfileSyncService.psm1, line 36 at r2](https://reviewable.io:443/reviews/powershell/sharepointdsc/637#-Kpw6JQORlk9pcpqC5Dk:-Ks8-LurOUGL4-Hi_6QA:b-896fix) ([raw file](https://github.com/powershell/sharepointdsc/blob/94f0625502507511e83ac4a5bc11246ce6373401/Modules/SharePointDsc/DSCResources/MSFT_SPUserProfileSyncService/MSFT_SPUserProfileSyncService.psm1#L36)):*
<details><summary><i>Previously, ykuijs (Yorick Kuijs) wrote…</i></summary><blockquote>

You mean a function to retrieve the farm account?
</blockquote></details>

Done.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPUserProfileSyncService/MSFT_SPUserProfileSyncService.psm1, line 177 at r2](https://reviewable.io:443/reviews/powershell/sharepointdsc/637#-Kpw6OmnZmE9KyP1sysr:-Ks8-Mbn-gyavN6Wz3EW:b-896fix) ([raw file](https://github.com/powershell/sharepointdsc/blob/94f0625502507511e83ac4a5bc11246ce6373401/Modules/SharePointDsc/DSCResources/MSFT_SPUserProfileSyncService/MSFT_SPUserProfileSyncService.psm1#L177)):*
<details><summary><i>Previously, ykuijs (Yorick Kuijs) wrote…</i></summary><blockquote>

You mean a function to retrieve the farm account?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/637#-:-Ks7zw6WT-gDaWQ1kJBH:b7o2tes)*

**Comment by BrianFarnhill** [comment]
:lgtm:

---

Reviewed 7 of 28 files at r3, 22 of 22 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/637#-:-KsLbr84i0Uz0ZhrhEk_:bnfp4nl)*

**Pull request merged**
