### PR TITLE
Fix Issues with Aliases and Crawled Property Mapping

### PR DESCRIPTION
**Pull request by NikCharlebois**
#### Pull Request (PR) description
Fix Issues with Aliases and Crawled Property Mapping

#### This Pull Request (PR) fixes the following issues
N/A

#### Task list
- [x] Added an entry under the Unreleased section of the change log in the CHANGELOG.md.
      Entry should say what was changed, and how that affects users (if applicable).
- [x] Resource documentation added/updated in README.md in the resource folder.
- [x] Resource parameter descriptions added/updated in schema.mof
      and comment-based help.
- [x] Comment-based help added/updated.
- [x] Localization strings added/updated in all localization files as appropriate.
- [x] Examples appropriately added/updated.
- [x] Unit tests added/updated. See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [x] Integration tests added/updated (where possible). See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [x] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/sharepointdsc/919)

### CODE REVIEW

**Comment by ykuijs** [comment]
Closing and reopening PR to kick off AppVeyor run

**Comment by ykuijs** [comment]
Two tests fail and this PR needs a merge from Dev

**Comment by NikCharlebois** [comment]
Sure, again here. It depends when this fix will be released, since this is a new resource and there is already an entry mentioning that it is a new one. I will add a second bullet anyway.

**Comment by ykuijs** [comment]
Ok my bad, I checked if this was a new resource but apparently overlooked the entry......sorry ;-)

**Pull request merged**
