### PR TITLE
Fix get of ups

### PR DESCRIPTION
**Pull request by NikCharlebois**
Converted the error thrown by the SPUserProfileServiceApp resource thrown by the Get-TargetResource function when the current user is the Farm account into becoming a warning.

- [x] Change details added to Unreleased section of changelog.md?
- [x] Added/updated documentation and descriptions in .schema.mof files where appropriate?
- [x] Examples updated for both the single server and small farm templates in the examples folder?
- [x] New/changed code adheres to [Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md)?
- [x] [Unit and Integration tests](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md) created/updated where possible?

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/sharepointdsc/817)

### CODE REVIEW

**Comment by ykuijs** [comment]
Please make sure the message also includes a warning. I.e.: "Specified PSDSCRunAsCredential ($localaccount) is the Farm Account. Please note that this will cause issues when applying the configuration."

**Comment by ykuijs** [comment]
Don't forget to update the Changelog

---

Review status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @NikCharlebois)

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPUserProfileServiceApp/MSFT_SPUserProfileServiceApp.psm1, line 98 at r1](https://reviewable.io/reviews/powershell/sharepointdsc/817#-LEkGF5QCHkB9TyJlQ7v:-LEkGF5QCHkB9TyJlQ7w:b-kjfj9s) ([raw file](https://github.com/powershell/sharepointdsc/blob/be0b9cf6a4a4e979695fe130cac97c031ec50981/Modules/SharePointDsc/DSCResources/MSFT_SPUserProfileServiceApp/MSFT_SPUserProfileServiceApp.psm1#L98)):*
> ```PowerShell
>                 if ($localaccount -eq $farmAccount.UserName)
>                 {
>                     Write-Verbose -Message ("The current user ($localaccount) is the Farm " + `
> ```

Please update the message to "Specified PSDSCRunAsCredential ($localaccount) is the Farm Account. Please note that this will cause issues when applying the configuration."

---

*[Tests/Unit/SharePointDsc/SharePointDsc.SPUserProfileServiceApp.Tests.ps1, line 96 at r1](https://reviewable.io/reviews/powershell/sharepointdsc/817#-LEkG13DCpetNZVIN5PO:-LEkG13DCpetNZVIN5PP:blrnr9v) ([raw file](https://github.com/powershell/sharepointdsc/blob/be0b9cf6a4a4e979695fe130cac97c031ec50981/Tests/Unit/SharePointDsc/SharePointDsc.SPUserProfileServiceApp.Tests.ps1#L96)):*
> ```PowerShell
> 
>             It "Should NOT throw exception in the Get method" {
>                 { Get-TargetResource @testParams } | (Get-TargetResource @testParams).Ensure | Should Be "Present"
> ```

Remove "{ Get-TargetResource @testParams }", this is not required.

---


*Comments from [Reviewable](https://reviewable.io/reviews/powershell/sharepointdsc/817#-:-LEkGK6f1q0RGrks3cPC:b-83qbl7)*

**Comment by NikCharlebois** [comment]
Review status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @ykuijs and @NikCharlebois)

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPUserProfileServiceApp/MSFT_SPUserProfileServiceApp.psm1, line 98 at r1](https://reviewable.io/reviews/powershell/sharepointdsc/817#-LEkGF5QCHkB9TyJlQ7v:-LEkJ3E_3x86F6aim_ZK:bh21gle) ([raw file](https://github.com/powershell/sharepointdsc/blob/be0b9cf6a4a4e979695fe130cac97c031ec50981/Modules/SharePointDsc/DSCResources/MSFT_SPUserProfileServiceApp/MSFT_SPUserProfileServiceApp.psm1#L98)):*
<details><summary><i>Previously, ykuijs (Yorick Kuijs) wrote…</i></summary><blockquote>

Please update the message to "Specified PSDSCRunAsCredential ($localaccount) is the Farm Account. Please note that this will cause issues when applying the configuration."
</blockquote></details>

I think this will be too confusing for the user. The warning is thrown if the Current User is the farm account, not the PSDSCRunAsCredential. This user only gets elevated a few lines down. I recommend we keep the message as-is for clarity.

---

*[Tests/Unit/SharePointDsc/SharePointDsc.SPUserProfileServiceApp.Tests.ps1, line 96 at r1](https://reviewable.io/reviews/powershell/sharepointdsc/817#-LEkG13DCpetNZVIN5PO:-LEkJd6x9EfopIm3GeFb:b-896fix) ([raw file](https://github.com/powershell/sharepointdsc/blob/be0b9cf6a4a4e979695fe130cac97c031ec50981/Tests/Unit/SharePointDsc/SharePointDsc.SPUserProfileServiceApp.Tests.ps1#L96)):*
<details><summary><i>Previously, ykuijs (Yorick Kuijs) wrote…</i></summary><blockquote>

Remove "{ Get-TargetResource @testParams }", this is not required.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/powershell/sharepointdsc/817)*

**Comment by ykuijs** [comment]
:lgtm:

---

Review status: 0 of 3 files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/powershell/sharepointdsc/817#-:-LEkP6P02k46QNX1oVlv:bnfp4nl)*

**Comment by ykuijs** [comment]
Reviewed 3 of 3 files at r2.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/powershell/sharepointdsc/817)*

**Comment by ykuijs** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/powershell/sharepointdsc/817#-:-LErtcrZDgC29A9tZsqR:bnfp4nl)*

**Pull request merged**
