### PR TITLE
SPProductUpdate: Closing Issue 679 v3.2 (WIP: Unit Tests)

### LINKED ISSUE #679: SPProductUpdate and SPLanguagePack conflict
**Details of the scenario you try and problem that is occurring:**
This was originally reported on the "SharePointDSC Best Practices and Gotchas Post" http://nikcharlebois.com/sharepoint-dsc-gotchas-and-best-practices/

In theory, it should be possible for someone to install, in order, a PU, a Language specific patch, and then run the config wizard. That scenario works just fine if done manually. However, with the SPDSC module, if you specify two SPProductUpdate blocks in a row, and then call the SPConfigWizard, it will skip over the second one because of the way we use B2B and will throw the following message:

Write-Verbose -Message ("An upgrade is pending. " + `
                                "To prevent a possible loop, the install will be skipped")

If this can be done manually, then we should look at having the DSC module allow it as well, given that Language specific patches are now separate from the main CU/PU.

**The DSC configuration that is using the resource:**
N/A

**Version of the Operating System and PowerShell the DSC Target Node is running:**
Win 2016/WMF 5.1

**Version of the DSC module you're using:**
1.9.0.0

### PR DESCRIPTION
**Pull request by andikrueger**
#### Pull Request (PR) description
This PR Fixes #679 with updating SharePoint server and using Language Pack resources at the same time. This fix also allows to keep SPProductUodate Resource descriptions in the configuration. This fix also enable the run several product updates in one configuration without having a farm. 

This PR needs some additional unit test to reflect the changes to the resource properly. 
@ykuijs Really hope you can work with this branch. Currently the tests do already import the RTM registry keys. Currently missing are tests with a CU or SP in place. For those tests to run successfully there is the need the mock the .msp data and provide test values for newer and lower CU versions than we have within those systems you took the registry from. 

#### This Pull Request (PR) fixes the following issues

    - Fixes #679

#### Task list

- [ ] Added an entry under the Unreleased section of the change log in the CHANGELOG.md.
      Entry should say what was changed, and how that affects users (if applicable).
- [ ] Resource documentation added/updated in README.md in the resource folder.
- [ ] Resource parameter descriptions added/updated in schema.mof
      and comment-based help.
- [ ] Comment-based help added/updated.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [ ] Examples appropriately added/updated.
- [ ] Unit tests added/updated. See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] Integration tests added/updated (where possible). See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/sharepointdsc/1046)

### CODE REVIEW

**Comment by ykuijs** [comment]
Quick push of some changes I added:
I have updated the tests, but still need to add a few more tests. Will push these later today.

**Comment by ykuijs** [comment]
@NikCharlebois Are you up for a review?

**Comment by andikrueger** [comment]
@ykuijs fantastic work on the tests! Thank you so much!

**Comment by NikCharlebois** [comment]
@ykuijs On it

**Pull request merged**
