### PR TITLE
Added resource MSFT_SPTrustedIdentityTokenIssuer

### PR DESCRIPTION
**Pull request by Yvand**
Thanks for submitting a Pull Request to this project.

Please make sure you have read the [Contribution Guidelines](https://github.com/powershell/xSharePoint/wiki/Contributing%20to%20xSharePoint).

To aid community reviewers in reviewing and merging your PR, please take the time to run through this checklist:
- [ ] Change details added to Unreleased section of readme.md?
- [ ] Added/updated documentation and descriptions in .schema.mof files where appropriate?
- [ ] Examples updated for both the single server and small farm templates in the examples folder?
- [ ] New/changed code adheres to [Style Guidelines]?(https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md)?
- [ ] [Unit and Integration tests](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md) created/updated where possible?

Your contribution to this project is greatly appreciated.

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/sharepointdsc/361)

### CODE REVIEW

**Comment by BrianFarnhill** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 13 unresolved discussions, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/powershell/sharepointdsc/361#-KLslJwQxvPkTTrzBvWz:-KLslJwQxvPkTTrzBvX-:235591810) (no related file):*
Some initial feedback below. I'll run it against a server for an integration test soon to see how it behaves.

---

*[README.md, line 51 \[r1\]](https://reviewable.io:443/reviews/powershell/sharepointdsc/361#-KLsiezu66puo2I2z9Tj:-KLsiezu66puo2I2z9Tk:1181555967) ([raw file](https://github.com/powershell/sharepointdsc/blob/e7b6415947129fa1fc64811fd1ab93d21c1c4761/README.md#L51)):*
> ```Markdown
> 
> ### Unreleased
> - Added resource MSFT_SPTrustedIdentityTokenIssuer
> ```

Our mistake on the guidance here - this section should be in the CHANGELOG.md file - not the readme any more. I'll fix the GitHub template to say this.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPTrustedIdentityTokenIssuer/MSFT_SPTrustedIdentityTokenIssuer.mof, line 6 \[r1\]](https://reviewable.io:443/reviews/powershell/sharepointdsc/361#-KLsirRPCP1PkzB3B9rF:-KLsirRPCP1PkzB3B9rG:798708815) ([raw file](https://github.com/powershell/sharepointdsc/blob/e7b6415947129fa1fc64811fd1ab93d21c1c4761/Modules/SharePointDsc/DSCResources/MSFT_SPTrustedIdentityTokenIssuer/MSFT_SPTrustedIdentityTokenIssuer.mof#L6)):*
> ```
> 
> This resource is used to make sure that a specific SPTrustedIdentityTokenIssuer is either present or absent in a farm.
> The Ensure property will dictate if the SPTrustedIdentityTokenIssuer should be present or absent. 
> ```

Rather than explain each property here, you can just describe the properties in the description metadata in the actual schema below. You can see how the documentation is generated to show these descriptions in [some of our existing doco](https://github.com/PowerShell/SharePointDsc/wiki/SPCreateFarm)

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPTrustedIdentityTokenIssuer/MSFT_SPTrustedIdentityTokenIssuer.psm1, line 33 \[r1\]](https://reviewable.io:443/reviews/powershell/sharepointdsc/361#-KLsjgYZx3OOg2yg1pu6:-KLsjgYZx3OOg2yg1pu7:-1033865866) ([raw file](https://github.com/powershell/sharepointdsc/blob/e7b6415947129fa1fc64811fd1ab93d21c1c4761/Modules/SharePointDsc/DSCResources/MSFT_SPTrustedIdentityTokenIssuer/MSFT_SPTrustedIdentityTokenIssuer.psm1#L33)):*
> ```PowerShell
>         }
> 
>         return @{
> ```

The return value should include all of the properties that the resource has currently, not just the name and ensure (even though those are all you need for the test). Can you look add adding the other existing values to this 

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPTrustedIdentityTokenIssuer/MSFT_SPTrustedIdentityTokenIssuer.psm1, line 78 \[r1\]](https://reviewable.io:443/reviews/powershell/sharepointdsc/361#-KLsjzFop-BrIFXv9rk0:-KLsjzFop-BrIFXv9rk1:255051945) ([raw file](https://github.com/powershell/sharepointdsc/blob/e7b6415947129fa1fc64811fd1ab93d21c1c4761/Modules/SharePointDsc/DSCResources/MSFT_SPTrustedIdentityTokenIssuer/MSFT_SPTrustedIdentityTokenIssuer.psm1#L78)):*
> ```PowerShell
> 
>                 $ClaimsMappingsArray = @()
>                 $params.ClaimsMappings| %{
> ```

Instead of the % alias and you please use Foreach-Object here

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPTrustedIdentityTokenIssuer/MSFT_SPTrustedIdentityTokenIssuer.psm1, line 87 \[r1\]](https://reviewable.io:443/reviews/powershell/sharepointdsc/361#-KLsk5BAde1bZNfOIrcz:-KLsk5BAde1bZNfOIrd-:-658364707) ([raw file](https://github.com/powershell/sharepointdsc/blob/e7b6415947129fa1fc64811fd1ab93d21c1c4761/Modules/SharePointDsc/DSCResources/MSFT_SPTrustedIdentityTokenIssuer/MSFT_SPTrustedIdentityTokenIssuer.psm1#L87)):*
> ```PowerShell
>                 }
> 
>                 if (!($ClaimsMappingsArray| ?{$_.MappedClaimType -like $IdentifierClaim})) {
> ```

Instead of the ? alias can you please use Where-Object

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPTrustedIdentityTokenIssuer/MSFT_SPTrustedIdentityTokenIssuer.psm1, line 102 \[r1\]](https://reviewable.io:443/reviews/powershell/sharepointdsc/361#-KLskB4Hix1B4TIitRYU:-KLskB4Hix1B4TIitRYV:-658364707) ([raw file](https://github.com/powershell/sharepointdsc/blob/e7b6415947129fa1fc64811fd1ab93d21c1c4761/Modules/SharePointDsc/DSCResources/MSFT_SPTrustedIdentityTokenIssuer/MSFT_SPTrustedIdentityTokenIssuer.psm1#L102)):*
> ```PowerShell
>                 $trust = New-SPTrustedIdentityTokenIssuer @runParams
> 
>                 if ((Get-SPClaimProvider| ?{$_.DisplayName -like $ClaimProviderName})) {
> ```

Instead of the ? alias can you please use Where-Object

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPTrustedIdentityTokenIssuer/MSFT_SPTrustedIdentityTokenIssuer.psm1, line 116 \[r1\]](https://reviewable.io:443/reviews/powershell/sharepointdsc/361#-KLskFNmdW1w6CLtcPwK:-KLskFNmdW1w6CLtcPwL:993347584) ([raw file](https://github.com/powershell/sharepointdsc/blob/e7b6415947129fa1fc64811fd1ab93d21c1c4761/Modules/SharePointDsc/DSCResources/MSFT_SPTrustedIdentityTokenIssuer/MSFT_SPTrustedIdentityTokenIssuer.psm1#L116)):*
> ```PowerShell
>             $params = $args[0]
>             # SPTrustedIdentityTokenIssuer must be removed from each zone of each web app before it can be deleted
>             Get-SPWebApplication| %{
> ```

Instead of the % alias can you please use Foreach-Object

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPTrustedIdentityTokenIssuer/MSFT_SPTrustedIdentityTokenIssuer.psm1, line 118 \[r1\]](https://reviewable.io:443/reviews/powershell/sharepointdsc/361#-KLskNc8DZb6iq8v0yby:-KLskNc8DZb6iq8v0ybz:993347584) ([raw file](https://github.com/powershell/sharepointdsc/blob/e7b6415947129fa1fc64811fd1ab93d21c1c4761/Modules/SharePointDsc/DSCResources/MSFT_SPTrustedIdentityTokenIssuer/MSFT_SPTrustedIdentityTokenIssuer.psm1#L118)):*
> ```PowerShell
>             Get-SPWebApplication| %{
>                 $wa = $_
>                 [Enum]::GetNames( [Microsoft.SharePoint.Administration.SPUrlZone] )| %{
> ```

Instead of the % alias can you please use Foreach-Object

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPTrustedIdentityTokenIssuer/MSFT_SPTrustedIdentityTokenIssuer.psm1, line 122 \[r1\]](https://reviewable.io:443/reviews/powershell/sharepointdsc/361#-KLskRk1RHp6dWhwiAxz:-KLskRk1RHp6dWhwiAy-:558015893) ([raw file](https://github.com/powershell/sharepointdsc/blob/e7b6415947129fa1fc64811fd1ab93d21c1c4761/Modules/SharePointDsc/DSCResources/MSFT_SPTrustedIdentityTokenIssuer/MSFT_SPTrustedIdentityTokenIssuer.psm1#L122)):*
> ```PowerShell
>                     $providers = Get-SPAuthenticationProvider -WebApplication $wa.Url -Zone $_ -ErrorAction SilentlyContinue
>                     if (!$providers) { return }
>                     $providers| ?{$_ -is [Microsoft.SharePoint.Administration.SPTrustedAuthenticationProvider] -and $_.LoginProviderName -like $Name}| %{
> ```

Instead of the ? alias can you please use Where-Object, and instead of the % alias can you please use Foreach-Object

---

*[Tests/SharePointDsc/SharePointDsc.SPTrustedIdentityTokenIssuer.Tests.ps1, line 15 \[r1\]](https://reviewable.io:443/reviews/powershell/sharepointdsc/361#-KLskopZuLbOrAay1rOK:-KLskopZuLbOrAay1rOL:63081091) ([raw file](https://github.com/powershell/sharepointdsc/blob/e7b6415947129fa1fc64811fd1ab93d21c1c4761/Tests/SharePointDsc/SharePointDsc.SPTrustedIdentityTokenIssuer.Tests.ps1#L15)):*
> ```PowerShell
> Import-Module (Join-Path $RepoRoot "Modules\SharePointDsc\DSCResources\$ModuleName\$ModuleName.psm1") -Force
> 
> Write-Host "ModuleName: $ModuleName"
> ```

Can ou please remove this extra line, it's not needed as the describe statement tells us what is being tested

---

*[Tests/SharePointDsc/SharePointDsc.SPTrustedIdentityTokenIssuer.Tests.ps1, line 50 \[r1\]](https://reviewable.io:443/reviews/powershell/sharepointdsc/361#-KLsl-rK5krM4oBjOfKA:-KLsl-rK5krM4oBjOfKB:-39928305) ([raw file](https://github.com/powershell/sharepointdsc/blob/e7b6415947129fa1fc64811fd1ab93d21c1c4761/Tests/SharePointDsc/SharePointDsc.SPTrustedIdentityTokenIssuer.Tests.ps1#L50)):*
> ```PowerShell
>                 $sptrust| Add-Member -Name Update -MemberType ScriptMethod  -Value { }
>                 return $sptrust
>             } -Verifiable
> ```

You don't need to mark these as verifiable, you can just call the assert statements on them without this

---

*[Tests/SharePointDsc/SharePointDsc.SPTrustedIdentityTokenIssuer.Tests.ps1, line 74 \[r1\]](https://reviewable.io:443/reviews/powershell/sharepointdsc/361#-KLsl8b6xALSZ24zm7Fb:-KLsl8b76Z4S0GZHgqYX:-122428439) ([raw file](https://github.com/powershell/sharepointdsc/blob/e7b6415947129fa1fc64811fd1ab93d21c1c4761/Tests/SharePointDsc/SharePointDsc.SPTrustedIdentityTokenIssuer.Tests.ps1#L74)):*
> ```PowerShell
>         }
> 
>         Context "The SPTrustedIdentityTokenIssuer does not exist, but it should be present and claims provider specified does not exist" {
> ```

Are there tests missing from this context block? I only see one empty mock?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/361)*

**Comment by BrianFarnhill** [comment]
Reviewed 5 of 5 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/powershell/sharepointdsc/361#-KLslJwQxvPkTTrzBvWz:-KLx3DYGlYd0Z_Hda64S:47521206) (no related file):*
<details><summary><i>Previously, BrianFarnhill (Brian Farnhill) wrote…</i></summary>
> Some initial feedback below. I'll run it against a server for an integration test soon to see how it behaves.
</details>
Just did a quick run over your changes. Couple of little things - but you'll also need to do a pull from PowerShell/dev to get this to be mergable again (we just merged in a big change that rearranged the tests folder a little, so just watch how that goes

---

*[CHANGELOG.md, line 115 \[r2\]](https://reviewable.io:443/reviews/powershell/sharepointdsc/361#-KLx19UyDkqcqxWhx3wt:-KLx19UyDkqcqxWhx3wu:936179652) ([raw file](https://github.com/powershell/sharepointdsc/blob/63c231e8a078734ef500553402d8ab3b3c48779b/CHANGELOG.md#L115)):*
> ```Markdown
> * Initial public release of xSharePoint
> 
> ### Unreleased
> ```

The unreleased section goes at the top. If you do a pull from PowerShell/dev you'll get the latest changes and see that it will already be there, so you can just add yours to that list.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPTrustedIdentityTokenIssuer/MSFT_SPTrustedIdentityTokenIssuer.mof, line 45 \[r2\]](https://reviewable.io:443/reviews/powershell/sharepointdsc/361#-KLx1i5-9hC_1G5P_QBJ:-KLx1i503BH4tQ-248Jo:-1944336733) ([raw file](https://github.com/powershell/sharepointdsc/blob/63c231e8a078734ef500553402d8ab3b3c48779b/Modules/SharePointDsc/DSCResources/MSFT_SPTrustedIdentityTokenIssuer/MSFT_SPTrustedIdentityTokenIssuer.mof#L45)):*
> ```
>     [Write, Description("Name of a claims provider to set with this SPTrustedIdentityTokenIssuer.")] String ClaimProviderName;
>     [Write, Description("Sign-out URL")] String ProviderSignOutUri;
>     [Write, ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
> ```

Why did you take the description off the ensure property? The one you had previously was fine

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPTrustedIdentityTokenIssuer/MSFT_SPTrustedIdentityTokenIssuer.psm1, line 186 \[r2\]](https://reviewable.io:443/reviews/powershell/sharepointdsc/361#-KLx2kxkcvn0d6r0RD_B:-KLx2kxkcvn0d6r0RD_C:208478282) ([raw file](https://github.com/powershell/sharepointdsc/blob/63c231e8a078734ef500553402d8ab3b3c48779b/Modules/SharePointDsc/DSCResources/MSFT_SPTrustedIdentityTokenIssuer/MSFT_SPTrustedIdentityTokenIssuer.psm1#L186)):*
> ```PowerShell
>     )
> 
>     #Write-Verbose -Message "xTest if SPTrustedIdentityTokenIssuer '$Name' exists ..."
> ```

Can you put this comment back to the previous version - without the "x" in there and uncomment the line?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/361)*

**Comment by Yvand** [comment]
Hello, I just commited requested changes.
I also moved SharePointDsc.SPTrustedIdentityTokenIssuer.Tests.ps1 to Unit directory and updated relative paths to make sure it can pick modules.

**Comment by BrianFarnhill** [comment]
@Yvand This is looking better - can I get you to go in to reviewable and click "acknowledge" next to each of the feedback items to say your happy with them as well so I can close them off and finalise the review?

**Comment by Yvand** [comment]
Review status: 1 of 5 files reviewed at latest revision, 17 unresolved discussions.

---

*[CHANGELOG.md, line 114 \[r2\]](https://reviewable.io:443/reviews/powershell/sharepointdsc/361#-KM8Gl6qiu3aV_RSJV1w:-KM8Gl6r3r-9nPhu-9N7:166989) ([raw file](https://github.com/powershell/sharepointdsc/blob/5a00c8cb030aefdf0adf3e254673a9c8d96b6273/CHANGELOG.md#L114)):*
> ```Markdown
> 
> * Initial public release of xSharePoint
>  
> ```

²

---

*[CHANGELOG.md, line 115 \[r2\]](https://reviewable.io:443/reviews/powershell/sharepointdsc/361#-KLx19UyDkqcqxWhx3wt:-KM4R_uII5pqUZxRPdzz:-499146009) ([raw file](https://github.com/powershell/sharepointdsc/blob/63c231e8a078734ef500553402d8ab3b3c48779b/CHANGELOG.md#L115)):*
<details><summary><i>Previously, BrianFarnhill (Brian Farnhill) wrote…</i></summary>
> The unreleased section goes at the top. If you do a pull from PowerShell/dev you'll get the latest changes and see that it will already be there, so you can just add yours to that list.
</details>
Done.

---

*[README.md, line 51 \[r1\]](https://reviewable.io:443/reviews/powershell/sharepointdsc/361#-KLsiezu66puo2I2z9Tj:-KM4RgyVL8NZwxTuxxUO:-499146009) ([raw file](https://github.com/powershell/sharepointdsc/blob/e7b6415947129fa1fc64811fd1ab93d21c1c4761/README.md#L51)):*
<details><summary><i>Previously, BrianFarnhill (Brian Farnhill) wrote…</i></summary>
> Our mistake on the guidance here - this section should be in the CHANGELOG.md file - not the readme any more. I'll fix the GitHub template to say this.
</details>
Done.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPTrustedIdentityTokenIssuer/MSFT_SPTrustedIdentityTokenIssuer.mof, line 6 \[r1\]](https://reviewable.io:443/reviews/powershell/sharepointdsc/361#-KLsirRPCP1PkzB3B9rF:-KM4RjHy9MsTdiKMs0mr:-499146009) ([raw file](https://github.com/powershell/sharepointdsc/blob/e7b6415947129fa1fc64811fd1ab93d21c1c4761/Modules/SharePointDsc/DSCResources/MSFT_SPTrustedIdentityTokenIssuer/MSFT_SPTrustedIdentityTokenIssuer.mof#L6)):*
<details><summary><i>Previously, BrianFarnhill (Brian Farnhill) wrote…</i></summary>
> Rather than explain each property here, you can just describe the properties in the description metadata in the actual schema below. You can see how the documentation is generated to show these descriptions in [some of our existing doco](https://github.com/PowerShell/SharePointDsc/wiki/SPCreateFarm)
</details>
Done.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPTrustedIdentityTokenIssuer/MSFT_SPTrustedIdentityTokenIssuer.mof, line 45 \[r2\]](https://reviewable.io:443/reviews/powershell/sharepointdsc/361#-KLx1i5-9hC_1G5P_QBJ:-KM4Rkgy_zh8tJ-RvBKz:-1496508232) ([raw file](https://github.com/powershell/sharepointdsc/blob/63c231e8a078734ef500553402d8ab3b3c48779b/Modules/SharePointDsc/DSCResources/MSFT_SPTrustedIdentityTokenIssuer/MSFT_SPTrustedIdentityTokenIssuer.mof#L45)):*
<details><summary><i>Previously, BrianFarnhill (Brian Farnhill) wrote…</i></summary>
> Why did you take the description off the ensure property? The one you had previously was fine
</details>
Indeed, I put it back.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPTrustedIdentityTokenIssuer/MSFT_SPTrustedIdentityTokenIssuer.psm1, line 33 \[r1\]](https://reviewable.io:443/reviews/powershell/sharepointdsc/361#-KLsjgYZx3OOg2yg1pu6:-KM4RtN-vrJhktgsV4Wi:-499146009) ([raw file](https://github.com/powershell/sharepointdsc/blob/e7b6415947129fa1fc64811fd1ab93d21c1c4761/Modules/SharePointDsc/DSCResources/MSFT_SPTrustedIdentityTokenIssuer/MSFT_SPTrustedIdentityTokenIssuer.psm1#L33)):*
<details><summary><i>Previously, BrianFarnhill (Brian Farnhill) wrote…</i></summary>
> The return value should include all of the properties that the resource has currently, not just the name and ensure (even though those are all you need for the test). Can you look add adding the other existing values to this 
</details>
Done.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPTrustedIdentityTokenIssuer/MSFT_SPTrustedIdentityTokenIssuer.psm1, line 78 \[r1\]](https://reviewable.io:443/reviews/powershell/sharepointdsc/361#-KLsjzFop-BrIFXv9rk0:-KM4RuOgFS-Z5EGAFn9Q:-499146009) ([raw file](https://github.com/powershell/sharepointdsc/blob/e7b6415947129fa1fc64811fd1ab93d21c1c4761/Modules/SharePointDsc/DSCResources/MSFT_SPTrustedIdentityTokenIssuer/MSFT_SPTrustedIdentityTokenIssuer.psm1#L78)):*
<details><summary><i>Previously, BrianFarnhill (Brian Farnhill) wrote…</i></summary>
> Instead of the % alias and you please use Foreach-Object here
</details>
Done.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPTrustedIdentityTokenIssuer/MSFT_SPTrustedIdentityTokenIssuer.psm1, line 87 \[r1\]](https://reviewable.io:443/reviews/powershell/sharepointdsc/361#-KLsk5BAde1bZNfOIrcz:-KM4RuxGRBZ7yop37HRO:-499146009) ([raw file](https://github.com/powershell/sharepointdsc/blob/e7b6415947129fa1fc64811fd1ab93d21c1c4761/Modules/SharePointDsc/DSCResources/MSFT_SPTrustedIdentityTokenIssuer/MSFT_SPTrustedIdentityTokenIssuer.psm1#L87)):*
<details><summary><i>Previously, BrianFarnhill (Brian Farnhill) wrote…</i></summary>
> Instead of the ? alias can you please use Where-Object
</details>
Done.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPTrustedIdentityTokenIssuer/MSFT_SPTrustedIdentityTokenIssuer.psm1, line 102 \[r1\]](https://reviewable.io:443/reviews/powershell/sharepointdsc/361#-KLskB4Hix1B4TIitRYU:-KM4Rv_2tWIfjqN2yJnU:-499146009) ([raw file](https://github.com/powershell/sharepointdsc/blob/e7b6415947129fa1fc64811fd1ab93d21c1c4761/Modules/SharePointDsc/DSCResources/MSFT_SPTrustedIdentityTokenIssuer/MSFT_SPTrustedIdentityTokenIssuer.psm1#L102)):*
<details><summary><i>Previously, BrianFarnhill (Brian Farnhill) wrote…</i></summary>
> Instead of the ? alias can you please use Where-Object
</details>
Done.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPTrustedIdentityTokenIssuer/MSFT_SPTrustedIdentityTokenIssuer.psm1, line 116 \[r1\]](https://reviewable.io:443/reviews/powershell/sharepointdsc/361#-KLskFNmdW1w6CLtcPwK:-KM4Rw8M5lxT1GxchCMm:-499146009) ([raw file](https://github.com/powershell/sharepointdsc/blob/e7b6415947129fa1fc64811fd1ab93d21c1c4761/Modules/SharePointDsc/DSCResources/MSFT_SPTrustedIdentityTokenIssuer/MSFT_SPTrustedIdentityTokenIssuer.psm1#L116)):*
<details><summary><i>Previously, BrianFarnhill (Brian Farnhill) wrote…</i></summary>
> Instead of the % alias can you please use Foreach-Object
</details>
Done.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPTrustedIdentityTokenIssuer/MSFT_SPTrustedIdentityTokenIssuer.psm1, line 118 \[r1\]](https://reviewable.io:443/reviews/powershell/sharepointdsc/361#-KLskNc8DZb6iq8v0yby:-KM4S8tKxkrzRDaY72QS:-499146009) ([raw file](https://github.com/powershell/sharepointdsc/blob/e7b6415947129fa1fc64811fd1ab93d21c1c4761/Modules/SharePointDsc/DSCResources/MSFT_SPTrustedIdentityTokenIssuer/MSFT_SPTrustedIdentityTokenIssuer.psm1#L118)):*
<details><summary><i>Previously, BrianFarnhill (Brian Farnhill) wrote…</i></summary>
> Instead of the % alias can you please use Foreach-Object
</details>
Done.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPTrustedIdentityTokenIssuer/MSFT_SPTrustedIdentityTokenIssuer.psm1, line 122 \[r1\]](https://reviewable.io:443/reviews/powershell/sharepointdsc/361#-KLskRk1RHp6dWhwiAxz:-KM4S9l3rgfaZ6wQSkw8:-499146009) ([raw file](https://github.com/powershell/sharepointdsc/blob/e7b6415947129fa1fc64811fd1ab93d21c1c4761/Modules/SharePointDsc/DSCResources/MSFT_SPTrustedIdentityTokenIssuer/MSFT_SPTrustedIdentityTokenIssuer.psm1#L122)):*
<details><summary><i>Previously, BrianFarnhill (Brian Farnhill) wrote…</i></summary>
> Instead of the ? alias can you please use Where-Object, and instead of the % alias can you please use Foreach-Object
</details>
Done.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPTrustedIdentityTokenIssuer/MSFT_SPTrustedIdentityTokenIssuer.psm1, line 186 \[r2\]](https://reviewable.io:443/reviews/powershell/sharepointdsc/361#-KLx2kxkcvn0d6r0RD_B:-KM4RY8SmKtox-4i8b7z:-499146009) ([raw file](https://github.com/powershell/sharepointdsc/blob/63c231e8a078734ef500553402d8ab3b3c48779b/Modules/SharePointDsc/DSCResources/MSFT_SPTrustedIdentityTokenIssuer/MSFT_SPTrustedIdentityTokenIssuer.psm1#L186)):*
<details><summary><i>Previously, BrianFarnhill (Brian Farnhill) wrote…</i></summary>
> Can you put this comment back to the previous version - without the "x" in there and uncomment the line?
</details>
Done.

---

*[Tests/Unit/SharePointDsc/SharePointDsc.SPTrustedIdentityTokenIssuer.Tests.ps1, line 50 \[r1\]](https://reviewable.io:443/reviews/powershell/sharepointdsc/361#-KLsl-rK5krM4oBjOfKA:-KM4SuMWkp_U6XPMSozC:-499146009) ([raw file](https://github.com/powershell/sharepointdsc/blob/e7b6415947129fa1fc64811fd1ab93d21c1c4761/Tests/Unit/SharePointDsc/SharePointDsc.SPTrustedIdentityTokenIssuer.Tests.ps1#L50)):*
<details><summary><i>Previously, BrianFarnhill (Brian Farnhill) wrote…</i></summary>
> You don't need to mark these as verifiable, you can just call the assert statements on them without this
</details>
Done.

---

*[Tests/Unit/SharePointDsc/SharePointDsc.SPTrustedIdentityTokenIssuer.Tests.ps1, line 74 \[r1\]](https://reviewable.io:443/reviews/powershell/sharepointdsc/361#-KLsl8b6xALSZ24zm7Fb:-KM4SyTJc2qcwgl950CG:-499146009) ([raw file](https://github.com/powershell/sharepointdsc/blob/e7b6415947129fa1fc64811fd1ab93d21c1c4761/Tests/Unit/SharePointDsc/SharePointDsc.SPTrustedIdentityTokenIssuer.Tests.ps1#L74)):*
<details><summary><i>Previously, BrianFarnhill (Brian Farnhill) wrote…</i></summary>
> Are there tests missing from this context block? I only see one empty mock?
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/361)*

**Comment by Yvand** [comment]
Review status: 1 of 5 files reviewed at latest revision, 4 unresolved discussions.

---

*[CHANGELOG.md, line 114 \[r2\]](https://reviewable.io:443/reviews/powershell/sharepointdsc/361#-KM8Gl6qiu3aV_RSJV1w:-KM8JOkEzVNRguaoIyqA:-499146009) ([raw file](https://github.com/powershell/sharepointdsc/blob/5a00c8cb030aefdf0adf3e254673a9c8d96b6273/CHANGELOG.md#L114)):*
<details><summary><i>Previously, Yvand (Yvan Duhamel) wrote…</i></summary>
> ²
</details>
Done.

---

*[Tests/Unit/SharePointDsc/SharePointDsc.SPTrustedIdentityTokenIssuer.Tests.ps1, line 15 \[r1\]](https://reviewable.io:443/reviews/powershell/sharepointdsc/361#-KLskopZuLbOrAay1rOK:-KM8J0QvsYGQxU3APnQ4:1082326186) ([raw file](https://github.com/powershell/sharepointdsc/blob/e7b6415947129fa1fc64811fd1ab93d21c1c4761/Tests/Unit/SharePointDsc/SharePointDsc.SPTrustedIdentityTokenIssuer.Tests.ps1#L15)):*
<details><summary><i>Previously, BrianFarnhill (Brian Farnhill) wrote…</i></summary>
> Can ou please remove this extra line, it's not needed as the describe statement tells us what is being tested
</details>
I'm not sure which link you are referring to, can you please make it explicit?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/361)*

**Comment by Yvand** [comment]
Review status: 1 of 5 files reviewed at latest revision, 3 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/powershell/sharepointdsc/361#-KLslJwQxvPkTTrzBvWz:-KM8JZr40tKlxPb5T87U:1633590629) (no related file):*
<details><summary><i>Previously, BrianFarnhill (Brian Farnhill) wrote…</i></summary>
> Just did a quick run over your changes. Couple of little things - but you'll also need to do a pull from PowerShell/dev to get this to be mergable again (we just merged in a big change that rearranged the tests folder a little, so just watch how that goes
</details>
I did it, thanks

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/361)*

**Comment by Yvand** [comment]
I hope I acknowledged items as expected in Reviewable but to be honest the tool is not very intuitive to me so I hope I did it as you requested :)

**Comment by BrianFarnhill** [comment]
Reviewed 2 of 5 files at r3, 3 of 3 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/361)*

**Pull request merged**
