### PR TITLE
X sp search authoratative pages

### PR DESCRIPTION
**Pull request by mrpullen**
#32 Work 

Resource to configure Search Authoritative / Demoted Pages. This resource enables you to configure each page as a distinct resource. The implementation suggested in the Issue above was to configure all the rules using a single resource. This seemed like an easier way to implement, then you could use a for loop in your configuration to generate the configuration for multiple values.

First thing it looks like I will need todo is to fix my spelling..

- [x] Change details added to Unreleased section of changelog.md?
- [x] Added/updated documentation and descriptions in .schema.mof files where appropriate?
- [x] Examples updated for both the single server and small farm templates in the examples folder?
- [x] New/changed code adheres to [Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md)?
- [x] [Unit and Integration tests](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md) created/updated where possible?

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/sharepointdsc/530)

### CODE REVIEW

**Comment by mrpullen** [comment]
Can someone familiar with the Pester Tests take a look? I have to create some [Microsoft.Office] objects to run the powershell, but I don't know how to mock the New-Object with different parameters / and / or Mock an Enum value..

Tx.

**Comment by mrpullen** [comment]
Any ideas on this failure? The issue is that I have an object type in two test files, and once it is loaded once it can't be loaded again.. Should these objects be loaded once outside of a specific test file??

**Comment by BrianFarnhill** [comment]
I'm not sure what's triggering this at first glance. Realistically we load every type twice anyway as every single test file gets run twice, once for SP2013 and once for SP2016, so I wouldn't think loading it twice should make a difference. Just for the sake of consistency though, instead of putting it in a separate cs file, could you do it inline like all of our other resources? Here's an example

        Add-Type -TypeDefinition @"
            namespace Microsoft.Office.Server.Search.Administration
            {
                public class SearchObjectLevel {
                    public static string Ssa { get { return ""; } }
                }
            }
    "@

---

Review status: 0 of 8 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/530#-:-KfAMliOiRflPYdaYLAM:b-knbumi)*

**Comment by mrpullen** [comment]
Added what I hope fill check and stop it from adding a type if a type already exists..

**Comment by BrianFarnhill** [comment]
The code coverage stats don't look like they are being picked up here for some reason, but if you can make the other changes here I'll have a look at that and see what we can do.

---

Reviewed 9 of 13 files at r2, 1 of 4 files at r3, 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 10 unresolved discussions, some commit checks failed.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPSearchAuthoritativePage/MSFT_SPSearchAuthoritativePage.psm1, line 54 at r4](https://reviewable.io:443/reviews/powershell/sharepointdsc/530#-KfcunAZylrynI8T3jit:-KfcunAZylrynI8T3jiu:b-se6jqq) ([raw file](https://github.com/powershell/sharepointdsc/blob/da723187d91b12feecca0f4fab4f65d21eb69769/Modules/SharePointDsc/DSCResources/MSFT_SPSearchAuthoritativePage/MSFT_SPSearchAuthoritativePage.psm1#L54)):*
> New-Object Microsoft.Office.Server.Search.Administration.SearchObjectOwner($searchObjectLevel)

This shouldn't use positional parameters, use -TypeName and -ArgumentsList 

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPSearchAuthoritativePage/MSFT_SPSearchAuthoritativePage.psm1, line 150 at r4](https://reviewable.io:443/reviews/powershell/sharepointdsc/530#-Kfcv458cxttJcwa4Q8E:-Kfcv458cxttJcwa4Q8F:bx9560o) ([raw file](https://github.com/powershell/sharepointdsc/blob/da723187d91b12feecca0f4fab4f65d21eb69769/Modules/SharePointDsc/DSCResources/MSFT_SPSearchAuthoritativePage/MSFT_SPSearchAuthoritativePage.psm1#L150)):*
> ```PowerShell
>             $serviceApp = Get-SPEnterpriseSearchServiceApplication -Identity $params.ServiceAppName
>             $searchObjectLevel = [Microsoft.Office.Server.Search.Administration.SearchObjectLevel]::Ssa
>             $searchOwner = New-Object Microsoft.Office.Server.Search.Administration.SearchObjectOwner($searchObjectLevel)
> ```

Same remark about positional parameters

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPSearchAuthoritativePage/MSFT_SPSearchAuthoritativePage.psm1, line 158 at r4](https://reviewable.io:443/reviews/powershell/sharepointdsc/530#-KfcvJBXBzjRfTLZ92-z:-KfcvJBXBzjRfTLZ920-:b-m43pzv) ([raw file](https://github.com/powershell/sharepointdsc/blob/da723187d91b12feecca0f4fab4f65d21eb69769/Modules/SharePointDsc/DSCResources/MSFT_SPSearchAuthoritativePage/MSFT_SPSearchAuthoritativePage.psm1#L158)):*
> ```PowerShell
>             if($params.Action -eq "Authoratative")
>             {
>                  New-SPEnterpriseSearchQueryAuthority -Url $params.Path -SearchApplication $serviceApp -Owner $searchOwner -Level $params.Level
> ```

Can we wrap this line so we don't go over the 100 character length recommendation in the style guidelines

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPSearchAuthoritativePage/MSFT_SPSearchAuthoritativePage.psm1, line 184 at r4](https://reviewable.io:443/reviews/powershell/sharepointdsc/530#-KfcvPaF8_sucoI94nOq:-KfcvPaF8_sucoI94nOr:b-m43pzv) ([raw file](https://github.com/powershell/sharepointdsc/blob/da723187d91b12feecca0f4fab4f65d21eb69769/Modules/SharePointDsc/DSCResources/MSFT_SPSearchAuthoritativePage/MSFT_SPSearchAuthoritativePage.psm1#L184)):*
> ```PowerShell
>             if($params.Action -eq "Authoratative")
>             {
>                 Set-SPEnterpriseSearchQueryAuthority -Identity $params.ServiceAppName -SearchApplication $ssa -Owner $searchOwner -Level $params.Level
> ```

Can we wrap this line so we don't go over the 100 character length recommendation in the style guidelines

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPSearchAuthoritativePage/MSFT_SPSearchAuthoritativePage.schema.mof, line 5 at r4](https://reviewable.io:443/reviews/powershell/sharepointdsc/530#-KfcvY-JlOMsIt8WiHgR:-KfcvY-JlOMsIt8WiHgS:b-vw3k3h) ([raw file](https://github.com/powershell/sharepointdsc/blob/da723187d91b12feecca0f4fab4f65d21eb69769/Modules/SharePointDsc/DSCResources/MSFT_SPSearchAuthoritativePage/MSFT_SPSearchAuthoritativePage.schema.mof#L5)):*
> ```
> {
>     [Key, Description("Search Service Application Name")] String ServiceAppName;
>     [Key, Description("Source URI for the crawl mapping")] String Path;
> ```

Still says crawl mapping here, shouldn't this be something else?

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPSearchAuthoritativePage/MSFT_SPSearchAuthoritativePage.schema.mof, line 6 at r4](https://reviewable.io:443/reviews/powershell/sharepointdsc/530#-KfcvpHX0vMbFP_PCcju:-KfcvpHX0vMbFP_PCcjv:b50rhni) ([raw file](https://github.com/powershell/sharepointdsc/blob/da723187d91b12feecca0f4fab4f65d21eb69769/Modules/SharePointDsc/DSCResources/MSFT_SPSearchAuthoritativePage/MSFT_SPSearchAuthoritativePage.schema.mof#L6)):*
> Real32

Shouldn't this be "UInt32"

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPSearchAuthoritativePage/MSFT_SPSearchAuthoritativePage.schema.mof, line 7 at r4](https://reviewable.io:443/reviews/powershell/sharepointdsc/530#-Kfcw3QqRyo8Z9T4w2F0:-Kfcw3QqRyo8Z9T4w2F1:b-z4melh) ([raw file](https://github.com/powershell/sharepointdsc/blob/da723187d91b12feecca0f4fab4f65d21eb69769/Modules/SharePointDsc/DSCResources/MSFT_SPSearchAuthoritativePage/MSFT_SPSearchAuthoritativePage.schema.mof#L7)):*
> resourec

Typo here

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPSearchAuthoritativePage/MSFT_SPSearchAuthoritativePage.schema.mof, line 8 at r4](https://reviewable.io:443/reviews/powershell/sharepointdsc/530#-Kfcw6zMuQJu0wLruM3d:-Kfcw6zN_8mz7VtnY476:b6yjwpi) ([raw file](https://github.com/powershell/sharepointdsc/blob/da723187d91b12feecca0f4fab4f65d21eb69769/Modules/SharePointDsc/DSCResources/MSFT_SPSearchAuthoritativePage/MSFT_SPSearchAuthoritativePage.schema.mof#L8)):*
> ```
>     [Write, Description("Level of Authoratative Page, values between 0.0 and 2.0")] Real32 Level;
>     [Write, Description("The resourec will either make the page authoratative or demoted based on this value"), ValueMap{"Authoratative","Demoted"}, Values{"Authoratative","Demoted"}] String Action;
>     [Write, Description("Ensure the crawl rule is Present or Absent"), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
> ```

Crawl rule again here

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPSearchAuthoritativePage/MSFT_SPSearchAuthoritativePage.schema.mof, line 9 at r4](https://reviewable.io:443/reviews/powershell/sharepointdsc/530#-KfcwDu8CSljevgkQqdP:-KfcwDu8CSljevgkQqdQ:b-9f4964) ([raw file](https://github.com/powershell/sharepointdsc/blob/da723187d91b12feecca0f4fab4f65d21eb69769/Modules/SharePointDsc/DSCResources/MSFT_SPSearchAuthoritativePage/MSFT_SPSearchAuthoritativePage.schema.mof#L9)):*
> thsi

Typo - @ykuijs can you look at the Access Services 2010 resource I just let through, it has this same typo. If you could pick it up in your bug fix PR that would be awesome :) 

---

*[Modules/SharePointDsc/Examples/Resources/SPSearchAuthoritativePage/2 - DemotedPage.ps1, line 3 at r4](https://reviewable.io:443/reviews/powershell/sharepointdsc/530#-Kfcwjz2v20b0v0BGvbC:-Kfcwjz3d7B-6NvrrM9L:b-rplew6) ([raw file](https://github.com/powershell/sharepointdsc/blob/da723187d91b12feecca0f4fab4f65d21eb69769/Modules/SharePointDsc/Examples/Resources/SPSearchAuthoritativePage/2 - DemotedPage.ps1#L3)):*
> ```PowerShell
> <#
> .EXAMPLE
>     This example shows how to create a Search Authoritative Page
> ```

Should this say something about it being demoted instead of authoratative

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/530#-:-KfcyVpxZqtO4FwUa2Vp:b-29og5r)*

**Comment by BrianFarnhill** [comment]
OK so I can't see where that weird character is, but its preventing the tests from running which is breaking the code coverage result as well. Leave it with me, I'll try to do a pull from your branch and see if I can find it and let you know where it is.

---

Reviewed 4 of 13 files at r2, 5 of 5 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/530#-:-Kfs-VO3kh6knGjla03Y:b-lg2xwb)*

**Comment by BrianFarnhill** [comment]
ok, swap out the two "Add-Type" statements at the top for this, that seems to fix it - the tests are broken after that point, but they run:

    Add-Type -TypeDefinition @"
    namespace Microsoft.Office.Server.Search.Administration { 
        public class SearchObjectLevel { 
            public static string Ssa { get { return ""; } }
        }

        public class SearchObjectOwner {
            public SearchObjectOwner(Microsoft.Office.Server.Search.Administration.SearchObjectLevel level) { }
        }
    }
    "@

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/530#-:-Kfs4rnU8UDiiov-0EXv:b34yfeq)*

**Comment by mrpullen** [comment]
So I updated the code to
 ```
Add-Type -TypeDefinition @"
namespace Microsoft.Office.Server.Search.Administration { 
    public enum SearchObjectLevel
    {
        SPWeb,
        SPSite,
        SPSiteSubscription,
        Ssa
    }
    
   
    public class SearchObjectOwner {
        public SearchObjectOwner(Microsoft.Office.Server.Search.Administration.SearchObjectLevel level) { }
    }
}
"@
```

the code expects that SearchObjectLevel to come back as an enum.

**Comment by BrianFarnhill** [comment]
Reviewed 1 of 13 files at r2, 2 of 2 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/530)*

**Comment by BrianFarnhill** [comment]
:lgtm: just need a merge from dev to resolve the conflict on the change log and we are good to go.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/530#-:-Kft03MpaQCzJTpKhCy2:b3fcw86)*

**Comment by BrianFarnhill** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r8.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/530#-:-Kfx27i57CO4nEx0IzvL:bnfp4nl)*

**Pull request merged**
