### PR TITLE
Several bugfixes and styling improvements

### PR DESCRIPTION
**Pull request by ykuijs**
Fixes for issues #383, #380 and #403. Also made some styling improvements

- [X] Change details added to Unreleased section of changelog.md?
- [N/A] Added/updated documentation and descriptions in .schema.mof files where appropriate?
- [N/A] Examples updated for both the single server and small farm templates in the examples folder?
- [X] New/changed code adheres to [Style Guidelines]?(https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md)?
- [X] [Unit and Integration tests](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md) created/updated where possible?

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/sharepointdsc/415)

### CODE REVIEW

**Comment by ykuijs** [comment]
Checking the Appveyor errors.......Pester is annoying me once again ;-)

**Comment by BrianFarnhill** [comment]
Looks like you need to check the tests for that .net 4.6 thing sorted. There was a couple of things I picked up in the review that relate to that, but it needs to be looked at. 

---

Reviewed 83 of 83 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[CHANGELOG.md, line 6 at r1](https://reviewable.io:443/reviews/powershell/sharepointdsc/415#-KTLgHu5PEl6q98HvMQj:-KTLgHu6VwBIkPEBdJHP:bwy0yuj) ([raw file](https://github.com/powershell/sharepointdsc/blob/c026b9357a7fd5e290ef916b30047cea611b9c71/CHANGELOG.md#L6)):*
> ```Markdown
>  * Fixed issue with mounting SPContentDatabase
>  * Fixed issue with SPShellAdmin and Content Database method
>  * Added .Net 4.6 support check
> ```

Can we make these specifically list the resources they impact - like "added .net 4.6 support check to SPInstallPrereqs" so its clear where the bug fix impacts?

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPInstall/MSFT_SPInstall.psm1, line 108 at r1](https://reviewable.io:443/reviews/powershell/sharepointdsc/415#-KTLhnq4SLpfQw_ZZzDl:-KTLhnq4SLpfQw_ZZzDm:b-h2d0l8) ([raw file](https://github.com/powershell/sharepointdsc/blob/c026b9357a7fd5e290ef916b30047cea611b9c71/Modules/SharePointDsc/DSCResources/MSFT_SPInstall/MSFT_SPInstall.psm1#L108)):*
> ```PowerShell
>         $svrsetupDll = Join-Path -Path $BinaryDir -ChildPath "updates\svrsetup.dll"
>         $checkDotNet = $true
>         if (Test-Path -Path $svrsetupDll) {
> ```

Bracket needs to open on new line

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPInstall/MSFT_SPInstall.psm1, line 109 at r1](https://reviewable.io:443/reviews/powershell/sharepointdsc/415#-KTLhqBciBwTLSgHCzf_:-KTLhqBdYO82VInGT2iY:bw8yroi) ([raw file](https://github.com/powershell/sharepointdsc/blob/c026b9357a7fd5e290ef916b30047cea611b9c71/Modules/SharePointDsc/DSCResources/MSFT_SPInstall/MSFT_SPInstall.psm1#L109)):*
> ```PowerShell
>         $checkDotNet = $true
>         if (Test-Path -Path $svrsetupDll) {
>             $svrsetupDllFileInfo = Get-ItemProperty $svrsetupDll
> ```

Positional parameter on Get-ItemProperty

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPInstallPrereqs/MSFT_SPInstallPrereqs.psm1, line 433 at r1](https://reviewable.io:443/reviews/powershell/sharepointdsc/415#-KTLi5noldjrGmxHJzXm:-KTLi5noldjrGmxHJzXn:b-oshkqg) ([raw file](https://github.com/powershell/sharepointdsc/blob/c026b9357a7fd5e290ef916b30047cea611b9c71/Modules/SharePointDsc/DSCResources/MSFT_SPInstallPrereqs/MSFT_SPInstallPrereqs.psm1#L433)):*
> ```PowerShell
>         $svrsetupDll = Join-Path -Path $BinaryDir -ChildPath "updates\svrsetup.dll"
>         $checkDotNet = $true
>         if (Test-Path -Path $svrsetupDll) {
> ```

Bracket should be on new line

---

*[Tests/Unit/SharePointDsc/SharePointDsc.SPInstall.Tests.ps1, line 126 at r1](https://reviewable.io:443/reviews/powershell/sharepointdsc/415#-KTLjiuzBnlkNFoBX0-x:-KTLjiv-Mo2pJGXpauto:b4ksvde) ([raw file](https://github.com/powershell/sharepointdsc/blob/c026b9357a7fd5e290ef916b30047cea611b9c71/Tests/Unit/SharePointDsc/SharePointDsc.SPInstall.Tests.ps1#L126)):*
> ```PowerShell
> 
>         Context "SharePoint binaries are installed and should not be" {
>             Mock Get-ItemProperty { return @{} } -ParameterFilter { $Path }
> ```

The parameter filter stuff here needs be in the formatted like this: $Parameter -eq "Value". So if you are looking to only mock Get-ItemProperty when -Path is specified to be a certain value (or is specified at all) then it should be $null -ne $Path so it's clear what the intent is. Same for the one below.

---

*[Tests/Unit/SharePointDsc/SharePointDsc.SPInstallPrereqs.Tests.ps1, line 92 at r1](https://reviewable.io:443/reviews/powershell/sharepointdsc/415#-KTLk9HNIv69v4eNWJ7k:-KTLk9HNIv69v4eNWJ7l:b-1cc5z4) ([raw file](https://github.com/powershell/sharepointdsc/blob/c026b9357a7fd5e290ef916b30047cea611b9c71/Tests/Unit/SharePointDsc/SharePointDsc.SPInstallPrereqs.Tests.ps1#L92)):*
> ```PowerShell
>             Mock Get-ItemProperty -MockWith {
>                 return @()
>             } -ParameterFilter { $Path }
> ```

Same comment in this file about formatting parameterfilter

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/415#-:-KTLkZaUr-8vv4LspJmZ:b-gr9uv8)*

**Comment by ykuijs** [comment]
Review status: 77 of 83 files reviewed at latest revision, 6 unresolved discussions.

---

*[CHANGELOG.md, line 6 at r1](https://reviewable.io:443/reviews/powershell/sharepointdsc/415#-KTLgHu5PEl6q98HvMQj:-KTOAPIAqEd4W3yxUtaj:b-896fix) ([raw file](https://github.com/powershell/sharepointdsc/blob/c026b9357a7fd5e290ef916b30047cea611b9c71/CHANGELOG.md#L6)):*
<details><summary><i>Previously, BrianFarnhill (Brian Farnhill) wrote…</i></summary>
> Can we make these specifically list the resources they impact - like "added .net 4.6 support check to SPInstallPrereqs" so its clear where the bug fix impacts?
</details>
Done.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPInstall/MSFT_SPInstall.psm1, line 108 at r1](https://reviewable.io:443/reviews/powershell/sharepointdsc/415#-KTLhnq4SLpfQw_ZZzDl:-KTOAQip4zZteN1sZq6Q:b-896fix) ([raw file](https://github.com/powershell/sharepointdsc/blob/c026b9357a7fd5e290ef916b30047cea611b9c71/Modules/SharePointDsc/DSCResources/MSFT_SPInstall/MSFT_SPInstall.psm1#L108)):*
<details><summary><i>Previously, BrianFarnhill (Brian Farnhill) wrote…</i></summary>
> Bracket needs to open on new line
</details>
Done.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPInstall/MSFT_SPInstall.psm1, line 109 at r1](https://reviewable.io:443/reviews/powershell/sharepointdsc/415#-KTLhqBciBwTLSgHCzf_:-KTOAROoG16VvjFJRfLX:b-896fix) ([raw file](https://github.com/powershell/sharepointdsc/blob/c026b9357a7fd5e290ef916b30047cea611b9c71/Modules/SharePointDsc/DSCResources/MSFT_SPInstall/MSFT_SPInstall.psm1#L109)):*
<details><summary><i>Previously, BrianFarnhill (Brian Farnhill) wrote…</i></summary>
> Positional parameter on Get-ItemProperty
</details>
Done.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPInstallPrereqs/MSFT_SPInstallPrereqs.psm1, line 433 at r1](https://reviewable.io:443/reviews/powershell/sharepointdsc/415#-KTLi5noldjrGmxHJzXm:-KTOASO3gU_ECDhzead3:b-896fix) ([raw file](https://github.com/powershell/sharepointdsc/blob/c026b9357a7fd5e290ef916b30047cea611b9c71/Modules/SharePointDsc/DSCResources/MSFT_SPInstallPrereqs/MSFT_SPInstallPrereqs.psm1#L433)):*
<details><summary><i>Previously, BrianFarnhill (Brian Farnhill) wrote…</i></summary>
> Bracket should be on new line
</details>
Done.

---

*[Tests/Unit/SharePointDsc/SharePointDsc.SPInstall.Tests.ps1, line 126 at r1](https://reviewable.io:443/reviews/powershell/sharepointdsc/415#-KTLjiuzBnlkNFoBX0-x:-KTOATNunZjxIx8b_RCU:b-896fix) ([raw file](https://github.com/powershell/sharepointdsc/blob/c026b9357a7fd5e290ef916b30047cea611b9c71/Tests/Unit/SharePointDsc/SharePointDsc.SPInstall.Tests.ps1#L126)):*
<details><summary><i>Previously, BrianFarnhill (Brian Farnhill) wrote…</i></summary>
> The parameter filter stuff here needs be in the formatted like this: $Parameter -eq "Value". So if you are looking to only mock Get-ItemProperty when -Path is specified to be a certain value (or is specified at all) then it should be $null -ne $Path so it's clear what the intent is. Same for the one below.
</details>
Done.

---

*[Tests/Unit/SharePointDsc/SharePointDsc.SPInstallPrereqs.Tests.ps1, line 92 at r1](https://reviewable.io:443/reviews/powershell/sharepointdsc/415#-KTLk9HNIv69v4eNWJ7k:-KTOAULgzqNi7SXaGAma:b-896fix) ([raw file](https://github.com/powershell/sharepointdsc/blob/c026b9357a7fd5e290ef916b30047cea611b9c71/Tests/Unit/SharePointDsc/SharePointDsc.SPInstallPrereqs.Tests.ps1#L92)):*
<details><summary><i>Previously, BrianFarnhill (Brian Farnhill) wrote…</i></summary>
> Same comment in this file about formatting parameterfilter
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/415)*

**Comment by BrianFarnhill** [comment]
Reviewed 6 of 6 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPContentDatabase/MSFT_SPContentDatabase.psm1, line 330 at r2](https://reviewable.io:443/reviews/powershell/sharepointdsc/415#-KTQnaGxvAjmeT6jksL0:-KTQnaGxvAjmeT6jksL1:b-drnyjl) ([raw file](https://github.com/powershell/sharepointdsc/blob/7b0cc8f1b9b4180b633ade99167a7a65c1bf69b6/Modules/SharePointDsc/DSCResources/MSFT_SPContentDatabase/MSFT_SPContentDatabase.psm1#L330)):*
> ```PowerShell
>             else
>             {
>                 Write-Verbose -Message "Could not update Content Database because the reference is null"
> ```

Can you expand on this? Why would it be null? What scenario are you catering for with this? I think we could give a more meaningful message to the user when this happens

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/415)*

**Comment by ykuijs** [comment]
Review status: 82 of 84 files reviewed at latest revision, 1 unresolved discussion.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPContentDatabase/MSFT_SPContentDatabase.psm1, line 330 at r2](https://reviewable.io:443/reviews/powershell/sharepointdsc/415#-KTQnaGxvAjmeT6jksL0:-KTSrYku0N9z5mbH-uEP:b-896fix) ([raw file](https://github.com/powershell/sharepointdsc/blob/7b0cc8f1b9b4180b633ade99167a7a65c1bf69b6/Modules/SharePointDsc/DSCResources/MSFT_SPContentDatabase/MSFT_SPContentDatabase.psm1#L330)):*
<details><summary><i>Previously, BrianFarnhill (Brian Farnhill) wrote…</i></summary>
> Can you expand on this? Why would it be null? What scenario are you catering for with this? I think we could give a more meaningful message to the user when this happens
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/415)*

**Comment by ykuijs** [comment]
Review status: 82 of 84 files reviewed at latest revision, 1 unresolved discussion.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPContentDatabase/MSFT_SPContentDatabase.psm1, line 330 at r2](https://reviewable.io:443/reviews/powershell/sharepointdsc/415#-KTQnaGxvAjmeT6jksL0:-KTSrnzmLPGQovqP4C1t:b7d0lm) ([raw file](https://github.com/powershell/sharepointdsc/blob/7b0cc8f1b9b4180b633ade99167a7a65c1bf69b6/Modules/SharePointDsc/DSCResources/MSFT_SPContentDatabase/MSFT_SPContentDatabase.psm1#L330)):*
<details><summary><i>Previously, ykuijs (Yorick Kuijs) wrote…</i></summary>
> Done.
</details>
For example: if the database server does not exist, Mount-SPContentDatabase does not give an terminating error and the variable end up being NULL.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/415)*

**Comment by BrianFarnhill** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPContentDatabase/MSFT_SPContentDatabase.psm1, line 330 at r2](https://reviewable.io:443/reviews/powershell/sharepointdsc/415#-KTQnaGxvAjmeT6jksL0:-KTfVQqbBrb2hC9O9y0y:bsgjtto) ([raw file](https://github.com/powershell/sharepointdsc/blob/7b0cc8f1b9b4180b633ade99167a7a65c1bf69b6/Modules/SharePointDsc/DSCResources/MSFT_SPContentDatabase/MSFT_SPContentDatabase.psm1#L330)):*
<details><summary><i>Previously, ykuijs (Yorick Kuijs) wrote…</i></summary>
> For example: if the database server does not exist, Mount-SPContentDatabase does not give an terminating error and the variable end up being NULL.
</details>
Do you think we can list things here to check for the failure? So something like  "unable to update content database, please ensure that the database server exists and that the run as account has permissions to it" or something to that extent. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/415)*

**Comment by ykuijs** [comment]
Reviewable has an issue, so replying the old-fashioned way.

Resolved the issue by adding -ErrorAction to the Mount-SPContentDatabase cmdlet. As it turns out, having a non-existent database is a non-terminating error which is not picked up by try/catch. By adding ErrorAction Stop, it now is being picked up which removes the necessity for this check.

**Comment by BrianFarnhill** [comment]
@ykuijs Thanks - yea reviewable are having an issue right now it seems, but I'm happy with that last fix and happy with the PR. Merging in to dev now 👍

**Pull request merged**
