### PR TITLE
new resource SPWebApplicationExtension

### PR DESCRIPTION
**Pull request by MikeLacher448**
new resource SPWebApplicationExtension

- [x] Change details added to Unreleased section of changelog.md?
- [x] Added/updated documentation and descriptions in .schema.mof files where appropriate?
- [x] Examples updated for both the single server and small farm templates in the examples folder?
- [x] New/changed code adheres to [Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md)?
- [x] [Unit and Integration tests](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md) created/updated where possible? [unit tests only]

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/sharepointdsc/510)

### CODE REVIEW

**Comment by MikeLacher448** [comment]
working on the failing tests... they worked before, but now they are not :)

**Comment by BrianFarnhill** [comment]
@MikeLacher448 How you going with those tests dude? Had a chance to look at them yet? 

---

Review status: 0 of 7 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/510#-:-KdxwP9tlfSQDGBodeQ1:b2gqj1i)*

**Comment by mrpullen** [comment]
Can we include the AuthenticationProvider and Claims stuff in this resource as well to keep it consistent. See #513 for implementation details. SPWebApplication now has 100% unit test coverage, would guess you could shift almost all of them over.

**Comment by BrianFarnhill** [comment]
@MikeLacher448 What do you think about pulling the claims stuff in from @mrpullen 's branch there? Reckon you can slide this in as well?

**Comment by MikeLacher448** [comment]
I'll take a look at the claims code from spwebapplication and fit them into here as well.

**Comment by MikeLacher448** [comment]
ok, I think I got this one all set now

**Comment by BrianFarnhill** [comment]
Overall a pretty decent effort dude - got a few things that need cleaning up though. Details below.

---

Reviewed 6 of 6 files at r3.
Review status: all files reviewed at latest revision, 14 unresolved discussions.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPWebApplicationExtension/MSFT_SPWebApplicationExtension.psm1, line 75 at r3](https://reviewable.io:443/reviews/powershell/sharepointdsc/510#-KfF92RBee3eqojImb30:-KfF92RBee3eqojImb31:b-5p5ry8) ([raw file](https://github.com/powershell/sharepointdsc/blob/ff29d77708489984644f6523ab95fe5eeaf2f1df/Modules/SharePointDsc/DSCResources/MSFT_SPWebApplicationExtension/MSFT_SPWebApplicationExtension.psm1#L75)):*
> ```PowerShell
>         if ($null -eq $wa) 
>         { 
>             Write-Verbose "WebApplication $($params.WebAppUrl) does not exist"
> ```

Avoid positional parameters

Write-Verbose **-Message** "...

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPWebApplicationExtension/MSFT_SPWebApplicationExtension.psm1, line 99 at r3](https://reviewable.io:443/reviews/powershell/sharepointdsc/510#-KfF9Hi-WPL-U_NQyTef:-KfF9Hi-WPL-U_NQyTeg:b1zk5g6) ([raw file](https://github.com/powershell/sharepointdsc/blob/ff29d77708489984644f6523ab95fe5eeaf2f1df/Modules/SharePointDsc/DSCResources/MSFT_SPWebApplicationExtension/MSFT_SPWebApplicationExtension.psm1#L99)):*
> ```PowerShell
>         }
> 
>         $PublicUrl = (Get-SPAlternateURL -WebApplication $params.WebAppUrl -Zone $params.zone).PublicUrl
> ```

lower case on the first letter of variables that aren't parameters

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPWebApplicationExtension/MSFT_SPWebApplicationExtension.psm1, line 99 at r3](https://reviewable.io:443/reviews/powershell/sharepointdsc/510#-KfF9OF6g1r9Fd7kvrZG:-KfF9OF6g1r9Fd7kvrZH:bq6xwwr) ([raw file](https://github.com/powershell/sharepointdsc/blob/ff29d77708489984644f6523ab95fe5eeaf2f1df/Modules/SharePointDsc/DSCResources/MSFT_SPWebApplicationExtension/MSFT_SPWebApplicationExtension.psm1#L99)):*
> ```PowerShell
>         }
> 
>         $PublicUrl = (Get-SPAlternateURL -WebApplication $params.WebAppUrl -Zone $params.zone).PublicUrl
> ```

Is there are scenario here where someone has set alternate URLs without an extension that might screw with this? I'm not 100% so wanted to ask the question

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPWebApplicationExtension/MSFT_SPWebApplicationExtension.psm1, line 236 at r3](https://reviewable.io:443/reviews/powershell/sharepointdsc/510#-KfF9lplfXKMKtzjfiWZ:-KfF9lplfXKMKtzjfiW_:bot6p4p) ([raw file](https://github.com/powershell/sharepointdsc/blob/ff29d77708489984644f6523ab95fe5eeaf2f1df/Modules/SharePointDsc/DSCResources/MSFT_SPWebApplicationExtension/MSFT_SPWebApplicationExtension.psm1#L236)):*
> ```PowerShell
> 
> 
>         $zone = [Microsoft.SharePoint.Administration.SPUrlZone]::$($params.Zone)
> ```

This line and the next couple are out of line in terms of indentation

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPWebApplicationExtension/MSFT_SPWebApplicationExtension.psm1, line 252 at r3](https://reviewable.io:443/reviews/powershell/sharepointdsc/510#-KfF9r11wnCA5fHnw8DQ:-KfF9r12-auYkMKLTD5L:b-sarz8r) ([raw file](https://github.com/powershell/sharepointdsc/blob/ff29d77708489984644f6523ab95fe5eeaf2f1df/Modules/SharePointDsc/DSCResources/MSFT_SPWebApplicationExtension/MSFT_SPWebApplicationExtension.psm1#L252)):*
> ```PowerShell
>                     if($params.AuthenticationMethod -eq "Claims")
>                     {
>                        try {
> ```

need to drop the brace here to a new line

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPWebApplicationExtension/MSFT_SPWebApplicationExtension.psm1, line 254 at r3](https://reviewable.io:443/reviews/powershell/sharepointdsc/510#-KfF9tQ-EKK1ul4_5-qw:-KfF9tQ0RQ6_228Wn0j_:boqddl4) ([raw file](https://github.com/powershell/sharepointdsc/blob/ff29d77708489984644f6523ab95fe5eeaf2f1df/Modules/SharePointDsc/DSCResources/MSFT_SPWebApplicationExtension/MSFT_SPWebApplicationExtension.psm1#L254)):*
> ```PowerShell
>                        try {
>                             $ap = Get-SPTrustedIdentityTokenIssuer -Identity $params.AuthenticationProvider -ErrorAction Stop
>                         } catch {
> ```

need to drop the catch and then the brace here to new lines each

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPWebApplicationExtension/MSFT_SPWebApplicationExtension.psm1, line 292 at r3](https://reviewable.io:443/reviews/powershell/sharepointdsc/510#-KfF9yod3eZoHklnNWiz:-KfF9yod3eZoHklnNWj-:b-kyjdn8) ([raw file](https://github.com/powershell/sharepointdsc/blob/ff29d77708489984644f6523ab95fe5eeaf2f1df/Modules/SharePointDsc/DSCResources/MSFT_SPWebApplicationExtension/MSFT_SPWebApplicationExtension.psm1#L292)):*
> ```PowerShell
>             }
>         else {
>             write-verbose 'extension exists'
> ```

Need to use positional parameter for "Message" here, but can we also make the message a little more descriptive so it makes sense when seen in the logs

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPWebApplicationExtension/MSFT_SPWebApplicationExtension.psm1, line 303 at r3](https://reviewable.io:443/reviews/powershell/sharepointdsc/510#-KfFA47x6Svw8qfqz0tp:-KfFA47x6Svw8qfqz0tq:b-u72j9q) ([raw file](https://github.com/powershell/sharepointdsc/blob/ff29d77708489984644f6523ab95fe5eeaf2f1df/Modules/SharePointDsc/DSCResources/MSFT_SPWebApplicationExtension/MSFT_SPWebApplicationExtension.psm1#L303)):*
> ```PowerShell
>                 if($params.AuthenticationMethod -eq "Claims")
>                 {
>                     try {
> ```

Same note here about moving braces to new lines

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPWebApplicationExtension/MSFT_SPWebApplicationExtension.psm1, line 413 at r3](https://reviewable.io:443/reviews/powershell/sharepointdsc/510#-KfFAFRqB1-gZnQ3sOA3:-KfFAFRqB1-gZnQ3sOA4:bwm1eeo) ([raw file](https://github.com/powershell/sharepointdsc/blob/ff29d77708489984644f6523ab95fe5eeaf2f1df/Modules/SharePointDsc/DSCResources/MSFT_SPWebApplicationExtension/MSFT_SPWebApplicationExtension.psm1#L413)):*
> ```PowerShell
>     $CurrentValues = Get-TargetResource @PSBoundParameters
> 
>     Write-Verbose "Got the current Values"
> ```

We don't need this here I don't think

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPWebApplicationExtension/MSFT_SPWebApplicationExtension.psm1, line 418 at r3](https://reviewable.io:443/reviews/powershell/sharepointdsc/510#-KfFAIAW00-fSZvEABqF:-KfFAIAW00-fSZvEABqG:b4r2y6o) ([raw file](https://github.com/powershell/sharepointdsc/blob/ff29d77708489984644f6523ab95fe5eeaf2f1df/Modules/SharePointDsc/DSCResources/MSFT_SPWebApplicationExtension/MSFT_SPWebApplicationExtension.psm1#L418)):*
> ```PowerShell
>                                                      -DesiredValues $PSBoundParameters `
>                                                      -ValuesToCheck @("Ensure","AuthenticationMethod","AllowAnonymous")
>     Write-Verbose "Tested the current Values"
> ```

Definitely don't need this one here

---

*[Tests/Unit/SharePointDsc/SharePointDsc.SPWebApplicationExtension.Tests.ps1, line 45 at r3](https://reviewable.io:443/reviews/powershell/sharepointdsc/510#-KfFBusyHiVv5WoQAmMc:-KfFBusyHiVv5WoQAmMd:b7ayed2) ([raw file](https://github.com/powershell/sharepointdsc/blob/ff29d77708489984644f6523ab95fe5eeaf2f1df/Tests/Unit/SharePointDsc/SharePointDsc.SPWebApplicationExtension.Tests.ps1#L45)):*
> ```PowerShell
>         
>         
>         # Test contexts
> ```

Can we add a context that tests the set method were the authentication method is "claims" but there is no provider listed? Just to check that it throws the exceptions. Also we need one that will see Get-SPTrustedIdentityTokenIssuer throw an error so we can test that logic too. 

---

*[Tests/Unit/SharePointDsc/SharePointDsc.SPWebApplicationExtension.Tests.ps1, line 46 at r3](https://reviewable.io:443/reviews/powershell/sharepointdsc/510#-KfFB9hQYEoY-KoirUpb:-KfFB9hQYEoY-KoirUpc:b-z6bz15) ([raw file](https://github.com/powershell/sharepointdsc/blob/ff29d77708489984644f6523ab95fe5eeaf2f1df/Tests/Unit/SharePointDsc/SharePointDsc.SPWebApplicationExtension.Tests.ps1#L46)):*
> ```PowerShell
>         
>         # Test contexts
>         Context -Name "The parent web application does not exist" -Fixture {
> ```

Can we add tests to this context for the get and test methods as well (get returning "absent" on the ensure property, and test returning false)

---

*[Tests/Unit/SharePointDsc/SharePointDsc.SPWebApplicationExtension.Tests.ps1, line 59 at r3](https://reviewable.io:443/reviews/powershell/sharepointdsc/510#-KfFAgP2PbdEoAuyLlEs:-KfFAgP2PbdEoAuyLlEt:b-qyw2o7) ([raw file](https://github.com/powershell/sharepointdsc/blob/ff29d77708489984644f6523ab95fe5eeaf2f1df/Tests/Unit/SharePointDsc/SharePointDsc.SPWebApplicationExtension.Tests.ps1#L59)):*
> ```PowerShell
>             
>             It "retrieving non-existent web application fails in the set method" {
>                 { Set-TargetResource @testParams } | Should Throw "Web Application with URL http://nosuchwebapplication.sharepoint.com does not exist"
> ```

Can we substitute the URL here with $($testParams.WebAppUrl) so if we ever change it then it doesn't need to be changed here as well?

---

*[Tests/Unit/SharePointDsc/SharePointDsc.SPWebApplicationExtension.Tests.ps1, line 176 at r3](https://reviewable.io:443/reviews/powershell/sharepointdsc/510#-KfFBmcu2ofLyxgcMZpl:-KfFBmcu2ofLyxgcMZpm:b-5ieouk) ([raw file](https://github.com/powershell/sharepointdsc/blob/ff29d77708489984644f6523ab95fe5eeaf2f1df/Tests/Unit/SharePointDsc/SharePointDsc.SPWebApplicationExtension.Tests.ps1#L176)):*
> ```PowerShell
> 
> 
>         Context -Name "The web appliation extension does exist and should that uses NTLM without AllowAnonymous" -Fixture {
> ```

Can you repeat this context with the HTTPS and SecureBindings properties?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/510#-:-KfFCIyaO4V4TAnBiiJT:bf10gli)*

**Comment by MikeLacher448** [comment]
will clean up the code today and re-commit... some of my extra write-verbose statements were just for troubleshooting and I forgot to remove them.

**Comment by MikeLacher448** [comment]
give me another day or two to work on the extra test cases, will re-commit by Monday.

**Comment by MikeLacher448** [comment]
Review status: all files reviewed at latest revision, 14 unresolved discussions, some commit checks failed.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPWebApplicationExtension/MSFT_SPWebApplicationExtension.psm1, line 75 at r3](https://reviewable.io:443/reviews/powershell/sharepointdsc/510#-KfF92RBee3eqojImb30:-KfgpvMAmEU9mJkZVQ-S:b-896fix) ([raw file](https://github.com/powershell/sharepointdsc/blob/ff29d77708489984644f6523ab95fe5eeaf2f1df/Modules/SharePointDsc/DSCResources/MSFT_SPWebApplicationExtension/MSFT_SPWebApplicationExtension.psm1#L75)):*
<details><summary><i>Previously, BrianFarnhill (Brian Farnhill) wrote…</i></summary><blockquote>

Avoid positional parameters

Write-Verbose **-Message** "...
</blockquote></details>

Done.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPWebApplicationExtension/MSFT_SPWebApplicationExtension.psm1, line 99 at r3](https://reviewable.io:443/reviews/powershell/sharepointdsc/510#-KfF9OF6g1r9Fd7kvrZG:-KfIP62lQKPvieiRmfb-:bz91tnl) ([raw file](https://github.com/powershell/sharepointdsc/blob/ff29d77708489984644f6523ab95fe5eeaf2f1df/Modules/SharePointDsc/DSCResources/MSFT_SPWebApplicationExtension/MSFT_SPWebApplicationExtension.psm1#L99)):*
<details><summary><i>Previously, BrianFarnhill (Brian Farnhill) wrote…</i></summary><blockquote>

Is there are scenario here where someone has set alternate URLs without an extension that might screw with this? I'm not 100% so wanted to ask the question
</blockquote></details>

Hadn't really considered that, since product guidance is to not assign URLs to zones without a web app extension to back them up. I will try to create that situation in my lab and test to see what happens.

UPDATE: if an alternate URL is set without an extension,  than the IIS settings properties for the zone will be null, so the resource will treat it as absent, and create the extension if it should be present.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPWebApplicationExtension/MSFT_SPWebApplicationExtension.psm1, line 99 at r3](https://reviewable.io:443/reviews/powershell/sharepointdsc/510#-KfF9Hi-WPL-U_NQyTef:-KfgprcN1rbGDDod4hOT:b-896fix) ([raw file](https://github.com/powershell/sharepointdsc/blob/ff29d77708489984644f6523ab95fe5eeaf2f1df/Modules/SharePointDsc/DSCResources/MSFT_SPWebApplicationExtension/MSFT_SPWebApplicationExtension.psm1#L99)):*
<details><summary><i>Previously, BrianFarnhill (Brian Farnhill) wrote…</i></summary><blockquote>

lower case on the first letter of variables that aren't parameters
</blockquote></details>

Done.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPWebApplicationExtension/MSFT_SPWebApplicationExtension.psm1, line 236 at r3](https://reviewable.io:443/reviews/powershell/sharepointdsc/510#-KfF9lplfXKMKtzjfiWZ:-Kfgv_S13Pgccsih3TMu:b-896fix) ([raw file](https://github.com/powershell/sharepointdsc/blob/ff29d77708489984644f6523ab95fe5eeaf2f1df/Modules/SharePointDsc/DSCResources/MSFT_SPWebApplicationExtension/MSFT_SPWebApplicationExtension.psm1#L236)):*
<details><summary><i>Previously, BrianFarnhill (Brian Farnhill) wrote…</i></summary><blockquote>

This line and the next couple are out of line in terms of indentation
</blockquote></details>

Done.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPWebApplicationExtension/MSFT_SPWebApplicationExtension.psm1, line 252 at r3](https://reviewable.io:443/reviews/powershell/sharepointdsc/510#-KfF9r11wnCA5fHnw8DQ:-Kfgva9DNq56jkFI57M9:b-896fix) ([raw file](https://github.com/powershell/sharepointdsc/blob/ff29d77708489984644f6523ab95fe5eeaf2f1df/Modules/SharePointDsc/DSCResources/MSFT_SPWebApplicationExtension/MSFT_SPWebApplicationExtension.psm1#L252)):*
<details><summary><i>Previously, BrianFarnhill (Brian Farnhill) wrote…</i></summary><blockquote>

need to drop the brace here to a new line
</blockquote></details>

Done.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPWebApplicationExtension/MSFT_SPWebApplicationExtension.psm1, line 254 at r3](https://reviewable.io:443/reviews/powershell/sharepointdsc/510#-KfF9tQ-EKK1ul4_5-qw:-KfgvawsDL_pAAyfTUfV:b-896fix) ([raw file](https://github.com/powershell/sharepointdsc/blob/ff29d77708489984644f6523ab95fe5eeaf2f1df/Modules/SharePointDsc/DSCResources/MSFT_SPWebApplicationExtension/MSFT_SPWebApplicationExtension.psm1#L254)):*
<details><summary><i>Previously, BrianFarnhill (Brian Farnhill) wrote…</i></summary><blockquote>

need to drop the catch and then the brace here to new lines each
</blockquote></details>

Done.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPWebApplicationExtension/MSFT_SPWebApplicationExtension.psm1, line 292 at r3](https://reviewable.io:443/reviews/powershell/sharepointdsc/510#-KfF9yod3eZoHklnNWiz:-KfISZ44VprhIWUZInzj:b-34hawv) ([raw file](https://github.com/powershell/sharepointdsc/blob/ff29d77708489984644f6523ab95fe5eeaf2f1df/Modules/SharePointDsc/DSCResources/MSFT_SPWebApplicationExtension/MSFT_SPWebApplicationExtension.psm1#L292)):*
<details><summary><i>Previously, BrianFarnhill (Brian Farnhill) wrote…</i></summary><blockquote>

Need to use positional parameter for "Message" here, but can we also make the message a little more descriptive so it makes sense when seen in the logs
</blockquote></details>

pulled this one out, was left over from testing

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPWebApplicationExtension/MSFT_SPWebApplicationExtension.psm1, line 303 at r3](https://reviewable.io:443/reviews/powershell/sharepointdsc/510#-KfFA47x6Svw8qfqz0tp:-Kfgw8DrFVsyJ23gr-ob:b-896fix) ([raw file](https://github.com/powershell/sharepointdsc/blob/ff29d77708489984644f6523ab95fe5eeaf2f1df/Modules/SharePointDsc/DSCResources/MSFT_SPWebApplicationExtension/MSFT_SPWebApplicationExtension.psm1#L303)):*
<details><summary><i>Previously, BrianFarnhill (Brian Farnhill) wrote…</i></summary><blockquote>

Same note here about moving braces to new lines
</blockquote></details>

Done.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPWebApplicationExtension/MSFT_SPWebApplicationExtension.psm1, line 413 at r3](https://reviewable.io:443/reviews/powershell/sharepointdsc/510#-KfFAFRqB1-gZnQ3sOA3:-KfISk8uAdhuzNRjcr2Z:b4aipv9) ([raw file](https://github.com/powershell/sharepointdsc/blob/ff29d77708489984644f6523ab95fe5eeaf2f1df/Modules/SharePointDsc/DSCResources/MSFT_SPWebApplicationExtension/MSFT_SPWebApplicationExtension.psm1#L413)):*
<details><summary><i>Previously, BrianFarnhill (Brian Farnhill) wrote…</i></summary><blockquote>

We don't need this here I don't think
</blockquote></details>

deleted, left over from testing

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPWebApplicationExtension/MSFT_SPWebApplicationExtension.psm1, line 418 at r3](https://reviewable.io:443/reviews/powershell/sharepointdsc/510#-KfFAIAW00-fSZvEABqF:-KfISmHv2Hu1KsfFZYjR:b4aipv9) ([raw file](https://github.com/powershell/sharepointdsc/blob/ff29d77708489984644f6523ab95fe5eeaf2f1df/Modules/SharePointDsc/DSCResources/MSFT_SPWebApplicationExtension/MSFT_SPWebApplicationExtension.psm1#L418)):*
<details><summary><i>Previously, BrianFarnhill (Brian Farnhill) wrote…</i></summary><blockquote>

Definitely don't need this one here
</blockquote></details>

deleted, left over from testing

---

*[Tests/Unit/SharePointDsc/SharePointDsc.SPWebApplicationExtension.Tests.ps1, line 45 at r3](https://reviewable.io:443/reviews/powershell/sharepointdsc/510#-KfFBusyHiVv5WoQAmMc:-Kfh9RDNoDZblNRwFUrF:b-896fix) ([raw file](https://github.com/powershell/sharepointdsc/blob/ff29d77708489984644f6523ab95fe5eeaf2f1df/Tests/Unit/SharePointDsc/SharePointDsc.SPWebApplicationExtension.Tests.ps1#L45)):*
<details><summary><i>Previously, BrianFarnhill (Brian Farnhill) wrote…</i></summary><blockquote>

Can we add a context that tests the set method were the authentication method is "claims" but there is no provider listed? Just to check that it throws the exceptions. Also we need one that will see Get-SPTrustedIdentityTokenIssuer throw an error so we can test that logic too. 
</blockquote></details>

Done.

---

*[Tests/Unit/SharePointDsc/SharePointDsc.SPWebApplicationExtension.Tests.ps1, line 46 at r3](https://reviewable.io:443/reviews/powershell/sharepointdsc/510#-KfFB9hQYEoY-KoirUpb:-Kfh9gcMsmplZcxC_0tL:b-896fix) ([raw file](https://github.com/powershell/sharepointdsc/blob/ff29d77708489984644f6523ab95fe5eeaf2f1df/Tests/Unit/SharePointDsc/SharePointDsc.SPWebApplicationExtension.Tests.ps1#L46)):*
<details><summary><i>Previously, BrianFarnhill (Brian Farnhill) wrote…</i></summary><blockquote>

Can we add tests to this context for the get and test methods as well (get returning "absent" on the ensure property, and test returning false)
</blockquote></details>

Done.

---

*[Tests/Unit/SharePointDsc/SharePointDsc.SPWebApplicationExtension.Tests.ps1, line 59 at r3](https://reviewable.io:443/reviews/powershell/sharepointdsc/510#-KfFAgP2PbdEoAuyLlEs:-Kfh9qT0g8EiHZ04GzIW:b-896fix) ([raw file](https://github.com/powershell/sharepointdsc/blob/ff29d77708489984644f6523ab95fe5eeaf2f1df/Tests/Unit/SharePointDsc/SharePointDsc.SPWebApplicationExtension.Tests.ps1#L59)):*
<details><summary><i>Previously, BrianFarnhill (Brian Farnhill) wrote…</i></summary><blockquote>

Can we substitute the URL here with $($testParams.WebAppUrl) so if we ever change it then it doesn't need to be changed here as well?
</blockquote></details>

Done.

---

*[Tests/Unit/SharePointDsc/SharePointDsc.SPWebApplicationExtension.Tests.ps1, line 176 at r3](https://reviewable.io:443/reviews/powershell/sharepointdsc/510#-KfFBmcu2ofLyxgcMZpl:-KfhDAn0XKhJVc5Sx6Cj:b-896fix) ([raw file](https://github.com/powershell/sharepointdsc/blob/ff29d77708489984644f6523ab95fe5eeaf2f1df/Tests/Unit/SharePointDsc/SharePointDsc.SPWebApplicationExtension.Tests.ps1#L176)):*
<details><summary><i>Previously, BrianFarnhill (Brian Farnhill) wrote…</i></summary><blockquote>

Can you repeat this context with the HTTPS and SecureBindings properties?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/510)*

**Comment by BrianFarnhill** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/510#-:-Kfitha9ZpOwAOdSx9YP:bnfp4nl)*

**Pull request merged**
