### PR TITLE
Added a loopcount increments every 5s to 600 before breaking the loop.

### PR DESCRIPTION
**Pull request by mrpullen**
#544 
I added a loopCount which increments every 5 seconds, and counts up to 600 == 30m (20/m)
This will timeout the SPFarmSolution after 30 minutes.

- [x] Change details added to Unreleased section of changelog.md?
- [ ] Added/updated documentation and descriptions in .schema.mof files where appropriate?
- [ ] Examples updated for both the single server and small farm templates in the examples folder?
- [x] New/changed code adheres to [Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md)?
- [ ] [Unit and Integration tests](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md) created/updated where possible?

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/sharepointdsc/552)

### CODE REVIEW

**Comment by mrpullen** [comment]
??

**Comment by BrianFarnhill** [comment]
So I'm gonna need an updated test for this one, and it's gonna be a little tricky because the JobExists property doesn't get returned again at any point from a cmdlet. What I would suggest is that we test this with:

    $solution = Get-SPSolution -Identity $params.Name -Verbose:$false -AssignmentCollection $gc

baked in to that loop, so it refreshes the solution object at each iteration. It's technically not required from what I know, but I don't think it'll do too much harm either. From here then we can update the mock for Get-SPSolution to return a different value for the first time it gets called. I know we do this in a few other resoruces (I think Search Topology does this, or distributed cache so check those) where we use a global variable to know if the function has been previously called or not. So take that approach and see how you go.

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/552#-:-KgMpoP_vGAqMtQx3Dag:bwlmtpc)*

**Comment by mrpullen** [comment]
Made a stab at it. Code Coverage came up from 73 to 92% so I think I am on the right track, per your suggested fix :)

**Comment by BrianFarnhill** [comment]
Looks fine now - just need an updated pull from dev for the changelog file and some comments to be removed and we're good to go. 

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[Tests/Unit/SharePointDsc/SharePointDsc.SPFarmSolution.Tests.ps1, line 25 at r2](https://reviewable.io:443/reviews/powershell/sharepointdsc/552#-KgQy4E_4aZDbZLyCGd2:-KgQy4E_4aZDbZLyCGd3:b72o2ya) ([raw file](https://github.com/powershell/sharepointdsc/blob/6f79c3ad8f509ea57f5ee2f911b0413a57b92d04/Tests/Unit/SharePointDsc/SharePointDsc.SPFarmSolution.Tests.ps1#L25)):*
> ```PowerShell
>         # Mocks for all contexts   
>         Mock -CommandName Update-SPSolution -MockWith { }
>         ##Mock -CommandName Wait-SPDSCSolutionJob -MockWith { }
> ```

Why is this commented out, we should remove it if its not needed

---

*[Tests/Unit/SharePointDsc/SharePointDsc.SPFarmSolution.Tests.ps1, line 79 at r2](https://reviewable.io:443/reviews/powershell/sharepointdsc/552#-KgQy7VhCmTZhtHXKyX6:-KgQy7VhCmTZhtHXKyX7:b72o2ya) ([raw file](https://github.com/powershell/sharepointdsc/blob/6f79c3ad8f509ea57f5ee2f911b0413a57b92d04/Tests/Unit/SharePointDsc/SharePointDsc.SPFarmSolution.Tests.ps1#L79)):*
> ```PowerShell
>                 Assert-MockCalled Add-SPSolution 
>                 Assert-MockCalled Install-SPSolution
>                 ##Assert-MockCalled Wait-SPDSCSolutionJob 
> ```

Why is this commented out, we should remove it if its not needed

---

*[Tests/Unit/SharePointDsc/SharePointDsc.SPFarmSolution.Tests.ps1, line 144 at r2](https://reviewable.io:443/reviews/powershell/sharepointdsc/552#-KgQyA4M8aGhcKDSDm9V:-KgQyA4M8aGhcKDSDm9W:b72o2ya) ([raw file](https://github.com/powershell/sharepointdsc/blob/6f79c3ad8f509ea57f5ee2f911b0413a57b92d04/Tests/Unit/SharePointDsc/SharePointDsc.SPFarmSolution.Tests.ps1#L144)):*
> ```PowerShell
>                 Assert-MockCalled Add-SPSolution 
>                 Assert-MockCalled Install-SPSolution
>                 ##Assert-MockCalled Wait-SPDSCSolutionJob 
> ```

Why is this commented out, we should remove it if its not needed

---

*[Tests/Unit/SharePointDsc/SharePointDsc.SPFarmSolution.Tests.ps1, line 183 at r2](https://reviewable.io:443/reviews/powershell/sharepointdsc/552#-KgQyAtsWBvy5WFrRreK:-KgQyAtsWBvy5WFrRreL:b72o2ya) ([raw file](https://github.com/powershell/sharepointdsc/blob/6f79c3ad8f509ea57f5ee2f911b0413a57b92d04/Tests/Unit/SharePointDsc/SharePointDsc.SPFarmSolution.Tests.ps1#L183)):*
> ```PowerShell
> 
>                 Assert-MockCalled Uninstall-SPSolution
>                 ##Assert-MockCalled Wait-SPDSCSolutionJob 
> ```

Why is this commented out, we should remove it if its not needed

---

*[Tests/Unit/SharePointDsc/SharePointDsc.SPFarmSolution.Tests.ps1, line 251 at r2](https://reviewable.io:443/reviews/powershell/sharepointdsc/552#-KgQyBPEzLo_ILgK985r:-KgQyBPEzLo_ILgK985s:b72o2ya) ([raw file](https://github.com/powershell/sharepointdsc/blob/6f79c3ad8f509ea57f5ee2f911b0413a57b92d04/Tests/Unit/SharePointDsc/SharePointDsc.SPFarmSolution.Tests.ps1#L251)):*
> ```PowerShell
>                 Assert-MockCalled Update-SPSolution
>                 Assert-MockCalled Install-SPFeature
>                 ##Assert-MockCalled Wait-SPDSCSolutionJob 
> ```

Why is this commented out, we should remove it if its not needed

---

*[Tests/Unit/SharePointDsc/SharePointDsc.SPFarmSolution.Tests.ps1, line 326 at r2](https://reviewable.io:443/reviews/powershell/sharepointdsc/552#-KgQyC0HnJ7CO2Z_dmu7:-KgQyC0HnJ7CO2Z_dmu8:b72o2ya) ([raw file](https://github.com/powershell/sharepointdsc/blob/6f79c3ad8f509ea57f5ee2f911b0413a57b92d04/Tests/Unit/SharePointDsc/SharePointDsc.SPFarmSolution.Tests.ps1#L326)):*
> ```PowerShell
>                 Assert-MockCalled Add-SPSolution
>                 Assert-MockCalled Install-SPSolution
>                 ##Assert-MockCalled Wait-SPDSCSolutionJob 
> ```

Why is this commented out, we should remove it if its not needed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/552#-:-KgQyLv85eDMyY5BKTeN:b-m0dl9m)*

**Comment by BrianFarnhill** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/552#-:-KgS-6pR2j_CCvcjpwSu:bnfp4nl)*

**Pull request merged**
