### PR TITLE
Extend SPDatabaseAAG to map databases to AG's via name pattern

### PR DESCRIPTION
**Pull request by ykuijs**
Extend SPDatabaseAAG to map databases to AG's via name pattern according to issue #407 

- [X] Change details added to Unreleased section of changelog.md?
- [X] Added/updated documentation and descriptions in .schema.mof files where appropriate?
- [X] Examples updated for both the single server and small farm templates in the examples folder?
- [X] New/changed code adheres to [Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md)?
- [X] [Unit and Integration tests](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md) created/updated where possible?

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/sharepointdsc/458)

### CODE REVIEW

**Comment by BrianFarnhill** [comment]
Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 12 unresolved discussions.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPDatabaseAAG/MSFT_SPDatabaseAAG.psm1, line 74 at r1](https://reviewable.io:443/reviews/powershell/sharepointdsc/458#-KWj1byc8Awy56IK1-V6:-KWj1byc8Awy56IK1-V7:bgeis81) ([raw file](https://github.com/powershell/sharepointdsc/blob/c187ee9f556cb959bfb6084fb8f9073ba30e326b/Modules/SharePointDsc/DSCResources/MSFT_SPDatabaseAAG/MSFT_SPDatabaseAAG.psm1#L74)):*
> ```PowerShell
>             {
>                 Write-Verbose -Message "Specified database(s) not found."
>                 $Ensure = "Not found"
> ```

Ensure should be set to "Absent" if they aren't in the correct group. Think of it more as a Boolean of "they are in the right group" or they are not. The specific error of database not being found should then be handled in the set method. 

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPDatabaseAAG/MSFT_SPDatabaseAAG.psm1, line 113 at r1](https://reviewable.io:443/reviews/powershell/sharepointdsc/458#-KWj21z-GyF8AIvxFKjE:-KWj21z05EsS6tNAbxIA:b-nyyk2y) ([raw file](https://github.com/powershell/sharepointdsc/blob/c187ee9f556cb959bfb6084fb8f9073ba30e326b/Modules/SharePointDsc/DSCResources/MSFT_SPDatabaseAAG/MSFT_SPDatabaseAAG.psm1#L113)):*
> ```PowerShell
>             {
>                 Write-Verbose -Message "Specified database(s) not found."
>                 $Ensure = "Not found"
> ```

Ensure should be set to "Absent" if they aren't in the correct group. 

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPDatabaseAAG/MSFT_SPDatabaseAAG.psm1, line 175 at r1](https://reviewable.io:443/reviews/powershell/sharepointdsc/458#-KWj4sGX8Vl2M_FeKyQC:-KWj4sGX8Vl2M_FeKyQD:bvh4sy3) ([raw file](https://github.com/powershell/sharepointdsc/blob/c187ee9f556cb959bfb6084fb8f9073ba30e326b/Modules/SharePointDsc/DSCResources/MSFT_SPDatabaseAAG/MSFT_SPDatabaseAAG.psm1#L175)):*
> ```PowerShell
> 
>             $databases = Get-SPDatabase | Where-Object -FilterScript { 
>                 $_.Name -like "*$($params.DatabaseName)*" 
> ```

Rather than top and tailing this with a wildcard, how do you feel about just passing the value through so then we let config authors do things like "SP_*" or "SP_*_Content" or other more complex patterns like that? Specificing a fixed name will still work, but I think this gives a little more flexibility wile making it obvious to someone who reads a config that you are not just talking about a database called "SP_" to get everything that starts with that - does that make sense?

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPDatabaseAAG/MSFT_SPDatabaseAAG.psm1, line 206 at r1](https://reviewable.io:443/reviews/powershell/sharepointdsc/458#-KWj2pytYam-vdudvtTw:-KWj2pytYam-vdudvtTx:b-tgvd43) ([raw file](https://github.com/powershell/sharepointdsc/blob/c187ee9f556cb959bfb6084fb8f9073ba30e326b/Modules/SharePointDsc/DSCResources/MSFT_SPDatabaseAAG/MSFT_SPDatabaseAAG.psm1#L206)):*
> ```PowerShell
>                     else
>                     {
>                         # Add to AAG
> ```

Probably don't need this comment here when the verbose output below tells us the same thing

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPDatabaseAAG/MSFT_SPDatabaseAAG.psm1, line 228 at r1](https://reviewable.io:443/reviews/powershell/sharepointdsc/458#-KWj4U9wn5qUuzMG49Zu:-KWj4U9wn5qUuzMG49Zv:b-e2sfy4) ([raw file](https://github.com/powershell/sharepointdsc/blob/c187ee9f556cb959bfb6084fb8f9073ba30e326b/Modules/SharePointDsc/DSCResources/MSFT_SPDatabaseAAG/MSFT_SPDatabaseAAG.psm1#L228)):*
> ```PowerShell
>     else 
>     {
>         # Remove from the AAG
> ```

Same about redundant comment

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPDatabaseAAG/MSFT_SPDatabaseAAG.psm1, line 288 at r1](https://reviewable.io:443/reviews/powershell/sharepointdsc/458#-KWj4Y_rG8RVWajcjEyq:-KWj4Y_rG8RVWajcjEyr:b62yklv) ([raw file](https://github.com/powershell/sharepointdsc/blob/c187ee9f556cb959bfb6084fb8f9073ba30e326b/Modules/SharePointDsc/DSCResources/MSFT_SPDatabaseAAG/MSFT_SPDatabaseAAG.psm1#L288)):*
> ```PowerShell
>     $PSBoundParameters.Ensure = $Ensure
> 
>     # Check if the April 2014 CU has been installed. The cmdlets have been added in this CU
> ```

We can probably ditch the check here as the first thing we do in the test method, is call the get method - which will do the check, so this becomes a bit redundant here.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPDatabaseAAG/Readme.md, line 9 at r1](https://reviewable.io:443/reviews/powershell/sharepointdsc/458#-KWj5ILS4Su4fRPVimAD:-KWj5ILS4Su4fRPVimAE:b-jz33me) ([raw file](https://github.com/powershell/sharepointdsc/blob/c187ee9f556cb959bfb6084fb8f9073ba30e326b/Modules/SharePointDsc/DSCResources/MSFT_SPDatabaseAAG/Readme.md#L9)):*
> ```Markdown
> 
> You can add a single database name by specifying the database name, or
> multiple databases by specifying a common part of the database name.
> ```

We might need to tweak this based on the feedback about how we pattern match above. 

---

*[Modules/SharePointDsc/Examples/Resources/SPDatabaseAAG/2-AddMultipleDBstoAAG.ps1, line 19 at r1](https://reviewable.io:443/reviews/powershell/sharepointdsc/458#-KWj5OY_rMKE6hZzTVGp:-KWj5OYamGc6TfsU9skl:b-jz33me) ([raw file](https://github.com/powershell/sharepointdsc/blob/c187ee9f556cb959bfb6084fb8f9073ba30e326b/Modules/SharePointDsc/Examples/Resources/SPDatabaseAAG/2-AddMultipleDBstoAAG.ps1#L19)):*
> ```PowerShell
>             SPDatabaseAAG ConfigDBAAG
>             {
>                 DatabaseName         = "Content"
> ```

We might need to tweak this based on the feedback about how we pattern match above. 

---

*[Tests/Unit/SharePointDsc/SharePointDsc.SPDatabaseAAG.Tests.ps1, line 65 at r1](https://reviewable.io:443/reviews/powershell/sharepointdsc/458#-KWj5cF2UsLESe3LJQqr:-KWj5cF2UsLESe3LJQqs:b8qqb6g) ([raw file](https://github.com/powershell/sharepointdsc/blob/c187ee9f556cb959bfb6084fb8f9073ba30e326b/Tests/Unit/SharePointDsc/SharePointDsc.SPDatabaseAAG.Tests.ps1#L65)):*
> ```PowerShell
>         }
> 
>         Context -Name "The databases are not in an availability group, but should be" -Fixture {
> ```

Can we change the contexts for multiple database scenarios to clearly say "Multiple databases matching a name pattern" instead of "the databases"

---

*[Tests/Unit/SharePointDsc/SharePointDsc.SPDatabaseAAG.Tests.ps1, line 67 at r1](https://reviewable.io:443/reviews/powershell/sharepointdsc/458#-KWj5WLuJVxfHszBT3ai:-KWj5WLuJVxfHszBT3aj:b-jz33me) ([raw file](https://github.com/powershell/sharepointdsc/blob/c187ee9f556cb959bfb6084fb8f9073ba30e326b/Tests/Unit/SharePointDsc/SharePointDsc.SPDatabaseAAG.Tests.ps1#L67)):*
> ```PowerShell
>         Context -Name "The databases are not in an availability group, but should be" -Fixture {
>             $testParams = @{
>                 DatabaseName = "Sample"
> ```

We might need to tweak this based on the feedback about how we pattern match above. 

---

*[Tests/Unit/SharePointDsc/SharePointDsc.SPDatabaseAAG.Tests.ps1, line 162 at r1](https://reviewable.io:443/reviews/powershell/sharepointdsc/458#-KWj5Y7HyW4ZF9g-jzQM:-KWj5Y7HyW4ZF9g-jzQN:b-jz33me) ([raw file](https://github.com/powershell/sharepointdsc/blob/c187ee9f556cb959bfb6084fb8f9073ba30e326b/Tests/Unit/SharePointDsc/SharePointDsc.SPDatabaseAAG.Tests.ps1#L162)):*
> ```PowerShell
>         Context -Name "The databases are not in the availability group and should not be" -Fixture {
>             $testParams = @{
>                 DatabaseName = "SampleDatabase"
> ```

We might need to tweak this based on the feedback about how we pattern match above. 

---

*[Tests/Unit/SharePointDsc/SharePointDsc.SPDatabaseAAG.Tests.ps1, line 283 at r1](https://reviewable.io:443/reviews/powershell/sharepointdsc/458#-KWj5_Ud9YR3wakkvMn7:-KWj5_Ud9YR3wakkvMn8:b-jz33me) ([raw file](https://github.com/powershell/sharepointdsc/blob/c187ee9f556cb959bfb6084fb8f9073ba30e326b/Tests/Unit/SharePointDsc/SharePointDsc.SPDatabaseAAG.Tests.ps1#L283)):*
> ```PowerShell
>         Context -Name "The databases are in an availability group and should not be" -Fixture {
>             $testParams = @{
>                 DatabaseName = "SampleDatabase"
> ```

We might need to tweak this based on the feedback about how we pattern match above. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/458)*

**Comment by ykuijs** [comment]
Review status: all files reviewed at latest revision, 12 unresolved discussions.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPDatabaseAAG/MSFT_SPDatabaseAAG.psm1, line 74 at r1](https://reviewable.io:443/reviews/powershell/sharepointdsc/458#-KWj1byc8Awy56IK1-V6:-KWj7KNUup0MKI4b9-FW:b-qnbi9k) ([raw file](https://github.com/powershell/sharepointdsc/blob/c187ee9f556cb959bfb6084fb8f9073ba30e326b/Modules/SharePointDsc/DSCResources/MSFT_SPDatabaseAAG/MSFT_SPDatabaseAAG.psm1#L74)):*
<details><summary><i>Previously, BrianFarnhill (Brian Farnhill) wrote…</i></summary>
> Ensure should be set to "Absent" if they aren't in the correct group. Think of it more as a Boolean of "they are in the right group" or they are not. The specific error of database not being found should then be handled in the set method. 
</details>
I had an issue here:
When you specify Ensure=Absent and the database doesn't exist, the Get method returns Absent as well. This is causing the Test method to return true, which is not correct. So either I had to throw an exception (like I do in the Set method) or introduce a third value. I chose the latter one.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPDatabaseAAG/MSFT_SPDatabaseAAG.psm1, line 175 at r1](https://reviewable.io:443/reviews/powershell/sharepointdsc/458#-KWj4sGX8Vl2M_FeKyQC:-KWj8BDkXovmI1Cl4wyk:bz84okn) ([raw file](https://github.com/powershell/sharepointdsc/blob/c187ee9f556cb959bfb6084fb8f9073ba30e326b/Modules/SharePointDsc/DSCResources/MSFT_SPDatabaseAAG/MSFT_SPDatabaseAAG.psm1#L175)):*
<details><summary><i>Previously, BrianFarnhill (Brian Farnhill) wrote…</i></summary>
> Rather than top and tailing this with a wildcard, how do you feel about just passing the value through so then we let config authors do things like "SP_*" or "SP_*_Content" or other more complex patterns like that? Specificing a fixed name will still work, but I think this gives a little more flexibility wile making it obvious to someone who reads a config that you are not just talking about a database called "SP_" to get everything that starts with that - does that make sense?
</details>
Not sure what you mean here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/458)*

**Comment by BrianFarnhill** [comment]
Review status: all files reviewed at latest revision, 12 unresolved discussions.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPDatabaseAAG/MSFT_SPDatabaseAAG.psm1, line 74 at r1](https://reviewable.io:443/reviews/powershell/sharepointdsc/458#-KWj1byc8Awy56IK1-V6:-KWo4nR1u3iAcdV3YmzS:b-sjr56p) ([raw file](https://github.com/powershell/sharepointdsc/blob/c187ee9f556cb959bfb6084fb8f9073ba30e326b/Modules/SharePointDsc/DSCResources/MSFT_SPDatabaseAAG/MSFT_SPDatabaseAAG.psm1#L74)):*
<details><summary><i>Previously, ykuijs (Yorick Kuijs) wrote…</i></summary>
> I had an issue here:
> When you specify Ensure=Absent and the database doesn't exist, the Get method returns Absent as well. This is causing the Test method to return true, which is not correct. So either I had to throw an exception (like I do in the Set method) or introduce a third value. I chose the latter one.
</details>
Ahhhh ok, so good call on not throwing the exception, happy with that approach. Could we perhaps return an empty string for database name if it's not found as an indicator that the databases don't exist instead? What do you think of that approach.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPDatabaseAAG/MSFT_SPDatabaseAAG.psm1, line 175 at r1](https://reviewable.io:443/reviews/powershell/sharepointdsc/458#-KWj4sGX8Vl2M_FeKyQC:-KWo4zx8oPqLRekkKVWs:b-yzco8a) ([raw file](https://github.com/powershell/sharepointdsc/blob/c187ee9f556cb959bfb6084fb8f9073ba30e326b/Modules/SharePointDsc/DSCResources/MSFT_SPDatabaseAAG/MSFT_SPDatabaseAAG.psm1#L175)):*
<details><summary><i>Previously, ykuijs (Yorick Kuijs) wrote…</i></summary>
> Not sure what you mean here.
</details>
so right now you have it like this:

    $_.Name -like "*$($params.DatabaseName)*"

which means if I want to find databases that contain a string (lets say "SP_") then I set database name to "SP_". But if you change it to be this:

    $_.Name -like $params.DatabaseName

It gives me the flexibility to put the wildcards in myself - so I can either specify a specific name (like "SP_Content"), or databases that have a prefix (like "SP_*") or databases that have a suffix (like "*_Content") or even things that contain a string anywhere (like "*Content*"). We essentially shift it to put the placement of the wildcard in the config authors hands rather than us assuming they are looking for a string anywhere in the name like in your line here. Does that make more sense?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/458)*

**Comment by BrianFarnhill** [comment]
Review status: all files reviewed at latest revision, 12 unresolved discussions.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPDatabaseAAG/MSFT_SPDatabaseAAG.psm1, line 175 at r1](https://reviewable.io:443/reviews/powershell/sharepointdsc/458#-KWj4sGX8Vl2M_FeKyQC:-KWo6PhWg2y4wtG5su9-:b-7ekpau) ([raw file](https://github.com/powershell/sharepointdsc/blob/c187ee9f556cb959bfb6084fb8f9073ba30e326b/Modules/SharePointDsc/DSCResources/MSFT_SPDatabaseAAG/MSFT_SPDatabaseAAG.psm1#L175)):*
<details><summary><i>Previously, BrianFarnhill (Brian Farnhill) wrote…</i></summary>
> so right now you have it like this:
> 
>     $_.Name -like "*$($params.DatabaseName)*"
> 
> which means if I want to find databases that contain a string (lets say "SP_") then I set database name to "SP_". But if you change it to be this:
> 
>     $_.Name -like $params.DatabaseName
> 
> It gives me the flexibility to put the wildcards in myself - so I can either specify a specific name (like "SP_Content"), or databases that have a prefix (like "SP_*") or databases that have a suffix (like "*_Content") or even things that contain a string anywhere (like "*Content*"). We essentially shift it to put the placement of the wildcard in the config authors hands rather than us assuming they are looking for a string anywhere in the name like in your line here. Does that make more sense?
</details>
Just realised why the first comment made no sense - when I was putting the \* in to the text GitHub thought I wanted to be italic based on the markdown syntax! I just updated my above comment to fix that so hopefully now it makes sense :P 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/458)*

**Comment by ykuijs** [comment]
Review status: all files reviewed at latest revision, 12 unresolved discussions.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPDatabaseAAG/MSFT_SPDatabaseAAG.psm1, line 74 at r1](https://reviewable.io:443/reviews/powershell/sharepointdsc/458#-KWj1byc8Awy56IK1-V6:-KXG9RPRzyHCSuJYxYIV:b77e1ey) ([raw file](https://github.com/powershell/sharepointdsc/blob/c187ee9f556cb959bfb6084fb8f9073ba30e326b/Modules/SharePointDsc/DSCResources/MSFT_SPDatabaseAAG/MSFT_SPDatabaseAAG.psm1#L74)):*
<details><summary><i>Previously, BrianFarnhill (Brian Farnhill) wrote…</i></summary>
> Ahhhh ok, so good call on not throwing the exception, happy with that approach. Could we perhaps return an empty string for database name if it's not found as an indicator that the databases don't exist instead? What do you think of that approach.
</details>
I am fine with returning an empty string, as long as it isn't Present or Absent :-)

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPDatabaseAAG/MSFT_SPDatabaseAAG.psm1, line 113 at r1](https://reviewable.io:443/reviews/powershell/sharepointdsc/458#-KWj21z-GyF8AIvxFKjE:-KXG9a_NVq5ISblnfAvS:bdgx0el) ([raw file](https://github.com/powershell/sharepointdsc/blob/c187ee9f556cb959bfb6084fb8f9073ba30e326b/Modules/SharePointDsc/DSCResources/MSFT_SPDatabaseAAG/MSFT_SPDatabaseAAG.psm1#L113)):*
<details><summary><i>Previously, BrianFarnhill (Brian Farnhill) wrote…</i></summary>
> Ensure should be set to "Absent" if they aren't in the correct group. 
</details>
As discussed in previous point: Returning an empty string now.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPDatabaseAAG/MSFT_SPDatabaseAAG.psm1, line 175 at r1](https://reviewable.io:443/reviews/powershell/sharepointdsc/458#-KWj4sGX8Vl2M_FeKyQC:-KXG9eqnSONMnxBoW-ZG:bfzoo6r) ([raw file](https://github.com/powershell/sharepointdsc/blob/c187ee9f556cb959bfb6084fb8f9073ba30e326b/Modules/SharePointDsc/DSCResources/MSFT_SPDatabaseAAG/MSFT_SPDatabaseAAG.psm1#L175)):*
<details><summary><i>Previously, BrianFarnhill (Brian Farnhill) wrote…</i></summary>
> Just realised why the first comment made no sense - when I was putting the \* in to the text GitHub thought I wanted to be italic based on the markdown syntax! I just updated my above comment to fix that so hopefully now it makes sense :P 
</details>
Agree, will change this.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPDatabaseAAG/MSFT_SPDatabaseAAG.psm1, line 206 at r1](https://reviewable.io:443/reviews/powershell/sharepointdsc/458#-KWj2pytYam-vdudvtTw:-KXG9iKF4X0XeVCMghXw:b-896fix) ([raw file](https://github.com/powershell/sharepointdsc/blob/c187ee9f556cb959bfb6084fb8f9073ba30e326b/Modules/SharePointDsc/DSCResources/MSFT_SPDatabaseAAG/MSFT_SPDatabaseAAG.psm1#L206)):*
<details><summary><i>Previously, BrianFarnhill (Brian Farnhill) wrote…</i></summary>
> Probably don't need this comment here when the verbose output below tells us the same thing
</details>
Done.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPDatabaseAAG/MSFT_SPDatabaseAAG.psm1, line 228 at r1](https://reviewable.io:443/reviews/powershell/sharepointdsc/458#-KWj4U9wn5qUuzMG49Zu:-KXG9jSlKxvaWqP_mynY:b-896fix) ([raw file](https://github.com/powershell/sharepointdsc/blob/c187ee9f556cb959bfb6084fb8f9073ba30e326b/Modules/SharePointDsc/DSCResources/MSFT_SPDatabaseAAG/MSFT_SPDatabaseAAG.psm1#L228)):*
<details><summary><i>Previously, BrianFarnhill (Brian Farnhill) wrote…</i></summary>
> Same about redundant comment
</details>
Done.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPDatabaseAAG/MSFT_SPDatabaseAAG.psm1, line 288 at r1](https://reviewable.io:443/reviews/powershell/sharepointdsc/458#-KWj4Y_rG8RVWajcjEyq:-KXGAFegNPBXb47Njbfu:b-896fix) ([raw file](https://github.com/powershell/sharepointdsc/blob/c187ee9f556cb959bfb6084fb8f9073ba30e326b/Modules/SharePointDsc/DSCResources/MSFT_SPDatabaseAAG/MSFT_SPDatabaseAAG.psm1#L288)):*
<details><summary><i>Previously, BrianFarnhill (Brian Farnhill) wrote…</i></summary>
> We can probably ditch the check here as the first thing we do in the test method, is call the get method - which will do the check, so this becomes a bit redundant here.
</details>
Done.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPDatabaseAAG/Readme.md, line 9 at r1](https://reviewable.io:443/reviews/powershell/sharepointdsc/458#-KWj5ILS4Su4fRPVimAD:-KXGAHOH8ZqeYSpvgj0u:b-896fix) ([raw file](https://github.com/powershell/sharepointdsc/blob/c187ee9f556cb959bfb6084fb8f9073ba30e326b/Modules/SharePointDsc/DSCResources/MSFT_SPDatabaseAAG/Readme.md#L9)):*
<details><summary><i>Previously, BrianFarnhill (Brian Farnhill) wrote…</i></summary>
> We might need to tweak this based on the feedback about how we pattern match above. 
</details>
Done.

---

*[Modules/SharePointDsc/Examples/Resources/SPDatabaseAAG/2-AddMultipleDBstoAAG.ps1, line 19 at r1](https://reviewable.io:443/reviews/powershell/sharepointdsc/458#-KWj5OY_rMKE6hZzTVGp:-KXGAgoudIikB0wY7g-x:b-896fix) ([raw file](https://github.com/powershell/sharepointdsc/blob/c187ee9f556cb959bfb6084fb8f9073ba30e326b/Modules/SharePointDsc/Examples/Resources/SPDatabaseAAG/2-AddMultipleDBstoAAG.ps1#L19)):*
<details><summary><i>Previously, BrianFarnhill (Brian Farnhill) wrote…</i></summary>
> We might need to tweak this based on the feedback about how we pattern match above. 
</details>
Done.

---

*[Tests/Unit/SharePointDsc/SharePointDsc.SPDatabaseAAG.Tests.ps1, line 65 at r1](https://reviewable.io:443/reviews/powershell/sharepointdsc/458#-KWj5cF2UsLESe3LJQqr:-KXGBrSAhii6k17PIURB:b-896fix) ([raw file](https://github.com/powershell/sharepointdsc/blob/c187ee9f556cb959bfb6084fb8f9073ba30e326b/Tests/Unit/SharePointDsc/SharePointDsc.SPDatabaseAAG.Tests.ps1#L65)):*
<details><summary><i>Previously, BrianFarnhill (Brian Farnhill) wrote…</i></summary>
> Can we change the contexts for multiple database scenarios to clearly say "Multiple databases matching a name pattern" instead of "the databases"
</details>
Done.

---

*[Tests/Unit/SharePointDsc/SharePointDsc.SPDatabaseAAG.Tests.ps1, line 67 at r1](https://reviewable.io:443/reviews/powershell/sharepointdsc/458#-KWj5WLuJVxfHszBT3ai:-KXGBsPySGLHa4Ug3n59:b-896fix) ([raw file](https://github.com/powershell/sharepointdsc/blob/c187ee9f556cb959bfb6084fb8f9073ba30e326b/Tests/Unit/SharePointDsc/SharePointDsc.SPDatabaseAAG.Tests.ps1#L67)):*
<details><summary><i>Previously, BrianFarnhill (Brian Farnhill) wrote…</i></summary>
> We might need to tweak this based on the feedback about how we pattern match above. 
</details>
Done.

---

*[Tests/Unit/SharePointDsc/SharePointDsc.SPDatabaseAAG.Tests.ps1, line 162 at r1](https://reviewable.io:443/reviews/powershell/sharepointdsc/458#-KWj5Y7HyW4ZF9g-jzQM:-KXGBtSUBUa9_bMX3rwo:b-896fix) ([raw file](https://github.com/powershell/sharepointdsc/blob/c187ee9f556cb959bfb6084fb8f9073ba30e326b/Tests/Unit/SharePointDsc/SharePointDsc.SPDatabaseAAG.Tests.ps1#L162)):*
<details><summary><i>Previously, BrianFarnhill (Brian Farnhill) wrote…</i></summary>
> We might need to tweak this based on the feedback about how we pattern match above. 
</details>
Done.

---

*[Tests/Unit/SharePointDsc/SharePointDsc.SPDatabaseAAG.Tests.ps1, line 283 at r1](https://reviewable.io:443/reviews/powershell/sharepointdsc/458#-KWj5_Ud9YR3wakkvMn7:-KXGBu6iB7Xkb9cqM3Ds:b-896fix) ([raw file](https://github.com/powershell/sharepointdsc/blob/c187ee9f556cb959bfb6084fb8f9073ba30e326b/Tests/Unit/SharePointDsc/SharePointDsc.SPDatabaseAAG.Tests.ps1#L283)):*
<details><summary><i>Previously, BrianFarnhill (Brian Farnhill) wrote…</i></summary>
> We might need to tweak this based on the feedback about how we pattern match above. 
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/458)*

**Comment by BrianFarnhill** [comment]
Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPDatabaseAAG/MSFT_SPDatabaseAAG.psm1, line 74 at r1](https://reviewable.io:443/reviews/powershell/sharepointdsc/458#-KWj1byc8Awy56IK1-V6:-KYBUWL8aClYi-50Dp1l:b-cdfnrl) ([raw file](https://github.com/powershell/sharepointdsc/blob/c187ee9f556cb959bfb6084fb8f9073ba30e326b/Modules/SharePointDsc/DSCResources/MSFT_SPDatabaseAAG/MSFT_SPDatabaseAAG.psm1#L74)):*
<details><summary><i>Previously, ykuijs (Yorick Kuijs) wrote…</i></summary><blockquote>

I am fine with returning an empty string, as long as it isn't Present or Absent :-)
</blockquote></details>

I meant the database name should be an empty string, not the ensure property. That way it signifies that the database can't be found through that rather than relying on an unknown property state for "Ensure"

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPDatabaseAAG/MSFT_SPDatabaseAAG.psm1, line 113 at r1](https://reviewable.io:443/reviews/powershell/sharepointdsc/458#-KWj21z-GyF8AIvxFKjE:-KYBUi3tpua5uaXkYTnU:b-9chp70) ([raw file](https://github.com/powershell/sharepointdsc/blob/c187ee9f556cb959bfb6084fb8f9073ba30e326b/Modules/SharePointDsc/DSCResources/MSFT_SPDatabaseAAG/MSFT_SPDatabaseAAG.psm1#L113)):*
<details><summary><i>Previously, ykuijs (Yorick Kuijs) wrote…</i></summary><blockquote>

As discussed in previous point: Returning an empty string now.
</blockquote></details>

as above

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/458)*

**Comment by ykuijs** [comment]
Review status: 4 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPDatabaseAAG/MSFT_SPDatabaseAAG.psm1, line 74 at r1](https://reviewable.io:443/reviews/powershell/sharepointdsc/458#-KWj1byc8Awy56IK1-V6:-KYOqX3lDAL0ylbwr3ru:b-896fix) ([raw file](https://github.com/powershell/sharepointdsc/blob/c187ee9f556cb959bfb6084fb8f9073ba30e326b/Modules/SharePointDsc/DSCResources/MSFT_SPDatabaseAAG/MSFT_SPDatabaseAAG.psm1#L74)):*
<details><summary><i>Previously, BrianFarnhill (Brian Farnhill) wrote…</i></summary><blockquote>

I meant the database name should be an empty string, not the ensure property. That way it signifies that the database can't be found through that rather than relying on an unknown property state for "Ensure"
</blockquote></details>

Done.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPDatabaseAAG/MSFT_SPDatabaseAAG.psm1, line 113 at r1](https://reviewable.io:443/reviews/powershell/sharepointdsc/458#-KWj21z-GyF8AIvxFKjE:-KYOqXnbA2b5Ww5_w4zB:b-896fix) ([raw file](https://github.com/powershell/sharepointdsc/blob/c187ee9f556cb959bfb6084fb8f9073ba30e326b/Modules/SharePointDsc/DSCResources/MSFT_SPDatabaseAAG/MSFT_SPDatabaseAAG.psm1#L113)):*
<details><summary><i>Previously, BrianFarnhill (Brian Farnhill) wrote…</i></summary><blockquote>

as above
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/458)*

**Comment by BrianFarnhill** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/458)*

**Pull request merged**
