### PR TITLE
Update AppVeyor.yml image

### PR DESCRIPTION
**Pull request by ykuijs**
Test to see what happens if we don't specify an image in the AppVeyor.yml file

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/sharepointdsc/806)

### CODE REVIEW

**Comment by johlju** [comment]
@ykuijs Seems that it worked! Just the question if you need run tests on WMF 5.0 (support WMF 5.0?) or if WMF 5.1 works?

**Comment by johlju** [comment]
@ykuijs If SharePointDsc need to support (be tested on) WMF 5.0, then we should resolve this in the test framework.
Running this before download of Codecov.exe starts https://stackoverflow.com/questions/41618766/powershell-invoke-webrequest-fails-with-ssl-tls-secure-channel

**Comment by johlju** [comment]
@ykuijs I just saw you https://github.com/PowerShell/SharePointDsc/pull/803#issuecomment-391842515. 😃

**Comment by johlju** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[appveyor.yml, line 2 at r1](https://reviewable.io/reviews/powershell/sharepointdsc/806#-LDMQm5N9ZxjG4U6ZsSs:-LDMQm5N9ZxjG4U6ZsSt:bbr1ayo) ([raw file](https://github.com/powershell/sharepointdsc/blob/76e31844ada1c2bc87b7b9b6604aab974bed6e40/appveyor.yml#L2)):*
> ```YAML
> version: 2.3.0.{build}
> #image: WMF 5
> ```

Remove this row, or change to `image: Visual Studio 2017` or `image: Visual Studio 2017.

---


*Comments from [Reviewable](https://reviewable.io/reviews/powershell/sharepointdsc/806)*

**Comment by ykuijs** [comment]
I commented out the line for testing purposes......have not deleted the line ;-)

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[appveyor.yml, line 2 at r1](https://reviewable.io/reviews/powershell/sharepointdsc/806#-LDMQm5N9ZxjG4U6ZsSs:-LDMS-yC8lAjDiUOVDKi:b-896fix) ([raw file](https://github.com/powershell/sharepointdsc/blob/76e31844ada1c2bc87b7b9b6604aab974bed6e40/appveyor.yml#L2)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Remove this row, or change to `image: Visual Studio 2017` or `image: Visual Studio 2017.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/powershell/sharepointdsc/806#-:-LDMS0sQ853hLS6cGA4t:b9b3hfh)*

**Comment by johlju** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/powershell/sharepointdsc/806#-:-LDMSDRUEYIgjzPujoLp:bnfp4nl)*

**Comment by johlju** [comment]
@ykuijs I let you merge 🙂

**Comment by ykuijs** [comment]
I will.....once AppVeyor has completed ;-)

Are you going to update your PR with this change after the merge?

**Comment by johlju** [comment]
Yes, I rebase my PR so we do it correctly. :)

**Pull request merged**
