### PR TITLE
Another bugfix PR (very large)

### LINKED ISSUE #1062: SPInstallPrereqs potentially problem checking version
#### Details of the scenario you tried and the problem that is occurring
Trying to install SharePoint 2019 and wondered about an error while installing Prereqs. The version was not correct.
I wondered about the code within the ressource.

#### Verbose logs showing the problem
Prerequisite [PLaceholder] was found but had unexpected version. Expected minimum version [WAS EMPTY] but found version 14.12.X.Y.

#### Suggested solution to the issue
The code seems to be not correct or do I forgot anything? I guess the if is not correct for e.g. the following values:
MinimumRequiredVersion: 15.1.0.3
InstalledVersion: 16.0.1.2
Afterwards $isRequiredVersionInstalled is $false I guess but should be $true?

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
The code implemented was:
```powershell
                    $isRequiredVersionInstalled = $true;

                    [int[]]$minimumRequiredVersion = $itemToCheck.MinimumRequiredVersion.Split('.')
                    [int[]]$installedVersion = $installedItem.DisplayVersion.Split('.')
                    for ([int]$index = 0; $index -lt $minimumRequiredVersion.Length -and $index -lt $installedVersion.Length; $index++)
                    {
                        if ($minimumRequiredVersion[$index] -gt $installedVersion[$index])
                        {
                            $isRequiredVersionInstalled = $false;
                        }
                    }
```

#### The operating system the target node is running
N/A

#### Version of SharePoint that is used (e.g. SharePoint 2016)
SharePoint 2019

#### Version and build of PowerShell the target node is running
5.1

#### Version of the DSC module that was used ('dev' if using current dev branch)
3.3.0.0

### LINKED ISSUE #1067: SPUserProfileSyncConnection: Test fails when specifying the Server parameter
#### Details of the scenario you tried and the problem that is occurring
When specifying the Server parameter in SPUserProfileSyncConnection, the Test method always fails because the Get method always returns Server=null.

#### Suggested solution to the issue
Do not check the Server parameter in SP2016

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
N/A

#### The operating system the target node is running
Windows 2016

#### Version of SharePoint that is used (e.g. SharePoint 2016)
SP2016/2019

#### Version and build of PowerShell the target node is running
v5.1

#### Version of the DSC module that was used ('dev' if using current dev branch)
Dev

### LINKED ISSUE #1068: SPConfigWizard: Should not try to run wizard if other servers do not have the binaries installed yet
#### Details of the scenario you tried and the problem that is occurring
When other servers in the farm do not have the binaries installed yet, SPConfigWizard should not try to run the config wizard. This because the wizard first stops the IIS W3 processes and then fails because it cannot upgrade servers. Unfortunately it does not restart IIS and therefore causing downtime.

#### Suggested solution to the issue
Implement a check to see if the config wizard can be ran. The following code is able to do that, but has to be tested on 2013 and 2016 before implementing:
```PowerShell
$farm = Get-SPFarm
$productVersions = [Microsoft.SharePoint.Administration.SPProductVersions]::GetProductVersions($farm)
$server = Get-SPServer $env:COMPUTERNAME
$serverProductInfo = $productVersions.GetServerProductInfo($server.Id);
if ($null -ne $serverProductInfo)
{
	$products = $serverProductInfo.Products;
	$statusType = $serverProductInfo.InstallStatus;
	if ($statusType -ne 0)
	{
		$statusType = $serverProductInfo.GetUpgradeStatus($farm, $server);
	}
}
else
{
	$statusType = [Microsoft.SharePoint.Administration.SPServerProductInfo+StatusType]::NoActionRequired;
}
Write-Host "StatusType: $statusType"

if ($statusType -ne "NoActionRequired")
{
    Write-Host "Upgrade not possible"
}

```

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
N/A

#### The operating system the target node is running
Windows 2016

#### Version of SharePoint that is used (e.g. SharePoint 2016)
SP2019

#### Version and build of PowerShell the target node is running
v5.1

#### Version of the DSC module that was used ('dev' if using current dev branch)
Dev

### LINKED ISSUE #1070: SPSecureStoreServiceApp is set to absent but test finds it and set does not.
#### Verbose logs showing the problem

VERBOSE: [VM0013]: LCM:  [ Start  Test     ]  [[SPSecureStoreServiceApp]SecureStoreServiceApp]
VERBOSE: [VM0013]:                            [[SPSecureStoreServiceApp]SecureStoreServiceApp] Testing secure store service application Secure Store Service Application
VERBOSE: [VM0013]:                            [[SPSecureStoreServiceApp]SecureStoreServiceApp] Getting secure store service application 'Secure Store Service Application'
VERBOSE: [VM0013]:                            [[SPSecureStoreServiceApp]SecureStoreServiceApp] Executing as the local run as user CONTOSO\SPAdmin
VERBOSE: [VM0013]:                            [[SPSecureStoreServiceApp]SecureStoreServiceApp] Leaving BeginProcessing Method of Get-SPServiceApplication.
VERBOSE: [VM0013]:                            [[SPSecureStoreServiceApp]SecureStoreServiceApp] Leaving ProcessRecord Method of Get-SPServiceApplication.
VERBOSE: [VM0013]:                            [[SPSecureStoreServiceApp]SecureStoreServiceApp] Leaving EndProcessing Method of Get-SPServiceApplication.
VERBOSE: [VM0013]:                            [[SPSecureStoreServiceApp]SecureStoreServiceApp] Specified database name does not match the actual database name. This resource cannot rename the database.
VERBOSE: [VM0013]: LCM:  [ End    Test     ]  [[SPSecureStoreServiceApp]SecureStoreServiceApp]  in 0.2660 seconds.
VERBOSE: [VM0013]: LCM:  [ Start  Set      ]  [[SPSecureStoreServiceApp]SecureStoreServiceApp]
VERBOSE: [VM0013]:                            [[SPSecureStoreServiceApp]SecureStoreServiceApp] Setting secure store service application 'Secure Store Service Application'
VERBOSE: [VM0013]:                            [[SPSecureStoreServiceApp]SecureStoreServiceApp] Getting secure store service application 'Secure Store Service Application'
VERBOSE: [VM0013]:                            [[SPSecureStoreServiceApp]SecureStoreServiceApp] Executing as the local run as user CONTOSO\SPAdmin
VERBOSE: [VM0013]:                            [[SPSecureStoreServiceApp]SecureStoreServiceApp] Leaving BeginProcessing Method of Get-SPServiceApplication.
VERBOSE: [VM0013]:                            [[SPSecureStoreServiceApp]SecureStoreServiceApp] Leaving ProcessRecord Method of Get-SPServiceApplication.
VERBOSE: [VM0013]:                            [[SPSecureStoreServiceApp]SecureStoreServiceApp] Leaving EndProcessing Method of Get-SPServiceApplication.
VERBOSE: [VM0013]:                            [[SPSecureStoreServiceApp]SecureStoreServiceApp] Removing Secure Store Service Application Secure Store Service Application
VERBOSE: [VM0013]:                            [[SPSecureStoreServiceApp]SecureStoreServiceApp] Executing as the local run as user CONTOSO\SPAdmin
VERBOSE: [VM0013]:                            [[SPSecureStoreServiceApp]SecureStoreServiceApp] Leaving BeginProcessing Method of Get-SPServiceApplication.
Object not found.
    + CategoryInfo          : ObjectNotFound: (Microsoft.Share...viceApplication:) [], CimException
    + FullyQualifiedErrorId : Microsoft.SharePoint.PowerShell.SPCmdletGetServiceApplication
    + PSComputerName        : localhost
 
VERBOSE: [VM0013]:                            [[SPSecureStoreServiceApp]SecureStoreServiceApp] Leaving ProcessRecord Method of Get-SPServiceApplication.
VERBOSE: [VM0013]:                            [[SPSecureStoreServiceApp]SecureStoreServiceApp] Leaving EndProcessing Method of Get-SPServiceApplication.
VERBOSE: [VM0013]:                            [[SPSecureStoreServiceApp]SecureStoreServiceApp] Leaving BeginProcessing Method of Get-SPServiceApplicationProxy.
VERBOSE: [VM0013]:                            [[SPSecureStoreServiceApp]SecureStoreServiceApp] Leaving ProcessRecord Method of Get-SPServiceApplicationProxy.
VERBOSE: [VM0013]:                            [[SPSecureStoreServiceApp]SecureStoreServiceApp] Leaving EndProcessing Method of Get-SPServiceApplicationProxy.
VERBOSE: [VM0013]: LCM:  [ End    Set      ]  [[SPSecureStoreServiceApp]SecureStoreServiceApp]  in 0.4220 seconds.
PowerShell DSC resource MSFT_SPSecureStoreServiceApp  failed to execute Set-TargetResource functionality with error message: You cannot call a method on a null-valued expression. 
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : ProviderOperationExecutionFailure
    + PSComputerName        : localhost
 
VERBOSE: [VM0013]:                            [] Consistency check completed.
The SendConfigurationApply function did not succeed. LCM failed to start desired state configuration manually.
    + CategoryInfo          : NotSpecified: (root/Microsoft/...gurationManager:String) [], CimException
    + FullyQualifiedErrorId : MI RESULT 1
    + PSComputerName        : localhost
 
VERBOSE: Operation 'Invoke CimMethod' complete.
VERBOSE: Time taken for configuration job to complete is 81.671 seconds

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
# insert configuration here
ServiceApplications = @{
    AccessService             = "Absent"                          # Present or Absent. Requires SQL Mixed mode authentication.
    AppManagementService      = "Absent"                         # Present or Absent. 
    MachineTranslationService = "Present"                         # Present or Absent. 
    ManagedMetadataService    = "Absent"                         # Present or Absent. 
    PerformancePointService   = "Present"                         # Present or Absent. 
    ProjectServerService      = "Absent"                         # Present or Absent. 
    SearchService             = "Present"                         # Present or Absent. 
    SecureStoreService        = "Absent"                         # Present or Absent. 
    SubScriptionService       = "Present"                         # Present or Absent. 
    UserProfileService        = "Absent"                         # Present or Absent. 
    VisoGraphicsService       = "Present"                         # Present or Absent.
    WordAutomationService     = "Absent"                         # Present or Absent. 
    WorkFlow                  = "Present"                         # Present or Absent. 
}     


# SECURESTORE SA
SPSecureStoreServiceApp SecureStoreServiceApp
{
    Name                 = "Secure Store Service Application"
    Ensure               = $ConfigurationData.NonNodeData.SharePoint.ServiceApplications.SecureStoreService
    ApplicationPool      = $ConfigurationData.NonNodeData.SharePoint.ApplicationPool
    AuditingEnabled      = $true
    AuditlogMaxSize      = 30
    DatabaseName         = ($ConfigurationData.NonNodeData.SharePoint.DataBasePrefix + "SecureStore")
    PsDscRunAsCredential = $SPSetupCred
    DependsOn            = "[AddEntryToLog]Log_SPSubscriptionSettingsServiceApp"
}

#### The operating system the target node is running
Microsoft server 2012 R2 Standard
StandardServerEdition
64-bit
Eng-Us

#### Version of SharePoint that is used (e.g. SharePoint 2016)
SP 2016 Update may 2019

#### Version and build of PowerShell the target node is running
5.1

#### Version of the DSC module that was used ('dev' if using current dev branch)
3.3.0.0

### LINKED ISSUE #1071: Improve logging of resources to compare values in Test method
#### Details of the scenario you tried and the problem that is occurring
When the Test method performs its test, it would be nice to display the current and desired output in the Verbose output.

#### Suggested solution to the issue
Implement solution to output the current and desired values in the Verbose log

### LINKED ISSUE #1072: Update resources that return Null from the Get method when an unexpected issue occurs
#### Details of the scenario you tried and the problem that is occurring
Initially we returned Null when anything happened in the Get method. This practice however changed and we are now returning a Hashtable, which contains Null values. Unfortunately not all resources were (fully) updated to match this new practice:

SPDesignerSettings, SPDiagnosticLoggingSettings, SPFarmAdministrators, SPHealthAnalyzerRuleState, SPIrmSettings, SPOutgoingEmailSettings, SPPasswordChangeSettings, SPSearchTopology, SPTimerJobState, SPUserProfileSection, SPUserProfileSyncConnection, SPWebAppBlockedFileTypes, SPWebApplicationAppDomain, SPWebAppPolicy, SPWebAppSiteUseAndDeletion, SPWebAppThrottlingSettings, SPWordAutomationServiceApp

#### Suggested solution to the issue
Update all above resources to match the current practice.

#### Version of the DSC module that was used ('dev' if using current dev branch)
Dev

### PR DESCRIPTION
**Pull request by ykuijs**
#### Pull Request (PR) description
This is a huge PR which fixes several issues, but also contains a lot of coding style updates.

#### This Pull Request (PR) fixes the following issues
- Fixes #1062 
- Fixes #1067 
- Fixes #1068 
- Fixes #1070  
- Fixes #1071 
- Fixes #1072 

#### Task list
- [X] Added an entry under the Unreleased section of the change log in the CHANGELOG.md.
      Entry should say what was changed, and how that affects users (if applicable).
- [X] Resource documentation added/updated in README.md in the resource folder.
- [X] Resource parameter descriptions added/updated in schema.mof
      and comment-based help.
- [X] Comment-based help added/updated.
- [X] Localization strings added/updated in all localization files as appropriate.
- [X] Examples appropriately added/updated.
- [X] Unit tests added/updated. See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [X] Integration tests added/updated (where possible). See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [X] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/sharepointdsc/1073)

### CODE REVIEW

**Comment by ykuijs** [comment]
@NikCharlebois Can you do the honors?? Sorry for the size of it ;-)

**Comment by NikCharlebois** [comment]
Will do on Saturday on the plane back from SPC :)

**Comment by ykuijs** [comment]
@NikCharlebois Any update mate?

**Comment by ykuijs** [comment]
@NikCharlebois is out-of-the-office this week.

@andikrueger, @ronx, @jensotto One of you guys able to review this PR?

**Comment by andikrueger** [comment]
I'm on it. Should I do the whole review or should I publish my WIP?

I hope that I don't miss anything...

**Comment by andikrueger** [comment]
I'm OK with a new PR for the remaining .tests.ps1 files! I will verify your changes during this week.

**Comment by ykuijs** [comment]
@andikrueger Any update on the review?

**Comment by andikrueger** [comment]
@ykuijs Your turn

**Pull request merged**
