### PR TITLE
Fix SPWebAppPolicy with OS in non-EnUS language

### PR DESCRIPTION
**Pull request by luigilink**
Fixed issue with SPWebAppPolicy resource and OS in non-EnUS language

- [x] Change details added to Unreleased section of changelog.md?
- [x] Added/updated documentation and descriptions in .schema.mof files where appropriate?
- [x] Examples updated for both the single server and small farm templates in the examples folder?
- [x] New/changed code adheres to [Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md)?
- [x] [Unit and Integration tests](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md) created/updated where possible?

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/sharepointdsc/504)

### CODE REVIEW

**Comment by BrianFarnhill** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[Tests/Unit/SharePointDsc/SharePointDsc.SPWebAppPolicy.Tests.ps1, line 202 at r1](https://reviewable.io:443/reviews/powershell/sharepointdsc/504#-KcU9X3HDtdEOl8YtcD3:-KcU9X3HDtdEOl8YtcD4:butayp4) ([raw file](https://github.com/powershell/sharepointdsc/blob/7e959d29ecc3236a24049b6e829c7199912978fc/Tests/Unit/SharePointDsc/SharePointDsc.SPWebAppPolicy.Tests.ps1#L202)):*
> ```PowerShell
>                     @{
>                         Name = "Full Read"
>                         Type = 'FullRead'
> ```

Looking at [the doco for the Type property](https://msdn.microsoft.com/en-us/library/office/microsoft.sharepoint.administration.sppolicyrole.type.aspx) it looks like Type isn't a string, it's a Enum type. While this test will work as a string, I would rather mock up the enumeration and use that in the tests. Have a look at [how we did this for SPBlobCacheSettings](https://github.com/PowerShell/SharePointDsc/blob/dev/Tests/Unit/SharePointDsc/SharePointDsc.SPBlobCacheSettings.Tests.ps1#L28) as that gives a perfect example of how to define this so you can return the enums in the mocks. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/504)*

**Comment by luigilink** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[Tests/Unit/SharePointDsc/SharePointDsc.SPWebAppPolicy.Tests.ps1, line 202 at r1](https://reviewable.io:443/reviews/powershell/sharepointdsc/504#-KcU9X3HDtdEOl8YtcD3:-KcwW6xYqTxkZj145Csh:b-pa7lma) ([raw file](https://github.com/powershell/sharepointdsc/blob/7e959d29ecc3236a24049b6e829c7199912978fc/Tests/Unit/SharePointDsc/SharePointDsc.SPWebAppPolicy.Tests.ps1#L202)):*
<details><summary><i>Previously, BrianFarnhill (Brian Farnhill) wrote…</i></summary><blockquote>

Looking at [the doco for the Type property](https://msdn.microsoft.com/en-us/library/office/microsoft.sharepoint.administration.sppolicyrole.type.aspx) it looks like Type isn't a string, it's a Enum type. While this test will work as a string, I would rather mock up the enumeration and use that in the tests. Have a look at [how we did this for SPBlobCacheSettings](https://github.com/PowerShell/SharePointDsc/blob/dev/Tests/Unit/SharePointDsc/SharePointDsc.SPBlobCacheSettings.Tests.ps1#L28) as that gives a perfect example of how to define this so you can return the enums in the mocks. 
</blockquote></details>

The Type property is already defined in line 21, is it enough ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/504)*

**Comment by BrianFarnhill** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[Tests/Unit/SharePointDsc/SharePointDsc.SPWebAppPolicy.Tests.ps1, line 202 at r1](https://reviewable.io:443/reviews/powershell/sharepointdsc/504#-KcU9X3HDtdEOl8YtcD3:-Kd38IeFVBT6vMe8RbbF:b-267jgk) ([raw file](https://github.com/powershell/sharepointdsc/blob/7e959d29ecc3236a24049b6e829c7199912978fc/Tests/Unit/SharePointDsc/SharePointDsc.SPWebAppPolicy.Tests.ps1#L202)):*
<details><summary><i>Previously, luigilink (Jean-Cyril Drouhin) wrote…</i></summary><blockquote>

The Type property is already defined in line 21, is it enough ?
</blockquote></details>

Ahhh, sorry I missed that. We need to just swap the string values here then for a type based enum - so something like [Microsoft.SharePoint.Administration.SPPolicyRoleType]::FullRead

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/504)*

**Comment by BrianFarnhill** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[Tests/Unit/SharePointDsc/SharePointDsc.SPWebAppPolicy.Tests.ps1, line 202 at r1](https://reviewable.io:443/reviews/powershell/sharepointdsc/504#-KcU9X3HDtdEOl8YtcD3:-Kdxw8Qi7JTK8DJWrWCV:b82eqax) ([raw file](https://github.com/powershell/sharepointdsc/blob/7e959d29ecc3236a24049b6e829c7199912978fc/Tests/Unit/SharePointDsc/SharePointDsc.SPWebAppPolicy.Tests.ps1#L202)):*
<details><summary><i>Previously, BrianFarnhill (Brian Farnhill) wrote…</i></summary><blockquote>

Ahhh, sorry I missed that. We need to just swap the string values here then for a type based enum - so something like [Microsoft.SharePoint.Administration.SPPolicyRoleType]::FullRead
</blockquote></details>

@luigilink Still waiting on you here buddy, can you get this last bit sorted so we can merge this in?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/504)*

**Comment by luigilink** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[Tests/Unit/SharePointDsc/SharePointDsc.SPWebAppPolicy.Tests.ps1, line 202 at r1](https://reviewable.io:443/reviews/powershell/sharepointdsc/504#-KcU9X3HDtdEOl8YtcD3:-Kdz4-KI5BtzVE43tBgX:b8espbh) ([raw file](https://github.com/powershell/sharepointdsc/blob/7e959d29ecc3236a24049b6e829c7199912978fc/Tests/Unit/SharePointDsc/SharePointDsc.SPWebAppPolicy.Tests.ps1#L202)):*
<details><summary><i>Previously, BrianFarnhill (Brian Farnhill) wrote…</i></summary><blockquote>

@luigilink Still waiting on you here buddy, can you get this last bit sorted so we can merge this in?
</blockquote></details>

Done. Sorry for the delay.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/504)*

**Comment by luigilink** [comment]
@BrianFarnhill Hope is good now 😄

**Comment by BrianFarnhill** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/504#-:-Ke0lOWqgsEW-M_SIWoN:bnfp4nl)*

**Pull request merged**
