### PR TITLE
Added the Reverse DSC Module and Unit Tests

### PR DESCRIPTION
**Pull request by NikCharlebois**
- [x] Original Release
- [x] Unit Tests Added

---

This change is [Reviewable](https://reviewable.io/reviews/PowerShell/SharePointDsc/396)

### CODE REVIEW

**Comment by BrianFarnhill** [comment]
@NikCharlebois Can you have a look at the failing tests please mate? Looks like you have issues with your path resolution when looking for the modules with the tests. Thanks dude

**Comment by BrianFarnhill** [comment]
@NikCharlebois Had a chance to look at this one dude? It's been sitting here for 2 weeks with failed tests and no new commits

**Comment by NikCharlebois** [comment]
Struggled a lot with the method's scope. the reverse DSC loads scripts that loads script that then load script...all tests are successful now!

**Comment by NikCharlebois** [comment]
@BrianFarnhill Ready for review....finally

**Comment by kilasuit** [comment]
@NikCharlebois - as a suggestion whilst you figure out the issues around getting the tests to workout correctly is that for a big change like this I make use of a pre commit git hook that runs the tests locally prior to the commit being completed.

This has the benefit that where any of the tests fail then it will roll back the commit to "staging" but not changing what you've been working on which should allow you to get a single "clean" commit added.

It isn't too difficult to get this setup as detailed in http://d.evops.co/?p=278 and that hopefully will help you with getting to a PR with a single commit that could be merged as this PR now has 70 commits added.

This is just a thought as I don't see many people making use of pre commit hooks but it certainly looks like it would be useful in this scenario especially as this is a relatively big (functionally) PR

**Comment by kilasuit** [comment]
^^ Should have refreshed my page between starting to type that and actually finishing it off :joy:

**Comment by ykuijs** [comment]
@kilasuit, at least now we all know about the pre commit git hook functionality...so thanks for sharing :-p

**Comment by NikCharlebois** [comment]
Indeed, thanks for sharing. I was just being lazy and doing 5 things at the same time. The 20 minutes delay between each appveyor run actually worked out for me ;) I will setup the precommit first the ng tomorrow and try it out though. Cheers

**Comment by NikCharlebois** [comment]
As an FYI, I have written a separate function that is not yet included in this PR that converts the resulting DSC configuration script into a JSON object that can be queried and manipulated in PowerShell. The function re-formats the resulting DSC script into a JSON string and uses the ConvertFrom-JSON cmdlet to cast it into a PSCustomObject. The main reason why I wrote this method was to validate the format of the end-result string output (Pester tests validate the method, not the string output), but I do see a lot of other benefits. I am just not sure at this point where to include the function....does it really belong in SharePointDSC.Reverse or in SharePointDSC.Util...?

**Comment by NikCharlebois** [comment]
@kilasuit Looks like Pre-commit hooks are not supported by GitHub for Windows. Will have to look at integrating it with VisualStudio

**Comment by kilasuit** [comment]
@NikCharlebois - Or you could just ditch Github for Windows and use git properly as a cmdline tool :wink:

**Comment by NikCharlebois** [comment]
What?!? No GUI? That's crazy talk...and yes I am now using git.exe and running the pester tests locally :)

Nik Charlebois
Microsoft Premier Field Engineer
613-790-2331

________________________________

**Comment by BrianFarnhill** [comment]
I'll do the review on this one when I get a sec - have just parked it due to complexity. When I get a nice chunk of time to go through it all (hopefully over the weekend or early next week) I'll do this one in full mate.

**Comment by BrianFarnhill** [comment]
Review status: 0 of 2 files reviewed at latest revision, 9 unresolved discussions.

---

*[Modules/SharePointDsc/Modules/SharePointDSC.Reverse/SharePointDSC.Reverse.psm1, line 2 at r4](https://reviewable.io:443/reviews/powershell/sharepointdsc/396#-KTSWnJ0uh0iriE4NHz5:-KTSWnJ0uh0iriE4NHz6:bfsuhf5) ([raw file](https://github.com/powershell/sharepointdsc/blob/59ac5449ebbf50087205ea3d46e2fdbddbf0fcfa/Modules/SharePointDsc/Modules/SharePointDSC.Reverse/SharePointDSC.Reverse.psm1#L2)):*
> ```PowerShell
> <##############################################################
>  # This script is used to analyze an existing SharePoint (2013, 2016 or greater), and to produce the resulting PowerShell DSC Configuration Script representing it. Its purpose is to help SharePoint Admins and Devs replicate an existing SharePoint farm in an isolated area in order to troubleshoot an issue. This script needs to be executed directly on one of the SharePoint server in the far we wish to replicate. Upon finishing its execution, this Powershell script will prompt the user to specify a path to a FOLDER where the resulting PowerShell DSC Configuraton (.ps1) script will be generated. The resulting script will be named "SP-Farm.DSC.ps1" and will contain an exact description, in DSC notation, of the various components and configuration settings of the current SharePoint Farm. This script can then be used in an isolated environment to replicate the SharePoint server farm. The script could also be used as a simple textual (while in a DSC notation format) description of what the configuraton of the SharePoint farm looks like. This script is meant to be community driven, and everyone is encourage to participate and help improve and mature it. It is not officially endorsed by Microsoft, and support is 'offered' on a best effort basis by its contributors. Bugs suggestions should be reported through the issue system on GitHub. They will be looked at as time permits.
> ```

Straight off the bat, this file is too huge to be easily manageable. We need to look at how we split this up in to more manageable pieces. I'll give it some thought as I go through the rest of the review but wanted to get that out as a starting point.

---

*[Modules/SharePointDsc/Modules/SharePointDSC.Reverse/SharePointDSC.Reverse.psm1, line 19 at r4](https://reviewable.io:443/reviews/powershell/sharepointdsc/396#-KTSYDiOqSBuc_b_0t0B:-KTSYDiOqSBuc_b_0t0C:bpgtbpj) ([raw file](https://github.com/powershell/sharepointdsc/blob/59ac5449ebbf50087205ea3d46e2fdbddbf0fcfa/Modules/SharePointDsc/Modules/SharePointDSC.Reverse/SharePointDSC.Reverse.psm1#L19)):*
> ```PowerShell
>         if($loopCount -gt 0)
>         {
>             Write-Host "Please ensure the Farm Account provided is not the same as the current user. You may need to execute the script as a different user." -BackgroundColor Yellow -ForegroundColor Black
> ```

Why do we not allow the farm account to run the script? Whats the reasoning on this?

---

*[Modules/SharePointDsc/Modules/SharePointDSC.Reverse/SharePointDSC.Reverse.psm1, line 38 at r4](https://reviewable.io:443/reviews/powershell/sharepointdsc/396#-KTSYbbIE_LQPZ3BQq_S:-KTSYbbJif1Mw3tmjOLr:boceyqp) ([raw file](https://github.com/powershell/sharepointdsc/blob/59ac5449ebbf50087205ea3d46e2fdbddbf0fcfa/Modules/SharePointDsc/Modules/SharePointDSC.Reverse/SharePointDSC.Reverse.psm1#L38)):*
> ```PowerShell
>     $spServers = $spFarm.Servers
> 
>     $totalSteps = 6 + ($spServers.Length * 18)
> ```

This seems a little fragile - when we look at how to break up this file and process we should give some thought to how to manage the progress bar, it definitely need to be here I just think we need to calculate and manage it better.

---

*[Modules/SharePointDsc/Modules/SharePointDSC.Reverse/SharePointDSC.Reverse.psm1, line 153 at r4](https://reviewable.io:443/reviews/powershell/sharepointdsc/396#-KTSasspSM1-9246KAa0:-KTSasspSM1-9246KAa1:bb1v4i9) ([raw file](https://github.com/powershell/sharepointdsc/blob/59ac5449ebbf50087205ea3d46e2fdbddbf0fcfa/Modules/SharePointDsc/Modules/SharePointDSC.Reverse/SharePointDSC.Reverse.psm1#L153)):*
> ```PowerShell
> }
> 
> function Read-OperatingSystemVersion
> ```

Why are we capturing this if we don't need it for the actual configuration? 

---

*[Modules/SharePointDsc/Modules/SharePointDSC.Reverse/SharePointDSC.Reverse.psm1, line 162 at r4](https://reviewable.io:443/reviews/powershell/sharepointdsc/396#-KTS_8-FgPvesIvbB0P5:-KTS_8-Gjp7JdkBkGNum:b-byflr7) ([raw file](https://github.com/powershell/sharepointdsc/blob/59ac5449ebbf50087205ea3d46e2fdbddbf0fcfa/Modules/SharePointDsc/Modules/SharePointDSC.Reverse/SharePointDSC.Reverse.psm1#L162)):*
> ```PowerShell
>     {
>         $serverName = $spServer.Name
>         $osInfo = Get-WmiObject Win32_OperatingSystem  -ComputerName $serverName| Select-Object @{Label="OSName"; Expression={$_.Name.Substring($_.Name.indexof("W"),$_.Name.indexof("|")-$_.Name.indexof("W"))}} , Version ,OSArchitecture -ErrorAction SilentlyContinue
> ```

We should be using CIM objects instead of WMI. Look to swap this to Get-CimObject instead

---

*[Modules/SharePointDsc/Modules/SharePointDSC.Reverse/SharePointDSC.Reverse.psm1, line 168 at r4](https://reviewable.io:443/reviews/powershell/sharepointdsc/396#-KTSbTRBVTY543op_yi6:-KTSbTRBVTY543op_yi7:b-91i7w0) ([raw file](https://github.com/powershell/sharepointdsc/blob/59ac5449ebbf50087205ea3d46e2fdbddbf0fcfa/Modules/SharePointDsc/Modules/SharePointDSC.Reverse/SharePointDSC.Reverse.psm1#L168)):*
> ```PowerShell
> }
> 
> function Read-SQLVersion
> ```

Again whats the logic in capturing this?

---

*[Modules/SharePointDsc/Modules/SharePointDSC.Reverse/SharePointDSC.Reverse.psm1, line 222 at r4](https://reviewable.io:443/reviews/powershell/sharepointdsc/396#-KTSbsaWIQUCV8rlnngn:-KTSbsaWIQUCV8rlnngo:b-q2mxp1) ([raw file](https://github.com/powershell/sharepointdsc/blob/59ac5449ebbf50087205ea3d46e2fdbddbf0fcfa/Modules/SharePointDsc/Modules/SharePointDSC.Reverse/SharePointDSC.Reverse.psm1#L222)):*
> ```PowerShell
>         $tempConfigDataContent += "    @{`r`n"
>         $tempConfigDataContent += "        NodeName = `"" + $spServer.Name + "`";`r`n"
>         $tempConfigDataContent += "        PSDscAllowPlainTextPassword = `$true;`r`n"
> ```

We can't put this in as a default, it breaks the methodology of DSC where we assume secure defaults and allow you to turn them off afterwards, so this either needs to come out or it needs an option to set it that isn't the default.

---

*[Modules/SharePointDsc/Modules/SharePointDSC.Reverse/SharePointDSC.Reverse.psm1, line 233 at r4](https://reviewable.io:443/reviews/powershell/sharepointdsc/396#-KTScJx7M2EzSaxg2NQy:-KTScJx7M2EzSaxg2NQz:b-qwwq8e) ([raw file](https://github.com/powershell/sharepointdsc/blob/59ac5449ebbf50087205ea3d46e2fdbddbf0fcfa/Modules/SharePointDsc/Modules/SharePointDSC.Reverse/SharePointDSC.Reverse.psm1#L233)):*
> ```PowerShell
> 
> <## This function ensures all required DSC Modules are properly loaded into the current PowerShell session. #>
> function Set-Imports
> ```

We should add version numbers to these so its clear what versions are expected to work with what we generate

---

*[Modules/SharePointDsc/Modules/SharePointDSC.Reverse/SharePointDSC.Reverse.psm1, line 241 at r4](https://reviewable.io:443/reviews/powershell/sharepointdsc/396#-KTScbSiJaiZIEt25EdI:-KTScbSiJaiZIEt25EdJ:b-eulgh8) ([raw file](https://github.com/powershell/sharepointdsc/blob/59ac5449ebbf50087205ea3d46e2fdbddbf0fcfa/Modules/SharePointDsc/Modules/SharePointDSC.Reverse/SharePointDSC.Reverse.psm1#L241)):*
> ```PowerShell
> }
> 
> <## This function receives a user name and returns the "Display Name" for that user. This function is primarly used to identify the Farm (System) account. #>
> ```

Just marking where I am up to here in the review so I can pick up from here when I get back to it! No need to respond to this

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/396)*

**Comment by NikCharlebois** [comment]
@BrianFarnhill For Item #2 in the list, every time I run the script as the Farm admin, Util throws me the following error. 

I figured this is due to how the method handled the credentials. The error is being thrown n the code below. As an example, if you run the script as farm account, than both $Credential and $EnvUsername will be equal (e.g. "sp_farm" for both).

if ($Credential.UserName.Split("\")[1] -eq $Env:USERNAME) 
        { 
            if (-not $Env:USERNAME.Contains("$")) 
            {
                throw [Exception] ("Unable to use both InstallAccount and " + `
                                   "PsDscRunAsCredential in a single resource. Remove one " + `
                                   "and try again.")
                return
            }
        }

**Comment by NikCharlebois** [comment]
Review status: 0 of 2 files reviewed at latest revision, 8 unresolved discussions.

---

*[Modules/SharePointDsc/Modules/SharePointDSC.Reverse/SharePointDSC.Reverse.psm1, line 2 at r4](https://reviewable.io:443/reviews/powershell/sharepointdsc/396#-KTSWnJ0uh0iriE4NHz5:-KTTyJLTgW6me8C0dn-c:bjh6sn4) ([raw file](https://github.com/powershell/sharepointdsc/blob/59ac5449ebbf50087205ea3d46e2fdbddbf0fcfa/Modules/SharePointDsc/Modules/SharePointDSC.Reverse/SharePointDSC.Reverse.psm1#L2)):*
<details><summary><i>Previously, BrianFarnhill (Brian Farnhill) wrote…</i></summary>
> Straight off the bat, this file is too huge to be easily manageable. We need to look at how we split this up in to more manageable pieces. I'll give it some thought as I go through the rest of the review but wanted to get that out as a starting point.
</details>
I agree, I would also would eventually like to try to generalize it even further. Most functions are performing the exact same string operations, only the parameter change.

---

*[Modules/SharePointDsc/Modules/SharePointDSC.Reverse/SharePointDSC.Reverse.psm1, line 19 at r4](https://reviewable.io:443/reviews/powershell/sharepointdsc/396#-KTSYDiOqSBuc_b_0t0B:-KTTyELv7JmIECggH1-j:b-dsxzdf) ([raw file](https://github.com/powershell/sharepointdsc/blob/59ac5449ebbf50087205ea3d46e2fdbddbf0fcfa/Modules/SharePointDsc/Modules/SharePointDSC.Reverse/SharePointDSC.Reverse.psm1#L19)):*
> every time I run the script as the Farm admin, Util throws me the following error. 
> 
> I figured this is due to how the method handled the credentials. The error is being thrown n the code below. As an example, if you run the script as farm account, than both $Credential and $EnvUsername will be equal (e.g. "sp_farm" for both).
> 
> if ($Credential.UserName.Split("\")[1] -eq $Env:USERNAME) 
<details><summary><i alt="summary">Quoted 7 lines of code…</i></summary>
>         { 
>             if (-not $Env:USERNAME.Contains("$")) 
>             {
>                 throw Exception
>                 return
>             }
>         }</details>


---

*[Modules/SharePointDsc/Modules/SharePointDSC.Reverse/SharePointDSC.Reverse.psm1, line 38 at r4](https://reviewable.io:443/reviews/powershell/sharepointdsc/396#-KTSYbbIE_LQPZ3BQq_S:-KTTy_gf-V_eCnwv0w9e:bv2vv8j) ([raw file](https://github.com/powershell/sharepointdsc/blob/59ac5449ebbf50087205ea3d46e2fdbddbf0fcfa/Modules/SharePointDsc/Modules/SharePointDSC.Reverse/SharePointDSC.Reverse.psm1#L38)):*
<details><summary><i>Previously, BrianFarnhill (Brian Farnhill) wrote…</i></summary>
> This seems a little fragile - when we look at how to break up this file and process we should give some thought to how to manage the progress bar, it definitely need to be here I just think we need to calculate and manage it better.
</details>
Sure thing. My only worry is that by making the Progress Bar more "rock solid" we risk slowing down the script's execution because we will need to first do a scan to determine just how many objects there are to loop through.

---

*[Modules/SharePointDsc/Modules/SharePointDSC.Reverse/SharePointDSC.Reverse.psm1, line 153 at r4](https://reviewable.io:443/reviews/powershell/sharepointdsc/396#-KTSasspSM1-9246KAa0:-KTTywF1d5L29Pt04Qw7:bl3ixhs) ([raw file](https://github.com/powershell/sharepointdsc/blob/59ac5449ebbf50087205ea3d46e2fdbddbf0fcfa/Modules/SharePointDsc/Modules/SharePointDSC.Reverse/SharePointDSC.Reverse.psm1#L153)):*
<details><summary><i>Previously, BrianFarnhill (Brian Farnhill) wrote…</i></summary>
> Why are we capturing this if we don't need it for the actual configuration? 
</details>
This auto correct in Reviewable is killing me! My initial idea was to write this script to ease our daily PFE job. If I am to go to a client next week and know nothing about their environments, I could simply ask them to run the script prior to me coming on site, and then get an exact picture of what their environment looks like, including all OS and SQL versions. We can take it off no problem, but I still think this is valuable information to capture.

---

*[Modules/SharePointDsc/Modules/SharePointDSC.Reverse/SharePointDSC.Reverse.psm1, line 162 at r4](https://reviewable.io:443/reviews/powershell/sharepointdsc/396#-KTS_8-FgPvesIvbB0P5:-KTTzamtlOMOSSerZQsG:bb6un1j) ([raw file](https://github.com/powershell/sharepointdsc/blob/59ac5449ebbf50087205ea3d46e2fdbddbf0fcfa/Modules/SharePointDsc/Modules/SharePointDSC.Reverse/SharePointDSC.Reverse.psm1#L162)):*
<details><summary><i>Previously, BrianFarnhill (Brian Farnhill) wrote…</i></summary>
> We should be using CIM objects instead of WMI. Look to swap this to Get-CimObject instead
</details>
Done

---

*[Modules/SharePointDsc/Modules/SharePointDSC.Reverse/SharePointDSC.Reverse.psm1, line 168 at r4](https://reviewable.io:443/reviews/powershell/sharepointdsc/396#-KTSbTRBVTY543op_yi6:-KTTzf6kyLeYH56KIHMJ:b-ya81ng) ([raw file](https://github.com/powershell/sharepointdsc/blob/59ac5449ebbf50087205ea3d46e2fdbddbf0fcfa/Modules/SharePointDsc/Modules/SharePointDSC.Reverse/SharePointDSC.Reverse.psm1#L168)):*
<details><summary><i>Previously, BrianFarnhill (Brian Farnhill) wrote…</i></summary>
> Again whats the logic in capturing this?
</details>
Same as above

---

*[Modules/SharePointDsc/Modules/SharePointDSC.Reverse/SharePointDSC.Reverse.psm1, line 222 at r4](https://reviewable.io:443/reviews/powershell/sharepointdsc/396#-KTSbsaWIQUCV8rlnngn:-KTTzodqBAx1iYQTruN4:b-s1wjt7) ([raw file](https://github.com/powershell/sharepointdsc/blob/59ac5449ebbf50087205ea3d46e2fdbddbf0fcfa/Modules/SharePointDsc/Modules/SharePointDSC.Reverse/SharePointDSC.Reverse.psm1#L222)):*
<details><summary><i>Previously, BrianFarnhill (Brian Farnhill) wrote…</i></summary>
> We can't put this in as a default, it breaks the methodology of DSC where we assume secure defaults and allow you to turn them off afterwards, so this either needs to come out or it needs an option to set it that isn't the default.
</details>
Our end goal is to allow and complete automation, from A to Z without using CredSSP. Therefore I will simply take it out.

---

*[Modules/SharePointDsc/Modules/SharePointDSC.Reverse/SharePointDSC.Reverse.psm1, line 233 at r4](https://reviewable.io:443/reviews/powershell/sharepointdsc/396#-KTScJx7M2EzSaxg2NQy:-KTU-0f76xIR2Mf4bj1o:b-nihvma) ([raw file](https://github.com/powershell/sharepointdsc/blob/59ac5449ebbf50087205ea3d46e2fdbddbf0fcfa/Modules/SharePointDsc/Modules/SharePointDSC.Reverse/SharePointDSC.Reverse.psm1#L233)):*
<details><summary><i>Previously, BrianFarnhill (Brian Farnhill) wrote…</i></summary>
> We should add version numbers to these so its clear what versions are expected to work with what we generate
</details>
Great Thinking. Somehow I couldn't figure out the version number for PSDesiredStateConfiguration. Don't think it is 4.0.0.0 since this is the experimental version up on the PowerShell Gallery. The other resources are done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/396)*

**Comment by NikCharlebois** [comment]
Review status: 0 of 2 files reviewed at latest revision, 8 unresolved discussions.

---

*[Modules/SharePointDsc/Modules/SharePointDSC.Reverse/SharePointDSC.Reverse.psm1, line 2 at r4](https://reviewable.io:443/reviews/powershell/sharepointdsc/396#-KTSWnJ0uh0iriE4NHz5:-KURp8oK73BvNjpKEZUA:b-896fix) ([raw file](https://github.com/powershell/sharepointdsc/blob/59ac5449ebbf50087205ea3d46e2fdbddbf0fcfa/Modules/SharePointDsc/Modules/SharePointDSC.Reverse/SharePointDSC.Reverse.psm1#L2)):*
<details><summary><i>Previously, NikCharlebois (Nik Charlebois) wrote…</i></summary>
> I agree, I would also would eventually like to try to generalize it even further. Most functions are performing the exact same string operations, only the parameter change.
</details>
Done.

---

*[Modules/SharePointDsc/Modules/SharePointDSC.Reverse/SharePointDSC.Reverse.psm1, line 19 at r4](https://reviewable.io:443/reviews/powershell/sharepointdsc/396#-KTSYDiOqSBuc_b_0t0B:-KURpBXYe1AiAFYeNQqS:b-896fix) ([raw file](https://github.com/powershell/sharepointdsc/blob/59ac5449ebbf50087205ea3d46e2fdbddbf0fcfa/Modules/SharePointDsc/Modules/SharePointDSC.Reverse/SharePointDSC.Reverse.psm1#L19)):*
<details><summary><i>Previously, NikCharlebois (Nik Charlebois) wrote…</i></summary>
> > every time I run the script as the Farm admin, Util throws me the following error. 
> > 
> > I figured this is due to how the method handled the credentials. The error is being thrown n the code below. As an example, if you run the script as farm account, than both $Credential and $EnvUsername will be equal (e.g. "sp_farm" for both).
> > 
> > if ($Credential.UserName.Split("\")[1] -eq $Env:USERNAME) 
> >         { 
> >             if (-not $Env:USERNAME.Contains("$")) 
> >             {
> >                 throw Exception
> >                 return
> >             }
> >         }
> 
</details>
Done.

---

*[Modules/SharePointDsc/Modules/SharePointDSC.Reverse/SharePointDSC.Reverse.psm1, line 38 at r4](https://reviewable.io:443/reviews/powershell/sharepointdsc/396#-KTSYbbIE_LQPZ3BQq_S:-KURpCAQ4R3fxQHnJzEA:b-896fix) ([raw file](https://github.com/powershell/sharepointdsc/blob/59ac5449ebbf50087205ea3d46e2fdbddbf0fcfa/Modules/SharePointDsc/Modules/SharePointDSC.Reverse/SharePointDSC.Reverse.psm1#L38)):*
<details><summary><i>Previously, NikCharlebois (Nik Charlebois) wrote…</i></summary>
> Sure thing. My only worry is that by making the Progress Bar more "rock solid" we risk slowing down the script's execution because we will need to first do a scan to determine just how many objects there are to loop through.
</details>
Done.

---

*[Modules/SharePointDsc/Modules/SharePointDSC.Reverse/SharePointDSC.Reverse.psm1, line 153 at r4](https://reviewable.io:443/reviews/powershell/sharepointdsc/396#-KTSasspSM1-9246KAa0:-KURpCUYzx9GkVr8yyrW:b-896fix) ([raw file](https://github.com/powershell/sharepointdsc/blob/59ac5449ebbf50087205ea3d46e2fdbddbf0fcfa/Modules/SharePointDsc/Modules/SharePointDSC.Reverse/SharePointDSC.Reverse.psm1#L153)):*
<details><summary><i>Previously, NikCharlebois (Nik Charlebois) wrote…</i></summary>
> This auto correct in Reviewable is killing me! My initial idea was to write this script to ease our daily PFE job. If I am to go to a client next week and know nothing about their environments, I could simply ask them to run the script prior to me coming on site, and then get an exact picture of what their environment looks like, including all OS and SQL versions. We can take it off no problem, but I still think this is valuable information to capture.
</details>
Done.

---

*[Modules/SharePointDsc/Modules/SharePointDSC.Reverse/SharePointDSC.Reverse.psm1, line 162 at r4](https://reviewable.io:443/reviews/powershell/sharepointdsc/396#-KTS_8-FgPvesIvbB0P5:-KURpD1EKHYyo9-ApB6A:b-896fix) ([raw file](https://github.com/powershell/sharepointdsc/blob/59ac5449ebbf50087205ea3d46e2fdbddbf0fcfa/Modules/SharePointDsc/Modules/SharePointDSC.Reverse/SharePointDSC.Reverse.psm1#L162)):*
<details><summary><i>Previously, NikCharlebois (Nik Charlebois) wrote…</i></summary>
> Done
</details>
Done.

---

*[Modules/SharePointDsc/Modules/SharePointDSC.Reverse/SharePointDSC.Reverse.psm1, line 168 at r4](https://reviewable.io:443/reviews/powershell/sharepointdsc/396#-KTSbTRBVTY543op_yi6:-KURpIeZf9sXdTHUP942:b-896fix) ([raw file](https://github.com/powershell/sharepointdsc/blob/59ac5449ebbf50087205ea3d46e2fdbddbf0fcfa/Modules/SharePointDsc/Modules/SharePointDSC.Reverse/SharePointDSC.Reverse.psm1#L168)):*
<details><summary><i>Previously, NikCharlebois (Nik Charlebois) wrote…</i></summary>
> Same as above
</details>
Done.

---

*[Modules/SharePointDsc/Modules/SharePointDSC.Reverse/SharePointDSC.Reverse.psm1, line 222 at r4](https://reviewable.io:443/reviews/powershell/sharepointdsc/396#-KTSbsaWIQUCV8rlnngn:-KURpDPrx-YMMmgllUO9:b-896fix) ([raw file](https://github.com/powershell/sharepointdsc/blob/59ac5449ebbf50087205ea3d46e2fdbddbf0fcfa/Modules/SharePointDsc/Modules/SharePointDSC.Reverse/SharePointDSC.Reverse.psm1#L222)):*
<details><summary><i>Previously, NikCharlebois (Nik Charlebois) wrote…</i></summary>
> Our end goal is to allow and complete automation, from A to Z without using CredSSP. Therefore I will simply take it out.
</details>
Done.

---

*[Modules/SharePointDsc/Modules/SharePointDSC.Reverse/SharePointDSC.Reverse.psm1, line 233 at r4](https://reviewable.io:443/reviews/powershell/sharepointdsc/396#-KTScJx7M2EzSaxg2NQy:-KURpE9Fm6aqO6C3B13v:b-896fix) ([raw file](https://github.com/powershell/sharepointdsc/blob/59ac5449ebbf50087205ea3d46e2fdbddbf0fcfa/Modules/SharePointDsc/Modules/SharePointDSC.Reverse/SharePointDSC.Reverse.psm1#L233)):*
<details><summary><i>Previously, NikCharlebois (Nik Charlebois) wrote…</i></summary>
> Great Thinking. Somehow I couldn't figure out the version number for PSDesiredStateConfiguration. Don't think it is 4.0.0.0 since this is the experimental version up on the PowerShell Gallery. The other resources are done.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/396)*

**Comment by BrianFarnhill** [comment]
Review status: 0 of 2 files reviewed at latest revision, 8 unresolved discussions.

---

*[Modules/SharePointDsc/Modules/SharePointDSC.Reverse/SharePointDSC.Reverse.psm1, line 2 at r4](https://reviewable.io:443/reviews/powershell/sharepointdsc/396#-KTSWnJ0uh0iriE4NHz5:-KUTvZZK_MxAfgPAqYpz:b-x8uacb) ([raw file](https://github.com/powershell/sharepointdsc/blob/59ac5449ebbf50087205ea3d46e2fdbddbf0fcfa/Modules/SharePointDsc/Modules/SharePointDSC.Reverse/SharePointDSC.Reverse.psm1#L2)):*
<details><summary><i>Previously, NikCharlebois (Nik Charlebois) wrote…</i></summary>
> Done.
</details>
We need to do this sooner rather than later - trying to review this all in one go, jumping from one spot to the other is almost impossible and taking forever. Do you think you can look at doing something with this to split it up before we bring it in?

---

*[Modules/SharePointDsc/Modules/SharePointDSC.Reverse/SharePointDSC.Reverse.psm1, line 19 at r4](https://reviewable.io:443/reviews/powershell/sharepointdsc/396#-KTSYDiOqSBuc_b_0t0B:-KUTilIAsigJrbulbh4E:b-ppin6n) ([raw file](https://github.com/powershell/sharepointdsc/blob/59ac5449ebbf50087205ea3d46e2fdbddbf0fcfa/Modules/SharePointDsc/Modules/SharePointDSC.Reverse/SharePointDSC.Reverse.psm1#L19)):*
<details><summary><i>Previously, NikCharlebois (Nik Charlebois) wrote…</i></summary>
> Done.
</details>
 I would actually like to test this as it's not something that should be a limiting factor here. Will leave this discussion open for now until we look at it

---

*[Modules/SharePointDsc/Modules/SharePointDSC.Reverse/SharePointDSC.Reverse.psm1, line 38 at r4](https://reviewable.io:443/reviews/powershell/sharepointdsc/396#-KTSYbbIE_LQPZ3BQq_S:-KUTqymtGYNQmFwWy-8t:b-7dptpy) ([raw file](https://github.com/powershell/sharepointdsc/blob/59ac5449ebbf50087205ea3d46e2fdbddbf0fcfa/Modules/SharePointDsc/Modules/SharePointDSC.Reverse/SharePointDSC.Reverse.psm1#L38)):*
<details><summary><i>Previously, NikCharlebois (Nik Charlebois) wrote…</i></summary>
> Done.
</details>
This doesn't look done dude, it's something we need to look at here. 

---

*[Modules/SharePointDsc/Modules/SharePointDSC.Reverse/SharePointDSC.Reverse.psm1, line 153 at r4](https://reviewable.io:443/reviews/powershell/sharepointdsc/396#-KTSasspSM1-9246KAa0:-KUTr7fEAmLDT0kJvqRx:bdpj980) ([raw file](https://github.com/powershell/sharepointdsc/blob/59ac5449ebbf50087205ea3d46e2fdbddbf0fcfa/Modules/SharePointDsc/Modules/SharePointDSC.Reverse/SharePointDSC.Reverse.psm1#L153)):*
<details><summary><i>Previously, NikCharlebois (Nik Charlebois) wrote…</i></summary>
> Done.
</details>
Leave this with me to have a think about, will advise before we merge. 

---

*[Modules/SharePointDsc/Modules/SharePointDSC.Reverse/SharePointDSC.Reverse.psm1, line 168 at r4](https://reviewable.io:443/reviews/powershell/sharepointdsc/396#-KTSbTRBVTY543op_yi6:-KUTrHSpvS0xtfndSM2g:buunvb4) ([raw file](https://github.com/powershell/sharepointdsc/blob/59ac5449ebbf50087205ea3d46e2fdbddbf0fcfa/Modules/SharePointDsc/Modules/SharePointDSC.Reverse/SharePointDSC.Reverse.psm1#L168)):*
<details><summary><i>Previously, NikCharlebois (Nik Charlebois) wrote…</i></summary>
> Done.
</details>
Again, leaving this open to ponder it before we close it off

---

*[Modules/SharePointDsc/Modules/SharePointDSC.Reverse/SharePointDSC.Reverse.psm1, line 301 at r5](https://reviewable.io:443/reviews/powershell/sharepointdsc/396#-KUTt81ArlvC8Ka6IcDd:-KUTt81ArlvC8Ka6IcDe:b-xxbpbm) ([raw file](https://github.com/powershell/sharepointdsc/blob/b3c4c7c1fab906e199cfcb013eb258a80217f4a9/Modules/SharePointDsc/Modules/SharePointDSC.Reverse/SharePointDSC.Reverse.psm1#L301)):*
> ```PowerShell
> 
> <## This function really is optional, but helps provide valuable information about the various software components installed in the current SharePoint farm (i.e. Cummulative Updates, Language Packs, etc.). #>
> function Read-SPProductVersions
> ```

Again leaving a remark here to consider if we need to include this information

---

*[Modules/SharePointDsc/Modules/SharePointDSC.Reverse/SharePointDSC.Reverse.psm1, line 307 at r5](https://reviewable.io:443/reviews/powershell/sharepointdsc/396#-KUTtJPtP5F7OGsRtCEQ:-KUTtJPuBXGkYE4P4wuY:b9721v8) ([raw file](https://github.com/powershell/sharepointdsc/blob/b3c4c7c1fab906e199cfcb013eb258a80217f4a9/Modules/SharePointDsc/Modules/SharePointDSC.Reverse/SharePointDSC.Reverse.psm1#L307)):*
> ```PowerShell
>     $Script:dscConfigContent += "-------------------------------------------`r`n"
> 
>     if($PSVersionTable.PSVersion -like "2.*")
> ```

We can take this out - you need PowerShell 4 to do DSC and SharePoint 2013 installs PowerShell 3 as a prereq I don't think we need this here.

---

*[Modules/SharePointDsc/Modules/SharePointDSC.Reverse/SharePointDSC.Reverse.psm1, line 386 at r5](https://reviewable.io:443/reviews/powershell/sharepointdsc/396#-KUTudiS-b5ylbxgxERv:-KUTudiS-b5ylbxgxERw:b-6th6om) ([raw file](https://github.com/powershell/sharepointdsc/blob/b3c4c7c1fab906e199cfcb013eb258a80217f4a9/Modules/SharePointDsc/Modules/SharePointDSC.Reverse/SharePointDSC.Reverse.psm1#L386)):*
> ```PowerShell
>     $dscBlock = ""
>     $foundInstallAccount = $false
>     $Params.Keys | % { 
> ```

I'm picking on this one line, but this applies to the whole file - you need to review to make sure you are following all of the style guidelines, so in this case no aliases (% is an alias of ForEach-Object)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/396)*

**Comment by NikCharlebois** [comment]
@BrianFarnhill I've isolated the helper methods. It will be tough to make it any more modular unfortunately. There are some specificities for each resources. For example, if SharePoint is not 2016, I need to remove the ServerRole param in order for it to work. Otherwise we could simply dynamically loop through each resources containsed in the DSCResources folder and call into their Get-TargetResources, but we are not there yet.

**Pull request closed without merging**
