### PR TITLE
SPFarm: Add support for vanity hosts on HTTP to CA #1102

### LINKED ISSUE #1102: SPFarm: CentralAdministrationUrl should support setting vanity host on HTTP
#### Details of the scenario you tried and the problem that is occurring

As a continuation of #1065 , we should be able to use the CentralAdministrationUrl param to set a vanity host with HTTP and not just HTTPS.

#### Suggested solution to the issue

Scenario 1:
CentralAdministrationUrl = "http://machine-name"
CentralAdministrationPort = "9999"
Expected result: CentralAdministrationUrl is ignored since this is the default behavior from running New-SPCentralAdministration.

Scenario 2:
CentralAdministrationUrl = "http://custom-name.domain.com"
CentralAdministrationPort = "9999"
Expected result: CA is provisioned on port 9999 and then bindings and AAMs updated to match the vanity url.

### PR DESCRIPTION
**Pull request by ronx**
#### Pull Request (PR) description
Add support for vanity hosts on HTTP to CA (issue #1102). Still testing this but wanted to go ahead and get the PR in to keep it on my radar (and get initial code review results).

#### This Pull Request (PR) fixes the following issues
- Fixes #1102 

#### Task list
- [x] Added an entry under the Unreleased section of the change log in the CHANGELOG.md.
      Entry should say what was changed, and how that affects users (if applicable).
- [x] Resource documentation added/updated in README.md in the resource folder.
- [x] Resource parameter descriptions added/updated in schema.mof
      and comment-based help.
- [ ] Comment-based help added/updated.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [ ] Examples appropriately added/updated.
- [x] Unit tests added/updated. See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] Integration tests added/updated (where possible). See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [x] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/sharepointdsc/1114)

### CODE REVIEW

**Comment by ronx** [comment]
@ykuijs Are there appveyor changes coming that will fix the build?

**Comment by ykuijs** [comment]
Tests are failing on the SPFarm resource, the same test for all three SP versions:

```
[00:26:55]     Context Invalid CA URL has been passed in (HTTP currently not supported)
[00:26:56]       [-] Should throw exception in the set method 376ms
[00:26:56]         Expected an exception, with message 'CentralAdministrationUrl parameter can only be used with HTTPS' to be thrown, but the message was 'Specified registry key hklm:SOFTWARE\Microsoft\Shared Tools\Web Server Extensions\15.0\Secure\ConfigDB could not be found.'. from C:\projects\sharepointdsc\modules\SharePointDsc\modules\SharePointDsc.Util\SharePointDsc.Util.psm1:314 char:9
[00:26:56]             +         throw "Specified registry key $Key could not be found."
[00:26:56]             +         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[00:26:56]         162:                 { Set-TargetResource @testParams } | Should Throw "CentralAdministrationUrl parameter can only be used with HTTPS"
[00:26:56]         at <ScriptBlock>, C:\projects\sharepointdsc\Tests\Unit\SharePointDsc\SharePointDsc.SPFarm.Tests.ps1: line 162
```

**Comment by ronx** [comment]
ah, that makes sense. I was looking at the appveyor console output and thought the yellow warnings were causing the failure. My mistake. ;)

**Comment by ykuijs** [comment]
Click the Tests menu to see which tests are failing:
image

**Comment by ronx** [comment]
yep, got it now... Also running the pester coverage tests locally. I'll have it sorted shortly.

**Comment by ykuijs** [comment]
Does this also fix issue 1115 or will you submit a new PR for that?

I am fine with combining both into one PR.

**Comment by ronx** [comment]
I'll probably do a separate PR for 1115 so I can go ahead and get this one merged when it's finished and not sure when I'll get to 1115.

BTW - the functionality for this one isn't implemented yet. I just added some pseudo code and updated test cases. Just want to let you know so you don't merge this one when the checks pass ;). I'll update when the code is in and ready.

**Comment by ronx** [comment]
BTW - I pinged you on Teams, but might be good to track this here as well... what was the issue with ReverseDsc that you mentioned in Rollup #1100 ? Since this PR will add support for HTTP and also adds a check for null/empty CentralAdministrationUrl param, I'm wondering if we can move the exceptions back to the Get method. I have moved it back for now (for code coverage and simplicity) and can test it with ReverseDsc if you let me know how I can test it.

**Comment by ronx** [comment]
I was talking to Nik about this yesterday, and he explained that ReverseDsc is calling the Get function with fake values, so it's probably using 0 for an int param, empty string for string, etc. I think the code I had added to handle null/empty values for CentralAdministrationUrl probably fixed the issue with ReverseDsc, but he pointed out an open issue in the ReverseDsc project that had to do with CentralAdministrationPort, which I noticed was still in the Get function after your rollup.

Handling issues with desired state in the Get-TargetResource is convenient, but probably not the best idea now that I think about it. It's convenient because Set and Test usually call into Get to get the current state to compare with the desired state, so you don't have to duplicate code... however, Get should simply be concerned with getting the current state of the resource without worrying about your intentions for setting desired state.

Nik said that ReverseDsc could intelligently handle parameter validation, so I removed the CentralAdministrationPort exception throwing and added param validation for that one. I'm going to try to the same with the other params, and any advanced validation that can't be handled with parameter validation, I'll move back to the Set method. Stay tuned...

**Pull request merged**
