### PR TITLE
Add resource SPTrustedSecurityTokenIssuer

### PR DESCRIPTION
**Pull request by Yvand**
### Pull Request (PR) description

Add resource SPTrustedSecurityTokenIssuer

#### This Pull Request (PR) fixes the following issues

None

#### Task list

- [x] Added an entry under the Unreleased section of the change log in the CHANGELOG.md.
      Entry should say what was changed, and how that affects users (if applicable).
- [x] Resource documentation added/updated in README.md in the resource folder.
- [x] Resource parameter descriptions added/updated in schema.mof
      and comment-based help.
- [ ] Comment-based help added/updated.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [x] Examples appropriately added/updated.
- [x] Unit tests added/updated. See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] Integration tests added/updated (where possible). See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [x] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/sharepointdsc/1088)

### CODE REVIEW

**Comment by Yvand** [comment]
The current status is that I finished the code of the resource itself, and I'm working on the Pester tests.

**Comment by Yvand** [comment]
@ykuijs this PR is now ready for your review!

**Comment by ykuijs** [comment]
Please make sure you pull from dev and resolve the conflicts in the changelog. Without that AppVeyor is unable to run its tests.

**Comment by Yvand** [comment]
___
*[Modules/SharePointDsc/DSCResources/MSFT_SPTrustedSecurityTokenIssuer/MSFT_SPTrustedSecurityTokenIssuer.psm1, line 147 at r3](https://reviewable.io/reviews/powershell/sharepointdsc/1088#-LiswOD100GxofJb3IXT:-LiwHdWW4HsBbj-uu1CH:b-ikak1k) ([raw file](https://github.com/powershell/sharepointdsc/blob/2141209889325db1ef5f59ca2ebe3e5acc1a07c1/Modules/SharePointDsc/DSCResources/MSFT_SPTrustedSecurityTokenIssuer/MSFT_SPTrustedSecurityTokenIssuer.psm1#L147)):*
<details><summary><i>Previously, ykuijs (Yorick Kuijs) wrote…</i></summary><blockquote>

If this is a possible scenario, we should cater for that. Do you know if this is a possible scenario?
</blockquote></details>

It's probably possible but potentially not simple to handle, I will investigate and let you know

**Pull request merged**
