### PR TITLE
Fixed Issues 487 and 519

### PR DESCRIPTION
**Pull request by NikCharlebois**
Fixes for Issues 487 and 519

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/sharepointdsc/658)

### CODE REVIEW

**Comment by BrianFarnhill** [comment]
Reviewed 2 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPFarm/MSFT_SPFarm.psm1, line 178 at r2](https://reviewable.io:443/reviews/powershell/sharepointdsc/658#-KvZ8FVFmkQQ4pH_czU0:-KvZ8FVFmkQQ4pH_czU1:b-t73lab) ([raw file](https://github.com/powershell/sharepointdsc/blob/f50d297b309353cc1867de3eb1ccb3ea8b3a98ca/Modules/SharePointDsc/DSCResources/MSFT_SPFarm/MSFT_SPFarm.psm1#L178)):*
> ```PowerShell
>             }
>             $installedVersion = Get-SPDSCInstalledProductVersion
>             if($installedVersion.FileMajorPart -eq 16)
> ```

We need a unit test that validates that if the version is 2016 that it is returned, and if it is 2013 that it is $null

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPFarm/MSFT_SPFarm.psm1, line 183 at r2](https://reviewable.io:443/reviews/powershell/sharepointdsc/658#-KvZ8L8ZSUgZjlk6uhvL:-KvZ8L8ZSUgZjlk6uhvM:by4vgkm) ([raw file](https://github.com/powershell/sharepointdsc/blob/f50d297b309353cc1867de3eb1ccb3ea8b3a98ca/Modules/SharePointDsc/DSCResources/MSFT_SPFarm/MSFT_SPFarm.psm1#L183)):*
> ```PowerShell
>                 if($null -ne $server -and $null -ne $server.Role)
>                 {
>                     $returnValue.Add("ServerRole", $server.Role)
> ```

We only add the value if its 2016, we should add ServerRole anyway and set it to $null if its a 2013 farm

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPSearchTopology/MSFT_SPSearchTopology.psm1, line 143 at r2](https://reviewable.io:443/reviews/powershell/sharepointdsc/658#-KvZ8BWKYPmZeRCUV-Wm:-KvZ8BWKYPmZeRCUV-Wn:b-thyp2p) ([raw file](https://github.com/powershell/sharepointdsc/blob/f50d297b309353cc1867de3eb1ccb3ea8b3a98ca/Modules/SharePointDsc/DSCResources/MSFT_SPSearchTopology/MSFT_SPSearchTopology.psm1#L143)):*
> ```PowerShell
>         
>         $firstPartition = $null
>         if($IndexComponents.Length -gt 0)
> ```

We need a unit test to validate the logic through here

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/658)*

**Comment by ykuijs** [comment]
@NikCharlebois The RootDirectory property isn't the only location where the index location can be found:
http://itgroove.net/mmman/2015/04/30/how-to-determine-your-sharepoint-2013-search-index-location-and-default-search-index-location/

So it the RootDirectory property is empty, you should use the IndexLocation property of the SearchServiceInstance.

**Comment by ykuijs** [comment]
Referencing the corresponding issues: #487 and #519

**Comment by ykuijs** [comment]
Reporting, since I accidentally deleted this reaction.....

@NikCharlebois The RootDirectory property isn't the only location where the index location can be found:
http://itgroove.net/mmman/2015/04/30/how-to-determine-your-sharepoint-2013-search-index-location-and-default-search-index-location/

So it the RootDirectory property is empty, you should use the IndexLocation property of the SearchServiceInstance

**Comment by NikCharlebois** [comment]
Review status: 0 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPFarm/MSFT_SPFarm.psm1, line 178 at r2](https://reviewable.io:443/reviews/powershell/sharepointdsc/658#-KvZ8FVFmkQQ4pH_czU0:-KvgSys6F4JqNYXJdJ4k:b-ky0qgr) ([raw file](https://github.com/powershell/sharepointdsc/blob/f50d297b309353cc1867de3eb1ccb3ea8b3a98ca/Modules/SharePointDsc/DSCResources/MSFT_SPFarm/MSFT_SPFarm.psm1#L178)):*
<details><summary><i>Previously, BrianFarnhill (Brian Farnhill) wrote…</i></summary><blockquote>

We need a unit test that validates that if the version is 2016 that it is returned, and if it is 2013 that it is $null
</blockquote></details>

Done, tests have been updated

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPFarm/MSFT_SPFarm.psm1, line 183 at r2](https://reviewable.io:443/reviews/powershell/sharepointdsc/658#-KvZ8L8ZSUgZjlk6uhvL:-KvgT6KdhudryzScNfiV:b-q3x1iu) ([raw file](https://github.com/powershell/sharepointdsc/blob/f50d297b309353cc1867de3eb1ccb3ea8b3a98ca/Modules/SharePointDsc/DSCResources/MSFT_SPFarm/MSFT_SPFarm.psm1#L183)):*
<details><summary><i>Previously, BrianFarnhill (Brian Farnhill) wrote…</i></summary><blockquote>

We only add the value if its 2016, we should add ServerRole anyway and set it to $null if its a 2013 farm
</blockquote></details>

Done, it now return that value as null for MajorVersion = 15

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPSearchTopology/MSFT_SPSearchTopology.psm1, line 143 at r2](https://reviewable.io:443/reviews/powershell/sharepointdsc/658#-KvZ8BWKYPmZeRCUV-Wm:-KvgT9sRZbWj5pOApWu8:bb6un1j) ([raw file](https://github.com/powershell/sharepointdsc/blob/f50d297b309353cc1867de3eb1ccb3ea8b3a98ca/Modules/SharePointDsc/DSCResources/MSFT_SPSearchTopology/MSFT_SPSearchTopology.psm1#L143)):*
<details><summary><i>Previously, BrianFarnhill (Brian Farnhill) wrote…</i></summary><blockquote>

We need a unit test to validate the logic through here
</blockquote></details>

Done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/658)*

**Comment by NikCharlebois** [comment]
Review status: 0 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPFarm/MSFT_SPFarm.psm1, line 178 at r2](https://reviewable.io:443/reviews/powershell/sharepointdsc/658#-KvZ8FVFmkQQ4pH_czU0:-KvgTV6qnwa6LeisnTlu:b-896fix) ([raw file](https://github.com/powershell/sharepointdsc/blob/f50d297b309353cc1867de3eb1ccb3ea8b3a98ca/Modules/SharePointDsc/DSCResources/MSFT_SPFarm/MSFT_SPFarm.psm1#L178)):*
<details><summary><i>Previously, NikCharlebois (Nik Charlebois) wrote…</i></summary><blockquote>

Done, tests have been updated
</blockquote></details>

Done.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPFarm/MSFT_SPFarm.psm1, line 183 at r2](https://reviewable.io:443/reviews/powershell/sharepointdsc/658#-KvZ8L8ZSUgZjlk6uhvL:-KvgTVdM_eCV2KyH8IBG:b-896fix) ([raw file](https://github.com/powershell/sharepointdsc/blob/f50d297b309353cc1867de3eb1ccb3ea8b3a98ca/Modules/SharePointDsc/DSCResources/MSFT_SPFarm/MSFT_SPFarm.psm1#L183)):*
<details><summary><i>Previously, NikCharlebois (Nik Charlebois) wrote…</i></summary><blockquote>

Done, it now return that value as null for MajorVersion = 15
</blockquote></details>

Done.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPSearchTopology/MSFT_SPSearchTopology.psm1, line 143 at r2](https://reviewable.io:443/reviews/powershell/sharepointdsc/658#-KvZ8BWKYPmZeRCUV-Wm:-KvgTW018t9S_yrJXBBx:b-896fix) ([raw file](https://github.com/powershell/sharepointdsc/blob/f50d297b309353cc1867de3eb1ccb3ea8b3a98ca/Modules/SharePointDsc/DSCResources/MSFT_SPSearchTopology/MSFT_SPSearchTopology.psm1#L143)):*
<details><summary><i>Previously, NikCharlebois (Nik Charlebois) wrote…</i></summary><blockquote>

Done
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/658)*

**Comment by NikCharlebois** [comment]
Reviewed 2 of 2 files at r1, 1 of 1 files at r2, 1 of 4 files at r3.
Review status: 1 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPFarm/MSFT_SPFarm.psm1, line 178 at r2](https://reviewable.io:443/reviews/powershell/sharepointdsc/658#-KvZ8FVFmkQQ4pH_czU0:-KvgTeqbqRoZxGfaXdjP:b-896fix) ([raw file](https://github.com/powershell/sharepointdsc/blob/f50d297b309353cc1867de3eb1ccb3ea8b3a98ca/Modules/SharePointDsc/DSCResources/MSFT_SPFarm/MSFT_SPFarm.psm1#L178)):*
<details><summary><i>Previously, NikCharlebois (Nik Charlebois) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/658)*

**Comment by NikCharlebois** [comment]
Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: 1 of 4 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/658)*

**Comment by NikCharlebois** [comment]
Reviewed 3 of 4 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/658)*

**Comment by BrianFarnhill** [comment]
:lgtm:

---

Reviewed 2 of 4 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/658#-:-KviEHXrvAfQx50yTekW:bnfp4nl)*

**Pull request merged**
