### PR TITLE
Update to add TLS Encryption Setting as a parameter

### PR DESCRIPTION
**Pull request by nissan**
Add TLS Encryption Setting as a parameter which can be set on ($true) or off ($false) explicitly

- [ ] Change details added to Unreleased section of changelog.md?
- [ ] Added/updated documentation and descriptions in .schema.mof files where appropriate?
- [ ] Examples updated for both the single server and small farm templates in the examples folder?
- [X] New/changed code adheres to [Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md)?
- [ ] [Unit and Integration tests](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md) created/updated where possible?

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/sharepointdsc/541)

### CODE REVIEW

**Comment by BrianFarnhill** [comment]
OK so you're missing quite a bit from this PR in terms of what we need for it to actually work - can I ask if you tested this anywhere first or just submitted the code?

Things that are missing:

* You need to make changes to the Schema.mof file for the new property to be usable at all
* There is no changes to the unit tests to validate the logic on the new property
* You can't make this property mandatory as SharePoint 2013 doesn't have it at all, which means it has to be optional, and in the code we have to do a version check so that if someone supplies this property on SharePoint 2013 we throw an error
* The changelog needs to be updated to add notes on this change
* There needs to be an additional example file added for this resource as well

I'm happy with the basic logic of how you have done the get/set/test of the logic - but we need the rest of the above items to be resolved before we can bring this in to the codebase.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/541#-:-KfnIR1yjmiEoOx9e5Cz:bgmajll)*

**Comment by ykuijs** [comment]
Would be great if you could also add the SMTP port setting. And please also include a check for version of SharePoint, since these settings are only present in SP2016.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/541#-:-Kg1bvxHMg2Lsz99-z4M:b-bedtpr)*

**Comment by ykuijs** [comment]
Linking to issue #540

**Comment by ykuijs** [comment]
@nissan, any update on this PR?

**Comment by BrianFarnhill** [comment]
I'm closing this one due to lack of response.

**Pull request closed without merging**
