### PR TITLE
Fix SPBlobCacheSettings issue where the service is not retrieved if the OS or SP language is not english

### LINKED ISSUE #923: Resources that use TypeName for Service Instance: Not working for non-english environments
#### Details of the scenario you tried and the problem that is occurring
The SPBlobCacheSettings resource tries to retrieve and configure the blob cache, only if the "Microsoft SharePoint Foundation Web Application" service is started on the server. However, we should use TypeName to determine if a service is started or not since it is culture dependent. E.g. my client has a French SharePoint environment and the service TypeName is "Application Web de Microsoft SharePoint Foundation" and therefore never detects or configures it.

This issue is widespread across multiple resource. We should modify every resource that uses the property TypeName to determine the status or retrieve an instance, so that it uses a parameter that is culture independent.

#### Verbose logs showing the problem
N/A

#### Suggested solution to the issue
Use .GetType().Name where possible (Web Foundation and Central Admin have the same name, so it won't work in that case), or the Name itself to determine the instance of the service (Central Admin has a name of Wss_Administration, and web foundation has an empty name).

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
N/A

#### The operating system the target node is running
Windows Server 2012 R2 (French)

#### Version of SharePoint that is used (e.g. SharePoint 2016)
SharePoint 2013

#### Version and build of PowerShell the target node is running
PoSh 4

#### Version of the DSC module that was used ('dev' if using current dev branch)
2.5.0.0

### PR DESCRIPTION
**Pull request by NikCharlebois**
#### Pull Request (PR) description
The resource is currently looking to see if the service is started by TypeName, which we now know is language dependent. Instead, I am now retrieving the service instance by internal name.

#### This Pull Request (PR) fixes the following issues
Partially fixes #923 

- [ ] Added an entry under the Unreleased section of the change log in the CHANGELOG.md.
      Entry should say what was changed, and how that affects users (if applicable).
- [ ] Resource documentation added/updated in README.md in the resource folder.
- [ ] Resource parameter descriptions added/updated in schema.mof
      and comment-based help.
- [ ] Comment-based help added/updated.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [ ] Examples appropriately added/updated.
- [ ] Unit tests added/updated. See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] Integration tests added/updated (where possible). See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/sharepointdsc/927)

### CODE REVIEW

**Comment by ykuijs** [comment]
There is still an error with test tests:
```
At C:\projects\sharepointdsc\Tests\Unit\SharePointDsc\SharePointDsc.SPBlobCacheSettings.Tests.ps1:355 char:1
+ }
+ ~
Unexpected token '}' in expression or statement.
```

**Comment by ykuijs** [comment]
Can you please merge from Dev. AppVeyor doesn't start because of a merge conflict

**Comment by ykuijs** [comment]
@NikCharlebois BlobCache tests are failing. Can you update these?

**Comment by ykuijs** [comment]
Tests are still failing. You can run these tests locally by running the following commands:
```
$githubPath = "C:\users\<userid>\Documents\GitHub\SharePointDsc"
cd (Join-Path -Path $githubPath -ChildPath "Tests\Unit\SharePointDSC")
$path16 = Join-Path -Path $githubPath -ChildPath "\Tests\Unit\Stubs\SharePoint\16.0.4456.1000\Microsoft.SharePoint.PowerShell.psm1"
.\SharePointDsc.SPBlobCacheSettings.Tests.ps1
.\SharePointDsc.SPBlobCacheSettings.Tests.ps1 -SharePointCmdletModule $path16
```

**Comment by NikCharlebois** [comment]
@ykuijs all yours to review

**Pull request merged**
