### PR TITLE
Sp install prereqs without cim instance

### PR DESCRIPTION
**Pull request by luigilink**
Thanks for submitting a Pull Request to this project.

Please make sure you have read the [Contribution Guidelines](https://github.com/powershell/xSharePoint/wiki/Contributing%20to%20xSharePoint).

To aid community reviewers in reviewing and merging your PR, please take the time to run through this checklist:
- [ ] Change details added to Unreleased section of readme.md?
- [x] Added/updated documentation and descriptions in .schema.mof files where appropriate?
- [x] Examples updated for both the single server and small farm templates in the examples folder?
- [x] New/changed code adheres to [Style Guidelines]?(https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md)?
- [ ] [Unit and Integration tests](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md) created/updated where possible?

Your contribution to this project is greatly appreciated.

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/sharepointdsc/341)

### CODE REVIEW

**Comment by ykuijs** [comment]
Please follow the coding guidlines as mentioned in https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md

For example the last guideline about using Cmdlet aliases

Also follow the following guidance: https://github.com/PowerShell/SharePointDsc/issues/311
$null should be placed on the left of the equality comparison.

Both issues were correct in the original code. You can use that as reference/example.

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPInstallPrereqs/MSFT_SPInstallPrereqs.psm1, line 66 \[r2\]](https://reviewable.io:443/reviews/powershell/sharepointdsc/341#-KKtqZkwXP4Hw-plbBjK:-KKtqZkwXP4Hw-plbBjL:-956035206) ([raw file](https://github.com/powershell/sharepointdsc/blob/98b532b302582c83c7598846a1267504315906eb/Modules/SharePointDsc/DSCResources/MSFT_SPInstallPrereqs/MSFT_SPInstallPrereqs.psm1#L66)):*
> ```PowerShell
>     
>     #Common prereqs
>     $returnValue.Add("AppFabric 1.1 for Windows Server", (($installedItems | ? {$_.DisplayName -eq "AppFabric 1.1 for Windows Server"}) -ne $null))
> ```

Please follow the coding guidlines as mentioned in https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md

For example the last guideline about using Cmdlet aliases

Also follow the following guidance: https://github.com/PowerShell/SharePointDsc/issues/311
$null should be placed on the left of the equality comparison.

Both issues were correct in the original code. You can use that as reference/example.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/341#-:-KKtrcF_MZLQtuOPyb6x:-956035206)*

**Comment by ykuijs** [comment]
Also: The Pester tests fail. Since the PR does not contain an updated test, I think you have to look at updating them as well to match the new registry checks you have implemented.

**Comment by BrianFarnhill** [comment]
@luigilink @ykuijs I'm super keen to get this in to 1.1 which I'm going to start prepping shortly. I've got some time this arvo so I might bash this in to a quick branch I've got in progress and open a PR with that in it to get this through review quicker. I'll let you know when it's ready.

**Comment by BrianFarnhill** [comment]
@ykuijs I've now got #343 open with the cleaned up version of this ready to go. 

@luigilink Sorry to take this one off you and rush it through, I'm just super keen to get this in to our next release. Will definitely work with you on the next PR you open through the code review process so you get the hang of that as well. 

Closing this one off now in favor of #343 - thanks guys

**Pull request closed without merging**
