### PR TITLE
Release 1.8

### PR DESCRIPTION
**Pull request by BrianFarnhill**
@kwirkykat Ready to drop a new release in your next wave :)

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/sharepointdsc/632)

### CODE REVIEW

**Comment by kwirkykat** [comment]
@BrianFarnhill Looks like tests are failing? Can't release without the tests passing.
Next release is July 12.

**Comment by ykuijs** [comment]
@BrianFarnhill The test that is failing is about the issue you raised in PowerShell/DscResource.Tests#144. Will you be able to fix this before July 12th?

**Comment by BrianFarnhill** [comment]
@kwirkykat Does it make a difference that the test that is failing is before of the issue that @ykuijs mentioned above in the common tests? And that its just on the examples stuff, not the main code? I ask because there is no way I'll get time to resolve the issue in those common tests before the next release window

**Comment by kwirkykat** [comment]
@BrianFarnhill Sorry, I can't release anything without a full test pass from AppVeyor on the release PR. I can release it outside of the normal release cadence whenever it gets fixed though.

**Comment by johlju** [comment]
@BrianFarnhill I started working on a fix for thugs when I saw that you didn't have much time to fix this. Let me know if I should complete the fix and send in a PR. But it looked like you were working on something too when I looked at the issue in DscResource.Tests. But I should just test it on two different repos and then I can PR in the change. 
Let me know if you want me to continue.

**Comment by BrianFarnhill** [comment]
@johlju I'll take a swing at it today and see how it goes, I should be able to carve out a couple of hours which I hope should be enough, but if I don't get it done today there is no way I will meet the release timeline there because I'm travelling next week, so I'll let you know later today how I go and if I need the help. I definitely appreciate it though, so thank you so much for even offering :)

**Comment by BrianFarnhill** [comment]
@kwirkykat I have a PR open now to fix the common tests at https://github.com/PowerShell/DscResource.Tests/pull/148 - once that is merged in we can trigger a build on this again and it will light up green. Again, thank you to @johlju for helping out!

**Comment by johlju** [comment]
We are here to help each other. I'm just glad I could help :)

**Pull request merged**
