### PR TITLE
Fix - Issue #696

### PR DESCRIPTION
**Pull request by NikCharlebois**
Fixes an issue with the User Profile Sync Service

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/sharepointdsc/698)

### CODE REVIEW

**Comment by ykuijs** [comment]
@NikCharlebois Test are failing. Can you please fix them?

**Comment by ykuijs** [comment]
One comment after a quick review:
For other resources we had to switch from the TypeName property to GetType().Name, because the TypeName was language specific and the GetType().Name wasn't. Please make sure you test this change on a non-English installation or keep using the GetType().Name method/property.

**Comment by ykuijs** [comment]
Linking to issue #696

**Comment by NikCharlebois** [comment]
@ykuijs ok, I wasn't aware of the culture issues with service apps typename. I flipped back to .GetType() and provided the proper service type name instead.

**Comment by ykuijs** [comment]
Just one typo. Can you also please update the Changelog.md file?

---

Reviewed 1 of 2 files at r3.
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPUserProfileSyncService/MSFT_SPUserProfileSyncService.psm1, line 275 at r3](https://reviewable.io:443/reviews/powershell/sharepointdsc/698#-L0RKGo63et5YK2pcgQY:-L0RKGo63et5YK2pcgQZ:b-xzwdxb) ([raw file](https://github.com/powershell/sharepointdsc/blob/488930f10167d63b61a407315ea05b99de2dee91/Modules/SharePointDsc/DSCResources/MSFT_SPUserProfileSyncService/MSFT_SPUserProfileSyncService.psm1#L275)):*
> ```PowerShell
>                 if ($null -eq $ups)
>                 {
>                     throw [Exception] ("No user profile service Service Application was found " + `
> ```

Has the word Service twice

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/698#-:-L0RKrsslh7AcnjV4_L7:bjlm6z1)*

**Comment by NikCharlebois** [comment]
Fixed

---

Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPUserProfileSyncService/MSFT_SPUserProfileSyncService.psm1, line 275 at r3](https://reviewable.io:443/reviews/powershell/sharepointdsc/698#-L0RKGo63et5YK2pcgQY:-L0RQXQ5pNpHV8tq3NDV:b-886gsx) ([raw file](https://github.com/powershell/sharepointdsc/blob/488930f10167d63b61a407315ea05b99de2dee91/Modules/SharePointDsc/DSCResources/MSFT_SPUserProfileSyncService/MSFT_SPUserProfileSyncService.psm1#L275)):*
<details><summary><i>Previously, ykuijs (Yorick Kuijs) wrote…</i></summary><blockquote>

Has the word Service twice
</blockquote></details>

Fixed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/698#-:-L0RQKdmHcDcbUuWOtzb:b-886gsx)*

**Comment by ykuijs** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/698#-:-L0ex8zha7N3Y-UgLoWG:bnfp4nl)*

**Pull request merged**
