### PR TITLE
Fixes for Connection Display Name

### PR DESCRIPTION
**Pull request by NikCharlebois**
Thanks for submitting a Pull Request to this project.
This template will help you create your pull request.

Please make sure you have read the [Contribution Guidelines](https://github.com/powershell/xSharePoint/wiki/Contributing%20to%20xSharePoint).

To aid community reviewers in reviewing and merging your PR, please take the time to run through this checklist:

**DELETE THIS LINE AND ABOVE**

[Replace this with a description of your pull request]

- [ ] Change details added to Unreleased section of changelog.md?
- [ ] Added/updated documentation and descriptions in .schema.mof files where appropriate?
- [ ] Examples updated for both the single server and small farm templates in the examples folder?
- [ ] New/changed code adheres to [Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md)?
- [ ] [Unit and Integration tests](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md) created/updated where possible?

**DELETE THIS LINE AND BELOW**

Your contribution to this project is greatly appreciated.

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/sharepointdsc/814)

### CODE REVIEW

**Comment by ykuijs** [comment]
You PR basically reverts the changes in my previous PR, which was a fix for issue #804 . There the resource tried to create the connection over and over again. If we would like to enable to use the dot in the name, we should also counter for the scenario where new connections will be created by DSC.

**Comment by NikCharlebois** [comment]
@Yorick yes, I gave some thoughts around that at first, but really, how can we tell if the connection was created by hand or by DSC? Even if I create it by hand, I can decide to call it "contoso.com" or "contoso-com". Should the Set-TargetResource create the connection, then performs a check against the created name and the name passed as a parameter and rename it if they don't match?

So for example, if the connection needs to be "contoso.com", DSC will create it as "contoso-com", and then Set-TargetResource would rename it back to "contoso.com"? This would handle the Set, and the Get would simply check for an exact match based on the name received.

**Comment by ykuijs** [comment]
The issue is that the "Add-SPProfileSyncConnection" cmdlet does not have an Name parameter. Internally it uses the Forest parameter, replacing the dot with a dash (I verified by looking at the code). So OOTB SharePoint acts differently when you create a connection from the GUI (you can specify a name) and by PowerShell (you cannot specify a name).

I think we should cater for both situations. Maybe by first checking if the specified name exist and if it does not, check for the Forest name where the dot is replaced by dash. But this does mean there could be a situation where you have two connections: One with dots and one with dashes. This resource is then unable to handle both situations......

**Comment by ykuijs** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r3.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/powershell/sharepointdsc/814#-:-LErtq2PCwCjYlMh0FRF:bnfp4nl)*

**Pull request merged**
