### PR TITLE
Infer the use of SSL

### PR DESCRIPTION
**Pull request by ykuijs**
As suggested in issue #424, this PR implements inferring the use of SSL instead of using the UseSSL parameter

- [X] Change details added to Unreleased section of changelog.md?
- [X] Added/updated documentation and descriptions in .schema.mof files where appropriate?
- [X] Examples updated for both the single server and small farm templates in the examples folder?
- [X] New/changed code adheres to [Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md)?
- [X] [Unit and Integration tests](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md) created/updated where possible?

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/sharepointdsc/459)

### CODE REVIEW

**Comment by BrianFarnhill** [comment]
@ykuijs Since this is a breaking change, I'm going to hold off on it for a moment, pending what we come up with in the discussion about v2.0 stuff in #456 - I suspect we'll need to merge this to a new branch though.

**Comment by ykuijs** [comment]
What do you mean with a breaking change? I thought that you meant you planned to have them fixed before v2

**Comment by BrianFarnhill** [comment]
@ykuijs By removing the UseSSL property we will break peoples schemas, there is no way around that, so this needs to be held off until we are ready to commit to releasing things as v2.0 - and what I raised as a point in that discussion is that it might be worth grouping all the breaking changes we have pending in issues in to one big release rather than releasing them one and a time.

**Comment by camiloborges** [comment]
Hello. Can I suggest we add a tag 'breakingchange' so it is easy to track these down?

**Comment by BrianFarnhill** [comment]
@ykuijs Can you please re-open this one to merge in to the "[preview-2.0](https://github.com/PowerShell/SharePointDsc/tree/preview-2.0)" branch? We'll park any breaking changes there until we drop 2.0. We can still review this now and merge it in though.

**Pull request closed without merging**
