### PR TITLE
SPVisioServiceApplication Fix

### PR DESCRIPTION
**Pull request by NikCharlebois**
Now creates the Service App Proxy

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/sharepointdsc/411)

### CODE REVIEW

**Comment by BrianFarnhill** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPVisioServiceApp/MSFT_SPVisioServiceApp.psm1, line 94 at r1](https://reviewable.io:443/reviews/powershell/sharepointdsc/411#-KTLc9KgEijFWfv61NAR:-KTLc9KgEijFWfv61NAS:b2ia220) ([raw file](https://github.com/powershell/sharepointdsc/blob/55c8a8e99d225fcb0a3ced778a17507d69b44ce4/Modules/SharePointDsc/DSCResources/MSFT_SPVisioServiceApp/MSFT_SPVisioServiceApp.psm1#L94)):*
> ```PowerShell
>         Invoke-SPDSCCommand -Credential $InstallAccount `
>                             -Arguments $PSBoundParameters `
>                             -ScriptBlock 
> ```

Why did you move the bracket to a new line here? This will cause issues as its a parameter value

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPVisioServiceApp/MSFT_SPVisioServiceApp.psm1, line 101 at r1](https://reviewable.io:443/reviews/powershell/sharepointdsc/411#-KTLcIXIRBQJvBiu5JMQ:-KTLcIXJofSugg8qp3Pi:bnh2iey) ([raw file](https://github.com/powershell/sharepointdsc/blob/55c8a8e99d225fcb0a3ced778a17507d69b44ce4/Modules/SharePointDsc/DSCResources/MSFT_SPVisioServiceApp/MSFT_SPVisioServiceApp.psm1#L101)):*
> ```PowerShell
>                                       -ApplicationPool $params.ApplicationPool
> 
>             $visioProxy = New-SPVisioServiceApplicationProxy -Name ($params.Name + "Proxy") -ServiceApplication $params.Name
> ```

We should be allowing users the option of setting the proxy name. Most of the other service apps have had this built in, can you lift the logic from one of those to add the "Proxy name" property to this resource and do the same thing?

---

*[Tests/Unit/SharePointDsc/SharePointDsc.SPVisioServiceApp.Tests.ps1, line 32 at r1](https://reviewable.io:443/reviews/powershell/sharepointdsc/411#-KTLcTKU5NtZpOco01gW:-KTLcTKV5TuOYNvXxpPd:bjzxrjn) ([raw file](https://github.com/powershell/sharepointdsc/blob/55c8a8e99d225fcb0a3ced778a17507d69b44ce4/Tests/Unit/SharePointDsc/SharePointDsc.SPVisioServiceApp.Tests.ps1#L32)):*
> ```PowerShell
>         Import-Module $Global:CurrentSharePointStubModule -WarningAction SilentlyContinue
> 
>         Mock Remove-SPServiceApplication { return $null }
> ```

Why did you add a return value here? 

---

*[Tests/Unit/SharePointDsc/SharePointDsc.SPVisioServiceApp.Tests.ps1, line 37 at r1](https://reviewable.io:443/reviews/powershell/sharepointdsc/411#-KTLcXAlLbbBdJnOkLYQ:-KTLcXAlLbbBdJnOkLYR:b6qsayi) ([raw file](https://github.com/powershell/sharepointdsc/blob/55c8a8e99d225fcb0a3ced778a17507d69b44ce4/Tests/Unit/SharePointDsc/SharePointDsc.SPVisioServiceApp.Tests.ps1#L37)):*
> ```PowerShell
> 
>             Mock Get-SPServiceApplication { return $null }
>             Mock New-SPVisioServiceApplication { return $null }
> ```

Same question about return values

---

*[Tests/Unit/SharePointDsc/SharePointDsc.SPVisioServiceApp.Tests.ps1, line 39 at r1](https://reviewable.io:443/reviews/powershell/sharepointdsc/411#-KTLc_lPuoHF-ZW0l8by:-KTLc_lQKGpDMSt6c7k3:b9q14t9) ([raw file](https://github.com/powershell/sharepointdsc/blob/55c8a8e99d225fcb0a3ced778a17507d69b44ce4/Tests/Unit/SharePointDsc/SharePointDsc.SPVisioServiceApp.Tests.ps1#L39)):*
> ```PowerShell
>             Mock New-SPVisioServiceApplication { return $null }
>             Mock New-SPVisioServiceApplicationProxy { return $null }
>             Mock Set-TargetResource { return $null }
> ```

Why are you mocking the entire Set-TargetResource call? We should be testing the logic in this, not mocking it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/411)*

**Comment by BrianFarnhill** [comment]
Also I need to get you to update the changelog.md file to list the fix under the unreleased heading as well. 

---

Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/411#-:-KTLdu2-zYWKJj1KDoye:b-6lpo4l)*

**Comment by BrianFarnhill** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[CHANGELOG.md, line 3 at r2](https://reviewable.io:443/reviews/powershell/sharepointdsc/411#-KTMG-EKopwpxWWYKh3u:-KTMG-ELNYKhuik-zrjX:b-5fz0ld) ([raw file](https://github.com/powershell/sharepointdsc/blob/46b8444bf3e2f0f53034fa0764ac2d2ef841b5e0/CHANGELOG.md#L3)):*
> ```Markdown
> # Change log for SharePointDsc
> ### Unreleased
>  * SPVisioServiceapplication now creates proxy and let's you specify a name for it
> ```

"let's" should be "lets" - also there should be an empty lin between the top level heading and the unreleased heading

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPVisioServiceApp/MSFT_SPVisioServiceApp.psm1, line 79 at r2](https://reviewable.io:443/reviews/powershell/sharepointdsc/411#-KTMHoSu_7CEPuSFQxz7:-KTMHoSu_7CEPuSFQxz8:b-gkj6ih) ([raw file](https://github.com/powershell/sharepointdsc/blob/46b8444bf3e2f0f53034fa0764ac2d2ef841b5e0/Modules/SharePointDsc/DSCResources/MSFT_SPVisioServiceApp/MSFT_SPVisioServiceApp.psm1#L79)):*
> ```PowerShell
>         [parameter(Mandatory = $false)]
>         [System.String] 
>         $ProxyName = "Visio Service Application Proxy",
> ```

Can we remove this default - it gets handled to be whatever the name is plus the word "proxy" on the end in the code itself, so we don't want this default to apply

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPVisioServiceApp/MSFT_SPVisioServiceApp.psm1, line 79 at r2](https://reviewable.io:443/reviews/powershell/sharepointdsc/411#-KTMIQL8BoEAmrd3kVdg:-KTMIQL8BoEAmrd3kVdh:b-hi8eo1) ([raw file](https://github.com/powershell/sharepointdsc/blob/46b8444bf3e2f0f53034fa0764ac2d2ef841b5e0/Modules/SharePointDsc/DSCResources/MSFT_SPVisioServiceApp/MSFT_SPVisioServiceApp.psm1#L79)):*
> ```PowerShell
>         [parameter(Mandatory = $false)]
>         [System.String] 
>         $ProxyName = "Visio Service Application Proxy",
> ```

Can I get you to add the proxy name property to the MOF schema, and to all of the methods in this module

---

*[Tests/Unit/SharePointDsc/SharePointDsc.SPVisioServiceApp.Tests.ps1, line 33 at r2](https://reviewable.io:443/reviews/powershell/sharepointdsc/411#-KTMI449aJ6hAiedDYbW:-KTMI449aJ6hAiedDYbX:b-2ppf51) ([raw file](https://github.com/powershell/sharepointdsc/blob/46b8444bf3e2f0f53034fa0764ac2d2ef841b5e0/Tests/Unit/SharePointDsc/SharePointDsc.SPVisioServiceApp.Tests.ps1#L33)):*
> ```PowerShell
> 
>         Mock Remove-SPServiceApplication { }
>         Mock Get-SPVisioServiceApplicationProxy { return $null }
> ```

I don't see anywhere else that you mock this to return an object for the times it should exist

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/411)*

**Comment by BrianFarnhill** [comment]
@NikCharlebois Got an update on this one dude? Has been stale for almost a week

**Comment by NikCharlebois** [comment]
@BrianFarnhill merges and changes have been done

**Comment by NikCharlebois** [comment]
Yep, my bad I totally missed your code review comments. Changes are on their way.

Nik

**Comment by NikCharlebois** [comment]
Review status: 0 of 4 files reviewed at latest revision, 9 unresolved discussions.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPVisioServiceApp/MSFT_SPVisioServiceApp.psm1, line 94 at r1](https://reviewable.io:443/reviews/powershell/sharepointdsc/411#-KTLc9KgEijFWfv61NAR:-KTuTiPSdPTpd_mRKV1q:b-886gsx) ([raw file](https://github.com/powershell/sharepointdsc/blob/55c8a8e99d225fcb0a3ced778a17507d69b44ce4/Modules/SharePointDsc/DSCResources/MSFT_SPVisioServiceApp/MSFT_SPVisioServiceApp.psm1#L94)):*
<details><summary><i>Previously, BrianFarnhill (Brian Farnhill) wrote…</i></summary>
> Why did you move the bracket to a new line here? This will cause issues as its a parameter value
</details>
Fixed

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPVisioServiceApp/MSFT_SPVisioServiceApp.psm1, line 101 at r1](https://reviewable.io:443/reviews/powershell/sharepointdsc/411#-KTLcIXIRBQJvBiu5JMQ:-KTuTjtalkh8_vvM_ajf:bb6un1j) ([raw file](https://github.com/powershell/sharepointdsc/blob/55c8a8e99d225fcb0a3ced778a17507d69b44ce4/Modules/SharePointDsc/DSCResources/MSFT_SPVisioServiceApp/MSFT_SPVisioServiceApp.psm1#L101)):*
<details><summary><i>Previously, BrianFarnhill (Brian Farnhill) wrote…</i></summary>
> We should be allowing users the option of setting the proxy name. Most of the other service apps have had this built in, can you lift the logic from one of those to add the "Proxy name" property to this resource and do the same thing?
</details>
Done

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPVisioServiceApp/MSFT_SPVisioServiceApp.psm1, line 79 at r2](https://reviewable.io:443/reviews/powershell/sharepointdsc/411#-KTMIQL8BoEAmrd3kVdg:-KTuTecHBvbRErvxIh1j:bb6un1j) ([raw file](https://github.com/powershell/sharepointdsc/blob/46b8444bf3e2f0f53034fa0764ac2d2ef841b5e0/Modules/SharePointDsc/DSCResources/MSFT_SPVisioServiceApp/MSFT_SPVisioServiceApp.psm1#L79)):*
<details><summary><i>Previously, BrianFarnhill (Brian Farnhill) wrote…</i></summary>
> Can I get you to add the proxy name property to the MOF schema, and to all of the methods in this module
</details>
Done

---

*[Tests/Unit/SharePointDsc/SharePointDsc.SPVisioServiceApp.Tests.ps1, line 32 at r1](https://reviewable.io:443/reviews/powershell/sharepointdsc/411#-KTLcTKU5NtZpOco01gW:-KTuTndiQlxWmmnNT3IA:b-s03wr1) ([raw file](https://github.com/powershell/sharepointdsc/blob/55c8a8e99d225fcb0a3ced778a17507d69b44ce4/Tests/Unit/SharePointDsc/SharePointDsc.SPVisioServiceApp.Tests.ps1#L32)):*
<details><summary><i>Previously, BrianFarnhill (Brian Farnhill) wrote…</i></summary>
> Why did you add a return value here? 
</details>
Null value return removed

---

*[Tests/Unit/SharePointDsc/SharePointDsc.SPVisioServiceApp.Tests.ps1, line 37 at r1](https://reviewable.io:443/reviews/powershell/sharepointdsc/411#-KTLcXAlLbbBdJnOkLYQ:-KTuTsehVTYKKssBU_WV:buvcvdw) ([raw file](https://github.com/powershell/sharepointdsc/blob/55c8a8e99d225fcb0a3ced778a17507d69b44ce4/Tests/Unit/SharePointDsc/SharePointDsc.SPVisioServiceApp.Tests.ps1#L37)):*
<details><summary><i>Previously, BrianFarnhill (Brian Farnhill) wrote…</i></summary>
> Same question about return values
</details>
Removed null return

---

*[Tests/Unit/SharePointDsc/SharePointDsc.SPVisioServiceApp.Tests.ps1, line 39 at r1](https://reviewable.io:443/reviews/powershell/sharepointdsc/411#-KTLc_lPuoHF-ZW0l8by:-KTuTvg8KpsX3hOg0nOY:b-s0l3z4) ([raw file](https://github.com/powershell/sharepointdsc/blob/55c8a8e99d225fcb0a3ced778a17507d69b44ce4/Tests/Unit/SharePointDsc/SharePointDsc.SPVisioServiceApp.Tests.ps1#L39)):*
<details><summary><i>Previously, BrianFarnhill (Brian Farnhill) wrote…</i></summary>
> Why are you mocking the entire Set-TargetResource call? We should be testing the logic in this, not mocking it.
</details>
Mock method has been removed

---

*[Tests/Unit/SharePointDsc/SharePointDsc.SPVisioServiceApp.Tests.ps1, line 33 at r2](https://reviewable.io:443/reviews/powershell/sharepointdsc/411#-KTMI449aJ6hAiedDYbW:-KTuTqLgLRtQa_phP69M:b5wtz60) ([raw file](https://github.com/powershell/sharepointdsc/blob/46b8444bf3e2f0f53034fa0764ac2d2ef841b5e0/Tests/Unit/SharePointDsc/SharePointDsc.SPVisioServiceApp.Tests.ps1#L33)):*
<details><summary><i>Previously, BrianFarnhill (Brian Farnhill) wrote…</i></summary>
> I don't see anywhere else that you mock this to return an object for the times it should exist
</details>
Mock method removed, not needed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/411)*

**Comment by NikCharlebois** [comment]
Review status: 0 of 4 files reviewed at latest revision, 4 unresolved discussions.

---

*[CHANGELOG.md, line 3 at r2](https://reviewable.io:443/reviews/powershell/sharepointdsc/411#-KTMG-EKopwpxWWYKh3u:-KTuU6wy6My9GARGJElN:b-y8xl7n) ([raw file](https://github.com/powershell/sharepointdsc/blob/46b8444bf3e2f0f53034fa0764ac2d2ef841b5e0/CHANGELOG.md#L3)):*
<details><summary><i>Previously, BrianFarnhill (Brian Farnhill) wrote…</i></summary>
> "let's" should be "lets" - also there should be an empty lin between the top level heading and the unreleased heading
</details>
Typo Fixed

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPVisioServiceApp/MSFT_SPVisioServiceApp.psm1, line 79 at r2](https://reviewable.io:443/reviews/powershell/sharepointdsc/411#-KTMHoSu_7CEPuSFQxz7:-KTuU8c7UaUDxZyMhNAG:b-c6lq9w) ([raw file](https://github.com/powershell/sharepointdsc/blob/46b8444bf3e2f0f53034fa0764ac2d2ef841b5e0/Modules/SharePointDsc/DSCResources/MSFT_SPVisioServiceApp/MSFT_SPVisioServiceApp.psm1#L79)):*
<details><summary><i>Previously, BrianFarnhill (Brian Farnhill) wrote…</i></summary>
> Can we remove this default - it gets handled to be whatever the name is plus the word "proxy" on the end in the code itself, so we don't want this default to apply
</details>
Default removed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/411)*

**Comment by BrianFarnhill** [comment]
Reviewed 4 of 4 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPVisioServiceApp/MSFT_SPVisioServiceApp.psm1, line 101 at r1](https://reviewable.io:443/reviews/powershell/sharepointdsc/411#-KTLcIXIRBQJvBiu5JMQ:-KTuaMOhkMhVl0gUVlgt:b-acdmj7) ([raw file](https://github.com/powershell/sharepointdsc/blob/55c8a8e99d225fcb0a3ced778a17507d69b44ce4/Modules/SharePointDsc/DSCResources/MSFT_SPVisioServiceApp/MSFT_SPVisioServiceApp.psm1#L101)):*
<details><summary><i>Previously, NikCharlebois (Nik Charlebois) wrote…</i></summary>
> Done
</details>
Proxy name is optional so you need to account for that - have a look at how we do this in [other resources](https://github.com/PowerShell/SharePointDsc/blob/dev/Modules/SharePointDsc/DSCResources/MSFT_SPManagedMetadataServiceApp/MSFT_SPManagedMetaDataServiceApp.psm1#L158) to get a feel for the code

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/411)*

**Comment by BrianFarnhill** [comment]
Just checking where you're at with these Nik, haven't seen anything come through on this PR in the last week or so 

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/411#-:-KUQ7SUvgFvbb_F7ZKLa:b22d5pe)*

**Comment by BrianFarnhill** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/411#-:-KUR631S7biLESCOf4DP:bnfp4nl)*

**Pull request merged**
