### PR TITLE
Add SPFarmPropertyBag resource

### PR DESCRIPTION
**Pull request by luigilink**
Add SPFarmPropertyBag resource

- [x] Change details added to Unreleased section of changelog.md?
- [x] Added/updated documentation and descriptions in .schema.mof files where appropriate?
- [x] Examples updated for both the single server and small farm templates in the examples folder?
- [x] New/changed code adheres to [Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md)?
- [x] [Unit and Integration tests](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md) created/updated where possible?

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/sharepointdsc/460)

### CODE REVIEW

**Comment by BrianFarnhill** [comment]
Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPFarmPropertyBag/MSFT_SPFarmPropertyBag.psm1, line 19 at r1](https://reviewable.io:443/reviews/powershell/sharepointdsc/460#-KYBWF7k7eZRblS_bKV2:-KYBWF7k7eZRblS_bKV3:b-8wwha8) ([raw file](https://github.com/powershell/sharepointdsc/blob/f055dd666df6b223929d57eef982ab6772de515d/Modules/SharePointDsc/DSCResources/MSFT_SPFarmPropertyBag/MSFT_SPFarmPropertyBag.psm1#L19)):*
> ```PowerShell
>         [System.String] 
>         $Ensure = 'Present'
>     )
> ```

You're missing InstallAccount as a parameter here

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPFarmPropertyBag/MSFT_SPFarmPropertyBag.psm1, line 46 at r1](https://reviewable.io:443/reviews/powershell/sharepointdsc/460#-KYBVQSU7WwduDLYBSt4:-KYBVQSU7WwduDLYBSt5:bs04w90) ([raw file](https://github.com/powershell/sharepointdsc/blob/f055dd666df6b223929d57eef982ab6772de515d/Modules/SharePointDsc/DSCResources/MSFT_SPFarmPropertyBag/MSFT_SPFarmPropertyBag.psm1#L46)):*
> ```PowerShell
>             $currentValue = $spFarm.Properties[$params.Key]
> 
>             if ($currentValue -eq $params.Value)
> ```

Here you are assuming that if the current value isn't correct that it should return that it is absent, which isn't the case. The value can be present and the correct value (Value is right and ensure = present), it can be present and wrong (value is wrong and ensure is still = present) or not there are all (where ensure would = absent). Can we update this code block so that if there is a value there at all in the property bag ensure should be present, and if its not there at all then make it absent.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPFarmPropertyBag/MSFT_SPFarmPropertyBag.psm1, line 89 at r1](https://reviewable.io:443/reviews/powershell/sharepointdsc/460#-KYBVye9f9O-XSWxOAzB:-KYBVye9f9O-XSWxOAzC:b-tknqay) ([raw file](https://github.com/powershell/sharepointdsc/blob/f055dd666df6b223929d57eef982ab6772de515d/Modules/SharePointDsc/DSCResources/MSFT_SPFarmPropertyBag/MSFT_SPFarmPropertyBag.psm1#L89)):*
> ```PowerShell
>     )
> 
>     Write-Verbose -Message "Setting antivirus configuration settings"
> ```

Need to update this to the current modules activities

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPFarmPropertyBag/MSFT_SPFarmPropertyBag.schema.mof, line 5 at r1](https://reviewable.io:443/reviews/powershell/sharepointdsc/460#-KYBWiQa5nDiQlTT8eCK:-KYBWiQa5nDiQlTT8eCL:bvgymtv) ([raw file](https://github.com/powershell/sharepointdsc/blob/f055dd666df6b223929d57eef982ab6772de515d/Modules/SharePointDsc/DSCResources/MSFT_SPFarmPropertyBag/MSFT_SPFarmPropertyBag.schema.mof#L5)):*
> ```
> {
>     [Key, Description("The key of the SPFarm property bag")] string Key;
>     [Required, Description("Value of the farm property bag")] String Value;
> ```

This should be optional since if ensure is set to absent it won't need a value. This means we need to add a check to make sure that the value is specified only when Ensure = Present in the set method. 

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPFarmPropertyBag/MSFT_SPFarmPropertyBag.schema.mof, line 6 at r1](https://reviewable.io:443/reviews/powershell/sharepointdsc/460#-KYBW9KVfmOt0fbYF1c8:-KYBW9KVfmOt0fbYF1c9:bchnmfc) ([raw file](https://github.com/powershell/sharepointdsc/blob/f055dd666df6b223929d57eef982ab6772de515d/Modules/SharePointDsc/DSCResources/MSFT_SPFarmPropertyBag/MSFT_SPFarmPropertyBag.schema.mof#L6)):*
> ```
>     [Key, Description("The key of the SPFarm property bag")] string Key;
>     [Required, Description("Value of the farm property bag")] String Value;
>     [Write, Description("Set to present to ensure the trust exists, or absent to ensure it is removed"), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] string Ensure;
> ```

The description here needs to be updated

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPFarmPropertyBag/MSFT_SPFarmPropertyBag.schema.mof, line 7 at r1](https://reviewable.io:443/reviews/powershell/sharepointdsc/460#-KYBWBlUyFR9QkIAamcp:-KYBWBlVJJOV9Om4hKOk:b-ogzy48) ([raw file](https://github.com/powershell/sharepointdsc/blob/f055dd666df6b223929d57eef982ab6772de515d/Modules/SharePointDsc/DSCResources/MSFT_SPFarmPropertyBag/MSFT_SPFarmPropertyBag.schema.mof#L7)):*
> ```
>     [Required, Description("Value of the farm property bag")] String Value;
>     [Write, Description("Set to present to ensure the trust exists, or absent to ensure it is removed"), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] string Ensure;
> };
> ```

Missing InstallAccount option here as well

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPFarmPropertyBag/readme.md, line 4 at r1](https://reviewable.io:443/reviews/powershell/sharepointdsc/460#-KYBWJw9LFXVx2jbt-87:-KYBWJw9LFXVx2jbt-88:b-7t9muc) ([raw file](https://github.com/powershell/sharepointdsc/blob/f055dd666df6b223929d57eef982ab6772de515d/Modules/SharePointDsc/DSCResources/MSFT_SPFarmPropertyBag/readme.md#L4)):*
> ```Markdown
> 
> This resource is used to work with SharePoint Property Bags at the farm level.
> Only farm administrators can use this resource.
> ```

Rather than saying "Only farm admins can use this" can we say something like "the account that runs this resource must be a farm administrator". Also is this something we should test for before we try to run the set method to be sure it is the case?

---

*[Modules/SharePointDsc/Examples/Resources/SPFarmPropertyBag/1-RemoveFarmPropertyBag.ps1, line 23 at r1](https://reviewable.io:443/reviews/powershell/sharepointdsc/460#-KYBWa3gZbEGRl3eOdhi:-KYBWa3gZbEGRl3eOdhj:b9wq6or) ([raw file](https://github.com/powershell/sharepointdsc/blob/f055dd666df6b223929d57eef982ab6772de515d/Modules/SharePointDsc/Examples/Resources/SPFarmPropertyBag/1-RemoveFarmPropertyBag.ps1#L23)):*
> ```PowerShell
>             PsDscRunAsCredential = $SetupAccount
>             Key = "KeyToRemove"
>             Value = "ContentFarm"
> ```

Looking at this, we should make value an optional field because if I'm ensure = absent I shouldn't need to specify a value. 

---

*[Tests/Unit/SharePointDsc/SharePointDsc.SPFarmPropertyBag.ps1, line 99 at r1](https://reviewable.io:443/reviews/powershell/sharepointdsc/460#-KYBXHboWx_uGwrfRe3k:-KYBXHboWx_uGwrfRe3l:b-w4wowr) ([raw file](https://github.com/powershell/sharepointdsc/blob/f055dd666df6b223929d57eef982ab6772de515d/Tests/Unit/SharePointDsc/SharePointDsc.SPFarmPropertyBag.ps1#L99)):*
> ```PowerShell
>                 Set-TargetResource @testParams 
> 
>                 Assert-MockCalled Get-SPFarm 
> ```

We don't really need to assert this here, its assumed by the call to the update of the farm object on the next line so we can drop this assert line. 

---

*[Tests/Unit/SharePointDsc/SharePointDsc.SPFarmPropertyBag.ps1, line 180 at r1](https://reviewable.io:443/reviews/powershell/sharepointdsc/460#-KYBXQG0v0KdImFfSFBY:-KYBXQG0v0KdImFfSFBZ:b4smd3b) ([raw file](https://github.com/powershell/sharepointdsc/blob/f055dd666df6b223929d57eef982ab6772de515d/Tests/Unit/SharePointDsc/SharePointDsc.SPFarmPropertyBag.ps1#L180)):*
> ```PowerShell
>                 Set-TargetResource @testParams 
> 
>                 Assert-MockCalled Get-SPFarm 
> ```

Same as above about ditching the assert statement

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/460)*

**Comment by luigilink** [comment]
Reviewed 6 of 6 files at r2.
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPFarmPropertyBag/MSFT_SPFarmPropertyBag.psm1, line 19 at r1](https://reviewable.io:443/reviews/powershell/sharepointdsc/460#-KYBWF7k7eZRblS_bKV2:-KZ66fOA_YLIPeETwGA6:b-896fix) ([raw file](https://github.com/powershell/sharepointdsc/blob/f055dd666df6b223929d57eef982ab6772de515d/Modules/SharePointDsc/DSCResources/MSFT_SPFarmPropertyBag/MSFT_SPFarmPropertyBag.psm1#L19)):*
<details><summary><i>Previously, BrianFarnhill (Brian Farnhill) wrote…</i></summary><blockquote>

You're missing InstallAccount as a parameter here
</blockquote></details>

Done.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPFarmPropertyBag/MSFT_SPFarmPropertyBag.psm1, line 46 at r1](https://reviewable.io:443/reviews/powershell/sharepointdsc/460#-KYBVQSU7WwduDLYBSt4:-KZ66grMLg9Urc-gyW9Q:b-bmgl4n) ([raw file](https://github.com/powershell/sharepointdsc/blob/f055dd666df6b223929d57eef982ab6772de515d/Modules/SharePointDsc/DSCResources/MSFT_SPFarmPropertyBag/MSFT_SPFarmPropertyBag.psm1#L46)):*
<details><summary><i>Previously, BrianFarnhill (Brian Farnhill) wrote…</i></summary><blockquote>

Here you are assuming that if the current value isn't correct that it should return that it is absent, which isn't the case. The value can be present and the correct value (Value is right and ensure = present), it can be present and wrong (value is wrong and ensure is still = present) or not there are all (where ensure would = absent). Can we update this code block so that if there is a value there at all in the property bag ensure should be present, and if its not there at all then make it absent.
</blockquote></details>

Is it better now ?

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPFarmPropertyBag/MSFT_SPFarmPropertyBag.psm1, line 89 at r1](https://reviewable.io:443/reviews/powershell/sharepointdsc/460#-KYBVye9f9O-XSWxOAzB:-KZ66rt82k_IjRXLpR0I:b-896fix) ([raw file](https://github.com/powershell/sharepointdsc/blob/f055dd666df6b223929d57eef982ab6772de515d/Modules/SharePointDsc/DSCResources/MSFT_SPFarmPropertyBag/MSFT_SPFarmPropertyBag.psm1#L89)):*
<details><summary><i>Previously, BrianFarnhill (Brian Farnhill) wrote…</i></summary><blockquote>

Need to update this to the current modules activities
</blockquote></details>

Done.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPFarmPropertyBag/MSFT_SPFarmPropertyBag.schema.mof, line 5 at r1](https://reviewable.io:443/reviews/powershell/sharepointdsc/460#-KYBWiQa5nDiQlTT8eCK:-KZ66tV2ND822AjRSQoO:b-896fix) ([raw file](https://github.com/powershell/sharepointdsc/blob/f055dd666df6b223929d57eef982ab6772de515d/Modules/SharePointDsc/DSCResources/MSFT_SPFarmPropertyBag/MSFT_SPFarmPropertyBag.schema.mof#L5)):*
<details><summary><i>Previously, BrianFarnhill (Brian Farnhill) wrote…</i></summary><blockquote>

This should be optional since if ensure is set to absent it won't need a value. This means we need to add a check to make sure that the value is specified only when Ensure = Present in the set method. 
</blockquote></details>

Done.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPFarmPropertyBag/MSFT_SPFarmPropertyBag.schema.mof, line 6 at r1](https://reviewable.io:443/reviews/powershell/sharepointdsc/460#-KYBW9KVfmOt0fbYF1c8:-KZ66wgBSyScEzf0A8-O:b-896fix) ([raw file](https://github.com/powershell/sharepointdsc/blob/f055dd666df6b223929d57eef982ab6772de515d/Modules/SharePointDsc/DSCResources/MSFT_SPFarmPropertyBag/MSFT_SPFarmPropertyBag.schema.mof#L6)):*
<details><summary><i>Previously, BrianFarnhill (Brian Farnhill) wrote…</i></summary><blockquote>

The description here needs to be updated
</blockquote></details>

Done.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPFarmPropertyBag/MSFT_SPFarmPropertyBag.schema.mof, line 7 at r1](https://reviewable.io:443/reviews/powershell/sharepointdsc/460#-KYBWBlUyFR9QkIAamcp:-KZ66y3lIlNE7GBYP6AF:b-896fix) ([raw file](https://github.com/powershell/sharepointdsc/blob/f055dd666df6b223929d57eef982ab6772de515d/Modules/SharePointDsc/DSCResources/MSFT_SPFarmPropertyBag/MSFT_SPFarmPropertyBag.schema.mof#L7)):*
<details><summary><i>Previously, BrianFarnhill (Brian Farnhill) wrote…</i></summary><blockquote>

Missing InstallAccount option here as well
</blockquote></details>

Done.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPFarmPropertyBag/readme.md, line 4 at r1](https://reviewable.io:443/reviews/powershell/sharepointdsc/460#-KYBWJw9LFXVx2jbt-87:-KZ66zHtHno88Jx9sjDJ:b-896fix) ([raw file](https://github.com/powershell/sharepointdsc/blob/f055dd666df6b223929d57eef982ab6772de515d/Modules/SharePointDsc/DSCResources/MSFT_SPFarmPropertyBag/readme.md#L4)):*
<details><summary><i>Previously, BrianFarnhill (Brian Farnhill) wrote…</i></summary><blockquote>

Rather than saying "Only farm admins can use this" can we say something like "the account that runs this resource must be a farm administrator". Also is this something we should test for before we try to run the set method to be sure it is the case?
</blockquote></details>

Done.

---

*[Modules/SharePointDsc/Examples/Resources/SPFarmPropertyBag/1-RemoveFarmPropertyBag.ps1, line 23 at r1](https://reviewable.io:443/reviews/powershell/sharepointdsc/460#-KYBWa3gZbEGRl3eOdhi:-KZ670VIF61a78wwQRXy:b-896fix) ([raw file](https://github.com/powershell/sharepointdsc/blob/f055dd666df6b223929d57eef982ab6772de515d/Modules/SharePointDsc/Examples/Resources/SPFarmPropertyBag/1-RemoveFarmPropertyBag.ps1#L23)):*
<details><summary><i>Previously, BrianFarnhill (Brian Farnhill) wrote…</i></summary><blockquote>

Looking at this, we should make value an optional field because if I'm ensure = absent I shouldn't need to specify a value. 
</blockquote></details>

Done.

---

*[Tests/Unit/SharePointDsc/SharePointDsc.SPFarmPropertyBag.ps1, line 99 at r1](https://reviewable.io:443/reviews/powershell/sharepointdsc/460#-KYBXHboWx_uGwrfRe3k:-KZ66Uu5zqjWZu0s0XDV:b-896fix) ([raw file](https://github.com/powershell/sharepointdsc/blob/f055dd666df6b223929d57eef982ab6772de515d/Tests/Unit/SharePointDsc/SharePointDsc.SPFarmPropertyBag.ps1#L99)):*
<details><summary><i>Previously, BrianFarnhill (Brian Farnhill) wrote…</i></summary><blockquote>

We don't really need to assert this here, its assumed by the call to the update of the farm object on the next line so we can drop this assert line. 
</blockquote></details>

Done.

---

*[Tests/Unit/SharePointDsc/SharePointDsc.SPFarmPropertyBag.ps1, line 180 at r1](https://reviewable.io:443/reviews/powershell/sharepointdsc/460#-KYBXQG0v0KdImFfSFBY:-KZ66WDApHnJ6tn-mhLJ:b-896fix) ([raw file](https://github.com/powershell/sharepointdsc/blob/f055dd666df6b223929d57eef982ab6772de515d/Tests/Unit/SharePointDsc/SharePointDsc.SPFarmPropertyBag.ps1#L180)):*
<details><summary><i>Previously, BrianFarnhill (Brian Farnhill) wrote…</i></summary><blockquote>

Same as above about ditching the assert statement
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/460)*

**Comment by BrianFarnhill** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPFarmPropertyBag/MSFT_SPFarmPropertyBag.psm1, line 46 at r1](https://reviewable.io:443/reviews/powershell/sharepointdsc/460#-KYBVQSU7WwduDLYBSt4:-KZY8AOzMxW6j23HfVv2:b-ievht9) ([raw file](https://github.com/powershell/sharepointdsc/blob/f055dd666df6b223929d57eef982ab6772de515d/Modules/SharePointDsc/DSCResources/MSFT_SPFarmPropertyBag/MSFT_SPFarmPropertyBag.psm1#L46)):*
<details><summary><i>Previously, luigilink (Jean-Cyril Drouhin) wrote…</i></summary><blockquote>

Is it better now ?
</blockquote></details>

What you should have in this get method here should look a little like this:

    if ($spFarm.Properties.Contains($params.Key) -eq $true)
    {
        $localEnsure = "Present"
        $currentValue = $spFarm.Properties[$params.Key]
    }
    else
    {
        $localEnsure = "Absent"
        $currentValue = $null
    }

So then the ensure property tells us if the value is there or not, and the value itself is tested to make sure it matches. Does that make more sense?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/460)*

**Comment by BrianFarnhill** [comment]
@luigilink Are you still able to make that last change so we can get this one through and released?

**Comment by luigilink** [comment]
Yes, I can did this monday

**Comment by luigilink** [comment]
Reviewed 1 of 7 files at r1, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPFarmPropertyBag/MSFT_SPFarmPropertyBag.psm1, line 46 at r1](https://reviewable.io:443/reviews/powershell/sharepointdsc/460#-KYBVQSU7WwduDLYBSt4:-Kbjtu6pLec5tini5lfU:bu9ni4o) ([raw file](https://github.com/powershell/sharepointdsc/blob/f055dd666df6b223929d57eef982ab6772de515d/Modules/SharePointDsc/DSCResources/MSFT_SPFarmPropertyBag/MSFT_SPFarmPropertyBag.psm1#L46)):*
<details><summary><i>Previously, BrianFarnhill (Brian Farnhill) wrote…</i></summary><blockquote>

What you should have in this get method here should look a little like this:

    if ($spFarm.Properties.Contains($params.Key) -eq $true)
    {
        $localEnsure = "Present"
        $currentValue = $spFarm.Properties[$params.Key]
    }
    else
    {
        $localEnsure = "Absent"
        $currentValue = $null
    }

So then the ensure property tells us if the value is there or not, and the value itself is tested to make sure it matches. Does that make more sense?
</blockquote></details>

Done. You're right, it's better and cleaner :+1: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/460)*

**Pull request merged**
