### PR TITLE
SPWebAppPropertyBag: Added new resource for managing web application property bag.

### LINKED ISSUE #799: SPWebAppPropertyBag: new resource: Set Properties on web application level
**Details of the scenario you try and problem that is occurring:**
Currently there is no resource available that allows to set property bag values at the web application level. There is a resource available to set the farm property bag.

There should be a resource that allows setting web application property bag values. There are the following options:

1. Extend SPWebApplication resource: Add a new parameter that consumes a custom object 
2. Create a new resource SPWebAppPropertyBag

@ykuijs @NikCharlebois What do you prefer?

### PR DESCRIPTION
**Pull request by jensotto**
#### Pull Request (PR) description

Added a new resource to manage web application property bag.

#### This Pull Request (PR) fixes the following issues
- Fixes #799 
#### Task list
- [x] Added an entry under the Unreleased section of the change log in the CHANGELOG.md.
      Entry should say what was changed, and how that affects users (if applicable).
- [x] Resource documentation added/updated in README.md in the resource folder.
- [x] Resource parameter descriptions added/updated in schema.mof
      and comment-based help.
- [x] Comment-based help added/updated.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [x] Examples appropriately added/updated.
- [x] Unit tests added/updated. See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] Integration tests added/updated (where possible). See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [x] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/sharepointdsc/886)

### CODE REVIEW

**Comment by ykuijs** [comment]
Line 5 of the Readme.md is too long. Please move some words to the next line:

C:\projects\sharepointdsc\Modules\SharePointDsc\DscResources\MSFT_SPWebAppPropertyBag\readme.md: 5: MD013 Line length

**Comment by jensotto** [comment]
@ykuijs  I'll fix your comments.
You should probably have a look in SPFarmPropertyBag for the same issues as I copied everything from SPFarmPropertyBag resource and I did not change any of the items you have commented.

**Comment by ykuijs** [comment]
In the initial post, there is a Reviewable button. If you click that button, Reviewable is opened in which you can acknowledge all comments. But you can also click the "Details" link behind the reviewable line at the checks.

**Comment by ykuijs** [comment]
Just one more update: You have to remove the trailing space on line 6 in Modules\SharePointDsc\DscResources\MSFT_SPWebAppPropertyBag\readme.md

And then we are all set to merge this PR!

**Comment by jensotto** [comment]
Done. 
Is there any way to get notified about these problems locally before pushing to the repository? I have to admit that this was a big pain to fix, especially since Appveyor takes a long time to complete. Maybe it's because I'm new to these rules.

**Comment by ykuijs** [comment]
@jensotto Yes there are. I am testing that at the moment. Will get back to you on this!

**Pull request merged**
