### PR TITLE
Project server bug

### PR DESCRIPTION
**Pull request by BrianFarnhill**
I broke a couple of things in these resources with the kerberos fixes - my bad! Fixes are here.

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/sharepointdsc/692)

### CODE REVIEW

**Comment by ykuijs** [comment]
One question for all updates: You assume the Default zone. Isn't this possible that the Default zone is using NTLM, but a different zone is using Kerberos?

---

Review status: 0 of 16 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/692#-:-L-ks5aDiFiFmp1TsN-8:b-1s542r)*

**Comment by BrianFarnhill** [comment]
True - lets document it as a requirement that the URL/auth you configure in the resources must match the default zone so we can account for it?

---

Review status: 0 of 16 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/692#-:-L-mmUz0vPYTPZPEGf6r:b-utpkts)*

**Comment by ykuijs** [comment]
Sounds like a plan! If you add that, I will complete the review and merge the PR

---

Review status: 0 of 16 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/692#-:-L-p13nHbFPjV67wx_Ym:bj0o0xy)*

**Comment by ykuijs** [comment]
@BrianFarnhill Can you please update this PR, so we can merge it into Dev and include it in v2.0

**Comment by BrianFarnhill** [comment]
It's on my to-do list for this morning. Expect it in an hour or so

Sent from Nine<http://www.9folders.com/>
________________________________

**Comment by BrianFarnhill** [comment]
@ykuijs  All yours mate

**Comment by ykuijs** [comment]
:lgtm:

---

Reviewed 16 of 16 files at r1, 8 of 8 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/692#-:-L0O5ZcPVGKmm_Cwb-Dm:bnfp4nl)*

**Pull request merged**
