### PR TITLE
Added NetBIOS Domain Names Support. 

### PR DESCRIPTION
**Pull request by camiloborges**
Thanks for submitting a Pull Request to this project.

Please make sure you have read the [Contribution Guidelines](https://github.com/powershell/xSharePoint/wiki/Contributing%20to%20xSharePoint).

To aid community reviewers in reviewing and merging your PR, please take the time to run through this checklist:
- [x] Change details added to Unreleased section of readme.md?
- [x] Added/updated documentation and descriptions in .schema.mof files where appropriate?
- [No] Examples updated for both the single server and small farm templates in the examples folder?
- [I hope so] New/changed code adheres to [Style Guidelines]?(https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md)?
- [Unit Tests Added] [Unit and Integration tests](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md) created/updated where possible?

Your contribution to this project is greatly appreciated.

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/sharepointdsc/349)

### CODE REVIEW

**Comment by camiloborges** [comment]
@BrianFarnhill , it will be interesting to see if this passes Integration Tests. I am always suspicious when Adding and retrieving objects from UPSA immediately after

**Comment by BrianFarnhill** [comment]
Reviewed 2 of 5 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[.gitignore, line 9 \[r2\]](https://reviewable.io:443/reviews/powershell/sharepointdsc/349#-KLIzu7ZRQyJdwWner9t:-KLIzu7_o0d3oFoMwG2-:-1665411682) ([raw file](https://github.com/powershell/sharepointdsc/blob/e9bb4790012d6e95bf60a00f76390aaf2743b221/.gitignore#L9)):*
> ```
> Modules/SharePointDsc/DscResource.Tests
> Modules/SharePointDsc/DscResource.Tests/*
> /Modules/xSharePoint
> ```

Why are you adding this to the ignore file? You shouldn't have anything in there. Please roll this back

---

*[CHANGELOG.md, line 17 \[r2\]](https://reviewable.io:443/reviews/powershell/sharepointdsc/349#-KLJ--Jf6NhS5OnTu9Pq:-KLJ--Jf6NhS5OnTu9Pr:2015305155) ([raw file](https://github.com/powershell/sharepointdsc/blob/e9bb4790012d6e95bf60a00f76390aaf2743b221/CHANGELOG.md#L17)):*
> ```Markdown
>  * Fixed a bug with SPSearchServiceApp that prevents the default crawl account from being managed after it is initially set
>  * Removed dependency on Win32_Prouct from SPInstallPrereqs
>  * Added support for NetBIOS domain names resolution to SPUserProfileServiceApp 
> ```

Please put this under a new heading "unreleased" as we've done 1.1 already

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/349)*

**Comment by camiloborges** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[.gitignore, line 9 \[r2\]](https://reviewable.io:443/reviews/powershell/sharepointdsc/349#-KLIzu7ZRQyJdwWner9t:-KLJ9LY-UVGisR0nquho:-759289550) ([raw file](https://github.com/powershell/sharepointdsc/blob/e9bb4790012d6e95bf60a00f76390aaf2743b221/.gitignore#L9)):*
<details><summary><i>Previously, BrianFarnhill (Brian Farnhill) wrote…</i></summary>
> Why are you adding this to the ignore file? You shouldn't have anything in there. Please roll this back
</details>
Good question. Because for some reason I ended up with an xSharePoint folder added again and I decided to remove it for good :)
Happy to remove it thought, but issue might happen again

---

*[CHANGELOG.md, line 17 \[r2\]](https://reviewable.io:443/reviews/powershell/sharepointdsc/349#-KLJ--Jf6NhS5OnTu9Pq:-KLJ9_9_8O3n_2UT2Mqp:1396147223) ([raw file](https://github.com/powershell/sharepointdsc/blob/e9bb4790012d6e95bf60a00f76390aaf2743b221/CHANGELOG.md#L17)):*
<details><summary><i>Previously, BrianFarnhill (Brian Farnhill) wrote…</i></summary>
> Please put this under a new heading "unreleased" as we've done 1.1 already
</details>
cool, I thought this would just sneak in :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/349)*

**Comment by BrianFarnhill** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[.gitignore, line 9 \[r2\]](https://reviewable.io:443/reviews/powershell/sharepointdsc/349#-KLIzu7ZRQyJdwWner9t:-KLJ9tcnmGBc8yjYiL64:-1689287053) ([raw file](https://github.com/powershell/sharepointdsc/blob/e9bb4790012d6e95bf60a00f76390aaf2743b221/.gitignore#L9)):*
<details><summary><i>Previously, camiloborges (Camilo Borges) wrote…</i></summary>
> Good question. Because for some reason I ended up with an xSharePoint folder added again and I decided to remove it for good :)
> Happy to remove it thought, but issue might happen again
> 
</details>
Yea remove it please

---

*[CHANGELOG.md, line 17 \[r2\]](https://reviewable.io:443/reviews/powershell/sharepointdsc/349#-KLJ--Jf6NhS5OnTu9Pq:-KLJ9wgym0f6pJQRJiHf:1093779252) ([raw file](https://github.com/powershell/sharepointdsc/blob/e9bb4790012d6e95bf60a00f76390aaf2743b221/CHANGELOG.md#L17)):*
<details><summary><i>Previously, camiloborges (Camilo Borges) wrote…</i></summary>
> cool, I thought this would just sneak in :)
</details>
No can do - release is too far along the process to get it in mate :) 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/349)*

**Comment by camiloborges** [comment]
Review status: 3 of 4 files reviewed at latest revision, 4 unresolved discussions.

---

*[CHANGELOG.md, line 17 \[r2\]](https://reviewable.io:443/reviews/powershell/sharepointdsc/349#-KLJ--Jf6NhS5OnTu9Pq:-KLJAUreE3aN_PLPEJSc:1403406937) ([raw file](https://github.com/powershell/sharepointdsc/blob/e9bb4790012d6e95bf60a00f76390aaf2743b221/CHANGELOG.md#L17)):*
<details><summary><i>Previously, BrianFarnhill (Brian Farnhill) wrote…</i></summary>
> No can do - release is too far along the process to get it in mate :) 
</details>
cool, files were updated. 

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPUserProfileServiceApp/MSFT_SPUserProfileServiceApp.psm1, line 139 \[r3\]](https://reviewable.io:443/reviews/powershell/sharepointdsc/349#-KLJAoq8dZs2ClIjDr_2:-KLJAoq8dZs2ClIjDr_3:-454773603) ([raw file](https://github.com/powershell/sharepointdsc/blob/c33a0fa75707da0919ca1e51fa7903dac8c7d36a/Modules/SharePointDsc/DSCResources/MSFT_SPUserProfileServiceApp/MSFT_SPUserProfileServiceApp.psm1#L139)):*
> ```PowerShell
>                 }
>             }
>             if($app.NetBIOSDomainNamesEnabled -ne $EnableNetBIOS){
> ```

Brian, check if you agree with this. (Hey I haven't used aliases!!!!)

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPUserProfileServiceApp/MSFT_SPUserProfileServiceApp.psm1, line 192 \[r3\]](https://reviewable.io:443/reviews/powershell/sharepointdsc/349#-KLJAwdoYFzujiEy2LYA:-KLJAwdoYFzujiEy2LYB:1010368323) ([raw file](https://github.com/powershell/sharepointdsc/blob/c33a0fa75707da0919ca1e51fa7903dac8c7d36a/Modules/SharePointDsc/DSCResources/MSFT_SPUserProfileServiceApp/MSFT_SPUserProfileServiceApp.psm1#L192)):*
> ```PowerShell
>     $PSBoundParameters.Ensure = $Ensure
>     $PSBoundParameters.EnableNetBIOS = $EnableNetBIOS
>     if($Ensure -eq "Present"){
> ```

Hey, just thinking about extensibility....
Shouldn't the Test-SPDSCSpecificParameters be responsible for filtering out values when not required?
I mean
For ALL modules: 
- We only need the  'Key'  When Ensure -eq "Absent"
- We should really care about ALL parameters.

So, My suggestion is to Have an option without "ValuesToCheck"(which can be $null) and when that is the case the Test-SPDSCSpecificParameters handles it differently.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/349)*

**Comment by BrianFarnhill** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPUserProfileServiceApp/MSFT_SPUserProfileServiceApp.psm1, line 139 \[r3\]](https://reviewable.io:443/reviews/powershell/sharepointdsc/349#-KLJAoq8dZs2ClIjDr_2:-KLJSBW1upFYlkozkOs5:2096865625) ([raw file](https://github.com/powershell/sharepointdsc/blob/c33a0fa75707da0919ca1e51fa7903dac8c7d36a/Modules/SharePointDsc/DSCResources/MSFT_SPUserProfileServiceApp/MSFT_SPUserProfileServiceApp.psm1#L139)):*
<details><summary><i>Previously, camiloborges (Camilo Borges) wrote…</i></summary>
> Brian, check if you agree with this. (Hey I haven't used aliases!!!!)
</details>
Actually lokking at it you should have this:

    if($app.NetBIOSDomainNamesEnabled -ne $params.EnableNetBIOS) {

Did you actually run this to make sure it worked or just write it up? :P 

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPUserProfileServiceApp/MSFT_SPUserProfileServiceApp.psm1, line 192 \[r3\]](https://reviewable.io:443/reviews/powershell/sharepointdsc/349#-KLJAwdoYFzujiEy2LYA:-KLJSS7LPjvRQ_Xx2Yvx:-28100277) ([raw file](https://github.com/powershell/sharepointdsc/blob/c33a0fa75707da0919ca1e51fa7903dac8c7d36a/Modules/SharePointDsc/DSCResources/MSFT_SPUserProfileServiceApp/MSFT_SPUserProfileServiceApp.psm1#L192)):*
<details><summary><i>Previously, camiloborges (Camilo Borges) wrote…</i></summary>
> Hey, just thinking about extensibility....
> Shouldn't the Test-SPDSCSpecificParameters be responsible for filtering out values when not required?
> I mean
> For ALL modules: 
> - We only need the  'Key'  When Ensure -eq "Absent"
> - We should really care about ALL parameters.
> 
> So, My suggestion is to Have an option without "ValuesToCheck"(which can be $null) and when that is the case the Test-SPDSCSpecificParameters handles it differently.
</details>
Not sure I follow - but either way a change to that Test-SPDscSpecificParameters method warrants discussion before touching it - so lets leave this as is for this PR and then open a new issue to discuss what you wanna do with that that one

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/349)*

**Comment by camiloborges** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPUserProfileServiceApp/MSFT_SPUserProfileServiceApp.psm1, line 139 \[r3\]](https://reviewable.io:443/reviews/powershell/sharepointdsc/349#-KLJAoq8dZs2ClIjDr_2:-KLJSsXrAZ3m5BydPRSR:-1843815952) ([raw file](https://github.com/powershell/sharepointdsc/blob/c33a0fa75707da0919ca1e51fa7903dac8c7d36a/Modules/SharePointDsc/DSCResources/MSFT_SPUserProfileServiceApp/MSFT_SPUserProfileServiceApp.psm1#L139)):*
<details><summary><i>Previously, BrianFarnhill (Brian Farnhill) wrote…</i></summary>
> Actually lokking at it you should have this:
> 
>     if($app.NetBIOSDomainNamesEnabled -ne $params.EnableNetBIOS) {
> 
> Did you actually run this to make sure it worked or just write it up? :P 
</details>
it works. I think it makes no real difference, but it means the existing Unit tests don't require massive changes, which helps from a Backward compatibility point of view. Since it is User Profile Service I am always worried about calling any method unless I really have to as I don't know what else it will do. 
I give you the this is ultra defensive code :) 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/349)*

**Comment by camiloborges** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPUserProfileServiceApp/MSFT_SPUserProfileServiceApp.psm1, line 139 \[r3\]](https://reviewable.io:443/reviews/powershell/sharepointdsc/349#-KLJAoq8dZs2ClIjDr_2:-KLJThdJ4PqolMR1AECk:2002965728) ([raw file](https://github.com/powershell/sharepointdsc/blob/c33a0fa75707da0919ca1e51fa7903dac8c7d36a/Modules/SharePointDsc/DSCResources/MSFT_SPUserProfileServiceApp/MSFT_SPUserProfileServiceApp.psm1#L139)):*
<details><summary><i>Previously, camiloborges (Camilo Borges) wrote…</i></summary>
> it works. I think it makes no real difference, but it means the existing Unit tests don't require massive changes, which helps from a Backward compatibility point of view. Since it is User Profile Service I am always worried about calling any method unless I really have to as I don't know what else it will do. 
> I give you the this is ultra defensive code :) 
</details>
I think got your point. You are saying that in DSC this won't work as I don't have the $params. Let me run this again here. I definitely ran it but I did refactor it afterwards...  I think you are correct :D

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/349)*

**Comment by BrianFarnhill** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPUserProfileServiceApp/MSFT_SPUserProfileServiceApp.psm1, line 139 \[r3\]](https://reviewable.io:443/reviews/powershell/sharepointdsc/349#-KLJAoq8dZs2ClIjDr_2:-KLPAg_Ciq3ATOfT_0cq:276867846) ([raw file](https://github.com/powershell/sharepointdsc/blob/c33a0fa75707da0919ca1e51fa7903dac8c7d36a/Modules/SharePointDsc/DSCResources/MSFT_SPUserProfileServiceApp/MSFT_SPUserProfileServiceApp.psm1#L139)):*
<details><summary><i>Previously, camiloborges (Camilo Borges) wrote…</i></summary>
> I think got your point. You are saying that in DSC this won't work as I don't have the $params. Let me run this again here. I definitely ran it but I did refactor it afterwards...  I think you are correct :D
</details>
How did you go with this mate? Got an update?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/349)*

**Comment by camiloborges** [comment]
Hey
Hello. Had an 'interesting' afternoon yesterday and couldn't be bothered with getting back to it. I made the suggested change just haven't done an integration test
Camilo Borges

Sent via iPhone while out and about

**Comment by camiloborges** [comment]
Review status: 2 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPUserProfileServiceApp/MSFT_SPUserProfileServiceApp.psm1, line 124 \[r4\]](https://reviewable.io:443/reviews/powershell/sharepointdsc/349#-KLRFzHMpw5q23jeDUiS:-KLRFzHMpw5q23jeDUiT:-1097668870) ([raw file](https://github.com/powershell/sharepointdsc/blob/fb08556091ba8cb5a291ae97cceb7645ea6ab809/Modules/SharePointDsc/DSCResources/MSFT_SPUserProfileServiceApp/MSFT_SPUserProfileServiceApp.psm1#L124)):*
> ```PowerShell
>             
>             $enableNetBIOS = $false
>             if ($params.ContainsKey("EnableNetBIOS")) { 
> ```

Brian, so the $EnableNetBIOS wasn't the issue, issue was I had deleted this IF. We need this when creating new service apps as EnableNetBIOS isn't one of the New-SpProfileServiceApp params. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/349)*

**Comment by camiloborges** [comment]
Review status: 2 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPUserProfileServiceApp/MSFT_SPUserProfileServiceApp.psm1, line 139 \[r3\]](https://reviewable.io:443/reviews/powershell/sharepointdsc/349#-KLJAoq8dZs2ClIjDr_2:-KLRGt5L0f-jLAQ0w25q:124177388) ([raw file](https://github.com/powershell/sharepointdsc/blob/c33a0fa75707da0919ca1e51fa7903dac8c7d36a/Modules/SharePointDsc/DSCResources/MSFT_SPUserProfileServiceApp/MSFT_SPUserProfileServiceApp.psm1#L139)):*
<details><summary><i>Previously, BrianFarnhill (Brian Farnhill) wrote…</i></summary>
> How did you go with this mate? Got an update?
</details>
sorry, 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/349)*

**Comment by BrianFarnhill** [comment]
Reviewed 1 of 2 files at r4, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/349)*

**Comment by BrianFarnhill** [comment]
@camiloborges Still seeing a unit test fail for the encoding on the schema file mate

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/349#-:-KLT8etS4inyawukevvb:-419789597)*

**Comment by camiloborges** [comment]
I noticed that. Will look into it in about 2 hrs.



Sent via iPhone while out and about

**Comment by BrianFarnhill** [comment]
Reviewed 3 of 3 files at r7.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[CHANGELOG.md, line 120 \[r7\]](https://reviewable.io:443/reviews/powershell/sharepointdsc/349#-KLYEIhVm6G5ttHfv8Oi:-KLYEIhVm6G5ttHfv8Oj:679400767) ([raw file](https://github.com/powershell/sharepointdsc/blob/f713e22732143422c0ee636f76a81e8f54d8d29f/CHANGELOG.md#L120)):*
> ```Markdown
> 
> * Initial public release of xSharePoint
>  
> ```

You took the empty line off the end of this one mate, we need it there

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPUserProfileServiceApp/MSFT_SPUserProfileServiceApp.schema.mof, line 0 \[r7\]](https://reviewable.io:443/reviews/powershell/sharepointdsc/349#-KLYROcof1p4u-eOime-:-KLYROcpBCbNTWCjMq2U:1746922367) ([raw file](https://github.com/powershell/sharepointdsc/blob/f713e22732143422c0ee636f76a81e8f54d8d29f/Modules/SharePointDsc/DSCResources/MSFT_SPUserProfileServiceApp/MSFT_SPUserProfileServiceApp.schema.mof#L0)):*
reviewable is showing this up as binary so I don't think the encoding is right yet either. I'm going to merge this in and then fix it myself just to end the back and forth on this one mate.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/349)*

**Comment by BrianFarnhill** [comment]
OK I think it was just reviewable that was choking on this a little - after the merge it all looks fine to me, so this one is all good.

**Pull request merged**
