### PR TITLE
Add pull request template and issue templates

### PR DESCRIPTION
**Pull request by johlju**
This is an automatic batch pull request.

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/sharepointdsc/852)

### CODE REVIEW

**Comment by johlju** [comment]
Pull-request updated, HEAD is now 204279960149deb45759e20073c8390f7253ca4d

**Comment by ykuijs** [comment]
@johlju Since this is marked as "Waiting for code fix": Is this ready for review/merge?

**Comment by johlju** [comment]
@ykuijs I thought I would get some of the SharePoint specific stuff in from the previous templates. I didn’t have time today. Hoping I have time to fix it tomorrow.

**Comment by ykuijs** [comment]
Perfect, no proble,. Then I won't review/merge right now ;-)

**Pull request merged**
