### PR TITLE
New SPConfigWizard, SPProductUpdate and SPInstallLanguagePack resources

### PR DESCRIPTION
**Pull request by ykuijs**
This PR includes two new resources:
- SPConfigWizard which checks if the Configuration Wizard is required and runs it if necessary
- SPProductUpdate which is able to install CU's, SP's and Language Pack SP's. It checks the version of an update and then determines if the specific update is required.

- [X] Change details added to Unreleased section of changelog.md?
- [X] Added/updated documentation and descriptions in .schema.mof files where appropriate?
- [X] Examples updated for both the single server and small farm templates in the examples folder?
- [X] New/changed code adheres to [Style Guidelines]?(https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md)?
- [X] [Unit and Integration tests](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md) created/updated where possible?

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/sharepointdsc/391)

### CODE REVIEW

**Comment by ykuijs** [comment]
Fixing issues #184 and partially #217. Am working on another resource to install Language Packs, but wanted to release these two resources first.

**Comment by ykuijs** [comment]
Looking into the failed Pester tests for SP16. Will submit a new commit later.

**Comment by BrianFarnhill** [comment]
Started the review, here is the feedback from the first few files

---

Reviewed 7 of 16 files at r1, 1 of 1 files at r2.
Review status: 8 of 16 files reviewed at latest revision, 19 unresolved discussions.

---

*[Modules/SharePointDsc/SharePointDsc.psd1, line 87 \[r3\]](https://reviewable.io:443/reviews/powershell/sharepointdsc/391#-KPjBiaGoNU7-lmBi2gR:-KPjBiaHQ7vn1SMZmZR9:b4oferd) ([raw file](https://github.com/powershell/sharepointdsc/blob/b0f0cc3af9e717029bb72ef3384b2e3a4fbae83e/Modules/SharePointDsc/SharePointDsc.psd1#L87)):*
> ```PowerShell
>                     "Get-SPDSCUserProfileSubTypeManager",
>                     "Get-SPDscOSVersion",
>                     "Get-SPDSCRegistryKey",
> ```

Can we add the other new methods you added to the utility module here?

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPConfigWizard/MSFT_SPConfigWizard.psm1, line 9 \[r3\]](https://reviewable.io:443/reviews/powershell/sharepointdsc/391#-KPjCSLZ6O-q4E9_5F5y:-KPjCSLZ6O-q4E9_5F5z:bajuwpi) ([raw file](https://github.com/powershell/sharepointdsc/blob/b0f0cc3af9e717029bb72ef3384b2e3a4fbae83e/Modules/SharePointDsc/DSCResources/MSFT_SPConfigWizard/MSFT_SPConfigWizard.psm1#L9)):*
> ```PowerShell
>         [parameter(Mandatory = $true)]
>         [ValidateSet("Present","Absent")]
>         [System.String] $Ensure,
> ```

Property names need to be on the line below the type, can you fix this for all of them?

    [System.String]
    $Ensure

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPConfigWizard/MSFT_SPConfigWizard.psm1, line 33 \[r3\]](https://reviewable.io:443/reviews/powershell/sharepointdsc/391#-KPjCgLaRRQQrbERUhGP:-KPjCgLaRRQQrbERUhGQ:bnw0wb2) ([raw file](https://github.com/powershell/sharepointdsc/blob/b0f0cc3af9e717029bb72ef3384b2e3a4fbae83e/Modules/SharePointDsc/DSCResources/MSFT_SPConfigWizard/MSFT_SPConfigWizard.psm1#L33)):*
> ```PowerShell
> 
>     # Read LanguagePackInstalled and SetupType registry keys
>     $languagePackInstalled = Get-SPDSCRegistryKey $wssRegKey "LanguagePackInstalled"
> ```

Can we not use positional parameters for this one? There are a few of your other ones as well that need this fixed

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPConfigWizard/MSFT_SPConfigWizard.psm1, line 45 \[r3\]](https://reviewable.io:443/reviews/powershell/sharepointdsc/391#-KPjD1S06bu-k9iqSDI2:-KPjD1S06bu-k9iqSDI3:b-umbwll) ([raw file](https://github.com/powershell/sharepointdsc/blob/b0f0cc3af9e717029bb72ef3384b2e3a4fbae83e/Modules/SharePointDsc/DSCResources/MSFT_SPConfigWizard/MSFT_SPConfigWizard.psm1#L45)):*
> ```PowerShell
>             DatabaseUpgradeTime = $DatabaseUpgradeTime
>         }
>     } else {
> ```

else needs to be on its own line, there are a couple like this too

    }
    else
    {

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPConfigWizard/MSFT_SPConfigWizard.schema.mof, line 7 \[r3\]](https://reviewable.io:443/reviews/powershell/sharepointdsc/391#-KPjE1wYG7vjfcoowsXD:-KPjE1wYG7vjfcoowsXE:b97wpdw) ([raw file](https://github.com/powershell/sharepointdsc/blob/b0f0cc3af9e717029bb72ef3384b2e3a4fbae83e/Modules/SharePointDsc/DSCResources/MSFT_SPConfigWizard/MSFT_SPConfigWizard.schema.mof#L7)):*
> ```
>     [Write, Description("Specify on which dates running the Configuration Wizard is allowed"), ValueMap{"mon","tue","wed","thu","fri","sat","sun"}, Values{"mon","tue","wed","thu","fri","sat","sun"}] String DatabaseUpgradeDays[];
>     [Write, Description("Specify in which time frame running the Configuration Wizard is allowed")] String DatabaseUpgradeTime;
>     [Write, Description("POWERSHELL 4 ONLY: The account to run this resource as, use PsDscRunAsAccount if using PowerShell 5"), EmbeddedInstance("MSFT_Credential")] String InstallAccount;
> ```

This should be PsDscRunAsCredential (not account), we fixed this in the other resources

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPConfigWizard/readme.md, line 5 \[r3\]](https://reviewable.io:443/reviews/powershell/sharepointdsc/391#-KPWCTSBj-FWMzNIWmHp:-KPWCTSBj-FWMzNIWmHq:b-icl2k1) ([raw file](https://github.com/powershell/sharepointdsc/blob/b0f0cc3af9e717029bb72ef3384b2e3a4fbae83e/Modules/SharePointDsc/DSCResources/MSFT_SPConfigWizard/readme.md#L5)):*
> ```Markdown
> This resource is used to perform the upgrade step of installing SharePoint updates, like Cumulative Updates, Service Packs and Language Packs.
> The DatabaseUpgradeDays and DatabaseUpgradeTime parameters specify a window in which the update can be installed.
> This module has to be used to complete the update installation step, performed by [SPProductUpdate](SPProductUpdate).
> ```

Can you take the link out as we don't process these well for the PowerShell help (yet)

---

*[Modules/SharePointDSC/DSCResources/MSFT_SPProductUpdate/MSFT_SPProductUpdate.psm1, line 44 \[r3\]](https://reviewable.io:443/reviews/powershell/sharepointdsc/391#-KPjFHDfpORjad6-Fo2S:-KPjFHDgSO2SV3hYJerA:b4pr6qx) ([raw file](https://github.com/powershell/sharepointdsc/blob/b0f0cc3af9e717029bb72ef3384b2e3a4fbae83e/Modules/SharePointDSC/DSCResources/MSFT_SPProductUpdate/MSFT_SPProductUpdate.psm1#L44)):*
> ```PowerShell
>     Write-Verbose "Update has version $fileVersion"
> 
>     $products = Get-SPDscFarmProductsInfo
> ```

This won't work for PowerShell 4 without passing InstallAccount. There are also a couple of calls to methods like this in this cmdlet, so why don't we wrap this cmdlet in the Invoke-SPDscCommand function rather than doing it in the child function and then passing the install account around?

---

*[Modules/SharePointDSC/DSCResources/MSFT_SPProductUpdate/MSFT_SPProductUpdate.psm1, line 64 \[r3\]](https://reviewable.io:443/reviews/powershell/sharepointdsc/391#-KPjFRC3LoufcCC4HhAL:-KPjFRC3LoufcCC4HhAM:b-lgeiuv) ([raw file](https://github.com/powershell/sharepointdsc/blob/b0f0cc3af9e717029bb72ef3384b2e3a4fbae83e/Modules/SharePointDSC/DSCResources/MSFT_SPProductUpdate/MSFT_SPProductUpdate.psm1#L64)):*
> ```PowerShell
>         try
>         {
>             $cultureInfo = New-Object System.Globalization.CultureInfo($language)
> ```

Can we not use positional arguments

    New-Object -TypeName System.Globalization.CultureInfo -ArgumentList $language

---

*[Modules/SharePointDSC/DSCResources/MSFT_SPProductUpdate/MSFT_SPProductUpdate.psm1, line 66 \[r3\]](https://reviewable.io:443/reviews/powershell/sharepointdsc/391#-KPjFcYi8e1DkNKMrN0t:-KPjFcYi8e1DkNKMrN0u:b-nxk0ty) ([raw file](https://github.com/powershell/sharepointdsc/blob/b0f0cc3af9e717029bb72ef3384b2e3a4fbae83e/Modules/SharePointDSC/DSCResources/MSFT_SPProductUpdate/MSFT_SPProductUpdate.psm1#L66)):*
> ```PowerShell
>             $cultureInfo = New-Object System.Globalization.CultureInfo($language)
>         }
>         catch {
> ```

Bracket to the next line

---

*[Modules/SharePointDSC/DSCResources/MSFT_SPProductUpdate/MSFT_SPProductUpdate.psm1, line 90 \[r3\]](https://reviewable.io:443/reviews/powershell/sharepointdsc/391#-KPjFjPF53w2fcn4joHD:-KPjFjPF53w2fcn4joHE:bbey1d7) ([raw file](https://github.com/powershell/sharepointdsc/blob/b0f0cc3af9e717029bb72ef3384b2e3a4fbae83e/Modules/SharePointDSC/DSCResources/MSFT_SPProductUpdate/MSFT_SPProductUpdate.psm1#L90)):*
> ```PowerShell
>         # Build language string used in Language Pack names
>         $languageString = "$languageEnglish/$languageNative"
>         Write-Verbose "Update is for the $languageEnglish language"
> ```

No positional parameters (there are few of this one)

    Write-Verbose -Message "Update..." 

---

*[Modules/SharePointDSC/DSCResources/MSFT_SPProductUpdate/MSFT_SPProductUpdate.psm1, line 110 \[r3\]](https://reviewable.io:443/reviews/powershell/sharepointdsc/391#-KPjG3_zGAkpIcg23BlF:-KPjG3_zGAkpIcg23BlG:b-3ns2bi) ([raw file](https://github.com/powershell/sharepointdsc/blob/b0f0cc3af9e717029bb72ef3384b2e3a4fbae83e/Modules/SharePointDSC/DSCResources/MSFT_SPProductUpdate/MSFT_SPProductUpdate.psm1#L110)):*
> ```PowerShell
>             Write-Verbose "Product found: $productName"
>         }
>         $versionInfo = Get-SPDscFarmVersionInfo $productName
> ```

Positional parameter

---

*[Modules/SharePointDSC/DSCResources/MSFT_SPProductUpdate/MSFT_SPProductUpdate.psm1, line 177 \[r3\]](https://reviewable.io:443/reviews/powershell/sharepointdsc/391#-KPjGdWMx623-Ln9qVPK:-KPjGdWMx623-Ln9qVPL:bg46fa0) ([raw file](https://github.com/powershell/sharepointdsc/blob/b0f0cc3af9e717029bb72ef3384b2e3a4fbae83e/Modules/SharePointDSC/DSCResources/MSFT_SPProductUpdate/MSFT_SPProductUpdate.psm1#L177)):*
> ```PowerShell
>     )
> 
>     if ($Ensure -eq "Absent") {
> ```

Bracket on new line

---

*[Modules/SharePointDSC/DSCResources/MSFT_SPProductUpdate/MSFT_SPProductUpdate.psm1, line 348 \[r3\]](https://reviewable.io:443/reviews/powershell/sharepointdsc/391#-KPjGvo1ckWa8ZdaITtq:-KPjGvo1ckWa8ZdaITtr:biqlr5) ([raw file](https://github.com/powershell/sharepointdsc/blob/b0f0cc3af9e717029bb72ef3384b2e3a4fbae83e/Modules/SharePointDSC/DSCResources/MSFT_SPProductUpdate/MSFT_SPProductUpdate.psm1#L348)):*
> ```PowerShell
>                                -PassThru
> 
>         # Error codes: https://technet.microsoft.com/en-us/library/cc179058%28v=office.14%29.aspx?f=255&MSPPError=-2147217396
> ```

Can we create a http://aka.ms link for this and include it in the default error message?

---

*[Modules/SharePointDSC/DSCResources/MSFT_SPProductUpdate/MSFT_SPProductUpdate.psm1, line 381 \[r3\]](https://reviewable.io:443/reviews/powershell/sharepointdsc/391#-KPjH6Xwq6irER7AlQK8:-KPjH6Xwq6irER7AlQK9:bsl244x) ([raw file](https://github.com/powershell/sharepointdsc/blob/b0f0cc3af9e717029bb72ef3384b2e3a4fbae83e/Modules/SharePointDSC/DSCResources/MSFT_SPProductUpdate/MSFT_SPProductUpdate.psm1#L381)):*
> ```PowerShell
>                                   -PassThru
> 
>         $osearchSvc        = Get-Service "OSearch15" 
> ```

Positional parameters

---

*[Modules/SharePointDSC/DSCResources/MSFT_SPProductUpdate/MSFT_SPProductUpdate.psm1, line 442 \[r3\]](https://reviewable.io:443/reviews/powershell/sharepointdsc/391#-KPjHD4R4e6zRal3uOER:-KPjHD4R4e6zRal3uOES:b6c41q4) ([raw file](https://github.com/powershell/sharepointdsc/blob/b0f0cc3af9e717029bb72ef3384b2e3a4fbae83e/Modules/SharePointDSC/DSCResources/MSFT_SPProductUpdate/MSFT_SPProductUpdate.psm1#L442)):*
> ```PowerShell
>     )
> 
>     if ($Ensure -eq "Absent") {
> ```

Bracket to new line

---

*[Modules/SharePointDSC/DSCResources/MSFT_SPProductUpdate/MSFT_SPProductUpdate.schema.mof, line 9 \[r3\]](https://reviewable.io:443/reviews/powershell/sharepointdsc/391#-KPjEkW9Q9dfT5LG0Tte:-KPjEkW9Q9dfT5LG0Ttf:b-lhij5) ([raw file](https://github.com/powershell/sharepointdsc/blob/b0f0cc3af9e717029bb72ef3384b2e3a4fbae83e/Modules/SharePointDSC/DSCResources/MSFT_SPProductUpdate/MSFT_SPProductUpdate.schema.mof#L9)):*
> ```
>     [Write, Description("Specify in which time frame the installation is allowed")] String BinaryInstallTime;
>     [Write, Description("Present to install SharePoint. Absent is currently not supported"), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] string Ensure;
>     [Write, Description("POWERSHELL 4 ONLY: The account to run this resource as, use PsDscRunAsAccount if using PowerShell 5"), EmbeddedInstance("MSFT_Credential")] String InstallAccount;
> ```

Same again for PsDscRunAsCredential

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPProductUpdate/readme.md, line 5 \[r3\]](https://reviewable.io:443/reviews/powershell/sharepointdsc/391#-KPjEt10KEXHZ-5S62fW:-KPjEt11RH2Olku5uwxo:b-g6i0lq) ([raw file](https://github.com/powershell/sharepointdsc/blob/b0f0cc3af9e717029bb72ef3384b2e3a4fbae83e/Modules/SharePointDsc/DSCResources/MSFT_SPProductUpdate/readme.md#L5)):*
> ```Markdown
> This resource is used to perform the update step of installing SharePoint updates, like Cumulative Updates and Service Packs.
> The SetupFile parameter should point to the update file.
> The ShutdownServices parameter is used to indicate if some services have to be stopped before installation of the update. 
> ```

I would like a better description of what gets shut down and why/when you should use this.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPProductUpdate/readme.md, line 7 \[r3\]](https://reviewable.io:443/reviews/powershell/sharepointdsc/391#-KPjEzYFKPQ2o6zcII2n:-KPjEzYFKPQ2o6zcII2o:btpv12i) ([raw file](https://github.com/powershell/sharepointdsc/blob/b0f0cc3af9e717029bb72ef3384b2e3a4fbae83e/Modules/SharePointDsc/DSCResources/MSFT_SPProductUpdate/readme.md#L7)):*
> ```Markdown
> The ShutdownServices parameter is used to indicate if some services have to be stopped before installation of the update. 
> The BinaryInstallDays and BinaryInstallTime parameters specify a window in which the update can be installed.
> This module requires the Configuration Wizard resource to fully complete the installation of the update, which can be done through the use of [SPConfigWizard](SPConfigWizard).
> ```

Again with the link removal

---

*[Modules/SharePointDsc/Modules/SharePointDsc.Util/SharePointDsc.Util.psm1, line 48 \[r3\]](https://reviewable.io:443/reviews/powershell/sharepointdsc/391#-KPjEZz-RJFlqpB510vd:-KPjEZz-RJFlqpB510ve:bnhaghr) ([raw file](https://github.com/powershell/sharepointdsc/blob/b0f0cc3af9e717029bb72ef3384b2e3a4fbae83e/Modules/SharePointDsc/Modules/SharePointDsc.Util/SharePointDsc.Util.psm1#L48)):*
> ```PowerShell
>     )
> 
>     $result = Invoke-SPDSCCommand -Credential $InstallAccount `
> ```

You don't pass $InstallAccount in here so it won't work for PowerShell 4

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/391#-:-KPjHKNW0l2dcolqBVWO:b3dz96p)*

**Comment by ykuijs** [comment]
Incorporated comments. Will push a new commit is a few minutes.

---

Review status: 8 of 16 files reviewed at latest revision, 19 unresolved discussions.

---

*[Modules/SharePointDSC/DSCResources/MSFT_SPProductUpdate/MSFT_SPProductUpdate.psm1, line 44 \[r3\]](https://reviewable.io:443/reviews/powershell/sharepointdsc/391#-KPjFHDfpORjad6-Fo2S:-KPqV9HOLpXmwkH826hG:b4uhqe1) ([raw file](https://github.com/powershell/sharepointdsc/blob/b0f0cc3af9e717029bb72ef3384b2e3a4fbae83e/Modules/SharePointDSC/DSCResources/MSFT_SPProductUpdate/MSFT_SPProductUpdate.psm1#L44)):*
> PsDscRunAsCredential
Good catch and good suggestion! Did the change.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/391#-:-KPqZoCOL8euTJCPRNDB:br70p7b)*

**Comment by ykuijs** [comment]
I have added a new SPInstallLanguagePack resource to this PR. With these three new resources you are able to install Language Packs, Service Packs (for SharePoint and Language Packs) and Cumulative Updates and run the Configuration Wizard via SharePointDSC

**Comment by BrianFarnhill** [comment]
Reviewed 6 of 16 files at r1, 1 of 1 files at r3, 14 of 15 files at r4, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPInstallLanguagePack/MSFT_SPInstallLanguagePack.psm1, line 33 \[r5\]](https://reviewable.io:443/reviews/powershell/sharepointdsc/391#-KPyg5Kus-H-wAvF6DSL:-KPyg5KvklBbBecwv20L:b7sg1r8) ([raw file](https://github.com/powershell/sharepointdsc/blob/38b16aa9f0faf6ecd171d9abcfbd7c5d25479588/Modules/SharePointDsc/DSCResources/MSFT_SPInstallLanguagePack/MSFT_SPInstallLanguagePack.psm1#L33)):*
> ```PowerShell
> 
>     # Check if Binary folder exists
>     if (-not(Test-Path $BinaryDir))
> ```

No positional parameters


    Test-Path -Path $BinaryDir

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPInstallLanguagePack/MSFT_SPInstallLanguagePack.psm1, line 38 \[r5\]](https://reviewable.io:443/reviews/powershell/sharepointdsc/391#-KPygCTcWXKzhL-a22As:-KPygCTcWXKzhL-a22At:b-lvby4k) ([raw file](https://github.com/powershell/sharepointdsc/blob/38b16aa9f0faf6ecd171d9abcfbd7c5d25479588/Modules/SharePointDsc/DSCResources/MSFT_SPInstallLanguagePack/MSFT_SPInstallLanguagePack.psm1#L38)):*
> ```PowerShell
>     }
> 
>     $osrvFolder = Get-ChildItem (Join-Path $BinaryDir "\osrv*.*")
> ```

No positional parameters

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPInstallLanguagePack/MSFT_SPInstallLanguagePack.psm1, line 274 \[r5\]](https://reviewable.io:443/reviews/powershell/sharepointdsc/391#-KPyi6fbRDHyBLZz3wup:-KPyi6fbRDHyBLZz3wuq:b-jin1vc) ([raw file](https://github.com/powershell/sharepointdsc/blob/38b16aa9f0faf6ecd171d9abcfbd7c5d25479588/Modules/SharePointDsc/DSCResources/MSFT_SPInstallLanguagePack/MSFT_SPInstallLanguagePack.psm1#L274)):*
> ```PowerShell
>     <Setting Id=`"OSERVERLPK`" Value=`"1`"/>
>     <Setting Id=`"USINGUIINSTALLMODE`" Value=`"0`"/>
>     <Logging Type=`"verbose`" Path=`"%temp%`" Template=`"SharePoint 2013  Products Language Pack Setup(*).log`"/>
> ```

Can we change the file name from 2013 to be something based on the version we know is installed?

---

*[Modules/SharePointDsc/Modules/SharePointDsc.Util/SharePointDsc.Util.psm1, line 107 \[r5\]](https://reviewable.io:443/reviews/powershell/sharepointdsc/391#-KPyvO2y-z0lJD1b6-uZ:-KPyvO2zgqJN7PVbLln0:b-gfg7c) ([raw file](https://github.com/powershell/sharepointdsc/blob/38b16aa9f0faf6ecd171d9abcfbd7c5d25479588/Modules/SharePointDsc/Modules/SharePointDsc.Util/SharePointDsc.Util.psm1#L107)):*
> ```PowerShell
>                     else
>                     {
>                         if ($currentversion -lt $versionInfo.Lowest) {
> ```

Bracket on new line here

---

*[Modules/SharePointDsc/Modules/SharePointDsc.Util/SharePointDsc.Util.psm1, line 142 \[r5\]](https://reviewable.io:443/reviews/powershell/sharepointdsc/391#-KPyx5khTQDfic3Q7dtr:-KPyx5khTQDfic3Q7dts:b-6ti5m3) ([raw file](https://github.com/powershell/sharepointdsc/blob/38b16aa9f0faf6ecd171d9abcfbd7c5d25479588/Modules/SharePointDsc/Modules/SharePointDsc.Util/SharePointDsc.Util.psm1#L142)):*
> ```PowerShell
>     )
> 
>     if ((Test-Path $Key) -eq $true)
> ```

Positional parameter used here

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/391)*

**Comment by BrianFarnhill** [comment]
Almost there, one last fix and I think we are good

---

Reviewed 3 of 3 files at r6.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPInstallLanguagePack/MSFT_SPInstallLanguagePack.psm1, line 38 \[r6\]](https://reviewable.io:443/reviews/powershell/sharepointdsc/391#-KQNIvnvxuQLfYH58xhJ:-KQNIvnvxuQLfYH58xhK:b-gbvr7q) ([raw file](https://github.com/powershell/sharepointdsc/blob/b3d2c60e640b956b0c7ab1f5a3c467f9245ae57f/Modules/SharePointDsc/DSCResources/MSFT_SPInstallLanguagePack/MSFT_SPInstallLanguagePack.psm1#L38)):*
> ```PowerShell
>     }
> 
>     $osrvFolder = Get-ChildItem (Join-Path -Path $BinaryDir `
> ```

Still using a positional parameter for Get-ChildItem here

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/391#-:-KQNJC5simp02y2CBGd7:bmev3ct)*

**Comment by ykuijs** [comment]
@BrianFarnhill Ok, last comment processed, all ready for the merge!

**Comment by BrianFarnhill** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/391#-:-KQSn6GDsjuMZRQwVahE:bnfp4nl)*

**Pull request merged**
