### PR TITLE
Patch invoke sp dsc command memory leak

### LINKED ISSUE #1037: Invoke-SPDSCCommand in SharePointDsc.Util.psm1 memory leak
#### Details of the scenario you tried and the problem that is occurring
I was using 2.3.0.0 version before upgrading my test environnment to 3.2.0.0
After upgrading to 3.2.0.0 I noticed an issue where my sharepoint servers would run out of memory after a couple of hours (arround 10 hours).
This happened even if the SharepointDsc module had no modification to the existing environment.
We have a very high configuration check frequency on test environment (every 15 minutes) to have the results of configuration changes very quickly.
Running the following powershell command would show many wsmprovhost.exe processes which are an indication of many powershell sessions running on the machine:
Get-Process -Name wsmprovhost

#### Suggested solution to the issue
After doing some debug, I found that the function Invoke-SPDSCCommand of the SharepointDsc.Util module was never removing the powershell session as it was the case before in my 2.3.0.0 version.
It looks like it is a wrong copy/paste of the section with local credential (which does not use a powershell) to the section where the powershell was in used which causes the issue.
Simply putting the results of the invoke-command in a variable, removing the powershell session, and then returning the result corrects the issue.
I will issue a pull request to correct this.
#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
Many configurations will have the issue as to test the compliance, many of them use an invoke-spdsccommand with credentials, thus launching a "local" remote powershell session which is never closed
Most of production environments will not see the issue as the configuration check frequency is probably higher than 15 minutes and the Invoke-SPDSCCommand as an idle timeout set to 60000. So the wsmprovhost process will mostly be killed before causing a memory issue.

# insert configuration here
```

#### The operating system the target node is running
OsName               : Microsoft Windows Server 2016 Datacenter
OsOperatingSystemSKU : DatacenterServerEdition
OsArchitecture       : 64-bit
WindowsBuildLabEx    : 14393.2485.amd64fre.rs1_release.180827-1809
OsLanguage           : en-US
OsMuiLanguages       : {en-US}

#### Version of SharePoint that is used (e.g. SharePoint 2016)
SharePoint 2016
#### Version and build of PowerShell the target node is running
Name                           Value                                                                                                    
----                           -----                                                                                                    
PSVersion                      5.1.14393.2485                                                                                           
PSEdition                      Desktop                                                                                                  
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                  
BuildVersion                   10.0.14393.2485                                                                                          
CLRVersion                     4.0.30319.42000                                                                                          
WSManStackVersion              3.0                                                                                                      
PSRemotingProtocolVersion      2.3                                                                                                      
SerializationVersion           1.1.0.1      

#### Version of the DSC module that was used ('dev' if using current dev branch)
3.2.0.0 dev branch

### PR DESCRIPTION
**Pull request by adruet29**
#### Pull Request (PR) description

Corrected the issue in order to remove-pssession and avoid memory leak from the Invoke-SPDSCCommand function in SharePointDsc.Util.psm1

#### This Pull Request (PR) fixes the following issues
Fixes #1037
#### Task list
- [x ] Added an entry under the Unreleased section of the change log in the CHANGELOG.md.
      Entry should say what was changed, and how that affects users (if applicable).
- [ ] Resource documentation added/updated in README.md in the resource folder.
- [ ] Resource parameter descriptions added/updated in schema.mof
      and comment-based help.
- [ ] Comment-based help added/updated.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [ ] Examples appropriately added/updated.
- [ ] Unit tests added/updated. See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] Integration tests added/updated (where possible). See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ x] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/sharepointdsc/1038)

### CODE REVIEW

**Comment by ykuijs** [comment]
You change to the Changelog.md file has an issue:
CHANGELOG.md: 6: MD013/line-length Line length [Expected: 80; Actual: 86]

Please make sure the line is split across multiple lines.

**Comment by adruet29** [comment]
Yes sorry about that, just saw the appveyor report. I corrected the line in the changelog to be under the 80 characters per line. I just committed the change, it should be ok.

**Comment by adruet29** [comment]
appveryor still reports  12 failed tests, but according to what I understand, it does not seem related to my modifications:
Error-Level PSSA rule(s) did not pass.
The following PSScriptAnalyzer rule 'PSDSCUseIdenticalMandatoryParametersForDSC' errors need to be fixed:
MSFT_SPSearchContentSource.psm1 (Line 1): The 'Required' parameter 'ScheduleType' is not present in 'Get-TargetResource' DSC resource function(s).
MSFT_SPSearchContentSource.psm1 (Line 219): The 'Required' parameter 'ScheduleType' is not present in 'Set-TargetResource' DSC resource function(s).
MSFT_SPSearchContentSource.psm1 (Line 683): The 'Required' parameter 'ScheduleType' is not present in 'Test-TargetResource' DSC resource function(s).
For instructions on how to run PSScriptAnalyzer on your own machine, please go to https://github.com/powershell/PSScriptAnalyzer
      [-] Should pass all error-level PS Script Analyzer rules 105ms
        Expected $null, but got @(Microsoft.Windows.PowerShell.ScriptAnalyzer.Generic.DiagnosticRecord, Microsoft.Windows.PowerShell.ScriptAnalyzer.Generic.DiagnosticRecord, Microsoft.Windows.PowerShell.ScriptAnalyzer.Generic.DiagnosticRecord).
        482:                     $errorPssaRulesOutput | Should -Be $null
        at <ScriptBlock>, C:\projects\sharepointdsc\Modules\SharePointDsc\DSCResource.Tests\Meta.Tests.ps1: line 482

I will look into it on monday.

**Comment by ykuijs** [comment]
I think that this has something to do with the new release of PSScriptAnalyzer. They released a new version three days ago.

The errors you are encountering are referring to subclasses, which should not be used in the *-TargetResource methods.

**Comment by ykuijs** [comment]
Raised an issue in PSSA (https://github.com/PowerShell/PSScriptAnalyzer/issues/1192) and DscResource.Tests (https://github.com/PowerShell/DscResource.Tests/issues/317)

**Comment by ykuijs** [comment]
I have a workaround what I will implement and merge. After that you can sync your branch with Dev and (hopefully :-) all tests will then pass.

**Comment by ykuijs** [comment]
PR submitted. I will merge it once all tests have completed. After that you can update your branch from Dev

**Comment by ykuijs** [comment]
PR merged. Can you pull from Dev and resolve the merge conflict in the Changelog?

**Comment by ykuijs** [comment]
Yes, that did the trick!

One question. In PR #1042 @sguilbault-sherweb submitted pretty much the same fix, if I am not mistaking. However, there just the finally keyword was added. Isn't that a better solution than what you have implemented here? The finally block is always executed, even if the try block contains a return keyword.

**Comment by adruet29** [comment]
Yes, the finally block in PR #1042 is way cleaner !

**Comment by ykuijs** [comment]
Ok, great! Will close this PR and merge the other one. Thanks for your help!

**Pull request closed without merging**
