### PR TITLE
Rollup bugfix including some more breaking changes

### PR DESCRIPTION
**Pull request by ykuijs**
Fixes for issues #648, #646, #634, #639, #620, #603, #571, #597, #638, #496, #324 

Breaking changes: #644, #550 and #423

- [X] Change details added to Unreleased section of changelog.md?
- [X] Added/updated documentation and descriptions in .schema.mof files where appropriate?
- [X] Examples updated for both the single server and small farm templates in the examples folder?
- [X] New/changed code adheres to [Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md)?
- [X] [Unit and Integration tests](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md) created/updated where possible?

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/sharepointdsc/660)

### CODE REVIEW

**Comment by ykuijs** [comment]
Review for initial review, I will add some small changes later.

**Comment by ykuijs** [comment]
Ok, PR is ready for review!

**Comment by ykuijs** [comment]
This PR will also solve issue #528

**Comment by BrianFarnhill** [comment]
Well, that was a monster of a review! Notes are below, but the large majority of it is fine - just a few little things to clean up. 

---

Reviewed 234 of 234 files at r1.
Review status: all files reviewed at latest revision, 11 unresolved discussions.

---

*[Modules/SharePointDsc/SharePointDsc.psd1, line 15 at r1](https://reviewable.io:443/reviews/powershell/sharepointdsc/660#-Kw2DL8sUsTJZUZQiOW-:-Kw2DL8sUsTJZUZQiOW0:b-nakp9f) ([raw file](https://github.com/powershell/sharepointdsc/blob/42a7f15bc588ed1ce157205128e46b0b95824c25/Modules/SharePointDsc/SharePointDsc.psd1#L15)):*
> ```PowerShell
> 
> # Version number of this module.
> ModuleVersion = '1.9.0.0'
> ```

This should be 2.0 since we are hitting that branch

---

*[Modules/SharePointDsc/SharePointDsc.psd1, line 129 at r1](https://reviewable.io:443/reviews/powershell/sharepointdsc/660#-Kw2DNor0g2rwiBnGnzD:-Kw2DNor0g2rwiBnGnzE:bqk7qss) ([raw file](https://github.com/powershell/sharepointdsc/blob/eb7586a743ae661d3075b53e7ba1c2e448cc7270/Modules/SharePointDsc/SharePointDsc.psd1#L129)):*
> ```PowerShell
>         # ReleaseNotes of this module
>         ReleaseNotes = "
> * Update SPSearchIndexPartition made ServiceAppName as a Key
> ```

This should also be the 2.0 changes, but we can pick this up in the release branch before we drop it out so I'm less worried about this one.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPAlternateUrl/MSFT_SPAlternateUrl.schema.mof, line 6 at r1](https://reviewable.io:443/reviews/powershell/sharepointdsc/660#-Kw2F2hRtfrJ30FULphm:-Kw2F2hRtfrJ30FULphn:beqrkuv) ([raw file](https://github.com/powershell/sharepointdsc/blob/42a7f15bc588ed1ce157205128e46b0b95824c25/Modules/SharePointDsc/DSCResources/MSFT_SPAlternateUrl/MSFT_SPAlternateUrl.schema.mof#L6)):*
> ```
>     [Key, Description("The name of the web application to apply the alternate URL to")] String WebAppName;
>     [Key, Description("The Zone to use for the alternate URL"), ValueMap{"Default","Intranet","Extranet","Custom","Internet"}, Values{"Default","Intranet","Extranet","Custom","Internet"}] String Zone;
>     [Key, Description("The new alternate URL")] String Url;
> ```

Should this one be a key? or just required? If its a key it means I could put in a resource that has the same web app Name and zone, but because it has a different URL it would overwrite a resource in the same config technically, whereas if it was required you could only do the same web app name/zone combination once per config. 

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPTimerJobState/MSFT_SPTimerJobState.psm1, line 97 at r1](https://reviewable.io:443/reviews/powershell/sharepointdsc/660#-Kw2WsvdICmImAz0FQ7y:-Kw2WsvdICmImAz0FQ7z:b-qjz9g3) ([raw file](https://github.com/powershell/sharepointdsc/blob/42a7f15bc588ed1ce157205128e46b0b95824c25/Modules/SharePointDsc/DSCResources/MSFT_SPTimerJobState/MSFT_SPTimerJobState.psm1#L97)):*
> ```PowerShell
>             else
>             {
>                 Write-Verbose -Message ("$($timerjob.Count) timer jobs found. Check input " + `
> ```

I would rather throw this as an exception than return null. If we can't return the current state of the object for any reason, we should be throwing. Returning null shouldn't ever happen.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPTimerJobState/MSFT_SPTimerJobState.psm1, line 180 at r1](https://reviewable.io:443/reviews/powershell/sharepointdsc/660#-Kw2YyFQWnZOSBo4mFzc:-Kw2YyFQWnZOSBo4mFzd:b-6t8j9c) ([raw file](https://github.com/powershell/sharepointdsc/blob/42a7f15bc588ed1ce157205128e46b0b95824c25/Modules/SharePointDsc/DSCResources/MSFT_SPTimerJobState/MSFT_SPTimerJobState.psm1#L180)):*
> ```PowerShell
>                     try 
>                     {
>                         Set-SPTimerJob $timerjob -Schedule $params.Schedule -ErrorAction Stop
> ```

Positional parameter use here needs to be fixed

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPTimerJobState/MSFT_SPTimerJobState.psm1, line 184 at r1](https://reviewable.io:443/reviews/powershell/sharepointdsc/660#-Kw2YHUmGNRfEVwsxY-3:-Kw2YHUmGNRfEVwsxY-4:bzel9jz) ([raw file](https://github.com/powershell/sharepointdsc/blob/42a7f15bc588ed1ce157205128e46b0b95824c25/Modules/SharePointDsc/DSCResources/MSFT_SPTimerJobState/MSFT_SPTimerJobState.psm1#L184)):*
> ```PowerShell
>                     catch 
>                     {
>                         if ($_.Exception.Message -like `
> ```

Any chance there is a specific exception type we can test for instead of just the text on it? If it's a general exception type that's fine, we can leave this as it is. But I would rather test for the type as that makes this would then work in multi-lingual scenarios.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPTimerJobState/MSFT_SPTimerJobState.psm1, line 208 at r1](https://reviewable.io:443/reviews/powershell/sharepointdsc/660#-Kw2YwTzEVD2dVsg-_5y:-Kw2YwTzEVD2dVsg-_5z:b-6t8j9c) ([raw file](https://github.com/powershell/sharepointdsc/blob/42a7f15bc588ed1ce157205128e46b0b95824c25/Modules/SharePointDsc/DSCResources/MSFT_SPTimerJobState/MSFT_SPTimerJobState.psm1#L208)):*
> ```PowerShell
>                         try 
>                         {
>                             Enable-SPTimerJob $timerjob
> ```

Positional parameter use here needs to be fixed

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPTimerJobState/MSFT_SPTimerJobState.psm1, line 222 at r1](https://reviewable.io:443/reviews/powershell/sharepointdsc/660#-Kw2YvbcymjHHh7l-CRR:-Kw2YvbcymjHHh7l-CRS:b-6t8j9c) ([raw file](https://github.com/powershell/sharepointdsc/blob/42a7f15bc588ed1ce157205128e46b0b95824c25/Modules/SharePointDsc/DSCResources/MSFT_SPTimerJobState/MSFT_SPTimerJobState.psm1#L222)):*
> ```PowerShell
>                         try 
>                         {
>                             Disable-SPTimerJob $timerjob
> ```

Positional parameter use here needs to be fixed

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPTimerJobState/MSFT_SPTimerJobState.psm1, line 245 at r1](https://reviewable.io:443/reviews/powershell/sharepointdsc/660#-Kw2Yrurym-Sup1H_R1I:-Kw2Yrurym-Sup1H_R1J:b-6t8j9c) ([raw file](https://github.com/powershell/sharepointdsc/blob/42a7f15bc588ed1ce157205128e46b0b95824c25/Modules/SharePointDsc/DSCResources/MSFT_SPTimerJobState/MSFT_SPTimerJobState.psm1#L245)):*
> ```PowerShell
>                         try 
>                         {
>                             Set-SPTimerJob $timerjob -Schedule $params.Schedule -ErrorAction Stop
> ```

Positional parameter use here needs to be fixed

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPTimerJobState/MSFT_SPTimerJobState.psm1, line 273 at r1](https://reviewable.io:443/reviews/powershell/sharepointdsc/660#-Kw2YmbCVO3jMQqwaG9b:-Kw2YmbCVO3jMQqwaG9c:b-6t8j9c) ([raw file](https://github.com/powershell/sharepointdsc/blob/42a7f15bc588ed1ce157205128e46b0b95824c25/Modules/SharePointDsc/DSCResources/MSFT_SPTimerJobState/MSFT_SPTimerJobState.psm1#L273)):*
> ```PowerShell
>                             try 
>                             {
>                                 Enable-SPTimerJob $timerjob
> ```

Positional parameter use here needs to be fixed

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPTimerJobState/MSFT_SPTimerJobState.psm1, line 286 at r1](https://reviewable.io:443/reviews/powershell/sharepointdsc/660#-Kw2Z2dJHs9lk4UHGKe9:-Kw2Z2dJHs9lk4UHGKeA:b-6t8j9c) ([raw file](https://github.com/powershell/sharepointdsc/blob/42a7f15bc588ed1ce157205128e46b0b95824c25/Modules/SharePointDsc/DSCResources/MSFT_SPTimerJobState/MSFT_SPTimerJobState.psm1#L286)):*
> ```PowerShell
>                             try 
>                             {
>                                 Disable-SPTimerJob $timerjob
> ```

Positional parameter use here needs to be fixed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/660#-:-Kw2cH1hsCZ-_WFLESUI:b-k897r9)*

**Comment by ykuijs** [comment]
Comments incorporated

---

Review status: all files reviewed at latest revision, 11 unresolved discussions.

---

*[Modules/SharePointDsc/SharePointDsc.psd1, line 15 at r1](https://reviewable.io:443/reviews/powershell/sharepointdsc/660#-Kw2DL8sUsTJZUZQiOW-:-Kw4Zll-SHwNDptUEvGb:b-qf662u) ([raw file](https://github.com/powershell/sharepointdsc/blob/42a7f15bc588ed1ce157205128e46b0b95824c25/Modules/SharePointDsc/SharePointDsc.psd1#L15)):*
<details><summary><i>Previously, BrianFarnhill (Brian Farnhill) wrote…</i></summary><blockquote>

This should be 2.0 since we are hitting that branch
</blockquote></details>

Can change this of course, but isn't this usually part of the release PR

---

*[Modules/SharePointDsc/SharePointDsc.psd1, line 129 at r1](https://reviewable.io:443/reviews/powershell/sharepointdsc/660#-Kw2DNor0g2rwiBnGnzD:-Kw4ZscqC-7pIS3xZ-Uh:b-qf662u) ([raw file](https://github.com/powershell/sharepointdsc/blob/eb7586a743ae661d3075b53e7ba1c2e448cc7270/Modules/SharePointDsc/SharePointDsc.psd1#L129)):*
<details><summary><i>Previously, BrianFarnhill (Brian Farnhill) wrote…</i></summary><blockquote>

This should also be the 2.0 changes, but we can pick this up in the release branch before we drop it out so I'm less worried about this one.
</blockquote></details>

Can change this of course, but isn't this usually part of the release PR

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPAlternateUrl/MSFT_SPAlternateUrl.schema.mof, line 6 at r1](https://reviewable.io:443/reviews/powershell/sharepointdsc/660#-Kw2F2hRtfrJ30FULphm:-Kw4ZujV4yzoeieErvV_:bo00lkj) ([raw file](https://github.com/powershell/sharepointdsc/blob/42a7f15bc588ed1ce157205128e46b0b95824c25/Modules/SharePointDsc/DSCResources/MSFT_SPAlternateUrl/MSFT_SPAlternateUrl.schema.mof#L6)):*
<details><summary><i>Previously, BrianFarnhill (Brian Farnhill) wrote…</i></summary><blockquote>

Should this one be a key? or just required? If its a key it means I could put in a resource that has the same web app Name and zone, but because it has a different URL it would overwrite a resource in the same config technically, whereas if it was required you could only do the same web app name/zone combination once per config. 
</blockquote></details>

This needs to be key, else you would not be able to add an Internal URL to a web app, since the WebAppName and Zone would be identical.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPTimerJobState/MSFT_SPTimerJobState.psm1, line 97 at r1](https://reviewable.io:443/reviews/powershell/sharepointdsc/660#-Kw2WsvdICmImAz0FQ7y:-Kw4aUBao_tsuq0LnMU_:b-896fix) ([raw file](https://github.com/powershell/sharepointdsc/blob/42a7f15bc588ed1ce157205128e46b0b95824c25/Modules/SharePointDsc/DSCResources/MSFT_SPTimerJobState/MSFT_SPTimerJobState.psm1#L97)):*
<details><summary><i>Previously, BrianFarnhill (Brian Farnhill) wrote…</i></summary><blockquote>

I would rather throw this as an exception than return null. If we can't return the current state of the object for any reason, we should be throwing. Returning null shouldn't ever happen.
</blockquote></details>

Done.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPTimerJobState/MSFT_SPTimerJobState.psm1, line 180 at r1](https://reviewable.io:443/reviews/powershell/sharepointdsc/660#-Kw2YyFQWnZOSBo4mFzc:-Kw4bcJd6VaaAfsVEd3h:b-896fix) ([raw file](https://github.com/powershell/sharepointdsc/blob/42a7f15bc588ed1ce157205128e46b0b95824c25/Modules/SharePointDsc/DSCResources/MSFT_SPTimerJobState/MSFT_SPTimerJobState.psm1#L180)):*
<details><summary><i>Previously, BrianFarnhill (Brian Farnhill) wrote…</i></summary><blockquote>

Positional parameter use here needs to be fixed
</blockquote></details>

Done.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPTimerJobState/MSFT_SPTimerJobState.psm1, line 184 at r1](https://reviewable.io:443/reviews/powershell/sharepointdsc/660#-Kw2YHUmGNRfEVwsxY-3:-Kw4jJk5MAKqXs_vKbJJ:bhmo3f1) ([raw file](https://github.com/powershell/sharepointdsc/blob/42a7f15bc588ed1ce157205128e46b0b95824c25/Modules/SharePointDsc/DSCResources/MSFT_SPTimerJobState/MSFT_SPTimerJobState.psm1#L184)):*
<details><summary><i>Previously, BrianFarnhill (Brian Farnhill) wrote…</i></summary><blockquote>

Any chance there is a specific exception type we can test for instead of just the text on it? If it's a general exception type that's fine, we can leave this as it is. But I would rather test for the type as that makes this would then work in multi-lingual scenarios.
</blockquote></details>

Unfortunately not. The Exception type is Microsoft.SharePoint.PowerShell.SPCmdletException, which is a generic exception.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPTimerJobState/MSFT_SPTimerJobState.psm1, line 208 at r1](https://reviewable.io:443/reviews/powershell/sharepointdsc/660#-Kw2YwTzEVD2dVsg-_5y:-Kw4bjTMaQzh66IKowtO:b-896fix) ([raw file](https://github.com/powershell/sharepointdsc/blob/42a7f15bc588ed1ce157205128e46b0b95824c25/Modules/SharePointDsc/DSCResources/MSFT_SPTimerJobState/MSFT_SPTimerJobState.psm1#L208)):*
<details><summary><i>Previously, BrianFarnhill (Brian Farnhill) wrote…</i></summary><blockquote>

Positional parameter use here needs to be fixed
</blockquote></details>

Done.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPTimerJobState/MSFT_SPTimerJobState.psm1, line 222 at r1](https://reviewable.io:443/reviews/powershell/sharepointdsc/660#-Kw2YvbcymjHHh7l-CRR:-Kw4bpEtdvzr6qL0csnM:b-896fix) ([raw file](https://github.com/powershell/sharepointdsc/blob/42a7f15bc588ed1ce157205128e46b0b95824c25/Modules/SharePointDsc/DSCResources/MSFT_SPTimerJobState/MSFT_SPTimerJobState.psm1#L222)):*
<details><summary><i>Previously, BrianFarnhill (Brian Farnhill) wrote…</i></summary><blockquote>

Positional parameter use here needs to be fixed
</blockquote></details>

Done.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPTimerJobState/MSFT_SPTimerJobState.psm1, line 245 at r1](https://reviewable.io:443/reviews/powershell/sharepointdsc/660#-Kw2Yrurym-Sup1H_R1I:-Kw4bl1nc_-ElmwJv7Uv:b-896fix) ([raw file](https://github.com/powershell/sharepointdsc/blob/42a7f15bc588ed1ce157205128e46b0b95824c25/Modules/SharePointDsc/DSCResources/MSFT_SPTimerJobState/MSFT_SPTimerJobState.psm1#L245)):*
<details><summary><i>Previously, BrianFarnhill (Brian Farnhill) wrote…</i></summary><blockquote>

Positional parameter use here needs to be fixed
</blockquote></details>

Done.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPTimerJobState/MSFT_SPTimerJobState.psm1, line 273 at r1](https://reviewable.io:443/reviews/powershell/sharepointdsc/660#-Kw2YmbCVO3jMQqwaG9b:-Kw4bwSiuI1SZ9zsUc9D:b-896fix) ([raw file](https://github.com/powershell/sharepointdsc/blob/42a7f15bc588ed1ce157205128e46b0b95824c25/Modules/SharePointDsc/DSCResources/MSFT_SPTimerJobState/MSFT_SPTimerJobState.psm1#L273)):*
<details><summary><i>Previously, BrianFarnhill (Brian Farnhill) wrote…</i></summary><blockquote>

Positional parameter use here needs to be fixed
</blockquote></details>

Done.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPTimerJobState/MSFT_SPTimerJobState.psm1, line 286 at r1](https://reviewable.io:443/reviews/powershell/sharepointdsc/660#-Kw2Z2dJHs9lk4UHGKe9:-Kw4bxC3-Kwa32eb7mbs:b-896fix) ([raw file](https://github.com/powershell/sharepointdsc/blob/42a7f15bc588ed1ce157205128e46b0b95824c25/Modules/SharePointDsc/DSCResources/MSFT_SPTimerJobState/MSFT_SPTimerJobState.psm1#L286)):*
<details><summary><i>Previously, BrianFarnhill (Brian Farnhill) wrote…</i></summary><blockquote>

Positional parameter use here needs to be fixed
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/660#-:-Kw4dkkyElLRpHmukszT:bs0p8a3)*

**Comment by BrianFarnhill** [comment]
Reviewed 4 of 236 files at r2, 232 of 232 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[Modules/SharePointDsc/SharePointDsc.psd1, line 15 at r1](https://reviewable.io:443/reviews/powershell/sharepointdsc/660#-Kw2DL8sUsTJZUZQiOW-:-KwcFtv1i0ac61KozmXV:bm3zuk5) ([raw file](https://github.com/powershell/sharepointdsc/blob/42a7f15bc588ed1ce157205128e46b0b95824c25/Modules/SharePointDsc/SharePointDsc.psd1#L15)):*
<details><summary><i>Previously, ykuijs (Yorick Kuijs) wrote…</i></summary><blockquote>

Can change this of course, but isn't this usually part of the release PR
</blockquote></details>

Yea but if we are doing a separate branch of it now anyway it saves us doing another branch later 

---

*[Modules/SharePointDsc/SharePointDsc.psd1, line 129 at r1](https://reviewable.io:443/reviews/powershell/sharepointdsc/660#-Kw2DNor0g2rwiBnGnzD:-KwcFytjNSAVZ5OnMoVo:bm3zuk5) ([raw file](https://github.com/powershell/sharepointdsc/blob/eb7586a743ae661d3075b53e7ba1c2e448cc7270/Modules/SharePointDsc/SharePointDsc.psd1#L129)):*
<details><summary><i>Previously, ykuijs (Yorick Kuijs) wrote…</i></summary><blockquote>

Can change this of course, but isn't this usually part of the release PR
</blockquote></details>

Yea but if we are doing a separate branch of it now anyway it saves us doing another branch later 

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPAlternateUrl/MSFT_SPAlternateUrl.schema.mof, line 6 at r1](https://reviewable.io:443/reviews/powershell/sharepointdsc/660#-Kw2F2hRtfrJ30FULphm:-KwcDu5c_xzo3ioIJsND:bos1bzk) ([raw file](https://github.com/powershell/sharepointdsc/blob/42a7f15bc588ed1ce157205128e46b0b95824c25/Modules/SharePointDsc/DSCResources/MSFT_SPAlternateUrl/MSFT_SPAlternateUrl.schema.mof#L6)):*
<details><summary><i>Previously, ykuijs (Yorick Kuijs) wrote…</i></summary><blockquote>

This needs to be key, else you would not be able to add an Internal URL to a web app, since the WebAppName and Zone would be identical.
</blockquote></details>

OK my bad

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPTimerJobState/MSFT_SPTimerJobState.psm1, line 184 at r1](https://reviewable.io:443/reviews/powershell/sharepointdsc/660#-Kw2YHUmGNRfEVwsxY-3:-KwcG3iemkRq48hTqqHo:bs3tidd) ([raw file](https://github.com/powershell/sharepointdsc/blob/42a7f15bc588ed1ce157205128e46b0b95824c25/Modules/SharePointDsc/DSCResources/MSFT_SPTimerJobState/MSFT_SPTimerJobState.psm1#L184)):*
<details><summary><i>Previously, ykuijs (Yorick Kuijs) wrote…</i></summary><blockquote>

Unfortunately not. The Exception type is Microsoft.SharePoint.PowerShell.SPCmdletException, which is a generic exception.
</blockquote></details>

All good, happy with this as it is then. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/660)*

**Comment by ykuijs** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[Modules/SharePointDsc/SharePointDsc.psd1, line 15 at r1](https://reviewable.io:443/reviews/powershell/sharepointdsc/660#-Kw2DL8sUsTJZUZQiOW-:-KxA55Th6BmzZ93U4c2x:b-896fix) ([raw file](https://github.com/powershell/sharepointdsc/blob/42a7f15bc588ed1ce157205128e46b0b95824c25/Modules/SharePointDsc/SharePointDsc.psd1#L15)):*
<details><summary><i>Previously, BrianFarnhill (Brian Farnhill) wrote…</i></summary><blockquote>

Yea but if we are doing a separate branch of it now anyway it saves us doing another branch later 
</blockquote></details>

Done.

---

*[Modules/SharePointDsc/SharePointDsc.psd1, line 129 at r1](https://reviewable.io:443/reviews/powershell/sharepointdsc/660#-Kw2DNor0g2rwiBnGnzD:-KxA57wRuB2QFXOgdV8h:b-896fix) ([raw file](https://github.com/powershell/sharepointdsc/blob/eb7586a743ae661d3075b53e7ba1c2e448cc7270/Modules/SharePointDsc/SharePointDsc.psd1#L129)):*
<details><summary><i>Previously, BrianFarnhill (Brian Farnhill) wrote…</i></summary><blockquote>

Yea but if we are doing a separate branch of it now anyway it saves us doing another branch later 
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/660)*

**Comment by BrianFarnhill** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/660#-:-KyD4t7K0g2Fq1ctzOuO:bnfp4nl)*

**Pull request merged**
