### PR TITLE
Fix MSFT_SPCreateFarm.psm1 and MSFT_SPJoinFarm.psm1

### PR DESCRIPTION
**Pull request by luigilink**
Fix non desired disconnect SPFarm when get-SPFarm return null.

- [x] Change details added to Unreleased section of changelog.md?
- [x] Added/updated documentation and descriptions in .schema.mof files where appropriate?
- [x] Examples updated for both the single server and small farm templates in the examples folder?
- [x] New/changed code adheres to [Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md)?
- [x] [Unit and Integration tests](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md) created/updated where possible?

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/sharepointdsc/495)

### CODE REVIEW

**Comment by BrianFarnhill** [comment]
I'm about to jump on a long flight so I'll have some time to try to adapt this code - I'll see what I can come up with that will work this in and potentially send you a pull request with some changes to work this in to an SPFarm resource maybe. Leave it with me for a couple of days and I'll let you know, but definitely don't close this one off yet :)

**Comment by luigilink** [comment]
@BrianFarnhill I fixed the failed pester, ready for review.

**Comment by BrianFarnhill** [comment]
@luigilink Thanks dude - Im deliberately sitting on this until I have the SPFarm resource one ready (should be a day or two) because I want to bring them in at the same time so we can leverage some common code, so sorry for delay on this but we will definitely get it sorted soon. Thanks dude

**Comment by ykuijs** [comment]
@BrianFarnhill, did you review this one? Can it be merged?

**Comment by BrianFarnhill** [comment]
Reviewed 6 of 8 files at r2.
Review status: 6 of 8 files reviewed at latest revision, 6 unresolved discussions.

---

*[CHANGELOG.md, line 26 at r2](https://reviewable.io:443/reviews/powershell/sharepointdsc/495#-KekJOVJ3c_YdbBWUiCH:-KekJOVJ3c_YdbBWUiCI:bjan1r) ([raw file](https://github.com/powershell/sharepointdsc/blob/ad02211a3fe7b9771287f46237bb676264c0a956/CHANGELOG.md#L26)):*
> ```Markdown
> * Added an error catch to provide more detail about running SPAppCatalog with
>   accounts other than the farm account
> * Fixed bug in SPCreateFarm and SPJoinFarm when a SharePoint Server is already
> ```

Can we put this under an unreleased heading

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPCreateFarm/MSFT_SPCreateFarm.psm1, line 79 at r2](https://reviewable.io:443/reviews/powershell/sharepointdsc/495#-KekGZOJg9zvvwYrUTkc:-KekGZOKpuXBQpBXLLXh:boybr1i) ([raw file](https://github.com/powershell/sharepointdsc/blob/ad02211a3fe7b9771287f46237bb676264c0a956/Modules/SharePointDsc/DSCResources/MSFT_SPCreateFarm/MSFT_SPCreateFarm.psm1#L79)):*
> ```PowerShell
>         $params = $args[0]
> 
>         $getSPMajorVersion = (Get-SPDSCInstalledProductVersion).FileMajorPart
> ```

This section we can now do with the helper I put in (based on your code here). Have a look at the SPFarm resource and you'll see it import a module and then execute the helper

        $modulePath = "..\..\Modules\SharePointDsc.Farm\SPFarm.psm1"
        Import-Module -Name (Join-Path -Path $scriptRoot -ChildPath $modulePath -Resolve)
        $dbStatus = Get-SPDSCConfigDBStatus -SQLServer $params.DatabaseServer `
                                            -Database $params.FarmConfigDatabaseName

Then you can look at $dbStatus.DatabaseExists to know the database has been created or not, and $dbStatus.ValidPermissions for the permissions. The DSN bit is still fine though. Have a look at how I did the get method in SPFarm and see if we can use pretty much the same logic. 

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPJoinFarm/MSFT_SPJoinFarm.psm1, line 62 at r2](https://reviewable.io:443/reviews/powershell/sharepointdsc/495#-KekHseUi6UUlB6OtTGb:-KekHseUi6UUlB6OtTGc:b-de4hzg) ([raw file](https://github.com/powershell/sharepointdsc/blob/ad02211a3fe7b9771287f46237bb676264c0a956/Modules/SharePointDsc/DSCResources/MSFT_SPJoinFarm/MSFT_SPJoinFarm.psm1#L62)):*
> ```PowerShell
>         $params = $args[0]
>         
>         $getSPMajorVersion = (Get-SPDSCInstalledProductVersion).FileMajorPart
> ```

Same feedback as CreateFarm resource

---

*[Modules/SharePointDsc/Modules/SharePointDsc.Util/SharePointDsc.Util.psm1, line 750 at r2](https://reviewable.io:443/reviews/powershell/sharepointdsc/495#-KekHwdbKyBhB-UA9Nz9:-KekHwdbKyBhB-UA9NzA:bddrdtw) ([raw file](https://github.com/powershell/sharepointdsc/blob/ad02211a3fe7b9771287f46237bb676264c0a956/Modules/SharePointDsc/Modules/SharePointDsc.Util/SharePointDsc.Util.psm1#L750)):*
> ```PowerShell
> }
> 
> function Test-SPDscSqlAccess
> ```

We can take this out as my helper covers this now

---

*[Tests/Unit/Stubs/SharePoint/15.0.4805.1000/Microsoft.SharePoint.PowerShell.psm1, line 19850 at r2](https://reviewable.io:443/reviews/powershell/sharepointdsc/495#-KekJHdHC0MFNaU5IXIG:-KekJHdIgUo9hrvrJz2s:bxvu39w) ([raw file](https://github.com/powershell/sharepointdsc/blob/ad02211a3fe7b9771287f46237bb676264c0a956/Tests/Unit/Stubs/SharePoint/15.0.4805.1000/Microsoft.SharePoint.PowerShell.psm1#L19850)):*
> ```PowerShell
>  } 
> 
> function Test-SPDscSqlAccess {
> ```

We dont ever update these stubs, please take this out

---

*[Tests/Unit/Stubs/SharePoint/16.0.4456.1000/Microsoft.SharePoint.PowerShell.psm1, line 20681 at r2](https://reviewable.io:443/reviews/powershell/sharepointdsc/495#-KekJKzAsbo649g4ABGK:-KekJKzAsbo649g4ABGL:bxvu39w) ([raw file](https://github.com/powershell/sharepointdsc/blob/ad02211a3fe7b9771287f46237bb676264c0a956/Tests/Unit/Stubs/SharePoint/16.0.4456.1000/Microsoft.SharePoint.PowerShell.psm1#L20681)):*
> ```PowerShell
>  } 
> 
> function Test-SPDscSqlAccess {
> ```

We dont ever update these stubs, please take this out

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/495)*

**Comment by ykuijs** [comment]
@luigilink Any update?

**Comment by luigilink** [comment]
Reviewed 7 of 8 files at r4.
Review status: 6 of 7 files reviewed at latest revision, 6 unresolved discussions.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPCreateFarm/MSFT_SPCreateFarm.psm1, line 79 at r2](https://reviewable.io:443/reviews/powershell/sharepointdsc/495#-KekGZOJg9zvvwYrUTkc:-KgOJvyHwFfz2XUpHjAp:b-896fix) ([raw file](https://github.com/powershell/sharepointdsc/blob/ad02211a3fe7b9771287f46237bb676264c0a956/Modules/SharePointDsc/DSCResources/MSFT_SPCreateFarm/MSFT_SPCreateFarm.psm1#L79)):*
<details><summary><i>Previously, BrianFarnhill (Brian Farnhill) wrote…</i></summary><blockquote>

This section we can now do with the helper I put in (based on your code here). Have a look at the SPFarm resource and you'll see it import a module and then execute the helper

        $modulePath = "..\..\Modules\SharePointDsc.Farm\SPFarm.psm1"
        Import-Module -Name (Join-Path -Path $scriptRoot -ChildPath $modulePath -Resolve)
        $dbStatus = Get-SPDSCConfigDBStatus -SQLServer $params.DatabaseServer `
                                            -Database $params.FarmConfigDatabaseName

Then you can look at $dbStatus.DatabaseExists to know the database has been created or not, and $dbStatus.ValidPermissions for the permissions. The DSN bit is still fine though. Have a look at how I did the get method in SPFarm and see if we can use pretty much the same logic. 
</blockquote></details>

Done.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPJoinFarm/MSFT_SPJoinFarm.psm1, line 62 at r2](https://reviewable.io:443/reviews/powershell/sharepointdsc/495#-KekHseUi6UUlB6OtTGb:-KgOJzGWLnvaonHpuj1j:b-896fix) ([raw file](https://github.com/powershell/sharepointdsc/blob/ad02211a3fe7b9771287f46237bb676264c0a956/Modules/SharePointDsc/DSCResources/MSFT_SPJoinFarm/MSFT_SPJoinFarm.psm1#L62)):*
<details><summary><i>Previously, BrianFarnhill (Brian Farnhill) wrote…</i></summary><blockquote>

Same feedback as CreateFarm resource
</blockquote></details>

Done.

---

*[Tests/Unit/Stubs/SharePoint/15.0.4805.1000/Microsoft.SharePoint.PowerShell.psm1, line 19850 at r2](https://reviewable.io:443/reviews/powershell/sharepointdsc/495#-KekJHdHC0MFNaU5IXIG:-KgOK1twflPUS7cHx-CU:b-896fix) ([raw file](https://github.com/powershell/sharepointdsc/blob/ad02211a3fe7b9771287f46237bb676264c0a956/Tests/Unit/Stubs/SharePoint/15.0.4805.1000/Microsoft.SharePoint.PowerShell.psm1#L19850)):*
<details><summary><i>Previously, BrianFarnhill (Brian Farnhill) wrote…</i></summary><blockquote>

We dont ever update these stubs, please take this out
</blockquote></details>

Done.

---

*[Tests/Unit/Stubs/SharePoint/16.0.4456.1000/Microsoft.SharePoint.PowerShell.psm1, line 20681 at r2](https://reviewable.io:443/reviews/powershell/sharepointdsc/495#-KekJKzAsbo649g4ABGK:-KgOK3Jf7HKArgLksPzX:b-896fix) ([raw file](https://github.com/powershell/sharepointdsc/blob/ad02211a3fe7b9771287f46237bb676264c0a956/Tests/Unit/Stubs/SharePoint/16.0.4456.1000/Microsoft.SharePoint.PowerShell.psm1#L20681)):*
<details><summary><i>Previously, BrianFarnhill (Brian Farnhill) wrote…</i></summary><blockquote>

We dont ever update these stubs, please take this out
</blockquote></details>

Done.

---

*[Modules/SharePointDsc/Modules/SharePointDsc.Util/SharePointDsc.Util.psm1, line 750 at r2](https://reviewable.io:443/reviews/powershell/sharepointdsc/495#-KekHwdbKyBhB-UA9Nz9:-KgOJqVIwWQGxwyc6fWY:b-896fix) ([raw file](https://github.com/powershell/sharepointdsc/blob/ad02211a3fe7b9771287f46237bb676264c0a956/Modules/SharePointDsc/Modules/SharePointDsc.Util/SharePointDsc.Util.psm1#L750)):*
<details><summary><i>Previously, BrianFarnhill (Brian Farnhill) wrote…</i></summary><blockquote>

We can take this out as my helper covers this now
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/495)*

**Comment by luigilink** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[CHANGELOG.md, line 26 at r2](https://reviewable.io:443/reviews/powershell/sharepointdsc/495#-KekJOVJ3c_YdbBWUiCH:-KgOQIoIflZ4Tff34g9j:b-896fix) ([raw file](https://github.com/powershell/sharepointdsc/blob/ad02211a3fe7b9771287f46237bb676264c0a956/CHANGELOG.md#L26)):*
<details><summary><i>Previously, BrianFarnhill (Brian Farnhill) wrote…</i></summary><blockquote>

Can we put this under an unreleased heading
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/495)*

**Comment by BrianFarnhill** [comment]
Reviewed 7 of 8 files at r4, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[Tests/Unit/SharePointDsc/SharePointDsc.SPCreateFarm.Tests.ps1, line 49 at r5](https://reviewable.io:443/reviews/powershell/sharepointdsc/495#-KgQvxRAhQOyaNTbrdmJ:-KgQvxRAhQOyaNTbrdmK:b-huvr0v) ([raw file](https://github.com/powershell/sharepointdsc/blob/afd57948a6a9dccf4824c3b9d74abb1e686b9d36/Tests/Unit/SharePointDsc/SharePointDsc.SPCreateFarm.Tests.ps1#L49)):*
> ```PowerShell
> 
>         # Test contexts
>         Context -Name "no farm is configured locally and a supported version of SharePoint is installed" -Fixture {
> ```

Can I get you to put an extra context in here that looks like the [one we did for SPFarm](https://github.com/PowerShell/SharePointDsc/blob/dev/Tests/Unit/SharePointDsc/SharePointDsc.SPFarm.Tests.ps1#L267) that checks that the logic for the wait to join the database works correctly (that way the code coverage on the change will go up and this should get it to pass the check to merge this one in). The code is there already, you should be able to just lift and shift the test in to both this one and the SPJoinFarm tests as well. The rest of the code looks good though so once the tests are added we should be good to go

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/495)*

**Comment by BrianFarnhill** [comment]
Reviewed 2 of 2 files at r6.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/495)*

**Pull request merged**
