### PR TITLE
Update MSFT_SPBlobCacheSettings.psm1

### PR DESCRIPTION
**Pull request by DamianWiese**
In Set-TargetResource configuring the max-age attribute in a few farm fails because this attribute is not part of the default Blob Cache attributes and $webconfig.configuration.SharePoint.BlobCache."max-age"  = $changes.MaxAgeInSeconds.ToString() only updates an existing attribute and will not create a new one. The following error message is seen in the console:

PowerShell DSC resource MSFT_SPBlobCacheSettings  failed to execute Set-TargetResource functionality with error
message: Exception setting "max-age": "The property 'max-age' cannot be found on this object. Verify that the property
exists and can be set."
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : ProviderOperationExecutionFailure
    + PSComputerName        : localhost

Fix:
Updated the max-age section to use the following, which will create the attribute if it does not exist and update it if it does exist.
$webconfig.configuration.SharePoint.BlobCache.SetAttribute("max-age",$($changes.MaxAgeInSeconds.ToString()))

Thanks for submitting a Pull Request to this project.
This template will help you create your pull request.

Please make sure you have read the [Contribution Guidelines](https://github.com/powershell/xSharePoint/wiki/Contributing%20to%20xSharePoint).

To aid community reviewers in reviewing and merging your PR, please take the time to run through this checklist:

**DELETE THIS LINE AND ABOVE**

[Replace this with a description of your pull request]

- [ ] Change details added to Unreleased section of changelog.md?
- [ ] Added/updated documentation and descriptions in .schema.mof files where appropriate?
- [ ] Examples updated for both the single server and small farm templates in the examples folder?
- [ ] New/changed code adheres to [Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md)?
- [ ] [Unit and Integration tests](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md) created/updated where possible?

**DELETE THIS LINE AND BELOW**

Your contribution to this project is greatly appreciated.

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/sharepointdsc/672)

### CODE REVIEW

**Comment by ykuijs** [comment]
Hi Damian, good addition. Just wondering: Should this Set method be used for all parameters, like Enabled, Location, MaxSize, etc? In a default web.config they exist, but there is a possiblity someone changed the web.config and deleted a parameter, causing the resource to crash on that.

**Comment by DamianWiese** [comment]
Hi Yorick, Yes I think that make sense. I'll make the changes and re-submit.

**Comment by DamianWiese** [comment]
Yorick,
I have updated the Set-TargetResource function to use the XML.SetAttribute() method for the properties:
enabled (EnableCache)
location (Location)
maxSize (MaxSizeInGB)
max-age (MaxAgeInSeconds)
path (FileTypes)

This latest commit is ready to be pulled.

**Comment by ykuijs** [comment]
Hi @DamianWiese, the changes look good. Just one more request. Can you also update the Changelog.MD file to include a description of your change in that file?

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/672#-:-KyzueI8oI6Vx-MuZhOP:b-kzjx5z)*

**Comment by DamianWiese** [comment]
@ykuijs, I've updated the changelog.MD file and created a pull request for that file.

**Comment by ykuijs** [comment]
Please include the changelog update in this PR by updating it in your patch-1 branch.

**Comment by DamianWiese** [comment]
@ykuijs sorry, for the hassle, I think I have it sorted now.

**Comment by ykuijs** [comment]
Now you just need to update your branch with the Powershell/Dev branch and resolve any conflicts and you are good to go ;-)

**Comment by ykuijs** [comment]
To do this:
In GitHub Desktop, in the History section click the "Update from PowerShell/dev" button. You will be prompted that conflicts are found in the Changelog.md. Open that file and check for something that looks like [this](https://www.git-tower.com/learn/content/01-git/01-ebook/en/01-command-line/05-advanced-topics/03-merge-conflicts/conflict-markers.png).

Combine the results and make sure the lines with >>>>>, <<<<< and ===== are gone. Then save the file, go back to GitHub Desktop, select the changelog.md and Commit again.

**Comment by DamianWiese** [comment]
Ok, now I think I've got it, for real. :)

**Comment by ykuijs** [comment]
Sorry, now the AppVeyor tests fail because the line above 1.9 contains trailing spaces :-)

**Comment by ykuijs** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/672#-:-Kz3IyEsBQ32_E4hPq-b:bnfp4nl)*

**Pull request merged**
