### PR TITLE
Added support to set windows search service accounts

### PR DESCRIPTION
**Pull request by BrianFarnhill**
Added an option to specify which service account should be used for the search and search host controller windows services to SPSearchServiceApp

- [X] Change details added to Unreleased section of changelog.md?
- [X] Added/updated documentation and descriptions in .schema.mof files where appropriate?
- [X] Examples updated for both the single server and small farm templates in the examples folder?
- [X] New/changed code adheres to [Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md)?
- [X] [Unit and Integration tests](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md) created/updated where possible?

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/sharepointdsc/626)

### CODE REVIEW

**Comment by BrianFarnhill** [comment]
The failure in the tests here is to do with one of the common tests that come from code outside our repo. I'll have a look in to this, but do not think that should impact on the ability to review this PR

**Comment by ykuijs** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/626#-:-KmknHpiILsTd1AiIXXe:bnfp4nl)*

**Comment by ykuijs** [comment]
Review completed. Do you want me to merge this PR or do you want to fix the test first?

**Comment by BrianFarnhill** [comment]
@ykuijs The test fix will be outside the repo so no need to wait for it here.

**Pull request merged**
