### PR TITLE
Imp service app proxy suffix

### PR DESCRIPTION
**Pull request by BrunoReboul**
Thanks for submitting a Pull Request to this project.

Please make sure you have read the [Contribution Guidelines](https://github.com/powershell/xSharePoint/wiki/Contributing%20to%20xSharePoint).

To aid community reviewers in reviewing and merging your PR, please take the time to run through this checklist:
- [yes ] Change details added to Unreleased section of changelog.md?
- [ yes] Added/updated documentation and descriptions in .schema.mof files where appropriate?
- [ na] Examples updated for both the single server and small farm templates in the examples folder?
- [ yes] New/changed code adheres to [Style Guidelines]?(https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md)?
- [ yes] [Unit and Integration tests](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md) created/updated where possible?

Limited to Secure Store as spoken

Your contribution to this project is greatly appreciated.

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/sharepointdsc/339)

### CODE REVIEW

**Comment by BrianFarnhill** [comment]
@BrunoReboul Have you had a chance to look at the failing tests on this? Let us know if you need help

**Comment by BrunoReboul** [comment]
@BrianFarnhill fixed now :-)

**Comment by BrianFarnhill** [comment]
Reviewed 3 of 9 files at r3.
Review status: 3 of 10 files reviewed at latest revision, 5 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/powershell/sharepointdsc/339#-KLrimFTrEOfVhE4kccH:-KLrimFTrEOfVhE4kccI:1900760088) (no related file):*
I just did a quick review on the first one, can you have a look at returning the proxy names in the get methods? I'm actually not sure how to look up the proxy that is associated with a specific service app though, so keen to get your thoughts on that. I'll review the rest of the changes once we have that sorted.

---

*[CHANGELOG.md, line 5 \[r3\]](https://reviewable.io:443/reviews/powershell/sharepointdsc/339#-KLrhQLU4j8NHxhdEPPa:-KLrhQLU4j8NHxhdEPPb:823129957) ([raw file](https://github.com/powershell/sharepointdsc/blob/84f5c3d0437869045f3c97608110cf0cf1dffc0d/CHANGELOG.md#L5)):*
> ```Markdown
> ### Unreleased
> 
>  * Add ProxyName parameters to Service App
> ```

Can you change this to the following:

 * Added ProxyName parameter to all service application resources

---

*[CHANGELOG.md, line 15 \[r3\]](https://reviewable.io:443/reviews/powershell/sharepointdsc/339#-KLrhK2cU0fYwPwYDzTF:-KLrhK2cU0fYwPwYDzTG:878967561) ([raw file](https://github.com/powershell/sharepointdsc/blob/84f5c3d0437869045f3c97608110cf0cf1dffc0d/CHANGELOG.md#L15)):*
> ```Markdown
> ### 1.1
> 
> >>>>>>> upstream/dev
> ```

I think you left this from a merge, can you remove this line?

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPManagedMetadataServiceApp/MSFT_SPManagedMetaDataServiceApp.psm1, line 39 \[r3\]](https://reviewable.io:443/reviews/powershell/sharepointdsc/339#-KLrhfy8I1yGLCAaIs13:-KLrhfy8I1yGLCAaIs14:2099435791) ([raw file](https://github.com/powershell/sharepointdsc/blob/84f5c3d0437869045f3c97608110cf0cf1dffc0d/Modules/SharePointDsc/DSCResources/MSFT_SPManagedMetadataServiceApp/MSFT_SPManagedMetaDataServiceApp.psm1#L39)):*
> ```PowerShell
>         else
>         {
>             return @{
> ```

We need to be able to return the current proxy name in the get methods here. Are you able to look it up and return it here?

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPManagedMetadataServiceApp/MSFT_SPManagedMetaDataServiceApp.psm1, line 82 \[r3\]](https://reviewable.io:443/reviews/powershell/sharepointdsc/339#-KLri-iQCfa7M9LseKep:-KLri-iQCfa7M9LseKeq:1736222064) ([raw file](https://github.com/powershell/sharepointdsc/blob/84f5c3d0437869045f3c97608110cf0cf1dffc0d/Modules/SharePointDsc/DSCResources/MSFT_SPManagedMetadataServiceApp/MSFT_SPManagedMetaDataServiceApp.psm1#L82)):*
> ```PowerShell
>             }
>             if ($params.ContainsKey("ProxyName")) { $pName = $params.ProxyName ; $params.Remove("ProxyName") | Out-Null }
>             if ($pName -eq $Null) {$pName = "$($params.Name) Proxy"}
> ```

Can you switch this so that the $null check is on the left?

    if ($null -eq $pName)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/339)*

**Comment by BrianFarnhill** [comment]
@BrunoReboul Have you had a chance to review the feedback from the code review yet?

**Comment by BrianFarnhill** [comment]
Updating this thread - I spoke to @BrunoReboul about this during the week, he is looking for a way to look up service app proxies from the service app object. Giving him some time to figure this one out to progress this one.

**Comment by BrunoReboul** [comment]
@BrianFarnhill  requested changes implemented on ManagedMetaDataServiceApp.
Thanks @luigilink for the hint on geting proxy names.
GetType().Name used to avoid language dependent issues
If ok, I could extend implementation to other Service app

**Comment by BrianFarnhill** [comment]
Review status: 1 of 10 files reviewed at latest revision, 6 unresolved discussions.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPManagedMetadataServiceApp/MSFT_SPManagedMetaDataServiceApp.psm1, line 43 \[r5\]](https://reviewable.io:443/reviews/powershell/sharepointdsc/339#-KN6TwligUOO6UhIh9pU:-KN6TwligUOO6UhIh9pV:-42227841) ([raw file](https://github.com/powershell/sharepointdsc/blob/b1388e55f52198d73fc04a40c6816896b1dea88a/Modules/SharePointDsc/DSCResources/MSFT_SPManagedMetadataServiceApp/MSFT_SPManagedMetaDataServiceApp.psm1#L43)):*
> ```PowerShell
>         {
>             $serviceAppProxy = $serviceAppProxies | Where-Object { $_.GetType().Name -eq 'MetadataWebServiceApplicationProxy' }
>             if ($null -ne $serviceAppProxy) { $proxyName = $serviceAppProxy.Name}
> ```

The issue here is that you are assuming that there is only ever going to be one service app proxy of each type in the farm - if you have multiple service apps of the same type where each has its own proxy, this will not return the correct proxy every time. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/339)*

**Comment by BrunoReboul** [comment]
@BrianFarnhill thank for feedback
Code updated to use :
$serviceAppProxy = $serviceAppProxies | Where-Object { $serviceApp.IsConnected($_)}

**Comment by BrianFarnhill** [comment]
Reviewed 6 of 9 files at r3, 2 of 3 files at r5, 1 of 1 files at r6.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPSearchServiceApp/MSFT_SPSearchServiceApp.psm1, line 63 \[r6\]](https://reviewable.io:443/reviews/powershell/sharepointdsc/339#-KNdCYSRLsQwHvX9tbo5:-KNdCYSSbHPw0iitDBMq:1186816951) ([raw file](https://github.com/powershell/sharepointdsc/blob/4f551bc44288e896dc2f6e2abb7c1dfe0bfecbba/Modules/SharePointDsc/DSCResources/MSFT_SPSearchServiceApp/MSFT_SPSearchServiceApp.psm1#L63)):*
> ```PowerShell
>                 $cloudIndex = $serviceApp.CloudIndex
>             }
>             $returnVal =  @{
> ```

You aren't returning the proxy name here - the get methods for all of the resources need to return the proxy names the same way as you did for the MMS one.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/339)*

**Comment by BrunoReboul** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[CHANGELOG.md, line 5 \[r3\]](https://reviewable.io:443/reviews/powershell/sharepointdsc/339#-KLrhQLU4j8NHxhdEPPa:-KNdsls8Y2BspGhwXSQS:-499146009) ([raw file](https://github.com/powershell/sharepointdsc/blob/84f5c3d0437869045f3c97608110cf0cf1dffc0d/CHANGELOG.md#L5)):*
<details><summary><i>Previously, BrianFarnhill (Brian Farnhill) wrote…</i></summary>
> Can you change this to the following:
> 
>  * Added ProxyName parameter to all service application resources
</details>
Done.

---

*[CHANGELOG.md, line 15 \[r3\]](https://reviewable.io:443/reviews/powershell/sharepointdsc/339#-KLrhK2cU0fYwPwYDzTF:-KNdsnk0X7Z_AilSZCps:-499146009) ([raw file](https://github.com/powershell/sharepointdsc/blob/84f5c3d0437869045f3c97608110cf0cf1dffc0d/CHANGELOG.md#L15)):*
<details><summary><i>Previously, BrianFarnhill (Brian Farnhill) wrote…</i></summary>
> I think you left this from a merge, can you remove this line?
</details>
Done.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPManagedMetadataServiceApp/MSFT_SPManagedMetaDataServiceApp.psm1, line 82 \[r3\]](https://reviewable.io:443/reviews/powershell/sharepointdsc/339#-KLri-iQCfa7M9LseKep:-KNdt5PSsbrdMbOcamsW:-499146009) ([raw file](https://github.com/powershell/sharepointdsc/blob/84f5c3d0437869045f3c97608110cf0cf1dffc0d/Modules/SharePointDsc/DSCResources/MSFT_SPManagedMetadataServiceApp/MSFT_SPManagedMetaDataServiceApp.psm1#L82)):*
<details><summary><i>Previously, BrianFarnhill (Brian Farnhill) wrote…</i></summary>
> Can you switch this so that the $null check is on the left?
> 
>     if ($null -eq $pName)
</details>
Done.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPManagedMetadataServiceApp/MSFT_SPManagedMetaDataServiceApp.psm1, line 43 \[r5\]](https://reviewable.io:443/reviews/powershell/sharepointdsc/339#-KN6TwligUOO6UhIh9pU:-KNdt0u2swmhcoVNKcH5:-499146009) ([raw file](https://github.com/powershell/sharepointdsc/blob/b1388e55f52198d73fc04a40c6816896b1dea88a/Modules/SharePointDsc/DSCResources/MSFT_SPManagedMetadataServiceApp/MSFT_SPManagedMetaDataServiceApp.psm1#L43)):*
<details><summary><i>Previously, BrianFarnhill (Brian Farnhill) wrote…</i></summary>
> The issue here is that you are assuming that there is only ever going to be one service app proxy of each type in the farm - if you have multiple service apps of the same type where each has its own proxy, this will not return the correct proxy every time. 
</details>
Done.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPSearchServiceApp/MSFT_SPSearchServiceApp.psm1, line 63 \[r6\]](https://reviewable.io:443/reviews/powershell/sharepointdsc/339#-KNdCYSRLsQwHvX9tbo5:-KNdsIjIPaM8GM7EfADT:-1040099467) ([raw file](https://github.com/powershell/sharepointdsc/blob/4f551bc44288e896dc2f6e2abb7c1dfe0bfecbba/Modules/SharePointDsc/DSCResources/MSFT_SPSearchServiceApp/MSFT_SPSearchServiceApp.psm1#L63)):*
<details><summary><i>Previously, BrianFarnhill (Brian Farnhill) wrote…</i></summary>
> You aren't returning the proxy name here - the get methods for all of the resources need to return the proxy names the same way as you did for the MMS one.
</details>
Yes absolutely. Just waiting for your GO on method now used within MMS to generalize it to other service apps. So is it ok to generalize ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/339)*

**Comment by BrianFarnhill** [comment]
@BrunoReboul Yes ok to generalise and use it that way because it will still return the proxy name attached to the service app for each one.

**Comment by BrunoReboul** [comment]
Generalization done

---

Review status: 5 of 16 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/339#-:-KNgajqpT81Bjg3kbuAd:1755585889)*

**Comment by BrianFarnhill** [comment]
Reviewed 11 of 11 files at r7.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[CHANGELOG.md, line 5 \[r3\]](https://reviewable.io:443/reviews/powershell/sharepointdsc/339#-KLrhQLU4j8NHxhdEPPa:-KNiZZc0G3cgFDSGNijU:1608198907) ([raw file](https://github.com/powershell/sharepointdsc/blob/84f5c3d0437869045f3c97608110cf0cf1dffc0d/CHANGELOG.md#L5)):*
<details><summary><i>Previously, BrunoReboul (Bruno REBOUL) wrote…</i></summary>
> Done.
</details>
Can you put this under the unreleased section again? The heading wont be there yet as we just shipped 1.2 so add the heading to the top again and list it under there.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/339)*

**Comment by BrunoReboul** [comment]
Review status: 15 of 16 files reviewed at latest revision, all discussions resolved.

---

*[CHANGELOG.md, line 5 \[r3\]](https://reviewable.io:443/reviews/powershell/sharepointdsc/339#-KLrhQLU4j8NHxhdEPPa:-KNlN3Fo5Rv9dlZY4wIM:-499146009) ([raw file](https://github.com/powershell/sharepointdsc/blob/84f5c3d0437869045f3c97608110cf0cf1dffc0d/CHANGELOG.md#L5)):*
<details><summary><i>Previously, BrianFarnhill (Brian Farnhill) wrote…</i></summary>
> Can you put this under the unreleased section again? The heading wont be there yet as we just shipped 1.2 so add the heading to the top again and list it under there.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/339)*

**Comment by BrianFarnhill** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r8.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/339#-:-KOIZcymxGkkliArNTAL:1417088721)*

**Pull request merged**
