### PR TITLE
New SPWebAppPermissions resource

### PR DESCRIPTION
**Pull request by ykuijs**
New SPWebAppPermissions resource, as described in issue #296 

Thanks for submitting a Pull Request to this project.

Please make sure you have read the [Contribution Guidelines](https://github.com/powershell/xSharePoint/wiki/Contributing%20to%20xSharePoint).

To aid community reviewers in reviewing and merging your PR, please take the time to run through this checklist:
- [X] Change details added to Unreleased section of Changelog.md?
- [X] Added/updated documentation and descriptions in .schema.mof files where appropriate?
- [X] Examples updated for both the single server and small farm templates in the examples folder?
- [X] New/changed code adheres to [Style Guidelines]?(https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md)?
- [X] [Unit and Integration tests](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md) created/updated where possible?

Your contribution to this project is greatly appreciated.

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xsharepoint/299)

### CODE REVIEW

**Comment by BrianFarnhill** [comment]
Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/powershell/xsharepoint/299#-KJDPwMfu5-p2UfRkwp9:-KJDPwMfu5-p2UfRkwpA:1610089295) (no related file):*
There is a merge conflict here - I suspect it's going to be just the CHANGELOG but have a look and update accordingly. Thanks Bud

---

*[Modules/SharePointDSC/DSCResources/MSFT_SPWebAppPermissions/MSFT_SPWebAppPermissions.psm1, line 34 \[r1\]](https://reviewable.io:443/reviews/powershell/xsharepoint/299#-KJDMcr_6-lf3ZmqiN6K:-KJDMcr_6-lf3ZmqiN6L:2117594552) ([raw file](https://github.com/powershell/xsharepoint/blob/cabe0430404a85d431a8d0bec87f254e65997bcf/Modules/SharePointDSC/DSCResources/MSFT_SPWebAppPermissions/MSFT_SPWebAppPermissions.psm1#L34)):*
> ```PowerShell
>     }
>     
>     if (($ListPermissions -contains "Manage Lists" -or $ListPermissions -contains "Override List Behaviors" -or $ListPermissions -contains "Add Items" -or $ListPermissions -contains "Edit Items" -or $ListPermissions -contains "Delete Items" -or $ListPermissions -contains "Approve Items" -or $ListPermissions -contains "Open Items" -or $ListPermissions -contains "View Versions" -or $ListPermissions -contains "Delete Versions" -or $ListPermissions -contains "Create Alerts" -or $SitePermissions -contains "Manage Permissions" -or $SitePermissions -contains "Manage Web Site" -or $SitePermissions -contains "Add and Customize Pages" -or $SitePermissions -contains "Manage Alerts" -or $SitePermissions -contains "Use Client Integration Features" -or $PersonalPermissions -contains "Manage Personal Views" -or $PersonalPermissions -contains "Add/Remove Personal Web Parts" -or $PersonalPermissions -contains "Update Personal Web Parts") -and -not ($ListPermissions -contains "View Items")) {
> ```

This is a bit of a monster line. Can we look at refactoring this a little. Either a) split it over multiple lines (example below), or b) put the permissions you are checking for in to an array and then use Compare-Object or something like that to figure out if there are things in there that you are testing about. 

    if (($ListPermissions -contains "Manage Lists" `
         -or $ListPermissions -contains "Override List Behaviors" `
         -or $ListPermissions -contains "Add Items" `
         -or $ListPermissions -contains "Edit Items" `
         -or $ListPermissions -contains "Delete Items" `
         -or $ListPermissions -contains "Approve Items" `
         -or $ListPermissions -contains "Open Items" `
         -or $ListPermissions -contains "View Versions" `
         -or $ListPermissions -contains "Delete Versions" `
         -or $ListPermissions -contains "Create Alerts" `
         -or $SitePermissions -contains "Manage Permissions" `
         -or $SitePermissions -contains "Manage Web Site" `
         -or $SitePermissions -contains "Add and Customize Pages" `
         -or $SitePermissions -contains "Manage Alerts" `
         -or $SitePermissions -contains "Use Client Integration Features" `
         -or $PersonalPermissions -contains "Manage Personal Views" `
         -or $PersonalPermissions -contains "Add/Remove Personal Web Parts" `
         -or $PersonalPermissions -contains "Update Personal Web Parts") `
       -and -not ($ListPermissions -contains "View Items")) {

---

*[Modules/SharePointDSC/DSCResources/MSFT_SPWebAppPermissions/MSFT_SPWebAppPermissions.psm1, line 58 \[r1\]](https://reviewable.io:443/reviews/powershell/xsharepoint/299#-KJDNA292qqV8lQzTuvQ:-KJDNA2AUzvrRhT66uPc:1330657228) ([raw file](https://github.com/powershell/xsharepoint/blob/cabe0430404a85d431a8d0bec87f254e65997bcf/Modules/SharePointDSC/DSCResources/MSFT_SPWebAppPermissions/MSFT_SPWebAppPermissions.psm1#L58)):*
> ```PowerShell
>     }    
> 
>     if (($ListPermissions -contains "Manage Lists" -or $ListPermissions -contains "Override List Behaviors" -or $ListPermissions -contains "Add Items" -or $ListPermissions -contains "Edit Items" -or $ListPermissions -contains "Delete Items" -or $ListPermissions -contains "View Items" -or $ListPermissions -contains "Approve Items" -or $ListPermissions -contains "Open Items" -or $ListPermissions -contains "View Versions" -or $ListPermissions -contains "Delete Versions" -or $ListPermissions -contains "Create Alerts" -or $SitePermissions -contains "Manage Permissions" -or $SitePermissions -contains "View Web Analytics Data"  -or $SitePermissions -contains "Create Subsites"  -or $SitePermissions -contains "Manage Web Site" -or $SitePermissions -contains "Add and Customize Pages" -or $SitePermissions -contains "Apply Themes and Borders" -or $SitePermissions -contains "Apply Style Sheets" -or $SitePermissions -contains "Create Groups" -or $SitePermissions -contains "Browse Directories" -or $SitePermissions -contains "Use Self-Service Site Creation" -or $SitePermissions -contains "Enumerate Permissions" -or $SitePermissions -contains "Manage Alerts" -or $PersonalPermissions -contains "Manage Personal Views" -or $PersonalPermissions -contains "Add/Remove Personal Web Parts" -or $PersonalPermissions -contains "Update Personal Web Parts") -and -not ($SitePermissions -contains "View Pages")) {
> ```

Same remark as above for refactoring the super long lines

---

*[Modules/SharePointDSC/DSCResources/MSFT_SPWebAppPermissions/MSFT_SPWebAppPermissions.psm1, line 74 \[r1\]](https://reviewable.io:443/reviews/powershell/xsharepoint/299#-KJDNLAZcxoma7lakPdQ:-KJDNLAZcxoma7lakPdR:2034084328) ([raw file](https://github.com/powershell/xsharepoint/blob/cabe0430404a85d431a8d0bec87f254e65997bcf/Modules/SharePointDSC/DSCResources/MSFT_SPWebAppPermissions/MSFT_SPWebAppPermissions.psm1#L74)):*
> ```PowerShell
>     }
> 
>     if (($ListPermissions -contains "Manage Lists" -or $ListPermissions -contains "Override List Behaviors" -or $ListPermissions -contains "Add Items" -or $ListPermissions -contains "Edit Items" -or $ListPermissions -contains "Delete Items" -or $ListPermissions -contains "View Items" -or $ListPermissions -contains "Approve Items" -or $ListPermissions -contains "Open Items" -or $ListPermissions -contains "View Versions" -or $ListPermissions -contains "Delete Versions" -or $ListPermissions -contains "Create Alerts" -or $ListPermissions -contains "View Application Pages" -or $SitePermissions -contains "Manage Permissions" -or $SitePermissions -contains "View Web Analytics Data"  -or $SitePermissions -contains "Create Subsites"  -or $SitePermissions -contains "Manage Web Site" -or $SitePermissions -contains "Add and Customize Pages" -or $SitePermissions -contains "Apply Themes and Borders" -or $SitePermissions -contains "Apply Style Sheets" -or $SitePermissions -contains "Create Groups" -or $SitePermissions -contains "Browse Directories" -or $SitePermissions -contains "Use Self-Service Site Creation" -or $SitePermissions -contains "View Pages" -or $SitePermissions -contains "Enumerate Permissions" -or $SitePermissions -contains "Browse User Information" -or $SitePermissions -contains "Manage Alerts" -or $SitePermissions -contains "Use Remote Interfaces" -or $SitePermissions -contains "Use Client Integration Features" -or $SitePermissions -contains "Edit Personal User Information" -or $PersonalPermissions -contains "Manage Personal Views" -or $PersonalPermissions -contains "Add/Remove Personal Web Parts" -or $PersonalPermissions -contains "Update Personal Web Parts") -and -not ($SitePermissions -contains "Open")) {
> ```

Same remark again about the long lines

---

*[Modules/SharePointDSC/DSCResources/MSFT_SPWebAppPermissions/MSFT_SPWebAppPermissions.psm1, line 184 \[r1\]](https://reviewable.io:443/reviews/powershell/xsharepoint/299#-KJDNfFPHcHjXw-PcqDl:-KJDNfFPHcHjXw-PcqDm:1580063325) ([raw file](https://github.com/powershell/xsharepoint/blob/cabe0430404a85d431a8d0bec87f254e65997bcf/Modules/SharePointDSC/DSCResources/MSFT_SPWebAppPermissions/MSFT_SPWebAppPermissions.psm1#L184)):*
> ```PowerShell
>     }
>     
>     if (($ListPermissions -contains "Manage Lists" -or $ListPermissions -contains "Override List Behaviors" -or $ListPermissions -contains "Add Items" -or $ListPermissions -contains "Edit Items" -or $ListPermissions -contains "Delete Items" -or $ListPermissions -contains "Approve Items" -or $ListPermissions -contains "Open Items" -or $ListPermissions -contains "View Versions" -or $ListPermissions -contains "Delete Versions" -or $ListPermissions -contains "Create Alerts" -or $SitePermissions -contains "Manage Permissions" -or $SitePermissions -contains "Manage Web Site" -or $SitePermissions -contains "Add and Customize Pages" -or $SitePermissions -contains "Manage Alerts" -or $SitePermissions -contains "Use Client Integration Features" -or $PersonalPermissions -contains "Manage Personal Views" -or $PersonalPermissions -contains "Add/Remove Personal Web Parts" -or $PersonalPermissions -contains "Update Personal Web Parts") -and -not ($ListPermissions -contains "View Items")) {
> ```

Instead of putting this complex logic at the top of each method, can you split it off to a function in this module (since it won't be called inside of an Invoke-SPDSCComannd block it'll see the function and will be able to call it fine) and then we can just call that from the top of each of the main methods.

---

*[Tests/SharePointDSC/SharePointDSC.SPWebAppPermissions.Tests.ps1, line 18 \[r1\]](https://reviewable.io:443/reviews/powershell/xsharepoint/299#-KJDPFfGfzfNDWmw32KM:-KJDPFfHxRlOGzRepIE6:2014509797) ([raw file](https://github.com/powershell/xsharepoint/blob/cabe0430404a85d431a8d0bec87f254e65997bcf/Tests/SharePointDSC/SharePointDSC.SPWebAppPermissions.Tests.ps1#L18)):*
> ```PowerShell
>     InModuleScope $ModuleName {
>             $testParams = @{
>                 WebAppUrl      = "http:/sharepoint.contoso.com"
> ```

URL has one "/" in it

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsharepoint/299)*

**Comment by ykuijs** [comment]
Review status: 1 of 7 files reviewed at latest revision, 6 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/powershell/xsharepoint/299#-KJDPwMfu5-p2UfRkwp9:-KJjClK1tajwmYyNgncM:-538218252) (no related file):*
<details><summary><i>Previously, BrianFarnhill (Brian Farnhill) wrote…</i></summary>
> There is a merge conflict here - I suspect it's going to be just the CHANGELOG but have a look and update accordingly. Thanks Bud
</details>
@brianfarnhill Comments processed. Ready for another review.

---

*[Modules/SharePointDSC/DSCResources/MSFT_SPWebAppPermissions/MSFT_SPWebAppPermissions.psm1, line 34 \[r1\]](https://reviewable.io:443/reviews/powershell/xsharepoint/299#-KJDMcr_6-lf3ZmqiN6K:-KJjCfe3HDtq0T7wv8hc:-499146009) ([raw file](https://github.com/powershell/xsharepoint/blob/cabe0430404a85d431a8d0bec87f254e65997bcf/Modules/SharePointDSC/DSCResources/MSFT_SPWebAppPermissions/MSFT_SPWebAppPermissions.psm1#L34)):*
<details><summary><i>Previously, BrianFarnhill (Brian Farnhill) wrote…</i></summary>
> This is a bit of a monster line. Can we look at refactoring this a little. Either a) split it over multiple lines (example below), or b) put the permissions you are checking for in to an array and then use Compare-Object or something like that to figure out if there are things in there that you are testing about. 
> 
>     if (($ListPermissions -contains "Manage Lists" `
>          -or $ListPermissions -contains "Override List Behaviors" `
>          -or $ListPermissions -contains "Add Items" `
>          -or $ListPermissions -contains "Edit Items" `
>          -or $ListPermissions -contains "Delete Items" `
>          -or $ListPermissions -contains "Approve Items" `
>          -or $ListPermissions -contains "Open Items" `
>          -or $ListPermissions -contains "View Versions" `
>          -or $ListPermissions -contains "Delete Versions" `
>          -or $ListPermissions -contains "Create Alerts" `
>          -or $SitePermissions -contains "Manage Permissions" `
>          -or $SitePermissions -contains "Manage Web Site" `
>          -or $SitePermissions -contains "Add and Customize Pages" `
>          -or $SitePermissions -contains "Manage Alerts" `
>          -or $SitePermissions -contains "Use Client Integration Features" `
>          -or $PersonalPermissions -contains "Manage Personal Views" `
>          -or $PersonalPermissions -contains "Add/Remove Personal Web Parts" `
>          -or $PersonalPermissions -contains "Update Personal Web Parts") `
>        -and -not ($ListPermissions -contains "View Items")) {
</details>
Done.

---

*[Modules/SharePointDSC/DSCResources/MSFT_SPWebAppPermissions/MSFT_SPWebAppPermissions.psm1, line 58 \[r1\]](https://reviewable.io:443/reviews/powershell/xsharepoint/299#-KJDNA292qqV8lQzTuvQ:-KJjCgjFdSbQ4OxkGBhi:-499146009) ([raw file](https://github.com/powershell/xsharepoint/blob/cabe0430404a85d431a8d0bec87f254e65997bcf/Modules/SharePointDSC/DSCResources/MSFT_SPWebAppPermissions/MSFT_SPWebAppPermissions.psm1#L58)):*
<details><summary><i>Previously, BrianFarnhill (Brian Farnhill) wrote…</i></summary>
> Same remark as above for refactoring the super long lines
</details>
Done.

---

*[Modules/SharePointDSC/DSCResources/MSFT_SPWebAppPermissions/MSFT_SPWebAppPermissions.psm1, line 74 \[r1\]](https://reviewable.io:443/reviews/powershell/xsharepoint/299#-KJDNLAZcxoma7lakPdQ:-KJjChgY_NDnDQaQ88hY:-499146009) ([raw file](https://github.com/powershell/xsharepoint/blob/cabe0430404a85d431a8d0bec87f254e65997bcf/Modules/SharePointDSC/DSCResources/MSFT_SPWebAppPermissions/MSFT_SPWebAppPermissions.psm1#L74)):*
<details><summary><i>Previously, BrianFarnhill (Brian Farnhill) wrote…</i></summary>
> Same remark again about the long lines
</details>
Done.

---

*[Modules/SharePointDSC/DSCResources/MSFT_SPWebAppPermissions/MSFT_SPWebAppPermissions.psm1, line 184 \[r1\]](https://reviewable.io:443/reviews/powershell/xsharepoint/299#-KJDNfFPHcHjXw-PcqDl:-KJjCigZeSyW61x-FUQB:-499146009) ([raw file](https://github.com/powershell/xsharepoint/blob/cabe0430404a85d431a8d0bec87f254e65997bcf/Modules/SharePointDSC/DSCResources/MSFT_SPWebAppPermissions/MSFT_SPWebAppPermissions.psm1#L184)):*
<details><summary><i>Previously, BrianFarnhill (Brian Farnhill) wrote…</i></summary>
> Instead of putting this complex logic at the top of each method, can you split it off to a function in this module (since it won't be called inside of an Invoke-SPDSCComannd block it'll see the function and will be able to call it fine) and then we can just call that from the top of each of the main methods.
</details>
Done.

---

*[Tests/SharePointDSC/SharePointDSC.SPWebAppPermissions.Tests.ps1, line 18 \[r1\]](https://reviewable.io:443/reviews/powershell/xsharepoint/299#-KJDPFfGfzfNDWmw32KM:-KJjCjaVEGYnBoqoeVhc:-499146009) ([raw file](https://github.com/powershell/xsharepoint/blob/cabe0430404a85d431a8d0bec87f254e65997bcf/Tests/SharePointDSC/SharePointDSC.SPWebAppPermissions.Tests.ps1#L18)):*
<details><summary><i>Previously, BrianFarnhill (Brian Farnhill) wrote…</i></summary>
> URL has one "/" in it
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsharepoint/299)*

**Comment by BrianFarnhill** [comment]
Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/powershell/sharepointdsc/299#-KJsJIQfTZgf7Zv1UJH8:-KJsJIQfTZgf7Zv1UJH9:1719741631) (no related file):*
Just some minor touch ups here and it's good to go. Thanks mate

---

*[Modules/SharePointDSC/DSCResources/MSFT_SPWebAppPermissions/MSFT_SPWebAppPermissions.psm1, line 16 \[r1\]](https://reviewable.io:443/reviews/powershell/sharepointdsc/299#-KJsIX7-l8jBB2NS07jQ:-KJsIX7-l8jBB2NS07jR:-1524908549) ([raw file](https://github.com/powershell/sharepointdsc/blob/6cf8ca51f0f43ba2f9c9444f6d4da67865e76835/Modules/SharePointDSC/DSCResources/MSFT_SPWebAppPermissions/MSFT_SPWebAppPermissions.psm1#L16)):*
> ```PowerShell
> 
>     Write-Verbose -Message "Getting permissions for Web Application '$WebAppUrl'"
>     Test-Input @PSBoundParameters
> ```

For any custom functions we right can we always name them "[verb]-SPDSC[noun]" - just so when someone is looking at the code its clear that the function is one of ours. 

---

*[Modules/SharePointDSC/DSCResources/MSFT_SPWebAppPermissions/MSFT_SPWebAppPermissions.psm1, line 101 \[r1\]](https://reviewable.io:443/reviews/powershell/sharepointdsc/299#-KJsIpNshNbYwqKdxHTg:-KJsIpNshNbYwqKdxHTh:-239952127) ([raw file](https://github.com/powershell/sharepointdsc/blob/6cf8ca51f0f43ba2f9c9444f6d4da67865e76835/Modules/SharePointDSC/DSCResources/MSFT_SPWebAppPermissions/MSFT_SPWebAppPermissions.psm1#L101)):*
> ```PowerShell
>     )
>     Write-Verbose -Message "Setting permissions for Web Application '$WebAppUrl'"
>     Test-Input @PSBoundParameters
> ```

Same on the cmdlet name here

---

*[Modules/SharePointDSC/DSCResources/MSFT_SPWebAppPermissions/MSFT_SPWebAppPermissions.psm1, line 193 \[r1\]](https://reviewable.io:443/reviews/powershell/sharepointdsc/299#-KJsIwtzGWLxtZVsyTAs:-KJsIwtzGWLxtZVsyTAt:-239952127) ([raw file](https://github.com/powershell/sharepointdsc/blob/6cf8ca51f0f43ba2f9c9444f6d4da67865e76835/Modules/SharePointDSC/DSCResources/MSFT_SPWebAppPermissions/MSFT_SPWebAppPermissions.psm1#L193)):*
> ```PowerShell
> 
>     Write-Verbose -Message "Testing permissions for Web Application '$WebAppUrl'"
>     Test-Input @PSBoundParameters
> ```

Same on the cmdlet name here

---

*[Modules/SharePointDSC/DSCResources/MSFT_SPWebAppPermissions/MSFT_SPWebAppPermissions.psm1, line 217 \[r1\]](https://reviewable.io:443/reviews/powershell/sharepointdsc/299#-KJsIzxvFBfSF0I61Bnc:-KJsIzxvFBfSF0I61Bnd:-749362697) ([raw file](https://github.com/powershell/sharepointdsc/blob/6cf8ca51f0f43ba2f9c9444f6d4da67865e76835/Modules/SharePointDSC/DSCResources/MSFT_SPWebAppPermissions/MSFT_SPWebAppPermissions.psm1#L217)):*
> ```PowerShell
> Export-ModuleMember -Function *-TargetResource
> 
> function Test-Input() {
> ```

And the cmdlet name here too

---

*[Modules/SharePointDSC/DSCResources/MSFT_SPWebAppPermissions/MSFT_SPWebAppPermissions.psm1, line 377 \[r1\]](https://reviewable.io:443/reviews/powershell/sharepointdsc/299#-KJsJ5saPaKgvSLKxxra:-KJsJ5saPaKgvSLKxxrb:696673515) ([raw file](https://github.com/powershell/sharepointdsc/blob/6cf8ca51f0f43ba2f9c9444f6d4da67865e76835/Modules/SharePointDSC/DSCResources/MSFT_SPWebAppPermissions/MSFT_SPWebAppPermissions.psm1#L377)):*
> ```PowerShell
>         Throw "Update Personal Web Parts is required when specifying Add/Remove Personal Web Parts"
>     }
> }
> ```

Need an empty line at the end of this file

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/299)*

**Comment by ykuijs** [comment]
Review status: 2 of 7 files reviewed at latest revision, 6 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/powershell/sharepointdsc/299#-KJsJIQfTZgf7Zv1UJH8:-KJt8PdaHl-fnHTKpRNT:23655569) (no related file):*
<details><summary><i>Previously, BrianFarnhill (Brian Farnhill) wrote…</i></summary>
> Just some minor touch ups here and it's good to go. Thanks mate
</details>
Touch ups done!

---

*[Modules/SharePointDSC/DSCResources/MSFT_SPWebAppPermissions/MSFT_SPWebAppPermissions.psm1, line 16 \[r1\]](https://reviewable.io:443/reviews/powershell/sharepointdsc/299#-KJsIX7-l8jBB2NS07jQ:-KJt8LwbixI9MIUc4F78:-499146009) ([raw file](https://github.com/powershell/sharepointdsc/blob/6cf8ca51f0f43ba2f9c9444f6d4da67865e76835/Modules/SharePointDSC/DSCResources/MSFT_SPWebAppPermissions/MSFT_SPWebAppPermissions.psm1#L16)):*
<details><summary><i>Previously, BrianFarnhill (Brian Farnhill) wrote…</i></summary>
> For any custom functions we right can we always name them "[verb]-SPDSC[noun]" - just so when someone is looking at the code its clear that the function is one of ours. 
</details>
Done.

---

*[Modules/SharePointDSC/DSCResources/MSFT_SPWebAppPermissions/MSFT_SPWebAppPermissions.psm1, line 101 \[r1\]](https://reviewable.io:443/reviews/powershell/sharepointdsc/299#-KJsIpNshNbYwqKdxHTg:-KJt8Mk1rwN-pPV_cFzb:-499146009) ([raw file](https://github.com/powershell/sharepointdsc/blob/6cf8ca51f0f43ba2f9c9444f6d4da67865e76835/Modules/SharePointDSC/DSCResources/MSFT_SPWebAppPermissions/MSFT_SPWebAppPermissions.psm1#L101)):*
<details><summary><i>Previously, BrianFarnhill (Brian Farnhill) wrote…</i></summary>
> Same on the cmdlet name here
</details>
Done.

---

*[Modules/SharePointDSC/DSCResources/MSFT_SPWebAppPermissions/MSFT_SPWebAppPermissions.psm1, line 193 \[r1\]](https://reviewable.io:443/reviews/powershell/sharepointdsc/299#-KJsIwtzGWLxtZVsyTAs:-KJt8NTtx3glMFl8qtA5:-499146009) ([raw file](https://github.com/powershell/sharepointdsc/blob/6cf8ca51f0f43ba2f9c9444f6d4da67865e76835/Modules/SharePointDSC/DSCResources/MSFT_SPWebAppPermissions/MSFT_SPWebAppPermissions.psm1#L193)):*
<details><summary><i>Previously, BrianFarnhill (Brian Farnhill) wrote…</i></summary>
> Same on the cmdlet name here
</details>
Done.

---

*[Modules/SharePointDSC/DSCResources/MSFT_SPWebAppPermissions/MSFT_SPWebAppPermissions.psm1, line 217 \[r1\]](https://reviewable.io:443/reviews/powershell/sharepointdsc/299#-KJsIzxvFBfSF0I61Bnc:-KJt8O37pCu3RU87kyTS:-499146009) ([raw file](https://github.com/powershell/sharepointdsc/blob/6cf8ca51f0f43ba2f9c9444f6d4da67865e76835/Modules/SharePointDSC/DSCResources/MSFT_SPWebAppPermissions/MSFT_SPWebAppPermissions.psm1#L217)):*
<details><summary><i>Previously, BrianFarnhill (Brian Farnhill) wrote…</i></summary>
> And the cmdlet name here too
</details>
Done.

---

*[Modules/SharePointDSC/DSCResources/MSFT_SPWebAppPermissions/MSFT_SPWebAppPermissions.psm1, line 377 \[r1\]](https://reviewable.io:443/reviews/powershell/sharepointdsc/299#-KJsJ5saPaKgvSLKxxra:-KJt8ObFWwIIferb4nkH:-499146009) ([raw file](https://github.com/powershell/sharepointdsc/blob/6cf8ca51f0f43ba2f9c9444f6d4da67865e76835/Modules/SharePointDSC/DSCResources/MSFT_SPWebAppPermissions/MSFT_SPWebAppPermissions.psm1#L377)):*
<details><summary><i>Previously, BrianFarnhill (Brian Farnhill) wrote…</i></summary>
> Need an empty line at the end of this file
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/299)*

**Comment by BrianFarnhill** [comment]
Reviewed 5 of 7 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/299)*

**Comment by BrianFarnhill** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/powershell/sharepointdsc/299#-KJtn85HsvzEEQT8Como:-KJtn85HsvzEEQT8Comp:972910993) (no related file):*
Needs a merge resolved (probably changelog.md after the last PR closed) and then its good to go

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/299)*

**Comment by ykuijs** [comment]
Merge done, AppVeyor check running as we speak

**Comment by BrianFarnhill** [comment]
Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/299)*

**Pull request merged**
