### PR TITLE
Fixes for MySiteHostLocation and Managed Path

### PR DESCRIPTION
**Pull request by NikCharlebois**
Fixing issue #770 

- [x] Change details added to Unreleased section of changelog.md?
- [x] Added/updated documentation and descriptions in .schema.mof files where appropriate?
- [x] Examples updated for both the single server and small farm templates in the examples folder?
- [x] New/changed code adheres to [Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md)?
- [ ] [Unit and Integration tests](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md) created/updated where possible?

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/sharepointdsc/787)

### CODE REVIEW

**Comment by ykuijs** [comment]
Few small comments. If you update them, I will merge the PR

---

Reviewed 4 of 5 files at r1, 1 of 2 files at r2.
Review status: 5 of 6 files reviewed at latest revision, 3 unresolved discussions.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPUserProfileServiceApp/MSFT_SPUserProfileServiceApp.psm1, line 170 at r2](https://reviewable.io:443/reviews/powershell/sharepointdsc/787#-L8XKbXlts_CSYxCNfAP:-L8XKbXlts_CSYxCNfAQ:b4gvaei) ([raw file](https://github.com/powershell/sharepointdsc/blob/51c8dea8616b4e9de4775b11a3db66d91e3d1470/Modules/SharePointDsc/DSCResources/MSFT_SPUserProfileServiceApp/MSFT_SPUserProfileServiceApp.psm1#L170)):*
> ```PowerShell
>             $upMySiteManagedPath = $null
>             try {
>                 $ca = Get-SPWebApplication -IncludeCentralAdministration | Where-Object {$_.IsAdministrationWebApplication}
> ```

Please change "Where-Object" to "Where-Object -FilterScript"

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPUserProfileServiceApp/MSFT_SPUserProfileServiceApp.psm1, line 171 at r2](https://reviewable.io:443/reviews/powershell/sharepointdsc/787#-L8XKk3xcSRXmcclI5xK:-L8XKk3xcSRXmcclI5xL:b-b2i3ih) ([raw file](https://github.com/powershell/sharepointdsc/blob/51c8dea8616b4e9de4775b11a3db66d91e3d1470/Modules/SharePointDsc/DSCResources/MSFT_SPUserProfileServiceApp/MSFT_SPUserProfileServiceApp.psm1#L171)):*
> ```PowerShell
>             try {
>                 $ca = Get-SPWebApplication -IncludeCentralAdministration | Where-Object {$_.IsAdministrationWebApplication}
>                 $caSite = $ca.Sites[0];
> ```

Semicolon not required ;-)

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPUserProfileServiceApp/MSFT_SPUserProfileServiceApp.psm1, line 173 at r2](https://reviewable.io:443/reviews/powershell/sharepointdsc/787#-L8XKorq9i_oFhfJKuQ6:-L8XKorq9i_oFhfJKuQ7:bnhk9ij) ([raw file](https://github.com/powershell/sharepointdsc/blob/51c8dea8616b4e9de4775b11a3db66d91e3d1470/Modules/SharePointDsc/DSCResources/MSFT_SPUserProfileServiceApp/MSFT_SPUserProfileServiceApp.psm1#L173)):*
> ```PowerShell
>                 $caSite = $ca.Sites[0];
>                 $serviceContext = Get-SPServiceContext($caSite)
>                 $userProfileManager = new-object Microsoft.Office.Server.UserProfiles.UserProfileManager($serviceContext)
> ```

Please update to New-Object

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/787#-:-L8XM6b3qCPFmgBfxtCk:b-ysql0f)*

**Comment by NikCharlebois** [comment]
Review status: 5 of 6 files reviewed at latest revision, 3 unresolved discussions.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPUserProfileServiceApp/MSFT_SPUserProfileServiceApp.psm1, line 170 at r2](https://beta.reviewable.io/reviews/powershell/sharepointdsc/787#-L8XKbXlts_CSYxCNfAP:-L8Y8aw469DGuJ6WDDdG:bb6un1j) ([raw file](https://github.com/powershell/sharepointdsc/blob/51c8dea8616b4e9de4775b11a3db66d91e3d1470/Modules/SharePointDsc/DSCResources/MSFT_SPUserProfileServiceApp/MSFT_SPUserProfileServiceApp.psm1#L170)):*
<details><summary><i>Previously, ykuijs (Yorick Kuijs) wrote…</i></summary><blockquote>

Please change "Where-Object" to "Where-Object -FilterScript"
</blockquote></details>

Done

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPUserProfileServiceApp/MSFT_SPUserProfileServiceApp.psm1, line 171 at r2](https://beta.reviewable.io/reviews/powershell/sharepointdsc/787#-L8XKk3xcSRXmcclI5xK:-L8Y8YN74srgUeeEFaBt:b2knlnc) ([raw file](https://github.com/powershell/sharepointdsc/blob/51c8dea8616b4e9de4775b11a3db66d91e3d1470/Modules/SharePointDsc/DSCResources/MSFT_SPUserProfileServiceApp/MSFT_SPUserProfileServiceApp.psm1#L171)):*
<details><summary><i>Previously, ykuijs (Yorick Kuijs) wrote…</i></summary><blockquote>

Semicolon not required ;-)
</blockquote></details>

Good old C# habits die hard;

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/powershell/sharepointdsc/787)*

**Comment by NikCharlebois** [comment]
Review status: 5 of 6 files reviewed at latest revision, 3 unresolved discussions.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPUserProfileServiceApp/MSFT_SPUserProfileServiceApp.psm1, line 173 at r2](https://beta.reviewable.io/reviews/powershell/sharepointdsc/787#-L8XKorq9i_oFhfJKuQ6:-L8Y8qt93Eu8UlPGnhY5:b-896fix) ([raw file](https://github.com/powershell/sharepointdsc/blob/51c8dea8616b4e9de4775b11a3db66d91e3d1470/Modules/SharePointDsc/DSCResources/MSFT_SPUserProfileServiceApp/MSFT_SPUserProfileServiceApp.psm1#L173)):*
<details><summary><i>Previously, ykuijs (Yorick Kuijs) wrote…</i></summary><blockquote>

Please update to New-Object
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/powershell/sharepointdsc/787)*

**Comment by ykuijs** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/787#-:-L8aOYLGqPkg_hUJc-8W:bnfp4nl)*

**Pull request merged**
