### PR TITLE
Sp proxy groups, issue #300

### PR DESCRIPTION
**Pull request by MikeLacher448**
Thanks for submitting a Pull Request to this project.

Please make sure you have read the [Contribution Guidelines](https://github.com/powershell/xSharePoint/wiki/Contributing%20to%20xSharePoint).

To aid community reviewers in reviewing and merging your PR, please take the time to run through this checklist:
- [x] Change details added to Unreleased section of readme.md?
- [x] Added/updated documentation and descriptions in .schema.mof files where appropriate?
- [ ] Examples updated for both the single server and small farm templates in the examples folder?
- [x] New/changed code adheres to [Style Guidelines]?(https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md)?
- [x] [Unit and Integration tests](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md) created/updated where possible?

Your contribution to this project is greatly appreciated. 

SPServiceAppProxyGroup and SPWebAppProxyGroup resources as discussed on issue #300

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/sharepointdsc/323)

### CODE REVIEW

**Comment by BrianFarnhill** [comment]
Reviewed 7 of 7 files at r1.
Review status: 4 of 7 files reviewed at latest revision, 21 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/powershell/sharepointdsc/323#-KKQeT0NxY3LVJXEP9i8:-KKQeT0NxY3LVJXEP9i9:-1734761207) (no related file):*
Can I get you to do a pull from PowerShell/dev and make sure that the commits you are making all have "SharePointDsc" with the lowercase "SC" at the end of it (so "SharePointDsc" not "SharePointDSC"). Windows isn't case sensitive so its hard to catch these things but I've had to make a few commits to fix this elsewhere. You might need to use "git mv" to rename the files to something else and then name them back with the lower case titles. I know it's a bit fiddly but we need to keep it named like the lower case option to meet the naming standards.

---

*[CHANGELOG.md, line 10 \[r1\]](https://reviewable.io:443/reviews/powershell/sharepointdsc/323#-KKQ_0M7jM4Lq-QLypO_:-KKQ_0M7jM4Lq-QLypOa:-1242481947) ([raw file](https://github.com/powershell/sharepointdsc/blob/adc5dd2f270d59c40d55fd4268a481c5a6e37c7b/CHANGELOG.md#L10)):*
> ```Markdown
>  * Fixed a bug with SPTimerJobState that prevented a custom schedule being applied to a timer job
>  * Fixed a bug with the detection of group principals vs. user principals in SPServiceAppSecurity and SPWebAppPolicy
>  * Added SPServiceAppProxyGroup and SPWebAppProxyGroup resources
> ```

Can you consolidate these on to the line at the top of this block with the other new resources?

    * Added SPBlobCacheSettings, SPOfficeOnlineServerBinding, SPWebAppPermissions , SPServiceAppProxyGroup and SPWebAppProxyGroup resources

---

*[Modules/SharePointDSC/DSCResources/MSFT_SPServiceAppProxyGroup/MSFT_SPServiceAppProxyGroup.psm1, line 8 \[r1\]](https://reviewable.io:443/reviews/powershell/sharepointdsc/323#-KKQ_FyNZSbC2SgClWiv:-KKQ_FyNZSbC2SgClWiw:758405247) ([raw file](https://github.com/powershell/sharepointdsc/blob/adc5dd2f270d59c40d55fd4268a481c5a6e37c7b/Modules/SharePointDSC/DSCResources/MSFT_SPServiceAppProxyGroup/MSFT_SPServiceAppProxyGroup.psm1#L8)):*
> ```PowerShell
>     (
>         [parameter(Mandatory = $true)]  [System.String]   $Name,
>         [parameter(Mandatory = $true)]  [System.String][ValidateSet("Present","Absent")] $Ensure,
> ```

Ensure should be optional and default to "present"

        [parameter(Mandatory = $false)]  [System.String][ValidateSet("Present","Absent")] $Ensure = "Present",

---

*[Modules/SharePointDSC/DSCResources/MSFT_SPServiceAppProxyGroup/MSFT_SPServiceAppProxyGroup.psm1, line 24 \[r1\]](https://reviewable.io:443/reviews/powershell/sharepointdsc/323#-KKQaHpYNOqvexfTiEwV:-KKQaHpYNOqvexfTiEwW:-297083129) ([raw file](https://github.com/powershell/sharepointdsc/blob/adc5dd2f270d59c40d55fd4268a481c5a6e37c7b/Modules/SharePointDSC/DSCResources/MSFT_SPServiceAppProxyGroup/MSFT_SPServiceAppProxyGroup.psm1#L24)):*
> ```PowerShell
>             return $null  
>         }
>         
> ```

Can we drop a Write-Verbose in here to say something about starting the get method for the proxy group? Same as you have at the top of the set method pretty much

---

*[Modules/SharePointDSC/DSCResources/MSFT_SPServiceAppProxyGroup/MSFT_SPServiceAppProxyGroup.psm1, line 32 \[r1\]](https://reviewable.io:443/reviews/powershell/sharepointdsc/323#-KKQ_VbmHMPI68g1NykI:-KKQ_VbmHMPI68g1NykJ:-1244761931) ([raw file](https://github.com/powershell/sharepointdsc/blob/adc5dd2f270d59c40d55fd4268a481c5a6e37c7b/Modules/SharePointDSC/DSCResources/MSFT_SPServiceAppProxyGroup/MSFT_SPServiceAppProxyGroup.psm1#L32)):*
> ```PowerShell
>                 $ProxyGroup = Get-SPServiceApplicationProxyGroup -Default
>             } else {
>                 $ProxyGroup = Get-SPServiceApplicationProxyGroup $params.name -EA 0 
> ```

We need to avoid using aliases, can you swap the "-EA 0" out for "-ErrorAction SilentlyContinue" here?

---

*[Modules/SharePointDSC/DSCResources/MSFT_SPServiceAppProxyGroup/MSFT_SPServiceAppProxyGroup.psm1, line 67 \[r1\]](https://reviewable.io:443/reviews/powershell/sharepointdsc/323#-KKQaP7c73vmNCXlk0zO:-KKQaP7dETHaufHO5Fdw:-235331430) ([raw file](https://github.com/powershell/sharepointdsc/blob/adc5dd2f270d59c40d55fd4268a481c5a6e37c7b/Modules/SharePointDSC/DSCResources/MSFT_SPServiceAppProxyGroup/MSFT_SPServiceAppProxyGroup.psm1#L67)):*
> ```PowerShell
>     (
>         [parameter(Mandatory = $true)]  [System.String]   $Name,
>         [parameter(Mandatory = $true)]  [System.String][ValidateSet("Present","Absent")] $Ensure,
> ```

Same comment about ensure being optional

---

*[Modules/SharePointDSC/DSCResources/MSFT_SPServiceAppProxyGroup/MSFT_SPServiceAppProxyGroup.psm1, line 234 \[r1\]](https://reviewable.io:443/reviews/powershell/sharepointdsc/323#-KKQcAQQ40qLd00vQXmI:-KKQcAQQ40qLd00vQXmJ:-2016627094) ([raw file](https://github.com/powershell/sharepointdsc/blob/adc5dd2f270d59c40d55fd4268a481c5a6e37c7b/Modules/SharePointDSC/DSCResources/MSFT_SPServiceAppProxyGroup/MSFT_SPServiceAppProxyGroup.psm1#L234)):*
> ```PowerShell
> 
> 
> function test-TargetResource
> ```

I know this is pedantic but can we make the start of test capitalised? Test-TargetResource

---

*[Modules/SharePointDSC/DSCResources/MSFT_SPServiceAppProxyGroup/MSFT_SPServiceAppProxyGroup.psm1, line 241 \[r1\]](https://reviewable.io:443/reviews/powershell/sharepointdsc/323#-KKQcG8pVh57qi7hMJpF:-KKQcG8pVh57qi7hMJpG:-235331430) ([raw file](https://github.com/powershell/sharepointdsc/blob/adc5dd2f270d59c40d55fd4268a481c5a6e37c7b/Modules/SharePointDSC/DSCResources/MSFT_SPServiceAppProxyGroup/MSFT_SPServiceAppProxyGroup.psm1#L241)):*
> ```PowerShell
>     (
>         [parameter(Mandatory = $true)]  [System.String]   $Name,
>         [parameter(Mandatory = $true)]  [System.String][ValidateSet("Present","Absent")] $Ensure,
> ```

Same comment about ensure being optional

---

*[Modules/SharePointDSC/DSCResources/MSFT_SPServiceAppProxyGroup/MSFT_SPServiceAppProxyGroup.psm1, line 304 \[r1\]](https://reviewable.io:443/reviews/powershell/sharepointdsc/323#-KKQcSLW2REM6vxDTIGS:-KKQcSLW2REM6vxDTIGT:80337811) ([raw file](https://github.com/powershell/sharepointdsc/blob/adc5dd2f270d59c40d55fd4268a481c5a6e37c7b/Modules/SharePointDSC/DSCResources/MSFT_SPServiceAppProxyGroup/MSFT_SPServiceAppProxyGroup.psm1#L304)):*
> ```PowerShell
>     
>     return $true 
> }
> ```

We need an empty new line at the end of this file

---

*[Modules/SharePointDSC/DSCResources/MSFT_SPServiceAppProxyGroup/MSFT_SPServiceAppProxyGroup.schema.mof, line 16 \[r1\]](https://reviewable.io:443/reviews/powershell/sharepointdsc/323#-KKQcZD9sZplTdY4MAjn:-KKQcZD9sZplTdY4MAjo:-729900594) ([raw file](https://github.com/powershell/sharepointdsc/blob/adc5dd2f270d59c40d55fd4268a481c5a6e37c7b/Modules/SharePointDSC/DSCResources/MSFT_SPServiceAppProxyGroup/MSFT_SPServiceAppProxyGroup.schema.mof#L16)):*
> ```
> Do not combine the ServiceAppProxies property with the ServiceAppProxiesToInclude and ServiceAppProxiesToExclude properties.
> ```

Can you add this line above the examples?

    **Examples**

---

*[Modules/SharePointDSC/DSCResources/MSFT_SPServiceAppProxyGroup/MSFT_SPServiceAppProxyGroup.schema.mof, line 19 \[r1\]](https://reviewable.io:443/reviews/powershell/sharepointdsc/323#-KKQcgDsgXREuy8PiftY:-KKQcgDsgXREuy8PiftZ:1478723543) ([raw file](https://github.com/powershell/sharepointdsc/blob/adc5dd2f270d59c40d55fd4268a481c5a6e37c7b/Modules/SharePointDSC/DSCResources/MSFT_SPServiceAppProxyGroup/MSFT_SPServiceAppProxyGroup.schema.mof#L19)):*
> ```
>    SPServiceAppProxyGroup TenantGroup1
>     {
>         Name                = "Tenant Group 1"
> ```

Can I get you to make these examples not use the words "tenant" - we aren't going to support multi-tenancy in SharePointDsc so I want to make sure people don't get confused here.

---

*[Modules/SharePointDSC/DSCResources/MSFT_SPServiceAppProxyGroup/MSFT_SPServiceAppProxyGroup.schema.mof, line 36 \[r1\]](https://reviewable.io:443/reviews/powershell/sharepointdsc/323#-KKQcqm0jh26fkXJ0wFC:-KKQcqm0jh26fkXJ0wFD:141904118) ([raw file](https://github.com/powershell/sharepointdsc/blob/adc5dd2f270d59c40d55fd4268a481c5a6e37c7b/Modules/SharePointDSC/DSCResources/MSFT_SPServiceAppProxyGroup/MSFT_SPServiceAppProxyGroup.schema.mof#L36)):*
> ```
> {
>     [Key, Description("Name of the Proxy Group to create")] String Name;
>     [Write, Description(".."), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] string Ensure;
> ```

Can I get you to put some descriptions on these properties please? 

---

*[Modules/SharePointDSC/DSCResources/MSFT_SPServiceAppProxyGroup/MSFT_SPServiceAppProxyGroup.schema.mof, line 41 \[r1\]](https://reviewable.io:443/reviews/powershell/sharepointdsc/323#-KKQcoqCNnJ0Dtv-J-gI:-KKQcoqCNnJ0Dtv-J-gJ:-657406214) ([raw file](https://github.com/powershell/sharepointdsc/blob/adc5dd2f270d59c40d55fd4268a481c5a6e37c7b/Modules/SharePointDSC/DSCResources/MSFT_SPServiceAppProxyGroup/MSFT_SPServiceAppProxyGroup.schema.mof#L41)):*
> ```
>     [Write, Description("..")] String ServiceAppProxiesToExclude[];
>     [Write, Description("POWERSHELL 4 ONLY: The account to run this resource as, use PsDscRunAsAccount if using PowerShell 5"), EmbeddedInstance("MSFT_Credential")] String InstallAccount;
> };
> ```

Need a blank new line at the end of this file

---

*[Modules/SharePointDSC/DSCResources/MSFT_SPWebAppProxyGroup/MSFT_SPWebAppProxyGroup.psm1, line 7 \[r1\]](https://reviewable.io:443/reviews/powershell/sharepointdsc/323#-KKQe0yCR-vL-Lfpz8et:-KKQe0yDCL2c99ZLOZws:1390144228) ([raw file](https://github.com/powershell/sharepointdsc/blob/adc5dd2f270d59c40d55fd4268a481c5a6e37c7b/Modules/SharePointDSC/DSCResources/MSFT_SPWebAppProxyGroup/MSFT_SPWebAppProxyGroup.psm1#L7)):*
> ```PowerShell
>     param
>     (
>         [parameter(Mandatory = $true)]  [System.String] $URL,
> ```

Can web make this WebAppUrl just to be clear about the URL that we expect here?

---

*[Modules/SharePointDSC/DSCResources/MSFT_SPWebAppProxyGroup/MSFT_SPWebAppProxyGroup.psm1, line 18 \[r1\]](https://reviewable.io:443/reviews/powershell/sharepointdsc/323#-KKQdJ9dQBAqJKf6aFpm:-KKQdJ9dQBAqJKf6aFpn:-1419615939) ([raw file](https://github.com/powershell/sharepointdsc/blob/adc5dd2f270d59c40d55fd4268a481c5a6e37c7b/Modules/SharePointDSC/DSCResources/MSFT_SPWebAppProxyGroup/MSFT_SPWebAppProxyGroup.psm1#L18)):*
> ```PowerShell
>             
>         $WebApp = get-spwebapplication $params.url
>         if (!$WebApp) { return $null }
> ```

Rather than return $null can we return a hashtable with a null value on the URL property?

    return @{
        Url = $null
        ServiceAppProxyGroup = $null
        InstallAccount = $params.InstallAccount
    }

---

*[Modules/SharePointDSC/DSCResources/MSFT_SPWebAppProxyGroup/MSFT_SPWebAppProxyGroup.psm1, line 81 \[r1\]](https://reviewable.io:443/reviews/powershell/sharepointdsc/323#-KKQeAJn8FIwjDWNe87K:-KKQeAJn8FIwjDWNe87L:1023428513) ([raw file](https://github.com/powershell/sharepointdsc/blob/adc5dd2f270d59c40d55fd4268a481c5a6e37c7b/Modules/SharePointDSC/DSCResources/MSFT_SPWebAppProxyGroup/MSFT_SPWebAppProxyGroup.psm1#L81)):*
> ```PowerShell
>         return $false 
>     }
> }
> ```

Need a new empty line at the end of this file

---

*[Modules/SharePointDSC/DSCResources/MSFT_SPWebAppProxyGroup/MSFT_SPWebAppProxyGroup.schema.mof, line 15 \[r1\]](https://reviewable.io:443/reviews/powershell/sharepointdsc/323#-KKQeENvK80F4nRX_h9S:-KKQeENvK80F4nRX_h9T:390978522) ([raw file](https://github.com/powershell/sharepointdsc/blob/adc5dd2f270d59c40d55fd4268a481c5a6e37c7b/Modules/SharePointDSC/DSCResources/MSFT_SPWebAppProxyGroup/MSFT_SPWebAppProxyGroup.schema.mof#L15)):*
> ```
>     {
>         URL                = "https://web.contoso.com"
>         ServiceAppProxyGroup  = "Tenant Group 1"
> ```

Again can we drop the references to the term "tenant" here?

---

*[Modules/SharePointDSC/DSCResources/MSFT_SPWebAppProxyGroup/MSFT_SPWebAppProxyGroup.schema.mof, line 28 \[r1\]](https://reviewable.io:443/reviews/powershell/sharepointdsc/323#-KKQeJwdqUkgIFcv0Nyd:-KKQeJwdqUkgIFcv0Nye:-473656327) ([raw file](https://github.com/powershell/sharepointdsc/blob/adc5dd2f270d59c40d55fd4268a481c5a6e37c7b/Modules/SharePointDSC/DSCResources/MSFT_SPWebAppProxyGroup/MSFT_SPWebAppProxyGroup.schema.mof#L28)):*
> ```
> class MSFT_SPWebAppProxyGroup : OMI_BaseResource
> {
>     [Key, Description("URL of the web application")] String URL;
> ```

Same as above, can we change this to WebAppUrl

---

*[Modules/SharePointDSC/DSCResources/MSFT_SPWebAppProxyGroup/MSFT_SPWebAppProxyGroup.schema.mof, line 31 \[r1\]](https://reviewable.io:443/reviews/powershell/sharepointdsc/323#-KKQeI8mTnQ-_3VlBrDw:-KKQeI8mTnQ-_3VlBrDx:-618886521) ([raw file](https://github.com/powershell/sharepointdsc/blob/adc5dd2f270d59c40d55fd4268a481c5a6e37c7b/Modules/SharePointDSC/DSCResources/MSFT_SPWebAppProxyGroup/MSFT_SPWebAppProxyGroup.schema.mof#L31)):*
> ```
>     [Required, Description("Name of the Service Applicaiton Proxy Group")] string ServiceAppProxyGroup; 
>     [Write, Description("POWERSHELL 4 ONLY: The account to run this resource as, use PsDscRunAsAccount if using PowerShell 5"), EmbeddedInstance("MSFT_Credential")] String InstallAccount;
> };
> ```

Need a new line on the end of the file

---

*[Tests/SharePointDSC/SharePointDSC.SPServiceAppProxyGroup.tests.ps1, line 29 \[r1\]](https://reviewable.io:443/reviews/powershell/sharepointdsc/323#-KKQfAbT1Eqik632uXO1:-KKQfAbT1Eqik632uXO2:-1871262418) ([raw file](https://github.com/powershell/sharepointdsc/blob/adc5dd2f270d59c40d55fd4268a481c5a6e37c7b/Tests/SharePointDSC/SharePointDSC.SPServiceAppProxyGroup.tests.ps1#L29)):*
> ```PowerShell
>         
>         $ListofAllServiceAppProxies = @(
>             "Tenant 1 User Profile Service Application",
> ```

Again with removing the references to "tenant" please

---

*[Tests/SharePointDSC/SharePointDSC.SPServiceAppProxyGroup.tests.ps1, line 35 \[r1\]](https://reviewable.io:443/reviews/powershell/sharepointdsc/323#-KKQfIbY4YcEZInFbF2b:-KKQfIbZkTiZivQs486D:-1879118681) ([raw file](https://github.com/powershell/sharepointdsc/blob/adc5dd2f270d59c40d55fd4268a481c5a6e37c7b/Tests/SharePointDSC/SharePointDSC.SPServiceAppProxyGroup.tests.ps1#L35)):*
> ```PowerShell
>         )
>         
>         Mock Import-Module {} -ParameterFilter { $_.Name -eq $ModuleName }
> ```

Why are you mocking Import-Module here? We should be able to just let that run as per usual to ensure the paths to our modules are good and can be loaded properly. I don't recall seeing import-module statements in there either? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/323)*

**Comment by MikeLacher448** [comment]
Review status: 4 of 7 files reviewed at latest revision, 21 unresolved discussions, some commit checks failed.

---

*[Tests/SharePointDSC/SharePointDSC.SPServiceAppProxyGroup.tests.ps1, line 35 \[r1\]](https://reviewable.io:443/reviews/powershell/sharepointdsc/323#-KKQfIbY4YcEZInFbF2b:-KKRCuHtY57dZLKX1BYv:-1896119329) ([raw file](https://github.com/powershell/sharepointdsc/blob/adc5dd2f270d59c40d55fd4268a481c5a6e37c7b/Tests/SharePointDSC/SharePointDSC.SPServiceAppProxyGroup.tests.ps1#L35)):*
<details><summary><i>Previously, BrianFarnhill (Brian Farnhill) wrote…</i></summary>
> Why are you mocking Import-Module here? We should be able to just let that run as per usual to ensure the paths to our modules are good and can be loaded properly. I don't recall seeing import-module statements in there either? 
</details>
part of a different test file I used as a template. Got rid of it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/323)*

**Comment by BrianFarnhill** [comment]
Reviewed 7 of 7 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/323)*

**Comment by BrianFarnhill** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/powershell/sharepointdsc/323#-KKQeT0NxY3LVJXEP9i8:-KKg5Oq7BD1nRQDcXhsE:481141429) (no related file):*
<details><summary><i>Previously, BrianFarnhill (Brian Farnhill) wrote…</i></summary>
> Can I get you to do a pull from PowerShell/dev and make sure that the commits you are making all have "SharePointDsc" with the lowercase "SC" at the end of it (so "SharePointDsc" not "SharePointDSC"). Windows isn't case sensitive so its hard to catch these things but I've had to make a few commits to fix this elsewhere. You might need to use "git mv" to rename the files to something else and then name them back with the lower case titles. I know it's a bit fiddly but we need to keep it named like the lower case option to meet the naming standards.
</details>
The last thing I need you to pick up here is the casing on the rename I talked about above. If you go to https://github.com/MikeLacher448/xSharePoint/tree/ed14bdc52669638aace4f07704c5f021c54005bd/Modules and have a look there you'll see there are two folders caused by the incorrect case. Ping me on Skype if you need a hand using the "git mv" command to fix this one up. Once that's done im happy with the rest of the code and we can merge this in.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/323)*

**Comment by MikeLacher448** [comment]
Review status: 3 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/powershell/sharepointdsc/323#-KKQeT0NxY3LVJXEP9i8:-KKhn69bY8pBPs_sMVac:-104290440) (no related file):*
<details><summary><i>Previously, BrianFarnhill (Brian Farnhill) wrote…</i></summary>
> The last thing I need you to pick up here is the casing on the rename I talked about above. If you go to https://github.com/MikeLacher448/xSharePoint/tree/ed14bdc52669638aace4f07704c5f021c54005bd/Modules and have a look there you'll see there are two folders caused by the incorrect case. Ping me on Skype if you need a hand using the "git mv" command to fix this one up. Once that's done im happy with the rest of the code and we can merge this in.
</details>
I think I got it this time. If this doesn't work, I'll ping you later.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/323)*

**Comment by BrianFarnhill** [comment]
Review status: 3 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/powershell/sharepointdsc/323#-KKQeT0NxY3LVJXEP9i8:-KKkGVth-izeGYezztKS:-665965421) (no related file):*
<details><summary><i>Previously, MikeLacher448 (Mike Lacher) wrote…</i></summary>
> I think I got it this time. If this doesn't work, I'll ping you later.
</details>
Almost - you got the main DSC resource module, but the same thing happened in the tests folder. Once you repeat that there we are good to go :)

https://github.com/MikeLacher448/xSharePoint/tree/80062a6ba61d4ef9b0dcf8af8b2bb27c9b1ff50f/Tests

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/323)*

**Comment by BrianFarnhill** [comment]
@MikeLacher448 You'll also need to do a pull from PowerShell dev and resolve conflicts. It's just the changelog file, so a quick fix.

**Comment by BrianFarnhill** [comment]
Reviewed 8 of 8 files at r4, 5 of 5 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/323)*

**Pull request merged**
