### PR TITLE
Sp trusted root authority

### PR DESCRIPTION
**Pull request by mrpullen**
Resource to manage SPTrustedRootAuthority settings.

I couldn't test the New-SPTrustedRootAuthority, keeps giving me an error where it expects a x509Certificate2, instead of my PSObject.

- [ ] Change details added to Unreleased section of changelog.md?
- [ ] Added/updated documentation and descriptions in .schema.mof files where appropriate?
- [ ] Examples updated for both the single server and small farm templates in the examples folder?
- [ ] New/changed code adheres to [Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md)?
- [ ] [Unit and Integration tests](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md) created/updated where possible?

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/sharepointdsc/549)

### CODE REVIEW

**Comment by mrpullen** [comment]
Couldn't figure out how to setup unit test when I needed the XCertificate2 type.. I commented out, so any help :)

**Comment by BrianFarnhill** [comment]
I have a sneaking suspicion that last time we came up against this we "cheated" a little seeing as we couldn't mock a certificate up easily and just changed the mocks for those specific functions to all [object] instead of [System.Security.Cryptography.X509Certificates.X509Certificate2] ... its not ideal but I think it's the best way to get this done, so if you want to include changes to the stubs in this PR for that, open each stub (both 2013 and 2016) and do a search for "System.Security.Cryptography.X509Certificates.X509Certificate2" and replace it with "object". I'll approve bringing that in with this PR, then you can mock up any object in the tests as the certificate to pass around. 

---

Review status: 0 of 7 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/549#-:-KgMF3h7nwgFdKQ-Uri8:b1puw03)*

**Comment by mrpullen** [comment]
Awesome. Thanks.

**Comment by BrianFarnhill** [comment]
Reviewed 7 of 11 files at r2, 1 of 1 files at r3.
Review status: 8 of 10 files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPTrustedRootAuthority/MSFT_SPTrustedRootAuthority.psm1, line 13 at r3](https://reviewable.io:443/reviews/powershell/sharepointdsc/549#-KgNG8MXWxBr3hOKHZqR:-KgNG8MXWxBr3hOKHZqS:b-at3txt) ([raw file](https://github.com/powershell/sharepointdsc/blob/a782df97449819c6318200b4f95221b556ea095b/Modules/SharePointDsc/DSCResources/MSFT_SPTrustedRootAuthority/MSFT_SPTrustedRootAuthority.psm1#L13)):*
> ```PowerShell
>         [parameter(Mandatory = $true)]
>         [System.String]
>         $Certificate,
> ```

Can we change this to "CertificateThumbprint" to make sure its super obvious that we expect the thumbprint here?

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPTrustedRootAuthority/MSFT_SPTrustedRootAuthority.psm1, line 37 at r3](https://reviewable.io:443/reviews/powershell/sharepointdsc/549#-KgNGCY-b1Qzo463sVBG:-KgNGCY-b1Qzo463sVBH:b-t8h08b) ([raw file](https://github.com/powershell/sharepointdsc/blob/a782df97449819c6318200b4f95221b556ea095b/Modules/SharePointDsc/DSCResources/MSFT_SPTrustedRootAuthority/MSFT_SPTrustedRootAuthority.psm1#L37)):*
> ```PowerShell
>             return @{
>                 Name = $params.Name
>                 Certificate = $params.Certificate
> ```

If its not present don't return anything for certificate - [string]::Empty is fine, or $null

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPTrustedRootAuthority/MSFT_SPTrustedRootAuthority.psm1, line 88 at r3](https://reviewable.io:443/reviews/powershell/sharepointdsc/549#-KgNGWwEjUv3MmuAGHE3:-KgNGWwEjUv3MmuAGHE4:b-wmmaqf) ([raw file](https://github.com/powershell/sharepointdsc/blob/a782df97449819c6318200b4f95221b556ea095b/Modules/SharePointDsc/DSCResources/MSFT_SPTrustedRootAuthority/MSFT_SPTrustedRootAuthority.psm1#L88)):*
> ```PowerShell
>             $params = $args[0]
>             
>             $cert = Get-ChildItem -Path "CERT:\LocalMachine\My" | Where-Object `
> ```

Rather than doing a Get-ChildItem and then filtering, you can just do a Get-Item for "Cert:\LocalMachine\My\$($params.CertificateThumbprint)" with -ErrorAction SilentlyConitnue on the end. This means we dont retrieve every cert in full to then filter it down. 

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPTrustedRootAuthority/MSFT_SPTrustedRootAuthority.psm1, line 107 at r3](https://reviewable.io:443/reviews/powershell/sharepointdsc/549#-KgNHKv6PnNKksSFUDk6:-KgNHKv7zqV_FkyoyEkZ:b-5hb5po) ([raw file](https://github.com/powershell/sharepointdsc/blob/a782df97449819c6318200b4f95221b556ea095b/Modules/SharePointDsc/DSCResources/MSFT_SPTrustedRootAuthority/MSFT_SPTrustedRootAuthority.psm1#L107)):*
> ```PowerShell
>             $params = $args[0]
>             
>             $cert = Get-ChildItem -Path "CERT:\LocalMachine\My" | Where-Object `
> ```

Same comment here about the filter

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPTrustedRootAuthority/MSFT_SPTrustedRootAuthority.schema.mof, line 6 at r3](https://reviewable.io:443/reviews/powershell/sharepointdsc/549#-KgNG-bOvGJA62Zdni3c:-KgNG-bOvGJA62Zdni3d:b-at3txt) ([raw file](https://github.com/powershell/sharepointdsc/blob/a782df97449819c6318200b4f95221b556ea095b/Modules/SharePointDsc/DSCResources/MSFT_SPTrustedRootAuthority/MSFT_SPTrustedRootAuthority.schema.mof#L6)):*
> ```
> {
>     [Key, Description("Specifies the name of the trusted root authority to create.")] String Name;
>     [Required, Description("Specifies the X.509 certificate of the trusted root authority, as a certificate thumbprint.")] String Certificate;
> ```

Can we change this to "CertificateThumbprint" to make sure its super obvious that we expect the thumbprint here?

---

*[Tests/Unit/SharePointDsc/SharePointDsc.SPTrustedRootAuthority.Tests.ps1, line 50 at r3](https://reviewable.io:443/reviews/powershell/sharepointdsc/549#-KgNIJf_JrqnUFWNYdLm:-KgNIJf_JrqnUFWNYdLn:bns88k4) ([raw file](https://github.com/powershell/sharepointdsc/blob/a782df97449819c6318200b4f95221b556ea095b/Tests/Unit/SharePointDsc/SharePointDsc.SPTrustedRootAuthority.Tests.ps1#L50)):*
> ```PowerShell
>             }
> 
>             Mock -CommandName Set-SPTrustedRootAuthority -MockWith {
> ```

You can move this mock to the top of the file outside of the individual context statements (just after the "Invoke-Command -ScriptBlock $Global:SPDscHelper.InitializeScript -NoNewScope" line), as it doesn't change from one context to the next so this way we only define it once. 

---

*[Tests/Unit/SharePointDsc/SharePointDsc.SPTrustedRootAuthority.Tests.ps1, line 147 at r3](https://reviewable.io:443/reviews/powershell/sharepointdsc/549#-KgNIi6yDxCIwPw5oe8A:-KgNIi6yDxCIwPw5oe8B:b-5r56lo) ([raw file](https://github.com/powershell/sharepointdsc/blob/a782df97449819c6318200b4f95221b556ea095b/Tests/Unit/SharePointDsc/SharePointDsc.SPTrustedRootAuthority.Tests.ps1#L147)):*
> ```PowerShell
> 
>             It "Should throw a Certificate not found error" {
>                 { Set-TargetResource @testParams } | Should Throw "Certificate not found in the local Certificate Store"
> ```

I can see the throw statement here at line 93 of the main module, and I can see the test passing for this - but the code coverage thinks that the line isn't actually being hit. So really I'm just leaving this one here for me to check this again after you make the other changes to see if the code coverage updates. If not, I'll let it through anyway as Im sure its working based on the test result, but I wanted to leave myself a note to check it

---

*[Tests/Unit/SharePointDsc/SPManagedMetaDataServiceApp/1-CreateServiceApp.ps1, line 1 at r3](https://reviewable.io:443/reviews/powershell/sharepointdsc/549#-KgNI4ca9x96BIyc_4qC:-KgNI4ca9x96BIyc_4qD:b-55p5mc) ([raw file](https://github.com/powershell/sharepointdsc/blob/a782df97449819c6318200b4f95221b556ea095b/Tests/Unit/SharePointDsc/SPManagedMetaDataServiceApp/1-CreateServiceApp.ps1#L1)):*
> ```PowerShell
> <#
> ```

I think you might have accidently copied some files here that shouldn't be here?

---

*[Tests/Unit/SharePointDsc/SPManagedMetaDataServiceApp/2-RemoveServiceApp.ps1, line 2 at r3](https://reviewable.io:443/reviews/powershell/sharepointdsc/549#-KgNI8rc3N1L9nGw36Jo:-KgNI8rc3N1L9nGw36Jp:b-55p5mc) ([raw file](https://github.com/powershell/sharepointdsc/blob/a782df97449819c6318200b4f95221b556ea095b/Tests/Unit/SharePointDsc/SPManagedMetaDataServiceApp/2-RemoveServiceApp.ps1#L2)):*
> ```PowerShell
> <#
> .EXAMPLE
> ```

I think you might have accidently copied some files here that shouldn't be here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/549)*

**Comment by BrianFarnhill** [comment]
:lgtm:

---

Reviewed 8 of 8 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/549#-:-KgQxYJkI5v1PMDE-FEl:bnfp4nl)*

**Pull request merged**
