### PR TITLE
SPSite: Fixed permission issues for default group creation.

### LINKED ISSUE #875: SPSite: Owner and Secondary Owner claims issues during Test-DSCConfiguration
When specifying owner and secondary owner on a site collection in a web application that uses claims authentication it is required to use the encoded claims format (i:0#.w|domain\username)
The test method gets the decoded logon name and compares it to the claims encoded value from the resource. This will not match, and the test fails.

#### Details of the scenario you tried and the problem that is occurring
N/A

#### Verbose logs showing the problem
N/A

#### Suggested solution to the issue

Test method needs to compare the correct user logon values when using claims authentication

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
SPSite EniCoMSite
{
    Name = "EniCoM"
    OwnerAlias = "i:0#.w|domain\username";
    SecondaryOwnerAlias = "i:0#.w|domain\username2";
    PsDscRunAsCredential = $SPSetupCredential;
    Url = "http://sharepoint";
    Language = 1033;
    CompatibilityLevel = 15;
     Template = "STS#0";
}

#### The operating system the target node is running
OsName               : Microsoft Windows Server 2012 R2 Standard
OsOperatingSystemSKU : StandardServerEdition
OsArchitecture       : 64-bit
WindowsBuildLabEx    : 9600.19101.amd64fre.winblue_ltsb_escrow.180718-1800
OsLanguage           : en-US
OsMuiLanguages       : {en-US}
#### Version of SharePoint that is used (e.g. SharePoint 2016)
SharePoint 2016

#### Version and build of PowerShell the target node is running
Name                           Value
----                           -----
PSVersion                      5.1.14409.1012
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14409.1012
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

#### Version of the DSC module that was used ('dev' if using current dev branch)
2.5.0.0

### LINKED ISSUE #898: SPSite: Exception calling "CreateDefaultAssociatedGroups" with "3" argument(s): "Access is denied.
When creating a new site collection using SPSite, if you don't have permissions on the site collection or web app policy, you are presented the following error:
Exception calling "CreateDefaultAssociatedGroups" with "3" argument(s): "Access is denied.

#### Details of the scenario you tried and the problem that is occurring
This is caused by recent submissions. We will have to correct it

#### Suggested solution to the issue
- Make sure the setup account has the correct permissions
- Make sure the documentation is updated with this requirement

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
 SPSite RootSite
{
    Url				 = 'http://sp.contoso.com'
    OwnerAlias			 = 'domain\user'
    Template			 = 'STS#0'   
    PsDSCRunAsCredential = $spsetup
}  
```

#### The operating system the target node is running
N/A

#### Version of SharePoint that is used (e.g. SharePoint 2016)
SP2013

#### Version and build of PowerShell the target node is running
v5.1

#### Version of the DSC module that was used ('dev' if using current dev branch)
Dev

### PR DESCRIPTION
**Pull request by jensotto**
#### Pull Request (PR) description
Uses the central administration site system account token to create a new instance of the site collection when creating default groups

Previously this resource retrieved the SPSite using Get-SPSite. For some reason the owner and secondary owner properties can then be null. This leads to the Test-TargetResource always returning false. If the site is instantiated using the central administration system account user token the owner and secondary owner properties are populated.

#### This Pull Request (PR) fixes the following issues
Fixes #898
Fixes #875 

#### Task list

- [x] Added an entry under the Unreleased section of the change log in the CHANGELOG.md.
      Entry should say what was changed, and how that affects users (if applicable).
- [ ] Resource documentation added/updated in README.md in the resource folder.
- [ ] Resource parameter descriptions added/updated in schema.mof
      and comment-based help.
- [ ] Comment-based help added/updated.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [ ] Examples appropriately added/updated.
- [x] Unit tests added/updated. See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] Integration tests added/updated (where possible). See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [x] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/sharepointdsc/904)

### CODE REVIEW

**Comment by jensotto** [comment]
I manage to implement the unit tests by slightly modifying the SPSite resource implementation.

**Comment by jensotto** [comment]
I have managed to fix a few more bugs that I've found earlier in this resource for example #875 . I need to rebuild the unit tests, but I will have to do that another day.

**Comment by ykuijs** [comment]
Excellent mate! One request: Can you add a description for all fixes you implement to the Changelog, even though an issue doesn't exist in the issuelist.

**Comment by jensotto** [comment]
Changelog updated and unit tests fixed

**Comment by jensotto** [comment]
@ykuijs The bugs I created in the latest commits is why I really believe we need to use strict mode. This would have caught the problems. Right now it's only a matter of reading skills and extensive live system/integration testing that can uncover these kind of mistakes.

**Pull request merged**
