### PR TITLE
SPWebAppClientCallableSettings: New resource for modifying client callable settings and setting administration site type in SPSite

### LINKED ISSUE #878: SPTenantCsom: Enable Tenant CSOM functionality
### Description
Add support for enabling/disabling the Tenant CSOM functionality on SP 2013/SP2016 in accordance to these blog posts:

https://blogs.msdn.microsoft.com/vesku/2015/12/04/sharepoint-tenant-csom-object-support-in-sharepoint-2013-and-2016/
https://blogs.msdn.microsoft.com/vesku/2014/06/09/provisioning-site-collections-using-sp-app-model-in-on-premises-with-just-csom/

### Proposed properties
WebApplication (This can possibly be skipped as it can be extracted from the AdministrationWebSite parameter)
AdministrationWebSite

### PR DESCRIPTION
**Pull request by jensotto**
#### Pull Request (PR) description
Added new resource for setting a web application client callable settings including proxy libraries.
Added AdministrationSiteType to SPSite resource.
This was a though one and I have been sick lately so please make sure that you do a proper review. I have testet it on a SharePoint 2013 environment, and it seems to work just fine.
The unit tests are a bit crazy, but it should cover most of the use cases. It also verifies that the correct values are actually written back to SharePoint objects.

There are some properties that are not implemented, one is only available in SharePoint 2016. I did not have time to prioritize those, and I don't think they are much used anyway.

#### This Pull Request (PR) fixes the following issues
- Fixes #878

#### Task list
- [x] Added an entry under the Unreleased section of the change log in the CHANGELOG.md.
      Entry should say what was changed, and how that affects users (if applicable).
- [x] Resource documentation added/updated in README.md in the resource folder.
- [x] Resource parameter descriptions added/updated in schema.mof
      and comment-based help.
- [x] Comment-based help added/updated.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [x] Examples appropriately added/updated.
- [x] Unit tests added/updated. See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] Integration tests added/updated (where possible). See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [x] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/sharepointdsc/899)

### CODE REVIEW

**Comment by jensotto** [comment]
Should I include the links to the blog posts by Vesa Juvonen in the readme file?
They do give a bit more information about the tenant administration functionality.
https://blogs.msdn.microsoft.com/vesku/2015/12/04/sharepoint-tenant-csom-object-support-in-sharepoint-2013-and-2016/
https://blogs.msdn.microsoft.com/vesku/2014/06/09/provisioning-site-collections-using-sp-app-model-in-on-premises-with-just-csom/

**Comment by jensotto** [comment]
There is one thing that I don't know how to do. Changing proxy libraries requires an IISReset on all servers in the farm. The guidance for SharePointDSC resources are that they should not require to contact other servers to complete the task. Do you have any suggestions on how to handle this?

**Comment by ykuijs** [comment]
About your question for adding the links to the Readme: It is always good to add additional information to the Readme file, so people can look up some background info. So yes, please add the links to the Readme!

**Comment by jensotto** [comment]
@ykuijs Sorry for having a meltdown a few minutes ago. I got really frustrated when it seemed everything I hade done just disappeared. It seems like Reviewable had down time that affected me. Luckily everything had been temporarily stored somewhere. Still I'm not able to sign in to Reviewable using Edge. I have to say that this reviewable app really starts to go on my nerves. Are there any other alternatives? Am I the only one that feels like this?

**Comment by ykuijs** [comment]
No worries mate, I have been in the same situation before. Fortunately Reviewable has a good caching feature, which stores all the work you did when you they have an issue with the site.

**Pull request merged**
