### PR TITLE
Remove all associated proxy instances if service app resource is absent

### PR DESCRIPTION
**Pull request by NikCharlebois**
This change is [Reviewable](https://reviewable.io/reviews/powershell/sharepointdsc/414)

### CODE REVIEW

**Comment by BrianFarnhill** [comment]
Reviewed 22 of 22 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPAccessServiceApp/MSFT_SPAccessServiceApp.psm1, line 126 at r1](https://reviewable.io:443/reviews/powershell/sharepointdsc/414#-KTLecBY3W-hsYukEpdp:-KTLecBY3W-hsYukEpdq:b-w2j9yn) ([raw file](https://github.com/powershell/sharepointdsc/blob/c869f44501d7d5c9edb6b8f960564f6d5a79fc33/Modules/SharePointDsc/DSCResources/MSFT_SPAccessServiceApp/MSFT_SPAccessServiceApp.psm1#L126)):*
> ```PowerShell
>             }
> 
>             # Remove the connected proxy(ies)
> ```

We probably don't need the comments here, it's pretty self explanatory so I would rather take them out. Same for all instances of this one

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPExcelServiceApp/MSFT_SPExcelServiceApp.psm1, line 141 at r1](https://reviewable.io:443/reviews/powershell/sharepointdsc/414#-KTLewTv9JLzNBDuwzpO:-KTLewTv9JLzNBDuwzpP:bjsj7r2) ([raw file](https://github.com/powershell/sharepointdsc/blob/c869f44501d7d5c9edb6b8f960564f6d5a79fc33/Modules/SharePointDsc/DSCResources/MSFT_SPExcelServiceApp/MSFT_SPExcelServiceApp.psm1#L141)):*
> ```PowerShell
>             }
> 
>             Remove-SPServiceApplication $app -Confirm:$false
> ```

Can I get you to fix the lack of use of positional parameters on these seeing as we're touching the same code. Should read:

    Remove-SPServiceApplication -Identity $app -Confirm:$false

---

*[Tests/Unit/SharePointDsc/SharePointDsc.SPAccessServiceApp.Tests.ps1, line 34 at r1](https://reviewable.io:443/reviews/powershell/sharepointdsc/414#-KTLfT8o_4TBp4p-_w4W:-KTLfT8o_4TBp4p-_w4X:b-xydfdd) ([raw file](https://github.com/powershell/sharepointdsc/blob/c869f44501d7d5c9edb6b8f960564f6d5a79fc33/Tests/Unit/SharePointDsc/SharePointDsc.SPAccessServiceApp.Tests.ps1#L34)):*
> ```PowerShell
>         Mock Set-SPAccessServicesApplication { }
>         Mock Remove-SPServiceApplication { }
>         Mock Get-SPServiceApplicationProxy { return $null }
> ```

Why are we returning null here? We would expect it to return null when it doesn't exist and return a value when it does, so this should vary by test context. Same for all of the tests where you have done this. 

---

*[Tests/Unit/SharePointDsc/SharePointDsc.SPWordAutomationServiceApp.Tests.ps1, line 300 at r1](https://reviewable.io:443/reviews/powershell/sharepointdsc/414#-KTLfo4TqIbvzc-QQIst:-KTLfo4TqIbvzc-QQIsu:bpul3wt) ([raw file](https://github.com/powershell/sharepointdsc/blob/c869f44501d7d5c9edb6b8f960564f6d5a79fc33/Tests/Unit/SharePointDsc/SharePointDsc.SPWordAutomationServiceApp.Tests.ps1#L300)):*
> ```PowerShell
>                 }) 
>             } 
>             Mock Remove-SPServiceApplication { return $null } 
> ```

Why did you add a return value here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/414)*

**Comment by BrianFarnhill** [comment]
@NikCharlebois Happy with the changes (reviewable is having a moment so I can't close that off) - just need you to do a pull from dev to resolve merge conflicts and we are good to go.

**Comment by NikCharlebois** [comment]
@BrianFarnhill merges and changes have been done

**Comment by NikCharlebois** [comment]
Done. Merged and committed back the files

**Comment by NikCharlebois** [comment]
Review status: 0 of 23 files reviewed at latest revision, 4 unresolved discussions.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPAccessServiceApp/MSFT_SPAccessServiceApp.psm1, line 126 at r1](https://reviewable.io:443/reviews/powershell/sharepointdsc/414#-KTLecBY3W-hsYukEpdp:-KTuRNJXFVZiK85LTwtj:b-ekl3k0) ([raw file](https://github.com/powershell/sharepointdsc/blob/c869f44501d7d5c9edb6b8f960564f6d5a79fc33/Modules/SharePointDsc/DSCResources/MSFT_SPAccessServiceApp/MSFT_SPAccessServiceApp.psm1#L126)):*
<details><summary><i>Previously, BrianFarnhill (Brian Farnhill) wrote…</i></summary>
> We probably don't need the comments here, it's pretty self explanatory so I would rather take them out. Same for all instances of this one
</details>
Comments taken out.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPExcelServiceApp/MSFT_SPExcelServiceApp.psm1, line 141 at r1](https://reviewable.io:443/reviews/powershell/sharepointdsc/414#-KTLewTv9JLzNBDuwzpO:-KTuRtYTh8lGMA98ZOqk:bts1guj) ([raw file](https://github.com/powershell/sharepointdsc/blob/c869f44501d7d5c9edb6b8f960564f6d5a79fc33/Modules/SharePointDsc/DSCResources/MSFT_SPExcelServiceApp/MSFT_SPExcelServiceApp.psm1#L141)):*
<details><summary><i>Previously, BrianFarnhill (Brian Farnhill) wrote…</i></summary>
> Can I get you to fix the lack of use of positional parameters on these seeing as we're touching the same code. Should read:
> 
>     Remove-SPServiceApplication -Identity $app -Confirm:$false
</details>
Params added

---

*[Tests/Unit/SharePointDsc/SharePointDsc.SPAccessServiceApp.Tests.ps1, line 34 at r1](https://reviewable.io:443/reviews/powershell/sharepointdsc/414#-KTLfT8o_4TBp4p-_w4W:-KTuRwN7KXmpXWogFi5N:b-ictgfh) ([raw file](https://github.com/powershell/sharepointdsc/blob/c869f44501d7d5c9edb6b8f960564f6d5a79fc33/Tests/Unit/SharePointDsc/SharePointDsc.SPAccessServiceApp.Tests.ps1#L34)):*
<details><summary><i>Previously, BrianFarnhill (Brian Farnhill) wrote…</i></summary>
> Why are we returning null here? We would expect it to return null when it doesn't exist and return a value when it does, so this should vary by test context. Same for all of the tests where you have done this. 
</details>
Null no longer returned.

---

*[Tests/Unit/SharePointDsc/SharePointDsc.SPWordAutomationServiceApp.Tests.ps1, line 300 at r1](https://reviewable.io:443/reviews/powershell/sharepointdsc/414#-KTLfo4TqIbvzc-QQIst:-KTuRz5v2ihVpy6gMnfy:b7k1bct) ([raw file](https://github.com/powershell/sharepointdsc/blob/c869f44501d7d5c9edb6b8f960564f6d5a79fc33/Tests/Unit/SharePointDsc/SharePointDsc.SPWordAutomationServiceApp.Tests.ps1#L300)):*
<details><summary><i>Previously, BrianFarnhill (Brian Farnhill) wrote…</i></summary>
> Why did you add a return value here?
</details>
Null value removed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/414)*

**Comment by BrianFarnhill** [comment]
Reviewed 6 of 22 files at r2, 13 of 13 files at r3.
Review status: 19 of 23 files reviewed at latest revision, 1 unresolved discussion.

---

*[Tests/Unit/SharePointDsc/SharePointDsc.SPAccessServiceApp.Tests.ps1, line 34 at r1](https://reviewable.io:443/reviews/powershell/sharepointdsc/414#-KTLfT8o_4TBp4p-_w4W:-KTuc9oeOOu3B3lxXFDp:bctlamj) ([raw file](https://github.com/powershell/sharepointdsc/blob/c869f44501d7d5c9edb6b8f960564f6d5a79fc33/Tests/Unit/SharePointDsc/SharePointDsc.SPAccessServiceApp.Tests.ps1#L34)):*
<details><summary><i>Previously, NikCharlebois (Nik Charlebois) wrote…</i></summary>
> Null no longer returned.
</details>
Why is it here at all though? It should be mocked differently in each context

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/414)*

**Comment by BrianFarnhill** [comment]
You need to do a pull from dev and resolve the conflict in changelog.md before appveyor can run.

---

Review status: 17 of 21 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/414#-:-KUAk6Zt-0hO_u3dqUKI:bwykeub)*

**Comment by BrianFarnhill** [comment]
Reviewed 22 of 24 files at r4.
Review status: 21 of 22 files reviewed at latest revision, 1 unresolved discussion.

---

*[tl4b52d1.a1v.txt, line 1 at r4](https://reviewable.io:443/reviews/powershell/sharepointdsc/414#-KUKlpEeNOZn33cz-6Pw:-KUKlpEgaLWHO_RBVYmc:b79u80v) ([raw file](https://github.com/powershell/sharepointdsc/blob/6480a2706681cf1f2162b581bf5fbab8e02b5631/tl4b52d1.a1v.txt#L1)):*
> ```
> Merge remote-tracking branch 'refs/remotes/PowerShell/dev' into Issue-360-Fix
> ```

Whats this file dude? Can you remove it please

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/414)*

**Comment by NikCharlebois** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[tl4b52d1.a1v.txt, line 1 at r4](https://reviewable.io:443/reviews/powershell/sharepointdsc/414#-KUKlpEeNOZn33cz-6Pw:-KUMUd73PnzlB1H5UuxP:b-ciih7u) ([raw file](https://github.com/powershell/sharepointdsc/blob/6480a2706681cf1f2162b581bf5fbab8e02b5631/tl4b52d1.a1v.txt#L1)):*
<details><summary><i>Previously, BrianFarnhill (Brian Farnhill) wrote…</i></summary>
> Whats this file dude? Can you remove it please
</details>
Dang, not sure why this ile got put in...I totally missed it. My pull/merges are still problematic...sorry, yet again about this

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/414)*

**Comment by NikCharlebois** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[Tests/Unit/SharePointDsc/SharePointDsc.SPAccessServiceApp.Tests.ps1, line 34 at r1](https://reviewable.io:443/reviews/powershell/sharepointdsc/414#-KTLfT8o_4TBp4p-_w4W:-KUMWVgTwClcBMORJh8n:boalrdo) ([raw file](https://github.com/powershell/sharepointdsc/blob/c869f44501d7d5c9edb6b8f960564f6d5a79fc33/Tests/Unit/SharePointDsc/SharePointDsc.SPAccessServiceApp.Tests.ps1#L34)):*
<details><summary><i>Previously, BrianFarnhill (Brian Farnhill) wrote…</i></summary>
> Why is it here at all though? It should be mocked differently in each context
</details>
It has been remove entirely

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/414)*

**Comment by BrianFarnhill** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r5.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/414#-:-KUQ85NBG2ZFHwBs8PMa:bnfp4nl)*

**Pull request merged**
