### PR TITLE
Added the SearchApplication param to fix some conflict when multiple …

### PR DESCRIPTION
**Pull request by NikCharlebois**
#### Pull Request (PR) description
Fixed an issue setting the Managed Property settings when multiple Search Service Application existed.

#### This Pull Request (PR) fixes the following issues
N/A

#### Task list
- [x] Added an entry under the Unreleased section of the change log in the CHANGELOG.md.
      Entry should say what was changed, and how that affects users (if applicable).
- [x] Resource documentation added/updated in README.md in the resource folder.
- [x] Resource parameter descriptions added/updated in schema.mof
      and comment-based help.
- [x] Comment-based help added/updated.
- [x] Localization strings added/updated in all localization files as appropriate.
- [x] Examples appropriately added/updated.
- [x] Unit tests added/updated. See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [x] Integration tests added/updated (where possible). See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [x] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/sharepointdsc/907)

### CODE REVIEW

**Comment by ykuijs** [comment]
Isn't this change also included in PR #909?

**Comment by NikCharlebois** [comment]
Since the resource is in the changelog, listed as new resource for release 2.6.0.0 I am debating whether or not it would make sense to add a second bullet under the resource to list what change was made since last PR. I say we should just keep it listed as new resource.

**Comment by ykuijs** [comment]
Fair point, I agree!

Does this PR have to be merged separately, since as far as I can see does the other PR include the same fix. Am I correct?

**Comment by NikCharlebois** [comment]
Yes you are correct, the other PR includes the fix as well, I forked after fixing this one...

**Comment by ykuijs** [comment]
Closing as duplicate

**Pull request closed without merging**
