### PR TITLE
new resource, SPServiceIdentity

### PR DESCRIPTION
**Pull request by MikeLacher448**
new resource, SPServiceInstanceIdentity
 used to set SP services that support it (C2WTS, Sandbox service, Excel Services, etc..) to run on the server as a specified managed account, as descried in issue #577 

- [X] Change details added to Unreleased section of changelog.md?
- [X] Added/updated documentation and descriptions in .schema.mof files where appropriate?
- [X] Examples updated for both the single server and small farm templates in the examples folder?
- [X] New/changed code adheres to [Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md)?
- [X] [Unit and Integration tests](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md) created/updated where possible?

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/sharepointdsc/642)

### CODE REVIEW

**Comment by MikeLacher448** [comment]
checks passed and ready for review.

**Comment by ykuijs** [comment]
Looks good, just some comments

---

Reviewed 1 of 6 files at r1.
Review status: 1 of 6 files reviewed at latest revision, 18 unresolved discussions.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPServiceIdentity/MSFT_SPServiceIdentity.psm1, line 7 at r2](https://reviewable.io:443/reviews/powershell/sharepointdsc/642#-KrpCVhaefkmTjUXJYjU:-KrpCVhaefkmTjUXJYjV:b3lonzh) ([raw file](https://github.com/powershell/sharepointdsc/blob/7f03233e1d41b8c30835d28cf7eacfa4be81301f/Modules/SharePointDsc/DSCResources/MSFT_SPServiceIdentity/MSFT_SPServiceIdentity.psm1#L7)):*
> ```PowerShell
>     param
>     (
>         [parameter(Mandatory = $true)]  [System.String] $Name,
> ```

Please split these into three different lines:
[parameter(Mandatory = $true)]
[System.String]
$Name,

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPServiceIdentity/MSFT_SPServiceIdentity.psm1, line 8 at r2](https://reviewable.io:443/reviews/powershell/sharepointdsc/642#-KrpCca4gcjiix3xDxQP:-KrpCca5PxAHH93BK1MJ:bkd3kca) ([raw file](https://github.com/powershell/sharepointdsc/blob/7f03233e1d41b8c30835d28cf7eacfa4be81301f/Modules/SharePointDsc/DSCResources/MSFT_SPServiceIdentity/MSFT_SPServiceIdentity.psm1#L8)):*
> ```PowerShell
>     (
>         [parameter(Mandatory = $true)]  [System.String] $Name,
>         [parameter(Mandatory = $false)] [System.Management.Automation.PSCredential] $InstallAccount,
> ```

Same as above, split across three lines

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPServiceIdentity/MSFT_SPServiceIdentity.psm1, line 9 at r2](https://reviewable.io:443/reviews/powershell/sharepointdsc/642#-KrpCeX-N-A0AYdG8keD:-KrpCeX-N-A0AYdG8keE:bkd3kca) ([raw file](https://github.com/powershell/sharepointdsc/blob/7f03233e1d41b8c30835d28cf7eacfa4be81301f/Modules/SharePointDsc/DSCResources/MSFT_SPServiceIdentity/MSFT_SPServiceIdentity.psm1#L9)):*
> ```PowerShell
>         [parameter(Mandatory = $true)]  [System.String] $Name,
>         [parameter(Mandatory = $false)] [System.Management.Automation.PSCredential] $InstallAccount,
>         [parameter(Mandatory = $false)] [System.String] $ManagedAccount
> ```

Same as above, split across three lines

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPServiceIdentity/MSFT_SPServiceIdentity.psm1, line 9 at r2](https://reviewable.io:443/reviews/powershell/sharepointdsc/642#-KrpEGmushBaiBXiEH0x:-KrpEGmushBaiBXiEH0y:b-dtermr) ([raw file](https://github.com/powershell/sharepointdsc/blob/7f03233e1d41b8c30835d28cf7eacfa4be81301f/Modules/SharePointDsc/DSCResources/MSFT_SPServiceIdentity/MSFT_SPServiceIdentity.psm1#L9)):*
> ```PowerShell
>         [parameter(Mandatory = $true)]  [System.String] $Name,
>         [parameter(Mandatory = $false)] [System.Management.Automation.PSCredential] $InstallAccount,
>         [parameter(Mandatory = $false)] [System.String] $ManagedAccount
> ```

Shouldn't this property be mandatory?

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPServiceIdentity/MSFT_SPServiceIdentity.psm1, line 24 at r2](https://reviewable.io:443/reviews/powershell/sharepointdsc/642#-KrpD4OoI_b5q_SoRsgE:-KrpD4OpTa1cozr-o1VY:b-o4zcmd) ([raw file](https://github.com/powershell/sharepointdsc/blob/7f03233e1d41b8c30835d28cf7eacfa4be81301f/Modules/SharePointDsc/DSCResources/MSFT_SPServiceIdentity/MSFT_SPServiceIdentity.psm1#L24)):*
> ```PowerShell
>             Name = $params.Name
>             ManagedAccount = $ManagedAccount
>             InstallAccount = $params.InstallAccount
> ```

InstallAccount does not have to be added. It will be ignored during comparison anyways.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPServiceIdentity/MSFT_SPServiceIdentity.psm1, line 38 at r2](https://reviewable.io:443/reviews/powershell/sharepointdsc/642#-KrpE_U3qGZ8g9H6tIVK:-KrpE_U3qGZ8g9H6tIVL:bkd3kca) ([raw file](https://github.com/powershell/sharepointdsc/blob/7f03233e1d41b8c30835d28cf7eacfa4be81301f/Modules/SharePointDsc/DSCResources/MSFT_SPServiceIdentity/MSFT_SPServiceIdentity.psm1#L38)):*
> ```PowerShell
>     param
>     (
>         [parameter(Mandatory = $true)]  [System.String] $Name,
> ```

Same as above, split across three lines

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPServiceIdentity/MSFT_SPServiceIdentity.psm1, line 39 at r2](https://reviewable.io:443/reviews/powershell/sharepointdsc/642#-KrpEaLcPfIDagWnDIF1:-KrpEaLcPfIDagWnDIF2:bkd3kca) ([raw file](https://github.com/powershell/sharepointdsc/blob/7f03233e1d41b8c30835d28cf7eacfa4be81301f/Modules/SharePointDsc/DSCResources/MSFT_SPServiceIdentity/MSFT_SPServiceIdentity.psm1#L39)):*
> ```PowerShell
>     (
>         [parameter(Mandatory = $true)]  [System.String] $Name,
>         [parameter(Mandatory = $false)] [System.Management.Automation.PSCredential] $InstallAccount,
> ```

Same as above, split across three lines

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPServiceIdentity/MSFT_SPServiceIdentity.psm1, line 40 at r2](https://reviewable.io:443/reviews/powershell/sharepointdsc/642#-KrpEAGnrx5u7nx64lrd:-KrpEAGnrx5u7nx64lre:b-dtermr) ([raw file](https://github.com/powershell/sharepointdsc/blob/7f03233e1d41b8c30835d28cf7eacfa4be81301f/Modules/SharePointDsc/DSCResources/MSFT_SPServiceIdentity/MSFT_SPServiceIdentity.psm1#L40)):*
> ```PowerShell
>         [parameter(Mandatory = $true)]  [System.String] $Name,
>         [parameter(Mandatory = $false)] [System.Management.Automation.PSCredential] $InstallAccount,
>         [parameter(Mandatory = $false)] [System.String] $ManagedAccount
> ```

Shouldn't this property be mandatory?

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPServiceIdentity/MSFT_SPServiceIdentity.psm1, line 40 at r2](https://reviewable.io:443/reviews/powershell/sharepointdsc/642#-KrpEbByQq1RYQOAFxrY:-KrpEbByQq1RYQOAFxrZ:bkd3kca) ([raw file](https://github.com/powershell/sharepointdsc/blob/7f03233e1d41b8c30835d28cf7eacfa4be81301f/Modules/SharePointDsc/DSCResources/MSFT_SPServiceIdentity/MSFT_SPServiceIdentity.psm1#L40)):*
> ```PowerShell
>         [parameter(Mandatory = $true)]  [System.String] $Name,
>         [parameter(Mandatory = $false)] [System.Management.Automation.PSCredential] $InstallAccount,
>         [parameter(Mandatory = $false)] [System.String] $ManagedAccount
> ```

Same as above, split across three lines

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPServiceIdentity/MSFT_SPServiceIdentity.psm1, line 51 at r2](https://reviewable.io:443/reviews/powershell/sharepointdsc/642#-KrpDCYMSl6kQ1tHdroN:-KrpDCYMSl6kQ1tHdroO:bi3ydl6) ([raw file](https://github.com/powershell/sharepointdsc/blob/7f03233e1d41b8c30835d28cf7eacfa4be81301f/Modules/SharePointDsc/DSCResources/MSFT_SPServiceIdentity/MSFT_SPServiceIdentity.psm1#L51)):*
> ```PowerShell
>         $serviceInstance = Get-SPServiceInstance -Server $env:COMPUTERNAME| Where-Object { $_.TypeName -eq $params.Name }
>         $managedAccount = Get-SPManagedAccount $params.ManagedAccount
>         if ($null -eq $serviceInstance) {
> ```

Please place the { on the next line, according to the coding style guide

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPServiceIdentity/MSFT_SPServiceIdentity.psm1, line 54 at r2](https://reviewable.io:443/reviews/powershell/sharepointdsc/642#-KrpDJatet0K4BcdpEW3:-KrpDJatet0K4BcdpEW4:bi3ydl6) ([raw file](https://github.com/powershell/sharepointdsc/blob/7f03233e1d41b8c30835d28cf7eacfa4be81301f/Modules/SharePointDsc/DSCResources/MSFT_SPServiceIdentity/MSFT_SPServiceIdentity.psm1#L54)):*
> ```PowerShell
>             throw [System.Exception] "Unable to locate service $($params.Name)"
>         }
>         if ($null -eq $managedAccount) {
> ```

Please place the { on the next line, according to the coding style guide

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPServiceIdentity/MSFT_SPServiceIdentity.psm1, line 58 at r2](https://reviewable.io:443/reviews/powershell/sharepointdsc/642#-KrpDbUx4KvAy6G4NbHS:-KrpDbUx4KvAy6G4NbHT:bi3ydl6) ([raw file](https://github.com/powershell/sharepointdsc/blob/7f03233e1d41b8c30835d28cf7eacfa4be81301f/Modules/SharePointDsc/DSCResources/MSFT_SPServiceIdentity/MSFT_SPServiceIdentity.psm1#L58)):*
> ```PowerShell
>         }
>         
>        if ($null -eq $serviceInstance.service.processidentity) {
> ```

Please place the { on the next line, according to the coding style guide

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPServiceIdentity/MSFT_SPServiceIdentity.psm1, line 58 at r2](https://reviewable.io:443/reviews/powershell/sharepointdsc/642#-KrpDoMEVcabX5-yUjku:-KrpDoMEVcabX5-yUjkv:b-y6ox36) ([raw file](https://github.com/powershell/sharepointdsc/blob/7f03233e1d41b8c30835d28cf7eacfa4be81301f/Modules/SharePointDsc/DSCResources/MSFT_SPServiceIdentity/MSFT_SPServiceIdentity.psm1#L58)):*
> ```PowerShell
>         }
>         
>        if ($null -eq $serviceInstance.service.processidentity) {
> ```

Can this check be added to the Get function as well. That way we detect that the service doesn't support changing the process identity at an earlier stage.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPServiceIdentity/MSFT_SPServiceIdentity.psm1, line 79 at r2](https://reviewable.io:443/reviews/powershell/sharepointdsc/642#-KrpEX5BvRTCCmLpPjyI:-KrpEX5BvRTCCmLpPjyJ:bkd3kca) ([raw file](https://github.com/powershell/sharepointdsc/blob/7f03233e1d41b8c30835d28cf7eacfa4be81301f/Modules/SharePointDsc/DSCResources/MSFT_SPServiceIdentity/MSFT_SPServiceIdentity.psm1#L79)):*
> ```PowerShell
>     param
>     (
>         [parameter(Mandatory = $true)]  [System.String] $Name,
> ```

Same as above, split across three lines

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPServiceIdentity/MSFT_SPServiceIdentity.psm1, line 80 at r2](https://reviewable.io:443/reviews/powershell/sharepointdsc/642#-KrpEXoe-e22sogSC9fQ:-KrpEXoe-e22sogSC9fR:bkd3kca) ([raw file](https://github.com/powershell/sharepointdsc/blob/7f03233e1d41b8c30835d28cf7eacfa4be81301f/Modules/SharePointDsc/DSCResources/MSFT_SPServiceIdentity/MSFT_SPServiceIdentity.psm1#L80)):*
> ```PowerShell
>     (
>         [parameter(Mandatory = $true)]  [System.String] $Name,
>         [parameter(Mandatory = $false)] [System.Management.Automation.PSCredential] $InstallAccount,
> ```

Same as above, split across three lines

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPServiceIdentity/MSFT_SPServiceIdentity.psm1, line 81 at r2](https://reviewable.io:443/reviews/powershell/sharepointdsc/642#-KrpENBYSy23KIa_E9EC:-KrpENBYSy23KIa_E9ED:b-dtermr) ([raw file](https://github.com/powershell/sharepointdsc/blob/7f03233e1d41b8c30835d28cf7eacfa4be81301f/Modules/SharePointDsc/DSCResources/MSFT_SPServiceIdentity/MSFT_SPServiceIdentity.psm1#L81)):*
> ```PowerShell
>         [parameter(Mandatory = $true)]  [System.String] $Name,
>         [parameter(Mandatory = $false)] [System.Management.Automation.PSCredential] $InstallAccount,
>         [parameter(Mandatory = $false)] [System.String] $ManagedAccount
> ```

Shouldn't this property be mandatory?

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPServiceIdentity/MSFT_SPServiceIdentity.psm1, line 81 at r2](https://reviewable.io:443/reviews/powershell/sharepointdsc/642#-KrpEYm1TdRXZItjJdvL:-KrpEYm1TdRXZItjJdvM:bkd3kca) ([raw file](https://github.com/powershell/sharepointdsc/blob/7f03233e1d41b8c30835d28cf7eacfa4be81301f/Modules/SharePointDsc/DSCResources/MSFT_SPServiceIdentity/MSFT_SPServiceIdentity.psm1#L81)):*
> ```PowerShell
>         [parameter(Mandatory = $true)]  [System.String] $Name,
>         [parameter(Mandatory = $false)] [System.Management.Automation.PSCredential] $InstallAccount,
>         [parameter(Mandatory = $false)] [System.String] $ManagedAccount
> ```

Same as above, split across three lines

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPServiceIdentity/MSFT_SPServiceIdentity.schema.mof, line 5 at r2](https://reviewable.io:443/reviews/powershell/sharepointdsc/642#-KrpE4_rQe8hC6N-QDnZ:-KrpE4_sEO9qLAE32-ym:bu3xh0p) ([raw file](https://github.com/powershell/sharepointdsc/blob/7f03233e1d41b8c30835d28cf7eacfa4be81301f/Modules/SharePointDsc/DSCResources/MSFT_SPServiceIdentity/MSFT_SPServiceIdentity.schema.mof#L5)):*
> ```
> {
>     [Key, Description("The name of the service instance to manage")] string Name;
>     [Write, Description("The user name of a managed account that will be used to run the service") ] string ManagedAccount;
> ```

Shouldn't this property be Required?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/642#-:-KrpF4cPKj1LlvGc70g5:b-9takr6)*

**Comment by ykuijs** [comment]
@MikeLacher448, any update?

**Comment by MikeLacher448** [comment]
@ykuijs , I think I got it all this time.

**Comment by ykuijs** [comment]
:lgtm:

---

Reviewed 1 of 6 files at r1, 2 of 2 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/642#-:-KsgxMxJe5ixqPR3XwJ6:bnfp4nl)*

**Pull request merged**
