### PR TITLE
SharePointDSC.Reverse

### PR DESCRIPTION
**Pull request by NikCharlebois**
Alpha Release

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/sharepointdsc/335)

### CODE REVIEW

**Comment by NikCharlebois** [comment]
No tests have been added yet. I just wanted to get this out there pending until I get time to write the tests.

**Comment by BrianFarnhill** [comment]
@NikCharlebois No worries mate, I can't merge this in until it has the tests there. How far away do you think you are from having them done? I'll handle the review of this one when it's ready.

**Comment by NikCharlebois** [comment]
I am really hoping to have time to address them within the next few weeks. So let's say in about 2 weeks....

**Comment by BrianFarnhill** [comment]
@NikCharlebois No worries, happy to park this here for a couple of weeks. Ping me when it's ready for review.

**Comment by BrianFarnhill** [comment]
Just gave this a quick once over - loving the direction in it this time vs. last time we saw this one dude. When I get a sec I'll do a code review in full of whats there as I've got some feedback (nothing super dramatic though), so you will be able to work on that as well as the tests. I'll try to get the review done in the next day or two and let you know.

**Comment by BrianFarnhill** [comment]
@NikCharlebois How are your tests looking on this one? Any update on this? If its going to be a while I would rather we close this one off and you can re-open when its ready for a review from top to bottom. Just let us know where you're up to

**Comment by BrianFarnhill** [comment]
@NikCharlebois I'm going to close this one off and wait until you're closer to something that is ready to merge in. Let me know when you have the tests done and open a new PR. Thanks dude.

**Pull request closed without merging**
