### PR TITLE
SPSearchMetadataCategory

### PR DESCRIPTION
**Pull request by NikCharlebois**
#### Pull Request (PR) description
New Resource to allow for the creation of new Search Metadata Categories

#### This Pull Request (PR) fixes the following issues
N/A

#### Task list
- [x] Added an entry under the Unreleased section of the change log in the CHANGELOG.md.
      Entry should say what was changed, and how that affects users (if applicable).
- [x] Resource documentation added/updated in README.md in the resource folder.
- [x] Resource parameter descriptions added/updated in schema.mof
      and comment-based help.
- [x] Comment-based help added/updated.
- [x] Localization strings added/updated in all localization files as appropriate.
- [x] Examples appropriately added/updated.
- [x] Unit tests added/updated. See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [x] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/sharepointdsc/933)

### CODE REVIEW

**Comment by NikCharlebois** [comment]
@ykuijs AppVeyor didn't kick on that one either....

**Comment by ykuijs** [comment]
There are issues with GitHub: https://status.github.com/messages

**Comment by ykuijs** [comment]
Why do you want to merge this to the v3.0 branch? A new resource can be merged into Dev, right?

**Comment by NikCharlebois** [comment]
Yep, just wasn’t sure what would be simpler. It doesn’t have to be included right now

Nik Charlebois
Senior Premier Field Engineer
613-790-2331
________________________________

**Pull request merged**
