### PR TITLE
Bugfix Rollup

### PR DESCRIPTION
**Pull request by ykuijs**
Another bugfix rollup PR, fixing issues #774, #794, #795, #804, #809

- [X] Change details added to Unreleased section of changelog.md?
- [X] Added/updated documentation and descriptions in .schema.mof files where appropriate?
- [X] Examples updated for both the single server and small farm templates in the examples folder?
- [X] New/changed code adheres to [Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md)?
- [X] [Unit and Integration tests](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md) created/updated where possible?

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/sharepointdsc/811)

### CODE REVIEW

**Comment by ykuijs** [comment]
@NikCharlebois All yours mate!

**Comment by NikCharlebois** [comment]
Review status: 5 of 6 files reviewed at latest revision, all discussions resolved.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPFarm/MSFT_SPFarm.psm1, line 189 at r1](https://reviewable.io/reviews/powershell/sharepointdsc/811#-LEF0idYDsrsSA05GLN0:-LEF0idYDsrsSA05GLN1:ber8qtp) ([raw file](https://github.com/powershell/sharepointdsc/blob/7bc9bc6080c11f6d1b8823c3dd4d2cfdd025c845/Modules/SharePointDsc/DSCResources/MSFT_SPFarm/MSFT_SPFarm.psm1#L189)):*
> ```PowerShell
>             {
>                 $server = Get-SPServer -Identity $env:COMPUTERNAME -ErrorAction SilentlyContinue
>                 if($null -ne $server -and $null -ne $server.Role)
> ```

Should we check for empty or null instead?
if(!$server -and !$server.Role)

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPFarm/MSFT_SPFarm.psm1, line 199 at r1](https://reviewable.io/reviews/powershell/sharepointdsc/811#-LEF0vuh6pWd4gD1f5rL:-LEF0vuh6pWd4gD1f5rM:b-ya81ng) ([raw file](https://github.com/powershell/sharepointdsc/blob/7bc9bc6080c11f6d1b8823c3dd4d2cfdd025c845/Modules/SharePointDsc/DSCResources/MSFT_SPFarm/MSFT_SPFarm.psm1#L199)):*
> ```PowerShell
> 
>                     $server = Get-SPServer -Identity $currentServer -ErrorAction SilentlyContinue
>                     if($null -ne $server -and $null -ne $server.Role)
> ```

Same as above

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPUserProfileSyncConnection/MSFT_SPUserProfileSyncConnection.psm1, line 73 at r1](https://reviewable.io/reviews/powershell/sharepointdsc/811#-LEF16hf0TnDr9ZbmyBb:-LEF16hf0TnDr9ZbmyBc:b-26t143) ([raw file](https://github.com/powershell/sharepointdsc/blob/7bc9bc6080c11f6d1b8823c3dd4d2cfdd025c845/Modules/SharePointDsc/DSCResources/MSFT_SPUserProfileSyncConnection/MSFT_SPUserProfileSyncConnection.psm1#L73)):*
> ```PowerShell
>         $nullreturn = @{
>             Name = $params.Name
>             UserprofileService = $null
> ```

Me being picky. use a capital 'P' in the name

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPUserProfileSyncConnection/MSFT_SPUserProfileSyncConnection.psm1, line 156 at r1](https://reviewable.io/reviews/powershell/sharepointdsc/811#-LEF1OeI2OR4v-kt2iKA:-LEF1OeI2OR4v-kt2iKB:b-vgm6w) ([raw file](https://github.com/powershell/sharepointdsc/blob/7bc9bc6080c11f6d1b8823c3dd4d2cfdd025c845/Modules/SharePointDsc/DSCResources/MSFT_SPUserProfileSyncConnection/MSFT_SPUserProfileSyncConnection.psm1#L156)):*
> ```PowerShell
>                 return @{
>                     Name = $params.Name
>                     UserprofileService = $params.UserProfileService
> ```

Use capital 'P'

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPUserProfileSyncConnection/MSFT_SPUserProfileSyncConnection.psm1, line 413 at r1](https://reviewable.io/reviews/powershell/sharepointdsc/811#-LEF25yO9ROCcVYq5jo9:-LEF25yO9ROCcVYq5joA:bvg37ub) ([raw file](https://github.com/powershell/sharepointdsc/blob/b323acce21a048cd2221b55d9c416682e95e442a/Modules/SharePointDsc/DSCResources/MSFT_SPUserProfileSyncConnection/MSFT_SPUserProfileSyncConnection.psm1#L413)):*
> ```PowerShell
>     return Test-SPDscParameterState -CurrentValues $CurrentValues `
>                                     -DesiredValues $PSBoundParameters `
>                                     -ValuesToCheck @("Name",
> ```

Why did we remove name as part of the checks, just curious.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPUserProfileSyncConnection/MSFT_SPUserProfileSyncConnection.psm1, line 559 at r1](https://reviewable.io/reviews/powershell/sharepointdsc/811#-LEF1t-02FJhAlPAQk1-:-LEF1t-02FJhAlPAQk10:b-3txszv) ([raw file](https://github.com/powershell/sharepointdsc/blob/7bc9bc6080c11f6d1b8823c3dd4d2cfdd025c845/Modules/SharePointDsc/DSCResources/MSFT_SPUserProfileSyncConnection/MSFT_SPUserProfileSyncConnection.psm1#L559)):*
> ```PowerShell
>     $CurrentValues = Get-TargetResource @PSBoundParameters
> 
>     if ($null -eq $CurrentValues.UserProfileService)
> ```

Should we check for null or empty? See above comments

---

*[Tests/Unit/SharePointDsc/SharePointDsc.SPUserProfileSyncConnection.Tests.ps1, line 27 at r1](https://reviewable.io/reviews/powershell/sharepointdsc/811#-LEF2YhL2rj9jk-zqwQM:-LEF2YhL2rj9jk-zqwQN:bqoczgm) ([raw file](https://github.com/powershell/sharepointdsc/blob/7bc9bc6080c11f6d1b8823c3dd4d2cfdd025c845/Tests/Unit/SharePointDsc/SharePointDsc.SPUserProfileSyncConnection.Tests.ps1#L27)):*
> ```PowerShell
>                                      -ArgumentList @("DOMAIN\username", $mockPassword)
> 
>         if ($Global:SPDscHelper.CurrentStubBuildNumber.Major -eq 16)
> ```

Global Comment: Shouldn't our tests include the Port parameter since this is a new parameter?

---


*Comments from [Reviewable](https://reviewable.io/reviews/powershell/sharepointdsc/811)*

**Comment by ykuijs** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPFarm/MSFT_SPFarm.psm1, line 189 at r1](https://reviewable.io/reviews/powershell/sharepointdsc/811#-LEF0idYDsrsSA05GLN0:-LEF3UhbAUs0qLERDciw:b-6jz322) ([raw file](https://github.com/powershell/sharepointdsc/blob/7bc9bc6080c11f6d1b8823c3dd4d2cfdd025c845/Modules/SharePointDsc/DSCResources/MSFT_SPFarm/MSFT_SPFarm.psm1#L189)):*
<details><summary><i>Previously, NikCharlebois (Nik Charlebois) wrote…</i></summary><blockquote>

Should we check for empty or null instead?
if(!$server -and !$server.Role)
</blockquote></details>

Get-SPServer returns a Null result when no server is found, so I think we should be checking for Null and not empty.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPFarm/MSFT_SPFarm.psm1, line 199 at r1](https://reviewable.io/reviews/powershell/sharepointdsc/811#-LEF0vuh6pWd4gD1f5rL:-LEF3gsI0-Th_b_UmdO6:b-6jz322) ([raw file](https://github.com/powershell/sharepointdsc/blob/7bc9bc6080c11f6d1b8823c3dd4d2cfdd025c845/Modules/SharePointDsc/DSCResources/MSFT_SPFarm/MSFT_SPFarm.psm1#L199)):*
<details><summary><i>Previously, NikCharlebois (Nik Charlebois) wrote…</i></summary><blockquote>

Same as above
</blockquote></details>

Get-SPServer returns a Null result when no server is found, so I think we should be checking for Null and not empty.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPUserProfileSyncConnection/MSFT_SPUserProfileSyncConnection.psm1, line 73 at r1](https://reviewable.io/reviews/powershell/sharepointdsc/811#-LEF16hf0TnDr9ZbmyBb:-LEF3pBA79uMMjbOKYDQ:b-896fix) ([raw file](https://github.com/powershell/sharepointdsc/blob/7bc9bc6080c11f6d1b8823c3dd4d2cfdd025c845/Modules/SharePointDsc/DSCResources/MSFT_SPUserProfileSyncConnection/MSFT_SPUserProfileSyncConnection.psm1#L73)):*
<details><summary><i>Previously, NikCharlebois (Nik Charlebois) wrote…</i></summary><blockquote>

Me being picky. use a capital 'P' in the name
</blockquote></details>

Done.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPUserProfileSyncConnection/MSFT_SPUserProfileSyncConnection.psm1, line 156 at r1](https://reviewable.io/reviews/powershell/sharepointdsc/811#-LEF1OeI2OR4v-kt2iKA:-LEF3q6RBaNFN3p9O-jC:b-896fix) ([raw file](https://github.com/powershell/sharepointdsc/blob/7bc9bc6080c11f6d1b8823c3dd4d2cfdd025c845/Modules/SharePointDsc/DSCResources/MSFT_SPUserProfileSyncConnection/MSFT_SPUserProfileSyncConnection.psm1#L156)):*
<details><summary><i>Previously, NikCharlebois (Nik Charlebois) wrote…</i></summary><blockquote>

Use capital 'P'
</blockquote></details>

Done.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPUserProfileSyncConnection/MSFT_SPUserProfileSyncConnection.psm1, line 413 at r1](https://reviewable.io/reviews/powershell/sharepointdsc/811#-LEF25yO9ROCcVYq5jo9:-LEF4658BTq1vTU0IKDs:b-pxa2nu) ([raw file](https://github.com/powershell/sharepointdsc/blob/b323acce21a048cd2221b55d9c416682e95e442a/Modules/SharePointDsc/DSCResources/MSFT_SPUserProfileSyncConnection/MSFT_SPUserProfileSyncConnection.psm1#L413)):*
<details><summary><i>Previously, NikCharlebois (Nik Charlebois) wrote…</i></summary><blockquote>

Why did we remove name as part of the checks, just curious.
</blockquote></details>

The Name parameter isn't used in SP2016. The PS cmdlet automatically uses the forest name and replaces the dot for underscore. That is why in the Get method I always return $params.Name. And since that means Name will always be equal, it is a waste of CPU cycle to check if the values match.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPUserProfileSyncConnection/MSFT_SPUserProfileSyncConnection.psm1, line 559 at r1](https://reviewable.io/reviews/powershell/sharepointdsc/811#-LEF1t-02FJhAlPAQk1-:-LEF3rVmDg-cRldDznFy:b-iicnx8) ([raw file](https://github.com/powershell/sharepointdsc/blob/7bc9bc6080c11f6d1b8823c3dd4d2cfdd025c845/Modules/SharePointDsc/DSCResources/MSFT_SPUserProfileSyncConnection/MSFT_SPUserProfileSyncConnection.psm1#L559)):*
<details><summary><i>Previously, NikCharlebois (Nik Charlebois) wrote…</i></summary><blockquote>

Should we check for null or empty? See above comments
</blockquote></details>

When anything goes wrong in the Get method, I return an hastable where UserProfileService is Null. That is why I am checking for Null

---

*[Tests/Unit/SharePointDsc/SharePointDsc.SPUserProfileSyncConnection.Tests.ps1, line 27 at r1](https://reviewable.io/reviews/powershell/sharepointdsc/811#-LEF2YhL2rj9jk-zqwQM:-LEF4bLH6CbyqWm_Ih3n:b-ex19v5) ([raw file](https://github.com/powershell/sharepointdsc/blob/7bc9bc6080c11f6d1b8823c3dd4d2cfdd025c845/Tests/Unit/SharePointDsc/SharePointDsc.SPUserProfileSyncConnection.Tests.ps1#L27)):*
<details><summary><i>Previously, NikCharlebois (Nik Charlebois) wrote…</i></summary><blockquote>

Global Comment: Shouldn't our tests include the Port parameter since this is a new parameter?
</blockquote></details>

I have added check "Port and UseDisabledFilter are specified and UseSSL is True", which is using the Port parameter.

---


*Comments from [Reviewable](https://reviewable.io/reviews/powershell/sharepointdsc/811)*

**Comment by NikCharlebois** [comment]
Review status: 5 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[Tests/Unit/SharePointDsc/SharePointDsc.SPUserProfileSyncConnection.Tests.ps1, line 27 at r1](https://reviewable.io/reviews/powershell/sharepointdsc/811#-LEF2YhL2rj9jk-zqwQM:-LEFRkKK9YMtY6Z_8geL:b-m77h40) ([raw file](https://github.com/powershell/sharepointdsc/blob/7bc9bc6080c11f6d1b8823c3dd4d2cfdd025c845/Tests/Unit/SharePointDsc/SharePointDsc.SPUserProfileSyncConnection.Tests.ps1#L27)):*
<details><summary><i>Previously, ykuijs (Yorick Kuijs) wrote…</i></summary><blockquote>

I have added check "Port and UseDisabledFilter are specified and UseSSL is True", which is using the Port parameter.
</blockquote></details>

Got it, sorry,not sure how I missed that.

---


*Comments from [Reviewable](https://reviewable.io/reviews/powershell/sharepointdsc/811)*

**Comment by NikCharlebois** [comment]
:lgtm:

---

Review status: 5 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/powershell/sharepointdsc/811#-:-LEFRy7x5-Jc--HsL9eU:bnfp4nl)*

**Pull request merged**
