### PR TITLE
Fix: SPProductUpdate and SPLanguagePack conflict

### LINKED ISSUE #679: SPProductUpdate and SPLanguagePack conflict
**Details of the scenario you try and problem that is occurring:**
This was originally reported on the "SharePointDSC Best Practices and Gotchas Post" http://nikcharlebois.com/sharepoint-dsc-gotchas-and-best-practices/

In theory, it should be possible for someone to install, in order, a PU, a Language specific patch, and then run the config wizard. That scenario works just fine if done manually. However, with the SPDSC module, if you specify two SPProductUpdate blocks in a row, and then call the SPConfigWizard, it will skip over the second one because of the way we use B2B and will throw the following message:

Write-Verbose -Message ("An upgrade is pending. " + `
                                "To prevent a possible loop, the install will be skipped")

If this can be done manually, then we should look at having the DSC module allow it as well, given that Language specific patches are now separate from the main CU/PU.

**The DSC configuration that is using the resource:**
N/A

**Version of the Operating System and PowerShell the DSC Target Node is running:**
Win 2016/WMF 5.1

**Version of the DSC module you're using:**
1.9.0.0

### LINKED ISSUE #839: In a 2 server farm scenario SPProductUpdate wrongly evaluates that the patch has been already installed.
In a 2 server farm scenario SPProductUpdate wrongly evaluates that August 2017 CULD (Language Dependant)  patch has been already installed. 

        SPProductUpdate InstallCU
            {
                SetupFile            = 'C:\Temp\'+$CUFile 
                ShutdownServices     = $true
                Ensure               = "Present"
                PsDscRunAsCredential = $SetupAccount
            }

        # Reboot if pending

        xPendingReboot RebootCheck1
        {
            Name = "RebootCheck1"
        }

        SPProductUpdate InstallCUL
            {
                SetupFile            = 'C:\Temp\'+$CULDFile 
                ShutdownServices     = $true
                Ensure               = "Present"
                PsDscRunAsCredential = $SetupAccount
                DependsOn = "[File]CUDirectoryCopy"
            }

        xPendingReboot RebootCheck2
        {
            Name = "RebootCheck2"
        }
        
        SPConfigWizard PSConfig
        {
            Ensure = "Present"
            PsDscRunAscredential = $SetupAccount
        }

Windows Server 2012 R2 

Sharepoint 2016

SharepointDSC 2.2.0.0

I have hit the issue with the CULD on the August 2017 CU

Assumptions
	- SP 2016 has 2 types of patches. Language independent (CU) and Language dependent (CULD) 
	- Both need to be installed even if no language pack has been installed as English is as well an build in Language Pack. 
	- Ref: https://blogs.technet.microsoft.com/stefan_gossner/2017/08/08/august-2017-cu-for-sharepoint-server-2016-is-available-for-download/

So have a 2 server farm scenario (1 APP, 1 FE) applied same DSC to both. 

THE CU that I try to apply is the Aug 2017 CU and CULD (Language dependent) 

I have end up in this situation

APP: CU and CULD applied
FE: CU only applied. 

When I try to reapply DSC and get to the  SPProductUpdate InstallCUL (see above for the DSC) it tells me that patch is already installed. 

(I added some verbose logging) 

VERBOSE: [DFS-SP16FE-750]: [[SPProductUpdate]InstallCUL] The lowest version of any SharePoint component is 16.0.4573.1000 | July 11th 2018 14:37:34 Info

VERBOSE: [DFS-SP16FE-750]: [[SPProductUpdate]InstallCUL] Version of SharePoint is equal or greater than the patch version. Patch is installed July 11th 2018 14:37:34 Info

Usually CU and CULD will have same version number 
But that is not the case with Aug 17 CU for the SP2016 here CULD has lower number.  

CU: sts2016-kb4011049-fullfile-x64-glb.exe - 16.0.4573.1002
CULD: wssloc2016-kb4011053-fullfile-x64-glb.exe - 16.0.4573.1000

Running the Get-SPDscFarmVersionInfo gives me this information. 

Name                           Value                                                                                                                                             
----                           -----                                                                                                                                             
Highest                        16.0.4573.1002                                                                                                                                    
Lowest                         16.0.4573.1000 

So this fragment of the SPProductUpdate.psm1 will return false and resource will think that the update is already installed. 

 Write-Verbose -Message "The lowest version of any SharePoint component is $($versionInfo.Lowest)"
    if ($versionInfo.Lowest -lt $fileVersion)

I haven't hit that issue during previous runs of the testing (with CUs from previous months) So it might be the case that in particular case when CU and CULD are not of the same version SPProductUpdate if failing to make correct evaluation that the patch is required. 

Executing from SharepointDSc.Util.psm1

$productVersions.GetServerProductInfo($server.id) gives us clear information that on FE this patch is missing. 

ServerId                         : 10cf73ce-d986-459b-a56e-c1192def3032
ServerName                       : <Removed>
Products                         : {Microsoft SharePoint Server 2016}
RequiredButMissingProducts       : {}
OptionalMissingProducts          : {}
RequiredButMissingPatchableUnits : {}
RequiredButMissingPatches        : {Update for Microsoft SharePoint Enterprise Server 2016 (**KB4011053**) 64-Bit Edition}
InstallStatus                    : InstallRequired

When I install the CULD from GUI it installs normally.

### PR DESCRIPTION
**Pull request by andikrueger**
#### Pull Request (PR) description
This is a preliminary version of my working status. Currently the unit tests are still missing as mentioned in #679.

@ykuijs and @NikCharlebois : I hop you can test this code again in one of your environments. In my environments, it works perfectly and fixes those issues.

#### This Pull Request (PR) fixes the following issues
- Fixes #679
- Fixes #839

#### Task list
- [x] Added an entry under the Unreleased section of the change log in the CHANGELOG.md.
      Entry should say what was changed, and how that affects users (if applicable).
- [x] Resource documentation added/updated in README.md in the resource folder.
- [x] Resource parameter descriptions added/updated in schema.mof
      and comment-based help.
- [x] Comment-based help added/updated.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [ ] Examples appropriately added/updated.
- [ ] Unit tests added/updated. See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] Integration tests added/updated (where possible). See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [x] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/sharepointdsc/938)

### CODE REVIEW

**Comment by philippe-entringer** [comment]
Hello, 
I’m currently testing the Multifarm uppdate with DSC.

•	2 Servers in SharePoint 2013 Farm (CU Sept 2017 + French LP)
•	CU to install : Novembre 2017

The problem is that After installing the CU Nov. 2017 with DSC and reboot the first Server
The APPLICATION_SpsInstallCU_Master resource is triggered over and over again with Error and the SPConfigWizard could not be started.

The French Language Pack has impact on lower version detection.
On the Central Admin I see that French LP, with 15.0.4963.1001 | Superseded


VERBOSE: [CONTENTFARM]: LCM:  [ Start  Resource ]  [[SPProductUpdate]APPLICATION_SpsInstallCU_Master]
VERBOSE: [CONTENTFARM]: LCM:  [ Start  Test     ]  [[SPProductUpdate]APPLICATION_SpsInstallCU_Master]
VERBOSE: [CONTENTFARM]:                            [[SPProductUpdate]APPLICATION_SpsInstallCU_Master] Testing install status of SP Update binaries
VERBOSE: [CONTENTFARM]:                            [[SPProductUpdate]APPLICATION_SpsInstallCU_Master] Getting install status of SP binaries
VERBOSE: [CONTENTFARM]:                            [[SPProductUpdate]APPLICATION_SpsInstallCU_Master] Checking file status of F:\DscShared\SoftwarePackages\SPS\SP2013\Updates\CU_Novembre_2017\ubersrv2013-kb4011251-fullf
ile-x64-glb.exe
VERBOSE: [CONTENTFARM]:                            [[SPProductUpdate]APPLICATION_SpsInstallCU_Master] Update has version 15.0.4981.1002
VERBOSE: [CONTENTFARM]:                            [[SPProductUpdate]APPLICATION_SpsInstallCU_Master] Executing as the local run as user CONTOSO\CSAPTTD10SPSFSP
VERBOSE: [CONTENTFARM]:                            [[SPProductUpdate]APPLICATION_SpsInstallCU_Master] Leaving BeginProcessing Method of Get-SPFarm.
VERBOSE: [CONTENTFARM]:                            [[SPProductUpdate]APPLICATION_SpsInstallCU_Master] Leaving ProcessRecord Method of Get-SPFarm.
VERBOSE: [CONTENTFARM]:                            [[SPProductUpdate]APPLICATION_SpsInstallCU_Master] Leaving EndProcessing Method of Get-SPFarm.
VERBOSE: [CONTENTFARM]:                            [[SPProductUpdate]APPLICATION_SpsInstallCU_Master] Leaving BeginProcessing Method of Get-SPServer.
VERBOSE: [CONTENTFARM]:                            [[SPProductUpdate]APPLICATION_SpsInstallCU_Master] Leaving ProcessRecord Method of Get-SPServer.
VERBOSE: [CONTENTFARM]:                            [[SPProductUpdate]APPLICATION_SpsInstallCU_Master] Leaving EndProcessing Method of Get-SPServer.
VERBOSE: [CONTENTFARM]:                            [[SPProductUpdate]APPLICATION_SpsInstallCU_Master] Update is a Cumulative Update.
VERBOSE: [CONTENTFARM]:                            [[SPProductUpdate]APPLICATION_SpsInstallCU_Master] Executing as the local run as user CONTOSO\CSAPTTD10SPSFSP
VERBOSE: [CONTENTFARM]:                            [[SPProductUpdate]APPLICATION_SpsInstallCU_Master] Leaving BeginProcessing Method of Get-SPFarm.
VERBOSE: [CONTENTFARM]:                            [[SPProductUpdate]APPLICATION_SpsInstallCU_Master] Leaving ProcessRecord Method of Get-SPFarm.
VERBOSE: [CONTENTFARM]:                            [[SPProductUpdate]APPLICATION_SpsInstallCU_Master] Leaving EndProcessing Method of Get-SPFarm.
VERBOSE: [CONTENTFARM]:                            [[SPProductUpdate]APPLICATION_SpsInstallCU_Master] Leaving BeginProcessing Method of Get-SPServer.
VERBOSE: [CONTENTFARM]:                            [[SPProductUpdate]APPLICATION_SpsInstallCU_Master] Leaving ProcessRecord Method of Get-SPServer.
VERBOSE: [CONTENTFARM]:                            [[SPProductUpdate]APPLICATION_SpsInstallCU_Master] Leaving EndProcessing Method of Get-SPServer.
VERBOSE: [CONTENTFARM]:                            [[SPProductUpdate]APPLICATION_SpsInstallCU_Master] The lowest version of any SharePoint component is 15.0.4963.1001
VERBOSE: [CONTENTFARM]: LCM:  [ End    Test     ]  [[SPProductUpdate]APPLICATION_SpsInstallCU_Master]  in 0.3120 seconds.
VERBOSE: [CONTENTFARM]: LCM:  [ Start  Set      ]  [[SPProductUpdate]APPLICATION_SpsInstallCU_Master]
VERBOSE: [CONTENTFARM]:                            [[SPProductUpdate]APPLICATION_SpsInstallCU_Master] Setting install status of SP Update binaries
VERBOSE: [CONTENTFARM]:                            [[SPProductUpdate]APPLICATION_SpsInstallCU_Master] Checking file status of F:\DscShared\SoftwarePackages\SPS\SP2013\Updates\CU_Novembre_2017\ubersrv2013-kb4011251-fullf
ile-x64-glb.exe
VERBOSE: [CONTENTFARM]:                            [[SPProductUpdate]APPLICATION_SpsInstallCU_Master] No BinaryInstallDays specified, Update can be ran on any day.
VERBOSE: [CONTENTFARM]:                            [[SPProductUpdate]APPLICATION_SpsInstallCU_Master] No BinaryInstallTime specified, Update can be ran at any time. Starting update.
VERBOSE: [CONTENTFARM]:                            [[SPProductUpdate]APPLICATION_SpsInstallCU_Master] Stopping services to speed up installation process
VERBOSE: [CONTENTFARM]:                            [[SPProductUpdate]APPLICATION_SpsInstallCU_Master] Executing as the local run as user CONTOSO\CSAPTTD10SPSFSP
VERBOSE: [CONTENTFARM]:                            [[SPProductUpdate]APPLICATION_SpsInstallCU_Master] Leaving BeginProcessing Method of Get-SPEnterpriseSearchServiceApplication.
VERBOSE: [CONTENTFARM]:                            [[SPProductUpdate]APPLICATION_SpsInstallCU_Master] Leaving ProcessRecord Method of Get-SPEnterpriseSearchServiceApplication.
VERBOSE: [CONTENTFARM]:                            [[SPProductUpdate]APPLICATION_SpsInstallCU_Master] Leaving EndProcessing Method of Get-SPEnterpriseSearchServiceApplication.
VERBOSE: [CONTENTFARM]:                            [[SPProductUpdate]APPLICATION_SpsInstallCU_Master] Search Services are stopped
VERBOSE: [CONTENTFARM]:                            [[SPProductUpdate]APPLICATION_SpsInstallCU_Master] Stopping other services
VERBOSE: [CONTENTFARM]:                            [[SPProductUpdate]APPLICATION_SpsInstallCU_Master] Beginning installation of the SharePoint update
VERBOSE: [CONTENTFARM]:                            [[SPProductUpdate]APPLICATION_SpsInstallCU_Master] Executing as the local run as user CONTOSO\CSAPTTD10SPSFSP
VERBOSE: [CONTENTFARM]: LCM:  [ End    Set      ]  [[SPProductUpdate]APPLICATION_SpsInstallCU_Master]  in 52.3210 seconds.
PowerShell DSC resource MSFT_SPProductUpdate  failed to execute Set-TargetResource functionality with error message: SharePoint update install failed, exit code was 17028. Error codes can be found at 
https://aka.ms/installerrorcodes 
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : ProviderOperationExecutionFailure
    + PSComputerName        : ContentFarm

thanks for your help

**Comment by andikrueger** [comment]
@philippe-entringer are you testing with this branch? If not please see #679 for further information. Currently we are working on a fix for this issue. Could you try this branches updates in your scenario? This would be great help!

**Comment by philippe-entringer** [comment]
I ve just tested your branch.
I get an error when executing the SPProductUpdate, 
I remove the cast [System.Version] ligne 331

$installedVersion = Get-SPDSCInstalledProductVersion_

Now it's working great ;)

Thanks

**Comment by andikrueger** [comment]
I will create a new branch for this PR based on the current dev branch.. Rebasing this PR is a nightmare.

**Pull request closed without merging**
