### PR TITLE
Bugfix PR for several issues

### PR DESCRIPTION
**Pull request by ykuijs**
This PR fixes the following issues:
#481 #533 #518 #523 #527 #502 #535 #537 #534 #557 #529 #532 #560 #553

- [X] Change details added to Unreleased section of changelog.md?
- [X] Added/updated documentation and descriptions in .schema.mof files where appropriate?
- [X] Examples updated for both the single server and small farm templates in the examples folder?
- [X] New/changed code adheres to [Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md)?
- [X] [Unit and Integration tests](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md) created/updated where possible?

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/sharepointdsc/570)

### CODE REVIEW

**Comment by BrianFarnhill** [comment]
Reviewed 68 of 68 files at r1.
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPFarm/MSFT_SPFarm.psm1, line 169 at r1](https://reviewable.io:443/reviews/powershell/sharepointdsc/570#-KhUBsAgYo0VNv6YMEQ5:-KhUBsAgYo0VNv6YMEQ6:b-7lhtwh) ([raw file](https://github.com/powershell/sharepointdsc/blob/8f6a2e91bc53c93fcd1536fed353a4753179ff97/Modules/SharePointDsc/DSCResources/MSFT_SPFarm/MSFT_SPFarm.psm1#L169)):*
> ```PowerShell
>                 Passphrase = $null 
>                 AdminContentDatabaseName = $centralAdminSite.ContentDatabases[0].Name
>                 RunCentralAdmin = $centralAdminProvisioned
> ```

So this is just going to tell me if Central Admin exists in the farm, not that it is running on the current node. What we need to do here is look for the Central Admin service instance through Get-SPServiceInstance to find if its running on this computer

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPInstallLanguagePack/Readme.md, line 12 at r1](https://reviewable.io:443/reviews/powershell/sharepointdsc/570#-KhUCaIel5b5Tz4jjQBG:-KhUCaIel5b5Tz4jjQBH:b-ijkvkf) ([raw file](https://github.com/powershell/sharepointdsc/blob/8f6a2e91bc53c93fcd1536fed353a4753179ff97/Modules/SharePointDsc/DSCResources/MSFT_SPInstallLanguagePack/Readme.md#L12)):*
> ```Markdown
> With SharePoint 2016, the Language Packs are offered as an EXE package. You have
> to extract this package before installing, using the following command:
> .\serverlanguagepack.exe /extract:<Extract Folder>
> ```

We need an empty line at the bottom of this file

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPManagedMetadataServiceApp/MSFT_SPManagedMetaDataServiceApp.psm1, line 89 at r1](https://reviewable.io:443/reviews/powershell/sharepointdsc/570#-KhUCu4AONzwkx7Tjhcp:-KhUCu4AONzwkx7Tjhcq:b-ac9sa5) ([raw file](https://github.com/powershell/sharepointdsc/blob/8f6a2e91bc53c93fcd1536fed353a4753179ff97/Modules/SharePointDsc/DSCResources/MSFT_SPManagedMetadataServiceApp/MSFT_SPManagedMetaDataServiceApp.psm1#L89)):*
> ```PowerShell
>                 $defaultPartitionId = [Guid]::Parse("0C37852B-34D0-418e-91C6-2AC25AF4BE5B")
> 
>                 if ((Get-SPDSCInstalledProductVersion).FileMajorPart -eq 15)
> ```

rather than "if 15 else everything else" approach, can we swap this for a switch statement, that has 15 and 16 as options, and a default option that throws an error for an unsupported version

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPQuotaTemplate/readme.md, line 8 at r1](https://reviewable.io:443/reviews/powershell/sharepointdsc/570#-KhUDAboXDfTKRYeOzpx:-KhUDAboXDfTKRYeOzpy:bbis4q3) ([raw file](https://github.com/powershell/sharepointdsc/blob/8f6a2e91bc53c93fcd1536fed353a4753179ff97/Modules/SharePointDsc/DSCResources/MSFT_SPQuotaTemplate/readme.md#L8)):*
> ```Markdown
> 
> The default value for the Ensure parameter is Present. When not specifying this
> parameter, the quota template is created.
> ```

Need an empty line at the end of this file

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPSecureStoreServiceApp/MSFT_SPSecureStoreServiceApp.psm1, line 373 at r1](https://reviewable.io:443/reviews/powershell/sharepointdsc/570#-KhUDVhLT2_6aqLdxejI:-KhUDVhLT2_6aqLdxejJ:b-giu9id) ([raw file](https://github.com/powershell/sharepointdsc/blob/8f6a2e91bc53c93fcd1536fed353a4753179ff97/Modules/SharePointDsc/DSCResources/MSFT_SPSecureStoreServiceApp/MSFT_SPSecureStoreServiceApp.psm1#L373)):*
> ```PowerShell
>     return Test-SPDscParameterState -CurrentValues $CurrentValues `
>                                     -DesiredValues $PSBoundParameters `
>                                     -ValuesToCheck @("ApplicationPool", "DatabaseName", "DatabaseServer", "FailoverDatabaseServer", Ensure")
> ```

How confident are we that this will move the database to a new server if I chance the database name or server property here? We've traditionally stayed clear of anything that would move databases to new servers so far - have you actually tested if this will work?

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPServiceAppProxyGroup/readme.md, line 20 at r1](https://reviewable.io:443/reviews/powershell/sharepointdsc/570#-KhUEWFt7ZHYEdwCBDoo:-KhUEWFt7ZHYEdwCBDop:brnx049) ([raw file](https://github.com/powershell/sharepointdsc/blob/8f6a2e91bc53c93fcd1536fed353a4753179ff97/Modules/SharePointDsc/DSCResources/MSFT_SPServiceAppProxyGroup/readme.md#L20)):*
> ```Markdown
> the ServiceAppProxies property with the ServiceAppProxiesToInclude and
> 
> The default value for the Ensure parameter is Present. When not specifying this
> ```

Need an empty line at the bottom of this file

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPSite/readme.md, line 14 at r1](https://reviewable.io:443/reviews/powershell/sharepointdsc/570#-KhUDvo8lK2quT_tZZ4t:-KhUDvo8lK2quT_tZZ4u:b6jf736) ([raw file](https://github.com/powershell/sharepointdsc/blob/8f6a2e91bc53c93fcd1536fed353a4753179ff97/Modules/SharePointDsc/DSCResources/MSFT_SPSite/readme.md#L14)):*
> ```Markdown
> parameter in SPWebApplication. This will set the specified host header on your
> IIS site and prevent the site from listening for the URL of the Host Header
> Site Collection.
> ```

Can we add a note here that those bindings can also be edited with the xWebsite resource in the xWebAdministration module as well

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPTrustedIdentityTokenIssuer/readme.md, line 30 at r1](https://reviewable.io:443/reviews/powershell/sharepointdsc/570#-KhUE3P9STZVPoVu-mdC:-KhUE3PA-Z8pMypuQJAa:b-ue6pee) ([raw file](https://github.com/powershell/sharepointdsc/blob/8f6a2e91bc53c93fcd1536fed353a4753179ff97/Modules/SharePointDsc/DSCResources/MSFT_SPTrustedIdentityTokenIssuer/readme.md#L30)):*
> ```Markdown
> 
> The default value for the Ensure parameter is Present. When not specifying this
> parameter, the token issuer is created.
> ```

Need a blank line at the bottom of this file

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPUserProfileProperty/readme.md, line 17 at r1](https://reviewable.io:443/reviews/powershell/sharepointdsc/570#-KhUE6r4CS3jofPz6rdk:-KhUE6r4CS3jofPz6rdl:brnx049) ([raw file](https://github.com/powershell/sharepointdsc/blob/8f6a2e91bc53c93fcd1536fed353a4753179ff97/Modules/SharePointDsc/DSCResources/MSFT_SPUserProfileProperty/readme.md#L17)):*
> ```Markdown
> 
> The default value for the Ensure parameter is Present. When not specifying this
> parameter, the user profile property is created.
> ```

Need an empty line at the bottom of this file

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPWebApplication/readme.md, line 14 at r1](https://reviewable.io:443/reviews/powershell/sharepointdsc/570#-KhUECQ9Muj-YvDwoBQg:-KhUECQAnrSgRI4_8dI4:b-3d22z6) ([raw file](https://github.com/powershell/sharepointdsc/blob/8f6a2e91bc53c93fcd1536fed353a4753179ff97/Modules/SharePointDsc/DSCResources/MSFT_SPWebApplication/readme.md#L14)):*
> ```Markdown
> parameter in SPWebApplication. This will set the specified host header on your
> IIS site and prevent the site from listening for the URL of the Host Header
> Site Collection.
> ```

Same remark here about mentioning xWebsite as an option for setting bindings

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/570)*

**Comment by ykuijs** [comment]
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPFarm/MSFT_SPFarm.psm1, line 169 at r1](https://reviewable.io:443/reviews/powershell/sharepointdsc/570#-KhUBsAgYo0VNv6YMEQ5:-KhWWjKOwwMf678mb0Sn:b-896fix) ([raw file](https://github.com/powershell/sharepointdsc/blob/8f6a2e91bc53c93fcd1536fed353a4753179ff97/Modules/SharePointDsc/DSCResources/MSFT_SPFarm/MSFT_SPFarm.psm1#L169)):*
<details><summary><i>Previously, BrianFarnhill (Brian Farnhill) wrote…</i></summary><blockquote>

So this is just going to tell me if Central Admin exists in the farm, not that it is running on the current node. What we need to do here is look for the Central Admin service instance through Get-SPServiceInstance to find if its running on this computer
</blockquote></details>

Done.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPInstallLanguagePack/Readme.md, line 12 at r1](https://reviewable.io:443/reviews/powershell/sharepointdsc/570#-KhUCaIel5b5Tz4jjQBG:-KhWWkOaAXPzZeCNLlOZ:b-896fix) ([raw file](https://github.com/powershell/sharepointdsc/blob/8f6a2e91bc53c93fcd1536fed353a4753179ff97/Modules/SharePointDsc/DSCResources/MSFT_SPInstallLanguagePack/Readme.md#L12)):*
<details><summary><i>Previously, BrianFarnhill (Brian Farnhill) wrote…</i></summary><blockquote>

We need an empty line at the bottom of this file
</blockquote></details>

Done.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPManagedMetadataServiceApp/MSFT_SPManagedMetaDataServiceApp.psm1, line 89 at r1](https://reviewable.io:443/reviews/powershell/sharepointdsc/570#-KhUCu4AONzwkx7Tjhcp:-KhWWlOH7bdTsWhv3NwC:b-896fix) ([raw file](https://github.com/powershell/sharepointdsc/blob/8f6a2e91bc53c93fcd1536fed353a4753179ff97/Modules/SharePointDsc/DSCResources/MSFT_SPManagedMetadataServiceApp/MSFT_SPManagedMetaDataServiceApp.psm1#L89)):*
<details><summary><i>Previously, BrianFarnhill (Brian Farnhill) wrote…</i></summary><blockquote>

rather than "if 15 else everything else" approach, can we swap this for a switch statement, that has 15 and 16 as options, and a default option that throws an error for an unsupported version
</blockquote></details>

Done.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPQuotaTemplate/readme.md, line 8 at r1](https://reviewable.io:443/reviews/powershell/sharepointdsc/570#-KhUDAboXDfTKRYeOzpx:-KhWWmJOad_UTXnV_k8e:b-896fix) ([raw file](https://github.com/powershell/sharepointdsc/blob/8f6a2e91bc53c93fcd1536fed353a4753179ff97/Modules/SharePointDsc/DSCResources/MSFT_SPQuotaTemplate/readme.md#L8)):*
<details><summary><i>Previously, BrianFarnhill (Brian Farnhill) wrote…</i></summary><blockquote>

Need an empty line at the end of this file
</blockquote></details>

Done.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPSecureStoreServiceApp/MSFT_SPSecureStoreServiceApp.psm1, line 373 at r1](https://reviewable.io:443/reviews/powershell/sharepointdsc/570#-KhUDVhLT2_6aqLdxejI:-KhWWnbuVcP0l8rq57QI:b-7dke11) ([raw file](https://github.com/powershell/sharepointdsc/blob/8f6a2e91bc53c93fcd1536fed353a4753179ff97/Modules/SharePointDsc/DSCResources/MSFT_SPSecureStoreServiceApp/MSFT_SPSecureStoreServiceApp.psm1#L373)):*
<details><summary><i>Previously, BrianFarnhill (Brian Farnhill) wrote…</i></summary><blockquote>

How confident are we that this will move the database to a new server if I chance the database name or server property here? We've traditionally stayed clear of anything that would move databases to new servers so far - have you actually tested if this will work?
</blockquote></details>

The resource is not able to move or rename the database, just like all other resources are not able to do this. My goal was to have the parameters checked.

I have now changed the code to match the logic in other resources.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPServiceAppProxyGroup/readme.md, line 20 at r1](https://reviewable.io:443/reviews/powershell/sharepointdsc/570#-KhUEWFt7ZHYEdwCBDoo:-KhWXB95HQNyFDEyieIW:b-896fix) ([raw file](https://github.com/powershell/sharepointdsc/blob/8f6a2e91bc53c93fcd1536fed353a4753179ff97/Modules/SharePointDsc/DSCResources/MSFT_SPServiceAppProxyGroup/readme.md#L20)):*
<details><summary><i>Previously, BrianFarnhill (Brian Farnhill) wrote…</i></summary><blockquote>

Need an empty line at the bottom of this file
</blockquote></details>

Done.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPSite/readme.md, line 14 at r1](https://reviewable.io:443/reviews/powershell/sharepointdsc/570#-KhUDvo8lK2quT_tZZ4t:-KhWXBwe289G7c-kHnHW:b-896fix) ([raw file](https://github.com/powershell/sharepointdsc/blob/8f6a2e91bc53c93fcd1536fed353a4753179ff97/Modules/SharePointDsc/DSCResources/MSFT_SPSite/readme.md#L14)):*
<details><summary><i>Previously, BrianFarnhill (Brian Farnhill) wrote…</i></summary><blockquote>

Can we add a note here that those bindings can also be edited with the xWebsite resource in the xWebAdministration module as well
</blockquote></details>

Done.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPTrustedIdentityTokenIssuer/readme.md, line 30 at r1](https://reviewable.io:443/reviews/powershell/sharepointdsc/570#-KhUE3P9STZVPoVu-mdC:-KhWXCi6_xxtC3mRph6p:b-896fix) ([raw file](https://github.com/powershell/sharepointdsc/blob/8f6a2e91bc53c93fcd1536fed353a4753179ff97/Modules/SharePointDsc/DSCResources/MSFT_SPTrustedIdentityTokenIssuer/readme.md#L30)):*
<details><summary><i>Previously, BrianFarnhill (Brian Farnhill) wrote…</i></summary><blockquote>

Need a blank line at the bottom of this file
</blockquote></details>

Done.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPUserProfileProperty/readme.md, line 17 at r1](https://reviewable.io:443/reviews/powershell/sharepointdsc/570#-KhUE6r4CS3jofPz6rdk:-KhWXD_no94r4wTdv7MJ:b-896fix) ([raw file](https://github.com/powershell/sharepointdsc/blob/8f6a2e91bc53c93fcd1536fed353a4753179ff97/Modules/SharePointDsc/DSCResources/MSFT_SPUserProfileProperty/readme.md#L17)):*
<details><summary><i>Previously, BrianFarnhill (Brian Farnhill) wrote…</i></summary><blockquote>

Need an empty line at the bottom of this file
</blockquote></details>

Done.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPWebApplication/readme.md, line 14 at r1](https://reviewable.io:443/reviews/powershell/sharepointdsc/570#-KhUECQ9Muj-YvDwoBQg:-KhWXEG-WOihwfpmnGEt:b-896fix) ([raw file](https://github.com/powershell/sharepointdsc/blob/8f6a2e91bc53c93fcd1536fed353a4753179ff97/Modules/SharePointDsc/DSCResources/MSFT_SPWebApplication/readme.md#L14)):*
<details><summary><i>Previously, BrianFarnhill (Brian Farnhill) wrote…</i></summary><blockquote>

Same remark here about mentioning xWebsite as an option for setting bindings
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/570)*

**Comment by ykuijs** [comment]
Just discovered a small issue in the Get-SPServiceInstance code. Am fixing this as we speak. Expect another commit soon.

**Comment by BrianFarnhill** [comment]
:lgtm:

---

Reviewed 8 of 11 files at r2, 2 of 3 files at r3, 5 of 5 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/570#-:-KhZvzDnM2iIaAWbkQpi:bnfp4nl)*

**Pull request merged**
