### PR TITLE
New resource: SPSearchServiceSettings

### LINKED ISSUE #923: Resources that use TypeName for Service Instance: Not working for non-english environments
#### Details of the scenario you tried and the problem that is occurring
The SPBlobCacheSettings resource tries to retrieve and configure the blob cache, only if the "Microsoft SharePoint Foundation Web Application" service is started on the server. However, we should use TypeName to determine if a service is started or not since it is culture dependent. E.g. my client has a French SharePoint environment and the service TypeName is "Application Web de Microsoft SharePoint Foundation" and therefore never detects or configures it.

This issue is widespread across multiple resource. We should modify every resource that uses the property TypeName to determine the status or retrieve an instance, so that it uses a parameter that is culture independent.

#### Verbose logs showing the problem
N/A

#### Suggested solution to the issue
Use .GetType().Name where possible (Web Foundation and Central Admin have the same name, so it won't work in that case), or the Name itself to determine the instance of the service (Central Admin has a name of Wss_Administration, and web foundation has an empty name).

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
N/A

#### The operating system the target node is running
Windows Server 2012 R2 (French)

#### Version of SharePoint that is used (e.g. SharePoint 2016)
SharePoint 2013

#### Version and build of PowerShell the target node is running
PoSh 4

#### Version of the DSC module that was used ('dev' if using current dev branch)
2.5.0.0

### LINKED ISSUE #966: SPSearchServiceApp: Missing PerformanceLevel Property
#### Details of the scenario you tried and the problem that is occurring
It is not possible to set the performance level within the SPSearchServiceApp. Actually I did not find any other ressource that includes that property.

#### Verbose logs showing the problem
N/A

#### Suggested solution to the issue
Implement a performance level property. As used in our project. I already tried to write it into the Set-Method.
```powershell
function Set-TargetResource
{
    [CmdletBinding()]
    param
    (
    ...
        [Parameter()] 
        [ValidateSet("Reduced","PartlyReduced","Maximum")] 
        [System.String] 
        $PerformanceLevel
    ...
    )
    ...
    $app = New-SPEnterpriseSearchServiceApplication @newParams
    if ($app)
    {
        if ($null -ne $params.PerformanceLevel)
        {
            $app | Set-SPEnterpriseSearchService -PerformanceLevel $params.PerformanceLevel
        }
    }
    ...
}
```
#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
N/A

#### The operating system the target node is running
N/A

#### Version of SharePoint that is used (e.g. SharePoint 2016)
SharePoint 2016

#### Version and build of PowerShell the target node is running
5.1

#### Version of the DSC module that was used ('dev' if using current dev branch)
2.1.0.0

### LINKED ISSUE #974: SPSearchServiceApp: (Discussion) Do we need to move the WindowsServiceAccount parameter to a new resource
The SPSearchServiceApp resource has a parameter to configure the WindowsServiceAccount. This property however is an environment wide setting, not service app specific:
https://github.com/PowerShell/SharePointDsc/blob/c6940e463f3c75292fb0f9cada586eadbb9e1e3a/Modules/SharePointDsc/DSCResources/MSFT_SPSearchServiceApp/MSFT_SPSearchServiceApp.psm1#L293

With the current implementation it is possible to set the WindowsServiceAccount to Account1 in SearchServiceApp1 and change it to Account2 in SearchServiceApp2. This will result in conflict, flipping the account back and forth.

Issue #966 also requests a parameter that is search specific. Is it an idea to combine these parameters into a new SPSearchService resource?

This can be a breaking change if we remove the parameter from the resource. But we since we just released v3.0, we have to wait until v4. In the meantime we can remove the code that implements the changes, so the parameter actually doesn't do anything but won't break existing configs at the same time.

@NikCharlebois What is your opinion?

### LINKED ISSUE #986: MSFT_SPInstallPrereqs: MSVCRT11 missing
#### Verbose logs showing the problem
When installing SharePoint 2019 the prereq MSVCRT11 is not required
#### Suggested solution to the issue
Add the MSVCRT11 to the requirements of SharePoint 2019
#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
# insert configuration here
`PInstallPrereqs InstallPrereqs {
            IsSingleInstance  = "Yes"
            Ensure            = "Present"
            InstallerPath     = "media\Sharepoint2019\PrerequisiteInstaller.exe"
            OnlineMode        = $false
            SXSpath           = "\media\SXS"
            KB3092423         = "\media\PreRequirements\sp2019\AppFabric-KB3092423-x64-ENU.exe"
            IDFX11            = "media\PreRequirements\sp2019\MicrosoftIdentityExtensions-64.msi"
            MSIPCClient       = "\\media\PreRequirements\sp2019\setup_msipc_x64.exe"
            SQLNCli           = "\media\PreRequirements\sp2019\sqlncli.msi"
            WCFDataServices56 = "media\PreRequirements\sp2019\WcfDataServices.exe"
            AppFabric         = "media\PreRequirements\sp2019\WindowsServerAppFabricSetup_x64.exe"
            DotNet472     = "\media\PreRequirements\sp2019\NDP472-KB4054530-x86-x64-AllOS-ENU.exe"
            Sync              = "\media\PreRequirements\sp2019\Synchronization.msi"
            MSVCRT11          = "\media\PreRequirements\sp2019\vcredist_x64.exe"
            MSVCRT141          = "\media\PreRequirements\sp2019\vc_redist.x64.exe"
        }
#### The operating system the target node is running

OsName               : Microsoft Windows Server 2016 Standard
OsOperatingSystemSKU : StandardServerEdition
OsArchitecture       : 64-bit
WindowsBuildLabEx    : 14393.2608.amd64fre.rs1_release.181024-1742
OsLanguage           : en-US
OsMuiLanguages       : {en-US} 

#### Version of SharePoint that is used (e.g. SharePoint 2016)
SharePoint 2019
#### Version and build of PowerShell the target node is running

Name                           Value                                                                                                                                  
----                           -----                                                                                                                                  
PSVersion                      5.1.14393.2608                                                                                                                         
PSEdition                      Desktop                                                                                                                                
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                
BuildVersion                   10.0.14393.2608                                                                                                                        
CLRVersion                     4.0.30319.42000                                                                                                                        
WSManStackVersion              3.0                                                                                                                                    
PSRemotingProtocolVersion      2.3                                                                                                                                    
SerializationVersion           1.1.0.1     

#### Version of the DSC module that was used ('dev' if using current dev branch)
3.0

### PR DESCRIPTION
**Pull request by ykuijs**
#### Pull Request (PR) description
This PR adds a new resource SPSearchServiceSettings

#### This Pull Request (PR) fixes the following issues
- Fixes #923 
- Fixes #974 
- Fixes #966 
- Fixes #986 

#### Task list
- [X] Added an entry under the Unreleased section of the change log in the CHANGELOG.md.
      Entry should say what was changed, and how that affects users (if applicable).
- [X] Resource documentation added/updated in README.md in the resource folder.
- [X] Resource parameter descriptions added/updated in schema.mof
      and comment-based help.
- [X] Comment-based help added/updated.
- [X] Localization strings added/updated in all localization files as appropriate.
- [X] Examples appropriately added/updated.
- [X] Unit tests added/updated. See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [X] Integration tests added/updated (where possible). See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [X] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/sharepointdsc/978)

### CODE REVIEW

**Comment by ykuijs** [comment]
@NikCharlebois, @andikrueger One of you guys got some time for a review?

**Comment by NikCharlebois** [comment]
Yep I am on it

**Comment by ykuijs** [comment]
@NikCharlebois Can you please finalized this PR, so I can merge it?

**Comment by ykuijs** [comment]
Ok, I messed up: I implemented a fix which was supposed to go into the rollup branch in this branch by mistake :-(

This will need another (minor) review. My apologies.

**Pull request merged**
