### PR TITLE
Yet another bugfix Rollup

### PR DESCRIPTION
**Pull request by ykuijs**
Implemented several bugfixes for the following issues:
#621, #618, #614, #610, #605, #602, #611, #609, #464, #622, #613

- [X] Change details added to Unreleased section of changelog.md?
- [X] Added/updated documentation and descriptions in .schema.mof files where appropriate?
- [X] Examples updated for both the single server and small farm templates in the examples folder?
- [X] New/changed code adheres to [Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md)?
- [X] [Unit and Integration tests](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md) created/updated where possible?

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/sharepointdsc/630)

### CODE REVIEW

**Comment by BrianFarnhill** [comment]
Reviewed 20 of 20 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPProductUpdate/MSFT_SPProductUpdate.psm1, line 53 at r1](https://reviewable.io:443/reviews/powershell/sharepointdsc/630#-Knq7QS_6kB_uVs66T5M:-Knq7QS_6kB_uVs66T5N:b4qkan8) ([raw file](https://github.com/powershell/sharepointdsc/blob/72cd9343aa8c04f5f96b83f4ae1753811a113a0a/Modules/SharePointDsc/DSCResources/MSFT_SPProductUpdate/MSFT_SPProductUpdate.psm1#L53)):*
> ```PowerShell
> 
>     Write-Verbose -Message "Checking file status of $SetupFile"
>     $zone = Get-Item $SetupFile -Stream "Zone.Identifier" -EA SilentlyContinue
> ```

Positional parameter use on, need to specify -Path before $SetupFile

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPQuotaTemplate/MSFT_SPQuotaTemplate.psm1, line 46 at r1](https://reviewable.io:443/reviews/powershell/sharepointdsc/630#-Knq9GLWeurGVyWxzcYZ:-Knq9GLWeurGVyWxzcY_:b33f5sj) ([raw file](https://github.com/powershell/sharepointdsc/blob/72cd9343aa8c04f5f96b83f4ae1753811a113a0a/Modules/SharePointDsc/DSCResources/MSFT_SPQuotaTemplate/MSFT_SPQuotaTemplate.psm1#L46)):*
> ```PowerShell
>     if ($MaximumUsagePointsSolutions -lt $WarningUsagePointsSolutions) 
>     {
>         Throw ("MaximumUsagePointsSolutions must be equal to or larger than " + `
> ```

The code coverage on this file is down below 70% right now, and these exceptions don't look like they are being hit. Any chance you can look at making sure these throws are actually being thrown and that should get the file above 70%, which will do as a baseline

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPWebAppSiteUseAndDeletion/MSFT_SPWebAppSiteUseAndDeletion.psm1, line 135 at r1](https://reviewable.io:443/reviews/powershell/sharepointdsc/630#-Knq9t-ybblgiciGtJtp:-Knq9t-ybblgiciGtJtq:bwgo639) ([raw file](https://github.com/powershell/sharepointdsc/blob/72cd9343aa8c04f5f96b83f4ae1753811a113a0a/Modules/SharePointDsc/DSCResources/MSFT_SPWebAppSiteUseAndDeletion/MSFT_SPWebAppSiteUseAndDeletion.psm1#L135)):*
> ```PowerShell
>         {
>             # Check schedule value     
>             switch ($job.Schedule.Description)
> ```

Looking at the codecov report this switch block doesn't appear to be getting covered, all the way down through to the wa.Update() line, so I think there is nothing coming down this 'else' path. Can I get you to have a look at that one and see what comes out of it? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/630)*

**Comment by BrianFarnhill** [comment]
@ykuijs Also looks like there are a couple of failing tests that should be looked at as well here mate

**Comment by ykuijs** [comment]
My submission was just before midnight and since the Appveyor test takes quite some time, I was not able to check the results yet :-)

Will check why the tests failed and incorporate your review comments.

**Comment by ykuijs** [comment]
@BrianFarnhill, any clue why AppVeyor is giving me the following error:
  Describing Common Tests - Validate Example Files
    [-] Error occurred in Describe block 299ms
      The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.
      At C:\projects\sharepointdsc\Modules\SharePointDsc\DSCResource.Tests\Meta.Tests.ps1:475 char:23

**Comment by ykuijs** [comment]
Review status: 16 of 22 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPProductUpdate/MSFT_SPProductUpdate.psm1, line 53 at r1](https://reviewable.io:443/reviews/powershell/sharepointdsc/630#-Knq7QS_6kB_uVs66T5M:-Kntp7yhOmswl7fArOxV:b-896fix) ([raw file](https://github.com/powershell/sharepointdsc/blob/72cd9343aa8c04f5f96b83f4ae1753811a113a0a/Modules/SharePointDsc/DSCResources/MSFT_SPProductUpdate/MSFT_SPProductUpdate.psm1#L53)):*
<details><summary><i>Previously, BrianFarnhill (Brian Farnhill) wrote…</i></summary><blockquote>

Positional parameter use on, need to specify -Path before $SetupFile
</blockquote></details>

Done.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPQuotaTemplate/MSFT_SPQuotaTemplate.psm1, line 46 at r1](https://reviewable.io:443/reviews/powershell/sharepointdsc/630#-Knq9GLWeurGVyWxzcYZ:-Kntp32aZnQhXoIipt0d:b-896fix) ([raw file](https://github.com/powershell/sharepointdsc/blob/72cd9343aa8c04f5f96b83f4ae1753811a113a0a/Modules/SharePointDsc/DSCResources/MSFT_SPQuotaTemplate/MSFT_SPQuotaTemplate.psm1#L46)):*
<details><summary><i>Previously, BrianFarnhill (Brian Farnhill) wrote…</i></summary><blockquote>

The code coverage on this file is down below 70% right now, and these exceptions don't look like they are being hit. Any chance you can look at making sure these throws are actually being thrown and that should get the file above 70%, which will do as a baseline
</blockquote></details>

Done.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPWebAppSiteUseAndDeletion/MSFT_SPWebAppSiteUseAndDeletion.psm1, line 135 at r1](https://reviewable.io:443/reviews/powershell/sharepointdsc/630#-Knq9t-ybblgiciGtJtp:-Kntp5LDzPTKHra48Coo:b-896fix) ([raw file](https://github.com/powershell/sharepointdsc/blob/72cd9343aa8c04f5f96b83f4ae1753811a113a0a/Modules/SharePointDsc/DSCResources/MSFT_SPWebAppSiteUseAndDeletion/MSFT_SPWebAppSiteUseAndDeletion.psm1#L135)):*
<details><summary><i>Previously, BrianFarnhill (Brian Farnhill) wrote…</i></summary><blockquote>

Looking at the codecov report this switch block doesn't appear to be getting covered, all the way down through to the wa.Update() line, so I think there is nothing coming down this 'else' path. Can I get you to have a look at that one and see what comes out of it? 
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/630)*

**Comment by BrianFarnhill** [comment]
@ykuijs Don't stress about that test, I've raised an issue for it at https://github.com/PowerShell/DscResource.Tests/issues/144 and we'll see what we can do to get it fixed.

**Comment by BrianFarnhill** [comment]
:lgtm:

---

Reviewed 5 of 6 files at r2, 5 of 5 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/630#-:-Ko4R3COkuXR80UZF6Cf:bnfp4nl)*

**Pull request merged**
