### PR TITLE
Extend SPWeb with the ability to change the email address for access requests

### LINKED ISSUE #539: Extend SPSite with the ability to change the email address for access requests
Details of the scenario you try and problem that is occurring:
[Help Wanted]
I configured SPOutgoingEmailSettings with email address From and ReplyTo addresses at the farm level, however Access Request Settings at a Site Collection level do not retain this email setting for "Send requests for access to the following email address:" parameter, and I do not see a setting for this at the SPSite keyword documentation. 
Can this be automated presently? Or does this presently require a manual configuration step?

Attaching the screenshot at the site collection level setting, as well as the DSC configuration script presently being used
access request settings
[sp2016singleserver.zip](https://github.com/PowerShell/SharePointDsc/files/855882/sp2016singleserver.zip)

The DSC configuration that is using the resource:
Single Server Farm created using SharePointDSC with site collections created using the SPSite keyword

Version of the Operating System and PowerShell the DSC Target Node is running:
Target system is running Window Server 2012 R2 running Powershell v5.0.10586.20151218

Version of the DSC module you're using:
SharePointDSC v1.6.0.0

### PR DESCRIPTION
**Pull request by andikrueger**
Closes #539 .

Extended the SPWeb resource with the ability to change the request access mail address.

- [x] Change details added to Unreleased section of changelog.md?
- [x] Added/updated documentation and descriptions in .schema.mof files where appropriate?
- [x] Examples updated for both the single server and small farm templates in the examples folder?
- [x] New/changed code adheres to [Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md)?
- [x] [Unit and Integration tests](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md) created/updated where possible?

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/sharepointdsc/667)

### CODE REVIEW

**Comment by ykuijs** [comment]
Great update, also the additional checks you implemented to check if the parameter is actually used! Just a few minor coding styleguide remarks.

---

Reviewed 3 of 6 files at r1, 1 of 2 files at r2, 1 of 1 files at r3.
Review status: 5 of 6 files reviewed at latest revision, 18 unresolved discussions.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPWeb/MSFT_SPWeb.psm1, line 1 at r3](https://reviewable.io:443/reviews/powershell/sharepointdsc/667#-KxqXxIWsG8DoYWMCP7x:-KxqXxIWsG8DoYWMCP7y:b-ae5xc3) ([raw file](https://github.com/powershell/sharepointdsc/blob/8627d4c337ccafbf2b4dd627aedb48e3b35f76ed/Modules/SharePointDsc/DSCResources/MSFT_SPWeb/MSFT_SPWeb.psm1#L1)):*
> ```PowerShell
> function Get-TargetResource {
> ```

Please follow the coding styleguide, which specifies that the curly brace should be on the next line

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPWeb/MSFT_SPWeb.psm1, line 47 at r3](https://reviewable.io:443/reviews/powershell/sharepointdsc/667#-KxqY5VecgtqnZqnBwaA:-KxqY5VecgtqnZqnBwaB:bfxj099) ([raw file](https://github.com/powershell/sharepointdsc/blob/8627d4c337ccafbf2b4dd627aedb48e3b35f76ed/Modules/SharePointDsc/DSCResources/MSFT_SPWeb/MSFT_SPWeb.psm1#L47)):*
> ```PowerShell
>         $AddToTopNav,
> 
>         [Parameter(Mandatory = $false)]
> ```

Please remove the "Mandatory = $false" bit, which is a Best Practice from the PSScriptAnalyzer (the rest of the parameters will be corrected in PR660)

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPWeb/MSFT_SPWeb.psm1, line 90 at r3](https://reviewable.io:443/reviews/powershell/sharepointdsc/667#-KxqYJx9DN7g6TjmiO08:-KxqYJx9DN7g6TjmiO09:b-ae5xc3) ([raw file](https://github.com/powershell/sharepointdsc/blob/8627d4c337ccafbf2b4dd627aedb48e3b35f76ed/Modules/SharePointDsc/DSCResources/MSFT_SPWeb/MSFT_SPWeb.psm1#L90)):*
> ```PowerShell
> }
> 
> function Set-TargetResource {
> ```

Please follow the coding styleguide, which specifies that the curly brace should be on the next line

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPWeb/MSFT_SPWeb.psm1, line 135 at r3](https://reviewable.io:443/reviews/powershell/sharepointdsc/667#-KxqYN3Ja5z993gb34ud:-KxqYN3Ja5z993gb34ue:bfxj099) ([raw file](https://github.com/powershell/sharepointdsc/blob/8627d4c337ccafbf2b4dd627aedb48e3b35f76ed/Modules/SharePointDsc/DSCResources/MSFT_SPWeb/MSFT_SPWeb.psm1#L135)):*
> ```PowerShell
>         $AddToTopNav,
> 
>         [Parameter(Mandatory = $false)]
> ```

Please remove the "Mandatory = $false" bit, which is a Best Practice from the PSScriptAnalyzer (the rest of the parameters will be corrected in PR660)

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPWeb/MSFT_SPWeb.psm1, line 166 at r3](https://reviewable.io:443/reviews/powershell/sharepointdsc/667#-KxqYYibiI-nkM5WsDqa:-KxqYYiciGYv7W-e4MQv:b-ae5xc3) ([raw file](https://github.com/powershell/sharepointdsc/blob/8627d4c337ccafbf2b4dd627aedb48e3b35f76ed/Modules/SharePointDsc/DSCResources/MSFT_SPWeb/MSFT_SPWeb.psm1#L166)):*
> ```PowerShell
>         $web = Get-SPWeb -Identity $params.Url -ErrorAction SilentlyContinue
> 
>         if ($null -eq $web) {
> ```

Please follow the coding styleguide, which specifies that the curly brace should be on the next line

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPWeb/MSFT_SPWeb.psm1, line 169 at r3](https://reviewable.io:443/reviews/powershell/sharepointdsc/667#-KxqYZpPNjF52Ib-fD3h:-KxqYZpPNjF52Ib-fD3i:b-ae5xc3) ([raw file](https://github.com/powershell/sharepointdsc/blob/8627d4c337ccafbf2b4dd627aedb48e3b35f76ed/Modules/SharePointDsc/DSCResources/MSFT_SPWeb/MSFT_SPWeb.psm1#L169)):*
> ```PowerShell
>             @("InstallAccount", "Ensure", "RequestAccessEmail") | 
>                 ForEach-Object -Process {
>                 if ($params.ContainsKey($_) -eq $true) {
> ```

Please follow the coding styleguide, which specifies that the curly brace should be on the next line

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPWeb/MSFT_SPWeb.psm1, line 184 at r3](https://reviewable.io:443/reviews/powershell/sharepointdsc/667#-KxqYa2LAQnxPEuTkoX4:-KxqYa2LAQnxPEuTkoX5:b-ae5xc3) ([raw file](https://github.com/powershell/sharepointdsc/blob/8627d4c337ccafbf2b4dd627aedb48e3b35f76ed/Modules/SharePointDsc/DSCResources/MSFT_SPWeb/MSFT_SPWeb.psm1#L184)):*
> ```PowerShell
>                 
>                 if (($params.ContainsKey("Name") -eq $true) `
>                         -and $web.Title -ne $params.Name) {
> ```

Please follow the coding styleguide, which specifies that the curly brace should be on the next line

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPWeb/MSFT_SPWeb.psm1, line 190 at r3](https://reviewable.io:443/reviews/powershell/sharepointdsc/667#-KxqYb5TFc-2KMIWxl86:-KxqYb5TFc-2KMIWxl87:b-ae5xc3) ([raw file](https://github.com/powershell/sharepointdsc/blob/8627d4c337ccafbf2b4dd627aedb48e3b35f76ed/Modules/SharePointDsc/DSCResources/MSFT_SPWeb/MSFT_SPWeb.psm1#L190)):*
> ```PowerShell
> 
>                 if (($params.ContainsKey("Description") -eq $true) `
>                         -and $web.Description -ne $params.Description) {
> ```

Please follow the coding styleguide, which specifies that the curly brace should be on the next line

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPWeb/MSFT_SPWeb.psm1, line 196 at r3](https://reviewable.io:443/reviews/powershell/sharepointdsc/667#-KxqYcUq6avipT1Z2e5H:-KxqYcUq6avipT1Z2e5I:b-ae5xc3) ([raw file](https://github.com/powershell/sharepointdsc/blob/8627d4c337ccafbf2b4dd627aedb48e3b35f76ed/Modules/SharePointDsc/DSCResources/MSFT_SPWeb/MSFT_SPWeb.psm1#L196)):*
> ```PowerShell
> 
>                 if (($params.ContainsKey("UseParentTopNav") -eq $true) `
>                         -and $web.Navigation.UseShared -ne $params.UseParentTopNav) {
> ```

Please follow the coding styleguide, which specifies that the curly brace should be on the next line

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPWeb/MSFT_SPWeb.psm1, line 202 at r3](https://reviewable.io:443/reviews/powershell/sharepointdsc/667#-KxqYfsJldRX0-NdhkTD:-KxqYfsJldRX0-NdhkTE:b-ae5xc3) ([raw file](https://github.com/powershell/sharepointdsc/blob/8627d4c337ccafbf2b4dd627aedb48e3b35f76ed/Modules/SharePointDsc/DSCResources/MSFT_SPWeb/MSFT_SPWeb.psm1#L202)):*
> ```PowerShell
> 
>                 if (($params.ContainsKey("UniquePermissions") -eq $true) `
>                         -and $web.HasUniquePerm -ne $params.UniquePermissions) {
> ```

Please follow the coding styleguide, which specifies that the curly brace should be on the next line

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPWeb/MSFT_SPWeb.psm1, line 207 at r3](https://reviewable.io:443/reviews/powershell/sharepointdsc/667#-KxqYgtHN7L0qFTiTDPd:-KxqYgtITJ-3dB-oPzQl:b-ae5xc3) ([raw file](https://github.com/powershell/sharepointdsc/blob/8627d4c337ccafbf2b4dd627aedb48e3b35f76ed/Modules/SharePointDsc/DSCResources/MSFT_SPWeb/MSFT_SPWeb.psm1#L207)):*
> ```PowerShell
>                 }
> 
>                 if ($params.ContainsKey("RequestAccessEmail") -eq $true) {
> ```

Please follow the coding styleguide, which specifies that the curly brace should be on the next line

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPWeb/MSFT_SPWeb.psm1, line 208 at r3](https://reviewable.io:443/reviews/powershell/sharepointdsc/667#-KxqYne-M3vwh6Nkrlu9:-KxqYne-M3vwh6NkrluA:b-ae5xc3) ([raw file](https://github.com/powershell/sharepointdsc/blob/8627d4c337ccafbf2b4dd627aedb48e3b35f76ed/Modules/SharePointDsc/DSCResources/MSFT_SPWeb/MSFT_SPWeb.psm1#L208)):*
> ```PowerShell
> 
>                 if ($params.ContainsKey("RequestAccessEmail") -eq $true) {
>                     if ($web.RequestAccessEmail -ne $params.RequestAccessEmail -and $web.HasUniquePerm) {
> ```

Please follow the coding styleguide, which specifies that the curly brace should be on the next line

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPWeb/MSFT_SPWeb.psm1, line 209 at r3](https://reviewable.io:443/reviews/powershell/sharepointdsc/667#-KxqYou-Kl9XY9F156L7:-KxqYou-Kl9XY9F156L8:b-ae5xc3) ([raw file](https://github.com/powershell/sharepointdsc/blob/8627d4c337ccafbf2b4dd627aedb48e3b35f76ed/Modules/SharePointDsc/DSCResources/MSFT_SPWeb/MSFT_SPWeb.psm1#L209)):*
> ```PowerShell
>                 if ($params.ContainsKey("RequestAccessEmail") -eq $true) {
>                     if ($web.RequestAccessEmail -ne $params.RequestAccessEmail -and $web.HasUniquePerm) {
>                         if ([Boolean]$params.RequestAccessEmail -as [System.Net.Mail.MailAddress]) {
> ```

Please follow the coding styleguide, which specifies that the curly brace should be on the next line

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPWeb/MSFT_SPWeb.psm1, line 216 at r3](https://reviewable.io:443/reviews/powershell/sharepointdsc/667#-KxqYzYkrnunCtZZlIY9:-KxqYzYliCcCGEVnkZwb:b-ae5xc3) ([raw file](https://github.com/powershell/sharepointdsc/blob/8627d4c337ccafbf2b4dd627aedb48e3b35f76ed/Modules/SharePointDsc/DSCResources/MSFT_SPWeb/MSFT_SPWeb.psm1#L216)):*
> ```PowerShell
>                         $changedWeb = $true
>                     }     
>                     else {
> ```

Please follow the coding styleguide, which specifies that the curly brace should be on the next line

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPWeb/MSFT_SPWeb.psm1, line 221 at r3](https://reviewable.io:443/reviews/powershell/sharepointdsc/667#-KxqZ4XpR47HkfaSqaoP:-KxqZ4XpR47HkfaSqaoQ:b-ae5xc3) ([raw file](https://github.com/powershell/sharepointdsc/blob/8627d4c337ccafbf2b4dd627aedb48e3b35f76ed/Modules/SharePointDsc/DSCResources/MSFT_SPWeb/MSFT_SPWeb.psm1#L221)):*
> ```PowerShell
>                 }
>                 
>                 if ($changedWeb) {
> ```

Please follow the coding styleguide, which specifies that the curly brace should be on the next line

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPWeb/MSFT_SPWeb.psm1, line 229 at r3](https://reviewable.io:443/reviews/powershell/sharepointdsc/667#-KxqZ5pnU8QDz-G81dNH:-KxqZ5pnU8QDz-G81dNI:b-ae5xc3) ([raw file](https://github.com/powershell/sharepointdsc/blob/8627d4c337ccafbf2b4dd627aedb48e3b35f76ed/Modules/SharePointDsc/DSCResources/MSFT_SPWeb/MSFT_SPWeb.psm1#L229)):*
> ```PowerShell
> }
> 
> function Test-TargetResource {
> ```

Please follow the coding styleguide, which specifies that the curly brace should be on the next line

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPWeb/MSFT_SPWeb.psm1, line 275 at r3](https://reviewable.io:443/reviews/powershell/sharepointdsc/667#-KxqZCHMdFP6J8VbtvPI:-KxqZCHMdFP6J8VbtvPJ:bfxj099) ([raw file](https://github.com/powershell/sharepointdsc/blob/8627d4c337ccafbf2b4dd627aedb48e3b35f76ed/Modules/SharePointDsc/DSCResources/MSFT_SPWeb/MSFT_SPWeb.psm1#L275)):*
> ```PowerShell
>         $AddToTopNav,
> 
>         [Parameter(Mandatory = $false)]
> ```

Please remove the "Mandatory = $false" bit, which is a Best Practice from the PSScriptAnalyzer (the rest of the parameters will be corrected in PR660)

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPWeb/MSFT_SPWeb.psm1, line 297 at r3](https://reviewable.io:443/reviews/powershell/sharepointdsc/667#-KxqZ86i3fp5LNeeUOyG:-KxqZ86i3fp5LNeeUOyH:b-ae5xc3) ([raw file](https://github.com/powershell/sharepointdsc/blob/8627d4c337ccafbf2b4dd627aedb48e3b35f76ed/Modules/SharePointDsc/DSCResources/MSFT_SPWeb/MSFT_SPWeb.psm1#L297)):*
> ```PowerShell
>         "Ensure")
>         
>     if ($CurrentValues.UniquePermissions) {
> ```

Please follow the coding styleguide, which specifies that the curly brace should be on the next line

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/667#-:-KxqZUId4Yvl7Z1-fcwD:b-8jsth)*

**Comment by andikrueger** [comment]
Review status: 5 of 6 files reviewed at latest revision, 18 unresolved discussions.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPWeb/MSFT_SPWeb.psm1, line 1 at r3](https://reviewable.io:443/reviews/powershell/sharepointdsc/667#-KxqXxIWsG8DoYWMCP7x:-KxqkObBTEKim5kWqt8f:b-896fix) ([raw file](https://github.com/powershell/sharepointdsc/blob/8627d4c337ccafbf2b4dd627aedb48e3b35f76ed/Modules/SharePointDsc/DSCResources/MSFT_SPWeb/MSFT_SPWeb.psm1#L1)):*
<details><summary><i>Previously, ykuijs (Yorick Kuijs) wrote…</i></summary><blockquote>

Please follow the coding styleguide, which specifies that the curly brace should be on the next line
</blockquote></details>

Done.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPWeb/MSFT_SPWeb.psm1, line 47 at r3](https://reviewable.io:443/reviews/powershell/sharepointdsc/667#-KxqY5VecgtqnZqnBwaA:-KxqkURHFbYRTjq36fQw:b-896fix) ([raw file](https://github.com/powershell/sharepointdsc/blob/8627d4c337ccafbf2b4dd627aedb48e3b35f76ed/Modules/SharePointDsc/DSCResources/MSFT_SPWeb/MSFT_SPWeb.psm1#L47)):*
<details><summary><i>Previously, ykuijs (Yorick Kuijs) wrote…</i></summary><blockquote>

Please remove the "Mandatory = $false" bit, which is a Best Practice from the PSScriptAnalyzer (the rest of the parameters will be corrected in PR660)
</blockquote></details>

Done.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPWeb/MSFT_SPWeb.psm1, line 90 at r3](https://reviewable.io:443/reviews/powershell/sharepointdsc/667#-KxqYJx9DN7g6TjmiO08:-KxqkVPHDX5AQrLqVwov:b-896fix) ([raw file](https://github.com/powershell/sharepointdsc/blob/8627d4c337ccafbf2b4dd627aedb48e3b35f76ed/Modules/SharePointDsc/DSCResources/MSFT_SPWeb/MSFT_SPWeb.psm1#L90)):*
<details><summary><i>Previously, ykuijs (Yorick Kuijs) wrote…</i></summary><blockquote>

Please follow the coding styleguide, which specifies that the curly brace should be on the next line
</blockquote></details>

Done.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPWeb/MSFT_SPWeb.psm1, line 135 at r3](https://reviewable.io:443/reviews/powershell/sharepointdsc/667#-KxqYN3Ja5z993gb34ud:-KxqkW9qS3Q_qjmwliU1:b-896fix) ([raw file](https://github.com/powershell/sharepointdsc/blob/8627d4c337ccafbf2b4dd627aedb48e3b35f76ed/Modules/SharePointDsc/DSCResources/MSFT_SPWeb/MSFT_SPWeb.psm1#L135)):*
<details><summary><i>Previously, ykuijs (Yorick Kuijs) wrote…</i></summary><blockquote>

Please remove the "Mandatory = $false" bit, which is a Best Practice from the PSScriptAnalyzer (the rest of the parameters will be corrected in PR660)
</blockquote></details>

Done.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPWeb/MSFT_SPWeb.psm1, line 166 at r3](https://reviewable.io:443/reviews/powershell/sharepointdsc/667#-KxqYYibiI-nkM5WsDqa:-KxqkXgK4mJDrKViNuGn:b-896fix) ([raw file](https://github.com/powershell/sharepointdsc/blob/8627d4c337ccafbf2b4dd627aedb48e3b35f76ed/Modules/SharePointDsc/DSCResources/MSFT_SPWeb/MSFT_SPWeb.psm1#L166)):*
<details><summary><i>Previously, ykuijs (Yorick Kuijs) wrote…</i></summary><blockquote>

Please follow the coding styleguide, which specifies that the curly brace should be on the next line
</blockquote></details>

Done.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPWeb/MSFT_SPWeb.psm1, line 169 at r3](https://reviewable.io:443/reviews/powershell/sharepointdsc/667#-KxqYZpPNjF52Ib-fD3h:-KxqkZT3k_e1xUa_FSrc:b-896fix) ([raw file](https://github.com/powershell/sharepointdsc/blob/8627d4c337ccafbf2b4dd627aedb48e3b35f76ed/Modules/SharePointDsc/DSCResources/MSFT_SPWeb/MSFT_SPWeb.psm1#L169)):*
<details><summary><i>Previously, ykuijs (Yorick Kuijs) wrote…</i></summary><blockquote>

Please follow the coding styleguide, which specifies that the curly brace should be on the next line
</blockquote></details>

Done.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPWeb/MSFT_SPWeb.psm1, line 184 at r3](https://reviewable.io:443/reviews/powershell/sharepointdsc/667#-KxqYa2LAQnxPEuTkoX4:-Kxqk_OdpxZbtxmacKRv:b-896fix) ([raw file](https://github.com/powershell/sharepointdsc/blob/8627d4c337ccafbf2b4dd627aedb48e3b35f76ed/Modules/SharePointDsc/DSCResources/MSFT_SPWeb/MSFT_SPWeb.psm1#L184)):*
<details><summary><i>Previously, ykuijs (Yorick Kuijs) wrote…</i></summary><blockquote>

Please follow the coding styleguide, which specifies that the curly brace should be on the next line
</blockquote></details>

Done.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPWeb/MSFT_SPWeb.psm1, line 190 at r3](https://reviewable.io:443/reviews/powershell/sharepointdsc/667#-KxqYb5TFc-2KMIWxl86:-Kxqka8MomQB9BfbcJM5:b-896fix) ([raw file](https://github.com/powershell/sharepointdsc/blob/8627d4c337ccafbf2b4dd627aedb48e3b35f76ed/Modules/SharePointDsc/DSCResources/MSFT_SPWeb/MSFT_SPWeb.psm1#L190)):*
<details><summary><i>Previously, ykuijs (Yorick Kuijs) wrote…</i></summary><blockquote>

Please follow the coding styleguide, which specifies that the curly brace should be on the next line
</blockquote></details>

Done.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPWeb/MSFT_SPWeb.psm1, line 196 at r3](https://reviewable.io:443/reviews/powershell/sharepointdsc/667#-KxqYcUq6avipT1Z2e5H:-KxqkbJwCKlqMtpa4CwN:b-896fix) ([raw file](https://github.com/powershell/sharepointdsc/blob/8627d4c337ccafbf2b4dd627aedb48e3b35f76ed/Modules/SharePointDsc/DSCResources/MSFT_SPWeb/MSFT_SPWeb.psm1#L196)):*
<details><summary><i>Previously, ykuijs (Yorick Kuijs) wrote…</i></summary><blockquote>

Please follow the coding styleguide, which specifies that the curly brace should be on the next line
</blockquote></details>

Done.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPWeb/MSFT_SPWeb.psm1, line 202 at r3](https://reviewable.io:443/reviews/powershell/sharepointdsc/667#-KxqYfsJldRX0-NdhkTD:-Kxqkda9PyiG944KGJS4:b-896fix) ([raw file](https://github.com/powershell/sharepointdsc/blob/8627d4c337ccafbf2b4dd627aedb48e3b35f76ed/Modules/SharePointDsc/DSCResources/MSFT_SPWeb/MSFT_SPWeb.psm1#L202)):*
<details><summary><i>Previously, ykuijs (Yorick Kuijs) wrote…</i></summary><blockquote>

Please follow the coding styleguide, which specifies that the curly brace should be on the next line
</blockquote></details>

Done.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPWeb/MSFT_SPWeb.psm1, line 207 at r3](https://reviewable.io:443/reviews/powershell/sharepointdsc/667#-KxqYgtHN7L0qFTiTDPd:-KxqkeEh1qr5DYXX5kx4:b-896fix) ([raw file](https://github.com/powershell/sharepointdsc/blob/8627d4c337ccafbf2b4dd627aedb48e3b35f76ed/Modules/SharePointDsc/DSCResources/MSFT_SPWeb/MSFT_SPWeb.psm1#L207)):*
<details><summary><i>Previously, ykuijs (Yorick Kuijs) wrote…</i></summary><blockquote>

Please follow the coding styleguide, which specifies that the curly brace should be on the next line
</blockquote></details>

Done.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPWeb/MSFT_SPWeb.psm1, line 208 at r3](https://reviewable.io:443/reviews/powershell/sharepointdsc/667#-KxqYne-M3vwh6Nkrlu9:-KxqkekmftilhueiHmf4:b-896fix) ([raw file](https://github.com/powershell/sharepointdsc/blob/8627d4c337ccafbf2b4dd627aedb48e3b35f76ed/Modules/SharePointDsc/DSCResources/MSFT_SPWeb/MSFT_SPWeb.psm1#L208)):*
<details><summary><i>Previously, ykuijs (Yorick Kuijs) wrote…</i></summary><blockquote>

Please follow the coding styleguide, which specifies that the curly brace should be on the next line
</blockquote></details>

Done.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPWeb/MSFT_SPWeb.psm1, line 209 at r3](https://reviewable.io:443/reviews/powershell/sharepointdsc/667#-KxqYou-Kl9XY9F156L7:-KxqkfRE3I_fIu7D7FX_:b-896fix) ([raw file](https://github.com/powershell/sharepointdsc/blob/8627d4c337ccafbf2b4dd627aedb48e3b35f76ed/Modules/SharePointDsc/DSCResources/MSFT_SPWeb/MSFT_SPWeb.psm1#L209)):*
<details><summary><i>Previously, ykuijs (Yorick Kuijs) wrote…</i></summary><blockquote>

Please follow the coding styleguide, which specifies that the curly brace should be on the next line
</blockquote></details>

Done.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPWeb/MSFT_SPWeb.psm1, line 216 at r3](https://reviewable.io:443/reviews/powershell/sharepointdsc/667#-KxqYzYkrnunCtZZlIY9:-KxqkgU8Og9V6w0z9DDV:b-896fix) ([raw file](https://github.com/powershell/sharepointdsc/blob/8627d4c337ccafbf2b4dd627aedb48e3b35f76ed/Modules/SharePointDsc/DSCResources/MSFT_SPWeb/MSFT_SPWeb.psm1#L216)):*
<details><summary><i>Previously, ykuijs (Yorick Kuijs) wrote…</i></summary><blockquote>

Please follow the coding styleguide, which specifies that the curly brace should be on the next line
</blockquote></details>

Done.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPWeb/MSFT_SPWeb.psm1, line 221 at r3](https://reviewable.io:443/reviews/powershell/sharepointdsc/667#-KxqZ4XpR47HkfaSqaoP:-Kxqkgz_vPKnxVsd3ScE:b-896fix) ([raw file](https://github.com/powershell/sharepointdsc/blob/8627d4c337ccafbf2b4dd627aedb48e3b35f76ed/Modules/SharePointDsc/DSCResources/MSFT_SPWeb/MSFT_SPWeb.psm1#L221)):*
<details><summary><i>Previously, ykuijs (Yorick Kuijs) wrote…</i></summary><blockquote>

Please follow the coding styleguide, which specifies that the curly brace should be on the next line
</blockquote></details>

Done.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPWeb/MSFT_SPWeb.psm1, line 229 at r3](https://reviewable.io:443/reviews/powershell/sharepointdsc/667#-KxqZ5pnU8QDz-G81dNH:-KxqkiDEy9LmLERxKlC_:b-896fix) ([raw file](https://github.com/powershell/sharepointdsc/blob/8627d4c337ccafbf2b4dd627aedb48e3b35f76ed/Modules/SharePointDsc/DSCResources/MSFT_SPWeb/MSFT_SPWeb.psm1#L229)):*
<details><summary><i>Previously, ykuijs (Yorick Kuijs) wrote…</i></summary><blockquote>

Please follow the coding styleguide, which specifies that the curly brace should be on the next line
</blockquote></details>

Done.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPWeb/MSFT_SPWeb.psm1, line 275 at r3](https://reviewable.io:443/reviews/powershell/sharepointdsc/667#-KxqZCHMdFP6J8VbtvPI:-KxqkkSFytidwwET-0IQ:b-896fix) ([raw file](https://github.com/powershell/sharepointdsc/blob/8627d4c337ccafbf2b4dd627aedb48e3b35f76ed/Modules/SharePointDsc/DSCResources/MSFT_SPWeb/MSFT_SPWeb.psm1#L275)):*
<details><summary><i>Previously, ykuijs (Yorick Kuijs) wrote…</i></summary><blockquote>

Please remove the "Mandatory = $false" bit, which is a Best Practice from the PSScriptAnalyzer (the rest of the parameters will be corrected in PR660)
</blockquote></details>

Done.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPWeb/MSFT_SPWeb.psm1, line 297 at r3](https://reviewable.io:443/reviews/powershell/sharepointdsc/667#-KxqZ86i3fp5LNeeUOyG:-KxqklDsxYRjPUFuW9yS:b-896fix) ([raw file](https://github.com/powershell/sharepointdsc/blob/8627d4c337ccafbf2b4dd627aedb48e3b35f76ed/Modules/SharePointDsc/DSCResources/MSFT_SPWeb/MSFT_SPWeb.psm1#L297)):*
<details><summary><i>Previously, ykuijs (Yorick Kuijs) wrote…</i></summary><blockquote>

Please follow the coding styleguide, which specifies that the curly brace should be on the next line
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/667)*

**Comment by andikrueger** [comment]
Fixed the coding style.

---

Review status: 5 of 6 files reviewed at latest revision, 18 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/667#-:-Kxr1l8PyTWxwLMfke7z:bu6t2k3)*

**Comment by ykuijs** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/667#-:-Kxt4jfMJEnyNqmZZ4zL:bnfp4nl)*

**Pull request merged**
