### PR TITLE
Add SPAccessServices2010 Resource

### PR DESCRIPTION
**Pull request by mrpullen**
[Replace this with a description of your pull request]
Added Resource to provision SharePoint Access Services 2010 Service Application.
Initial check-in does not configure settings.
#281 

- [x] Change details added to Unreleased section of changelog.md?
- [x] Added/updated documentation and descriptions in .schema.mof files where appropriate?
- [x] Examples updated for both the single server and small farm templates in the examples folder?
- [x] New/changed code adheres to [Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md)?
- [x] [Unit and Integration tests](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md) created/updated where possible?

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/sharepointdsc/522)

### CODE REVIEW

**Comment by mrpullen** [comment]
Ok.. that's the last time I try to edit a file through the edit inline window in github..

**Comment by ykuijs** [comment]
Looks good overall, just a few minor remarks.

---

Reviewed 1 of 6 files at r1, 1 of 4 files at r2, 2 of 4 files at r4.
Review status: 4 of 6 files reviewed at latest revision, 7 unresolved discussions.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPAccessServices2010/MSFT_SPAccessServices2010.psm1, line 21 at r4](https://reviewable.io:443/reviews/powershell/sharepointdsc/522#-KehjIcMH1VzFeHFZkCf:-KehjIcMH1VzFeHFZkCg:bhvmc3v) ([raw file](https://github.com/powershell/sharepointdsc/blob/b25a69c65ecd5ab09056e480b240c7c1a014619a/Modules/SharePointDsc/DSCResources/MSFT_SPAccessServices2010/MSFT_SPAccessServices2010.psm1#L21)):*
> ```PowerShell
>         [System.Management.Automation.PSCredential]
>         $InstallAccount
> ```

Remove this blank line

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPAccessServices2010/MSFT_SPAccessServices2010.psm1, line 61 at r4](https://reviewable.io:443/reviews/powershell/sharepointdsc/522#-KehjOgQcosX_QD7Twt5:-KehjOgQcosX_QD7Twt6:ba168bj) ([raw file](https://github.com/powershell/sharepointdsc/blob/b25a69c65ecd5ab09056e480b240c7c1a014619a/Modules/SharePointDsc/DSCResources/MSFT_SPAccessServices2010/MSFT_SPAccessServices2010.psm1#L61)):*
> ```PowerShell
>             }
>         }
> ```

Remove these blank lines

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPAccessServices2010/MSFT_SPAccessServices2010.psm1, line 105 at r4](https://reviewable.io:443/reviews/powershell/sharepointdsc/522#-KehjZe5URIvAanYnrAf:-KehjZe5URIvAanYnrAg:ba168bj) ([raw file](https://github.com/powershell/sharepointdsc/blob/b25a69c65ecd5ab09056e480b240c7c1a014619a/Modules/SharePointDsc/DSCResources/MSFT_SPAccessServices2010/MSFT_SPAccessServices2010.psm1#L105)):*
> ```PowerShell
>             $accessApp = New-SPAccessServiceApplication -Name $params.Name `
>                                                         -ApplicationPool $params.ApplicationPool
>     
> ```

Remove these blank lines

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPAccessServices2010/MSFT_SPAccessServices2010.psm1, line 111 at r4](https://reviewable.io:443/reviews/powershell/sharepointdsc/522#-KehjvECygl7XbCx_i6I:-KehjvECygl7XbCx_i6J:b-jnjq8k) ([raw file](https://github.com/powershell/sharepointdsc/blob/b25a69c65ecd5ab09056e480b240c7c1a014619a/Modules/SharePointDsc/DSCResources/MSFT_SPAccessServices2010/MSFT_SPAccessServices2010.psm1#L111)):*
> ```PowerShell
>     if($result.Ensure -eq "Present" -and $Ensure -eq "Present") 
>     {
>         Write-Verbose "Recreating Access 2010 service application '$Name'"
> ```

Is recreating the service application the only way? Can't we just change the application pool?

What would be the impact of recreating the service application for end users?

---

*[Tests/Unit/SharePointDsc/SharePointDsc.SPAccessServices2010.Tests.ps1, line 30 at r4](https://reviewable.io:443/reviews/powershell/sharepointdsc/522#-KehkMDEbRIhbmWWPrKx:-KehkMDEbRIhbmWWPrKy:bdwzg3i) ([raw file](https://github.com/powershell/sharepointdsc/blob/b25a69c65ecd5ab09056e480b240c7c1a014619a/Tests/Unit/SharePointDsc/SharePointDsc.SPAccessServices2010.Tests.ps1#L30)):*
> ```PowerShell
>         Mock -CommandName Remove-SPServiceApplication -MockWith { }
> 
>         
> ```

Remove blank line, only one line needed

---

*[Tests/Unit/SharePointDsc/SharePointDsc.SPAccessServices2010.Tests.ps1, line 32 at r4](https://reviewable.io:443/reviews/powershell/sharepointdsc/522#-KehkR3Ckkg4NY_heii5:-KehkR3Ckkg4NY_heii6:bco1vgc) ([raw file](https://github.com/powershell/sharepointdsc/blob/b25a69c65ecd5ab09056e480b240c7c1a014619a/Tests/Unit/SharePointDsc/SharePointDsc.SPAccessServices2010.Tests.ps1#L32)):*
> ```PowerShell
>         
>         # Test contexts
>     
> ```

Remove blank lines

---

*[Tests/Unit/SharePointDsc/SharePointDsc.SPAccessServices2010.Tests.ps1, line 77 at r4](https://reviewable.io:443/reviews/powershell/sharepointdsc/522#-Kehk_m5LMxisWqTpKJG:-Kehk_m61pi38VGHC6by:be7uzdo) ([raw file](https://github.com/powershell/sharepointdsc/blob/b25a69c65ecd5ab09056e480b240c7c1a014619a/Tests/Unit/SharePointDsc/SharePointDsc.SPAccessServices2010.Tests.ps1#L77)):*
> ```PowerShell
>             It "Should call (New-SPAccessServiceApplication) on Set-TargetResource" {
>                 Set-TargetResource @testParams
>                 Assert-MockCalled New-SPAccessServiceApplication -Times 1
> ```

You can combine the Assert-MockCalled in one block, so:
Set-TargetResource @testParams
Assert-MockCalled Get-SPServiceApplication
Assert-MockCalled New-SPAccessServiceApplication -Times 1
Assert-MockCalled Remove-SPServiceApplication -Times 0

Like you do in the test below

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/522#-:-Kehl5Nn7UlfT60aaady:b-kjwpla)*

**Comment by BrianFarnhill** [comment]
Reviewed 1 of 6 files at r1, 1 of 4 files at r2, 4 of 4 files at r4.
Review status: 2 of 6 files reviewed at latest revision, 8 unresolved discussions.

---

*[CHANGELOG.md, line 3 at r4](https://reviewable.io:443/reviews/powershell/sharepointdsc/522#-KekUZPdkNAxjWbL56VN:-KekUZPdkNAxjWbL56VO:b-18ztdp) ([raw file](https://github.com/powershell/sharepointdsc/blob/b25a69c65ecd5ab09056e480b240c7c1a014619a/CHANGELOG.md#L3)):*
> ```Markdown
> # Change log for SharePointDsc
> 
> ## Unreleased
> ```

We need to move this to a new unreleased heading, 1.6 has been released now. If you do a pull from dev you should see the latest updated 

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPAccessServices2010/MSFT_SPAccessServices2010.psm1, line 111 at r4](https://reviewable.io:443/reviews/powershell/sharepointdsc/522#-KehjvECygl7XbCx_i6I:-KekbcJN6sjG361N-anf:b-jz7p1u) ([raw file](https://github.com/powershell/sharepointdsc/blob/b25a69c65ecd5ab09056e480b240c7c1a014619a/Modules/SharePointDsc/DSCResources/MSFT_SPAccessServices2010/MSFT_SPAccessServices2010.psm1#L111)):*
<details><summary><i>Previously, ykuijs (Yorick Kuijs) wrote…</i></summary><blockquote>

Is recreating the service application the only way? Can't we just change the application pool?

What would be the impact of recreating the service application for end users?
</blockquote></details>

Yea I'm 100% not comfortable with this - if the admin has changed any other settings in the service app then they will be lost in this scenario. So we either need to a) add every option that can be configured in the service app to this resource, or b) document that we don't support changing the service app, that we just do that when provisioning. For the sake of getting something shipped sooner rather than later I say we take option b) and then add an issue to our backlog to come back and do the extra properties later.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/522)*

**Comment by BrianFarnhill** [comment]
Reviewed 4 of 4 files at r5.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPAccessServices2010/MSFT_SPAccessServices2010.psm1, line 21 at r4](https://reviewable.io:443/reviews/powershell/sharepointdsc/522#-KehjIcMH1VzFeHFZkCf:-KfAG2UIanCsfKlQmsTX:b-kj6nbo) ([raw file](https://github.com/powershell/sharepointdsc/blob/b25a69c65ecd5ab09056e480b240c7c1a014619a/Modules/SharePointDsc/DSCResources/MSFT_SPAccessServices2010/MSFT_SPAccessServices2010.psm1#L21)):*
<details><summary><i>Previously, ykuijs (Yorick Kuijs) wrote…</i></summary><blockquote>

Remove this blank line
</blockquote></details>

We only needed the blank line beneath install account removed, not all the blank lines in the resource. Sorry if that wasn't clear.  We need one blank line between the parameters, and individual lines between code in the functions are fine as long as they make thing more readable. Does that make sense?

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPAccessServices2010/MSFT_SPAccessServices2010.psm1, line 111 at r4](https://reviewable.io:443/reviews/powershell/sharepointdsc/522#-KehjvECygl7XbCx_i6I:-KfAGbcSYJWGNfZZUNdM:bqxikf5) ([raw file](https://github.com/powershell/sharepointdsc/blob/b25a69c65ecd5ab09056e480b240c7c1a014619a/Modules/SharePointDsc/DSCResources/MSFT_SPAccessServices2010/MSFT_SPAccessServices2010.psm1#L111)):*
<details><summary><i>Previously, BrianFarnhill (Brian Farnhill) wrote…</i></summary><blockquote>

Yea I'm 100% not comfortable with this - if the admin has changed any other settings in the service app then they will be lost in this scenario. So we either need to a) add every option that can be configured in the service app to this resource, or b) document that we don't support changing the service app, that we just do that when provisioning. For the sake of getting something shipped sooner rather than later I say we take option b) and then add an issue to our backlog to come back and do the extra properties later.
</blockquote></details>

Much happier with the new approach to update the app pool, can we update the Write-Verbose statement here so that it doesn't say "Recreating" now?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/522)*

**Comment by BrianFarnhill** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/522#-:-KfcjkF78QYspIV7MCdj:bnfp4nl)*

**Pull request merged**
