### PR TITLE
Fixes Visio SA issue

### PR DESCRIPTION
**Pull request by NikCharlebois**
Fixes issue #772 

- [x] Change details added to Unreleased section of changelog.md?
- [x] Added/updated documentation and descriptions in .schema.mof files where appropriate?
- [x] Examples updated for both the single server and small farm templates in the examples folder?
- [x] New/changed code adheres to [Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md)?
- [x] [Unit and Integration tests](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md) created/updated where possible?

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/sharepointdsc/773)

### CODE REVIEW

**Comment by ykuijs** [comment]
@NikCharlebois, can you please check the tests. It looks like non of the existing tests are hitting you change, resulting in a 0% code coverage for your change

**Comment by NikCharlebois** [comment]
@ykuijs looks to me like an AppVeyor glitch. I will make a meaningless change and will trigger the build process again to see. Cheers

**Comment by ykuijs** [comment]
Never mind the failed CodeCov test. If you remove the item in the Changelog, I will merge the PR

---

Reviewed 1 of 2 files at r1.
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[CHANGELOG.md, line 6 at r2](https://reviewable.io:443/reviews/powershell/sharepointdsc/773#-L6OHVx1KHV1ZoWhfLDJ:-L6OHVx1KHV1ZoWhfLDK:b-9dkhw2) ([raw file](https://github.com/powershell/sharepointdsc/blob/e195f9bde98c4f72401a3f791f4f17d37af12eaf/CHANGELOG.md#L6)):*
> ```Markdown
> 
> * SPDistributedCacheClientSettings
>   * Added the new resource
> ```

Why is this in the changelog? This is for your other PR.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/773#-:-L6OHacFkt7cE9wufD-2:byhm0fm)*

**Comment by NikCharlebois** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[CHANGELOG.md, line 6 at r2](https://reviewable.io:443/reviews/powershell/sharepointdsc/773#-L6OHVx1KHV1ZoWhfLDJ:-L6cTRY6seQtssjxO4-v:b-jofeqd) ([raw file](https://github.com/powershell/sharepointdsc/blob/e195f9bde98c4f72401a3f791f4f17d37af12eaf/CHANGELOG.md#L6)):*
<details><summary><i>Previously, ykuijs (Yorick Kuijs) wrote…</i></summary><blockquote>

Why is this in the changelog? This is for your other PR.
</blockquote></details>

I branched from a branch.....my bad

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/773)*

**Comment by ykuijs** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/773#-:-L6p69NDRDGH97a_ZlWi:bnfp4nl)*

**Pull request merged**
