### PR TITLE
Update v3.0-development with updates from dev branch

### PR DESCRIPTION
**Pull request by ykuijs**
#### Pull Request (PR) description
Update the  v3.0-development branch with updates from the dev branch

#### This Pull Request (PR) fixes the following issues
N/A

#### Task list
- [X] Added an entry under the Unreleased section of the change log in the CHANGELOG.md.
      Entry should say what was changed, and how that affects users (if applicable).
- [X] Resource documentation added/updated in README.md in the resource folder.
- [X] Resource parameter descriptions added/updated in schema.mof
      and comment-based help.
- [X] Comment-based help added/updated.
- [X] Localization strings added/updated in all localization files as appropriate.
- [X] Examples appropriately added/updated.
- [X] Unit tests added/updated. See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [X] Integration tests added/updated (where possible). See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [X] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/sharepointdsc/944)

### CODE REVIEW

**Comment by ykuijs** [comment]
@NikCharlebois Can you review?

**Comment by NikCharlebois** [comment]
@ykuijs  will do first thing in the morning.

**Comment by ykuijs** [comment]
@NikCharlebois Can you please do a last review? I can merge this PR afterwards

**Comment by NikCharlebois** [comment]
@ykuijs Done. Last thing remaining is that potential check to throw an error if a multi-tenancy site is being created in 2019.

**Comment by ykuijs** [comment]
@NikCharlebois Lets change the MT issue as a separate PR, so we can merge this PR and continue with the other PRs as well.

**Pull request merged**
