### PR TITLE
Add SPWebAppPeoplePickerSettingsSearchADDomains

### PR DESCRIPTION
**Pull request by luigilink**
Adding SPWebAppPeoplePickerSettingsSearchADDomains Resource

- [x] Change details added to Unreleased section of changelog.md?
- [x] Added/updated documentation and descriptions in .schema.mof files where appropriate?
- [x] Examples updated for both the single server and small farm templates in the examples folder?
- [x] New/changed code adheres to [Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md)?
- [x] [Unit and Integration tests](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md) created/updated where possible?

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/sharepointdsc/555)

### CODE REVIEW

**Comment by luigilink** [comment]
New resource in progress, I'll try to add examples and pester tomorrow.

**Comment by ykuijs** [comment]
@luigilink, any update?

Also make sure you test this resource on an actual environment.....while taking a quick glance on your code, I think it will never work: One of the parameters is $Url, but you are using $WebApplicationUrl in your code.......

**Comment by ykuijs** [comment]
@luigilink, any update?

**Comment by BrianFarnhill** [comment]
@ykuijs I don't want to lose this code but I do think we need to close this PR off for inactivity. We should pull his branch in to one of our forks so we can finish it and get it over the line if we can.

**Comment by luigilink** [comment]
I fixed the wrong variable and add example file.
I'll try tomorrow to add the pester file.

**Comment by ykuijs** [comment]
Just wondering: Should we use the sub class to specify multiple domains in one resource, just like we do with the permissions in SPWebPolicyPermissions?

With the current way, your config requires two of these resources specified if you would like to add two domains. With the sub class, you can combine these into one resource.

Another thing: Isn't is required to specify a password with the login name?

---

Reviewed 3 of 4 files at r1, 1 of 2 files at r3.
Review status: 4 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPWebAppPeoplePickerSettingsSearchADDomains/MSFT_SPWebAppPeoplePickerSettingsSearchADDomains.psm1, line 193 at r4](https://reviewable.io:443/reviews/powershell/sharepointdsc/555#-KmCDO_ZB4IEsMdF9Ymr:-KmCDO__sCGlipCdPCKs:b-fltkcn) ([raw file](https://github.com/powershell/sharepointdsc/blob/24fa31d0fae57ff249a8ee92f3a55ec791927ac0/Modules/SharePointDsc/DSCResources/MSFT_SPWebAppPeoplePickerSettingsSearchADDomains/MSFT_SPWebAppPeoplePickerSettingsSearchADDomains.psm1#L193)):*
> ```PowerShell
>     return Test-SPDscParameterState -CurrentValues $CurrentValues `
>                                     -DesiredValues $PSBoundParameters `
>                                     -ValuesToCheck @('Ensure', 'DomainName')
> ```

What is the reason that you don't check for the possibility for a different login name?

---

*[Tests/Unit/SharePointDsc/SharePointDsc.SPWebAppPeoplePickerSettingsSearchADDomains.Tests.ps1, line 89 at r4](https://reviewable.io:443/reviews/powershell/sharepointdsc/555#-KmCEPcTGVrA5BrV-M7g:-KmCEPcTGVrA5BrV-M7h:b-ydsna7) ([raw file](https://github.com/powershell/sharepointdsc/blob/24fa31d0fae57ff249a8ee92f3a55ec791927ac0/Tests/Unit/SharePointDsc/SharePointDsc.SPWebAppPeoplePickerSettingsSearchADDomains.Tests.ps1#L89)):*
> ```PowerShell
>         }
> 
>         Context -Name "The SPPeoplePickerSearchActiveDirectoryDomain doesn't exist but shouldn't" -Fixture {
> ```

I think the name of the test is incorrect

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/555#-:-KmCFFMaxEzPVHVoWIWF:bp4ue3y)*

**Comment by luigilink** [comment]
If you want to add two or more domains If prefer this approach:
SearchActiveDirectoryDomains = @("contoso.com","mydomain.local","mytrusted.ext")
foreach($adDomain in $SearchActiveDirectoryDomains)
{
	$domainShortName = $adDomain.Split('.')[0];
	xSPSearchActiveDirectoryDomains "APPLICATION_SearchADDomain_$domainShortName" 
	{
		DependsOn = "[SPWebApplication]APPLICATION_SpsWApp$($Node.NodeName)"
		PsDscRunAsCredential = $SetupFarm
		WebApplicationURL = "https://$($Node.NodeName)"
		DomainName = "$adDomain"
		Ensure = "Present"
	}
}

Only LoginName is required see here: https://msdn.microsoft.com/en-us/library/microsoft.sharepoint.administration.sppeoplepickersearchactivedirectorydomain_members(v=office.15).aspx

---

Review status: 4 of 6 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/555#-:-KmVX0UEqn8npujrCsyf:bxbl7qt)*

**Comment by ykuijs** [comment]
The issue with your suggested way is that you cannot enforce a certain list (see SPFarmAdministrators as example). I can go in and add fabrikam.com as a new domain. The only way to remove this is to add a new resource for that domain with Ensure=Absent. There is no way of saying, these are the domains I want and remove the rest.

---

Review status: 4 of 6 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/555#-:-Kmko-1E4P7JgutLaxkr:b-jnr8tc)*

**Comment by DarenDaigle** [comment]
I also noticed that one thing a subclass approach would provide is granular control over credentials per domain and whether they are forest or domain entries.

**Comment by ykuijs** [comment]
I have created a new resource for configuring the PeoplePickerSettings and use the information from this PR. It will be included in my next PR. Closing this PR.

**Pull request closed without merging**
