### PR TITLE
Release 1.1

### PR DESCRIPTION
**Pull request by BrianFarnhill**
Release branch for version 1.1

@kwirkykat This is all ready to ship. If you could merge this PR in to master and then drop the build in the PowerShell gallery that would be awesome :) Let me know if you need anything from me on this one.

/cc @KarolKaczmarek

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/sharepointdsc/347)

### CODE REVIEW

**Comment by kwirkykat** [comment]
@BrianFarnhill I would like to wait to release this with the rest of the Resource Kit on Wednesday. That alright with you?

**Comment by BrianFarnhill** [comment]
@kwirkykat Totally fine - I just try to make sure I have these PR's that merge to master ready for when you do that so you can do it at the same time each month, so definitely happy to wait to be included in that same run :)

**Comment by kwirkykat** [comment]
@BrianFarnhill Thanks :)

**Comment by kwirkykat** [comment]
@BrianFarnhill Would you like release branches left open or deleted after they are merged?

**Comment by BrianFarnhill** [comment]
@kwirkykat Deleted, but I can clean those up. Thanks Katie!

**Pull request merged**
