### PR TITLE
Removed Win32_Product from SPInstall

### PR DESCRIPTION
**Pull request by BrianFarnhill**
Quick fix to something that should have happened in 1.1 when we removed Win32_Product from SPInstallPrereqs. I also made style changes to bring SPInstall in line as well. 

- [X] Change details added to Unreleased section of changelog.md?
- [n/a] Added/updated documentation and descriptions in .schema.mof files where appropriate?
- [n/a] Examples updated for both the single server and small farm templates in the examples folder?
- [X] New/changed code adheres to [Style Guidelines]?(https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md)?
- [X] [Unit and Integration tests](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md) created/updated where possible?

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/sharepointdsc/367)

### CODE REVIEW

**Comment by ykuijs** [comment]
Looks perfect

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/367#-:-KMVZg8DYxm1gWxRJueO:-669736804)*

**Comment by ykuijs** [comment]
It just needs an update from Dev.

**Comment by BrianFarnhill** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/367)*

**Comment by BrianFarnhill** [comment]
Reviewed 2 of 3 files at r1, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/367)*

**Pull request merged**
