### PR TITLE
Merge of SP2019 Public Preview changes into v3.0 branch

### PR DESCRIPTION
**Pull request by ykuijs**
This PR merges all private changes into the public SharePointDsc repo. This will add support for the SharePoint 2019 Public Preview build.

@NikCharlebois To you the honors of reviewing this PR ;-)

- [X] Change details added to Unreleased section of changelog.md?
- [X] Added/updated documentation and descriptions in .schema.mof files where appropriate?
- [X] Examples updated for both the single server and small farm templates in the examples folder?
- [X] New/changed code adheres to [Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md)?
- [X] [Unit and Integration tests](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md) created/updated where possible?

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/sharepointdsc/847)

### CODE REVIEW

**Comment by ykuijs** [comment]
AppVeyor not starting closing and reopening issue

**Comment by johlju** [comment]
@ykuijs There are tests failing

https://ci.appveyor.com/project/PowerShell/sharepointdsc/build/2.4.0.1390?fullLog=true#L13168
https://ci.appveyor.com/project/PowerShell/sharepointdsc/build/2.4.0.1390?fullLog=true#L16654

**Comment by johlju** [comment]
@ykuijs and now they are passing. 😃 Ready for @NikCharlebois to review, if have time. 🙂

**Comment by NikCharlebois** [comment]
Yep, on it

**Comment by NikCharlebois** [comment]
@ykuijs all yours to review mate

**Pull request merged**
