### PR TITLE
Added feature pack 1 support

### LINKED ISSUE #450: Small Farm Role Support
When will SharePointDSC be updated to support the new small farm roles available with SharePoint 2016 Feature Pack 1?

### PR DESCRIPTION
**Pull request by BrianFarnhill**
Fixes #450 

- [X] Change details added to Unreleased section of changelog.md?
- [X] Added/updated documentation and descriptions in .schema.mof files where appropriate?
- [X] Examples updated for both the single server and small farm templates in the examples folder?
- [X] New/changed code adheres to [Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md)?
- [X] [Unit and Integration tests](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md) created/updated where possible?

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/sharepointdsc/451)

### CODE REVIEW

**Comment by ykuijs** [comment]
@BrianFarnhill Two tests still fail, can you please check these. I will review afterwards.

**Comment by BrianFarnhill** [comment]
@ykuijs Forgot to update the stubs, will get that sorted this morning then go again

**Comment by ykuijs** [comment]
@BrianFarnhill you are going the wrong way dude......from now six tests are failing :-)

**Comment by BrianFarnhill** [comment]
@ykuijs I kept getting distracted and didn't get to finish this! The latest change I just made should have fixed the stubs, so it should finally be ready for a review. Thanks mate!

**Comment by BrianFarnhill** [comment]
@ykuijs Urgh - there is still a fail, but it looks like it's to do with the trusted token issuer. Let me look in to it as I want to make sure that feature pack 1 doesn't break one of our other resources, but if you could review the rest of what's here that would be great.

**Comment by BrianFarnhill** [comment]
@ykuijs OK found the issue with the stub generator and manually fixed it up, should finally be good to go here.

**Comment by ykuijs** [comment]
:lgtm:

Just one question: Many changes in the Powershell.psm1 file are changes to the order of the parameters. Did you do this on purpose?

---

Reviewed 6 of 7 files at r1, 2 of 3 files at r3, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/451#-:-KWbU-x0we-tYDnMWkmS:bgwjtnn)*

**Comment by BrianFarnhill** [comment]
That file is autogenerated for the most part, I just ran the same script (which is stored in the test helper file) to generate it, so nothing I changed was on purpose in that regard, its just how the updated version of SP saw the parameters.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/451#-:-KWdnyAjREkL7YKdE84L:bwc9cgz)*

**Pull request merged**
