### PR TITLE
Distributed cache client settings

### PR DESCRIPTION
**Pull request by NikCharlebois**
Added a new SPDistributedCacheClientsettings resource. Issue #505 

- [x] Change details added to Unreleased section of changelog.md?
- [x] Added/updated documentation and descriptions in .schema.mof files where appropriate?
- [x] Examples updated for both the single server and small farm templates in the examples folder?
- [x] New/changed code adheres to [Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md)?
- [x] [Unit and Integration tests](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md) created/updated where possible?

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/sharepointdsc/769)

### CODE REVIEW

**Comment by ykuijs** [comment]
Shouldn't we be using default values, as specified in: https://technet.microsoft.com/en-us/library/jj219613.aspx#Fine-tune the Distributed Cache service by using a Windows PowerShell script

---

Reviewed 2 of 7 files at r2.
Review status: 2 of 7 files reviewed at latest revision, 5 unresolved discussions.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPDistributedCacheClientSettings/MSFT_SPDistributedCacheClientSettings.psm1, line 693 at r2](https://reviewable.io:443/reviews/powershell/sharepointdsc/769#-L6OFaLWodzO21pYcQQ0:-L6OFaLWodzO21pYcQQ1:b-2trwsr) ([raw file](https://github.com/powershell/sharepointdsc/blob/ba2fdd711ff40f086d623d3500f2626b259eedc1/Modules/SharePointDsc/DSCResources/MSFT_SPDistributedCacheClientSettings/MSFT_SPDistributedCacheClientSettings.psm1#L693)):*
> ```PowerShell
>     return Test-SPDscParameterState -CurrentValues $CurrentValues `
>                                     -DesiredValues $PSBoundParameters `
>                                     -ValuesToCheck @("Ensure")
> ```

Why aren't you checking all parameters? If I am not mistaking, this will never update any settings.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPDistributedCacheClientSettings/MSFT_SPDistributedCacheClientSettings.schema.mof, line 4 at r2](https://reviewable.io:443/reviews/powershell/sharepointdsc/769#-L6OFvipKHsWguAVVxar:-L6OFvipKHsWguAVVxas:breo3wo) ([raw file](https://github.com/powershell/sharepointdsc/blob/ba2fdd711ff40f086d623d3500f2626b259eedc1/Modules/SharePointDsc/DSCResources/MSFT_SPDistributedCacheClientSettings/MSFT_SPDistributedCacheClientSettings.schema.mof#L4)):*
> ```
> class MSFT_SPDistributedCacheClientSettings : OMI_BaseResource
> {
>     [Key, Description("Present to initiate the configuration of the settings. Absent is not supported"), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
> ```

You probably used this parameter as key to make sure this resource can only be used once, correct?

---

*[Modules/SharePointDsc/Examples/Resources/SPDistributedCacheClientSettings/1-ConfigureClientSettings.ps1, line 49 at r2](https://reviewable.io:443/reviews/powershell/sharepointdsc/769#-L6OGQQ7n6PB-xNlYObX:-L6OGQQ7n6PB-xNlYObY:b-2esd4d) ([raw file](https://github.com/powershell/sharepointdsc/blob/ba2fdd711ff40f086d623d3500f2626b259eedc1/Modules/SharePointDsc/Examples/Resources/SPDistributedCacheClientSettings/1-ConfigureClientSettings.ps1#L49)):*
> ```PowerShell
>                 DSTACRequestTimeout         = 1000
>                 DSTACChannelOpenTimeOut     = 1000
>                 InstallAccount              = $SetupAccount
> ```

Please use PsDscRunAsCredential in the example

---

*[Tests/Unit/SharePointDsc/SharePointDsc.SPDistributedCacheClientSettings.Tests.ps1, line 87 at r2](https://reviewable.io:443/reviews/powershell/sharepointdsc/769#-L6OGn_5NaI3cwyKqUjP:-L6OGn_6KYsjFbGj1j9q:bqx8rsf) ([raw file](https://github.com/powershell/sharepointdsc/blob/ba2fdd711ff40f086d623d3500f2626b259eedc1/Tests/Unit/SharePointDsc/SharePointDsc.SPDistributedCacheClientSettings.Tests.ps1#L87)):*
> ```PowerShell
> 
>             It "Should successfully test the resource" {
>                 (Test-TargetResource @testParams) | Should Be $true
> ```

This shouldn't be true, since not all values are according to specifications. This has to do with the fact that the Test method just checks for the Ensure parameter.

---

*[Tests/Unit/SharePointDsc/SharePointDsc.SPDistributedCacheClientSettings.Tests.ps1, line 89 at r2](https://reviewable.io:443/reviews/powershell/sharepointdsc/769#-L6OGa2ovBAb2yZQROJG:-L6OGa2ovBAb2yZQROJH:b3kh9ke) ([raw file](https://github.com/powershell/sharepointdsc/blob/ba2fdd711ff40f086d623d3500f2626b259eedc1/Tests/Unit/SharePointDsc/SharePointDsc.SPDistributedCacheClientSettings.Tests.ps1#L89)):*
> ```PowerShell
>                 (Test-TargetResource @testParams) | Should Be $true
>             }
>         }
> ```

Please also add a test where all values are correct.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/769#-:-L6OG8ZX0D1cGQS7mO5d:b-r6bea1)*

**Comment by NikCharlebois** [comment]
I guess so, but that opens the door to a wider discussion I think. What if people want to let people configure certain settings manually as they want, but want DSC to enforce the settings for others. For example, a company could want to make sure that the DLTC settings are enforced, but don't care if people go and change the other ones. If we specify default values in the Set-TargetResource method, then people will loose this flexibility. I will still go ahead and set the default values though

---

Review status: 2 of 7 files reviewed at latest revision, 5 unresolved discussions.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPDistributedCacheClientSettings/MSFT_SPDistributedCacheClientSettings.psm1, line 693 at r2](https://reviewable.io:443/reviews/powershell/sharepointdsc/769#-L6OFaLWodzO21pYcQQ0:-L6cWPKaCKq22gr_8v1m:bf9ub16) ([raw file](https://github.com/powershell/sharepointdsc/blob/ba2fdd711ff40f086d623d3500f2626b259eedc1/Modules/SharePointDsc/DSCResources/MSFT_SPDistributedCacheClientSettings/MSFT_SPDistributedCacheClientSettings.psm1#L693)):*
<details><summary><i>Previously, ykuijs (Yorick Kuijs) wrote…</i></summary><blockquote>

Why aren't you checking all parameters? If I am not mistaking, this will never update any settings.
</blockquote></details>

Checking them all now.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPDistributedCacheClientSettings/MSFT_SPDistributedCacheClientSettings.schema.mof, line 4 at r2](https://reviewable.io:443/reviews/powershell/sharepointdsc/769#-L6OFvipKHsWguAVVxar:-L6cWV4QUo2NiscfLHjA:bpczgvg) ([raw file](https://github.com/powershell/sharepointdsc/blob/ba2fdd711ff40f086d623d3500f2626b259eedc1/Modules/SharePointDsc/DSCResources/MSFT_SPDistributedCacheClientSettings/MSFT_SPDistributedCacheClientSettings.schema.mof#L4)):*
<details><summary><i>Previously, ykuijs (Yorick Kuijs) wrote…</i></summary><blockquote>

You probably used this parameter as key to make sure this resource can only be used once, correct?
</blockquote></details>

Correct. Settings resources can only be used once....even though we don't enforce it.

---

*[Modules/SharePointDsc/Examples/Resources/SPDistributedCacheClientSettings/1-ConfigureClientSettings.ps1, line 49 at r2](https://reviewable.io:443/reviews/powershell/sharepointdsc/769#-L6OGQQ7n6PB-xNlYObX:-L6cWxB27tuqu9-9D4yJ:b-896fix) ([raw file](https://github.com/powershell/sharepointdsc/blob/ba2fdd711ff40f086d623d3500f2626b259eedc1/Modules/SharePointDsc/Examples/Resources/SPDistributedCacheClientSettings/1-ConfigureClientSettings.ps1#L49)):*
<details><summary><i>Previously, ykuijs (Yorick Kuijs) wrote…</i></summary><blockquote>

Please use PsDscRunAsCredential in the example
</blockquote></details>

Done.

---

*[Tests/Unit/SharePointDsc/SharePointDsc.SPDistributedCacheClientSettings.Tests.ps1, line 87 at r2](https://reviewable.io:443/reviews/powershell/sharepointdsc/769#-L6OGn_5NaI3cwyKqUjP:-L6cX-tezfV885AbqXLY:b-896fix) ([raw file](https://github.com/powershell/sharepointdsc/blob/ba2fdd711ff40f086d623d3500f2626b259eedc1/Tests/Unit/SharePointDsc/SharePointDsc.SPDistributedCacheClientSettings.Tests.ps1#L87)):*
<details><summary><i>Previously, ykuijs (Yorick Kuijs) wrote…</i></summary><blockquote>

This shouldn't be true, since not all values are according to specifications. This has to do with the fact that the Test method just checks for the Ensure parameter.
</blockquote></details>

Done.

---

*[Tests/Unit/SharePointDsc/SharePointDsc.SPDistributedCacheClientSettings.Tests.ps1, line 89 at r2](https://reviewable.io:443/reviews/powershell/sharepointdsc/769#-L6OGa2ovBAb2yZQROJG:-L6cY1ASmFq8bxG2bn3F:b-896fix) ([raw file](https://github.com/powershell/sharepointdsc/blob/ba2fdd711ff40f086d623d3500f2626b259eedc1/Tests/Unit/SharePointDsc/SharePointDsc.SPDistributedCacheClientSettings.Tests.ps1#L89)):*
<details><summary><i>Previously, ykuijs (Yorick Kuijs) wrote…</i></summary><blockquote>

Please also add a test where all values are correct.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/769#-:-L6cUOENqTyBTQ7ynXaJ:b-ubwjle)*

**Comment by ykuijs** [comment]
That is a very good point. You are absolutely right. I prefer the flexibility option. But maybe it is a good idea to add the fine tune settings to the Readme file though, just as a reference.

---

Reviewed 1 of 7 files at r1, 2 of 7 files at r2, 2 of 3 files at r3.
Review status: 6 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[Tests/Unit/SharePointDsc/SharePointDsc.SPDistributedCacheClientSettings.Tests.ps1, line 89 at r2](https://reviewable.io:443/reviews/powershell/sharepointdsc/769#-L6OGa2ovBAb2yZQROJG:-L6p8TOaXqfiavbHxLW3:bwgjr71) ([raw file](https://github.com/powershell/sharepointdsc/blob/ba2fdd711ff40f086d623d3500f2626b259eedc1/Tests/Unit/SharePointDsc/SharePointDsc.SPDistributedCacheClientSettings.Tests.ps1#L89)):*
<details><summary><i>Previously, NikCharlebois (Nik Charlebois) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I meant a test that would return True, so all values are configured as specified

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/769#-:-L6p6asmWPOhpc9kgRdw:b-2upfnn)*

**Comment by ykuijs** [comment]
@NikCharlebois Can you please update the Ensure parameter to match the method used in SPManagedMetadataServiceAppDefault, as mentioned in #778?

**Comment by NikCharlebois** [comment]
@ykuijs Can you elaborate as to what you recommend the change to Ensure should be. Not sure I am following based on the comments for unique names in #778 . Thanks

**Comment by ykuijs** [comment]
@NikCharlebois Sure, instead of the Ensure parameter, does the SPManagedMetadataServiceAppDefault resource has a IsSingleInstance parameter, which a ValidateSet of just "Yes"

```
        [Parameter(Mandatory = $true)]
        [ValidateSet('Yes')]
        [String]
        $IsSingleInstance,
```
That is the same method as described in https://docs.microsoft.com/en-us/powershell/dsc/singleinstance to make sure only one instance of a resource can be used.

So it would be great if you can also use that method instead of the Ensure parameter, so we use a consistent method across the entire module.

**Comment by NikCharlebois** [comment]
Done

---

Review status: 3 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[Tests/Unit/SharePointDsc/SharePointDsc.SPDistributedCacheClientSettings.Tests.ps1, line 89 at r2](https://reviewable.io:443/reviews/powershell/sharepointdsc/769#-L6OGa2ovBAb2yZQROJG:-L7ZEnxygCJ-Jw6s_EjZ:b-896fix) ([raw file](https://github.com/powershell/sharepointdsc/blob/ba2fdd711ff40f086d623d3500f2626b259eedc1/Tests/Unit/SharePointDsc/SharePointDsc.SPDistributedCacheClientSettings.Tests.ps1#L89)):*
<details><summary><i>Previously, ykuijs (Yorick Kuijs) wrote…</i></summary><blockquote>

I meant a test that would return True, so all values are configured as specified
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/769#-:-L7ZEkXrYBJ8b_J1GYJF:bb6un1j)*

**Comment by ykuijs** [comment]
Review status: 3 of 7 files reviewed at latest revision, 4 unresolved discussions.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPDistributedCacheClientSettings/MSFT_SPDistributedCacheClientSettings.psm1, line 374 at r4](https://reviewable.io:443/reviews/powershell/sharepointdsc/769#-L7coHbYGxyRNqC7jYZT:-L7coHbZ5-6KsxGZk6Hp:b-l0kgii) ([raw file](https://github.com/powershell/sharepointdsc/blob/21256d1d82ce5b06207339fa2ee1100cbf71d6cd/Modules/SharePointDsc/DSCResources/MSFT_SPDistributedCacheClientSettings/MSFT_SPDistributedCacheClientSettings.psm1#L374)):*
> ```PowerShell
>     Write-Verbose -Message "Setting the Distributed Cache Client Settings"
> 
>     if ($IsSingleInstance -eq "Yes")
> ```

Since $IsSingleInstance can only be Yes, this check isn't necessary.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPDistributedCacheClientSettings/MSFT_SPDistributedCacheClientSettings.psm1, line 543 at r4](https://reviewable.io:443/reviews/powershell/sharepointdsc/769#-L7coPGSnwHTkfEVjwqu:-L7coPGSnwHTkfEVjwqv:b-pff9o9) ([raw file](https://github.com/powershell/sharepointdsc/blob/21256d1d82ce5b06207339fa2ee1100cbf71d6cd/Modules/SharePointDsc/DSCResources/MSFT_SPDistributedCacheClientSettings/MSFT_SPDistributedCacheClientSettings.psm1#L543)):*
> ```PowerShell
>         }
>     }
>     else
> ```

Since $IsSingleInstance can only be Yes, this won't ever happen

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPDistributedCacheClientSettings/MSFT_SPDistributedCacheClientSettings.psm1, line 691 at r4](https://reviewable.io:443/reviews/powershell/sharepointdsc/769#-L7coU1e_7C2SuX8V2Tr:-L7coU1e_7C2SuX8V2Ts:bwnef8q) ([raw file](https://github.com/powershell/sharepointdsc/blob/21256d1d82ce5b06207339fa2ee1100cbf71d6cd/Modules/SharePointDsc/DSCResources/MSFT_SPDistributedCacheClientSettings/MSFT_SPDistributedCacheClientSettings.psm1#L691)):*
> ```PowerShell
>     return Test-SPDscParameterState -CurrentValues $CurrentValues `
>                                     -DesiredValues $PSBoundParameters `
>                                     -ValuesToCheck @("IsSingleInstance",
> ```

You shouldn't have to check IsSingleInstance

---

*[Tests/Unit/SharePointDsc/SharePointDsc.SPDistributedCacheClientSettings.Tests.ps1, line 89 at r2](https://reviewable.io:443/reviews/powershell/sharepointdsc/769#-L6OGa2ovBAb2yZQROJG:-L7cobMOiAzIhDwlXeS0:bbpyv8w) ([raw file](https://github.com/powershell/sharepointdsc/blob/ba2fdd711ff40f086d623d3500f2626b259eedc1/Tests/Unit/SharePointDsc/SharePointDsc.SPDistributedCacheClientSettings.Tests.ps1#L89)):*
<details><summary><i>Previously, NikCharlebois (Nik Charlebois) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

This test still tests for "Should be $false"

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/769)*

**Comment by NikCharlebois** [comment]
Review status: 3 of 7 files reviewed at latest revision, 4 unresolved discussions.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPDistributedCacheClientSettings/MSFT_SPDistributedCacheClientSettings.psm1, line 374 at r4](https://reviewable.io:443/reviews/powershell/sharepointdsc/769#-L7coHbYGxyRNqC7jYZT:-L7cx6AQ8MUf2JLzxWUX:b-896fix) ([raw file](https://github.com/powershell/sharepointdsc/blob/21256d1d82ce5b06207339fa2ee1100cbf71d6cd/Modules/SharePointDsc/DSCResources/MSFT_SPDistributedCacheClientSettings/MSFT_SPDistributedCacheClientSettings.psm1#L374)):*
<details><summary><i>Previously, ykuijs (Yorick Kuijs) wrote…</i></summary><blockquote>

Since $IsSingleInstance can only be Yes, this check isn't necessary.
</blockquote></details>

Done.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPDistributedCacheClientSettings/MSFT_SPDistributedCacheClientSettings.psm1, line 543 at r4](https://reviewable.io:443/reviews/powershell/sharepointdsc/769#-L7coPGSnwHTkfEVjwqu:-L7cx7y7UVcCy-muiU7L:b-896fix) ([raw file](https://github.com/powershell/sharepointdsc/blob/21256d1d82ce5b06207339fa2ee1100cbf71d6cd/Modules/SharePointDsc/DSCResources/MSFT_SPDistributedCacheClientSettings/MSFT_SPDistributedCacheClientSettings.psm1#L543)):*
<details><summary><i>Previously, ykuijs (Yorick Kuijs) wrote…</i></summary><blockquote>

Since $IsSingleInstance can only be Yes, this won't ever happen
</blockquote></details>

Done.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPDistributedCacheClientSettings/MSFT_SPDistributedCacheClientSettings.psm1, line 691 at r4](https://reviewable.io:443/reviews/powershell/sharepointdsc/769#-L7coU1e_7C2SuX8V2Tr:-L7cxCerst01ICbkVadq:b-896fix) ([raw file](https://github.com/powershell/sharepointdsc/blob/21256d1d82ce5b06207339fa2ee1100cbf71d6cd/Modules/SharePointDsc/DSCResources/MSFT_SPDistributedCacheClientSettings/MSFT_SPDistributedCacheClientSettings.psm1#L691)):*
<details><summary><i>Previously, ykuijs (Yorick Kuijs) wrote…</i></summary><blockquote>

You shouldn't have to check IsSingleInstance
</blockquote></details>

Done.

---

*[Tests/Unit/SharePointDsc/SharePointDsc.SPDistributedCacheClientSettings.Tests.ps1, line 89 at r2](https://reviewable.io:443/reviews/powershell/sharepointdsc/769#-L6OGa2ovBAb2yZQROJG:-L7czz6dYLf2MuJzlpdc:b-896fix) ([raw file](https://github.com/powershell/sharepointdsc/blob/ba2fdd711ff40f086d623d3500f2626b259eedc1/Tests/Unit/SharePointDsc/SharePointDsc.SPDistributedCacheClientSettings.Tests.ps1#L89)):*
<details><summary><i>Previously, ykuijs (Yorick Kuijs) wrote…</i></summary><blockquote>

This test still tests for "Should be $false"
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/769)*

**Comment by ykuijs** [comment]
:lgtm:

---

Reviewed 1 of 7 files at r2, 2 of 4 files at r4, 2 of 2 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/769#-:-L7dZGLEMEHU48hWU2vp:bnfp4nl)*

**Pull request merged**
