### PR TITLE
AutoSPInstaller Example Code

### PR DESCRIPTION
**Pull request by mrpullen**
#398 

Added Example that would take an AutoSPInstaller.xml file and generate a DSC Configuration. This is still in a preliminary stage, but wanted to put in a pull request to solicit feedback on approach before I go too far down the rabbit hole.

- [X] Change details added to Unreleased section of changelog.md?
- [NA] Added/updated documentation and descriptions in .schema.mof files where appropriate?
- [NA ] Examples updated for both the single server and small farm templates in the examples folder?
- [X] New/changed code adheres to [Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md)?
- [ ] [Unit and Integration tests](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md) created/updated where possible?

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/sharepointdsc/514)

### CODE REVIEW

**Comment by mrpullen** [comment]
My bad. I branched from another pull request. I will clean up the MSFT_SPWebApplication updates tomorrow from this branch. Let me know if this fits with the basic idea of getting DSC to work with the SPAutoInstaller, or if you want to refactor to make the entire thing cleaner. It might be nice to "convert" the XML into a $Configuration hash table or something so we would have a standard object to work with, then pass in the object instead of passing in the XML.

**Comment by BrianFarnhill** [comment]
I will review this one when I get a little more time, but gut feeling says we are on the right path. Shooting from the hip a couple of thoughts:

* I think we might need to look at the credential management stuff in a little more detail. I wanna run some tests to make sure they encrypt right
* I think I want to move the folder out of that examples folder, but will give that some thought too
* We will need to look at unit testing for this, but again I want to give that some thought too

I'll get back to a full review ASAP though

---

Reviewed 1 of 4 files at r2.
Review status: 1 of 3 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/514#-:-Kdy-vsZeZOpgMe9Ku_z:b-9tzf9y)*

**Comment by mrpullen** [comment]
Another option, and maybe something that would work better would be to write a function that would take the XML and just generate a PowerShell data file. Then we could just build a standard Configuration that would take the PowerShell data file configuration. The benefit is that once you ran the script you would be back in "native" DSC land. I might work up a quick sample of this as well. We could push all the specifics into a data file like.

Uploaded a quick sample of what I thought that might look like

**Comment by BrianFarnhill** [comment]
@mrpullen I'm not sure about the second one, I think as a middle ground the initial idea of just parsing the xml like you have to start with is the better approach to take on this one.

**Comment by mrpullen** [comment]
Ok. Will finish up on an xml parser.

**Comment by mrpullen** [comment]
I am going to build this out as a set of composite resources. That way each "top level" XML node can be broken out, making testing each specific piece a bit simpler. I am going to close this PR and submit a new one once that's ready. Finishing a project now, but this will be first up on my list once I am clear.

**Pull request closed without merging**
