### PR TITLE
Update MSFT_SPSearchContentSource.psm1 issue #840

### PR DESCRIPTION
**Pull request by adruet29**
Regarding issue MSFT_SPSearchContentSource does not take StartHour parameter for schedule #840

I was able to solve this issue, but I must admit that I am a newbie regarding the pull request process...

So here it is. From what I was able to understand, the StartHour parameter is correctly checked in the test Get-SPDSCSearchCrawlSchedule.psm1 module.
The issue seems to be in the MSFT_SPSearchContentSource.psm1, as in its Set-TargetResource function there is never the parameter CrawlScheduleStartDateTime which is required by the sharepoint powershell cmdlet Set-SPEnterpriseSearchCrawlContentSource to had a start hour to the schedule.

Hope it helps.

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/sharepointdsc/841)

### CODE REVIEW

**Comment by adruet29** [comment]
OK, sorry for my beginer's mistakes.

So I added this to changelog:
## Unreleased

* MSFT_SPSearchContentSource
  * Fixed issue where the parameter StartHour was never taken into account (issue 840)

Hope it's ok the way I did it.

**Comment by ykuijs** [comment]
No problem, we have all been there ;-)

Please make sure you add the item in alphabetical order.

**Comment by adruet29** [comment]
Hum, I see, so I took the changelog file from the dev branch and inserted the comment on my fix respecting the alphabetical number:

# Change log for SharePointDsc

## Unreleased

* SPCacheAccounts
  * Fixed issue where the Test method would fail if SetWebAppPolicy was set to
    false.
* SPDistributedCacheService
  * Updated resource to allow updating the cache size
* SPFarm
  * Implemented ability to deploy Central Administration site to a server at a
    later point in time
* SPInfoPathFormsServiceConfig
  * Fixed issue with trying to set the MaxSizeOfUserFormState parameter
* SPProductUpdate
  * Fixed an issue where the resource failed when the search was already paused
* SPProjectServerLicense
  * Fixed issue with incorrect detection of the license
* SPSearchContentSource
  * Fixed issue where the Get method returned a conversion error when the content
    source contained just one address
  * Fixed issue where the parameter StartHour was never taken into account (issue 840)
* SPSearchServiceApp
  * Fixed issue where the service account was not set correctly when the service
    application was first created
  * Fixed issue where the Get method throws an error when the service app wasn't
    created properly

**Comment by ykuijs** [comment]
Ok, just noticed you used the wrong branch as starting point. You used branch release-2.3 (branch used for releasing v2.3), but should have used the branch "dev", which is the active development branch. I tried to change branch, but this means a lot of other files are also included into this PR.

Can you please use the Dev branch as your starting point and resubmit the PR?

**Comment by adruet29** [comment]
My mistake, sorry about that. I will close this one and open a new one.

**Pull request closed without merging**
