### PR TITLE
Added the new SPWebAppSuiteBar resource to edit Web App Suite Bar branding

### PR DESCRIPTION
**Pull request by NikCharlebois**
- ✔ Change details added to Unreleased section of changelog.md?
- ✔ Added/updated documentation and descriptions in .schema.mof files where appropriate?
- ✔ Examples updated for both the single server and small farm templates in the examples folder?
- ✔ New/changed code adheres to [Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md)?
- ✔ [Unit and Integration tests](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md) created/updated where possible?

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/sharepointdsc/662)

### CODE REVIEW

**Comment by NikCharlebois** [comment]
Pop open the Champagne! It worked!

**Comment by BrianFarnhill** [comment]
You're missing the resource-specific example for this one (under Modules\SharePointDsc\Examples\Resources\SPWebAppSuiteBar). I've got some feedback on the main work done, I'll review the tests once the other changes are made. Thanks mate

---

Reviewed 1 of 4 files at r1, 5 of 6 files at r2.
Review status: 6 of 7 files reviewed at latest revision, 10 unresolved discussions.

---

*[CHANGELOG.md, line 7 at r2](https://reviewable.io:443/reviews/powershell/sharepointdsc/662#-KwqW7gbStay4u-SDXlq:-KwqW7gbStay4u-SDXlr:bwt77c4) ([raw file](https://github.com/powershell/sharepointdsc/blob/5026a4a78823a7f0bb37fcc1b3b403383c259c77/CHANGELOG.md#L7)):*
> ```Markdown
> * Added resource: SPMinRoleCompliance
> 
> ## 2.0
> ```

Can you put this under "unreleased" like we normally do?

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPWebAppSuiteBar/MSFT_SPWebAppSuiteBar.psm1, line 38 at r2](https://reviewable.io:443/reviews/powershell/sharepointdsc/662#-KwqWIk-VfdNw-f22tq6:-KwqWIk-VfdNw-f22tq7:b76jpt8) ([raw file](https://github.com/powershell/sharepointdsc/blob/5026a4a78823a7f0bb37fcc1b3b403383c259c77/Modules/SharePointDsc/DSCResources/MSFT_SPWebAppSuiteBar/MSFT_SPWebAppSuiteBar.psm1#L38)):*
> ```PowerShell
>     Write-Verbose -Message "Getting web app suite bar properties for $WebAppUrl"
> 
>     $installedVersion = Get-SPDSCInstalledProductVersion    
> ```

I don't think you are using this line here at all since you grab the version inside the invoke block below, so you should be able to remove this line

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPWebAppSuiteBar/MSFT_SPWebAppSuiteBar.psm1, line 50 at r2](https://reviewable.io:443/reviews/powershell/sharepointdsc/662#-KwqWRUBJtJEFTmIZig0:-KwqWRUBJtJEFTmIZig1:b-jtwlj7) ([raw file](https://github.com/powershell/sharepointdsc/blob/5026a4a78823a7f0bb37fcc1b3b403383c259c77/Modules/SharePointDsc/DSCResources/MSFT_SPWebAppSuiteBar/MSFT_SPWebAppSuiteBar.psm1#L50)):*
> ```PowerShell
>         if ($null -eq $wa) 
>         { 
>             return $null 
> ```

We shouldn't be returning null from "get" methods. I would return the initial $returnVal value you have below with all the nulls on it rather than a flat-out null

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPWebAppSuiteBar/MSFT_SPWebAppSuiteBar.psm1, line 140 at r2](https://reviewable.io:443/reviews/powershell/sharepointdsc/662#-KwqWhJrdTOmfH8jRX68:-KwqWhJrdTOmfH8jRX69:b-lqghn9) ([raw file](https://github.com/powershell/sharepointdsc/blob/5026a4a78823a7f0bb37fcc1b3b403383c259c77/Modules/SharePointDsc/DSCResources/MSFT_SPWebAppSuiteBar/MSFT_SPWebAppSuiteBar.psm1#L140)):*
> ```PowerShell
>         }
>     }
>     elseif($installedVersion.FileMajorPart -ge 16)
> ```

Rather than elseif can you put this in to a switch statement, then use a default block that throws an error about using an unsupported version of SP. There are examples of this elsewhere in the module

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPWebAppSuiteBar/MSFT_SPWebAppSuiteBar.psm1, line 164 at r2](https://reviewable.io:443/reviews/powershell/sharepointdsc/662#-KwqXE6Ds3qV475Z8wEf:-KwqXE6Ds3qV475Z8wEg:b4kqox8) ([raw file](https://github.com/powershell/sharepointdsc/blob/5026a4a78823a7f0bb37fcc1b3b403383c259c77/Modules/SharePointDsc/DSCResources/MSFT_SPWebAppSuiteBar/MSFT_SPWebAppSuiteBar.psm1#L164)):*
> ```PowerShell
>     $CurrentValues = Get-TargetResource @PSBoundParameters
>     
>     if ($null -eq $CurrentValues) 
> ```

Expect this to not be a $null based on the previous item, so you'll need to change your approach here as well

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPWebAppSuiteBar/MSFT_SPWebAppSuiteBar.psm1, line 189 at r2](https://reviewable.io:443/reviews/powershell/sharepointdsc/662#-KwqXbYAOqC6JO8pYAY1:-KwqXbYAOqC6JO8pYAY2:bm6prh6) ([raw file](https://github.com/powershell/sharepointdsc/blob/5026a4a78823a7f0bb37fcc1b3b403383c259c77/Modules/SharePointDsc/DSCResources/MSFT_SPWebAppSuiteBar/MSFT_SPWebAppSuiteBar.psm1#L189)):*
> ```PowerShell
>         {
>             $wa.SuiteBarBrandingElementHtml = $params.SuiteBarBrandingElementHtml
>             $wa.Update()
> ```

You can put this update line after the if statement seeing as it's in both code blocks

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPWebAppSuiteBar/MSFT_SPWebAppSuiteBar.psm1, line 241 at r2](https://reviewable.io:443/reviews/powershell/sharepointdsc/662#-KwqXpoteaFFCbo5viEg:-KwqXpoteaFFCbo5viEh:bv0ii48) ([raw file](https://github.com/powershell/sharepointdsc/blob/5026a4a78823a7f0bb37fcc1b3b403383c259c77/Modules/SharePointDsc/DSCResources/MSFT_SPWebAppSuiteBar/MSFT_SPWebAppSuiteBar.psm1#L241)):*
> ```PowerShell
>     $CurrentValues = Get-TargetResource @PSBoundParameters
>     
>     if ($null -eq $CurrentValues) 
> ```

Again don't expect a null here

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPWebAppSuiteBar/MSFT_SPWebAppSuiteBar.psm1, line 247 at r2](https://reviewable.io:443/reviews/powershell/sharepointdsc/662#-KwqXxTuc-q2OU6lNn0Z:-KwqXxTuc-q2OU6lNn0_:b-uqu1z2) ([raw file](https://github.com/powershell/sharepointdsc/blob/5026a4a78823a7f0bb37fcc1b3b403383c259c77/Modules/SharePointDsc/DSCResources/MSFT_SPWebAppSuiteBar/MSFT_SPWebAppSuiteBar.psm1#L247)):*
> ```PowerShell
> 
>     # Determine the default identity type to use for entries that do not have it specified
>     $returnValue = Invoke-SPDSCCommand -Credential $InstallAccount `
> ```

I don't think you need all of this logic here, you should just be able to use the Test-SPDscParameterState to compare the values. They will either match the desired state or they won't, and if the user provides invalid parameters then this will get caught in the set method. This means we can simplify this test method down a whole lot.

---

*[Modules/SharePointDsc/Examples/Single Server/SharePoint.ps1, line 142 at r2](https://reviewable.io:443/reviews/powershell/sharepointdsc/662#-KwqYrtD_T4kuHSsnZqW:-KwqYrtD_T4kuHSsnZqX:b-andevi) ([raw file](https://github.com/powershell/sharepointdsc/blob/5026a4a78823a7f0bb37fcc1b3b403383c259c77/Modules/SharePointDsc/Examples/Single Server/SharePoint.ps1#L142)):*
> ```PowerShell
>         }
>         
>         SPWebAppSuiteBar SuiteBarBranding
> ```

We tend to keep the examples here to just basic resources so it doesn't need to go in here, can you please remove this one

---

*[Modules/SharePointDsc/Examples/Small Farm/SharePoint.ps1, line 155 at r2](https://reviewable.io:443/reviews/powershell/sharepointdsc/662#-KwqYx9BfFCzpRjTvJ3G:-KwqYx9CMrQkLSwsjnFN:b-andevi) ([raw file](https://github.com/powershell/sharepointdsc/blob/5026a4a78823a7f0bb37fcc1b3b403383c259c77/Modules/SharePointDsc/Examples/Small Farm/SharePoint.ps1#L155)):*
> ```PowerShell
>         }
> 
>         SPWebAppSuiteBar SuiteBarBranding
> ```

We tend to keep the examples here to just basic resources so it doesn't need to go in here, can you please remove this one

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/662#-:-KwqZJ2_cV0xQQ4FqyZz:b91nj7x)*

**Comment by NikCharlebois** [comment]
Review status: 6 of 7 files reviewed at latest revision, 10 unresolved discussions.

---

*[CHANGELOG.md, line 7 at r2](https://reviewable.io:443/reviews/powershell/sharepointdsc/662#-KwqW7gbStay4u-SDXlq:-Kwr5AAx3ySuPGGOVrI9:b-896fix) ([raw file](https://github.com/powershell/sharepointdsc/blob/5026a4a78823a7f0bb37fcc1b3b403383c259c77/CHANGELOG.md#L7)):*
<details><summary><i>Previously, BrianFarnhill (Brian Farnhill) wrote…</i></summary><blockquote>

Can you put this under "unreleased" like we normally do?
</blockquote></details>

Done.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPWebAppSuiteBar/MSFT_SPWebAppSuiteBar.psm1, line 38 at r2](https://reviewable.io:443/reviews/powershell/sharepointdsc/662#-KwqWIk-VfdNw-f22tq6:-Kwr5eWjMVS2G2Uk787-:b-a91ydm) ([raw file](https://github.com/powershell/sharepointdsc/blob/5026a4a78823a7f0bb37fcc1b3b403383c259c77/Modules/SharePointDsc/DSCResources/MSFT_SPWebAppSuiteBar/MSFT_SPWebAppSuiteBar.psm1#L38)):*
<details><summary><i>Previously, BrianFarnhill (Brian Farnhill) wrote…</i></summary><blockquote>

I don't think you are using this line here at all since you grab the version inside the invoke block below, so you should be able to remove this line
</blockquote></details>

You are right. I removed the line

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPWebAppSuiteBar/MSFT_SPWebAppSuiteBar.psm1, line 50 at r2](https://reviewable.io:443/reviews/powershell/sharepointdsc/662#-KwqWRUBJtJEFTmIZig0:-Kwr5w9Ix-tDXmm5UEBA:brgks4n) ([raw file](https://github.com/powershell/sharepointdsc/blob/5026a4a78823a7f0bb37fcc1b3b403383c259c77/Modules/SharePointDsc/DSCResources/MSFT_SPWebAppSuiteBar/MSFT_SPWebAppSuiteBar.psm1#L50)):*
<details><summary><i>Previously, BrianFarnhill (Brian Farnhill) wrote…</i></summary><blockquote>

We shouldn't be returning null from "get" methods. I would return the initial $returnVal value you have below with all the nulls on it rather than a flat-out null
</blockquote></details>

I copied this line from the SPWebAppPolicy Resource. It also returns a direct $null, but I have changed mine to follow your recommendations.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPWebAppSuiteBar/MSFT_SPWebAppSuiteBar.psm1, line 140 at r2](https://reviewable.io:443/reviews/powershell/sharepointdsc/662#-KwqWhJrdTOmfH8jRX68:-Kwr6wAOudlDoZieL_xg:b-896fix) ([raw file](https://github.com/powershell/sharepointdsc/blob/5026a4a78823a7f0bb37fcc1b3b403383c259c77/Modules/SharePointDsc/DSCResources/MSFT_SPWebAppSuiteBar/MSFT_SPWebAppSuiteBar.psm1#L140)):*
<details><summary><i>Previously, BrianFarnhill (Brian Farnhill) wrote…</i></summary><blockquote>

Rather than elseif can you put this in to a switch statement, then use a default block that throws an error about using an unsupported version of SP. There are examples of this elsewhere in the module
</blockquote></details>

Done.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPWebAppSuiteBar/MSFT_SPWebAppSuiteBar.psm1, line 164 at r2](https://reviewable.io:443/reviews/powershell/sharepointdsc/662#-KwqXE6Ds3qV475Z8wEf:-Kwr7NS5HfuB49rQ5VK4:b-qev6eg) ([raw file](https://github.com/powershell/sharepointdsc/blob/5026a4a78823a7f0bb37fcc1b3b403383c259c77/Modules/SharePointDsc/DSCResources/MSFT_SPWebAppSuiteBar/MSFT_SPWebAppSuiteBar.psm1#L164)):*
<details><summary><i>Previously, BrianFarnhill (Brian Farnhill) wrote…</i></summary><blockquote>

Expect this to not be a $null based on the previous item, so you'll need to change your approach here as well
</blockquote></details>

Good call. Logic changed to check for WebAppUrl key to be null instead

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPWebAppSuiteBar/MSFT_SPWebAppSuiteBar.psm1, line 189 at r2](https://reviewable.io:443/reviews/powershell/sharepointdsc/662#-KwqXbYAOqC6JO8pYAY1:-Kwr7aIXZowtNUWb8OY6:b8li1fy) ([raw file](https://github.com/powershell/sharepointdsc/blob/5026a4a78823a7f0bb37fcc1b3b403383c259c77/Modules/SharePointDsc/DSCResources/MSFT_SPWebAppSuiteBar/MSFT_SPWebAppSuiteBar.psm1#L189)):*
<details><summary><i>Previously, BrianFarnhill (Brian Farnhill) wrote…</i></summary><blockquote>

You can put this update line after the if statement seeing as it's in both code blocks
</blockquote></details>

Done deal. One less line of code.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPWebAppSuiteBar/MSFT_SPWebAppSuiteBar.psm1, line 241 at r2](https://reviewable.io:443/reviews/powershell/sharepointdsc/662#-KwqXpoteaFFCbo5viEg:-Kwr7nMk5hX_3Rwxd7uF:b-896fix) ([raw file](https://github.com/powershell/sharepointdsc/blob/5026a4a78823a7f0bb37fcc1b3b403383c259c77/Modules/SharePointDsc/DSCResources/MSFT_SPWebAppSuiteBar/MSFT_SPWebAppSuiteBar.psm1#L241)):*
<details><summary><i>Previously, BrianFarnhill (Brian Farnhill) wrote…</i></summary><blockquote>

Again don't expect a null here
</blockquote></details>

Done.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPWebAppSuiteBar/MSFT_SPWebAppSuiteBar.psm1, line 247 at r2](https://reviewable.io:443/reviews/powershell/sharepointdsc/662#-KwqXxTuc-q2OU6lNn0Z:-Kwr8oLcTrKXIokRMYo7:b-qul8yo) ([raw file](https://github.com/powershell/sharepointdsc/blob/5026a4a78823a7f0bb37fcc1b3b403383c259c77/Modules/SharePointDsc/DSCResources/MSFT_SPWebAppSuiteBar/MSFT_SPWebAppSuiteBar.psm1#L247)):*
<details><summary><i>Previously, BrianFarnhill (Brian Farnhill) wrote…</i></summary><blockquote>

I don't think you need all of this logic here, you should just be able to use the Test-SPDscParameterState to compare the values. They will either match the desired state or they won't, and if the user provides invalid parameters then this will get caught in the set method. This means we can simplify this test method down a whole lot.
</blockquote></details>

Yeah, you are right. I overdid the Test method a bit. It is simplified now.

---

*[Modules/SharePointDsc/Examples/Single Server/SharePoint.ps1, line 142 at r2](https://reviewable.io:443/reviews/powershell/sharepointdsc/662#-KwqYrtD_T4kuHSsnZqW:-Kwr93Y3fC_mvOgadwPn:bb6un1j) ([raw file](https://github.com/powershell/sharepointdsc/blob/5026a4a78823a7f0bb37fcc1b3b403383c259c77/Modules/SharePointDsc/Examples/Single Server/SharePoint.ps1#L142)):*
<details><summary><i>Previously, BrianFarnhill (Brian Farnhill) wrote…</i></summary><blockquote>

We tend to keep the examples here to just basic resources so it doesn't need to go in here, can you please remove this one
</blockquote></details>

Done

---

*[Modules/SharePointDsc/Examples/Small Farm/SharePoint.ps1, line 155 at r2](https://reviewable.io:443/reviews/powershell/sharepointdsc/662#-KwqYx9BfFCzpRjTvJ3G:-Kwr98H8V5LsADXS_4CU:bb6un1j) ([raw file](https://github.com/powershell/sharepointdsc/blob/5026a4a78823a7f0bb37fcc1b3b403383c259c77/Modules/SharePointDsc/Examples/Small Farm/SharePoint.ps1#L155)):*
<details><summary><i>Previously, BrianFarnhill (Brian Farnhill) wrote…</i></summary><blockquote>

We tend to keep the examples here to just basic resources so it doesn't need to go in here, can you please remove this one
</blockquote></details>

Done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/662)*

**Comment by ykuijs** [comment]
@NikCharlebois Mate, your last commit broke some of the tests. Can you fix this, so we can merge this PR?

**Comment by NikCharlebois** [comment]
It's fixed now.

---

Review status: 2 of 8 files reviewed at latest revision, 10 unresolved discussions.

---

*[CHANGELOG.md, line 7 at r2](https://reviewable.io:443/reviews/powershell/sharepointdsc/662#-KwqW7gbStay4u-SDXlq:-KxiLtxhnzCPE7hrbHG0:b-896fix) ([raw file](https://github.com/powershell/sharepointdsc/blob/5026a4a78823a7f0bb37fcc1b3b403383c259c77/CHANGELOG.md#L7)):*
<details><summary><i>Previously, NikCharlebois (Nik Charlebois) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Done.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPWebAppSuiteBar/MSFT_SPWebAppSuiteBar.psm1, line 38 at r2](https://reviewable.io:443/reviews/powershell/sharepointdsc/662#-KwqWIk-VfdNw-f22tq6:-KxiLv0IbhT9NcqFj73a:b-896fix) ([raw file](https://github.com/powershell/sharepointdsc/blob/5026a4a78823a7f0bb37fcc1b3b403383c259c77/Modules/SharePointDsc/DSCResources/MSFT_SPWebAppSuiteBar/MSFT_SPWebAppSuiteBar.psm1#L38)):*
<details><summary><i>Previously, NikCharlebois (Nik Charlebois) wrote…</i></summary><blockquote>

You are right. I removed the line
</blockquote></details>

Done.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPWebAppSuiteBar/MSFT_SPWebAppSuiteBar.psm1, line 50 at r2](https://reviewable.io:443/reviews/powershell/sharepointdsc/662#-KwqWRUBJtJEFTmIZig0:-KxiLw1YewebFgrU1ir0:b-896fix) ([raw file](https://github.com/powershell/sharepointdsc/blob/5026a4a78823a7f0bb37fcc1b3b403383c259c77/Modules/SharePointDsc/DSCResources/MSFT_SPWebAppSuiteBar/MSFT_SPWebAppSuiteBar.psm1#L50)):*
<details><summary><i>Previously, NikCharlebois (Nik Charlebois) wrote…</i></summary><blockquote>

I copied this line from the SPWebAppPolicy Resource. It also returns a direct $null, but I have changed mine to follow your recommendations.
</blockquote></details>

Done.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPWebAppSuiteBar/MSFT_SPWebAppSuiteBar.psm1, line 140 at r2](https://reviewable.io:443/reviews/powershell/sharepointdsc/662#-KwqWhJrdTOmfH8jRX68:-KxiLx658oihJzA3DLW8:b-896fix) ([raw file](https://github.com/powershell/sharepointdsc/blob/5026a4a78823a7f0bb37fcc1b3b403383c259c77/Modules/SharePointDsc/DSCResources/MSFT_SPWebAppSuiteBar/MSFT_SPWebAppSuiteBar.psm1#L140)):*
<details><summary><i>Previously, NikCharlebois (Nik Charlebois) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Done.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPWebAppSuiteBar/MSFT_SPWebAppSuiteBar.psm1, line 164 at r2](https://reviewable.io:443/reviews/powershell/sharepointdsc/662#-KwqXE6Ds3qV475Z8wEf:-KxiLxp9LhNjIGl15IA6:b-896fix) ([raw file](https://github.com/powershell/sharepointdsc/blob/5026a4a78823a7f0bb37fcc1b3b403383c259c77/Modules/SharePointDsc/DSCResources/MSFT_SPWebAppSuiteBar/MSFT_SPWebAppSuiteBar.psm1#L164)):*
<details><summary><i>Previously, NikCharlebois (Nik Charlebois) wrote…</i></summary><blockquote>

Good call. Logic changed to check for WebAppUrl key to be null instead
</blockquote></details>

Done.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPWebAppSuiteBar/MSFT_SPWebAppSuiteBar.psm1, line 189 at r2](https://reviewable.io:443/reviews/powershell/sharepointdsc/662#-KwqXbYAOqC6JO8pYAY1:-KxiLylwQzRJeGuCqvgf:b-896fix) ([raw file](https://github.com/powershell/sharepointdsc/blob/5026a4a78823a7f0bb37fcc1b3b403383c259c77/Modules/SharePointDsc/DSCResources/MSFT_SPWebAppSuiteBar/MSFT_SPWebAppSuiteBar.psm1#L189)):*
<details><summary><i>Previously, NikCharlebois (Nik Charlebois) wrote…</i></summary><blockquote>

Done deal. One less line of code.
</blockquote></details>

Done.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPWebAppSuiteBar/MSFT_SPWebAppSuiteBar.psm1, line 241 at r2](https://reviewable.io:443/reviews/powershell/sharepointdsc/662#-KwqXpoteaFFCbo5viEg:-KxiLziNYaXfylpploqu:b-896fix) ([raw file](https://github.com/powershell/sharepointdsc/blob/5026a4a78823a7f0bb37fcc1b3b403383c259c77/Modules/SharePointDsc/DSCResources/MSFT_SPWebAppSuiteBar/MSFT_SPWebAppSuiteBar.psm1#L241)):*
<details><summary><i>Previously, NikCharlebois (Nik Charlebois) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Done.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPWebAppSuiteBar/MSFT_SPWebAppSuiteBar.psm1, line 247 at r2](https://reviewable.io:443/reviews/powershell/sharepointdsc/662#-KwqXxTuc-q2OU6lNn0Z:-KxiM-TxBs2VasIIhu-q:b-896fix) ([raw file](https://github.com/powershell/sharepointdsc/blob/5026a4a78823a7f0bb37fcc1b3b403383c259c77/Modules/SharePointDsc/DSCResources/MSFT_SPWebAppSuiteBar/MSFT_SPWebAppSuiteBar.psm1#L247)):*
<details><summary><i>Previously, NikCharlebois (Nik Charlebois) wrote…</i></summary><blockquote>

Yeah, you are right. I overdid the Test method a bit. It is simplified now.
</blockquote></details>

Done.

---

*[Modules/SharePointDsc/Examples/Single Server/SharePoint.ps1, line 142 at r2](https://reviewable.io:443/reviews/powershell/sharepointdsc/662#-KwqYrtD_T4kuHSsnZqW:-KxiM0MJLXp9qSytj7kC:b-896fix) ([raw file](https://github.com/powershell/sharepointdsc/blob/5026a4a78823a7f0bb37fcc1b3b403383c259c77/Modules/SharePointDsc/Examples/Single Server/SharePoint.ps1#L142)):*
<details><summary><i>Previously, NikCharlebois (Nik Charlebois) wrote…</i></summary><blockquote>

Done
</blockquote></details>

Done.

---

*[Modules/SharePointDsc/Examples/Small Farm/SharePoint.ps1, line 155 at r2](https://reviewable.io:443/reviews/powershell/sharepointdsc/662#-KwqYx9BfFCzpRjTvJ3G:-KxiM1P-rpBT-OWqDVnf:b-896fix) ([raw file](https://github.com/powershell/sharepointdsc/blob/5026a4a78823a7f0bb37fcc1b3b403383c259c77/Modules/SharePointDsc/Examples/Small Farm/SharePoint.ps1#L155)):*
<details><summary><i>Previously, NikCharlebois (Nik Charlebois) wrote…</i></summary><blockquote>

Done
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/662#-:-KxiLpIoyWF2jnSjIJb7:b93hkmg)*

**Comment by NikCharlebois** [comment]
Reviewed 5 of 6 files at r3, 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/662)*

**Comment by BrianFarnhill** [comment]
:lgtm: Just needs a pull from dev to resolve conflicts in the changelog and it's good to go.

---

Reviewed 5 of 6 files at r3, 2 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/662#-:-KyD9wYYV9Yq88JAtoKu:b8d8z73)*

**Comment by BrianFarnhill** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/662#-:-KyI4TAX4Hj1iNji4rZx:bnfp4nl)*

**Pull request merged**
