### PR TITLE
SPLogLevel

### PR DESCRIPTION
**Pull request by MikeLacher448**
new resource, SPLogLevel, as described in issue #274 

- [x] Change details added to Unreleased section of changelog.md?
- [x] Added/updated documentation and descriptions in .schema.mof files where appropriate?
- [x] Examples updated for both the single server and small farm templates in the examples folder?
- [x] New/changed code adheres to [Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md)?
- [x] [Unit and Integration tests](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md) created/updated where possible?

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/sharepointdsc/685)

### CODE REVIEW

**Comment by MikeLacher448** [comment]
getting appveyor errors because tThe only mandatory property is a collection. I could throw in a mandatory string that isn't used for anything, but that feels like cheating.. Open to ideas on approaches for this.

**Comment by BrianFarnhill** [comment]
@MikeLacher448 Did you actually run this as part of a DSC script? I'm pretty sure that the primary key being a collection will actually break things and not let that resource run. So we need to come up with something to be the primary key. I suggest something like "Ensure = Present" as it's generic and well understood elsewhere, and just throw an error when someone specifies ensure = absent. Does that make sense?

**Comment by ykuijs** [comment]
@BrianFarnhill is correct, a Key parameter cannot be an collection. I would not prefer to use the Ensure parameter as key, since this would mean we are limiting users to only use one SPLogLevel blocks in their configs.

I would suggest to use a Name parameter, in which you can specify a name for your config. This parameter wouldn't be used for anything else, but would give use some flexibility.

**Comment by MikeLacher448** [comment]
I tested the get/set/ and test methods on a SP server, but no, I did not actually try to compile and apply a configuration. Adjusting now to use a Name as a key, and will compile and apply a config to test as well.

**Comment by MikeLacher448** [comment]
all checks passed, ready for review

**Comment by ykuijs** [comment]
Resources looks good, just a few review comments

---

Reviewed 1 of 8 files at r1, 4 of 7 files at r3.
Review status: 5 of 8 files reviewed at latest revision, 22 unresolved discussions.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPLogLevel/MSFT_SPLogLevel.psm1, line 26 at r3](https://reviewable.io:443/reviews/powershell/sharepointdsc/685#-Kzd3hLb6Eyp8zo5I8Sj:-Kzd3hLb6Eyp8zo5I8Sk:bayvj6x) ([raw file](https://github.com/powershell/sharepointdsc/blob/66ec9e5f44de2ff380ea2714f85527e4830a2d09/Modules/SharePointDsc/DSCResources/MSFT_SPLogLevel/MSFT_SPLogLevel.psm1#L26)):*
> ```PowerShell
>         {
>             Write-Verbose -Message "Exactly one log area, or the wildcard character '*' must be provided for each log item area"
>             return $null
> ```

We shouldn't be returning null from "get" methods. I would prefer to specify a $nullReturn value with all the nulls on it rather than a flat-out null:
$nullReturn = @{
    $Name = $Name
    $SPLogLevelSetting = $null
}

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPLogLevel/MSFT_SPLogLevel.psm1, line 60 at r3](https://reviewable.io:443/reviews/powershell/sharepointdsc/685#-Kzd3MgQQ1slFub_XgIp:-Kzd3MgQQ1slFub_XgIq:b-pb4q6m) ([raw file](https://github.com/powershell/sharepointdsc/blob/66ec9e5f44de2ff380ea2714f85527e4830a2d09/Modules/SharePointDsc/DSCResources/MSFT_SPLogLevel/MSFT_SPLogLevel.psm1#L60)):*
> ```PowerShell
>                                  -Arguments $PSBoundParameters `
>                                  -ScriptBlock {
> ```

Please remove empty line

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPLogLevel/MSFT_SPLogLevel.psm1, line 66 at r3](https://reviewable.io:443/reviews/powershell/sharepointdsc/685#-Kzd4XbDnPDBOCt1_RHQ:-Kzd4XbDnPDBOCt1_RHR:be7imz4) ([raw file](https://github.com/powershell/sharepointdsc/blob/66ec9e5f44de2ff380ea2714f85527e4830a2d09/Modules/SharePointDsc/DSCResources/MSFT_SPLogLevel/MSFT_SPLogLevel.psm1#L66)):*
> ```PowerShell
>          foreach ($DesiredSetting in $params.SPLogLevelSetting)
>          {
>             Write-Verbose "Getting SP Log Level Settings for $($DesiredSetting.Area):$($DesiredSetting.Name)"
> ```

Please use named parameters. -Message in this case

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPLogLevel/MSFT_SPLogLevel.psm1, line 98 at r3](https://reviewable.io:443/reviews/powershell/sharepointdsc/685#-Kzd3R1PAW1UlEGDstn2:-Kzd3R1PAW1UlEGDstn3:b-pb4q6m) ([raw file](https://github.com/powershell/sharepointdsc/blob/66ec9e5f44de2ff380ea2714f85527e4830a2d09/Modules/SharePointDsc/DSCResources/MSFT_SPLogLevel/MSFT_SPLogLevel.psm1#L98)):*
> ```PowerShell
>                     $Tracelevel = [System.String]::Join(",",(($CurrentLogItemSettings.traceseverity) | Select-Object -Unique))
>                 }
> ```

Please remove empty line

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPLogLevel/MSFT_SPLogLevel.psm1, line 128 at r3](https://reviewable.io:443/reviews/powershell/sharepointdsc/685#-Kzd3T8kus-ffrGFM-Bx:-Kzd3T8kus-ffrGFM-By:b-pb4q6m) ([raw file](https://github.com/powershell/sharepointdsc/blob/66ec9e5f44de2ff380ea2714f85527e4830a2d09/Modules/SharePointDsc/DSCResources/MSFT_SPLogLevel/MSFT_SPLogLevel.psm1#L128)):*
> ```PowerShell
>                     $Eventlevel = [System.String]::Join(",",(($CurrentLogItemSettings.Eventseverity) | Select-Object -Unique))
>                 }
> ```

Please remove empty line

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPLogLevel/MSFT_SPLogLevel.psm1, line 135 at r3](https://reviewable.io:443/reviews/powershell/sharepointdsc/685#-Kzd3TzHeuSS-amcyg-l:-Kzd3TzHeuSS-amcyg-m:b-4zz3sb) ([raw file](https://github.com/powershell/sharepointdsc/blob/66ec9e5f44de2ff380ea2714f85527e4830a2d09/Modules/SharePointDsc/DSCResources/MSFT_SPLogLevel/MSFT_SPLogLevel.psm1#L135)):*
> ```PowerShell
>                $Eventlevel = [System.String]::Join(",",(($CurrentLogItemSettings.Eventseverity) | Select-Object -Unique))
>             }
> ```

Please remove additional empty line

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPLogLevel/MSFT_SPLogLevel.psm1, line 143 at r3](https://reviewable.io:443/reviews/powershell/sharepointdsc/685#-Kzd3WrXctgSZDtpturm:-Kzd3WrXctgSZDtpturn:b-38txvj) ([raw file](https://github.com/powershell/sharepointdsc/blob/66ec9e5f44de2ff380ea2714f85527e4830a2d09/Modules/SharePointDsc/DSCResources/MSFT_SPLogLevel/MSFT_SPLogLevel.psm1#L143)):*
> ```PowerShell
>                 EventLevel = $EventLevel
>              }
> ```

Please remove empty lines

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPLogLevel/MSFT_SPLogLevel.psm1, line 151 at r3](https://reviewable.io:443/reviews/powershell/sharepointdsc/685#-Kzd3Y9wm63w2gRe6SJC:-Kzd3Y9wm63w2gRe6SJD:b-pb4q6m) ([raw file](https://github.com/powershell/sharepointdsc/blob/66ec9e5f44de2ff380ea2714f85527e4830a2d09/Modules/SharePointDsc/DSCResources/MSFT_SPLogLevel/MSFT_SPLogLevel.psm1#L151)):*
> ```PowerShell
>             SPLogLevelSetting = $CurrentLogLevelSettings
>         }
> ```

Please remove empty line

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPLogLevel/MSFT_SPLogLevel.psm1, line 153 at r3](https://reviewable.io:443/reviews/powershell/sharepointdsc/685#-Kzd4vNocpvToiiCcnb2:-Kzd4vNocpvToiiCcnb3:b-pb4q6m) ([raw file](https://github.com/powershell/sharepointdsc/blob/66ec9e5f44de2ff380ea2714f85527e4830a2d09/Modules/SharePointDsc/DSCResources/MSFT_SPLogLevel/MSFT_SPLogLevel.psm1#L153)):*
> ```PowerShell
> 
>     }
> ```

Please remove empty line

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPLogLevel/MSFT_SPLogLevel.psm1, line 155 at r3](https://reviewable.io:443/reviews/powershell/sharepointdsc/685#-Kzd3YhDlkyVqNDwYeIf:-Kzd3YhDlkyVqNDwYeIg:b-38txvj) ([raw file](https://github.com/powershell/sharepointdsc/blob/66ec9e5f44de2ff380ea2714f85527e4830a2d09/Modules/SharePointDsc/DSCResources/MSFT_SPLogLevel/MSFT_SPLogLevel.psm1#L155)):*
> ```PowerShell
> 
>     return $result
> ```

Please remove empty lines

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPLogLevel/MSFT_SPLogLevel.psm1, line 212 at r3](https://reviewable.io:443/reviews/powershell/sharepointdsc/685#-Kzd5-iD_VlB_vU7ZWCp:-Kzd5-iD_VlB_vU7ZWCq:b-pb4q6m) ([raw file](https://github.com/powershell/sharepointdsc/blob/66ec9e5f44de2ff380ea2714f85527e4830a2d09/Modules/SharePointDsc/DSCResources/MSFT_SPLogLevel/MSFT_SPLogLevel.psm1#L212)):*
> ```PowerShell
>                         -Arguments $PSBoundParameters `
>                         -ScriptBlock {
> ```

Please remove empty line

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPLogLevel/MSFT_SPLogLevel.psm1, line 258 at r3](https://reviewable.io:443/reviews/powershell/sharepointdsc/685#-Kzd3cHG7C5bMzdulFI9:-Kzd3cHG7C5bMzdulFIA:b-38txvj) ([raw file](https://github.com/powershell/sharepointdsc/blob/66ec9e5f44de2ff380ea2714f85527e4830a2d09/Modules/SharePointDsc/DSCResources/MSFT_SPLogLevel/MSFT_SPLogLevel.psm1#L258)):*
> ```PowerShell
>                 }
>             }
> ```

Please remove empty lines

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPLogLevel/MSFT_SPLogLevel.psm1, line 262 at r3](https://reviewable.io:443/reviews/powershell/sharepointdsc/685#-Kzd3dAvP7cKkOG5KT5F:-Kzd3dAvP7cKkOG5KT5G:b-38txvj) ([raw file](https://github.com/powershell/sharepointdsc/blob/66ec9e5f44de2ff380ea2714f85527e4830a2d09/Modules/SharePointDsc/DSCResources/MSFT_SPLogLevel/MSFT_SPLogLevel.psm1#L262)):*
> ```PowerShell
> 
>         }
> ```

Please remove empty lines

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPLogLevel/MSFT_SPLogLevel.psm1, line 266 at r3](https://reviewable.io:443/reviews/powershell/sharepointdsc/685#-Kzd3dnZ--OGb8Ksca66:-Kzd3dnZ--OGb8Ksca67:b-38txvj) ([raw file](https://github.com/powershell/sharepointdsc/blob/66ec9e5f44de2ff380ea2714f85527e4830a2d09/Modules/SharePointDsc/DSCResources/MSFT_SPLogLevel/MSFT_SPLogLevel.psm1#L266)):*
> ```PowerShell
> 
>     }
> ```

Please remove empty lines

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPLogLevel/MSFT_SPLogLevel.psm1, line 311 at r3](https://reviewable.io:443/reviews/powershell/sharepointdsc/685#-Kzd4KIlJ0LxLOIWcpUa:-Kzd4KIlJ0LxLOIWcpUb:b-pb4q6m) ([raw file](https://github.com/powershell/sharepointdsc/blob/66ec9e5f44de2ff380ea2714f85527e4830a2d09/Modules/SharePointDsc/DSCResources/MSFT_SPLogLevel/MSFT_SPLogLevel.psm1#L311)):*
> ```PowerShell
>             $mismatchedSettingFound = $true
>         }
> ```

Please remove empty line

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPLogLevel/MSFT_SPLogLevel.psm1, line 322 at r3](https://reviewable.io:443/reviews/powershell/sharepointdsc/685#-Kzd4MvNuwSRfYOf1wh8:-Kzd4MvNuwSRfYOf1wh9:b-38txvj) ([raw file](https://github.com/powershell/sharepointdsc/blob/66ec9e5f44de2ff380ea2714f85527e4830a2d09/Modules/SharePointDsc/DSCResources/MSFT_SPLogLevel/MSFT_SPLogLevel.psm1#L322)):*
> ```PowerShell
>         return $true
>     }
> ```

Please remove empty lines

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPLogLevel/MSFT_SPLogLevel.schema.mof, line 6 at r3](https://reviewable.io:443/reviews/powershell/sharepointdsc/685#-KzdHDFC38w3xKrqI4gN:-KzdHDFC38w3xKrqI4gO:b-xhoxbh) ([raw file](https://github.com/powershell/sharepointdsc/blob/66ec9e5f44de2ff380ea2714f85527e4830a2d09/Modules/SharePointDsc/DSCResources/MSFT_SPLogLevel/MSFT_SPLogLevel.schema.mof#L6)):*
> ```
>     [Key, Description("Log Item Area")] String Area;
>     [Key, Description("Log Item Name")] String Name;
>     [Write, Description("Minimum severity to capture in the trace logs "), ValueMap{"None","Unexpected","Monitorable","Medium","Verbose","VerboseEx","default"}, Values{"None","Unexpected","Monitorable","Medium","Verbose","VerboseEx","default"}] String TraceLevel;
> ```

Is there a reason that you have written default in lowercase?

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPLogLevel/readme.md, line 7 at r3](https://reviewable.io:443/reviews/powershell/sharepointdsc/685#-KzdHRVfSdDw_YSnpcjc:-KzdHRVfSdDw_YSnpcjd:b-wi28h9) ([raw file](https://github.com/powershell/sharepointdsc/blob/66ec9e5f44de2ff380ea2714f85527e4830a2d09/Modules/SharePointDsc/DSCResources/MSFT_SPLogLevel/readme.md#L7)):*
> ```Markdown
> globally for all areas and categories (using the '*' character as the
> wildcard), for all categories within an area, and for specific categories
> within an area. Settings can be change to desired valid valures, or set to the
> ```

change should be changed, valures should be values

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPLogLevel/readme.md, line 9 at r3](https://reviewable.io:443/reviews/powershell/sharepointdsc/685#-KzdHKP0vAHSu53dR1W9:-KzdHKP0vAHSu53dR1WA:b-cyjt03) ([raw file](https://github.com/powershell/sharepointdsc/blob/66ec9e5f44de2ff380ea2714f85527e4830a2d09/Modules/SharePointDsc/DSCResources/MSFT_SPLogLevel/readme.md#L9)):*
> ```Markdown
> within an area. Settings can be change to desired valid valures, or set to the
> default by using the keyword 'default' as the trace level and event level.
> You must specify a unique name for each insance of this resource in a configuration.
> ```

insance should be instance

---

*[Tests/Unit/SharePointDsc/SharePointDsc.SPLogLevel.Tests.ps1, line 3 at r3](https://reviewable.io:443/reviews/powershell/sharepointdsc/685#-KzdHczfHZouLf65R9dF:-KzdHczfHZouLf65R9dG:brqhgkx) ([raw file](https://github.com/powershell/sharepointdsc/blob/66ec9e5f44de2ff380ea2714f85527e4830a2d09/Tests/Unit/SharePointDsc/SharePointDsc.SPLogLevel.Tests.ps1#L3)):*
> ```PowerShell
> [CmdletBinding()]
> param(
>     [Parameter(Mandatory = $false)]
> ```

Please remove the "Mandatory = $false"

---

*[Tests/Unit/SharePointDsc/SharePointDsc.SPLogLevel.Tests.ps1, line 22 at r3](https://reviewable.io:443/reviews/powershell/sharepointdsc/685#-KzdHi18hXFXC--NrQ6l:-KzdHi18hXFXC--NrQ6m:b-1yhxt9) ([raw file](https://github.com/powershell/sharepointdsc/blob/66ec9e5f44de2ff380ea2714f85527e4830a2d09/Tests/Unit/SharePointDsc/SharePointDsc.SPLogLevel.Tests.ps1#L22)):*
> ```PowerShell
> 
>         # Initialize tests
> ```

Please remove empty lines, leaving just one

---

*[Tests/Unit/SharePointDsc/SharePointDsc.SPLogLevel.Tests.ps1, line 41 at r3](https://reviewable.io:443/reviews/powershell/sharepointdsc/685#-Kze_BZWKirTflarHxYn:-Kze_BZWKirTflarHxYo:b-pb4q6m) ([raw file](https://github.com/powershell/sharepointdsc/blob/66ec9e5f44de2ff380ea2714f85527e4830a2d09/Tests/Unit/SharePointDsc/SharePointDsc.SPLogLevel.Tests.ps1#L41)):*
> ```PowerShell
>                 )
>             }
> ```

Please remove empty line

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/685#-:-Kze_SaFqQvz2r7sR4bl:b-4ume5e)*

**Comment by MikeLacher448** [comment]
updated to address all code review comments

**Comment by ykuijs** [comment]
:lgtm:

---

Reviewed 5 of 5 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/685#-:-L-3R2jhhf5PvSuLj8xj:bnfp4nl)*

**Pull request merged**
