### PR TITLE
Bugfix PR

### PR DESCRIPTION
**Pull request by ykuijs**
This PR fixes issues #719, #707, #706, #657, #705

@NikCharlebois, can you please review?

- [X] Change details added to Unreleased section of changelog.md?
- [X] Added/updated documentation and descriptions in .schema.mof files where appropriate?
- [X] Examples updated for both the single server and small farm templates in the examples folder?
- [X] New/changed code adheres to [Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md)?
- [X] [Unit and Integration tests](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md) created/updated where possible?

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/sharepointdsc/734)

### CODE REVIEW

**Comment by NikCharlebois** [comment]
Reviewed 22 of 23 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[.github/ISSUE_TEMPLATE.md, line 11 at r2](https://reviewable.io:443/reviews/powershell/sharepointdsc/734#-L3A97Lqp1FC6ZVlsSvc:-L3A97Lrtkwi0puxyUmF:b-7xegrp) ([raw file](https://github.com/powershell/sharepointdsc/blob/08c01e5d4a5de5594ba8728008af7bba912084ab/.github/ISSUE_TEMPLATE.md#L11)):*
> ```Markdown
> **Version of the Operating System and PowerShell the DSC Target Node is running:**
> 
> **Version of SharePoint that is used:**
> ```

We may want to give specific details about what we are expecting from the users so that we don't end up with something like "Enterprise" instead of the version number (e.g. 2016)

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPSearchAuthoritativePage/readme.md, line 6 at r2](https://reviewable.io:443/reviews/powershell/sharepointdsc/734#-L3ATxCqmyZuzARgmhgb:-L3ATxCqmyZuzARgmhgc:b9fzjfw) ([raw file](https://github.com/powershell/sharepointdsc/blob/08c01e5d4a5de5594ba8728008af7bba912084ab/Modules/SharePointDsc/DSCResources/MSFT_SPSearchAuthoritativePage/readme.md#L6)):*
> ```Markdown
> search service application. You can create new pages, change existing pages and
> remove existing pages.
> ```

Check for comments below about using “when you omit this parameter instead”

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPSearchCrawlerImpactRule/readme.md, line 8 at r2](https://reviewable.io:443/reviews/powershell/sharepointdsc/734#-L3ASWICgMPiz6knLPXh:-L3ASWIDKZNIo_U4MGga:b-8nfnm4) ([raw file](https://github.com/powershell/sharepointdsc/blob/08c01e5d4a5de5594ba8728008af7bba912084ab/Modules/SharePointDsc/DSCResources/MSFT_SPSearchCrawlerImpactRule/readme.md#L8)):*
> ```Markdown
> 
> The default value for the Ensure parameter is Present. When not specifying this
> parameter, the crawl rule is created.
> ```

Just realized that in the resources I submitted in my previous PR, we used “when you omit this parameter” instead. Should we try to standardize our lingo?

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPSearchCrawlMapping/readme.md, line 7 at r2](https://reviewable.io:443/reviews/powershell/sharepointdsc/734#-L3ASpvuouFrL2bThp2_:-L3ASpvvXEon51CkoVw3:b-tnfoeg) ([raw file](https://github.com/powershell/sharepointdsc/blob/08c01e5d4a5de5594ba8728008af7bba912084ab/Modules/SharePointDsc/DSCResources/MSFT_SPSearchCrawlMapping/readme.md#L7)):*
> ```Markdown
> and remove existing mappings.
> 
> The default value for the Ensure parameter is Present. When not specifying this
> ```

Use “Omit” instead

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/734)*

**Comment by NikCharlebois** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[appveyor.yml, line 1 at r2](https://reviewable.io:443/reviews/powershell/sharepointdsc/734#-L3Df9X39LAqBUxuc19L:-L3Df9X39LAqBUxuc19M:b-hmmp2l) ([raw file](https://github.com/powershell/sharepointdsc/blob/08c01e5d4a5de5594ba8728008af7bba912084ab/appveyor.yml#L1)):*
> ```YAML
> version: 2.0.0.{build}
> ```

Don't we want this to be 2.1.0.[build} instead since we are currently planning for the upcoming release?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/734)*

**Comment by ykuijs** [comment]
Ready for final review

---

Review status: 18 of 23 files reviewed at latest revision, 5 unresolved discussions.

---

*[appveyor.yml, line 1 at r2](https://reviewable.io:443/reviews/powershell/sharepointdsc/734#-L3Df9X39LAqBUxuc19L:-L3Eoo8Ia_9S-tIlqqVB:b-896fix) ([raw file](https://github.com/powershell/sharepointdsc/blob/08c01e5d4a5de5594ba8728008af7bba912084ab/appveyor.yml#L1)):*
<details><summary><i>Previously, NikCharlebois (Nik Charlebois) wrote…</i></summary><blockquote>

Don't we want this to be 2.1.0.[build} instead since we are currently planning for the upcoming release?
</blockquote></details>

Done.

---

*[.github/ISSUE_TEMPLATE.md, line 11 at r2](https://reviewable.io:443/reviews/powershell/sharepointdsc/734#-L3A97Lqp1FC6ZVlsSvc:-L3EowCdf3FT7_TGyz2B:b-z2smm2) ([raw file](https://github.com/powershell/sharepointdsc/blob/08c01e5d4a5de5594ba8728008af7bba912084ab/.github/ISSUE_TEMPLATE.md#L11)):*
<details><summary><i>Previously, NikCharlebois (Nik Charlebois) wrote…</i></summary><blockquote>

We may want to give specific details about what we are expecting from the users so that we don't end up with something like "Enterprise" instead of the version number (e.g. 2016)
</blockquote></details>

Good point! Added an example.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPSearchAuthoritativePage/readme.md, line 6 at r2](https://reviewable.io:443/reviews/powershell/sharepointdsc/734#-L3ATxCqmyZuzARgmhgb:-L3EpKH6Aj07odDt-xdQ:b-896fix) ([raw file](https://github.com/powershell/sharepointdsc/blob/08c01e5d4a5de5594ba8728008af7bba912084ab/Modules/SharePointDsc/DSCResources/MSFT_SPSearchAuthoritativePage/readme.md#L6)):*
<details><summary><i>Previously, NikCharlebois (Nik Charlebois) wrote…</i></summary><blockquote>

Check for comments below about using “when you omit this parameter instead”
</blockquote></details>

Done.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPSearchCrawlerImpactRule/readme.md, line 8 at r2](https://reviewable.io:443/reviews/powershell/sharepointdsc/734#-L3ASWICgMPiz6knLPXh:-L3EpS-4qL7Wxi5S8WOf:b-896fix) ([raw file](https://github.com/powershell/sharepointdsc/blob/08c01e5d4a5de5594ba8728008af7bba912084ab/Modules/SharePointDsc/DSCResources/MSFT_SPSearchCrawlerImpactRule/readme.md#L8)):*
<details><summary><i>Previously, NikCharlebois (Nik Charlebois) wrote…</i></summary><blockquote>

Just realized that in the resources I submitted in my previous PR, we used “when you omit this parameter” instead. Should we try to standardize our lingo?
</blockquote></details>

Done.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPSearchCrawlMapping/readme.md, line 7 at r2](https://reviewable.io:443/reviews/powershell/sharepointdsc/734#-L3ASpvuouFrL2bThp2_:-L3EpZAtlyLPCy4erMjM:b-896fix) ([raw file](https://github.com/powershell/sharepointdsc/blob/08c01e5d4a5de5594ba8728008af7bba912084ab/Modules/SharePointDsc/DSCResources/MSFT_SPSearchCrawlMapping/readme.md#L7)):*
<details><summary><i>Previously, NikCharlebois (Nik Charlebois) wrote…</i></summary><blockquote>

Use “Omit” instead
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/734#-:-L3EpuHP5TH29XGisGBY:bsy6x6j)*

**Comment by NikCharlebois** [comment]
:lgtm:

---

Reviewed 5 of 5 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/734#-:-L3T1qzAByKIb0LmvDYZ:bnfp4nl)*

**Pull request merged**
