### PR TITLE
Webapp large list window fix

### PR DESCRIPTION
**Pull request by MikeLacher448**
fix bug with large list windows not being set, Issue 511

- [X] Change details added to Unreleased section of changelog.md?
- [X] Added/updated documentation and descriptions in .schema.mof files where appropriate?
- [X] Examples updated for both the single server and small farm templates in the examples folder?
- [X] New/changed code adheres to [Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md)?
- [X] [Unit and Integration tests](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md) created/updated where possible?

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/sharepointdsc/526)

### CODE REVIEW

**Comment by MikeLacher448** [comment]
the test functions in SPDSC.util didn't seem to work with ciminsance properties.. so I create a hash table with the values just for the test methods... not the most elegant solution, but I could not get anything else to work, and I didn't want to mess with the helper functions. Open to suggestions if you want it addressed differently.

**Comment by BrianFarnhill** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[Modules/SharePointDsc/Modules/SharePointDsc.WebApplication/SPWebApplication.Throttling.psm1, line 140 at r1](https://reviewable.io:443/reviews/powershell/sharepointdsc/526#-Kekj2NIPwQwRo56q72S:-Kekj2NIPwQwRo56q72T:b-aaftlp) ([raw file](https://github.com/powershell/sharepointdsc/blob/4abfde038ef2303106890f401479ab5fc28e2899/Modules/SharePointDsc/Modules/SharePointDsc.WebApplication/SPWebApplication.Throttling.psm1#L140)):*
> ```PowerShell
>     if ($testReturn -eq $true) 
>     {
>         #if ((Test-SPDSCObjectHasProperty $DesiredSettings "HappyHour") -eq $true) 
> ```

Happy with the approach, we can ditch the commented out line here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/526)*

**Comment by MikeLacher448** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[Modules/SharePointDsc/Modules/SharePointDsc.WebApplication/SPWebApplication.Throttling.psm1, line 140 at r1](https://reviewable.io:443/reviews/powershell/sharepointdsc/526#-Kekj2NIPwQwRo56q72S:-KephQdchZHjCPgVT3Ef:b-896fix) ([raw file](https://github.com/powershell/sharepointdsc/blob/4abfde038ef2303106890f401479ab5fc28e2899/Modules/SharePointDsc/Modules/SharePointDsc.WebApplication/SPWebApplication.Throttling.psm1#L140)):*
<details><summary><i>Previously, BrianFarnhill (Brian Farnhill) wrote…</i></summary><blockquote>

Happy with the approach, we can ditch the commented out line here.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/526)*

**Comment by BrianFarnhill** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/526#-:-KfAKefdYpexXCHWpkE_:bnfp4nl)*

**Pull request merged**
