### PR TITLE
Type name in service application resources replaced by GetType Method

### PR DESCRIPTION
**Pull request by luigilink**
Thanks for submitting a Pull Request to this project.

Please make sure you have read the [Contribution Guidelines](https://github.com/powershell/xSharePoint/wiki/Contributing%20to%20xSharePoint).

To aid community reviewers in reviewing and merging your PR, please take the time to run through this checklist:
- [ ] Change details added to Unreleased section of readme.md?
- [x] Added/updated documentation and descriptions in .schema.mof files where appropriate?
- [x] Examples updated for both the single server and small farm templates in the examples folder?
- [x] New/changed code adheres to [Style Guidelines]?(https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md)?
- [x] [Unit and Integration tests](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md) created/updated where possible?

Your contribution to this project is greatly appreciated.

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/sharepointdsc/350)

### CODE REVIEW

**Comment by luigilink** [comment]
Could you give me help on failed test ?
Thanks in advance.

**Comment by BrianFarnhill** [comment]
@luigilink Ping me on skype and we can have a chat about this

**Comment by luigilink** [comment]
@BrianFarnhill Finally, I found a fix for the test with Pester

**Comment by BrianFarnhill** [comment]
What you need to do here is then test for the null value before calling GetType() to make sure you don't hit that null reference exception. Please put the tests back in.

---

Reviewed 1 of 3 files at r3.
Review status: 1 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPServiceInstance/MSFT_SPServiceInstance.schema.mof, line 22 \[r3\]](https://reviewable.io:443/reviews/powershell/sharepointdsc/350#-KLrjoTvWLU2QrxTDiVt:-KLrjoTvWLU2QrxTDiVu:1860604328) ([raw file](https://github.com/powershell/sharepointdsc/blob/ce851f4fcbf7c0f1ae4a25d4d0b6df0f389a0bb6/Modules/SharePointDsc/DSCResources/MSFT_SPServiceInstance/MSFT_SPServiceInstance.schema.mof#L22)):*
> ```
>         InstallAccount = $InstallAccount
>     }
>     
> ```

I want to avoid making a change like this as it would be a breaking change (as all service instances will break as they wont match the names any more). So rather than rely on authors to look up the types, can we move the logic in to the resource that says something along the lines of if Name = "this" then TypeName should equal "that" kind of thing? Does that make sense? My thinking is that from there we can even look at localising it to have the names for each language worked in to there as well at some point. 

---

*[Tests/SharePointDsc/SharePointDsc.SPServiceInstance.Tests.ps1, line 33 \[r3\]](https://reviewable.io:443/reviews/powershell/sharepointdsc/350#-KLrkd_Xe4Z27igFUqff:-KLrkd_Xe4Z27igFUqfg:1217435533) ([raw file](https://github.com/powershell/sharepointdsc/blob/a8db4d98bfa3ef5611eb7b1091f55aa0039558c4/Tests/SharePointDsc/SharePointDsc.SPServiceInstance.Tests.ps1#L33)):*
> ```PowerShell
> 
>         Context "The service instance is not running but should be" {
>             Mock Get-SPServiceInstance { return $null }
> ```

As per my previous comment, please put the tests back in. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/350#-:-KLrlsJk-GhJ8MzqI_Cs:986118168)*

**Comment by luigilink** [comment]
Review status: 0 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[Tests/SharePointDsc/SharePointDsc.SPServiceInstance.Tests.ps1, line 33 \[r3\]](https://reviewable.io:443/reviews/powershell/sharepointdsc/350#-KLrkd_Xe4Z27igFUqff:-KM4GKH3p6JnFhA5U3Hj:1730986369) ([raw file](https://github.com/powershell/sharepointdsc/blob/a8db4d98bfa3ef5611eb7b1091f55aa0039558c4/Tests/SharePointDsc/SharePointDsc.SPServiceInstance.Tests.ps1#L33)):*
<details><summary><i>Previously, BrianFarnhill (Brian Farnhill) wrote…</i></summary>
> As per my previous comment, please put the tests back in. 
</details>
It's done.  Test restored from previous version

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/350)*

**Comment by BrianFarnhill** [comment]
@luigilink I'm still seeing failures in most of the tests - https://ci.appveyor.com/project/PowerShell/sharepointdsc/build/1.1.0.143#L1032 shows the failures. Can you have a look at the logic in the tests and update them to reflect the changes in your code?

**Comment by luigilink** [comment]
Review status: 0 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPServiceInstance/MSFT_SPServiceInstance.schema.mof, line 22 \[r3\]](https://reviewable.io:443/reviews/powershell/sharepointdsc/350#-KLrjoTvWLU2QrxTDiVt:-KMUYZHsa6X-tdP5cHcc:1841025756) ([raw file](https://github.com/powershell/sharepointdsc/blob/ce851f4fcbf7c0f1ae4a25d4d0b6df0f389a0bb6/Modules/SharePointDsc/DSCResources/MSFT_SPServiceInstance/MSFT_SPServiceInstance.schema.mof#L22)):*
<details><summary><i>Previously, BrianFarnhill (Brian Farnhill) wrote…</i></summary>
> I want to avoid making a change like this as it would be a breaking change (as all service instances will break as they wont match the names any more). So rather than rely on authors to look up the types, can we move the logic in to the resource that says something along the lines of if Name = "this" then TypeName should equal "that" kind of thing? Does that make sense? My thinking is that from there we can even look at localising it to have the names for each language worked in to there as well at some point. 
</details>
Backward compatibility assured with new code

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/350)*

**Comment by luigilink** [comment]
Review status: 0 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPServiceInstance/MSFT_SPServiceInstance.schema.mof, line 22 \[r3\]](https://reviewable.io:443/reviews/powershell/sharepointdsc/350#-KLrjoTvWLU2QrxTDiVt:-KMUZFSCAXRzXaXrOCv3:-499146009) ([raw file](https://github.com/powershell/sharepointdsc/blob/ce851f4fcbf7c0f1ae4a25d4d0b6df0f389a0bb6/Modules/SharePointDsc/DSCResources/MSFT_SPServiceInstance/MSFT_SPServiceInstance.schema.mof#L22)):*
<details><summary><i>Previously, luigilink (Jean-Cyril Drouhin) wrote…</i></summary>
> Backward compatibility assured with new code
</details>
Done.

---

*[Tests/SharePointDsc/SharePointDsc.SPServiceInstance.Tests.ps1, line 33 \[r3\]](https://reviewable.io:443/reviews/powershell/sharepointdsc/350#-KLrkd_Xe4Z27igFUqff:-KMUZCbgifsti8JTR7Vb:-499146009) ([raw file](https://github.com/powershell/sharepointdsc/blob/a8db4d98bfa3ef5611eb7b1091f55aa0039558c4/Tests/SharePointDsc/SharePointDsc.SPServiceInstance.Tests.ps1#L33)):*
<details><summary><i>Previously, luigilink (Jean-Cyril Drouhin) wrote…</i></summary>
> It's done.  Test restored from previous version
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/350)*

**Comment by BrianFarnhill** [comment]
Review status: 0 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPServiceInstance/MSFT_SPServiceInstance.schema.mof, line 22 \[r3\]](https://reviewable.io:443/reviews/powershell/sharepointdsc/350#-KLrjoTvWLU2QrxTDiVt:-KMWJDjHoEiSbwP2HRFZ:-665749179) ([raw file](https://github.com/powershell/sharepointdsc/blob/ce851f4fcbf7c0f1ae4a25d4d0b6df0f389a0bb6/Modules/SharePointDsc/DSCResources/MSFT_SPServiceInstance/MSFT_SPServiceInstance.schema.mof#L22)):*
<details><summary><i>Previously, luigilink (Jean-Cyril Drouhin) wrote…</i></summary>
> Done.
</details>
@luigilink I get that the process you have implemented here works for backwards compatability, but you are complicating the documentation by saying "it could be this value or that value", which gets further complicated when we look to implement localisation.  We need to keep to the original values that were passed here and just change how they are looked up within the module like I suggested so we don't shoot ourselves in the feet when we do language specific implementations later on and to keep the documentation simple.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/350)*

**Comment by BrianFarnhill** [comment]
I've made the changes requested here in a separate pull request #385 since this one has gone cold, I didn't want to lose the code though so the fix is in that new PR. Closing this one off.

**Pull request closed without merging**
