### PR TITLE
New SPWebAppAuthentication resource, last breaking change for v2.0

### PR DESCRIPTION
**Pull request by ykuijs**
Implemented fix for issue #538 and removal of SPCreateFarm and SPJoinFarm

- [X] Change details added to Unreleased section of changelog.md?
- [X] Added/updated documentation and descriptions in .schema.mof files where appropriate?
- [X] Examples updated for both the single server and small farm templates in the examples folder?
- [X] New/changed code adheres to [Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md)?
- [X] [Unit and Integration tests](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md) created/updated where possible?

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/sharepointdsc/690)

### CODE REVIEW

**Comment by ykuijs** [comment]
Working on syncing the branch with Dev

**Comment by BrianFarnhill** [comment]
Looks solid, one question from me and then I'm good to go with it

---

Reviewed 19 of 258 files at r1, 14 of 39 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPWebAppAuthentication/readme.md, line 12 at r2](https://reviewable.io:443/reviews/powershell/sharepointdsc/690#-L-hlyFepcsudLOlsWwt:-L-hlyFfeEM8S0h-9lv8:bp1i4wr) ([raw file](https://github.com/powershell/sharepointdsc/blob/61228c80c001622c66514206a994d7df8b666efc/Modules/SharePointDsc/DSCResources/MSFT_SPWebAppAuthentication/readme.md#L12)):*
> ```Markdown
> 
> NOTE 2: Updating the configuration can take a long time. The
> Set-SPWebApplication sometimes requires a very long time to complete its
> ```

Do we want to include some sort of estimate of minutes here to set the expectation?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/690#-:-L-hmeo8B0L6PbPGDkdq:b-n2r9oq)*

**Comment by ykuijs** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPWebAppAuthentication/readme.md, line 12 at r2](https://reviewable.io:443/reviews/powershell/sharepointdsc/690#-L-hlyFepcsudLOlsWwt:-L-hnfNvOanglAmJKvo4:bl2vgj6) ([raw file](https://github.com/powershell/sharepointdsc/blob/61228c80c001622c66514206a994d7df8b666efc/Modules/SharePointDsc/DSCResources/MSFT_SPWebAppAuthentication/readme.md#L12)):*
<details><summary><i>Previously, BrianFarnhill (Brian Farnhill) wrote…</i></summary><blockquote>

Do we want to include some sort of estimate of minutes here to set the expectation?
</blockquote></details>

Not sure, but I can add something like "up to five minutes"

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/690)*

**Comment by BrianFarnhill** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPWebAppAuthentication/readme.md, line 12 at r2](https://reviewable.io:443/reviews/powershell/sharepointdsc/690#-L-hlyFepcsudLOlsWwt:-L-ho-KLd2lk5pmmMYz-:bn2nboq) ([raw file](https://github.com/powershell/sharepointdsc/blob/61228c80c001622c66514206a994d7df8b666efc/Modules/SharePointDsc/DSCResources/MSFT_SPWebAppAuthentication/readme.md#L12)):*
<details><summary><i>Previously, ykuijs (Yorick Kuijs) wrote…</i></summary><blockquote>

Not sure, but I can add something like "up to five minutes"
</blockquote></details>

I feel like if its enough to to warrant putting a warning on there, that we should give an estimate of some sort is all

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/690)*

**Comment by BrianFarnhill** [comment]
:lgtm: Just let the tests run before you merge and I'm good from there!

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/690#-:-L-hpXy7adPt5iK8INXD:b-7rixsp)*

**Comment by ykuijs** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPWebAppAuthentication/readme.md, line 12 at r2](https://reviewable.io:443/reviews/powershell/sharepointdsc/690#-L-hlyFepcsudLOlsWwt:-L-hqV-z0or0Q-6FWHUJ:b-896fix) ([raw file](https://github.com/powershell/sharepointdsc/blob/61228c80c001622c66514206a994d7df8b666efc/Modules/SharePointDsc/DSCResources/MSFT_SPWebAppAuthentication/readme.md#L12)):*
<details><summary><i>Previously, BrianFarnhill (Brian Farnhill) wrote…</i></summary><blockquote>

I feel like if its enough to to warrant putting a warning on there, that we should give an estimate of some sort is all
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/690)*

**Pull request merged**
