### PR TITLE
SPS2013: Accept 2008 R2 and 2012 SQL native client version not only 2008 R2

### PR DESCRIPTION
**Pull request by BrunoReboul**
For SPS2013 prereq, currently, if the SQL native client version is not
exactly 2008 R2 then xSPInstallPrereqs fails. E.g SQL Server 2012 not
accepted

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xsharepoint/305)

### CODE REVIEW

**Comment by BrianFarnhill** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/powershell/xsharepoint/305#-KJIhXPew9MS5zXYeRbZ:-KJIhXPew9MS5zXYeRb_:59867284) (no related file):*
A couple of other things I would like you to do for me to be able to merge this one in:

 - Update CHANGELOG.md listing this fix under the "unreleased" heading
 - Update the unit tests for this resource so we can test that when either version of this is returned that we still get the correct response (email me if you need help on this one)

Once these are done and the below comment is resolved we can close this one off and merge it in. Thanks for submitting this fix! It's a scenario we hadn't accounted for. 

---

*[Modules/SharePointDSC/DSCResources/MSFT_SPInstallPrereqs/MSFT_SPInstallPrereqs.psm1, line 73 \[r1\]](https://reviewable.io:443/reviews/powershell/xsharepoint/305#-KJIai5x_2xenXaiYdu9:-KJIai5x_2xenXaiYduA:-1421567379) ([raw file](https://github.com/powershell/xsharepoint/blob/06c4d165ff29b14c464662e8ec113b09125e9a4a/Modules/SharePointDSC/DSCResources/MSFT_SPInstallPrereqs/MSFT_SPInstallPrereqs.psm1#L73)):*
> ```PowerShell
>     if ($majorVersion -eq 15) {
>         $returnValue.Add("Active Directory Rights Management Services Client 2.*", (($installedItems | ? {$_.Name -like "Active Directory Rights Management Services Client 2.*"}) -ne $null))
>         $returnValue.Add("Microsoft SQL Server x Native Client", (($installedItems | ? {$_.Name -like "Microsoft SQL Server *native*"}) -ne $null))
> ```

Can we change this to check specifically for either 2008 R2 or or 2012 in the check rather than wild carding it?

    $returnValue.Add("Microsoft SQL Server Native Client (2008 R2 or 2012)", (($installedItems | ? { $_.Name -match "SQL Server (2008 R2|2012) Native Client" }) -ne $null))

This will do a regular expression check that will look for either. Since 2014 has no native client (it installs the 2012 native client) this should be a sufficient check

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsharepoint/305)*

**Comment by BrunoReboul** [comment]
Hi Brian,
Requested actions have been done:
- Change log is updated
- Pester unit test have been run with result:
Describing SPInstallPrereqs - SharePoint Build 15.0.4805.1000
   Context Prerequisites are not installed but should be and are to be installed in online mode
    [+] returns absent from the get method 944ms
    [+] returns false from the test method 73ms
    [+] Calls the prerequisite installer from the set method and records the need for a reboot 144ms
    [+] Calls the prerequisite installer from the set method and a pending reboot is preventing it from running 75ms
    [+] Calls the prerequisite installer from the set method and passes a successful installation 78ms
    [+] Calls the prerequisite installer from the set method when the prerequisite installer is already running 117ms
    [+] Calls the prerequisite installer from the set method and invalid arguments are passed to the installer 114ms
    [+] Calls the prerequisite installer from the set method and throws for unknown error codes 51ms
   Context Prerequisites are installed and should be
    [+] returns present from the get method 174ms
    [+] returns true from the test method 82ms
   Context Prerequisites are installed but should not be
    [+] throws an exception from the set method 76ms
    [+] throws an exception from the set method 31ms
   Context Prerequisites are not installed but should be and are to be installed in offline mode
    [+] throws an exception in the set method if required parameters are not set 161ms
    [+] does not throw an exception where the required parameters are included 236ms
   Context Prerequisites are not installed but should be and are to be installed in offline mode, but invalid paths have been
 passed
    [+] throws an exception in the set method if required parameters are not set 76ms
    [+] does not throw an exception where the required parameters are included 39ms
   Context SharePoint 2013 is installing on a server with .NET 4.6
    [+] throws an error in the set method 58ms
   Context Prerequisites are not installed but should be and are to be installed in offline mode, with SXSstore specified
    [+] installs required Windows features from specified path 170ms
    [+] feature install requires a reboot 70ms
    [+] feature install failure throws an error 50ms
Tests completed in 2.83s
Passed: 20 Failed: 0 Skipped: 0 Pending: 0 Inconclusive: 0

**Comment by BrianFarnhill** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/powershell/xsharepoint/305#-KJIhXPew9MS5zXYeRbZ:-KJfD7XS4Wi5rRr3gerO:657277730) (no related file):*
<details><summary><i>Previously, BrianFarnhill (Brian Farnhill) wrote…</i></summary>
> A couple of other things I would like you to do for me to be able to merge this one in:
> 
>  - Update CHANGELOG.md listing this fix under the "unreleased" heading
>  - Update the unit tests for this resource so we can test that when either version of this is returned that we still get the correct response (email me if you need help on this one)
> 
> Once these are done and the below comment is resolved we can close this one off and merge it in. Thanks for submitting this fix! It's a scenario we hadn't accounted for. 
</details>
I can see that the previous tests are running, but we need to update the tests so that we can run a test that ensures we see a pass with either SQL native client version being returned. IM me when you see me online this week and I'll see if I can talk you through it.

---

*[Modules/SharePointDSC/DSCResources/MSFT_SPInstallPrereqs/MSFT_SPInstallPrereqs.psm1, line 73 \[r1\]](https://reviewable.io:443/reviews/powershell/xsharepoint/305#-KJIai5x_2xenXaiYdu9:-KJfD1QYTkQGEWL6laaR:-1839731133) ([raw file](https://github.com/powershell/xsharepoint/blob/06c4d165ff29b14c464662e8ec113b09125e9a4a/Modules/SharePointDSC/DSCResources/MSFT_SPInstallPrereqs/MSFT_SPInstallPrereqs.psm1#L73)):*
<details><summary><i>Previously, BrianFarnhill (Brian Farnhill) wrote…</i></summary>
> Can we change this to check specifically for either 2008 R2 or or 2012 in the check rather than wild carding it?
> 
>     $returnValue.Add("Microsoft SQL Server Native Client (2008 R2 or 2012)", (($installedItems | ? { $_.Name -match "SQL Server (2008 R2|2012) Native Client" }) -ne $null))
> 
> This will do a regular expression check that will look for either. Since 2014 has no native client (it installs the 2012 native client) this should be a sufficient check
</details>
Can you change this line to be the same as my example here so we use a regular expression to check?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsharepoint/305)*

**Comment by BrunoReboul** [comment]
Code updated to accept SQL Native client 2008 R2 or 2012, not any
changelog updated
integration test done
unitary test done

**Comment by BrianFarnhill** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/powershell/sharepointdsc/305#-KJsJgQIKCaeWLtiJh9J:-KJsJgQIKCaeWLtiJh9K:1918266561) (no related file):*
You need to update the unit tests here so that we can validate the logic we have changed here. Currently if you have a look at [SharePointDsc.SPInstallPrereqs.Tests.ps1](https://github.com/PowerShell/SharePointDsc/blob/dev/Tests/SharePointDsc/SharePointDsc.SPInstallPrereqs.Tests.ps1#L128) you'll see that we currently simulate returning the 2008 native client. You need to drop the below set of tests in beneath the one I've linked to above as this one will run that simulation again but this has the 2012 client specified for the SP2013 check. Does that make sense?

    Context "Prerequisites are installed and should be (with SQL 2012 native client for SP2013)" {
            $testParams = @{
                InstallerPath = "C:\SPInstall"
                OnlineMode = $true
                Ensure = "Present"
            }
            
            Mock Get-WindowsFeature { @( @{ Name = "ExampleFeature"; Installed = $true }) }
            if ($majorBuildNumber -eq 15) {
                Mock Get-CimInstance { return @(
                    @{ Name = "Microsoft CCR and DSS Runtime 2008 R3"}
                    @{ Name = "Microsoft Sync Framework Runtime v1.0 SP1 (x64)"}
                    @{ Name = "AppFabric 1.1 for Windows Server"}
                    @{ Name = "WCF Data Services 5.6.0 Runtime"}
                    @{ Name = "WCF Data Services 5.0 (for OData v3) Primary Components"}
                    @{ Name = "Microsoft SQL Server 2012 Native Client"}
                    @{ Name = "Active Directory Rights Management Services Client 2.0"}
                )}
            }
            if ($majorBuildNumber -eq 16) {
                Mock Get-CimInstance { return @(
                    @{ Name = "Microsoft CCR and DSS Runtime 2008 R3"}
                    @{ Name = "Microsoft Sync Framework Runtime v1.0 SP1 (x64)"}
                    @{ Name = "AppFabric 1.1 for Windows Server"}
                    @{ Name = "WCF Data Services 5.6.0 Runtime"}
                    @{ Name = "Microsoft ODBC Driver 11 for SQL Server"}
                    @{ Name = "Microsoft Visual C++ 2012 x64 Minimum Runtime - 11.0.61030"}
                    @{ Name = "Microsoft Visual C++ 2012 x64 Additional Runtime - 11.0.61030"}
                    @{ Name = "Microsoft Visual C++ 2015 x64 Minimum Runtime - 14.0.23026"}
                    @{ Name = "Microsoft Visual C++ 2015 x64 Additional Runtime - 14.0.23026"}
                    @{ Name = "Microsoft SQL Server 2012 Native Client"}
                    @{ Name = "Active Directory Rights Management Services Client 2.1"}
                )}
            }
            Mock Get-ChildItem { return $null }
            Mock Get-ChildItem { return @(
                (New-Object Object | 
                    Add-Member ScriptMethod GetValue { return "Microsoft Identity Extensions" } -PassThru)
            ) }
            
            It "returns present from the get method" {
                (Get-TargetResource @testParams).Ensure | Should Be "Present"
            }

            It "returns true from the test method" {
                Test-TargetResource @testParams | Should Be $true
            }
        }

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/305)*

**Comment by BrianFarnhill** [comment]
@BrunoReboul You'll also need to do a pull from PowerShell/dev to resolve the merge conflicts here now. If you run this at the git command line it will do the pull and tell you which files have merge conflicts that you need to resolve. Open those files to resolve the conflicts (it's usually the CHANGELOG.md file, so just make sure that all the appropriate values are in it) and then commit back here with the merged fixes.

    cd [path to your local repo]
    git pull https://github.com/PowerShell/SharePointDsc.git dev

**Comment by BrunoReboul** [comment]
Unit test updated as proposed to deal with SQL 2012 scenario
Pull from PowerShell dev done too

**Comment by BrianFarnhill** [comment]
Reviewed 3 of 4 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/305)*

**Pull request merged**
