### PR TITLE
Updated documentation on remote installation

### PR DESCRIPTION
**Pull request by BrianFarnhill**
Updated documentation in regards to supported scenarios for installation of binaries from network locations. The short version is it's doable, but only at the expense of security, so I wanted to capture that and make it clear in the documentation.

- [X] Change details added to Unreleased section of changelog.md?
- [X] Added/updated documentation and descriptions in .schema.mof files where appropriate?
- [X] Examples updated for both the single server and small farm templates in the examples folder?
- [X] New/changed code adheres to [Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md)?
- [X] [Unit and Integration tests](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md) created/updated where possible?

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/sharepointdsc/473)

### CODE REVIEW

**Comment by ykuijs** [comment]
Reviewed 2 of 3 files at r1.
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPInstall/Readme.md, line 11 at r1](https://reviewable.io:443/reviews/powershell/sharepointdsc/473#-KYxBWpVWzE2AsRoCWxE:-KYxBWpVWzE2AsRoCWxF:bd1r6bh) ([raw file](https://github.com/powershell/sharepointdsc/blob/f505c0492a10c3e8c1db7ff5032000fe5f4cf3b4/Modules/SharePointDsc/DSCResources/MSFT_SPInstall/Readme.md#L11)):*
> ```Markdown
> ## Installing from network locations
> 
> If you wish to install the prerequisites from a network location this can
> ```

"prerequisites" should be "SharePoint"

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/473)*

**Comment by BrianFarnhill** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPInstall/Readme.md, line 11 at r1](https://reviewable.io:443/reviews/powershell/sharepointdsc/473#-KYxBWpVWzE2AsRoCWxE:-KYz6OEReaX8hObkLi_t:b-3dl2o7) ([raw file](https://github.com/powershell/sharepointdsc/blob/f505c0492a10c3e8c1db7ff5032000fe5f4cf3b4/Modules/SharePointDsc/DSCResources/MSFT_SPInstall/Readme.md#L11)):*
<details><summary><i>Previously, ykuijs (Yorick Kuijs) wrote…</i></summary><blockquote>

"prerequisites" should be "SharePoint"
</blockquote></details>

And this is why we code review. Nice catch mate, I've updated it. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/473)*

**Comment by ykuijs** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPInstall/Readme.md, line 11 at r2](https://reviewable.io:443/reviews/powershell/sharepointdsc/473#-KYz83eEM1GyG3JeiUwP:-KYz83eFydfIbuMjFcdd:b-c9li3r) ([raw file](https://github.com/powershell/sharepointdsc/blob/a89ca530896ebc88a2e8b57c9680bec63d6993b6/Modules/SharePointDsc/DSCResources/MSFT_SPInstall/Readme.md#L11)):*
> ```Markdown
> ## Installing from network locations
> 
> If you wish to install the SharePoint from a network location this can
> ```

Now I am being really picky: "the" should also be removed in front of "the SharePoint" :-)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/473)*

**Comment by BrianFarnhill** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPInstall/Readme.md, line 11 at r2](https://reviewable.io:443/reviews/powershell/sharepointdsc/473#-KYz83eEM1GyG3JeiUwP:-KYz91v42N8lSSGv5sYj:blmzb5d) ([raw file](https://github.com/powershell/sharepointdsc/blob/a89ca530896ebc88a2e8b57c9680bec63d6993b6/Modules/SharePointDsc/DSCResources/MSFT_SPInstall/Readme.md#L11)):*
<details><summary><i>Previously, ykuijs (Yorick Kuijs) wrote…</i></summary><blockquote>

Now I am being really picky: "the" should also be removed in front of "the SharePoint" :-)
</blockquote></details>

I had that one coming, all fixed :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/473)*

**Comment by ykuijs** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/473#-:-KYzGhczK6bi3SHsrqpR:bnfp4nl)*

**Pull request merged**
