### PR TITLE
Removed Win32_Product from SPInstallPrereqs

### LINKED ISSUE #293: Remove dependency on Win32_Product in SPInstallPrereqs
**Details of the scenario you try and problem that is occurring:**

Currently the SPInstallPrereqs resource depends on the Win32_Product class to determine what is installed and what isn't. As per [this article](https://blogs.technet.microsoft.com/heyscriptingguy/2011/11/13/use-powershell-to-quickly-find-installed-software/) this query isn't optimised and can trigger some additional consistency checks, which should be avoided. All the checks in the get method for this resource should therefore use alternative approaches to determine what is installed and what isn't (either registry or file system checks)

**The DSC configuration that is using the resource:**

SPInstallPrereqs

**Version of the Operating System and PowerShell the DSC Target Node is running:**

n/a

**Version of the DSC module you're using:**

0.12 (but issue has existed since the very beginning at 0.2)

### PR DESCRIPTION
**Pull request by BrianFarnhill**
Fixes #293 and is a cleaned up version of #341 as discussed in the comments there

@ykuijs all yours to review mate

- [X] Change details added to Unreleased section of readme.md?
- [n/a] Added/updated documentation and descriptions in .schema.mof files where appropriate?
- [n/a] Examples updated for both the single server and small farm templates in the examples folder?
- [X] New/changed code adheres to [Style Guidelines]?(https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md)?
- [X] [Unit and Integration tests](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md) created/updated where possible?

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/sharepointdsc/343)

### CODE REVIEW

**Comment by luigilink** [comment]
The x86Path variable refers to Wow6432 node and the x64Path refers to currentVersion, is it the right way ?
```
$x86Path = "HKLM:\Software\Wow6432Node\Microsoft\Windows\CurrentVersion\Uninstall\*"
$x64Path = "HKLM:\Software\Microsoft\Windows\CurrentVersion\Uninstall\*"
```
What do you think of the -Unique parameter to avoid dupicates entires :
` $installedItemsX64 = Get-ItemProperty -Path $x64Path | Select-Object -Property DisplayName **-Unique**`

**Comment by ykuijs** [comment]
The regkeys are correct. Wow6432 is the 32 bit section of the registry (even though the naming can be confusing :-)

---

Reviewed 2 of 3 files at r1.
Review status: 2 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPInstallPrereqs/MSFT_SPInstallPrereqs.psm1, line 169 \[r1\]](https://reviewable.io:443/reviews/powershell/sharepointdsc/343#-KKyPRT3RLWiOwG0bLIZ:-KKyPRT3RLWiOwG0bLI_:-426136823) ([raw file](https://github.com/powershell/sharepointdsc/blob/913701f65fa456f68a5d5ace9bf9e3d11d4da88a/Modules/SharePointDsc/DSCResources/MSFT_SPInstallPrereqs/MSFT_SPInstallPrereqs.psm1#L169)):*
> ```PowerShell
>         else 
>         {
>             # Server 2012 R2
> ```

Shouldn't we check if Windows 2012 R2 is really used and throw an error if it isn't??

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPInstallPrereqs/MSFT_SPInstallPrereqs.psm1, line 453 \[r1\]](https://reviewable.io:443/reviews/powershell/sharepointdsc/343#-KKyRdOHy2bi8X7iWLkZ:-KKyRdOLGEukEYBDKzIz:-426136823) ([raw file](https://github.com/powershell/sharepointdsc/blob/913701f65fa456f68a5d5ace9bf9e3d11d4da88a/Modules/SharePointDsc/DSCResources/MSFT_SPInstallPrereqs/MSFT_SPInstallPrereqs.psm1#L453)):*
> ```PowerShell
>         else 
>         {
>             # Server 2012 R2
> ```

Shouldn't we check if Windows 2012 R2 is really used and throw an error if it isn't??

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/343#-:-KKyOlWi9W5HymeyZerh:-956211000)*

**Comment by BrianFarnhill** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPInstallPrereqs/MSFT_SPInstallPrereqs.psm1, line 169 \[r1\]](https://reviewable.io:443/reviews/powershell/sharepointdsc/343#-KKyPRT3RLWiOwG0bLIZ:-KL-YUTnpWeYQ5zdmbtk:-499146009) ([raw file](https://github.com/powershell/sharepointdsc/blob/913701f65fa456f68a5d5ace9bf9e3d11d4da88a/Modules/SharePointDsc/DSCResources/MSFT_SPInstallPrereqs/MSFT_SPInstallPrereqs.psm1#L169)):*
<details><summary><i>Previously, ykuijs (Yorick Kuijs) wrote…</i></summary>
> Shouldn't we check if Windows 2012 R2 is really used and throw an error if it isn't??
</details>
Done.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPInstallPrereqs/MSFT_SPInstallPrereqs.psm1, line 453 \[r1\]](https://reviewable.io:443/reviews/powershell/sharepointdsc/343#-KKyRdOHy2bi8X7iWLkZ:-KL-YW3d8s0-Q4pfcQbJ:-499146009) ([raw file](https://github.com/powershell/sharepointdsc/blob/913701f65fa456f68a5d5ace9bf9e3d11d4da88a/Modules/SharePointDsc/DSCResources/MSFT_SPInstallPrereqs/MSFT_SPInstallPrereqs.psm1#L453)):*
<details><summary><i>Previously, ykuijs (Yorick Kuijs) wrote…</i></summary>
> Shouldn't we check if Windows 2012 R2 is really used and throw an error if it isn't??
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/343)*

**Comment by BrianFarnhill** [comment]
@ykuijs Changes made - can you confirm you're happy for this to merge?

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/343#-:-KL-Y_wInz0CKI8S7X6v:-1082699094)*

**Comment by ykuijs** [comment]
Reviewed 4 of 4 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/343)*

**Pull request merged**
