### PR TITLE
New SPOfficeOnlineServerBinding resource

### LINKED ISSUE #212: Add xSPOfficeWebAppsBinding resource
We need to add a resource that will allow for setting the bindings to Office web apps server. The resource will initially just be focused around setting a single binding for all types and will add support to narrow a binding to an application type later. The first cut of the resource should look something like this:

xSPOfficeWebAppsBinding OWABinding
{
    ServerName = "webapps.contoso.com"
    AllowHTTP = $false
    Ensure = "Present"
    Zone = "internal-https"
}

### PR DESCRIPTION
**Pull request by BrianFarnhill**
Fixes #212 

This new resource adds the ability to connect a farm to an Office Online Server 2016/Office Web Apps 2013 farm.

- [X] Change details added to Unreleased section of readme.md?
- [X] Added/updated documentation and descriptions in .schema.mof files where appropriate?
- [X] Examples updated for both the single server and small farm templates in the examples folder?
- [X] New/changed code adheres to [Style Guidelines]?(https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md)?
- [X] [Unit and Integration tests](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md) created/updated where possible?

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xsharepoint/317)

### CODE REVIEW

**Comment by ykuijs** [comment]
One type and one comment. The rest looks fine

<details><summary><i>Previously, BrianFarnhill (Brian Farnhill) wrote…</i></summary>
> #### New SPOfficeOnlineServerBinding resource
> 
> Fixes #212 
> 
> 
> 
> This new resource adds the ability to connect a farm to an Office Online Server 2016/Office Web Apps 2013 farm.
> 
> 
> 
> - [X] Change details added to Unreleased section of readme.md?
> 
> - [X] Added/updated documentation and descriptions in .schema.mof files where appropriate?
> 
> - [X] Examples updated for both the single server and small farm templates in the examples folder?
> 
> - [X] New/changed code adheres to [Style Guidelines]?(https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md)?
> 
> - [X] [Unit and Integration tests](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md) created/updated where possible?
> 
> 
> 
</details>


---

Review status: 0 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPOfficeOnlineServerBinding/MSFT_SPOfficeOnlineServerBinding.psm1, line 55 \[r1\]](https://reviewable.io:443/reviews/powershell/xsharepoint/317#-KJewEujJgAtaph4SBOA:-KJewEujJgAtaph4SBOB:-365980041) ([raw file](https://github.com/powershell/xsharepoint/blob/ca56b62b40f59751289f3be80212e0dc452bb304/Modules/SharePointDsc/DSCResources/MSFT_SPOfficeOnlineServerBinding/MSFT_SPOfficeOnlineServerBinding.psm1#L55)):*
> ```PowerShell
> 
>     if ($Ensure -eq "Present") { 
>         if ($DnsName -ne $CurrentResults.DnsNzme) {
> ```

Typo in variable name DnsNzme should be DnsName

What if the DnsName is equal, but you want to change the WOPIZone. This situation is not possible in the current code.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsharepoint/317#-:-KJex9US4EMyvIlP21Py:-831216068)*

**Comment by ykuijs** [comment]
Still not familiar with the inner workings of Reviewable :-)

<details><summary><i>Previously, ykuijs (Yorick Kuijs) wrote…</i></summary>
> One type and one comment. The rest looks fine
</details>


---

Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsharepoint/317#-:-KJexjQGTHXDoopSukCH:-2060880939)*

**Comment by BrianFarnhill** [comment]
@ykuijs Looks like reviewable lost this one because of the repo rename. I've made the change based on your comments though, let me know what you think

**Comment by ykuijs** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsharepoint/317)*

**Pull request merged**
