### PR TITLE
Release 1.9

### PR DESCRIPTION
**Pull request by ykuijs**
@kwirkykat v1.9 is ready to be included in your next wave

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/sharepointdsc/652)

### CODE REVIEW

**Comment by BrianFarnhill** [comment]
@ykuijs Wanna look at those tests mate?

**Comment by BrianFarnhill** [comment]
@ykuijs Looks like someone accidently checked in the DscResources.Tests folder - get it removed and you should be fine :)

**Comment by ykuijs** [comment]
Issue caused by a change in the DscResource.Tests repo. Investigating the issue.

**Comment by BrianFarnhill** [comment]
@ykuijs Can you drop the fix to the test harness back in to the dev branch as well?

**Comment by ykuijs** [comment]
Issue resolved, ready for merge into Master

**Pull request merged**
