### PR TITLE
xSPUserProfileSyncService Remove Status field from Get-TargetResource

### PR DESCRIPTION
**Pull request by BrunoReboul**
Proposed Fix :
xSPUserProfileSyncService Remove Status field from Get-TargResource: not
in MOF, redundant with Ensure

Change log updated

Pester unit test has been run:
Describing SPUserProfileSyncService - SharePoint Build 15.0.4805.1000
   Context User profile sync service is not found locally
    [+] returns absent from the get method 970ms
   Context User profile sync service is not running and should be
    [+] returns absent from the get method 146ms
    [+] returns false from the test method 61ms
    [+] calls the start service cmdlet from the set method 253ms
    [+] returns values from the get method where the farm account doesn't match 59ms
    [+] throws in the set method if the user profile service app can't be found 81ms
   Context User profile sync service is running and should be
    [+] returns present from the get method 79ms
    [+] returns true from the test method 38ms
   Context User profile sync service is running and shouldn't be
    [+] returns present from the get method 77ms
    [+] returns false from the test method 31ms
    [+] calls the start service cmdlet from the set method 62ms
   Context User profile sync service is not running and shouldn't be
    [+] returns absent from the get method 75ms
    [+] returns true from the test method 32ms
Tests completed in 1.97s
Passed: 13 Failed: 0 Skipped: 0 Pending: 0 Inconclusive: 0

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xsharepoint/318)

### CODE REVIEW

**Comment by BrianFarnhill** [comment]
You don't need to paste the test results in here, we will see them. What we do normally need is the tests to be updated so that they reflect the change to show that logic still works. In this specific case, I don't think the tests need to change so its fine.

Also you need to follow the link above for the CLA to be signed electronically before I can accept this change in as well.

<details><summary><i>Previously, msftclas (Microsoft Contribution License Agreements) wrote…</i></summary>
> Hi __@BrunoReboul__, I'm your friendly neighborhood Microsoft Pull Request Bot (You can call me MSBOT). Thanks for your contribution!
> 
>     <span>
> 
>         In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.microsoft.com.
> 
>     </span>
> 
> 
> 
> TTYL, MSBOT;
> 
> 
</details>


---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[CHANGELOG.md, line 5 \[r1\]](https://reviewable.io:443/reviews/powershell/xsharepoint/318#-KJfFYdXmjKVe7yvtak-:-KJfFYdY5FtLK3fHS9TT:-29985202) ([raw file](https://github.com/powershell/xsharepoint/blob/2241f707526575694d9cf1390f63d94a56684c32/CHANGELOG.md#L5)):*
> ```Markdown
> ### Unreleased
> 
>  * xSPUserProfileSyncService Remove Status field from Get-TargResource: not in MOF, redundant with Ensure
> ```

Can you change the wording here:

    * Removed redundant "status" value in return of SPUserProfileSyncService

---

*[Modules/SharePointDSC/DSCResources/MSFT_SPUserProfileSyncService/MSFT_SPUserProfileSyncService.psm1, line 55 \[r1\]](https://reviewable.io:443/reviews/powershell/xsharepoint/318#-KJfFsVGTanXXqiNFQVt:-KJfFsVGTanXXqiNFQVu:-495919090) ([raw file](https://github.com/powershell/xsharepoint/blob/2241f707526575694d9cf1390f63d94a56684c32/Modules/SharePointDSC/DSCResources/MSFT_SPUserProfileSyncService/MSFT_SPUserProfileSyncService.psm1#L55)):*
> ```PowerShell
>             InstallAccount = $params.InstallAccount
>  # Remove Status as 1) not defined in mof file 2) is redundant with Ensure
>  #           Status = $syncService.Status
> ```

Can you please just remove the status property all together, not just comment it out.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsharepoint/318#-:-KJfF3dBHBEqjh-OTNLT:-1167375127)*

**Comment by BrunoReboul** [comment]
Hi Brian,
CLA signed
Status removed instead of comment it

**Comment by BrianFarnhill** [comment]
Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/powershell/sharepointdsc/318#-KJsL_t3mgH3b6Nuclbp:-KJsL_t4FrDRtWz4Bglh:-219141313) (no related file):*
This is ready to go but you need to resolve the merge conflicts here. See my comments on [your other pull request](https://github.com/PowerShell/SharePointDsc/pull/305) for how to do this. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/318)*

**Comment by BrunoReboul** [comment]
pull from PowerShell dev done

**Comment by BrianFarnhill** [comment]
@BrunoReboul One last merge to resolve (suspect after I merged your last PR the changelog needs a look at again)

**Comment by BrunoReboul** [comment]
yep, changelog.md conflict resolved
Merge from PowerShell dev done
Push to origin done

**Comment by BrianFarnhill** [comment]
Reviewed 1 of 3 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/318)*

**Pull request merged**
