### PR TITLE
fixed typos in SPJoinFarm and SPServiceAppProxyGroup

### PR DESCRIPTION
**Pull request by MikeLacher448**
Fixing typo within SPServiceAppProxyGroup resource
Fixing comparison operator in SPJoinFarm resource (issue #381)

- [X] Change details added to Unreleased section of changelog.md?
- [ ] Added/updated documentation and descriptions in .schema.mof files where appropriate?
- [ ] Examples updated for both the single server and small farm templates in the examples folder?
- [X] New/changed code adheres to [Style Guidelines]?(https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md)?
- [ ] [Unit and Integration tests](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md) created/updated where possible?

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/sharepointdsc/392)

### CODE REVIEW

**Comment by MikeLacher448** [comment]
not sure why this is failing the AppVeyor checks, I can't see any details?

**Comment by ykuijs** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/392#-:-KPbj0_JkeJxGFDAO0FM:bnfp4nl)*

**Comment by ykuijs** [comment]
Not sure why the Appveyor test is failing, I can't see a cause either. @BrianFarnhill Do you see more details?

**Comment by BrianFarnhill** [comment]
No idea, will review it without it though. 

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPJoinFarm/MSFT_SPJoinFarm.psm1, line 175 \[r1\]](https://reviewable.io:443/reviews/powershell/sharepointdsc/392#-KPj42Pmjnu0cIyCxt6J:-KPj42Pmjnu0cIyCxt6K:b-76q3k8) ([raw file](https://github.com/powershell/sharepointdsc/blob/351b21930e444cc6f41c9907ba559d798f237cce/Modules/SharePointDsc/DSCResources/MSFT_SPJoinFarm/MSFT_SPJoinFarm.psm1#L175)):*
> ```PowerShell
>     }
> 
>     if ($null -eq $result)
> ```

Why did you switch this? The only time we can see a value return from the above statement is when there is an error (see the return line in the catch block)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/392#-:-KPj3xgsy_D-JoiViaI4:bt2tff8)*

**Comment by MikeLacher448** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPJoinFarm/MSFT_SPJoinFarm.psm1, line 175 \[r1\]](https://reviewable.io:443/reviews/powershell/sharepointdsc/392#-KPj42Pmjnu0cIyCxt6J:-KPmJPSOo_4SW1kKixKv:b-pa5mcn) ([raw file](https://github.com/powershell/sharepointdsc/blob/351b21930e444cc6f41c9907ba559d798f237cce/Modules/SharePointDsc/DSCResources/MSFT_SPJoinFarm/MSFT_SPJoinFarm.psm1#L175)):*
<details><summary><i>Previously, BrianFarnhill (Brian Farnhill) wrote…</i></summary>
> Why did you switch this? The only time we can see a value return from the above statement is when there is an error (see the return line in the catch block)
</details>
I see, I was thinking that Connect-SPConfiguration database would return a farm object if successful, and that receiving nothing was the error state.

I do believe I found the culprit, Install-SPFeature outputs an object. Updating the script to redirect that to out-null, and will perform a final test in my lab before committing. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/392)*

**Comment by BrianFarnhill** [comment]
Reviewed 1 of 3 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/392)*

**Pull request merged**
