### PR TITLE
SPDistributedCacheService: Stop-SPServiceInstance may throw an exception in SharePoint 2019

### PR DESCRIPTION
**Pull request by Yvand**
#### Pull Request (PR) description

This PR updates resource SPDistributedCacheService to avoid exception on Stop-SPServiceInstance with SharePoint 2019.

#### This Pull Request (PR) fixes the following issues

- https://github.com/PowerShell/SharePointDsc/issues/995: Resource SPDistributedCacheService throws an error when it configures the service for the 1st time. If I run the DSC configuration again on the server there is no error.

#### Task list

- [x] Added an entry under the Unreleased section of the change log in the CHANGELOG.md.
      Entry should say what was changed, and how that affects users (if applicable).
- [ ] Resource documentation added/updated in README.md in the resource folder.
- [ ] Resource parameter descriptions added/updated in schema.mof
      and comment-based help.
- [ ] Comment-based help added/updated.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [ ] Examples appropriately added/updated.
- [ ] Unit tests added/updated. See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] Integration tests added/updated (where possible). See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/sharepointdsc/997)

### CODE REVIEW

**Comment by Yvand** [comment]
Today I made new tests and realized the issue is still present, the solution I proposed does not solve it, I need to investigate this more...

**Comment by ykuijs** [comment]
@Yvand I'll leave the PR open for now, so you can just submit any further updates. Please let me know when it is ready for review!

**Comment by ykuijs** [comment]
Posting another update to remove the Abandoned state set by the GitHub bot.

@Yvand Any update?

**Comment by Yvand** [comment]
@ykuijs Yes, sorry for the late reply.
I found that ProcessIdentity.Deploy() may also throw an exception:
https://github.com/PowerShell/SharePointDsc/blob/3844111e1e98c1aa4483f4251845425264af8434/Modules/SharePointDsc/DSCResources/MSFT_SPDistributedCacheService/MSFT_SPDistributedCacheService.psm1#L312

What is painful is that it does not always fail, and I don't why it's so random...
I will update the PR with a try/catch around ProcessIdentity.Deploy() and continue my tests

**Comment by ykuijs** [comment]
Great, let me know when you are ready for a review!

**Comment by Yvand** [comment]
I confirm that, sometimes, ProcessIdentity.Deploy() may also throw the exact same exception as the Stop-SPServiceInstance cmdlet:

```
[[SPDistributedCacheService]EnableDistributedCache] Executing using a provided 
credential and local PSSession as user contoso\spsetup
VERBOSE: [2019-01-09 12:36:02Z] [VERBOSE] [SP]:                            
[[SPDistributedCacheService]EnableDistributedCache] Enabling distributed cache 
service
VERBOSE: [2019-01-09 12:44:47Z] [ERROR] Exception calling "Deploy" with "0" 
argument(s): "Error occurred while performing the operation on host SP:22233 : 
ErrorCode<ERRCAdmin016>:SubStatus<ES0001>:Host is not running in cluster."
VERBOSE: [2019-01-09 12:44:48Z] Settings handler status to 'transitioning' 
(C:\Packages\Plugins\Microsoft.Powershell.DSC\2.77.0.0\Status\0.status)
VERBOSE: [2019-01-09 12:44:48Z] [VERBOSE] [SP]: LCM:  [ End    Set      ]  
[[SPDistributedCacheService]EnableDistributedCache]  in 543.1870 seconds.
VERBOSE: [2019-01-09 12:44:48Z] [ERROR] The PowerShell DSC resource 
'[SPDistributedCacheService]EnableDistributedCache' with SourceInfo 
'C:\Packages\Plugins\Microsoft.Powershell.DSC\2.77.0.0\DSCWork\ConfigureSPVM.0\
ConfigureSPVM.ps1::425::9::SPDistributedCacheService' threw one or more 
```

Let me recap:

* This always fails in SharePoint 2019 if the service is not already started:

https://github.com/PowerShell/SharePointDsc/blob/3844111e1e98c1aa4483f4251845425264af8434/Modules/SharePointDsc/DSCResources/MSFT_SPDistributedCacheService/MSFT_SPDistributedCacheService.psm1#L249-L251

* This randomly* fails in SharePoint 2019 if the service is not already started:

https://github.com/PowerShell/SharePointDsc/blob/3844111e1e98c1aa4483f4251845425264af8434/Modules/SharePointDsc/DSCResources/MSFT_SPDistributedCacheService/MSFT_SPDistributedCacheService.psm1#L312

*: According to my tests, it seems to fail 1 time every 5-6 strictly similar deployments (new VM each time).

I propose to fix/hide both by surrounding them with try/catch statements.
@ykuijs This PR is ready for review, thanks!

**Comment by ykuijs** [comment]
If they only fail when the service isn't already started, doesn't it make more sense to add a check to make sure the service is actually started? And if not, don't run the code.

**Comment by Yvand** [comment]
For the scenario 1: Just before, the module runs [Add-SPDistributedCacheServiceInstance](https://docs.microsoft.com/en-us/powershell/module/sharepoint-server/add-spdistributedcacheserviceinstance?view=sharepoint-ps).
Assuming this cmdlet starts the service on the local server, then the service is started when we stop it.

For the scenario 2: the module runs Start-SPServiceInstance and does wait until status is "Online", so service is actually started when it reaches ProcessIdentity.Deploy()

So either the error "ErrorCode<ERRCAdmin016>:SubStatus<ES0001>:Host is not running in cluster" is misleading on the actual cause, or I missed something

**Pull request merged**
