### PR TITLE
New resource SPSearchFileType

### PR DESCRIPTION
**Pull request by ykuijs**
New resource SPSearchFileType #30 

- [X] Change details added to Unreleased section of changelog.md?
- [X] Added/updated documentation and descriptions in .schema.mof files where appropriate?
- [X] Examples updated for both the single server and small farm templates in the examples folder?
- [X] New/changed code adheres to [Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md)?
- [X] [Unit and Integration tests](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md) created/updated where possible?

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/sharepointdsc/466)

### CODE REVIEW

**Comment by BrianFarnhill** [comment]
Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[Modules/SharePointDsc/Examples/Resources/SPSearchFileType/1-RequiredParameters.ps1, line 3 at r1](https://reviewable.io:443/reviews/powershell/sharepointdsc/466#-KYBjrAmLTywgrap6DgT:-KYBjrAmLTywgrap6DgU:b-cy4ldj) ([raw file](https://github.com/powershell/sharepointdsc/blob/2115e40d4c7160e2bcc46645da319514b2fde892/Modules/SharePointDsc/Examples/Resources/SPSearchFileType/1-RequiredParameters.ps1#L3)):*
> ```PowerShell
> <#
> .EXAMPLE
>     This example shows how to apply settings to a sepcific URL in search
> ```

Did you update the text for this? Looks like its one of the old ones still - also does the file name match the scenario here?

---

*[Modules/SharePointDsc/Examples/Resources/SPSearchFileType/2-AllParameters.ps1, line 3 at r1](https://reviewable.io:443/reviews/powershell/sharepointdsc/466#-KYBjz8vfVF-6hVk0R78:-KYBjz8vfVF-6hVk0R79:b-tloa01) ([raw file](https://github.com/powershell/sharepointdsc/blob/2115e40d4c7160e2bcc46645da319514b2fde892/Modules/SharePointDsc/Examples/Resources/SPSearchFileType/2-AllParameters.ps1#L3)):*
> ```PowerShell
> <#
> .EXAMPLE
>     This example shows how to set a certificate for authentication to a content source
> ```

Same about this comment and filename too

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/466)*

**Comment by ykuijs** [comment]
Review status: 5 of 7 files reviewed at latest revision, 2 unresolved discussions.

---

*[Modules/SharePointDsc/Examples/Resources/SPSearchFileType/1-RequiredParameters.ps1, line 3 at r1](https://reviewable.io:443/reviews/powershell/sharepointdsc/466#-KYBjrAmLTywgrap6DgT:-KYJLjh69QHFzZ5LFUaI:b-896fix) ([raw file](https://github.com/powershell/sharepointdsc/blob/2115e40d4c7160e2bcc46645da319514b2fde892/Modules/SharePointDsc/Examples/Resources/SPSearchFileType/1-RequiredParameters.ps1#L3)):*
<details><summary><i>Previously, BrianFarnhill (Brian Farnhill) wrote…</i></summary><blockquote>

Did you update the text for this? Looks like its one of the old ones still - also does the file name match the scenario here?
</blockquote></details>

Done.

---

*[Modules/SharePointDsc/Examples/Resources/SPSearchFileType/2-AllParameters.ps1, line 3 at r1](https://reviewable.io:443/reviews/powershell/sharepointdsc/466#-KYBjz8vfVF-6hVk0R78:-KYJLkQz65rHCUTAObsw:b-896fix) ([raw file](https://github.com/powershell/sharepointdsc/blob/2115e40d4c7160e2bcc46645da319514b2fde892/Modules/SharePointDsc/Examples/Resources/SPSearchFileType/2-AllParameters.ps1#L3)):*
<details><summary><i>Previously, BrianFarnhill (Brian Farnhill) wrote…</i></summary><blockquote>

Same about this comment and filename too
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/466)*

**Comment by BrianFarnhill** [comment]
Just need to pull from dev to resolve the usual conflicts and this one is good to go.

---

Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/466#-:-KYVFp61Kgi6nW5YUms1:b-hrfyms)*

**Comment by BrianFarnhill** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/466)*

**Pull request merged**
