### PR TITLE
Refactor to align with test standards

### LINKED ISSUE #332: Refactor to align with test standards
When SharePointDsc began there was no formal guidance for the structure of the pester tests that are run, nor were there standards for integration testing. [These standards](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md) now exist and our solution needs to be refactored to accommodate these. 

I'll be doing the refactor of this (and have already been working on the integration tests), and am capturing this work item here to track technical debt and raise awareness of the standards. Once we have examples comited with the new test templates, then all future PRs will be expected to follow this model.

### PR DESCRIPTION
**Pull request by BrianFarnhill**
Fixes #332 

Finally and long overdue, but here is the test refactoring. In #332 we talked about adopting the common model but as per the discussion there I went with my own approach. This PR is the result of that work.

- [X] Change details added to Unreleased section of changelog.md?
- [X] Added/updated documentation and descriptions in .schema.mof files where appropriate?
- [X] Examples updated for both the single server and small farm templates in the examples folder?
- [X] New/changed code adheres to [Style Guidelines]?(https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md)?
- [X] [Unit and Integration tests](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md) created/updated where possible?

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/sharepointdsc/429)

### CODE REVIEW

**Comment by BrianFarnhill** [comment]
I see the issue with the tests here, its to do with the duplication to the module path for a copy of the module. Will go back to why I did that and then put a fix in to the appveyor build.

**Comment by BrianFarnhill** [comment]
Got the tests sorted, ready for review

**Comment by ykuijs** [comment]
I am on it!

@BrianFarnhill There are some merge conflicts. Can you make sure these are resolved.

**Comment by BrianFarnhill** [comment]
@ykuijs Merge conflicts sorted dude

**Comment by ykuijs** [comment]
Reviewed 92 of 108 files at r1, 3 of 3 files at r2, 2 of 3 files at r3.
Review status: 95 of 109 files reviewed at latest revision, 2 unresolved discussions.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPWordAutomationServiceApp/MSFT_SPWordAutomationServiceApp.psm1, line 204 at r3](https://reviewable.io:443/reviews/powershell/sharepointdsc/429#-KUThe2QwsbrImA01he5:-KUThe2R8OKS0ku1Sr2a:b68lhvy) ([raw file](https://github.com/powershell/sharepointdsc/blob/acfffd8fc94e764dd51227ce94416994476f320e/Modules/SharePointDsc/DSCResources/MSFT_SPWordAutomationServiceApp/MSFT_SPWordAutomationServiceApp.psm1#L204)):*
> ```PowerShell
>                 $returnVal =  @{ 
>                     Name = $params.Name 
>                     Ensure = "Present"
> ```

Shouldn't this be Absent?

---

*[Tests/Integration/SharePointDsc/SharePointDsc.SPManagedAccount.Tests.ps1, line 14 at r3](https://reviewable.io:443/reviews/powershell/sharepointdsc/429#-KUTj7j6kPlyYa2re8lB:-KUTj7j6kPlyYa2re8lC:b-qz39fr) ([raw file](https://github.com/powershell/sharepointdsc/blob/acfffd8fc94e764dd51227ce94416994476f320e/Tests/Integration/SharePointDsc/SharePointDsc.SPManagedAccount.Tests.ps1#L14)):*
> ```PowerShell
> 
> Describe -Tags @("PostFarm") "SPManagedAccount - Integration Tests" {
>     Context -Name "Creates new new managed accounts" {
> ```

In the Unit tests you have added the -Fixture parameter to the Context lines, which is missing in the Integration test files. Is this on purpose?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/429)*

**Comment by BrianFarnhill** [comment]
Review status: 95 of 109 files reviewed at latest revision, 2 unresolved discussions.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPWordAutomationServiceApp/MSFT_SPWordAutomationServiceApp.psm1, line 204 at r3](https://reviewable.io:443/reviews/powershell/sharepointdsc/429#-KUThe2QwsbrImA01he5:-KUTxfpIlHv-3vbdWZlQ:b4mfg7l) ([raw file](https://github.com/powershell/sharepointdsc/blob/acfffd8fc94e764dd51227ce94416994476f320e/Modules/SharePointDsc/DSCResources/MSFT_SPWordAutomationServiceApp/MSFT_SPWordAutomationServiceApp.psm1#L204)):*
<details><summary><i>Previously, ykuijs (Yorick Kuijs) wrote…</i></summary>
> Shouldn't this be Absent?
</details>
Nah - the logic here did my head in first time I looked at it as well. if the service app is not there at all (which is what would trigger it being absent) it would get picked up earlier in the get method and send out the $nullReturn object. So what this was is it was essentially saying "if it's there but you want it to be absent, I'll skip all other other properties and just send out the bare minimum" which looking at it is a bit wrong, so Ive just pushed a change in so that if it's present it returns all values, regardless of what the ensure property is, so that should make the get method make way more sense now.

---

*[Tests/Integration/SharePointDsc/SharePointDsc.SPManagedAccount.Tests.ps1, line 14 at r3](https://reviewable.io:443/reviews/powershell/sharepointdsc/429#-KUTj7j6kPlyYa2re8lB:-KUTxFq5dJPhC2WgVW0b:b-8a3wyz) ([raw file](https://github.com/powershell/sharepointdsc/blob/acfffd8fc94e764dd51227ce94416994476f320e/Tests/Integration/SharePointDsc/SharePointDsc.SPManagedAccount.Tests.ps1#L14)):*
<details><summary><i>Previously, ykuijs (Yorick Kuijs) wrote…</i></summary>
> In the Unit tests you have added the -Fixture parameter to the Context lines, which is missing in the Integration test files. Is this on purpose?
</details>
Yep, will do the integration tests as a next step. Did some fixes to these through generic find/replace fixes to tidy up syntax, but will do a full run through of these next.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/429)*

**Comment by ykuijs** [comment]
Reviewed 1 of 2 files at r4, 1 of 1 files at r5.
Review status: 97 of 109 files reviewed at latest revision, 1 unresolved discussion.

---

*[Tests/Integration/SharePointDsc/SharePointDsc.SPManagedAccount.Tests.ps1, line 14 at r3](https://reviewable.io:443/reviews/powershell/sharepointdsc/429#-KUTj7j6kPlyYa2re8lB:-KUXDHKkBZExR9Z1MYrr:b60rjpu) ([raw file](https://github.com/powershell/sharepointdsc/blob/acfffd8fc94e764dd51227ce94416994476f320e/Tests/Integration/SharePointDsc/SharePointDsc.SPManagedAccount.Tests.ps1#L14)):*
<details><summary><i>Previously, BrianFarnhill (Brian Farnhill) wrote…</i></summary>
> Yep, will do the integration tests as a next step. Did some fixes to these through generic find/replace fixes to tidy up syntax, but will do a full run through of these next.
</details>
Will you do this as part of this PR? If so, I will wait for the new commit. Else I will finish up this review so you can merge the PR.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/429)*

**Comment by BrianFarnhill** [comment]
Review status: 97 of 109 files reviewed at latest revision, 1 unresolved discussion.

---

*[Tests/Integration/SharePointDsc/SharePointDsc.SPManagedAccount.Tests.ps1, line 14 at r3](https://reviewable.io:443/reviews/powershell/sharepointdsc/429#-KUTj7j6kPlyYa2re8lB:-KUYqWuI9ETlsLUvkXFw:b-ags20c) ([raw file](https://github.com/powershell/sharepointdsc/blob/acfffd8fc94e764dd51227ce94416994476f320e/Tests/Integration/SharePointDsc/SharePointDsc.SPManagedAccount.Tests.ps1#L14)):*
<details><summary><i>Previously, ykuijs (Yorick Kuijs) wrote…</i></summary>
> Will you do this as part of this PR? If so, I will wait for the new commit. Else I will finish up this review so you can merge the PR.
</details>
Will be  a separate PR

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/429)*

**Comment by ykuijs** [comment]
:lgtm:

---

Reviewed 11 of 108 files at r1, 1 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/429#-:-KUaisd_vsyPWKFwa7vP:bnfp4nl)*

**Pull request merged**
