### PR TITLE
Various bugfixes

### PR DESCRIPTION
**Pull request by ykuijs**
Bugfixes for issues #467, #476, #477, #478, #479, #480, #482, #484, #485

- [X] Change details added to Unreleased section of changelog.md?
- [X] Added/updated documentation and descriptions in .schema.mof files where appropriate?
- [X] Examples updated for both the single server and small farm templates in the examples folder?
- [X] New/changed code adheres to [Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md)?
- [X] [Unit and Integration tests](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md) created/updated where possible?

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/sharepointdsc/491)

### CODE REVIEW

**Comment by ykuijs** [comment]
I haven't made any changes in SPAppCatalog and SPJoinFarm, however tests for these module are failing and I don't know why. The code looks fine. Any clue?

**Comment by ykuijs** [comment]
Errors most probably caused by an update to Pester. @BrianFarnhill will look into this.

**Comment by BrianFarnhill** [comment]
@ykuijs OK so I think I got it - mostly minor stuff, there was [one bug](https://github.com/pester/Pester/issues/709) I raised for the Pester guys, but I put workarounds in to our code to unblock this in #499 - I'll merge that in as soon as the tests light up green so all you need to do is pull from dev and then I can code review and close this one out.

**Comment by ykuijs** [comment]
@BrianFarnhill Tests have succeeded, so this PR is ready for review!

**Comment by BrianFarnhill** [comment]
Couple of little questions but all in all a great PR mate

---

Reviewed 10 of 11 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[CHANGELOG.md, line 8 at r2](https://reviewable.io:443/reviews/powershell/sharepointdsc/491#-KbvixSMibi4nh8WwDh-:-KbvixSMibi4nh8WwDh0:bsu7eiz) ([raw file](https://github.com/powershell/sharepointdsc/blob/9a56eb038677575df1b3acdae99b1c3f20603555/CHANGELOG.md#L8)):*
> ```Markdown
>   network locations instead of locally
> * New resources: SPFarmPropertyBag
> * Bugfix in SPSite, which wasn't returing the quota template name in a correct way (issue 467)
> ```

Can we take the issue numbers off these, we don't need them listed here (and they have no context when the readme hits the powershell gallery anyway)

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPFarmSolution/MSFT_SPFarmSolution.psm1, line 60 at r2](https://reviewable.io:443/reviews/powershell/sharepointdsc/491#-KbvjjNMuJZCiuw7R0Iu:-KbvjjNMuJZCiuw7R0Iv:b-aa02wz) ([raw file](https://github.com/powershell/sharepointdsc/blob/c875fa2ac44cc6f6bcd525c08f432a9e66481fb9/Modules/SharePointDsc/DSCResources/MSFT_SPFarmSolution/MSFT_SPFarmSolution.psm1#L60)):*
> ```PowerShell
>             $deployedWebApplications = @($solution.DeployedWebApplications `
>                                          | Select-Object -ExpandProperty Url)
>             $ContainsGlobalAssembly = $solution.ContainsGlobalAssembly
> ```

Why have we taken this out? Did we actually need this property? If so we could put it in to the schema as a read only property. Just want to double check before I let this one through

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/491#-:-KbvkprcYrX1O1Ig58zS:bahsep0)*

**Comment by ykuijs** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[CHANGELOG.md, line 8 at r2](https://reviewable.io:443/reviews/powershell/sharepointdsc/491#-KbvixSMibi4nh8WwDh-:-Kbxme33I-BdMsNRnhvH:bwlpiyp) ([raw file](https://github.com/powershell/sharepointdsc/blob/9a56eb038677575df1b3acdae99b1c3f20603555/CHANGELOG.md#L8)):*
<details><summary><i>Previously, BrianFarnhill (Brian Farnhill) wrote…</i></summary><blockquote>

Can we take the issue numbers off these, we don't need them listed here (and they have no context when the readme hits the powershell gallery anyway)
</blockquote></details>

Added these for my own administration, but forgot to take them out ;-) Now done!

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPFarmSolution/MSFT_SPFarmSolution.psm1, line 60 at r2](https://reviewable.io:443/reviews/powershell/sharepointdsc/491#-KbvjjNMuJZCiuw7R0Iu:-KbxmlJYSUO3dNfnx4-u:bj4m5k2) ([raw file](https://github.com/powershell/sharepointdsc/blob/c875fa2ac44cc6f6bcd525c08f432a9e66481fb9/Modules/SharePointDsc/DSCResources/MSFT_SPFarmSolution/MSFT_SPFarmSolution.psm1#L60)):*
<details><summary><i>Previously, BrianFarnhill (Brian Farnhill) wrote…</i></summary><blockquote>

Why have we taken this out? Did we actually need this property? If so we could put it in to the schema as a read only property. Just want to double check before I let this one through
</blockquote></details>

We need this property in the Set method. In the old version this was retrieved in the Get method and then passed to the Set method. In this version, I retrieve this info in the Set method, since that is the only place when we need the info.

We could add this to the schema, but then it would be possible to specify a GAC deployment when the solution doesn't require this or the opposite. In the current version I retrieve the info from the solution itself, so always use the correct value.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/491)*

**Comment by BrianFarnhill** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[Modules/SharePointDsc/DSCResources/MSFT_SPFarmSolution/MSFT_SPFarmSolution.psm1, line 60 at r2](https://reviewable.io:443/reviews/powershell/sharepointdsc/491#-KbvjjNMuJZCiuw7R0Iu:-Kc-mDA0VS379wbcAKNf:b8ox7wl) ([raw file](https://github.com/powershell/sharepointdsc/blob/c875fa2ac44cc6f6bcd525c08f432a9e66481fb9/Modules/SharePointDsc/DSCResources/MSFT_SPFarmSolution/MSFT_SPFarmSolution.psm1#L60)):*
<details><summary><i>Previously, ykuijs (Yorick Kuijs) wrote…</i></summary><blockquote>

We need this property in the Set method. In the old version this was retrieved in the Get method and then passed to the Set method. In this version, I retrieve this info in the Set method, since that is the only place when we need the info.

We could add this to the schema, but then it would be possible to specify a GAC deployment when the solution doesn't require this or the opposite. In the current version I retrieve the info from the solution itself, so always use the correct value.
</blockquote></details>

Happy with your approach here, thanks dude

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/491)*

**Pull request merged**
