### PR TITLE
Fix SPInstallLanguagePack to install before farm creation

### PR DESCRIPTION
**Pull request by luigilink**
Fix SPInstallLanguagePack to install before farm creation

- [x] Change details added to Unreleased section of changelog.md?
- [x] Added/updated documentation and descriptions in .schema.mof files where appropriate?
- [x] Examples updated for both the single server and small farm templates in the examples folder?
- [x] New/changed code adheres to [Style Guidelines]?(https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md)?
- [x] [Unit and Integration tests](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md) created/updated where possible?

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/sharepointdsc/413)

### CODE REVIEW

**Comment by BrianFarnhill** [comment]
@ykuijs I've reviewed the code here but would like your opinion on the new approach on this one

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[Modules/SharePointDsc/Modules/SharePointDsc.Util/SharePointDsc.Util.psm1, line 136 at r1](https://reviewable.io:443/reviews/powershell/sharepointdsc/413#-KTLcz0T93zZhV_kVntk:-KTLcz0UAYbnJrOVEFLE:b-tuyp5l) ([raw file](https://github.com/powershell/sharepointdsc/blob/bf97fe23c1e4d5f43fa15375af7199751a3a0b23/Modules/SharePointDsc/Modules/SharePointDsc.Util/SharePointDsc.Util.psm1#L136)):*
> ```PowerShell
> function Get-SPDscRegProductsInfo
> {
>     $registryLocation = Get-ChildItem HKLM:\Software\Microsoft\Windows\CurrentVersion\Uninstall
> ```

We don't use positional parameters as per style guidelines.

    Get-ChildItem -Path HKLM:\...

---

*[Modules/SharePointDsc/Modules/SharePointDsc.Util/SharePointDsc.Util.psm1, line 137 at r1](https://reviewable.io:443/reviews/powershell/sharepointdsc/413#-KTLd7sZl5mc2bLVosvl:-KTLd7sZl5mc2bLVosvm:b-uneg45) ([raw file](https://github.com/powershell/sharepointdsc/blob/bf97fe23c1e4d5f43fa15375af7199751a3a0b23/Modules/SharePointDsc/Modules/SharePointDsc.Util/SharePointDsc.Util.psm1#L137)):*
> ```PowerShell
> {
>     $registryLocation = Get-ChildItem HKLM:\Software\Microsoft\Windows\CurrentVersion\Uninstall
>     $sharePointPrograms = $registryLocation | where-object { $_.PsPath -like "*\Office*" } | foreach {Get-ItemProperty $_.PsPath}
> ```

Couple of things on this line:

* Where-Object should use the FilterScript parameter to avoid a positional parameter
* Foreach is an alias of ForEach-Object so we need to not use the alias
* Foreach-Object should use the Process parameter to avoid the script block being a positional parameter

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/413#-:-KTLdTahTAU2wiXbZG5b:bbldoop)*

**Comment by luigilink** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[Modules/SharePointDsc/Modules/SharePointDsc.Util/SharePointDsc.Util.psm1, line 136 at r1](https://reviewable.io:443/reviews/powershell/sharepointdsc/413#-KTLcz0T93zZhV_kVntk:-KTP388kGraHQ7PAUxlJ:b-896fix) ([raw file](https://github.com/powershell/sharepointdsc/blob/bf97fe23c1e4d5f43fa15375af7199751a3a0b23/Modules/SharePointDsc/Modules/SharePointDsc.Util/SharePointDsc.Util.psm1#L136)):*
<details><summary><i>Previously, BrianFarnhill (Brian Farnhill) wrote…</i></summary>
> We don't use positional parameters as per style guidelines.
> 
>     Get-ChildItem -Path HKLM:\...
</details>
Done.

---

*[Modules/SharePointDsc/Modules/SharePointDsc.Util/SharePointDsc.Util.psm1, line 137 at r1](https://reviewable.io:443/reviews/powershell/sharepointdsc/413#-KTLd7sZl5mc2bLVosvl:-KTP39GV7m_-tTVb_Rae:b-896fix) ([raw file](https://github.com/powershell/sharepointdsc/blob/bf97fe23c1e4d5f43fa15375af7199751a3a0b23/Modules/SharePointDsc/Modules/SharePointDsc.Util/SharePointDsc.Util.psm1#L137)):*
<details><summary><i>Previously, BrianFarnhill (Brian Farnhill) wrote…</i></summary>
> Couple of things on this line:
> 
> * Where-Object should use the FilterScript parameter to avoid a positional parameter
> * Foreach is an alias of ForEach-Object so we need to not use the alias
> * Foreach-Object should use the Process parameter to avoid the script block being a positional parameter
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/413)*

**Comment by BrianFarnhill** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[Modules/SharePointDsc/Modules/SharePointDsc.Util/SharePointDsc.Util.psm1, line 139 at r2](https://reviewable.io:443/reviews/powershell/sharepointdsc/413#-KTQlgXwZBwTTXZ1SVv2:-KTQlgXwZBwTTXZ1SVv3:b-sf3u1b) ([raw file](https://github.com/powershell/sharepointdsc/blob/c4211f883d29cb4de8687631bf3aa2372ff96dd6/Modules/SharePointDsc/Modules/SharePointDsc.Util/SharePointDsc.Util.psm1#L139)):*
> ```PowerShell
>     $sharePointPrograms = $registryLocation | Where-Object -FilterScript {
>          $_.PsPath -like "*\Office*" 
>     } | foreach-object -Process { Get-ItemProperty -Path $_.PsPath }
> ```

I know it's a little picky, but to meet the style guidelines can I get you to use proper casing on the foreach-object bit (so make it ForEach-Object) and drop the Get-ItemProperty bit inside those brackets to a new line like you did with the filterscript above?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/413)*

**Comment by BrianFarnhill** [comment]
:lgtm: but I really want to get confirmation from @ykuijs 's opinion on the fix before we roll it in seeing as this resource was his to own. I'll ping him directly as well and get him to validate before we roll this in. 

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/413#-:-KTkiyye09nN95Z7srxb:brgc1mg)*

**Comment by ykuijs** [comment]
A little delayed response, my apologies. I am fine with this change.

**Comment by BrianFarnhill** [comment]
@luigilink Can you do a pull from dev and resolve the merge conflict so we can put this one in?

**Comment by ykuijs** [comment]
:lgtm:

---

Reviewed 1 of 4 files at r1, 3 of 3 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/413#-:-KTyQEZRXeMr9Hgo9w3j:bnfp4nl)*

**Comment by BrianFarnhill** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/sharepointdsc/413#-:-KU-A0CfFustD4AmEEcJ:bnfp4nl)*

**Pull request merged**
